### ISSUE TITLE
markdown-tab/spaces not identing as expected

### ISSUE THREAD

**Issue by berot3** [prettier/prettier-vscode#1000]
### Summary

_When trying to format bullet-lists, it is not formatting as expected_.

setting: `prettier.tabWidth`

### Steps To Reproduce:

1.  edit *.md with bullet-list  
    example:
    ````
    - this
    - is
        - a really cool
        - example
    ````
1. set "prettier.tabWidth": **4** (instead of the deafult "2")
1. after applying prettier, it moves the text after the indented 2 points by 2 spaces.

### Expected result

    ````
    - this
    - is
        - a really cool
        - example
    ````

### Actual result

    ````
    - this
    - is
        -   a really cool
        -   example
    ````

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: newest version, but same for older ones: 1.39.1

**Prettier & Prettier Plugin Version**: newest: 2.3.0

**OS and version**: Windows 1903

**Comment by ntotten** [comment]
I can't repro this. Please provide a sample repository and steps to reproduce so I can investigate more.
