### ISSUE TITLE
Prettier miscounts line length with JSX + semi=false

### ISSUE THREAD

**Issue by patspam** [prettier/prettier-vscode#1002]
### Summary

Prettier gets confused about line length (`printWidth`) with the following JSX snippet:

```jsx
const Foo = props => (
  <div>
    xxxxxxxx xxxx xxxx xx xxx xxxxxxxxXXXXXX XXXXXXX XXXXXxxxxxxxx xxxxxxx xxxxx{" "}
  </div>
)
```

When `semi` is disabled in `.prettierrc`, eg.

```
{
  "semi": false
}
```

### Github Repository to Reproduce Issue

https://github.com/patspam/prettier-jsx-printWidth-bug

### Steps To Reproduce:

run `prettier --check repro.js` in the repro repo

### Expected result

```
Checking formatting...
repro.js
Code style issues found in the above file(s). Forgot to run Prettier?
```

### Actual result

```
Checking formatting...
All matched files use Prettier code style!
```

**Prettier & Prettier Plugin Version**:

```
prettier --version
1.18.2
```

**OS and version**:

```
uname -a
Darwin XXXXX 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
