### ISSUE TITLE
Add support for Jekyll SCSS

### ISSUE THREAD

**Issue by JerryGoyal** [prettier/prettier-vscode#1011]
Jekyll is a static site generator which has the built in support for processing [SASS](https://jekyllrb.com/docs/assets/).
SCSS files in jekyll are pretty same as other SCSS files except there are 2 lines of three dashes at beginning of each SCSS file. https://jekyllrb.com/docs/assets/
```
--- 
---
.markdown-body {
  p {
    color: blue;
  }

  &:hover {
    color: red;
  }
}
```
I added three dashes to prettier-ignore  range but didn't work as expected.
Can we please support these also in /* prettier-ignore */

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
