### ISSUE TITLE
Formatting Ruby throws "Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by jrdioko** [prettier/prettier-vscode#1017]
Issue Type: <b>Bug</b>

I'm trying to use the Prettier extension to format Ruby code. The Prettier extension works fine with TypeScript, and the `prettier` command-line tool works fine with Ruby. 

I open a new file in VSCode and give it the contents 

```
  x = 2
```

I then change the language mode to Ruby, and execute the command Format Document, it correctly removes the leading 2 spaces. However, if I create a new file in my project `app/models/test.rb` with the same contents and try to Format Document, I get a VSCode error alert that says:

```
Cannot read property 'split' of undefined
```

There is no backtrace, and I can't find any more information about what could be generating this error.

Extension version: 2.3.0
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ntotten** [comment]
Can you try version 3.0 and see if you still have this issue. You can install the 3.0 preview here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

**Comment by jrdioko** [comment]
Sure. I just upgraded to the latest (3.4.1), and now when I try to run Format Document on a ruby file (either a new file with the language set manually or a `test.rb` file saved to disk), nothing happens (the extra indent isn't removed in either case). I have my `settings.json` set up as follows:

```
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "[ruby]": {
        "editor.formatOnSave": true
    },
```

But saving the file and manually calling Format Document do nothing. Is there any way to debug and get some kind of error message?

**Comment by ntotten** [comment]
Can you share the Prettier output log when you save a file? That will help.

**Comment by jrdioko** [comment]
Thanks for the very quick response! I can't seem to figure out how to access the right log files. I've tried "Developer: Show Logs..." for "Extension Host" but I'm not seeing any relevant messages in there. Is that the right place?

**Comment by ntotten** [comment]
@jrdioko Click on the "Prettier" button on the toolbar and that will open up prettier's logs.

**Comment by jrdioko** [comment]
Ah, easier than I thought. Here is the full log after following these steps:

1. Close VSCode
2. Open VSCode
3. Open the `app/models/test.rb` file.
4. Run the command "Format Document"

Log:
```
[INFO - 3:30:13 PM] Extension Name: "prettier-vscode".
[INFO - 3:30:13 PM] Extension Version: "3.7.0".
[INFO - 3:30:13 PM] Loaded module 'prettier@1.18.2' from '/Users/me/src/project/node_modules/prettier/index.js'.
[INFO - 3:30:13 PM] Enabling prettier for languages:
[
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "json",
  "jsonc",
  "json5",
  "css",
  "postcss",
  "less",
  "scss",
  "graphql",
  "markdown",
  "mdx",
  "html",
  "vue",
  "yaml",
  "ruby"
]
[INFO - 3:30:13 PM] Enabling prettier for range supported languages:
[
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "json",
  "graphql"
]
[INFO - 3:30:17 PM] Loaded module 'prettier@1.18.2' from '/Users/me/src/project/node_modules/prettier/index.js'.
[INFO - 3:30:23 PM] Formatting /Users/me/src/project/app/models/test.rb.
[INFO - 3:30:23 PM] Loaded module 'prettier@1.18.2' from '/Users/me/src/project/node_modules/prettier/index.js'.
[INFO - 3:30:23 PM] Resolved ignore file to /Users/me/src/project/.prettierignore.
[INFO - 3:30:23 PM] File Info:
{
  "ignored": false,
  "inferredParser": "ruby"
}
[INFO - 3:30:23 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "auto",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/Users/me/src/project/app/models/test.rb",
  "parser": "ruby",
  "addTrailingCommas": false,
  "inlineConditionals": true,
  "inlineLoops": true,
  "preferHashLabels": true,
  "preferSingleQuotes": true
}
[ERROR - 3:30:23 PM] undefined
undefined
[INFO - 3:30:23 PM] Formatting completed in 86.676889ms.
```

**Comment by ntotten** [comment]
Well I need to make our error logging better obviously. I suspect this is an issue in the ruby plugin, but that’s not certain. Can you run prettier through the CLI to get the same result?

**Comment by jrdioko** [comment]
Running it through the CLI seems to work fine:

```
> cat app/models/test.rb
    x = 5
> npx prettier app/models/test.rb
x = 5
```

**Comment by jrdioko** [comment]
Today I saw a Prettier warning (that I assume was introduced in a new version) saying that my Ruby version is no longer supported. I made sure it's loading the right version of Ruby, and now formatting seems to work fine for these test cases. Feel free to close (or leave open if there's some missing logging to address here). Thanks!
