### ISSUE TITLE
How can I maintain new lines on Prettier?

### ISSUE THREAD

**Issue by Unknow-del** [prettier/prettier-vscode#1019]
Hi guys,
I have a question about a Prettier.
I have a file .css where I want to preserve the newlines that I add.
But every time I run Prettier the empty lines were compressed always in one.

How can I maintain this newlines?

Thank you for reading

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
