### ISSUE TITLE
Specify where .prettierrc is

### ISSUE THREAD

**Issue by javierguzman** [prettier/prettier-vscode#1020]
Hello all,

I have started using this plugin but I do not find how I can specify where my .prettierrc is. I know normally this is placed at the root folder but I have a config folder and I would like to tell it is there. Eslint plugin has that option but I do not see a similar one for prettier.

If there is no way to do so, I would like to request that as a new feature.

Thank you in advance and also for your all your work with this plugin.
Regards, Javier

edit: I have found that in version 3 there is a configPath option, however, my visual code only shows version up to 2.3 or so. Is this the reason why I cannot do that? If the release has been done already, is there a problem with my vs not showing the current versions?

**Comment by ntotten** [comment]
Version 3.0 is in perview. You can install it here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

I expect it will be in the stable release in the next week or so.

**Comment by javierguzman** [comment]
Thanks Nathan! :) I will wait then
