### ISSUE TITLE
Range ignore not supported

### ISSUE THREAD

**Issue by Walther** [prettier/prettier-vscode#1023]
### Summary

Prettier has a feature for ranged ignores  <https://prettier.io/docs/en/ignore.html#range-ignore> since v1.12.0+.

### Steps To Reproduce:

CSS file:

```
/* prettier-ignore-start */
/* from pandoc syntax highlighting  */
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #60a0b0; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; } /* Comment */
code span.cv { color: #60a0b0; } /* CommentVar */
code span.do { color: #ba2121; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; } /* Information */
code span.kw { color: #007020; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; } /* Warning */
/* prettier-ignore-end */
```

### Expected result

prettier-vscode does not reformat the section defined with `prettier-ignore-start` and `prettier-ignore-end`

### Actual result

prettier-vscode reformats all the lines.

### Additional information

![prettier-vscode](https://user-images.githubusercontent.com/2943750/68535687-fa4e7680-034e-11ea-8e8e-91ba0d1fcf56.gif)

**VS Code Version**:

```
code --version
1.39.2
6ab598523be7a800d7f3eb4d92d7ab9a66069390
x64
```

**Prettier & Prettier Plugin Version**:

```
prettier --version
1.19.1
```

Plugin version `2.3.0`

**OS and version**:

macOS Mojave 10.14.6 (18G103)

**Comment by kachkaev** [comment]
This issue can be [reproduced in Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgA4Cc4wwCWcuAtEQOZQT5kDOMAhrjJuqgDpQaYBmuCAFscTKABMIYTPQCesJgA9MACyoqANuuJRKmdlyiRxcGdjEA6JhszBMkDbSSYAxHz4AGLx4DcmAL6YvACCGqRsHNzGpvTmUFZQtvYQjrjOLgBsHkweAEa+AUFYwVA0zMTQBlEQJmaWTGx2Dk6uAOziAJweAEwdfoEhhLhEuQCu8FVGNTFxFrmJTSktLgAs2R6tBQNYAEJM9HAAcpPRdfFjSduYO6NEGjAAkomRU7WxlmB8Sc1prl6b3S2RUwAGFoDBBBoAGKOADuJ2mZwsYBU3yWv1WG3W-WBIJULARb1mYAWyVS6QAHBTvEDeGCoIwxBFDKd3vFIGjya4sjl8ji6cIhAhmdUiR8AG6c5Y8vK0rBgoRC2AANQJL1Zs0kUoxuSY3QAjAb+VgACJSUZK8pESrqxFsiziRpk5ZdQFeY2YE0NJgAFVk2FMtrF8XEksWXMxOU2HpNcDAqpsQZmllI2vS7hpHoAorhBLhCcn4nBlHYrlnFPAGdbniy7bM+DZw8s1lG5ZgYRAGgWkXxRmm-hluhTWnAPVDRkYKjXRYWLEQRKXgQ8hNhaCLXrOiKSfukZXzCrwnnxaEIGtXu-aANbwpsY-49NsAaTgslhtHEF9mEGw-cyGX--4egA8gGuANLQn6WBATo7n8WKAsBMAqKmSZItgP63ukuRgK0ORtgACvgeBSHA9D0BBqH2vQ0iYa4aybDkHoAMoBmARDWHiaq1sGFhkb+uS5P+VLMax7EaExEJbnolGzIwv70diB5YBJwy6JB8Tikwv76h0+qtK0YAeqqwxMLkYTqRY4r0PJWKMUpmDKqQurEEIKlSRZsJabRmTrPuVwAOosFA7kvLweAEMQpAUNQtBwGQCAfi8IAADQgN+U70MgoAsIIsL4SwCCZSgTDihARDiClIC5GBYCXgQLFMGxujIBCoxwKlKgwEIGj+Wo8DvGAcBMYVRDEOKo2yMg4BkZVW4HKwhFMJQp7IHw1gHKlABW9CKDsNV1TATFMEKAAyW5wKt63tSA22KExUlhAAiqM0EXUga0aBtIDmLg81TWAM2pXgW4wP55VIcg1JA4IBz+WB2BTeF83ihdqUAI4vfAhHfkVID7GQUBwHAJgVal+AY0Q+CLctTCXZ910HEIRAtbgbWpfQD1wM9r1019zC5GDjoqMg3SpRCTB3FJCorSgNCE5VowHD6plFR9X3im1TwmLATFgMM2AwCU4gSbIYS83A-j+EAA), which means that it's not specific to VSCode. As far as the [core docs say](https://prettier.io/docs/en/ignore.html#css), Prettier does not support ignoring ranges in CSS. You can add the entire file to `.prettierignore` as a workaround.

**Comment by Walther** [comment]
Ah, my bad for misreading, headings seem to imply the ranged ignore only exists for markdown. That could become a feature request 🤔 
Thanks for the quick response!
