### ISSUE TITLE
You have legacy settings in your VS Code config

### ISSUE THREAD

**Issue by ReTWi** [prettier/prettier-vscode#1029]
Suddenly prettier stopped working with error:

`You have legacy settings in your VS Code config. They are being ignored Would you like to migrate them to '.prettierrc'?.`

Install/reinstall doesn't help.

In project i only have prettier.config.js:
`module.exports = {
  printWidth: 140,
  singleQuote: true,
  jsxSingleQuote: true,
  semi: false
}
`

**UPDATE**
I was able to partially solve this by installing prettier as dependency and updating prettier.config.js to .prettierrc:
```
{
  "printWidth": 140,
  "singleQuote": true,
  "jsxSingleQuote": true,
  "semi": false
}
```

Problem now is that with following project structure:
```
dist
src
package.json
```

I get the same error if i try to "pretty" anything inside folders dist/src, when top level "pretting" works fine.

**Comment by ntotten** [comment]
That error doesn't stop it from working it just is telling you that somewhere you have legacy configuration settings. See: https://github.com/prettier/prettier-vscode/blob/master/README.md#error-messages

**Comment by ntotten** [comment]
Can you provide a same project to help repro the issue? I am able to run everything correctly when I have `package.json` at the root and have subfolders with source.

**Comment by ReTWi** [comment]
@ntotten thanks, also delete all prettier oprions from vscode setting, now it's fine.
