### ISSUE TITLE
Fix "You have legacy settings in your VS Code config" notification

### ISSUE THREAD

**Issue by PabloSzx** [prettier/prettier-vscode#1030]
In the last update every time that I format a document (every time I save a file) this notification appears and I can't do anything about it, my settings don't have any prettier configurations and when I press "Migrate Config" creates a file but does nothing to fix the problem.

I'd like this error to be fixed, or at least the notification to just appear once, not every time I format a file, the notification doesn't even disappear itself after some time!, I have to manually press X

![notification](https://i.imgur.com/BzLporg.png)

**Comment by Limonische** [comment]
I have the same issue, but i have my prettier config in a dedicated prettier.config.js file.

**Comment by MatthewPorter31** [comment]
Same here, tried reinstalling the extension but still showing up.

**Comment by ntotten** [comment]
You have a legacy prettier setting in your project or global config. See: https://github.com/prettier/prettier-vscode#error-messages

I will add logging to include more information about where the setting was found.

**Comment by ntotten** [comment]
Version 3.2.1 adds logging and a button on the message to show the logs. The logs will tell you what setting was found and where it was found.

I also changed the dialogs to warnings instead of errors.

**Comment by SkeLLLa** [comment]
It needs a way to disable this notification, cause in many cases it may be useless. It's more than enough to show it one time. If user wants to keep those settings - then let it be. For example if someone uses synced config with different versions of this extension (e.g. v2), those legacy staff become needed.

**Comment by R3vid** [comment]
Same Error here. After removing "prettier.singleQuote" line form setting file and puting it in .prettierrc config file these setting ist ignored. Where should i put the .prettierrc file?
