### ISSUE TITLE
Project .prettierrc does not work when global config("prettier.configPath") is set

### ISSUE THREAD

**Issue by XiongAmao** [prettier/prettier-vscode#1033]
### Summary

Project .prettierrc does not work when global config("prettier.configPath") is set.
Is the global configuration higher priority?

### Expected result

I want to use the global config when there is no prettier config in the project root directory.
Then use local config on the project root when there is .prettierrc.

### Actual result

Local config does not work.

### Additional information

**VS Code Version**: 1.40.0

**Prettier-vscode**: 3.2.0  

**OS and version**: 

OS: Windows_NT x64 10.0.18362

**Comment by ntotten** [comment]
This is by design. If you set the configPath, then it will be used. You should be able to override the global setting though by setting the `prettier.configPath` to null in your workspace config `.vscode/settings.json` if you want to revert back to the project config.
