### ISSUE TITLE
prettier key in package.json not allowing a string value

### ISSUE THREAD

**Issue by mskelton** [prettier/prettier-vscode#1034]
### Summary

Setting `prettier` key in package.json to a string causes a warning when it is valid syntax according to [prettier.io](https://prettier.io/docs/en/configuration.html#sharing-configurations).

### Github Repository to Reproduce Issue

https://github.com/mskelton/prettier-bug

### Steps To Reproduce:

1. Install the plugin
1. Add a `prettier` key to package.json with a string value equal to the name of the shared prettier config (i.e. `my-prettier-config`)
1. Notice warning in package.json

### Expected result

`prettier` key in package.json should allow a string.

### Actual result

`prettier` key in package.json only allows an object

### Additional information

**VS Code Version**:  1.40.0
**Prettier & Prettier Plugin Version**: 3.2.1
**OS and version**: macOS Catalina

**Comment by ntotten** [comment]
A similar issues was reported here #965. I am fairly sure that this issue is with prettier itself rather than the extension. I'll dig into this asap though.

**Comment by mskelton** [comment]
That seems to be a different issue.  In my case, prettier reformats the code either through VS Code or the command line, but it is displaying the warning in package.json that something isn't correct even though it is.  I should note that this only happened after updating to v3 as v2 didn't display the warning in package.json.

**Comment by ntotten** [comment]
I cannot reproduce this. I cloned the repo, ran yarn, then opened it and everything worked as expected.

![image](https://user-images.githubusercontent.com/282782/70850820-8d059800-1e5c-11ea-9a41-e52feaa3e678.png)

Log shows:

```
["INFO" - 10:27:48 AM] Extension Name: "prettier-vscode".
["INFO" - 10:27:48 AM] Extension Version: "3.13.0".
["INFO" - 10:27:48 AM] Loaded module 'prettier@1.19.1' from '/Users/ntotten/dev/temp/prettier-bug/node_modules/prettier/index.js'
["INFO" - 10:27:48 AM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 10:27:48 AM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 10:27:49 AM] Loaded module 'prettier@1.19.1' from '/Users/ntotten/dev/temp/prettier-bug/node_modules/prettier/index.js'
["INFO" - 10:27:50 AM] Formatting /Users/ntotten/dev/temp/prettier-bug/index.js
["INFO" - 10:27:50 AM] Loaded module 'prettier@1.19.1' from '/Users/ntotten/dev/temp/prettier-bug/node_modules/prettier/index.js'
["INFO" - 10:27:50 AM] Using ignore file (if present) at /Users/ntotten/dev/temp/prettier-bug/.prettierignore
["INFO" - 10:27:50 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 10:27:50 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:27:50 AM] Prettier Options:
{
  "filepath": "/Users/ntotten/dev/temp/prettier-bug/index.js",
  "parser": "babel",
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5"
}
["INFO" - 10:27:50 AM] Formatting completed in 465.497956ms.
["INFO" - 10:28:14 AM] Loaded module 'prettier@1.19.1' from '/Users/ntotten/dev/temp/prettier-bug/node_modules/prettier/index.js'
```

Notice the config used matches your custom config. 

I also don't see any warnings on the `package.json`. 

![image](https://user-images.githubusercontent.com/282782/70850854-d48c2400-1e5c-11ea-824f-c71f79f7e092.png)


I am using VS Code 1.41.0, Prettier Extension 3.13.0. Please reopen if you can provide more details. Try yto run vscode without any extensions but prettier installed. It is possible another extension is running something that conflicts.
