### ISSUE TITLE
Settings globally?

### ISSUE THREAD

**Issue by kanlukasz** [prettier/prettier-vscode#1037]
So after Prettier 3 there is no option to use settings globally?
I don't like when something create additional files in my project folder 😥
Is there any solution to create one global file with Prettier settings?
Maybe somewhere in VSCode install folder?

**Comment by Ciantic** [comment]
This is bad for me too!

I've used global settings for years (?), and there is like ~60 or so projects that I don't want `.prettierrc`.

**Comment by MRMokwa** [comment]
> 
> 
> This is bad for me too!
> 
> I've used global settings for years (?), and there is like ~60 or so projects that I don't want `.prettierrc`. Code I do is mostly throwaway WP garbage, with LESS and PHP and HTML, I don't want any of the `.prettierrc` files there because the prettier in that case is just a helper for myself.
> 
> Please, bring back the global settings.
> 
> Solution is to install 2.3.0, like this:
> 
> ![image](https://user-images.githubusercontent.com/64731/68668194-50d6d300-0550-11ea-96fb-56942827b570.png)
> 
> Then choose 2.3.0

Thank you, this saved me

**Comment by ntotten** [comment]
You can set the `prettier.configPath` globally and point it to a shared configuration file. https://github.com/prettier/prettier-vscode#prettierconfigpath

**Comment by Ciantic** [comment]
@ntotten one more thing, if it's that easy, the little bubble suggest migrating should say it. The bubble *gives an impression* that you must now save it to all project directories individually, why else would other people were here too if it's just matter of setting single config.

**Comment by domemvs** [comment]
> You can set the `prettier.configPath` globally and point it to a shared configuration file.

Do local project-based .prettierrcs still overwrite this then? If not, this is, unfortunately, useless!

**Comment by CiGit** [comment]
you can put a config file at the root of all your projects without using `prettier.configPath` (null)
/
...
- MyProjects
  - .prettierrc
  - ProjectA
  - ProjectB
  - Project with prettier
    - .prettierrc
  - ...

It can even be `/.prettierrc` I think

A config file is found from the file being processed and up the file system

This wouldn't work if your are developing inside a Container/VM/whatever :smile:

**Comment by kanlukasz** [comment]
` "prettier.configPath": "c:\\Users\\xxxxx\\.vscode\\.prettierrc"` works fine.
Thank you for advices

**Comment by cmckni3** [comment]
I removed my global settings from VS Code but now files that haven't been saved don't format using the settings from `~/.prettierrc`.

**Comment by XiongAmao** [comment]
> I removed my global settings from VS Code but now files that haven't been saved don't format using the settings from `~/.prettierrc`.

@ntotten 
I got the same problem. I didn't set any vscode prettier config in `settings.json`.  , and `~/.prettierrc`(i try`~/.prettierrc.js`/ `~/.prettierrc.config.js`) doesn't work. It seems to be overwritten by the default vscode prettier config in 3.5.0.

When I format code manually: 

![image.png](https://i.loli.net/2019/11/14/MWG8m9ACyuX3YPs.png)
