### ISSUE TITLE
"You have legacy settings in your VS Code config" with no legacy settings

### ISSUE THREAD

**Issue by andyhmltn** [prettier/prettier-vscode#1038]
### Summary

After updating VS code today, I now get an error every time I save a JS file:

'You have legacy settings in your VS Code config. They are being ignored Would you like to migrate them to '.prettierrc'?.'

I've removed any mention of prettier from my settings, but still get the same error.

### Steps To Reproduce:

My VSCode settings file is as follows:

```
{
  "window.zoomLevel": 2,
  "editor.parameterHints.enabled": false,
  "workbench.editor.enablePreview": false,
  "files.insertFinalNewline": true,
  "workbench.colorTheme": "Horizon Default",
  "breadcrumbs.enabled": false,
  "workbench.iconTheme": "vs-nomo-dark",
  "workbench.statusBar.visible": true,
  "editor.tabSize": 2,
  "editor.gotoLocation.multiple": "goto",
  "javascript.updateImportsOnFileMove.enabled": "never",
  "files.associations": {
    "*.ts": "typescriptreact"
  },
  "emmet.triggerExpansionOnTab": true,
  "javascript.implicitProjectConfig.checkJs": true,
  "workbench.activityBar.visible": true,
  "eslint.alwaysShowStatus": true,
  "eslint.validate": [
    {
      "language": "typescript",
      "autoFix": true
    },
    {
      "language": "typescriptreact",
      "autoFix": true
    }
  ],
  "vsicons.dontShowNewVersionMessage": true,
  "editor.stablePeek": true,
  "editor.minimap.enabled": true,
  "editor.detectIndentation": false,
  "editor.formatOnSave": true,
}
```

### Expected result

I should be able to use prettier, without popups, as I have done for the past few months.

### Actual result

I receive a popup alerting me to legacy settings that don't exist. The 'migrate config' option just fills my prettierrc with a bunch of settings that I didn't make in the first place and now I have to turn off prettier all together to get some work done.

### Additional information

VSCode version: 1.40.0

I feel like forcing this popup to display on every save, without giving the user the option to at least silence it, is a bit much.

**Comment by ntotten** [comment]
I will add a setting to hide the warning. However, the prettier settings are there somewhere. If you click the "View Log" button you will see where it found the settings. They may be in your global or your project config.

**Comment by avmaktslave** [comment]
also, integration with stylelint was broken

**Comment by ntotten** [comment]
@avmaktslave Can you open a separate bug on stylelint. Also be sure to see the instructions here in the advanced section: https://github.com/prettier/prettier-vscode#vs-code-eslint-and-tslint-integration

You need to install stylelint in your project now as we had too many bugs with shipping it with the extnsion.

**Comment by ntotten** [comment]
Tracking the option to dismiss/hide the warnings here: #1039

**Comment by andyhmltn** [comment]
Thank you @ntotten 👍

**Comment by jscheel** [comment]
I'm confused as to what happened. Has something changed so that the prettier version in my project can no longer be used?

**Comment by ntotten** [comment]
This should no longer be an issue. The settings change was reverted so no user actin is required.
