### ISSUE TITLE
Format only the file being saved

### ISSUE THREAD

**Issue by Ciantic** [prettier/prettier-vscode#1040]
With 3.2 series the plugin works differently, it will now format *all* files when I save.

I don't trust prettier enough to format all files each time I save, and besides that, I want to migrate project files individually as I save.

With 2.x series it used to follow the VSCode setting "Format on Save" so that each time I saved it formatted only that file. Is it possible to get that behavior back?

**Comment by ntotten** [comment]
This shouldn't be the case and I haven't seen this. Can you provide more details on how this is happening? Include the logs of prettier and if possible a sample github repo that I can use to duplicate this.

**Comment by Ciantic** [comment]
I can't reproduce this, closing unless I find it again.
