### ISSUE TITLE
Different format on each save attempt with ESLint integration

### ISSUE THREAD

**Issue by otanriverdi** [prettier/prettier-vscode#1041]
Since the last update, I had to remove the legacy eslint integration option. Now, the file formats with different rules each time I save and the plugin is basically unusable for me.

I can save the file over and over again and it switches rules constantly.

**Comment by ntotten** [comment]
Have you installed the estlint-prettier module locally? https://github.com/prettier/prettier-vscode#vs-code-eslint-and-tslint-integration

I am not sure why it would be running differently each time, that is very odd. Can you provide the output logs of prettier and if possible a simple github repo I can use to duplicate this behavior?

**Comment by otanriverdi** [comment]
For those having the same issue, the popup window on migration to the new version on VSCode links to the new Github readme which instructs you to add these settings for the ESLint/TSLint integration.

```
"eslint.autoFixOnSave": true,
"editor.codeActionsOnSave": {
  "source.fixAll.tslint": true
 }
```

The issue is, the docs previously recommended using the setting;

`"editor.formatOnSave": true`

Which seems to conflict with new settings and causing the issue that I stated above.

Removing this setting fixed the issue for me. Remove the issue as you please and thank you!
