### ISSUE TITLE
Using prettierPath says i'm using an outdated version of prettier but it's prettier@1.19.1 latest

### ISSUE THREAD

**Issue by esetnik** [prettier/prettier-vscode#1042]
### Summary

Your project is configured to use an outdated version of prettier. You may encounter issues. It is recommended you upgrade to the latest version of prettier.

```json
  "prettier.prettierPath": "./node_modules/.bin/prettier"
```

```bash
❯ ~/work/project/node_modules/.bin/prettier -v
1.19.1
```

```

[INFO - 10:19:39 AM] Formatting ~/work/project/frontend/src/containers/EditSiteContainer.js.
[INFO - 10:19:39 AM] Loaded module 'prettier@undefined' from '~/work/project/node_modules/.bin/prettier'.
[ERROR - 10:19:39 AM] Outdated version of prettier installed. Falling back to bundled version of prettier.
```

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  Use `prettierPath` to point to locally installed prettier

### Expected result

Since 1.19.1 is the latest version, I expect prettier-vscode to use it

### Actual result

Falls back to bundled version of prettier

### Additional information

**VS Code Version**:
```
1.40.0
86405ea23e3937316009fc27c9361deee66ffbf5
x64
```

**Prettier & Prettier Plugin Version**:
```
prettier@1.19.1
prettier-vscode@3.3.0

**OS and version**:
macOS 10.15.1

**Comment by ntotten** [comment]
Try setting the option to ` "prettier.prettierPath": "./node_modules/prettier"` rather than the bin location.

**Comment by esetnik** [comment]
That seems to have worked although the log output is a bit strange. I'm not sure what it means by `No path provided, using bundled prettier.`

```
[INFO - 11:24:36 AM] Extension Name: esbenp.prettier-vscode.
[INFO - 11:24:36 AM] Extension Version: 0.0.0.
[INFO - 11:24:36 AM] No path provided, using bundled prettier.
[INFO - 11:24:36 AM] No path provided, using bundled prettier.
[INFO - 11:24:36 AM] Loaded module 'prettier@1.19.1' from '/Users/user/work/project/node_modules/prettier'.
```

**Comment by ntotten** [comment]
@esetnik That is by design. That comes from the language registration part that happens before the module is loaded. I'll update the log messages to make that less confusing. Good feedback.

**Comment by ntotten** [comment]
The latest update removes that unnecessary logging.
