### ISSUE TITLE
extension setting no longer valid

### ISSUE THREAD

**Issue by phpSing** [prettier/prettier-vscode#1046]
Issue Type: <b>Bug</b>

on 12th Nov 2019, everything was ok

today 13th Nov 2019, I re-open the editor, change some code in the file, format on save, all the single quotes become double quotes, and I go to the extension setting, the single quote setting is disabled and ask me to use extension setting instead, but I am looking at the extension setting, so I go to the global setting again, set the quote to single. it is still not working. I am so frustrated now as I need to push code to remote. the format just fail on save. I do not want double quotes.

did anything happened between 12th & 13th Nov 2019? It is really annoying, if anything changed, should not create resistence to user experience.

Extension version: 3.2.1
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 11|
|Memory (System)|8.00GB (0.41GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by phpSing** [comment]
use configuration file instead to override. but this create a internal issue, if 3-4 developers on the project, we need extra time to align the format.

**Comment by RajThakar70** [comment]
having the same issue
