### ISSUE TITLE
Configuration setting vueIndentScriptAndStyle is not working

### ISSUE THREAD

**Issue by anoop-ananthan** [prettier/prettier-vscode#1048]
### Summary
The configuration `"vueIndentScriptAndStyle": false` is not taking any effect on format of vue file.

An update was added to the prettier automatically and codes were formatted in a way that I did not configure. So I checked the documentation and as per the [link](https://prettier.io/docs/en/options.html#vue-files-script-and-style-tags-indentation) I found,  added this to `.prettierrc`

### Github Repository to Reproduce Issue
There is no source code as it is the changes on the configuration file `.prettierrc`
```
{
    "printWidth": 100,
    "semi": false,
    "singleQuote": true,
    "tabWidth": 4,
    "trailingComma": "all",
    "jsxBracketSameLine": true,
    "arrowParens": "avoid",
    "htmlWhitespaceSensitivity": "strict",
    "vueIndentScriptAndStyle": false
}
```

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  Install/update to v3.3.5
1.  Change configuration as shown above 
1. Format a **Vue** file

### Expected result

The expected result is style and script elements keep their indentations. Screenshot is attached

### Actual result

style and script elements lose their indentations.

### Additional information

**Script Indent**
Even though removing this intending is nice & useful, the changes introduced in a project where large no: of people are working is messing up code-review and stuff. So it'd be a lot better if it could be controlled using configuration.
![image](https://user-images.githubusercontent.com/40450822/68735742-91902400-0604-11ea-80cc-f6631e28cabe.png)

**Style Indent**
**I would prefer to keep both `script` and `style` configuration different**. Personally I want to have an indent on the style contents.
![image](https://user-images.githubusercontent.com/40450822/68735892-1f6c0f00-0605-11ea-8b5a-79eed05de23e.png)

**VS Code Version**:
v1.40.0
**Prettier & Prettier Plugin Version**:
v3.3.5
**OS and version**:
Ubutntu 16

Thank you for the amazing extension.

**Comment by ntotten** [comment]
Can you post the output log of prettier?

**Comment by anoop-ananthan** [comment]
Reverted back to old version.

**Comment by AbdelElrafa** [comment]
Can you please reopen this issues? Changing versions doesn't fix it. It's still broken.

**Comment by ntotten** [comment]
Do you have prettier installed locally? If so it needs to be version 1.19 or above. This might be something we need to warn about. Prettier has a similar issue: https://github.com/prettier/prettier/issues/6887

If that isn't the problem, please share your prettier output logs. You can access them by clicking the Prettier button in the bottom toolbar.

**Comment by anoop-ananthan** [comment]
1) Prettier is not installed locally
2) The following is the log out put
```
[INFO - 7:00:40 pm] Prettier Options:
{
  "filepath": "/home/anoop/coding/projects/tm-web/src/components/action/AddActionPerson.vue",
  "parser": "vue",
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "lf",
  "printWidth": 100,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all",
  "jsxBracketSameLine": true,
  "arrowParens": "avoid",
  "htmlWhitespaceSensitivity": "strict",
  "vueIndentScriptAndStyle": false
}
[INFO - 7:00:40 pm] Formatting completed in 65.302614ms.
```

**Comment by anoop-ananthan** [comment]
Hi, prettier was not installed locally. 

It seems weird, I had to install node.js due to some other reason and reinstalled vscode and all the extensions and **it is working correctly**

**Comment by anoop-ananthan** [comment]
This is happening again:

```
["INFO" - 1:57:41 pm] Formatting /home/anoop/coding/projects/tm-web/src/components/dashboard/PostStatsCardView.vue
["INFO" - 1:57:41 pm] Using ignore file (if present) at /home/anoop/coding/projects/tm-web/.prettierignore
["INFO" - 1:57:41 pm] Loaded module 'prettier@1.18.2' from '/home/anoop/coding/projects/tm-web/node_modules/prettier/index.js'
["INFO" - 1:57:41 pm] File Info:
{
  "ignored": false,
  "inferredParser": "vue"
}
["INFO" - 1:57:41 pm] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 1:57:41 pm] Prettier Options:
{
  "filepath": "/home/anoop/coding/projects/tm-web/src/components/dashboard/PostStatsCardView.vue",
  "parser": "vue",
  "printWidth": 100,
  "semi": false,
  "singleQuote": true,
  "tabWidth": 4,
  "trailingComma": "all",
  "jsxBracketSameLine": true,
  "arrowParens": "avoid",
  "htmlWhitespaceSensitivity": "css",
  "vueIndentScriptAndStyle": true
}
["INFO" - 1:57:41 pm] Formatting completed in 421.477212ms.
```

`.prettierrc`
```
{
    "printWidth": 100,
    "semi": false,
    "singleQuote": true,
    "tabWidth": 4,
    "trailingComma": "all",
    "jsxBracketSameLine": true,
    "arrowParens": "avoid",
    "htmlWhitespaceSensitivity": "css",
    "vueIndentScriptAndStyle": true
}
```

### Output
![Uploading image.png…]()

**Comment by ntotten** [comment]
Please provide a sample repo I can use to reproduce this issue. See: https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo
