### ISSUE TITLE
Extension host terminated vscode 1.40.0

### ISSUE THREAD

**Issue by MareikeTaeubner** [prettier/prettier-vscode#1050]
### Summary

VSCode extension host crashes on startup if prettier code formatter extension is enabled (disabling vscode core functions like git integration).

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  Disable all vscode extensions.
1.  open vscode window -> it should open without issue
1. enable prettier code formatter extension -> the extension host crashes
1. open the vscode window anew -> the extension host crashes
1. disable prettier extension again and restart extension host -> restart successful

### Expected result

The VSCode window opens without error.

### Actual result

VSCode extension host crashes - disabling not just prettier but core functions (because vscode handles that badly :( ).

### Additional information

Since VSCode does not log which extension crashed I am not 100% sure prettier is at fault here, but with only prettier activated it is an educated guess.

Error message after Startup:
![extensionHostWindow](https://user-images.githubusercontent.com/4388257/68743305-6f8da600-05f2-11ea-87e5-191c2b00bf24.png)

Console error messages:
![prettierCrash](https://user-images.githubusercontent.com/4388257/68743190-2e959180-05f2-11ea-85f6-a7b1fa190a6e.png)

**VS Code Version**: 
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Datum: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
Betriebssystem: Windows_NT x64 10.0.18362

**Prettier & Prettier Plugin Version**: 
Plugin: 3.3.5
Prettier: 1.19.1 (but crashes also without prettier locally installed)

**OS and version**: Windows 10 Pro 10.0.18362 Build 18362

**Comment by MareikeTaeubner** [comment]
It does seem to be a problem with vscode itself (https://github.com/microsoft/vscode/issues/84803). Sorry for mistakenly reporting here :(

**Comment by ntotten** [comment]
No problem. Thanks for following up!
