### ISSUE TITLE
Extension 'prettier.prettier-vscode' is configured as formatter but not available. Select a different default formatter to continue.

### ISSUE THREAD

**Issue by David-Else** [prettier/prettier-vscode#1052]
After updating to V3 of plugin, altering all my references to `prettier.prettier-vscode`, and moving preferences into `package.json` now after an update it says `Extension 'prettier.prettier-vscode' is configured as formatter but not available. Select a different default formatter to continue.`

**Comment by ntotten** [comment]
I am going to need logs or something to figure out what is going on. Please provide clear repro steps, a sample repo, and output logs.

**Comment by David-Else** [comment]
@ntotten **Sorry**, I did not mean to be a jerk!

I have just spent 2 days reporting bugs to various projects non stop as they all stopped working at once. It has been a nightmare. I am going to just give up now and try to get back to what I was meant to be doing 2 days ago. I literally just worked for free for 2 days chasing open source bugs 9-5, hope you understand the frustration, I am really grateful for all the work you have done! Thanks!

**Comment by ntotten** [comment]
Understand, I know that can be frustrating. Apologies for the inconvenience around the extension. I did revert the big change around configuration so you can use the previous settings. Lots of feedback on that and it was clear that it was too disruptive of a change. 

I am going to continue chasing bugs down and i am confident we'll get these issues ironed out soon. This release made a lot of underlying changes that will be good in the long run. I closed approximately 100 outstanding bugs through these changes, but obviously in the process introduced a few. Please do open a new issue when you have a chance. I will try to figure out what is going on with your other open issue soon - after I am done with my day job. :)

**Comment by CiGit** [comment]
prettier.prettier-vscode is an alternate reality extension. (v3 test version)
Did you remove it and installed esbenp.prettier-vscode instead ? In which case you would have to rename your default formatter

**Comment by ntotten** [comment]
Good point @CiGit. I didnt even notice that. They are currently the same version, but you will need to use one or the other and have your settings match.

**Comment by David-Else** [comment]
I removed `esbenp.prettier-vscode` and installed `prettier.prettier-vscode`. Now after an update VS Code does not recognize `prettier.prettier-vscode` and allows me to select `esbenp.prettier-vscode` instead which seems to have appeared.

I publish a Fedora install script and changed the package reference to:
```
    code_extensions=(
        prettier.prettier-vscode
   )
```
Was this the wrong thing to do, should I change it back to `esbenp.prettier-vscode`? Thanks.

**Comment by andreasmarkussen** [comment]
I was missing a global prettier install, and I forgot after reinstalling my machine

    npm install --global prettier
