### ISSUE TITLE
prettier.requireConfig has deprecation warning on it

### ISSUE THREAD

**Issue by AndrewRayCode** [prettier/prettier-vscode#1056]
<img width="1436" alt="Screen Shot 2019-11-14 at 3 44 51 PM" src="https://user-images.githubusercontent.com/79215/68905348-c203bb00-06f5-11ea-9bd8-fc7f15dc0bc1.png">

This setting shows the deprecation message:

> This extension no longer supports setting Prettier options using VS Code configuration. Use the prettier configuration file instead. 

However this setting is both still in the readme and also not something you can configure through prettier, as far as I'm aware. It seems like a catch 22 that you would put "only run if there's a prettier config file" inside the prettier config file itself? I assume this message is showing in error?

**Comment by ntotten** [comment]
This is a mistake. I will fix in the next release.
