### ISSUE TITLE
"singleQuote": true , but still it's not working, exchanges always to double qoutes

### ISSUE THREAD

**Issue by Maryary94** [prettier/prettier-vscode#1060]
So basically I tried most of the thing here in GitHub, but still the "singleQuote": true, doesn't work.
PS: is formatOnSave

Normally my  .prettierrc is like this:
![Screenshot_2](https://user-images.githubusercontent.com/33401848/68943128-35630680-07a2-11ea-9474-153206bc3e55.png)

and even I tried to do this:
(it seemed a redundancy but still, I tried)
![Screenshot_1](https://user-images.githubusercontent.com/33401848/68943222-78bd7500-07a2-11ea-942d-9780ec019710.png)

And even so, it's not working (example):
![image](https://user-images.githubusercontent.com/33401848/68943238-8c68db80-07a2-11ea-9084-7bc1bf29478e.png)

Any idea to resolve?

**Comment by BendingBender** [comment]
Same problem here. Seems to happen since the last update.

**Comment by BendingBender** [comment]
I have a similar problem but sith `bracketSpacing`. The default [according to docs](https://prettier.io/docs/en/options.html#bracket-spacing) is `true`. I didn't have it specified in `.eslintrc`. Since the current release prettier-vscode started to format my files as if it was set to `false`. Specifying it in the workspace settings didn't help. I hat to add `"bracketSpacing": true` to my `.eslintrc` for prettier-vscode to format my files with `bracketSpacing`.

**Comment by Veraoliveira1** [comment]
When I added "bracketSpacing": true, this appeared:
![image](https://user-images.githubusercontent.com/33401848/68945694-deacfb00-07a8-11ea-9bbb-55e743a280df.png)

**Comment by ntotten** [comment]
@Maryary94 Please click on the Prettier icon in the toolbar to show the prettier logs and provide the full logs. That will help track down why the the format isn't being pickedup. However, this seems very odd:

![image](https://user-images.githubusercontent.com/282782/69087523-be817400-0a14-11ea-8a3b-099dfd74c368.png)

Why is the path in your `node_modules`? Prettier will only detect `.prettierrc` files that below the file being formatted. It looks like your file is at this path:

![image](https://user-images.githubusercontent.com/282782/69087769-dc4ed900-0a14-11ea-9309-b3705c97d7d8.png)

Regarding the `Failed to load module issue`. You need to run `npm install` if you are trying to load prettier from a `package.json`

**Comment by riseforest** [comment]
Have similar issue, I use vetur with pettier format my vscode.
The configuration is :
vuetur.formant.defaultFormmaterOptions: {
 prettier: {
printWIdth: 80
singleQuote: ture
}
}

It works fine on 3.7 but not work from 3.8

**Comment by parkjangwon** [comment]
@riseforest  it is working... thankyou!
