### ISSUE TITLE
格式化失败

### ISSUE THREAD

**Issue by hesichuan** [prettier/prettier-vscode#1061]
Issue Type: <b>Bug</b>

开发vue项目时，在vue文件中保存后提示项目使用的prettier插件过时了

Extension version: 3.6.0
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|-psn_0_12622857|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by hesichuan** [comment]
提示信息如下：
Your project is configured to use an outdated version of prettier that cannot be used by this extension. Upgrade to the latest version of prettier.

**Comment by huyajie** [comment]
没人吗 我的也是

**Comment by ntotten** [comment]
What version of prettier do you have installed in your local project?

**Comment by hesichuan** [comment]
Prettier - Code formatter  3.8.0

**Comment by ntotten** [comment]
That is the extension version. What version of `prettier` do you have installed in your project in the `package.json`? It is likely outdated.

**Comment by hesichuan** [comment]
"@vue/eslint-config-prettier": "^5.0.0"

**Comment by ntotten** [comment]
@hesichuan That isnt what I am asking. Please provide the full logs. https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue

**Comment by yangfandashuaige** [comment]
Hello, I have a big file save no response, but other small file save no problem. Have you ever met?
