### ISSUE TITLE
Format selection does not work on .scss and .css file

### ISSUE THREAD

**Issue by msbx2244** [prettier/prettier-vscode#1063]
<img width="455" alt="Screen Shot 1398-08-25 at 00 10 33" src="https://user-images.githubusercontent.com/57813901/68974443-054d4f00-0806-11ea-96c6-597fe2a53291.png">

In `.scss` and `.css` file, only we can `Format Document` with prettier plugin.
Format Selection also is necessary but there is nothing.

**Comment by joemaller** [comment]
Not sure about the current status, but I suspect it's unchanged: No upstream support.  https://github.com/prettier/prettier-vscode/issues/529#issuecomment-410650704

**Comment by ntotten** [comment]
I updated the docs to note which languages are supported: https://github.com/prettier/prettier-vscode#format-selection
