### ISSUE TITLE
prettier require config setting being removed?

### ISSUE THREAD

**Issue by DanceParty** [prettier/prettier-vscode#1071]
### Summary

"This extension no longer supports setting Prettier options using VSCode configuration..."

What is the recommended way to move forward with this? I looked at the README (which still shows this setting as a valid setting) and the CHANGELOG without any success.

_Feel free to attach a screenshot_.

<img width="794" alt="Screen Shot 2019-11-18 at 12 04 24 PM" src="https://user-images.githubusercontent.com/10778294/69087594-a05b4a00-09fb-11ea-89b8-5986b01e54ec.png">

**VS Code Version**:

1.40.0

**Prettier & Prettier Plugin Version**:

3.6.0

**Comment by ntotten** [comment]
Duplicate of #1056
