### ISSUE TITLE
User-Setting has preference over Workspace-Setting

### ISSUE THREAD

**Issue by bluemoehre** [prettier/prettier-vscode#1074]
### Summary

In version `3.4.0` a change was introduced which causes my User-Setting to have preference over the Workspace-Settings. (I just updated from `3.3.x`)

### Steps To Reproduce:

1.  add `.prettierrc` with `{ "printWidth": 120 }` to your project
1.  Goto VSCode `Preferences` → `Settings` → `User` and set `semi: false` + `printWidth: 40`
1.  add a random JS file having multiple lines of code with more than 120 chars
1.  use `>Format document` (with Prettier)

### Expected result

Code lines will be wrapped before 120 chars
Code has semicolons at the end of every line, since that's Prettier's default and a config file was provided, which does not touch that.

### Actual result

Code lines are wrapped correctly (according to `.prettierrc`)
Code has NO semicolons (according to User-Settings)

### Additional information

If `.prettierrc` or similar config is provided there should be no unexpected mix between User-Settings & config file. Settings not provided by `.prettierrc` should fallback to Prettier's default, else you will need to provide a full detailed config file to guarantee overwriting all User-Settings.

See also:
https://code.visualstudio.com/docs/getstarted/settings
> Workspace settings override user settings. Workspace settings are specific to a project and can be shared across developers on a project.

Reverting back to 3.3.0 the behavior is good again.

**VS Code Version**:
1.40.1

**Prettier & Prettier Plugin Version**:
3.7.0

**OS and version**:
MacOS 10.14.6

**Comment by ntotten** [comment]
Fixed in 3.8.0 and added tests to ensure it doesn't regress. Thanks!

**Comment by chrisj-skinner** [comment]
This update has caused my prettier to ignore my single quotes and is now making everything double quotes. No changes to my settings json in VSCODE where made apart from updating this plugin.
I was only using the VSCODE extension and had no need for a `.prettierrc` file, nor did I have prettier installed as a dependency in my project. Everything worked fine until this update.

**Comment by esr360** [comment]
I'm using the latest VSCode, and my user settings are still overriding my workspace settings...
