### ISSUE TITLE
Consider adding back prettier-eslint local resolution

### ISSUE THREAD

**Issue by lukaszmoroz** [prettier/prettier-vscode#108]
I.e. 4cc8d01
Or keep `prettier-eslint` always updated.
It's another extension (after `prettier-eslint-code`) I'm having trouble with using because it stays with an outdated dependency. Right now `prettier-eslint` is at `6.2.3` (with some bugs fixed) but can't be used because this extension locked it at `6.1.2`.
[Here](https://github.com/esbenp/prettier-vscode/issues/70#issuecomment-296448053) you decided that the output from `prettier-eslint` will not change between versions but what else could change if not the output (if its only function is formatting)?

I would even say it makes more sense to not bundle `prettier-eslint` at all and just rely on the user to provide one either globally or in the workspace (that's what eslint extension does). It gives control to the user and doesn't lead to unexpected results.

**Comment by CiGit** [comment]
I would agree on updating it. Requiring a local version is a potential trouble where we have no control. I prefer avoid that to be honest :-) Having it work out of the box is pleasant IMO.
The output from prettier-eslint is the output from `prettier -> eslint --fix` (bug fix excluded ...) those dependencies are picked up by prettier-eslint.

**Comment by CiGit** [comment]
Just published 0.17.2 with prettier-eslint@6.2.3

**Comment by lukaszmoroz** [comment]
Hmm ok, I'm not going to pursue but still think it would be nice to ensure that e.g. the output from the extension is always the same as from the cli.

Thanks for the update.

**Comment by CiGit** [comment]
I've let that one opened for discussion.
IMHO the output from prettier-eslint depends on prettier and eslint (Your local versions are picked up). I see prettier-eslint's bug fixes as *bug fixes* (something which does unexpected things).

**Comment by CiGit** [comment]
stalled, closing

**Comment by OliverJAsh** [comment]
+1 to the idea of using the local version of `prettier-eslint` if there is one.

I have upgraded to v9 (which has bug fixes) whilst this extension is stuck on v8. This means that formatting via the CLI vs via VS Code has different results, which is very confusing until you understand why this is.

Is there any reason not to use the local `prettier-eslint`?

**Comment by shamilovtim** [comment]
This seems to have caused the issue in #861
