### ISSUE TITLE
Prettier can not format js file.

### ISSUE THREAD

**Issue by atasoyh** [prettier/prettier-vscode#1080]
### Steps To Reproduce:

1.  Upgrade Visual Studio to 1.40.1
2. Open any project and any js file to format.
3. Press Shift+Option+F to format.
4. You'll see an error "Extension `Prettier - Code Formatter` cannot format ..." 

### Additional information

![Screenshot 2019-11-20 at 11 42 49](https://user-images.githubusercontent.com/1092496/69236261-0e824700-0b8b-11ea-8011-a3e60ff1790c.png)

**VS Code Version**:
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
**Prettier & Prettier Plugin Version**:
3.8.0
**OS and version**:
MacOS Catalina : 10.15.1 (19B88)

**Comment by gmonte** [comment]
I think that the option `prettier.eslintIntegration` has been deprecated.

**Comment by ntotten** [comment]
Please provide the prettier logs.

**Comment by atasoyh** [comment]
I can't see any log. Where should I see exactly for log? 
I've thought I see the error log on output window which is like screenshot. 
![Screenshot 2019-11-22 at 16 19 02](https://user-images.githubusercontent.com/1092496/69442251-23eea100-0d44-11ea-800b-465626b5840c.png)

**Comment by ntotten** [comment]
@atasoyh you need to actually save a file to get the log for that file.

**Comment by atasoyh** [comment]
How exactly should I save a file to get the log? It didnt make sense on my side?

**Comment by ntotten** [comment]
See: https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue

**Comment by atasoyh** [comment]
There was no log output. I checked I had a few more prettier extension. I uninstalled others and it starred to working. Others had been installed before; maybe we new updates there was a conflict somewhere. Thanks for your support anyway!

**Comment by hosseinmd** [comment]
I have this issues exactly
