### ISSUE TITLE
Legacy linting options popup should be permanently dismissible

### ISSUE THREAD

**Issue by BPScott** [prettier/prettier-vscode#1083]
### Summary

I've got a project that contains:

```json
{
  "editor.formatOnSave": true,
  "prettier.eslintIntegration": true,
  "prettier.stylelintIntegration": true,
}
```

This means that every time I save a file formattable by prettier I get s deprecation toast saying "You have legacy lintier options in your VS Code settings" with the options to see the log or remove the settings. This is helpful the first time you see it but feels somewhat needy the 900th time you see it.

I currently don't have the time to remove these settings and provide a replacement approach (educating my team to install a whole new plugins will take a bit of time), and would appreciate being able to make this toast permanently go away while retaining my existing settings so that I don't have to ignore that.

Would it be possible to add an extra option to this toast that permanently stops it from appearing. This could be once per settings file, or across all of VSCode I don't mind which.

### Steps To Reproduce:

Trigger the legacy settings toast

### Expected result

I should be able to choose "Stop reminding me about this" and the popup will no longer trigger on subsequent invocations of the prettier plugin.

### Actual result

I need to have to close this toast every time it appears or learn to ignore its constant presence in the corner of my screen, as does everybody else on my team who is using the repo with these settings.

**Comment by ntotten** [comment]
The settings for the linters  don’t do anything anymore though. Why not just remove them to permanently disable the pop up. It seems to be the same effort to delete the settings from your project as it does to set a permanently disable setting.

**Comment by BPScott** [comment]
Oooh I didn't realise that now it always opts into the integrations if you've got prettier-eslint / prettier-stylelint installed. That's handy. I assumed their deprecations in v3 worked in the same way as in v2 where the options are deprecated but still actually do something.

**Comment by ntotten** [comment]
Yeah, they were marked as deprecated in v2 and in v3 they are unused entirely. I will remove them completely in v4 (i.e. no warnings, etc).
