### ISSUE TITLE
Optional chaining not working in typescript file

### ISSUE THREAD

**Issue by DavidBabel** [prettier/prettier-vscode#1090]
**Is your feature request related to a problem? Please describe.**
Optional chaining is not working in vscode.

**Describe the solution you'd like**
Update to prettier last version which apparently fixed the issue : https://github.com/prettier/prettier-vscode/issues/977

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/prettier/prettier-vscode/issues/977

**Comment by ntotten** [comment]
We are using the latest version of prettier in this extension, see: https://github.com/prettier/prettier-vscode/blob/master/package.json#L119

You can also install prettier locally in your project.

**Comment by DavidBabel** [comment]
I have it locally, but is the plugin supposed to recognize the one in node modules ?
I did not find any information about it.

yet in a tsx react stack, it seems to not work.

**Comment by ntotten** [comment]
Are you on the insider edition of vscode? Optional chaining isn't supported in VS Code standard yet.
