### ISSUE TITLE
Prettire does not converting double quote to single quote

### ISSUE THREAD

**Issue by impushkar** [prettier/prettier-vscode#1094]
![2019-11-25-123415_1366x768_scrot](https://user-images.githubusercontent.com/32325817/69519379-eb3b0b80-0f7f-11ea-8a80-51f1711bd257.png)

  "prettier.singleQuote": true,
"editor.formatOnSave": true,

![2019-11-25-123506_1366x768_scrot](https://user-images.githubusercontent.com/32325817/69519436-06a61680-0f80-11ea-8605-cc4996239b6d.png)

**Comment by impushkar** [comment]
![2019-11-25-123824_1366x768_scrot](https://user-images.githubusercontent.com/32325817/69519618-7ddbaa80-0f80-11ea-81a4-e8b0285052a0.png)

**Comment by impushkar** [comment]
> This issue is closed because it does not match our issue template or include all the required information. Please read and follow the instructions and reopen.

i am facing this problem because of prettier plugin . two three day ago it was working fine. but since saturday it showing error does not formatting code.  Is this version issue or else. pls suggest what can i do to resolve this.

**Comment by ntotten** [comment]
Please use the issue template.

**Comment by sreekumarp** [comment]
This is happening after updating to October release

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by sreekumarp** [comment]
Logged a new issue with issue template #1099
