### ISSUE TITLE
Multiple function argument doesn't break lines anymore

### ISSUE THREAD

**Issue by luchillo17** [prettier/prettier-vscode#1096]
### Summary

This plugin used to format function arguments split after 2, now it doesn't after the latest update

### Github Repository to Reproduce Issue

https://github.com/luchillo17/prettier-vscode-errors

### Steps To Reproduce:

1. Clone repo.
2. Run `npm i`.
3. Open & format file `multiline-format-issue.ts`

### Expected result

Check the red part in the following image, that was before the update

### Actual result
Check the green part, that's current result and is re-formatting everywhere in my code, it's harder to read, off course those 3 functions will never reach 80 width.

![image](https://user-images.githubusercontent.com/9698639/69576760-fd767300-0f9a-11ea-845f-59f1f5739745.png)

### Additional information

**VS Code Version**: 1.40.1

**Prettier Extension Version**: 3.9.0

**OS and version**: Win 10 1909

## Prettier Log Output

![image](https://user-images.githubusercontent.com/9698639/69577346-277c6500-0f9c-11ea-8402-b473850b4a94.png)

**Comment by ntotten** [comment]
The github repro provided doesn't reproduce the issue for me. It looks like you are actually using `prettier-tslint` in your real project which may be the cause. Can you take a look at the github repro again and make sure you can reproduce this. My test seems to work correctly:

![image](https://user-images.githubusercontent.com/282782/69639600-ce0f4700-102a-11ea-86e0-cf8971450b6a.png)

**Comment by luchillo17** [comment]
Oh but it is working different than before, it used to split `take(1)`, `retry(3)` and `delay(100)` each in their own line, the diff in the "Actual Results" section shows how it used to split those pipe (and also function) args, i think it's more readable like it was before.

**Comment by ntotten** [comment]
Ah, that would be something to bring up on the core prettier repo: https://github.com/prettier/prettier

This extension doesn't make any formatting decisions, it just runs the prettier library.

**Comment by luchillo17** [comment]
@ntotten Thanks, what was the previous version of prettier bundled so i can report which one used to work like that?

**Comment by ntotten** [comment]
We’ve bundled all of them. This extension updates every time prettier does so unfortunately I’m not sure which one behaved that way.

**Comment by luchillo17** [comment]
Since it changed with latest update that removed the editor settings in favor of the `.prettierrc` file, should be one released this last week, since the latest according to tags is 3.5.0, i guess it's the version bundled with 3.0.2 that used to work.

**Comment by urdarinda** [comment]
This exactly is happening to me as well :/

**Comment by luchillo17** [comment]
I still dunno which was the version bundled with 3.5.0 or 3.0.2, where do i look for that @ntotten?

**Comment by ntotten** [comment]
https://github.com/prettier/prettier-vscode/commits/master/package.json

**Comment by luchillo17** [comment]
Finally found it, the version it used to work was prettier@1.18.2, @urdarinda you can get the old behavior installing this exact version in your project directly.

**Comment by luchillo17** [comment]
It seems the way they detect function composition has changed, i guess we'll have to deal with it, getting used to it.
