### ISSUE TITLE
Clarification of extension namespace: esbenp vs Prettier

### ISSUE THREAD

**Issue by BPScott** [prettier/prettier-vscode#1101]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
No

**Describe alternatives you've considered**
No

**Additional context**
The close-issue-app bot feels pretty heavy handed. My query doesn't fit into the template. This duplicates #1100 while trying to keep that bot happy.

---

Currently the extension is available under two namespaces in the VSCode marketplace [`esbenp.prettier-vscode`](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and  [`Prettier.prettier-vscode`](https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode).

I know you used the Prettier namespace as a testing ground for v3 work, but now both namespaces use the same code. Because of this duplication I'm unsure which extension I should use. I know the esbenp namespaces has been around a lot longer and has a large existing mindshare and an established install base but the Prettier namespaces sounds a lot more official.

Which namespace should I suggest people use? Stick with `esbenp` or start recommending people migrate to use `Prettier`?

Do you have any plans on deprecating / removing one of the namespaces at any point in the future?

**Comment by ntotten** [comment]
Good question. I was going to ask my contacts at Microsoft about how to handle this. They are actually exactly the same - i have been pushing the releases to both. In hindsight I should have use something like `esbenp-prettier-vscode-next` for the preview release. 

For now, I would suggest using the `esbenp` one, but it doesn't really matter.

**Comment by BPScott** [comment]
I discovered earlier today that you can yank an extension from the market place even if it is well established. I wonder if that's worth doing with Prettier.prettier-vscode to save on any more fragmentation. A bit of immediate pain for longer term cohesion.

**Comment by ntotten** [comment]
Ah, I didn’t realize that was possible. It really only has a few hundred users.

**Comment by ntotten** [comment]
> The close-issue-app bot feels pretty heavy handed. My query doesn't fit into the template. This duplicates #1100 while trying to keep that bot happy.

This is the one edge case, but so far it has worked pretty well at forcing people to open high-quality issues that I can actually use to find out the problem. I do check the closed issues periodically to make sure i don't miss something, but so far I am liking how it is automatically closing issues like this:  https://github.com/prettier/prettier-vscode/issues/1103

**Comment by ntotten** [comment]
I published a new version of the `prettier` extension that doesn't do anything except register the main extension as a dependency. It effectively is gone now. I will only be updating the esbenp version going forward. Future preview releases will be published under a name like `prettier-vscode-next` or something.
