### ISSUE TITLE
Change in indentation

### ISSUE THREAD

**Issue by derwaldgeist** [prettier/prettier-vscode#1110]
Some while ago, VSCode prettier changed the way it handles its eslint integration. I followed the instructions to setup the required files, but since then the indentation object literals in ternary operators changed and is marked as "error" by eslint.

Here's a code snippet with the old configuration setup (configuration in VSCode settings):

![image](https://user-images.githubusercontent.com/3984535/69893022-318bc400-130c-11ea-96c0-aafebc944c5e.png)

Properties are aligned to the opening { and the closing } is aligned with the ternary operator's colon.

After the change, prettier formats the code like this:

![image](https://user-images.githubusercontent.com/3984535/69893047-6dbf2480-130c-11ea-87f3-ffa45166b361.png)

Now the properties of the object literal are indented, and the closing } is aligned to the opening {.

which is considered an error by eslint.

![image](https://user-images.githubusercontent.com/3984535/69893098-e45c2200-130c-11ea-993e-542e2408d74c.png)

I attached my config files. The options in the files haven't changed.

[config-files.zip](https://github.com/prettier/prettier-vscode/files/3906550/config-files.zip)

**Comment by derwaldgeist** [comment]
I tried to tweak this by setting an ObjectExpression rule for indent, but I couldn't find a combination that instructs prettier to use the old style and make eslint happy.

**Comment by ntotten** [comment]
Would you be able to publish a simple project instead of just the config files?

Also one note , this setting isn't anything `"eslintIntegration": true` in prettier or vscode config. You can delete it.

**Comment by iou90** [comment]
Have the same issue here.

``` js
/*
vscode 1.41.0,
prettier extension 3.16.1,
eslint 6.7.2
*/
const testIndent = [];
const test = checkWhatever =>
    checkWhatever
        ? testIndent.map(() => {
              test: 'the indent of this line marked error by eslint';
          })
        : testIndent;
```

The  project: [prettierWithEslint.zip](https://github.com/prettier/prettier-vscode/files/3976728/prettierWithEslint.zip)

**Comment by iou90** [comment]
https://stackoverflow.com/questions/52178093/ignore-the-indentation-in-a-template-literal-with-the-eslint-indent-rule
This helped.
Config eslint with:
``` json
"rules": {
    "indent": ["error", 2, { "ignoredNodes": ["TemplateLiteral *"] }],
    "function-paren-newline": "off"
  }
```
@derwaldgeist

**Comment by iou90** [comment]
@derwaldgeist 
Config with eslint:
``` js
indent: ['error', 4, { SwitchCase: 1, ignoredNodes: ['ConditionalExpression *'] }]
```

**Comment by derwaldgeist** [comment]
@iou90 Great, that worked! Thanks.

**Comment by ntotten** [comment]
The problem is that you don't have `prettier-eslint` installed locally so the prettier extension isn't using ESLint integration at all.

You need to run:

```
npm install prettier-estlint -D
```

Your package.json should have the following:

```
  "devDependencies": {
    "eslint": "^6.7.2",
    "prettier-eslint": "^9.0.1"
  }
```

Once I ran that on your sample project, everything worked as expected. See the eslint configuration instructions here: https://github.com/prettier/prettier-vscode#prettier-linter-integration-advanced

**Comment by iou90** [comment]
@ntotten 
I do not want to use prettier-eslint witch formats js codes with "eslint --fix" (need to run "eslint --fix" without formating).

**Comment by ntotten** [comment]
@iou90 It sounds like you need to set this up: https://github.com/prettier/eslint-config-prettier

**Comment by derwaldgeist** [comment]
> The problem is that you don't have `prettier-eslint` installed locally so the prettier extension isn't using ESLint integration at all.

Thanks for that info. I actually wasn't aware of this.

**Comment by iou90** [comment]
@ntotten eslint-config-prettier will not work with specific rules added in eslintrc.

``` js
module.exports = {
    extends: ['eslint:recommended', 'eslint-config-prettier'], // not works
    rules: {
        indent: ['error', 4, { SwitchCase: 1 }],
    },
    env: {
        browser: true,
        commonjs: true,
        es6: true,
        node: true,
    },
    parserOptions: {
        ecmaVersion: '2019',
        sourceType: 'module',
    },
};
```

**Comment by ntotten** [comment]
It sounds like you are asking to configure prettier and eslint in ways that conflict. It isn't possible. The whole point of `eslint-config-prettier` is to disable eslint rules like the `indent` rule you have configured and let prettier handle the formatting. You can't have eslint and prettier BOTH do formatting.
