### ISSUE TITLE
Rename config option to "Require prettier configuration in a file or package.json to format"

### ISSUE THREAD

**Issue by jedwards1211** [prettier/prettier-vscode#1118]
Seems like the "Require a configuration file to format" option works even when the prettier config lives in package.json, but it's impossible to tell just looking at the extension options.

**Comment by ntotten** [comment]
I’m not renaming the config as that would be a major breaking change, but we can add some additional docs.

**Comment by jedwards1211** [comment]
I'm confused, breaking change?  It seems to accept config in package.json so I don't see why there would be any breaking behavioral changes

**Comment by ntotten** [comment]
I added additional description info to explain how this works. Ultimately, it’s based on the behavior of prettier itself.

**Comment by jedwards1211** [comment]
Okay thanks, the linked page on prettier makes it clear!
