### ISSUE TITLE
[question] How to disable on html files via editorconfig

### ISSUE THREAD

**Issue by morenoh149** [prettier/prettier-vscode#1120]
I have a django project I'm working on. Prettier vscode doesn't do a good job with the django templates. Other issues report you can disable prettier on html files.

How do I disable prettier for html files via editorconfig?

**Comment by ntotten** [comment]
You cannot do it in editor config. My recommendation is to use a .prettierignore file, but you can also disable languages in the VSCode config.

**Comment by morenoh149** [comment]
ok for those that don't know what a `.prettierignore` file looks like you can add a file to your project root like

```
*.html
```
and vscode wont use prettier on those files in that project.
