### ISSUE TITLE
how can I stop the toast?

### ISSUE THREAD

**Issue by cmonacaps** [prettier/prettier-vscode#1122]
It says,

> Your project is configured to use an outdated version of prettier that cannot be used by this extension. Upgrade to the latest version of prettier.

It kind of works.  The project is not mine to change as instructed.  I'd rather not switch off prettier and don't have the willpower to make a project settings change atm

**Comment by ntotten** [comment]
I’m not sure how it would work. You need to upgrade. I can’t support all versions of prettier forever.
