### ISSUE TITLE
Support por Java in Visual Studio Code

### ISSUE THREAD

**Issue by rcpacheco** [prettier/prettier-vscode#1124]
I'm using Visual Studio Code developing a Java/SpringBoot proyect. The plugin get enebled so:

["INFO" - 11:56:14] Enabling prettier in workspace 'myProject' for languages:
[
  "javascript",
  "mongo",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "json",
  "jsonc",
  "json5",
  "css",
  "postcss",
  "less",
  "scss",
  "graphql",
  "markdown",
  "mdx",
  "html",
  "vue",
  "yaml"
]
["INFO" - 11:56:14] Enabling prettier for range supported languages
[
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "json",
  "graphql"
]

Is it possible to detect that it is a Java project and enable it? 

Thanks a lot

**Comment by ntotten** [comment]
Try this: https://github.com/jhipster/prettier-java
