### ISSUE TITLE
Running rbprettier from vscode

### ISSUE THREAD

**Issue by pitosalas** [prettier/prettier-vscode#1125]
I have the latest prettier, the latest vscode, the rbprettier gem installed. This is all on MacOS with the latest update.

When I ask to "format document" on a ruby file I get an error message, "There is no formatter for Ruby installed".

**Comment by ntotten** [comment]
This plugin doesn’t use gems. You need to install the node module. https://github.com/prettier/plugin-ruby#npm-package
