### ISSUE TITLE
Add option to prevent wrapping HTML tags / HTML attributes, control odd behavior of trailing close tags.

### ISSUE THREAD

**Issue by CrocodileDunDooDoo** [prettier/prettier-vscode#1129]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the only decent HTML code formatter in VS Code does strange things with my code like break up a single html tag onto multiple lines, or worse yet it leaves a closing tag on the same line as another really long tag.  Usually when all the tags are nested properly you can visually tell where problems or missing tags occur in an HTML document just by scanning it, however these weird choices make the HTML incredibly difficult to read.

**Describe the solution you'd like**
1.  Make the default behavior, or add an option, to prevent Prettier from leaving closing HTML tags on a previous line.
2.  Make the default behavior, or add an option, that prevents breaking up of HTML tags onto multiple lines.  Currently the behavior isn't consistent even with the ability to control the max line length.  It just randomly chops up the document and makes it a visual nightmare.

**Describe alternatives you've considered**
Banging my head against a wall.  Isn't helping so far.

**Additional context**
Why the hell was this done to begin with?  It doesn't add any benefits unless you can control which tags get broken up outside of just a line-length-limit.  HTML is tedious, this formatter makes it more so.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by CrocodileDunDooDoo** [comment]
I apologize for not being very clear.  This is an issue with the default VS Code formatter as well.  It only allows control over how long a line's length can be, and puts closing tags on previous lines while breaking up long tags across multiple lines.
