### ISSUE TITLE
Package.json Resolution Should Be More Predicable

### ISSUE THREAD

**Issue by ntotten** [prettier/prettier-vscode#1135]
This issue is for discussion purposed and not necessarily a change that will be made.

Currently, the way that `package.json` files are resolved is the file tree is walked downward from the file being formatted until/if a package.json file is found. I think there are a couple of problems with this.

1. It results in some unpredictable behaviors. For example, if you register a plugin in the `package.json` (package 2) file in the root of your project and have some other `package.json` (package 2) file up higher in the tree, when you try to open a file above package 2, the plugin will never work - even though it is registered with the project. This will result in errors (see also #1134).

2. It requires that prettier be installed in many places in a project. My assumption is that most people want prettier to be centrally managed/configured in a project. I have seen projects that end up with many different versions of prettier at many different levels of the project because prettier has to be installed in every `package.json`.

The proposed solution would be to, by default, use only the `package.json` file at the Workspace Root (as defined by VS Code) OR in cases where prettier configuration files are found (i.e. if a .prettierrc file is found in a folder, we would look for a `package.json` in that folder. 

This behavior is how the ESLint plugin does resolution and I think it is much more predictable and will reduce some of the confusion around usage of prettier with plugins. I were to implement this, I would add a new configuration setting called something like `useLegacyModuleResolution` in order to keep the behavior for people that already build projects assuming this behavior.

Let me know what you think.

**Comment by lydell** [comment]
In all small projects I work on, I have Prettier configured once in the project root.

At work, we have this setup: https://github.com/lydell/prettier-multi-project-test. As long as that keeps working, I’m happy :smiling_face_with_three_hearts:
