### ISSUE TITLE
How to stop break line in function with argument and callback?

### ISSUE THREAD

**Issue by ryuta69** [prettier/prettier-vscode#1137]
# Problem
If I code like this, 

```javascript
MongoClient.connect(connectionURL, { userNewUrlParse: true }, (error, client) => {
-----
});
```

it would prettier like this.

```javascript
MongoClient.connect(
  connectionURL,
  { userNewUrlParse: true },
  (error, client) => {
-----
  }
);
----
});
```

I'd like to not work prettier only this part.
Every features except this is great and satisfying.

## What I've tried
Nothing, because I have found this issue.
https://github.com/prettier/prettier-vscode/issues/352

well, is this issue closed with unsolved..?

## Conclusion
Any help is appreciated.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
