### ISSUE TITLE
PostCSS support

### ISSUE THREAD

**Issue by svipben** [prettier/prettier-vscode#114]
Hello,

I'm using this extension to support PostCSS, but it doesn't work with Prettier. Can you add PostCSS in language mode?

Extension: https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language

Thank you!

**Comment by CiGit** [comment]
Is #116 ok for you?

**Comment by svipben** [comment]
@CiGit yes!

**Comment by stewartduffy** [comment]
Can someone share their config they used to get PostCss formatting with prettier please?
I am using this https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language for syntax support.

Do you need to name the files .pcss extension or do you map css to postcss type? 
```
"files.associations": {
  "*.css": "postcss"
}
```
I have tried this too
```
  "[postcss]": {
    "editor.formatOnSave": true
  },
```

No luck...

**Comment by ads1018** [comment]
@stewartduffy I'm also using vscode and struggling getting it to work with postcss files.

**Comment by CiGit** [comment]
Language are now provided by prettier. postcss is currently not part of what prettier gives us.
There is a PR on prettier's side for exactly that

**Comment by CiGit** [comment]
Supported since 1.1
