### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by saurabhguptarock** [prettier/prettier-vscode#1142]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `3.14.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Saurabh\esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Please provide the requested file and reopen.
