### ISSUE TITLE
disable  quote formatting (single and double) 

### ISSUE THREAD

**Issue by nurmohammed840** [prettier/prettier-vscode#1149]
**How to disable quote formatting in prettier?**

I use both quote ( single and double ) in node.js project.<br>But prettier format all single quote into double quote.<br>
**Note : I use both quote for syntax highlighter**
Is there any way to disable  quote formatting in ***prettier*** ?

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
