### ISSUE TITLE
The configuration file remains the same, but the formatting results are random.

### ISSUE THREAD

**Issue by lihefei** [prettier/prettier-vscode#1154]
### Summary

The exact same code, the formatting results at different times are very different, and random appearance is completely unexpected. This caused a lot of differences when committing code to git.

### Steps To Reproduce:

1.  first day
```
 let { points, deviceMarker, pointCollection, customOverlay } = this.mapConfig;
```

2.  The third day
```
let {
    points,
    deviceMarker,
    pointCollection,
    customOverlay
} = this.mapConfig;
```
3.  The fifth day
```
 let { points, deviceMarker, pointCollection, customOverlay } = this.mapConfig;
```

### Expected result

The format results are the same for all three days.

### Actual result

The three-day format results change randomly.

**VS Code Version**:
1.41.0

**Prettier Extension Version**:
3.17.0

**OS and version**:
Windows_NT x64 10.0.18362

**Comment by ntotten** [comment]
Please provide logs and actual reproduction steps and reopen.
