### ISSUE TITLE
My pretter formats only files from the root directory, from the subdirectory - no.

### ISSUE THREAD

**Issue by ntotten** [prettier/prettier-vscode#1160]
> Looks like this is fixed with [b57b238](https://github.com/prettier/prettier-vscode/commit/b57b238d4e2b0ec6ff3b47db5df8d2d2ce158ccd) - I've updated the extension and all seems to be fine now. <

Yes, it works now. Thank you for efficiency.
I have another problem, can someone tell me: My pretter formats only files from the root directory, from the subdirectory - no.
![image](https://user-images.githubusercontent.com/18327326/71347419-67267480-257b-11ea-83cf-80e033d0692f.png)
For some reason, it does not see the configuration file when formatting their subdirectories.

_Originally posted by @DSpade-r in https://github.com/prettier/prettier-vscode/issues/1156#issuecomment-568408587_

**Comment by ntotten** [comment]
Moving to new issue.

@DSpade-r Do you have a `prettierignore` file?

**Comment by CiGit** [comment]
prettier ignores `node_modules`

**Comment by DSpade-r** [comment]
> Moving to new issue.
> 
> @DSpade-r Do you have a `prettierignore` file?

No I don't use prettierignore


> prettier ignores `node_modules`

Can I somehow to disable it? I use different 'node_modules' for using direct path in import expression.

**Comment by DSpade-r** [comment]
I played a bit with .prettierignore
!/src/node_modules or !/node_modules doesn't work
with any else folders works fine

**Comment by ntotten** [comment]
Oh, yeah. I didn’t realize you were formatting node modules. Formatting node modules is not supported through this extension. You can use the Prettier CLI directly with the  --with-node-modules flag. We don’t intend to support that though in the extension.

**Comment by DSpade-r** [comment]
> Oh, yeah. I didn’t realize you were formatting node modules. Formatting node modules is not supported through this extension. You can use the Prettier CLI directly with the --with-node-modules flag. We don’t intend to support that though in the extension.


It makes sense. But can you implement only ignore node_modules from the root folder? there are no strict rules for using a directory with the same name.

**Comment by CiGit** [comment]
>  We don’t intend to support that though in the extension.

And what if we instead always format them if asked?

We format only a single file at a time. I'm pretty sure this flag exists because of globing. This allows users to avoid having to setup a prettierignore in most projects. In a *conventional* node project, there is no point in formatting files you don't own and you speed up the CLI by skipping them.
