### ISSUE TITLE
printWith:120 is not work on JSON like code

### ISSUE THREAD

**Issue by nailfar** [prettier/prettier-vscode#1173]
before format: 
![image](https://user-images.githubusercontent.com/12581226/71581232-3d52ec00-2b3f-11ea-973b-0b5c2dcfee55.png)

after format:
![image](https://user-images.githubusercontent.com/12581226/71581310-85720e80-2b3f-11ea-97df-21e1ee0685f6.png)

printWith is 120,it should no-wrap but not;

Prettier - Code formatter 3.18.0
macOs
.prettierrc
```
{
  "semi": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "arrowParens": "always",
  "jsxBracketSameLine": true,
  "printWidth": 120,
  "htmlWhitespaceSensitivity": "ignore",
  "overrides": [
    {
      "files": ".prettierrc",
      "options": { "parser": "json" }
    }
  ]
}

```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
