### ISSUE TITLE
Question: How to prevent from to enter next line after +

### ISSUE THREAD

**Issue by fakhamatia** [prettier/prettier-vscode#1177]
I want this:
![Screenshot from 2019-12-31 18-06-28](https://user-images.githubusercontent.com/20030910/71624698-240e7600-2bf9-11ea-9a5b-688db9d49eaa.png)

Not this:
![Screenshot from 2019-12-31 18-06-00](https://user-images.githubusercontent.com/20030910/71624702-2a045700-2bf9-11ea-9131-2db0743932dc.png)

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
