### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Batonja** [prettier/prettier-vscode#1178]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `3.18.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Administrator\esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/4017896/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by ntotten** [comment]
Please attach the required file and reopen.
