### ISSUE TITLE
Format Selection option doesn't show for css files

### ISSUE THREAD

**Issue by sebastiantf** [prettier/prettier-vscode#1194]
### Summary

The `Format Selection` command doesn't show up in the commands list for css files. But `Format Document` command shows fine.

### Steps To Reproduce:

1.  Open a .css file
2.  Select a portion of the code
3. `Cmd+Shift+P`
4. Search for `Format Selection`
5. Cannot find `Format Selection`, only `Format Document` is shown

### Expected result

`Format Selection` command is found and able to be executed.

### Actual result

Cannot find `Format Selection`, only `Format Document` is shown

### Additional information

<img width="1098" alt="prettierissue" src="https://user-images.githubusercontent.com/36922376/72168865-03fa6600-33f4-11ea-9ecc-0f09f99f8e06.png">

**VS Code Version**: 1.41.1

**Prettier Extension Version**: 3.18.0

**OS and version**: Mac OS Mojave 10.14.5

## Prettier Log Output

```
["INFO" - 9:40:27 PM] Extension Name: "prettier-vscode".
["INFO" - 9:40:27 PM] Extension Version: "3.18.0".
["INFO" - 9:40:27 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 9:40:27 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 9:42:35 PM] Loaded module 'prettier@1.19.1' from '/Users/sebastiantf/.vscode/extensions/esbenp.prettier-vscode-3.18.0/node_modules/prettier/index.js'

```

**Comment by ntotten** [comment]
Format selection isn’t supported in CSS. This is a limitation on prettier itself. See: https://github.com/prettier/prettier-vscode#format-selection
