### ISSUE TITLE
Extension 'Prettier - Code Formatter' cannot format html when using custom plugin

### ISSUE THREAD

**Issue by Acidic9** [prettier/prettier-vscode#1195]
I've developed a plugin for Prettier available on NPM as [`prettier-plugin-tailwind-classes-sorter`](https://www.npmjs.com/package/prettier-plugin-tailwind-classes-sorter).

When trying to use this in VSCode, I receive an error:

> Extension 'Prettier - Code Formatter' cannot format index.html

![Screenshot](https://imgur.com/idKrrSI.png)

But the plugin works when using Prettier cli with `./node_modules/.bin/prettier ./index.html`

---

To reproduce, in an empty project:

```bash
yarn add --dev prettier prettier-plugin-tailwind-classes-sorter
echo "module.exports={theme:{},variants:{},plugins:[]}" > ./tailwind.config.js
echo "<html><body class="w-full container"></body></html>" > ./index.html
```

Then restart VSCode.

**Comment by ntotten** [comment]
Please provide the output log.

**Comment by Acidic9** [comment]
@ntotten The output log does not display anything related to the issue.

**Comment by ntotten** [comment]
Looks like an issue with the plugin. I would suggest contacting the author.

![image](https://user-images.githubusercontent.com/282782/73184787-fbd84100-40ea-11ea-9dcb-28b6820fe107.png)

**Comment by Acidic9** [comment]
I am the author.. thats why I'm here making an issue. It is unresolved. Any help would be appreciated...

**Comment by ntotten** [comment]
you're repo steps dont mention anything about a config. please provide that file.

**Comment by Acidic9** [comment]
Sorry, I forgot to include that... I've updated the original issue comment.

**Comment by ntotten** [comment]
I just ran the repro while debugging the extension. It has something to do with resolving the tailwind config while the extension is trying to determine what languages are supported by the plugin. In debug mode I get this error:

`Activating extension 'esbenp.prettier-vscode' failed: could not find tailwind.config.js.`

It is fairly easy to run this extension and debug. Just clone the repo, open it in vscode insiders and use the "Run Extension" debug option. You can step through code, etc. 

I don't think it is anything wrong with the extension, but rather something with the plugin. My guess is it has to do with some path resolution from where the extension is executing compared to where the prettier CLI is executing. Sorry, I don't have more info. That's really all the time I have to look into this.

**Comment by Acidic9** [comment]
Ah okay thank you! I'll look into it!
