### ISSUE TITLE
Require Pragma honored when using Format On Save

### ISSUE THREAD

**Issue by AaronSamuelsson** [prettier/prettier-vscode#1206]
As brought up in the past in [prettier/prettier-vscode#145](https://github.com/prettier/prettier-vscode/issues/145#) pragma check on save would be a huge improvement. Now that it has been implemented in prettier, and since the issue was closed in 2017, I would like to reopen this request. Currently prettier-vscode doesn't honor pragmas during format-on-save.

I would like to be able to use format-on-save in VS Code using Prettier. Prettier should check for pragmas and only apply formating if it is present.

**Comment by henrymyers** [comment]
Bump. This is really annoying.

**Comment by ntotten** [comment]
The extension already supports this parameter. Is it not working?

**Comment by henrymyers** [comment]
After writing my comment, I realized that manually adding `"requirePragma": true` to the config **does** work with format on save. It's activating the _extension's_ requirePragma option that doesn't.

**Comment by ntotten** [comment]
I think maybe the issue you are having is that the VS Code config only applies if no other config exists. So if a prettier config file is detected, the vscode config wont do anything.

**Comment by henrymyers** [comment]
That seems quite possible. Thanks!

**Comment by AaronSamuelsson** [comment]
The bot closed me while I was sick. Guess I should have checked in sooner.

@ntotten I am not sure I understand, when I click require pragma check box in plugin settings, it does not look for the pragma  when format on-save runs. 

I have format on-save chosen and default formatter set to esbenp.prettier-vscode in user settings

**Comment by ntotten** [comment]
@AaronSamuelsson It only uses that setting if you DO NOT have a prettier configuration file in your project. Those are fallback settings only.
