### ISSUE TITLE
HTML formatting doesn't look like the output from the playground

### ISSUE THREAD

**Issue by nbaleli-w** [prettier/prettier-vscode#1211]
### Summary
prettifying HTML files is good, but certain parts are very strange and hard to read.
I'd leave it alone but after testing in the prettier playground, I understand that the problem is maybe with the plugin?

### Steps To Reproduce:
this is a test block of HTML code:
```
<div class="data-images-group__images">
    <div
        ng-repeat="item in group.images"
        ng-click="$ctrl.onImageClick(item)"
        data-selected="{{$ctrl.isItemSelected(item)}}"
        class="item rel"
    >
        <div class="image">
            <img src="/static/js/pages/images/500_500.png" alt="" />
        </div>
        <div class="item-overlay">
            <div class="item-select">
                <div
                    ng-click="$ctrl.toggleItemSelected($event, item)"
                    class="item-select-circle"
                ></div>
            </div>
            <div class="item-content">
                <span class="ellipsis">{{item.name}}</span>
                <span class="ellipsis"
                    >{{item.created_at | date: "shorDate"}}</span
                >
                <span class="ellipsis"
                    >{{item.created_at | date: "shorTime"}}</span
                >
            </div>
        </div>
        <div class="item-selected-overlay"></div>
    </div>
</div>
```

### Expected result
it should look like the output from the playground

### Actual result
the block of code pasted above is the actual output of running prettify in VScode

you can see espacially this part:
```
<span class="ellipsis"
    >{{item.created_at | date: "shorTime"}}</span
>
```

### Additional information

link to the playground: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiOkTEQLSYC2RA5nCQ2wE4QCuABwD6wlu07UAfJSi55uDDlkLVuKGwY84guHSohM8ZrkxzeAwQDpxHEtRVr5GhoUxgA1gYAkYGDwIraABJVg4AYQJ3DwAKIzhmAEoHOSdcWnoGEjgCOD84dANgYF9-QMwSYOMAZRy8+HQ440SAXxaUtPxiMgN4k20CDoUZVKclPEJSCmpbOGlHTvlUFjYFxdUSHjADAHoSehh3HYArEh3BCTPZs4BWAAY74Xu7q0ENIfXVIgIYAw-FnYjTqoHZYbBAtLjLpTXrGBgQbBwAJEACe81Giyhkx6Mzh2VyfnRnzU4zWxNULjcnh8fgCVhgEDYbFyVQStQJDRi3jgiNgABpTM1-uSFNjpoY8XU-K5MFtcsLPlIQWCIetlThVZiwdCcRKEq5oPBYESRYoSBc5GKDDkooISBUFSKpMU+lYoERmHA2iDzUQoGTFQG1b7Ld1xTbMHaHSAg+TncBXWBtHQCsI6LgAD7pFNIWPE6gkAAWEB4ABEU9RvXsLXm0priagQzrwwRbfb7DGMabcPHE8mGmmYJns-Bc13TQXizwACosOYgKsh2tOeuQ0Ea2Pq8GbsHL5uw-X4+oFeGI5FozudJXr7cYrcje8gPkgCCCQ7QEjIUBEHh8ADuAAKP4IJ+KBENgECYOgT4gAARjwRCeHAMDVBcYBmGwyD+PwcDPoWMDMAQADqhbxL6YBwLUUD2oc2BGCiyDgGQMFmNkPAwABCFsKwyAAGbfNkz6nAAHgAQghSEoR6cAADJmHAfECbhIAidUGG5AAivwEDwIpBCCSAFw8GxjH4YRMGCDwZgwERUEwIWyAABx3M+lkQNkREIYIjGWZwSKIjBACO2nwJxr6gSApAMFAcAFAUMHaMFspwJx7A8Ug-H6cp2TMJgWE8Dhz72homkhQpGVKc+9CwbZ6D2cgABMVUIZgUQaOEEDMOlIBQNACnPvw2TTkQsGgZlBnYDhwRQOgCAoUmkYwAAgjN1QwCiuR6dkbRAA
**VS Code Version**: 1.42.0-insider

**Prettier Extension Version**: 3.18.0

**OS and version**: Ubuntu 18

## Prettier Log Output
```
["INFO" - 16:39:30] Formatting Untitled-1
["INFO" - 16:39:30] Using bundled version of prettier.
["INFO" - 16:39:30] Using ignore file (if present) at undefined
["INFO" - 16:39:30] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 16:39:30] Parser not inferred, using VS Code language.
["INFO" - 16:39:30] Resolved parser to 'html'
["INFO" - 16:39:30] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 16:39:30] Prettier Options:
{
  "filepath": "Untitled-1",
  "parser": "html",
  "useTabs": false,
  "tabWidth": 4,
  "endOfLine": "lf"
}
["INFO" - 16:39:30] Formatting completed in 54.922771ms.

```

**Comment by CiGit** [comment]
If you set tabWidth to 4 on the playground, you will see the same output.

**Comment by nbaleli-w** [comment]
I stand corrected, I must be tired as I was sure I double checked that.

Thank you.
