### ISSUE TITLE
Prettier version being detected as "unknown". Throws upgrade toast

### ISSUE THREAD

**Issue by beck** [prettier/prettier-vscode#1225]
### Summary

Seeing message:
> Your project is configured to use an outdated version of prettier that cannot be used by this extension. Upgrade to the latest version of prettier.

But am using `1.19.1` (installed globally).

## Prettier Log Output

```
["INFO" - 12:49:27 PM] Extension Name: "prettier-vscode".
["INFO" - 12:49:27 PM] Extension Version: "3.18.0".
["INFO" - 12:49:27 PM] Loaded module 'prettier@unknown' from '/usr/local/bin/prettier'
["ERROR" - 12:49:27 PM] Outdated version of prettier installed. Falling back to bundled version of prettier.
```
Testing the bin:
```
$ /usr/local/bin/prettier --version
1.19.1
```

**Comment by ntotten** [comment]
The path `/usr/local/bin/prettier` is not a module path, it is the path to the prettier cli script. Did you set `prettierPath` to this?
