### ISSUE TITLE
Markdown Wrongly Formatted

### ISSUE THREAD

**Issue by 997293** [prettier/prettier-vscode#1227]
### Summary

In VS Code Markdown, Prettier produces wrong results.

### Steps To Reproduce:

Copy and paste the following to VS code Markdown.

```
1. - XXX
     - XXX
2. XXX
```

Format the document with Prettier.

### Expected result

Nothing is expected to change. The code is already well formatted and shouldn't change. So the expected result should be:

```
1. - XXX
     - XXX
2. XXX
```

### Actual result

```
1. - XXX
   - XXX
2. XXX
```

The second line is changed by Prettier, which should not.

**VS Code Version**: 1.41.1

**Prettier Extension Version**: 3.18.0

**OS and version**: Windows 10

## Prettier Log Output

```
["INFO" - 12:22:15 PM] Formatting completed in 14.7896ms.
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
