### ISSUE TITLE
Extension doesn't work with local dependencies

### ISSUE THREAD

**Issue by bogdansoare** [prettier/prettier-vscode#1242]
### Summary

I have prettier installed in my project's local dependencies, but the extension doesn't work in VS Code, when I don't have prettier installed in local dependencies the extension works.

**VS Code Version**: 1.42.0

**Prettier Extension Version**: 3.20.0

**OS and version**: macOS 10.15.3 

## Prettier Log Output

```
["INFO" - 2:28:51 PM] Extension Name: "prettier-vscode".
["INFO" - 2:28:51 PM] Extension Version: "3.20.0".
["INFO" - 2:28:51 PM] Loaded module 'prettier@1.19.1' from '/Users/bogdansoare/Sites/platform/apps/web/node_modules/prettier/index.js'
["INFO" - 2:28:51 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 2:28:51 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
```

**Comment by ntotten** [comment]
I am not really understanding the issue. From the log you provided everything seems to be working. Can you provide more detail reproduction steps?

**Comment by bogdansoare** [comment]
It seems to be working but it isn't, when I try to format the document nothing happens, also there is no checkmark besides Prettier in the status bar

As for reproduction I've just installed the extension and try using it in a project that has prettier as a dev dependency

**Comment by bogdansoare** [comment]
After a reinstall it worked 🤷‍♂, I will close this issue for now.
Sorry for the time wasted.
