### ISSUE TITLE
Plugin search directory is incorrect in the second window if two are opened

### ISSUE THREAD

**Issue by davidbailey00** [prettier/prettier-vscode#1248]
### Summary

When two VS Code windows are opened for two different directories ("A" and "B"), the plugin searches directory A to look for plugins specified in project B's `.prettierrc.json` and can't find them.

### Github Repository to Reproduce Issue

- https://github.com/davidbailey00/reaware

- https://github.com/davidbailey00/davidbailey.codes (before this commit: https://github.com/davidbailey00/davidbailey.codes/commit/864de49f37296e603e97a43d1d5b7fbf233c3e89)

### Steps To Reproduce:

1. Open a project ("A") in VS Code, with no other windows open.
   e.g. `/home/david/Code/JavaScript/reaware` in my log
2. Open a second project ("B"), which has a `.prettierrc.json` file, specifying some plugins.
   e.g. `/home/david/Code/JavaScript/davidbailey.codes` in my log
3. Install these plugins in project B using `(p)npm/yarn install` if they're not already installed.
4. Format a file in project B using the VS Code extension.

### Expected result

The file is formatted correctly.

### Actual result

The file fails to format because the extension looks in the wrong directory to find Prettier plugins, and can't find them because they don't exist.

### Additional information

`.prettierrc.json` in the failing project:

```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
   "plugins": ["prettier-plugin-toml"]
}
```

- It formats correctly when changing `prettier-plugin-toml` to `./node_modules/prettier-plugin-toml`
- It also formats correctly if "project B" is opened first

**VS Code Version**: 1.42.0

**Prettier Extension Version**: 3.20.0

**OS and version**: Pop!_OS / Ubuntu 19.10

## Prettier Log Output

```
["INFO" - 12:14:43] Extension Name: "prettier-vscode".
["INFO" - 12:14:43] Extension Version: "3.20.0".
["INFO" - 12:14:43] Loaded module 'prettier@1.19.1' from '/home/david/Code/JavaScript/davidbailey.codes/node_modules/prettier/index.js'
["INFO" - 12:14:43] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 12:14:43] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["ERROR" - 13:05:33] Error formatting document.
["ERROR" - 13:05:33] Cannot find module 'prettier-plugin-toml' from '/home/david/Code/JavaScript/reaware'
Error: Cannot find module 'prettier-plugin-toml' from '/home/david/Code/JavaScript/reaware'
	at Function.sync (/home/david/Code/JavaScript/davidbailey.codes/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:15946:13)
	at /home/david/Code/JavaScript/davidbailey.codes/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:44141:29
	at Array.map (<anonymous>)
	at loadPlugins (/home/david/Code/JavaScript/davidbailey.codes/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:44133:59)
	at /home/david/Code/JavaScript/davidbailey.codes/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:44205:16
	at Object.format (/home/david/Code/JavaScript/davidbailey.codes/node_modules/.pnpm/registry.npmjs.org/prettier/1.19.1/node_modules/prettier/index.js:44226:12)
	at /home/david/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:18554:45
	at t.default.safeExecution (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:18576:21)
	at t.default.<anonymous> (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:18554:23)
	at Generator.next (<anonymous>)
	at s (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.20.0/dist/extension.js:18251:19)
["INFO" - 13:05:33] Formatting completed in 25.171317ms.
["INFO" - 13:05:33] Loaded module 'prettier@1.19.1' from '/home/david/Code/JavaScript/davidbailey.codes/node_modules/prettier/index.js'
["INFO" - 13:05:33] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 13:05:33] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
```

**Comment by ntotten** [comment]
I think I have figured out what is going on with the caching of the path, but I think the error is actually correct in that the path you had provided isn't valid. Prettier config asks to specify valid paths to the module, so your first config `"plugins": ["prettier-plugin-toml"]` is invalid.

Your second configured path is valid `./node_modules/prettier-plugin-toml`.

I'll investigate this some more when I have time, but I think this isn't something that needs to be fixed in the extension.

**Comment by yet-another-dev** [comment]
@davidbailey00 From your Prettier output log it seems you're using pnpm. I've noticed a similar issue related to Prettier plugins and pnpm ([see here](https://github.com/prettier/plugin-pug/issues/113)). Perhaps this is an issue with this extension not playing nicely with repositories that use pnpm?
