### ISSUE TITLE
trim final newline

### ISSUE THREAD

**Issue by Kordian-Dziwisz** [prettier/prettier-vscode#1249]
**Is your feature request related to a problem? Please describe.**
VSCode offers an option to trim final newline, prettier overwrites this function.

**Describe the solution you'd like**
Option to trim final newlines in prettier config

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
