### ISSUE TITLE
Prettier problem with .svelte files

### ISSUE THREAD

**Issue by bmoreira10** [prettier/prettier-vscode#1250]
I'm trying to use the prettier with svelte files and it's not formating and neither detecting (bottom right on vscode) but in JS files it works and JSON.

**VS Code Version**: 1.41.1
**OS and version**: Linux x64 5.3.0-26-generic (Linux Mint)

When I save in a JS file it works and I have logs but when I try to save to format a svelte file it does not log anything on the prettier console.

settings.json
```
{
    "workbench.colorTheme": "Material Theme",
    "workbench.iconTheme": "material-icon-theme",
    "window.zoomLevel": 1,
    "svelte.plugin.svelte.format.enable": false,
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
}
```

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by bmoreira10** [comment]
I can't provide more information I think, I don't have logs when I try to format the file (on save or manually).
