### ISSUE TITLE
Prettierignore paths are relative to .prettierignore file, not relative to project root

### ISSUE THREAD

**Issue by DanielPower** [prettier/prettier-vscode#1252]
### Summary
.prettierrc and .prettierignore are located in /foobar/portal/static, where /foobar is the workspace root.

This works for our prettier githook, which is run from the project root 

When running prettier from the CLI using `--config ./portal/static/.prettierrc --ignore-path ./portal/static/.prettierignore`, it correctly reads the paths as being relative to the workspace root. But when running prettier from VS Code with this extension, it expects paths relative to the location of the .prettierignore.

The .prettierignore file is written to use paths relative to the workspace root, and I would like to be able to have prettier-vscode also run relative to the workspace root.

For example:
`portal/static/javascript/lightbox.js`

is ignored when running from the CLI from the project root. But is not ignored when running from prettier-vscode, because it expects `javascript/lightbox.js`.

### Expected result
Ignore paths would be relative to project root, not the location of the .prettierignore

### Actual result
Ignore paths were relative to the .prettierignore

### Additional information

**VS Code Version**:
1.42.0

**Prettier Extension Version**:
3.20.0

**OS and version**:
OSX Catalina 10.15.3

```
["INFO" - 10:57:53 AM] Formatting /Users/daniel/Development/foobar/portal/static/javascript/lightbox.js
["INFO" - 10:57:53 AM] Using ignore file (if present) at /Users/daniel/Development/foobar/portal/static/.prettierignore
["INFO" - 10:57:53 AM] Loaded module 'prettier@1.18.2' from '/Users/daniel/Development/foobar/portal/static/node_modules/prettier/index.js'
["INFO" - 10:57:53 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 10:57:53 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:57:53 AM] Prettier Options:
{
  "filepath": "/Users/daniel/Development/foobar/portal/static/javascript/lightbox.js",
  "parser": "babel",
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 100,
  "quoteProps": "as-needed",
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "useTabs": false
}
```

**Comment by macgyver** [comment]
somewhat related - i'm noticing that `.prettierignore` files that are *not* in the project root are not being respected, e.g. i have a repo with prettier files in the `app` folder, e.g. `app/.prettierrc` and `app/.prettierignore` - when I open the `app` folder the ignore file is used correctly but when I open the workspace root the prettierignore file is not used.

**Comment by macgyver** [comment]
Is anybody on the core team here going to triage issues? I'm sort of interested in helping out but I'd like to know that someone with the power to merge PRs has confirmed the issue and thinks it is fixable.

**Comment by ntotten** [comment]
So right now we are trying to match the behavior of the prettier CLI as closely as possible: https://prettier.io/docs/en/ignore.html#ignoring-files

I am reluctant to deviate from that, but happy to discuss better options.

**Comment by macgyver** [comment]
oh interesting.. is there any reason the resolution for a `.prettierignore` file differs from the way the config file is resolved? it seems consistent with `.gitignore` for example to be "resolved starting from the location of the file being formatted, and searching up the file tree until a ... file is (or isn't) found."

**Comment by ntotten** [comment]
To be honest, I'm not really sure why it is this way. There is a discussion here: https://github.com/prettier/prettier/issues/4081

**Comment by macgyver** [comment]
ok I'll follow up there - currently I'm dealing with this by adding both the repo root and the sub-folder with the ignore file to the workspace and it seems to generally be working, but it's defnitely kind of weird - do you wanna close this ticket for now?

**Comment by ntotten** [comment]
Sure, ill close this. Thanks!
