### ISSUE TITLE
Running slow on `save Participants`

### ISSUE THREAD

**Issue by mascardoso** [prettier/prettier-vscode#1253]
### Summary

VsCode Prettier extension is slowing down onSave. 

### Github Repository to Reproduce Issue

https://github.com/prettier/prettier-vscode

### Steps To Reproduce:

1. Open vscode
2. Add the formatOnSave option
3. Install latest extension from prettier. Activate it.
2. Open a js file.
2. Save.

### Expected result

Saving should have been instant.

### Actual result

Saving can take up to a minute.

### Additional information

<img width="709" alt="Screenshot 2020-02-18 at 12 11 47" src="https://user-images.githubusercontent.com/2275908/74732048-aa365880-5249-11ea-9c3b-d2d2a6b891e8.png">

**VS Code Version**:  1.42.1

**Prettier Extension Version**: 3.20.0

**OS and version**: macOS Mojave 10.14.6

## Prettier Log Output

```
["INFO" - 12:16:31 PM] Extension Name: "prettier-vscode".
["INFO" - 12:16:31 PM] Extension Version: "3.20.0".
["INFO" - 12:16:31 PM] Loaded module 'prettier@1.19.1' from '/Users/cardomar/Web/uxf-sple-tf/node_modules/prettier/index.js'
["INFO" - 12:16:31 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 12:16:31 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 12:16:34 PM] Formatting /Users/cardomar/Web/uxf-sple-tf/src/sple/resources/run-export-webview.js
["INFO" - 12:16:34 PM] Using ignore file (if present) at /Users/cardomar/Web/uxf-sple-tf/.prettierignore
["INFO" - 12:16:34 PM] Loaded module 'prettier@1.19.1' from '/Users/cardomar/Web/uxf-sple-tf/node_modules/prettier/index.js'
["INFO" - 12:16:34 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 12:16:34 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 12:16:34 PM] Prettier Options:
{
  "filepath": "/Users/cardomar/Web/uxf-sple-tf/src/sple/resources/run-export-webview.js",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "printWidth": 120,
  "endOfLine": "lf",
  "semi": false,
  "singleQuote": true
}
["INFO" - 12:16:34 PM] Loaded module 'prettier-eslint@unknown' from '/Users/cardomar/Web/uxf-sple-tf/node_modules/prettier-eslint/dist/index.js'
["INFO" - 12:16:34 PM] Formatting using 'prettier-eslint'
["INFO" - 12:16:39 PM] Formatting completed in 769.107933ms.
```

**Comment by ntotten** [comment]
I’m not sure I understand. The formatting took 769ms. Additionally, VSCode times out formatting after 1500ms be default so it shouldn’t be possible for formatting to take a minute. I’ll need additional information to reproduce this.

**Comment by brombomb** [comment]
@ntotten Not anymore.  https://code.visualstudio.com/updates/v1_42#_handling-slow-save-operations

**Comment by cjroebuck** [comment]
I think this should be reopened.

I'm also seeing very long save times recently (probably from when VSCode moved away from the timeout option as referenced by @ntotten). Disabling the prettier extension is the only thing that solves the issue right now.

```
["INFO" - 9:50:32 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 9:50:32 PM] Prettier Options:
{
  "filepath": "/Users/....js",
  "parser": "babel",
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "printWidth": 80,
  "singleQuote": false
}
["INFO" - 9:50:32 PM] Loaded module 'prettier-eslint@unknown' from '/Users...'
["INFO" - 9:50:32 PM] Formatting using 'prettier-eslint'
["INFO" - 9:50:43 PM] Formatting completed in 677.137701ms.
```

Although the logs say that formatting *only* takes 677ms, **the actual time from when I hit cmd+s to `Formatting completed..` is 11 seconds.**

**Comment by chanmathew** [comment]
Having this issue as well

**Comment by kyds3k** [comment]
Having the same issue, saving a css file.

**Comment by syzhakov** [comment]
same issue...

**Comment by sgwanlee** [comment]
got same issue

**Comment by Xamsix** [comment]
Same issue right now
