### ISSUE TITLE
Invalid pretterPath returns wrong error message.

### ISSUE THREAD

**Issue by towry** [prettier/prettier-vscode#1258]
message.ts:

https://github.com/prettier/prettier-vscode/blob/9476a014323f41da7e89a05f133671a97a53ac07/src/message.ts#L4

warnOutdatedPrettierVersion:
https://github.com/prettier/prettier-vscode/blob/9476a014323f41da7e89a05f133671a97a53ac07/src/NotificationService.ts#L35

The extension keep giving outdated prettier version notification, but I have the latest version 1.19.1 installed.

```
./node_modules/.bin/prettier --version
1.19.1
```

The settings:

![截屏2020-02-28下午12 32 41](https://user-images.githubusercontent.com/8279858/75510596-710a9f00-5a26-11ea-81bc-22ca3501a855.png)

**Comment by ntotten** [comment]
The message is wrong. I’ll look into it. The issue though is you set the prettier path to the bin path, not the module. Change it to ./node_modules/prettier and it should work as expected.
