### ISSUE TITLE
Update to Prettier 2.0

### ISSUE THREAD

**Issue by tkafka** [prettier/prettier-vscode#1275]
Prettier has released a 2.0 version, with an improvement of code formatting - would it be hard to update the dependency?

https://prettier.io/blog/2020/03/21/2.0.0.html

EDIT: Aha, there is a PR already - awesome! https://github.com/prettier/prettier-vscode/pull/1272

**Comment by madsgodvinjensen** [comment]
Plus one for reviewing and merging the open PR 🙏

**Comment by wsjscss** [comment]
Waiting for this

**Comment by SkeLLLa** [comment]
Please do that update as semver-major for this extension, cause prettier 2.0 introduces some changes that couldn't be changed and at the same time they go against common codestyle practices. So many users may decide to stay on previous version.

**Comment by ntotten** [comment]
v4.0.0 uses prettier 2
