### ISSUE TITLE
Prettier version cannot be resolved, when installed globally

### ISSUE THREAD

**Issue by robinmanuelthiel** [prettier/prettier-vscode#1296]
### Summary

When installing Prettier globally (via brew for example), the plugin can not fetch its version, so it throws an error message and falls back to the bundled version of prettier.

### Steps To Reproduce:

1.  Install Prettier via `brew install prettier`
1.  Change the **Prettier Path** settings to `/usr/local/bin/prettier`
1. Format a document

### Expected result

The document should be formatted with the globally installed version of prettier.

### Actual result

An error message appears: "Your project is configured to use an outdated version of prettier that cannot be used by this extension. Upgrade to the latest version of prettier."

The logs show the following:

```
["INFO" - 6:44:31 PM] Loaded module 'prettier@unknown' from '/usr/local/bin/prettier'
["ERROR" - 6:44:31 PM] Outdated version of prettier installed. Falling back to bundled version of prettier.
```

Looks like the problem is the **unknown** version it gets.

**Comment by ntotten** [comment]
The extension doesn't support the bin path of prettier. You need to point the Prettier Path to the node module root directory. I am not exactly sure where that is when you do a brew install.

The error message for this is wrong - that is tracked in #1258.
