### ISSUE TITLE
does't work in multiple project workspace

### ISSUE THREAD

**Issue by mhy-web** [prettier/prettier-vscode#1297]
### Summary
Can not formate and find global settings.js when a workspace is opening with multiple project.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:'
1. mkdir such as demo
2. cd demo and init a vue project by vue-cli 
3. init other project with express
4. config eslint and others
5. use prettier to formate vue or js file, then it's not worked

### Expected result

can not formate and get config of global setting.js

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:  1.43.2

**Prettier Extension Version**: 4.0.0

**OS and version**: mac os 10.14.5 (18F132)

## Prettier Log Output

```
["INFO" - 11:27:39 AM] Require config set to true and no config present. Skipping file.
```

**Comment by ntotten** [comment]
Can you provide a sample repository I can use to reproduce this? It seems there might be some significant things in the step `config eslint and others`.
