### ISSUE TITLE
Support different trailingComma settings per language

### ISSUE THREAD

**Issue by chrisleck** [prettier/prettier-vscode#130]
Our project uses `trailingComma: all` for typescript and `trailingComma: es5` for javascript.  Is there a way to set that up here?

**Comment by CiGit** [comment]
I don't see a way to do that. Except if your files are in different workspaces...

**Comment by CiGit** [comment]
Maybe once if vscode supports language settings for extensions
https://github.com/Microsoft/vscode/issues/26707

**Comment by CiGit** [comment]
Would #167 fix this issue?

**Comment by chrisleck** [comment]
If the multi-language setting stuff makes it in, it looks like it will fix this issue.
