### ISSUE TITLE
Provide an option in VSCode to format the whole project

### ISSUE THREAD

**Issue by shamilovtim** [prettier/prettier-vscode#1300]
**Is your feature request related to a problem? Please describe.**
The latest breaking changes in v2 are only modifying my files one at a time as I work on them rather than across my whole project

**Describe the solution you'd like**
An option in CMD-Shift-P that lets you format the entire project with Prettier

**Describe alternatives you've considered**
Command line is an option but using this plugin should not require ejecting to the command line

**Comment by ntotten** [comment]
I am not really sure this is a viable option. We don't really know what files people would want to run prettier on. Given that this is a rare breaking change in prettier, I think using the CLI is the best option.
