### ISSUE TITLE
Version 4.0.0 and up seems to add trailing commas

### ISSUE THREAD

**Issue by jeffsawatzky** [prettier/prettier-vscode#1301]
Version 4.0.0 and up seems to add trailing commas to javascript files. I have even set the trailing comma setting to none in the preferences and it doesn't seem to care.

When I install 3.20.0 I don't get this problem

**Comment by freund17** [comment]
Seems related to https://github.com/prettier/prettier-vscode/issues/1290

**Comment by trivikr** [comment]
> I have even set the trailing comma setting to none in the preferences and it doesn't seem to care.

@jeffsawatzky You either define your own prettier configuration or use [prettier-v1-config](https://www.npmjs.com/package/prettier-v1-config)
Details: https://github.com/prettier/prettier-vscode/issues/1290#issuecomment-610468847

**Comment by jeffsawatzky** [comment]
@trivikr, so are the VS Code preferences useless now? If so, can they be removed as they cause confusion? Or can instructions be added to them on how to make it work?

Also, it would be sweet if prettier could use the `eslintrc.js` settings where appropriate so that we don't need to keep that and `.prettierrc` in sync

**Comment by trivikr** [comment]
> So are the VS Code preferences useless now?
> If so, can they be removed as they cause confusion?
> Or can instructions be added to them on how to make it work?

I believe you mean [VS Code Settings](https://github.com/prettier/prettier-vscode#visual-studio-code-settings)
My personal recommendation is to use [Prettier Configuration file](https://prettier.io/docs/en/configuration.html), so that your code is not tightly coupled to any editor.

As per documentation in README, VS Code setting would be used if Prettier configuration is absent.

**Comment by hezhongfeng** [comment]
VS Code Settings dont work about trailing commas,so I add a `.prettierrc` file in my project， it work well.So I think its a bug about `VS Code Settings `?

```
// .prettierrc
{
  "trailingComma": "none"
}
```

**Comment by ntotten** [comment]
As @trivikr mentioned. The VS Code preferences are ONLY used if no prettier config file is detected. So if you set trailingComma to none in VS Code, but have a prettier config that does NOT have `trailingComma` and you do NOT have a local version of prettier less than 2.0 installed, then the built in prettier will be used with your local config file and it will use prettier 2.0 defaults (which for `trailingComma` is `es5`).

The solution (as is ALWAYS recommended) is to set your prettier config file to exactly what you want and not rely on global fullbacks, etc. We also recommend you install prettier locally in your project so you can determine the exact version of prettier you are using.

**Comment by jeffsawatzky** [comment]
@ntotten I don't have a .prettier config file, so I assume that the VS Code Settings should be used.

I also don't have any local version of prettier installed in the project, so I assume the one bundled with the extension should be used (which should be 2).

However, it still does not seem to use the setting the VS Code.

**Comment by mansn** [comment]
@jeffsawatzky What does the Prettier log output in VSCode say?
You don't have any .editorconfig either I guess? Because that also counts as local configuration which will cause VS Code configuration to be ignored.

**Comment by jeffsawatzky** [comment]
Yeah, there is an editor config, guess that was it. Though that is a little unintuitive given that editorconfig has no option for trailing comma so I wouldn't have thought that was the cause. But good to know for the future. Also, it wasn't mentioned here:
https://prettier.io/docs/en/configuration.html

**Comment by anywhereiromy** [comment]
@jeffsawatzky How did you solve having an .editorconfig file but removing trailing comma?

**Comment by jeffsawatzky** [comment]
I didn't. I ended up adding a .prettierrc config file which basically makes the VS code preferences useless. I feel like they should just be removed.
