### ISSUE TITLE
Unnecessary semicolon issue in arrow function

### ISSUE THREAD

**Issue by asadalisandhu** [prettier/prettier-vscode#1304]
public _getGroupLinks = (groups: any): void => {
    this._getGroupThumbnails(groups);
  };

**Comment by asadalisandhu** [comment]
I have tried this but no luck:
    "semicolon": [true, "always", "ignore-bound-class-methods"],
https://github.com/wmonk/create-react-app-typescript/issues/263

**Comment by ntotten** [comment]
I'm not sure what this issue is related to.  This `"semicolon": [true, "always", "ignore-bound-class-methods"],` isn't a setting of this extension or prettier. Perhaps this is a bug for https://github.com/prettier/prettier-eslint?
