### ISSUE TITLE
Result is not as expected

### ISSUE THREAD

**Issue by janwagner** [prettier/prettier-vscode#1313]
Hi. I just don't get it why my markup is not being formatted like it should be. By trying the [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOiDEQEYFwC0MEEBdRATk5AQK4BbKNQB8GHPmJkqIOjChMA5lwj8ADriwl1xAJ5MAZowAeuY3BNNVAdzGo6-GKyhTSFavNdem6OIaJ+AhhcH0xIRWgCPVwiMBgcOGoYPXU4WUdnaHsdIldCd1lw6CVo9QALXGKoUtTylnpGJmxMODsQcQB6XKguzJdxfug3GU8FUIVff0DgicVqpii9ZNT0zycXHPU8kY8QatqKqojD+p0CTBhm1vaunr6N6C6sbGecURAAGhAIdQToEjIUDcWwABW4CEBKCIBBsRD0gO+dC4cQA1nAYABlbZgTA1ZAwLj8ODfcowQQEADq5UucFyYDgmMhlxwlz0yHAZC++ygJDgXBgoJRSkERGQAQIfO+ACsSCYAEIosDorFEQRwAAyeLg4phUpAspMmLxpTgAEV+BB4LrJSSQNsuHyuBzOHQ4ARueouHiYJTMOgYOVkAAOAAM3y9ED5lJR6g5Xrp-OwOu+AEdLfAhb8oSBSEwoHA4H50NyuHB05gy0KiCKxUgJfq+YJMASiXaSCbGBarTr63q7bQ6H6A0GkAAmb6EoiYC41ADCEEEoo5dIArNz+HyACr0KENu3YYkASSgflgmLA3r+AEFT5iUowbXyAL7PoA), everything looks right, but in VSC (default prettier settings) the markup is not very readable and looks like [this](https://pastiebin.com/5e90261971d32).

Does anybody knows what i am doing wrong?
Thank you!

**Comment by ntotten** [comment]
Are you sure you have prettier set as your default formatted in VS Code? https://github.com/prettier/prettier-vscode#default-formatter

If that's not it, please open a new bug with the full details and the logs: https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue
