### ISSUE TITLE
Please add a configuration for space after 'function' keyword

### ISSUE THREAD

**Issue by odedltr** [prettier/prettier-vscode#1314]
Hi, your VSC plugin upgrade to version 4.0.0 included forcing a space between 'function' keyword and the parentheses.

Up Until version 4.0.0: `window.addEventListener('event', function(e) {});`
As from version 4.0.0: `window.addEventListener('event', function (e) {});`

I prefer to ommit space before parentheses and really don't wish to reformat all my code according to this. Can this be configurable?

**Comment by polarathene** [comment]
If you only rely on the plugin to provide prettier and it's configuration(default from prettier), you'll get updates of newer releases of prettier with newer versions of this plugin, that would be expected right?

So you are not providing a local or global version of prettier, nor a config of your own to change the behaviour? You will probably find the reason for this issue you're experiencing came with the [`2.0.0` release of Prettier](https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot) where it is specifically mentioned as a change:

> Previously, a space would be added after the `function` keyword in function declarations, but not in function expressions. Now, for consistency, a space is always added after the `function` keyword. The only exception is generator declarations where `function*` is treated as a whole word.

There is no mention of disabling this change, nor is it listed as an [option in the prettier docs](https://prettier.io/docs/en/options.html), so no you probably can't configure it differently. You'd need to use an older version of prettier, or run something else afterwards to revert that rule. 

Perhaps with eslint formatting after prettier, [this seems to be the same rule](https://eslint.org/docs/rules/space-before-function-paren), although when using prettier it's discouraged to have eslint use formatting rules afaik.
