### ISSUE TITLE
Default formatting changed in v4

### ISSUE THREAD

**Issue by lorensr** [prettier/prettier-vscode#1317]
With v4, after formatting JS file, trailing commas are added, and parentheses are added around single arguments.

When I downgrade to `v3.20` and reformat, the commas and parentheses are removed.

### Additional information

**VS Code Version**: 1.43.2

**Prettier Extension Version**: 4.*

**OS and version**: Mac 10.15.4

## Prettier Log Output

```
["INFO" - 12:50:38 AM] Formatting /Users/me/gh/guide-api/src/resolvers/User.js
["INFO" - 12:50:38 AM] Using ignore file (if present) at /Users/me/gh/guide-api/.prettierignore
["INFO" - 12:50:38 AM] Using bundled version of prettier.
["INFO" - 12:50:38 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 12:50:38 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 12:50:38 AM] Prettier Options:
{
  "filepath": "/Users/me/gh/guide-api/src/resolvers/User.js",
  "parser": "babel",
  "singleQuote": true,
  "semi": false
}
["INFO" - 12:50:38 AM] Formatting completed in 30.940685ms.
```

This bug also experienced by @sbreakey

**Comment by ntotten** [comment]
This is the expected behavior in the new version of Prettier. 

See announcement blog post for changes: https://prettier.io/blog/2020/03/21/2.0.0.html

See VS Code extension docs for how configuration works: https://github.com/prettier/prettier-vscode#configuration

**Comment by lorensr** [comment]
Ah, thanks!

For others: I had to add these lines to my project's `.prettierrc`:

```
trailingComma: none
arrowParens: avoid
```

Note that a local config file overrides config in VS Code settings.

**Comment by harbulot** [comment]
@ntotten Is there a way to downgrade the version of Prettier used by the VS plugin, so as to revert to the previous formatting rules?

**Comment by sbreakey** [comment]
> @ntotten Is there a way to downgrade the version of Prettier used by the VS plugin, so as to revert to the previous formatting rules?

Yes, that's what I did in the end. Well, I downgraded the vsplugin itself. In VS Code I went to extensions (Ctrl+Shift+X) searched for "prettier" and then clicked on the cog. There is an option to "Install Another Version...". 3.20.0 worked for me.

**Comment by harbulot** [comment]
@sbreakey Thanks for the suggestion. Downgrading the whole plugin seems to be the way to go for now. I'm just guessing there's a point where version 3.x will no longer be compatible with a future release of VS Code.

The settings described above are a step in the right direction, but they don't fix everything unfortunately. Some changes in Prettier 2.0 are non-customisable and different from the previous versions, which causes a lot of unnecessary changes. See prettier/prettier#7972, for example.

It would be good to either (a) be able to keep older versions of Prettier running with newer versions of the VS Code plugin or (b) having options in Prettier to keep the formatting consistent with the previous versions. (The latter would probably make more sense.)

**Comment by ntotten** [comment]
I am going to lock this. The changes to config are not something that we do in the extension. This is something the core prettier team has decided and we simply use prettier in the extension.
