### ISSUE TITLE
Trailing comma existence

### ISSUE THREAD

**Issue by jacky-ew** [prettier/prettier-vscode#1318]
### Summary

trailing commas added on save.

### Github Repository to Reproduce Issue

-

### Steps To Reproduce:

1.  open js files, tap Save
2. trailing commas added to each end of line
3. example: style={{ fontSize: 10, color: "pink", }} <-- trailing comma

### Expected result
no trailing comma on save

_Describe what should have happened_.

### Actual result
on save trailing comma is added

_Describe what actually happened instead_.

### Additional information
i left an issue on vs code github. I change the formatter ` "prettier.trailingComma": "none"` in settings.json, but not working, then i change in the prettierrc.json then only it works. Does not happened before. Happens after a vscode update i thk (not too sure what updates and caused the issue).
my confusion is , is prettier using both vscode settings and prettierrc.json? can i make sure prettier plugin only follows the prettierrc.json i put in? thanks

_Feel free to attach a screenshot_.

**VS Code Version**: 1.44.0

**Prettier Extension Version**: 4.2.0

**OS and version**: macos 10.15.4

## Prettier Log Output

```
["INFO" - 6:21:20 PM] Extension Name: "prettier-vscode".
["INFO" - 6:21:20 PM] Extension Version: "4.2.0".
["INFO" - 6:21:20 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 6:21:20 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 6:33:00 PM] Formatting /Users/dev/Documents/easypass/js/components/register/index.js
["INFO" - 6:33:00 PM] Using ignore file (if present) at /Users/dev/Documents/easypass/.prettierignore
["INFO" - 6:33:00 PM] Using bundled version of prettier.
["INFO" - 6:33:00 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 6:33:00 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 6:33:00 PM] Prettier Options:
{
  "filepath": "/Users/dev/Documents/easypass/js/components/register/index.js",
  "parser": "flow",
  "useTabs": true,
  "tabWidth": 2,
  "endOfLine": "lf",
  "semi": true,
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "printWidth": 120,
  "trailingComma": "none",
  "arrowParens": "avoid"
}
["INFO" - 6:33:01 PM] Formatting completed in 708.733815ms.

```

**Comment by kachkaev** [comment]
This is expected behaviour in the new versions. See:

* https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-trailingcomma-to-es5-6963httpsgithubcomprettierprettierpull6963-by-fiskerhttpsgithubcomfisker

* https://github.com/prettier/prettier-vscode#configuration
