### ISSUE TITLE
Ignore pragmas & .prettierignore not working

### ISSUE THREAD

**Issue by truchi** [prettier/prettier-vscode#1319]
Up-to-date VSCode and prettier-vscode.
Empty configPath & ignorePath settings.
Ignore file in project root as expected by prettier.
Both multi-root & non multi-root.

Tried everything found in other issues.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
