### ISSUE TITLE
JSX didn't format correctly when set quote_type to 'single' in .editorconfig file

### ISSUE THREAD

**Issue by trlanfeng** [prettier/prettier-vscode#1325]
### Summary

When set the quote_type to 'single' in EditorConfig file, the prettier will ignore the settings in vscode.
In JSX file, the js part will be format correctly, but the html part does not.
Line 2 will be format to `const a = '123'`, but in line 4 , the quote will not be changed.

```
class TestComponent extends Component {
  const a = "123";
  render() {
    return (<div b="456"></div>)
  }
}
```

### Expected result

```
class TestComponent extends Component {
  const a = '123';
  render() {
    return (<div b='456'></div>)
  }
}
```

### Actual result

```
class TestComponent extends Component {
  const a = '123';
  render() {
    return (<div b="456"></div>)
  }
}
```

**VS Code Version**:    1.44.0

**Prettier Extension Version**:    4.3.0

**OS and version**:   macOs 10.15.4

## Prettier Log Output

```
["INFO" - 2:21:21 PM] Formatting /Users/___/Code/Personal/gplus/src/components/assistantmycase/index.tsx
["INFO" - 2:21:21 PM] Using ignore file (if present) at /Users/___/Code/Personal/gplus/.prettierignore
["INFO" - 2:21:21 PM] Loaded module 'prettier@1.19.1' from '/Users/___/Code/Personal/gplus/node_modules/prettier/index.js'
["INFO" - 2:21:21 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 2:21:21 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 2:21:21 PM] Prettier Options:
{
  "filepath": "/Users/___/Code/Personal/gplus/src/components/assistantmycase/index.tsx",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 2,
  "singleQuote": true
}
["INFO" - 2:21:21 PM] Formatting completed in 32.135806ms.
```

**Comment by ntotten** [comment]
Looks like a potential bug in prettier itself. Please file on https://github.com/prettier/prettier

See: https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgCpyYwDCEAtgA7QIw5wAe8UAJrqZdbDsADpQ45IUIjnQ4AvDgDkARgBMAZikBuPgIBOCZnHUAKAJTc1AnJpgBXdf10AeZgEsAbjgBG4qQBYArADYpAPhsAegdHf31jAF8+SJAAGhAIChh7aExkUHR1dQgAdwAFLIR0lHRUXPQAT3SEl3V0MABrOBgAZQoG+ygAc2QYdXM4BIALGDJUAHVh+3hMDrA4VuKZpxnK5HBseJAuzB0YfPrusnRkADMyvYSAK0x6ACF6ppbW9DI4ABkuuHPLoZBbvRWl1uqg4ABFcwQeC-VBXEAddR7dQbGCVCiEMDqezJbYUbGwCb2ZgwYbIAAcAAYEviIHsJvUKBt8YQdI4fgkAI5Q+CHJIlEBYAC0UDgcG0zG2mm59k0h3Qx1OSAucP+ezI9j6AzVILBkOhPyQ-UGCRg6BcRJJZKQclN9XsqBB7BOG0IXm25j2eHNJRV8McgwAkiwaK0sTiYABBFitNFg2F7SKRIA
