### ISSUE TITLE
VSCode Prettier format on save messes up 

### ISSUE THREAD

**Issue by stoplion** [prettier/prettier-vscode#1326]
Been using VSCode Prettier format on save feature for a while.

Lately is CONSTANTLY makes mistakes and misformats Javascript.

For example:

const foo = 123

 [save] 

const foo = 1;23

I've disabled it for now, but is there some way to make this not hap

Mac OS, VSCode latest, and latest plugin version.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by stoplion** [comment]
https://stackoverflow.com/questions/61215212/vscode-prettier-format-on-save-messes-up-formatting/61215974#61215974

How do you include a GitHub repo? 
The bug repro setup is: any JS file, VSCode, and Prettier
