### ISSUE TITLE
Coloring problem with ? operator in Reactjs

### ISSUE THREAD

**Issue by KheiriGitHub** [prettier/prettier-vscode#1330]
### Summary

When the ?. operator or ?? operator is used as an expression in Reactjs components the rest of the code will be as string coloring.

### Expected result

![image](https://user-images.githubusercontent.com/48985255/79325710-e672f600-7f26-11ea-9dd0-333de277113c.png)

### Actual result

![image](https://user-images.githubusercontent.com/48985255/79325791-086c7880-7f27-11ea-894d-f8571a79c47e.png)

**VS Code Version**:
1.44.1
**Prettier Extension Version**:
4.4.0
**OS and version**:
windows 10 Enterprise LTSC
## Prettier Log Output

```
["INFO" - 2:14:52 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 2:14:52 PM] Extension Version: 4.4.0.
["INFO" - 2:14:52 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 2:14:53 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]

```

**Comment by ntotten** [comment]
Prettier doesn't have anything to do with the syntax highlighting. This may be a bug in VS Code.

**Comment by KheiriGitHub** [comment]
Thanks a lot
