### ISSUE TITLE
Add option for notification / code highlight on parsing errors

### ISSUE THREAD

**Issue by luastoned** [prettier/prettier-vscode#1332]
**Is your feature request related to a problem? Please describe.**
Lets assume I don't run a linter because I'm working on an external code base, I run prettier and nothing happens. The small warning icon often goes under the radar when something goes wrong.

**Describe the solution you'd like**
Two options:

- Highlight the offending code in the editor
- Show a notification with a reduced error message, maybe something like this:

```
Prettier: Error formatting document
  07 | ,typo
> 08 | const fn1 = (...) => {
     | ^
  09 | 
```

**Additional context**
This should of course be an option configurable via settings.
I feel like I can't be the only one overseeing the small warning from time to time.

**Comment by ntotten** [comment]
I like the idea of highlighting the error line and putting the the error in the errors panel. I’ll try to look into it soon.

**Comment by ntotten** [comment]
Actually, thinking about this a bit more. Doesn't the language service provide this already? For example, if i make a typo in javascript, vscode already displays a warning about the typo. Can you give me a repro scenario that can show this would be useful beyond features of the existing languages?

**Comment by luastoned** [comment]
To my understanding you need to have other plugins (ie. ESLint/TSLint or TypeScript) installed to receive those kind of warnings. When you just have VSCode / Prettier no warnings are displayed.

**Comment by ntotten** [comment]
VSCode provides warnings for invalid code in the problems view. Code that cannot be parsed should always show as an error even without any extensions installed.

This seems to be going beyond what prettier is meant to do - it shouldn’t be used as a tool for validating code.

I’m open to the idea, but I’d need to understand a specific case where this is valuable.

**Comment by Nircek** [comment]
Well, maybe there are other extensions available but the option to turn on notifying of parser failure would be welcomed. At least by me as the user. Because at the moment (as I wrote in #1419) there is no sign that something went wrong.

**Comment by ntotten** [comment]
One thing to be aware of is that the icon on the toolbar for prettier will change when there is an error:

![image](https://user-images.githubusercontent.com/282782/84919444-ec549700-b08f-11ea-8beb-3b7b7c92df68.png)

**Comment by Nircek** [comment]
Thanks, I haven't seen that. Good to know!

>  Because at the moment (as I wrote in #1419) there is no sign that something went wrong.

So there is a sign but it has to be seen by the user. :stuck_out_tongue:

But the failure notification also would be good so I think you should at least consider it.
