### ISSUE TITLE
Seamlessly handle re-loading Prettier if it has been changed

### ISSUE THREAD

**Issue by JHilker** [prettier/prettier-vscode#1336]
**Is your feature request related to a problem? Please describe.**
Currently if the version of Prettier inside of a project changes (typically from an `npm` or `yarn` install), the version the extension uses becomes stale, still using the version it initially cached, leading to changes on save that may not match what the Prettier CLI would output. As this point reloading the VS Code window is necessary in order to have the extension pick up the correct, new, version of Prettier and use it instead.

**Describe the solution you'd like**
I think a working solution here would be to setup a file watcher for the found modules directory. If a change is made to any of those files / the directory itself, then we can invalidate the existing cache we have, allowing the next save to re-detect the module it should be using to run Prettier on the file.

**Describe alternatives you've considered**
An alternative solution would be to add a command which can reset the cache on demand. This would be be slightly better than reloading the entire window, but would still need to be on demand, meaning you have to know you need to do it.

**Additional context**
I've primarily hit this problem when rolling out a Prettier upgrade org-wide. People tend to upgrade their dependencies, then hit VS Code formatting things improperly and reach out for support. FWIW I've hit the same problem with the VS Code ESLint extension 😞.

Figured I'd toss up an issue for this for discussion @ntotten. I've also started a WIP branch so you can get a general sense of what I'm thinking about here: https://github.com/prettier/prettier-vscode/compare/master...JHilker:experiment-with-file-watching. It's definitely a bit messy with debugging logic, but is for the most part fully functional (aside from the global module resolution logic) if you want to check it out locally. I'm also planning on adding tests before tossing up a PR if you think this is a change you'd like to see in the extension.

**Comment by ntotten** [comment]
I'm certainly open to this. It's something we have tried to handle, but there always seems to be more cases that get missed. We also need to be careful about perf (too many file watchers, etc.) and unneeded reloads.

**Comment by ntotten** [comment]
Have you had a chance to test this in v6? I think this may have been addressed, but I'm not certain.

**Comment by JHilker** [comment]
Just did some quick testing with 6.3.1 and it still seems to be a problem, at least for my use case. 

Though it looks like the log no longer specifies what version of Prettier is loaded making it a bit harder. I ended up swapping between 1.19 and 2.0 and was able to repro the new version not automatically getting picked up with [the change of the default of `arrowParens`](https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-arrowparens-to-always-7430httpsgithubcomprettierprettierpull7430-by-kachkaevhttpsgithubcomkachkaev).

**Comment by ntotten** [comment]
> log no longer specifies what version of Prettier is loaded making it a bit harder
Enable debug logs for the extension. I reduced the default logging.

**Comment by jedwards1211** [comment]
@ntotten
> too many file watchers, etc.

for local installs, does anything besides `node_modules/prettier/package.json` need to get watched for each project directory?

I wonder if just checking the `mtime` of `node_modules/prettier/package.json` each time before you run prettier would be sufficient and fast enough.

**Comment by JHilker** [comment]
On my WIP branch ages ago I was watching change/unlink/unlinkDir on the `modulePath` the extension was loading. I imagine looking at the `package.json` wouldn't be too much different, but I think the module path itself is also a fine indicator? Either way I don't think "too many file watchers" is too big a concern 🤞

**Comment by jedwards1211** [comment]
`package.json` is the only file that's guaranteed to be there and it's guaranteed to change if a different version gets installed.  So I always figured it's the best file to watch or look at mtimes of when making extensions that use locally installed tools

**Comment by ntotten** [comment]
Closing as there hasn't been any activity in some time.
