### ISSUE TITLE
Running 'Prettier - Code formatter’ Formatter

### ISSUE THREAD

**Issue by vchouhan** [prettier/prettier-vscode#1342]
Issue Type: <b>Bug</b>

<img width="533" alt="Screen Shot 2020-04-20 at 11 00 43 PM" src="https://user-images.githubusercontent.com/1222739/79821170-10c81780-835c-11ea-8826-be507800bf10.png">
<img width="1008" alt="Screen Shot 2020-04-20 at 10 36 34 AM" src="https://user-images.githubusercontent.com/1222739/79821172-10c81780-835c-11ea-9e89-09f9a016abdc.png">
 The editor.onSave functionality with the plugin crashes the editor especially while working with JSX files, the formatter is stuck in a loop.

Extension version: 4.4.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by gabrielsch** [comment]
I and my team were having the same problem on prettier 4.4.0, rolling back to 3.20.0 solved the issue.
