### ISSUE TITLE
Still can't format user settings.json in combination with editor.defaultFormatter

### ISSUE THREAD

**Issue by texastoland** [prettier/prettier-vscode#1343]
### Summary

_Reopening #911 moved from microsoft/vscode#95468_ which was reopening microsoft/vscode#79038.

Prettier appears to not recognize `settings.json` as a formattable file type. According to Code maintainers it's because the extension isn't registering for the appropriate URI scheme: https://github.com/microsoft/vscode/issues/95468#issuecomment-617061736. How can I help?

**VS Code Version**:

1.45.0-insider

**Prettier Extension Version**:

4.4.0

**OS and version**:

Mac OS X 10.15.4 19E287

## Prettier Log Output

No log

**Comment by ntotten** [comment]
I'm not going to do this myself, but if somebody wants to send a PR I'm open to accepting.

**Comment by texastoland** [comment]
Do you understand the source of the issue? Any guidance where to start? I've barely started getting my feet wet with extensions.

**Comment by ntotten** [comment]
Fixed in 4.7.0

**Comment by macintacos** [comment]
For others that might come here; this works when you switch `settings.json` to be associated with the `jsonc` format (I still got an error when it was considering it a JSON file). You can do this by adding `settings.json` to the `files.associations` array in.... `settings.json` 🙂
