### ISSUE TITLE
Json data after Prettier formatted and then the number is changed

### ISSUE THREAD

**Issue by rich77926** [prettier/prettier-vscode#1352]
### Summary

Json data after Prettier formatted and then the number is changed

### Steps To Reproduce:

1.  This is step 1.
![image](https://user-images.githubusercontent.com/45219321/80189535-685cd080-8645-11ea-941e-ac0cd603feff.png)

1.  This is step 2. 
![image](https://user-images.githubusercontent.com/45219321/80189567-73affc00-8645-11ea-99c6-7f5a5bdb9ed0.png)

1. This is step 3.
![image](https://user-images.githubusercontent.com/45219321/80189603-81fe1800-8645-11ea-90a6-b73eb47a1272.png)

### Expected result

The test value should not be changed.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
