### ISSUE TITLE
Activate prettier by presence of specific file

### ISSUE THREAD

**Issue by raelb** [prettier/prettier-vscode#1353]
I like using prettier for React code. However in most other cases I don't want to use prettier. So in these cases I add a `.prettierignore` file to the project.

Actually I would prefer if things worked the other way around, i.e.: by default prettier is not active, unless the project contains a specific file e.g. `.prettier`.

Perhaps there is already an option similar to this?

Thanks

**Comment by JHilker** [comment]
If you use the [`prettier.requireConfig`](https://github.com/prettier/prettier-vscode#prettierrequireconfig-default-false) option, it will only attempt to run prettier if it finds a [prettier config setup](https://prettier.io/docs/en/configuration.html).

An empty file named `.prettierrc` should be enough to trigger this and will use the default prettier settings if you don't already have a prettier config.

**Comment by raelb** [comment]
Thanks, that's just what I was looking for.
