### ISSUE TITLE
Problem formatting multiline CSS strings

### ISSUE THREAD

**Issue by janilahti** [prettier/prettier-vscode#1359]
### Summary
If CSS file has a string value which is split into multiple lines, newline character `\` inside the string is not handled correctly, affecting the rest of the formatting from that point forwards. Reference: https://drafts.csswg.org/css-values-3/#strings

### Github Repository to Reproduce Issue
https://github.com/janilahti/prettier-css-formatting-problem-demo

### Steps To Reproduce:
Use prettier-vscode default config

Clone the repo and open it with vscode.
Observe formatting problem.

### Expected result
CSS should be formatted properly even with multiline string values.

### Actual result
Formatting problem affecting everything below the problem point.

### Additional information
VS Code Version: 1.44.1

Prettier Extension Version: 4.4.0

OS and version: Windows 1909

### Prettier Log Output

```
["INFO" - 1:16:56 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 1:16:56 PM] Extension Version: 4.4.0.
["INFO" - 1:16:57 PM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 1:16:57 PM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
```

**Comment by ntotten** [comment]
I don't see anything wrong with the formatting. The syntax highlighting looks wrong, but that is a problem with VS Code not prettier.

![image](https://user-images.githubusercontent.com/282782/81500356-b86fa000-929f-11ea-87c3-68d45ca43349.png)
