### ISSUE TITLE
Typescript parser error with '?. ' (questionmark and dot)

### ISSUE THREAD

**Issue by vkrenta** [prettier/prettier-vscode#1364]
**Environments:**

- Prettier Version: 4.1.0  - 4.5.0
- React Typescript
- NodeJS v14.0.0
- OS: Windows 10
- Editor: vs-code

Expression
```react
<Button
        title={props.children?.toString()}
        buttonStyle={$.buttonStyle}
        titleStyle={$.titleStyle}
      
      />
```
gives next error 
```
SyntaxError: Expression expected.
title={props.children?.toString()}
                      ^
```
When i downgrade to version 4.0.0 - prettier works, 4.0.1 or later - crashes

**Comment by ntotten** [comment]
This is likely an issue with using the wrong version of typescript. Please provide a sample repro I can use to reproduce this.
