### ISSUE TITLE
Range formater and eslint formats the whole document

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier-vscode#137]
By using eslintIntegration and the range formater, the whole document gets formatted. 

Due to prettier-eslint not supporting this feature (yet?)

Alternative: Disable eslint with the range formater.

**Comment by RobinMalfait** [comment]
There are multiple problems with format selection:

1. Because it gets re-printed and you select nested code, it will move everything to the left
2. if forgot to select a { meaning you have "invalid" code selected because it can not be printed in 1 go, it will fail. (this happens quite a lot in my case).
3. Why do we need this feature actually? If you work with an html file with script tags in it. Aren't there ways to only format that script block because that's the only part that can be formatted? Just thinking out loud.

**Comment by CiGit** [comment]
Have you tried the range formater recently ? @josephfrazier improved it a lot :-)
1 and 2 are past issues to me.
3. Prettier aims to support HTML in the future if I remember correctly. Sorry I've no source right now.

**Comment by RobinMalfait** [comment]
Oh, I haven't used range formatting in a while now, ignore my comments :D

**Comment by CiGit** [comment]
I've some ideas:
- Remove eslint support 
- Use only prettier on range formatting
- As is, ie format document
- prettier-eslint supports range.

**Comment by divyanshu013** [comment]
Seeing this issue in latest vscode (1.19 release) on Fedora 27 linux x64. Reporting since this has been open since quite some time. I've to manually copy the seletion to a new js file, run prettier on it and then copy it back again at the moment :sweat_smile:

**Comment by ReeganExE** [comment]
I've to do work-around by: Format whole document (Shift + Alt + F) -> copy the formarted block code -> Ctrl + Z -> Paste 😆😆

**Comment by ccqgithub** [comment]
This feature(selection format) is very necessary.

**Comment by ccqgithub** [comment]
I think this feature(selection format) is very necessary. Because in the multi project collaboration development of old projects, conflicts can be reduced.

**Comment by sshmyg** [comment]
I've turned off `"prettier.eslintIntegration": false` but nevertheless format selection formats all document (

**Comment by CiGit** [comment]
Format selection formats the first common parent node which can act as a valid `Program`. This may be your entire file.

**Comment by mschlitz-trux** [comment]
> I've turned off `"prettier.eslintIntegration": false` but nevertheless format selection formats all document (

This was the only thing that worked for me. Unfortunate, but Format Selection is extremely useful for me.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration

**Comment by 0njzy0** [comment]
Still have this problem

**Comment by msbx2244** [comment]
same!
I want format selection on sass file.

**Comment by zhanzizhen** [comment]
Is there any solution for this problem?

**Comment by ntotten** [comment]
No, the issue is with `prettier-eslint` no supporting range formatting. The fix from our side would be to disable range formatting when eslint integration is enabled, but that's probably not something I am going to prioritize any time soon. Happy to accept a PR though.
