### ISSUE TITLE
Extension errors, saying latest version of Prettier is outdated

### ISSUE THREAD

**Issue by selfagency** [prettier/prettier-vscode#1372]
### Summary
Despite using the latest version of Prettier (2.0.5) as both a project dependency and in my global /usr/local/bin (via Yarn), I am getting the following error every time I save a file in VS Code:

```
Your project is configured to use an outdated version of prettier that cannot be used by this extension. Upgrade to the latest version of prettier.
```

### Github Repository to Reproduce Issue

https://gitlab.com/selfagencyllc/selfagency-nuxt-boilerplate

### Steps To Reproduce:

`yarn install` and then open VS Code, click on a file, and hit save.

### Expected result

Prettier extension should not error.

### Actual result

Prettier errors.

### Additional information

**VS Code Version**: 1.46.0-insider

**Prettier Extension Version**: 4.5.0

**OS and version**: MacOS 10.15.4

## Prettier Log Output

```
["INFO" - 8:41:36 PM] Formatting /Users/daniel/code/selfagency-nuxt/jsconfig.json
["INFO" - 8:41:36 PM] Using ignore file (if present) at /Users/daniel/code/selfagency-nuxt/.prettierignore
["INFO" - 8:41:36 PM] Loaded module 'prettier@unknown' from '/usr/local/bin/prettier'
["ERROR" - 8:41:36 PM] Outdated version of prettier installed. Falling back to bundled version of prettier.
```

**Comment by ntotten** [comment]
I think your `node_modules` folder is in a bad state. I cloned this repo and everything worked as expected. I do see a dependency in the `yarn.lock` for an old version of prettier as a child component, but when i run yarn install the latest version gets installed - which is what is expected based on the lock file. Can you delete your `node_modules` folder and try again?

**Comment by selfagency** [comment]
Cleared out my global node_modules and it works now, thanks
