### ISSUE TITLE
"prettier.arrowParens": "avoid" nor "always" not working

### ISSUE THREAD

**Issue by levitomer** [prettier/prettier-vscode#1374]
**Please Note: Though in this example, I am using JSX function component. This issue happens with other types of single-argument functions.**

I am trying to format React JSX arrow function component that receives a single argument props:
```
const ActualResult = (props) => {
    return <div>{props.secret}</div>
}
```
I have added `prettier.arrowParens: "avoid"` into my VSCode settings file, in order to remove parenthesis around single argument functions:

According to prettier docs on [arrowParens option](https://prettier.io/docs/en/options.html), valid options are:
`"always"` - Always include parens. Example: (x) => x
`"avoid"` - Omit parens when possible. Example: x => x

### Expected Result:
Parenthesis are removed from single argument functions

```
const ExpectedResult = props => {
    return <div>{props.secret}</div>
}
```

### Actual Result:
Nothing is changed and ESlint alerts on `Unexpected parentheses around single function argument.eslint(arrow-parens)`
```
const ActualResult = (props) => {
    return <div>{props.secret}</div>
}
```
**Extension, OS, and VSCode information**
VSCode Version: 1.45.0
OS: Windows_NT x64 10.0.18362
ESlint: 2.1.5
Prettier: 4.5.0

**Comment by ntotten** [comment]
Can you try disabling all extensions except prettier. I am not sure what would be causing this error as we list this correctly in the property config: https://github.com/prettier/prettier-vscode/blob/e7068e29413a01bec07a734952562422572d0ea1/package.json#L265-L274

**Comment by levitomer** [comment]
Mmm.. I don't have any formatting extensions except prettier :/

If it correctly listed, why its acting like the old version and asking for a boolean?
![image](https://user-images.githubusercontent.com/18260079/81574807-f1e30100-93ae-11ea-9573-ec30fdb370e0.png)

**Comment by ntotten** [comment]
I’m guessing you don’t have the document configured to format with prettier. Feel free to open a bug with more details for this new issue or post on stackoverflow as that may be better for support type questions.
