### ISSUE TITLE
Call Re-Indent on Format

### ISSUE THREAD

**Issue by shanekenyon87** [prettier/prettier-vscode#1376]
Currently, for Salesforce Apex files, when I perform a "Format Document" it does not reindent based on my tab settings.

I have manually run the command "Reindent Lines".

It would be great if there were an option to enable auto-reindent when I format the document.

**Comment by ntotten** [comment]
I’m not exactly sure what the issue is here. When you format a document all indentation is should be applied. When you say “tab settings” do you mean your VSCode settings or prettier config?

**Comment by shanekenyon87** [comment]
Hi there.  By tab settings I mean the indention config (tabs vs. spaces, and indentation size).  So yes, some indentation does occur.  However, when you have legacy code with random indentation, typically mixed spaces and tabs and different indent sizes (2, 4, 8 spaces etc.), the Prettier formatter doesn't reset ALL indentation to the desired state per the config.  But if you run the "Reindent Lines" command, everything is normalized.  So the idea here is to have an option to automatically run that command when Format Document is called, before the Prettier formatting is applied.

**Comment by ntotten** [comment]
Prettier doesn't use tab configuration from VS Code nor does it have anything to do with the "Reindent Lines" command - you shouldn't use that command with prettier as they will result in different formats. To configured prettier for VS Code the best option is to use a prettier config file. See here for details: https://github.com/prettier/prettier-vscode#configuration

**Comment by shanekenyon87** [comment]
Well in that case, perhaps there is a bug as the 'Format Code' command is failing to indent legacy code that has mixed indentation formats applied (i.e. some are tabs and some are spaces).  The expected behavior is that it converts all indentation to what is defined in the prettier config file, and reindents according to the style rule.

**Comment by ntotten** [comment]
If you can provide a repro I can investigate.
