### ISSUE TITLE
Formatted semicolon

### ISSUE THREAD

**Issue by HeZero** [prettier/prettier-vscode#1387]
After I configured the plugin, the formatting code automatically added a lot of semicolons to me, which made my experience very bad

**Comment by JHilker** [comment]
Semicolon's are default for Prettier. If you want it this extension to format without them you'll need to [explicitly configure Prettier](https://github.com/prettier/prettier-vscode#prettier-settings). For this you'll want to set `prettier.semi` to `false`

**Comment by HeZero** [comment]
Thanks, I solved this problem by setting the .prettierrc file in the root directory
