### ISSUE TITLE
Extension 'prettier - Code formatter' cannot format "hello.py"

### ISSUE THREAD

**Issue by krave1986** [prettier/prettier-vscode#1395]
### Summary
I used to write javascript only in vs code and everything works fine.
But now I start learning python.
When I hit ctrl-s will see this warning:
Extension 'prettier - Code formatter' cannot format "hello.py"

### Github Repository to Reproduce Issue
https://github.com/krave1986/learn_python.git

### Steps To Reproduce:

1.  clone the repo
1.  cd into the directory - hello
1.  open hello.py and hit ctrl + s

### Expected result

No warning about prettier presents.

### Actual result

Warning:
Extension 'prettier - Code formatter' cannot format "hello.py"

### Additional information

**VS Code Version**:
1.45.1

**Prettier Extension Version**:
4.7.0

**OS and version**:
Windows 10

## Prettier Log Output
no prettier button available in the bottom toolbar.

**Comment by krave1986** [comment]
Saving the file will trigger the warning even if I have set .prettierignore to ignore hello.py

**Comment by ntotten** [comment]
Prettier doesn’t support python.

**Comment by krave1986** [comment]
For others who have met the same warning, please try to set a language-per formatter for python.

If you are like me who wants to use prettier for javascript as well as black for python, and you already have prettier set as the default editor for all languages in vs code via
`"editor.defaultFormatter": "esbenp.prettier-vscode"`, you can formatter specific for python:
```
	"[python]": {
		"editor.defaultFormatter": "ms-python.python",
	}
```
ms-python.python refers to the extension - python build by Microsoft which offers formatter options for python language. The options covers:
autopep8,
black,
yapf,
none

Info from [here](https://github.com/microsoft/vscode-docs/issues/3728#issuecomment-635623182)
