### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by nithipramesti** [prettier/prettier-vscode#1400]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `4.7.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 610,
		"activateCallTime": 1312,
		"activateResolvedTime": 74,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "esbenp.prettier-vscode",
				"_lower": "esbenp.prettier-vscode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by ntotten** [comment]
Needs the rest of the error info.
