### ISSUE TITLE
Prettier automatically quotes vuetify property values (true, false, numbers)

### ISSUE THREAD

**Issue by Kenan7** [prettier/prettier-vscode#1404]
I want to pass contain as a true value;

![image](https://user-images.githubusercontent.com/11595462/83256862-4ca89500-a1c4-11ea-8ba7-64adde0bf7b5.png)

But when I save it automatically quotes the property value

![image](https://user-images.githubusercontent.com/11595462/83256841-3e5a7900-a1c4-11ea-9ec0-3a4e9db9b11c.png)

My default setting is "as-needed"

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
