### ISSUE TITLE
Support for additional file types

### ISSUE THREAD

**Issue by cj81499** [prettier/prettier-vscode#1405]
**Is your feature request related to a problem? Please describe.**
I would like to use prettier on .njk files with the html parser. It works when I run `npx prettier **/*.njk 
 --parser html`, but (as far as I can tell), there is no way to set this up in the .prettierrc file.

**Describe the solution you'd like**
I think the simplest solution would be to support arbitrary file types in the overrides section of the .prettierrc file. For example:
```json
{
  "overrides": [
    {
      "files": "*.njk",
      "options": { "parser": "html" }
    }
  ]
}
```

**Comment by ntotten** [comment]
This is supported today, but it can be somewhat complex depending on what is happening. I wrote a wiki article that should help explain this: https://github.com/prettier/prettier-vscode/wiki/Custom-File-Extension-Configuration

**Comment by cj81499** [comment]
This doesn't solve my problem. I'd like vscode to syntax highlight as a `.njk` file, but format as though it were an `.html` file, which (unless I'm misunderstanding your writing) still isn't possible.

**Comment by ntotten** [comment]
@cj81499 You have to send a pull request to prettier as explained here: https://github.com/prettier/prettier-vscode/wiki/Custom-File-Extension-Configuration#custom-language-identifier

**Comment by cj81499** [comment]
It seems a way to do this, either in prettier config or vscode prettier, without making a PR to prettier would be very useful... What a shame.

**Comment by ntotten** [comment]
Happy to accept a PR for a more convenient implementation.

**Comment by ntotten** [comment]
This feature is now supported in 5.3.0. You can register custom glob paths for the extension to provide formatting for. See: https://github.com/prettier/prettier-vscode#prettierdocumentselectors

**Comment by cj81499** [comment]
@ntotten this looks great! Many thanks to you and whomever implemented the feature!
