### ISSUE TITLE
Clearer instructions on installing local "Prettier" to avoid issues like recent ts errors (e.g. null chaining)

### ISSUE THREAD

**Issue by preom** [prettier/prettier-vscode#1408]
**Is your feature request related to a problem? Please describe.**
Prettier recently started failing for me on newer ts features. Problem was localized to that folder. Digging around eventually lead me to [this link](https://github.com/prettier/prettier-vscode/issues/1322#issuecomment-613150056) that provided a solution. Which was mostly luck at checking recent errors. 

**Describe the solution you'd like**
Clearer instructions in the readme or in the output message.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ntotten** [comment]
We have documentation on how prettier is resolved. I am not sure exactly what else we can add. Feel free to send a pull request.

https://github.com/prettier/prettier-vscode#prettier-resolution
