### ISSUE TITLE
Java source code formatting stopped working (prettier 5.0.0)

### ISSUE THREAD

**Issue by pprivately** [prettier/prettier-vscode#1410]
### Summary
prettier stopped working when set as default formatter in Settings / Text Editor / Formatting. I had to reset default formatter to none in order to bring back original Java source code formatting.
I did not check whether problem happens on Java files only or also on some other files.
Prettier generally throws an error: "Extension 'Prettier - Code formatter' can not format 'src\main\java\...\file.java'".
_Short summary of what is going on or to provide context_.

### Github Repository to Reproduce Issue
Missing

### Steps To Reproduce:
Install latest VSCode and latest extensions, enable prettier as default formatter

### Expected result
Java source code formatted on "Format Source" action.

### Actual result
No formatting happens - error "Extension 'Prettier - Code formatter' can not format 'src\main\java\...\file.java'".

### Additional information

**VS Code Version**: 1.51.1

**Prettier Extension Version**: 5.0.0

**OS and version**: Windows 10 Build 18363

Other VScode exentsions - note I am syncing settings (code-settings-sync v3.4.3 (latest)):
azds v2.0.220200601
azure-account v0.8.11
code-settings-sync v3.4.3
csharp v1.22.0
dot v0.0.1
EditorConfig v0.15.1
fontawesome-autocomplete v1.0.1
ginfuru-vscode-jekyll-syntax v0.1.1
gitdownloadazurerepos v1.0.9
githistory v0.6.5
gitlens v10.2.1
Go v0.14.3
graphviz-preview v1.4.0
java v0.62.0
java-properties v0.0.2
mssql v1.9.0
plantuml v2.13.11
prettier-vscode v5.0.0
remote-containers v0.117.1
remote-ssh v0.51.0
remote-ssh-edit v0.51.0
remote-wsl v0.44.2
ruby v0.27.0
shopify-liquid v2.3.0
spellright v3.0.50
vscode-aks-tools v0.0.4
vscode-boot-dev-pack v0.0.8
vscode-checkstyle v1.3.3
vscode-concourse v1.18.0
vscode-docker v1.2.1
vscode-java-debug v0.26.0
vscode-java-debugger-azds v0.2.3
vscode-java-dependency v0.10.2
vscode-java-pack v0.9.1
vscode-java-test v0.22.4
vscode-javadoc v0.0.1
vscode-jekyll-snippets v0.9.3
vscode-JS-CSS-HTML-formatter v0.2.3
vscode-kubernetes-tools v1.2.0
vscode-lombok v1.0.1
vscode-manifest-yaml v1.18.0
vscode-maven v0.21.4
vscode-prettydiff v0.6.5
vscode-ruby v0.27.0
vscode-spring-boot v1.18.0
vscode-spring-boot-dashboard v0.1.10
vscode-spring-initializr v0.4.8
vscode-xml v0.11.0
vscode-yaml v0.8.0
vscodeintellicode v1.2.7
xml v2.5.0

## Prettier Log Output
```
workbench.desktop.main.js:sourcemap:1642   ERR The request (id: 174, method: 'textDocument/hover') has been cancelled: Error: The request (id: 174, method: 'textDocument/hover') has been cancelled
	at c:\Users\Pawel.EBSOFT\.vscode\extensions\redhat.java-0.62.0\dist\extension.js:1:73520
	at c:\Users\Pawel.EBSOFT\.vscode\extensions\redhat.java-0.62.0\dist\extension.js:1:73814
	at Immediate.<anonymous> (c:\Users\Pawel.EBSOFT\.vscode\extensions\redhat.java-0.62.0\dist\extension.js:1:74175)
	at processImmediate (internal/timers.js:439:21) 
```

**Comment by ntotten** [comment]
This doesn't seem like an error with prettier. That log output is not from our extension. See here on how to provide the prettier log: https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#4-always-provide-the-log-output
