### ISSUE TITLE
Feature request: formatOnType

### ISSUE THREAD

**Issue by akrueger** [prettier/prettier-vscode#142]
Was just curious if `editor.formatOnType` could be respected for this?

Thanks

**Comment by CiGit** [comment]
See #12 
It would need to implement https://code.visualstudio.com/docs/extensionAPI/vscode-api#OnTypeFormattingEditProvider and `registerOnTypeFormattingEditProvider` I've not glanced at those. It would also need a good cursor tracking.

**Comment by akrueger** [comment]
Thanks for the info. I've never tried formatOnType, I think I was just curious if there was an implementation possibility based on demos I'd seen of `refmt` and `prettier`. It's not a major concern for me as much as a curiosity.

**Comment by eramitmittal** [comment]
Format on type is pretty cool and helpful as formatting kicks in once the line has 'ended'.
Format on save does not work too well with autosave

**Comment by nickmccurdy** [comment]
I'll often want to format some one-off code example to post online (kinda like Emacs' scratch buffer). It would be easier if I could use Prettier without having to save the file in VSCode. Instead I often end up using Prettier's online playground.

**Comment by andrecasal** [comment]
I'd like to bump up this feature because `"editor.formatOnType": true` is very useful in itself but also because, unfortunately, `"editor.formatOnSave": true` [does not trigger](https://www.youtube.com/watch?v=zJ8EjUqx1hg&list=PLVwLx67OHLu1HIbCihg3cohaM5eCarbiQ) with `"files.autoSave": "afterDelay"`.
