### ISSUE TITLE
Unable to save code with Single Quote.

### ISSUE THREAD

**Issue by sameergaikwad222** [prettier/prettier-vscode#1430]
### Summary

When i try to save code with Single Quote, It automatically saves same with Double Quotes after formatting.

### Github Repository to Reproduce Issue

Im using local coding project.

### Steps To Reproduce:

1.  type=>    import dogs from '@/data/dogs.js';
1.  This is step 2. try to save and see results.

### Expected result

code should be saved as  import dogs from '@/data/dogs.js';

### Actual result

code is getting saved as import dogs from "@/data/dogs.js";

### Additional information

_Feel free to attach a [screenshot_.](url
![prettier](https://user-images.githubusercontent.com/64338046/84583916-5e24aa80-ae1c-11ea-8edf-1e20b4e844ab.jpg)
)

**VS Code Version**:
Version: 1.46.0 (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**OS and version**:
Windows 10 Pro

**Prettier Extension Version**:
v5.0.0

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREESHOT, COPY AND PASTE THE TEXT
```

**Comment by sameergaikwad222** [comment]
I think this issue is from Latest update of VSCode 1.46.0

**Comment by ntotten** [comment]
This issue does not contain enough information to investigate. Please follow the instructions and reopen: https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue
