### ISSUE TITLE
Include .vsix to github releases

### ISSUE THREAD

**Issue by gyzerok** [prettier/prettier-vscode#1432]
Hello folks!

**Is your feature request related to a problem? Please describe.**
I am using [code-server](https://github.com/cdr/code-server) which can't use Marketplace due to the legal reasons. So they have their own "marketplace" where they are trying to publish extensions.

The simplest way for them to automatically update their own marketplace is by observing github releases of related extensions.

**Describe the solution you'd like**
It would be really helpful if you could include .vsix files into your github releases.

**Describe alternatives you've considered**
Currently it seems that they are building extension from source which is less reliable option. So sometimes extension version falls behind.

**Comment by ntotten** [comment]
Starting with 5.0.1 the vsix is included in the release.

**Comment by gyzerok** [comment]
Big thanks!
