### ISSUE TITLE
Single quotes converted to double.

### ISSUE THREAD

**Issue by stoplion** [prettier/prettier-vscode#1436]
Related to https://github.com/prettier/prettier-vscode/issues/206 issue from 2017.

1. Using `Prettier` extension in VSCode. (latest / latest)

2. Have the `Single Quote` set to single.

3. `format onSave` is set to true.

***Still...***
When I hit save, single quotes are converted to double.. 

-------

In addition...

1. I've set eslint to use single quotes
2. I've even deleted the eslint extension from VSCode.

```
// in .eslint file
"quotes": [2, "single", { "avoidEscape": true }],
```

***Still...***
When I hit save, single quotes are converted to double.. 
-------

**Output from VScode when I click save...**
```
["INFO" - 1:05:11 PM] Formatting /Users/george.norris/Code/Project/server/controllers/ExportsController.ts
["INFO" - 1:05:11 PM] Using ignore file (if present) at /Users/me/Code/Project/.prettierignore
["INFO" - 1:05:11 PM] Using bundled version of prettier.
["INFO" - 1:05:11 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 1:05:11 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 1:05:11 PM] Prettier Options:
{
  "filepath": "/Users/me/Code/Project/server/controllers/ExportsController.ts",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf"
}
```

This problem is driving me nuts..

**Comment by kmacute** [comment]
Same here :-1:

**Comment by ntotten** [comment]
I am guessing you are using the legacy ESLint integration which was removed in version 5.0.0. If you want to run ESLint and Prettier together the supported method is to use the ESLint extension - not this extension. See: https://github.com/prettier/prettier-vscode#linter-integration
