### ISSUE TITLE
Relative path for ignore file

### ISSUE THREAD

**Issue by fishgills** [prettier/prettier-vscode#1451]
I have a monorepo setup with projects defined in VSC workspace folder, for example:

```{
  "folders": [
    {
      "name": "Yoda",
      "path": "."
    },
    {
      "name": "Neo",
      "path": "./projects/neo"
    },
```

When editing a file inside a VSCode project, prettier plugin seems to be looking for the ignore file inside the project directory. I can't seem to get it to look at the root level of the project. 

In the plugin's log file I see:

```["INFO" - 1:30:52 PM] Formatting /Users/cdavis/Documents/BDC/neo2.0/projects/neo/src/app/pages/bill/new-bill2/new-bill2.template.html
["INFO" - 1:30:52 PM] Using ignore file (if present) at /Users/cdavis/Documents/BDC/neo2.0/projects/neo/.prettierignore
["INFO" - 1:30:52 PM] Loaded module 'prettier@2.0.5' from '/Users/cdavis/Documents/BDC/neo2.0/node_modules/prettier/index.js'
```

Notice it's looking inside `projects/neo/`, not at the root level of `neo2.0`.

I've tried using variables and that doesn't work:

```["INFO" - 1:31:47 PM] Formatting /Users/cdavis/Documents/BDC/neo2.0/projects/neo/src/app/pages/bill/new-bill2/new-bill2.template.html
["INFO" - 1:31:47 PM] Using ignore file (if present) at /Users/cdavis/Documents/BDC/neo2.0/projects/neo/${rootPath}/.prettierignore
["INFO" - 1:31:47 PM] Loaded module 'prettier@2.0.5' from '/Users/cdavis/Documents/BDC/neo2.0/node_modules/prettier/index.js'
```

Anyway to get it to use a path relative to the project root?

**Comment by fishgills** [comment]
I guess a simple solution could be to look up the directory tree for the prettier ignore file. Might be easy to implement.

**Comment by ntotten** [comment]
You can set the Ignore Path setting to `../.prettierignore` and it will look a level below the project. The default behavior of looking in the project is consistent with the Prettier CLI so we don't want to change it.

Add this to your workspace config:

```
  "settings": {
    "prettier.ignorePath": "../.prettierignore"
  }
```
Or through the config UI.

![image](https://user-images.githubusercontent.com/282782/86367938-97e21780-bc4a-11ea-8325-9416294539cf.png)
