### ISSUE TITLE
Option for disable line break for string format

### ISSUE THREAD

**Issue by pablocael** [prettier/prettier-vscode#1453]
for string using `` format such as:
 ${myVariable} ${otherVariable} .

prettier cannot break line since it will result in a line break in the formatted string.

Need option for disable that.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. However, do note that per the option philosophy they won't add this configuration. See: https://prettier.io/docs/en/option-philosophy.html
