### ISSUE TITLE
Non .editorconfig settings are ignored

### ISSUE THREAD

**Issue by IngressoDev** [prettier/prettier-vscode#1454]
### Summary
When using this plugin and a .editorconfig file exists and the checkbox "use .editorconfig" is enabled settings like "jsx single quote" will be ignored.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  Install this plugin
1.  Enable the "use .editorconfig" option
1.  Enable "jsx single quotes"
1.  Create an empty ".editorconfig" file
1.  Format a .jsx file where quotes are double quotes

### Expected result
Double quotes should be transformed to single quotes, because the vs code setting is activated and there is no rule in the .editorconfig.

### Actual result
Nothing happends

### Additional information
I saved my vs code settings in user scope so that e.g. the prettier settings are the same on every project.
But the plugin ignores all settings when there is a .editorconfig even when there is no rule for formating quotes

**VS Code Version**:
1.46.1

**Prettier Extension Version**:
5.1.3

**OS and version**:
Windows 10

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREESHOT, COPY AND PASTE THE TEXT
```

**Comment by ntotten** [comment]
This is by design. If you have either an editorconfig or prettier config those will be used. VSCode settings aren’t ONLY used when no other config is available.

**Comment by IngressoDev** [comment]
But there is no way to define my prettier configs in an .editorconfig, isn't it?
So i have to create a .prettierrc file?

**Comment by ntotten** [comment]
Correct, `.editorconfig` does not have all the features of a `.prettierrc`.

**Comment by ajparrah** [comment]
Thanks for your answer. I was freaking out

> Correct, `.editorconfig` does not have all the features of a `.prettierrc`.
