### ISSUE TITLE
text.trimEnd is not a function

### ISSUE THREAD

**Issue by ert4web** [prettier/prettier-vscode#1464]
### Summary

When I install the prettier through NPM in my project, prettier in VScode extension is not working, when I save the the file it is not formatting.when ever I hit the save button in prettier output it is showing
"text.trimEnd is not a function"
If I uninstall the prettier through NPM it is working as normal.

Also I can format the it using nom commands.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1. install prettier in VScode from extensions

2. in VScode Settings enable the format on save and check the Required 'prettierconfig' to format.

3. npm i -D prettier;

4. write the below code int he scripts section of the package.json file
"format": "prettier "src/**/*.{html,js,jsx}

5. create .prettierrc file in root folder

### Expected result

when I save the file it should format the code, as I enable the format on save

### Actual result

prettier is not foraging the code when I save the file

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:1.27.2 (1.27.2)

**Prettier Extension Version**:2.2.2

**OS and version**:macOS Catalina 10.15.5

## Prettier Log Output
text.trimEnd is not a function

Good-Issue -->

```
LOG GOES HERE. DO NOT USE A SCREESHOT, COPY AND PASTE THE TEXT
```

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
