### ISSUE TITLE
Per language settings

### ISSUE THREAD

**Issue by jahirfiquitiva** [prettier/prettier-vscode#1467]
Hi, I couldn't find it so I was wondering if there's a way to setup code styles per language... for example, in javascript I'd like 2 spaces, but in css I'd like 4. Also, I would like to disable css transforming `.8` into `0.8` for example.

How can I achieve that? If it's not possible, would you mind adding that as an option?

Thanks

**Comment by ntotten** [comment]
https://prettier.io/docs/en/configuration.html#configuration-overrides

**Comment by jahirfiquitiva** [comment]
@ntotten from what I see, that's for project settings, I want the settings to be used in all projects, so I think they must be part of vscode settings, yet I don't see any examples on how to achieve that

**Comment by ntotten** [comment]
The extension doesn't support that and won't support that. Extension config is meant to be only a backup, it is recommended that every project has a prettier config file.
