### ISSUE TITLE
Wrong indentation on paste

### ISSUE THREAD

**Issue by iliakan** [prettier/prettier-vscode#1473]
### Summary

On paste, the formatting is with wrong indentation. Here's the animated gif to show that.

![Jul-17-2020 13-53-58](https://user-images.githubusercontent.com/349336/87779322-4b473080-c835-11ea-8164-9e5ddb40d7a9.gif)

### Github Repository to Reproduce Issue

The code of the file is here:
https://gist.github.com/5e2c082a2d237645ff09dc32fce51c0f

### Steps To Reproduce:

1. Open the file.
2. Remove and paste `.querySelector('#previewWorkerManagerFrame')` in the line with `//`.

### Expected result

Good indents.

In this particular case, there should be no changes at all.

### Actual result

Wrong indents, see the image.

### Additional information

This issue shows up in other situations too. Spoils a lot of pleasure of using prettier.

**VS Code Version**: 1.47.1
**Prettier Extension Version**: 5.1.3
**OS and version**: MacOS Mojave 10.14.6

## Prettier Log Output

```
["INFO" - 1:59:20 PM] Formatting /js/javascript-nodejs/modules/taskui/client/lib/codeRunner.js
["INFO" - 1:59:20 PM] Using ignore file (if present) at /js/javascript-nodejs/.prettierignore
["INFO" - 1:59:20 PM] Using bundled version of prettier.
["INFO" - 1:59:20 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 1:59:20 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 1:59:20 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 160,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/js/javascript-nodejs/modules/taskui/client/lib/codeRunner.js",
  "parser": "babel",
  "rangeEnd": 190,
  "rangeStart": 146
}
["INFO" - 1:59:20 PM] Formatting completed in 17.504457ms.
```

**Comment by ntotten** [comment]
I'll look into this when I have time, but I will say that format on paste has always been challenging and it generally tends to not be super reliable. I don't use it for that reason.

**Comment by musm** [comment]
I have the same issue. Note I have disabled format on paste, yet the problem still persists.

**Comment by iliakan** [comment]
@musm For me the problem disappeared after I disabled format on paste. Try to disable prettier extension, does that fix it?

P.S. It looks like a fixable bug. At least most code editors format on paste without any issues. 
I really hope @ntotten will be able to figure out the reason.

**Comment by mdmower** [comment]
This issue looks to be equivalent to running _Format Selection_ on pasted contents when _Format On Paste_ is disabled. I'm guessing that's what's tricky about resolving this issue, deciding on the scope of surrounding lines to include in the format decisions.

**Comment by ntotten** [comment]
I was able to reproduce this in [prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhrBwEMraAJGVHAYUzgBKWKFDjkawADpQaNVgE8oYGuWEAKYI34AaGgHdmASxgAxCgLhVcMXTEOo4ELDBoBfAJQTps2ZChUXTTJKAEZdYJgAJjd6GlE9GgBZSypmAHM4HgALZhE4HDV3AG5vHwB6Mpp8AEcsMXkAZXy4MBgKNQByAGIScjgAN0M4PQB1CgBrMUTc9LETcmYHDvdS2RgswypCPFR8P3hYEcMoDAg9fDIA5LZZtVWfKRkfZ8hUVFyMbXvn1JOAIwgRC+T2esgMxjM5AsVhwNm+PjsDiccJBPlcwNBNA6ACoOhjQQBtCKRAC692K0lKrmkrhA2hAEBIdmgVGQoGY5HIZwAChyEKyUMwcAZ5Kz6X8FmBJjAGiRmGBjmlkDBVHB6VkuDgRht4FQ5WA4E1-MZDIMYPJkOA2HSQMcqGIYNyFml3sgAGZC+30gBWVCIACFJdKGos4AAZY5wd2etUgX1EBqKvAARSwEHg0ZwXpAcvI9vIlr+zD++RtvWOMCOGHWyAAHAAGem9CD2kYLEiW3qWMT9KP02rpuBOxkCkCsAC0ojgGGnNr6tUMfSd6VdSA9Wdj9tQhmVqvpVCTcFTg8z2ZgxarNaQkXpKqMOEVfDezEtlgArDasPaACrFgXr7N+jqABJE4EBlMByEMJkAEETgac08FPWMFigDIEI5GBkBCAAWAA2elUIyABRE5sIATnrVxXCAA). So this is actually an issue with range formatting on the prettier core library. Please open the issue there: https://github.com/prettier/prettier

**Comment by iliakan** [comment]
Looks like 2.1.0 will fix it! =) https://github.com/prettier/prettier/issues/8963#issuecomment-672819930
