### ISSUE TITLE
There is no formatter for 'hc' files installed

### ISSUE THREAD

**Issue by skebi69** [prettier/prettier-vscode#1475]
Issue Type: <b>Bug</b>

I have VS Code 1.47.1 with HashiCorp Terraform 2.1.1 and Prettier 5.1.3 extensions (among others) installed on a Fedora Core 32 64 bit VirtualBox instance with 4GB ram. Currently all system packages and extensions are up to date.
When I try and run prettier with the shortcut (<Ctrl> + <Shift> + i) I get the title error. When I click on the Install Formatter... button in the error the only extension it suggests is HashiCorp Terraform 2.1.1. I also have the settings set to format on save. When I save my tf file no formatting takes place.
This happens whether or not I have run 'terraform init' in against the directory or not (one piece of Googling suggested running it).
What is missing that is keeping Prettier from formatting my tf file?

Extension version: 5.1.3
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-14T00:13:57.513Z)
OS version: Linux x64 5.7.8-200.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (1 x 2399)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 0, 0|
|Memory (System)|3.84GB (0.45GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by ntotten** [comment]
https://github.com/prettier/prettier/issues/6499
