### ISSUE TITLE
data error after formatting,The array was formatted with extra brackets

### ISSUE THREAD

**Issue by sdark1326632** [prettier/prettier-vscode#1479]
### Summary

data error after formatting,The array was formatted with extra brackets

### Steps To Reproduce:

1.  before
<script>
    var obj = {
        
    }
    [1,2,3,4].forEach((v) => {
        
    })
</script>
2.after format
var obj = {}[(1, 2, 3, 4)].forEach((v) => {});

### Expected result
[1,2,3,4].forEach((v) => {})

### Actual result
[(1, 2, 3, 4)].forEach((v) => {});

_Describe what actually happened instead_.

### Additional information

![before](https://user-images.githubusercontent.com/30542243/88364431-77bef780-cdb5-11ea-819c-ed0e4f276ce6.png)

![after](https://user-images.githubusercontent.com/30542243/88364439-7db4d880-cdb5-11ea-83d1-86c84e08bef7.png)

**VS Code Version**:
版本: 1.47.2
提交: 17299e413d5590b14ab0340ea477cdd86ff13daf
日期: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

**Prettier Extension Version**:
v5.1.3

**OS and version**:

macOS high Sierra v10.13.6

## Prettier Log Output
{
  "ignored": false,
  "inferredParser": "html"
}
["INFO" - 1:58:02 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 1:58:02 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "none",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/Users/sdark/Desktop/未命名文件夹/index.html",
  "parser": "html"
}

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
