### ISSUE TITLE
Keep generating backslashes and vscode will crash

### ISSUE THREAD

**Issue by Clloz** [prettier/prettier-vscode#1481]
**VS Code Version**: 1.47.2

**Prettier Extension Version**: 5.1.3

**OS and version**: MacOS 10.15.3

### Summary
Format two consecutive backslashes `\\` will keep generating backslashes, and vscode will crash.

### Steps To Reproduce:
1. Enter two consecutive backslashes `\\` in a js file, then format this file by prettier.
2. prettier will keep generating `\`, and vscode will crash. I must force quit. when I reopen vscode,  there are lots of backslashes in the file.

### PS: 
The backslash in the regular expression does not cause the problem. `/\\/`

**Comment by ntotten** [comment]
I was able to reproduce this through the CLI so this is an issue for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
