### ISSUE TITLE
mixed tabs and spaces issue

### ISSUE THREAD

**Issue by DomPilipu** [prettier/prettier-vscode#1488]
### Summary

After prettier formatted TS Code I got a ES Lint Error that I have mixed tabs and spaces. (See Screenshot) I cannot stop ES Lint from flag this as error because it is a bigger project with lots of Developers. I Cannot remove the two leading spaces because prettier reformats it after save. Work around is useing spaces instead of tabs but I dont want to do this either. Dont know if bug or intended. What I know it is fucking annoying. just read your "no screenshot" rule, have no idea why but this issue is best explained by a screenshot

### Github Repository to Reproduce Issue

It is a private company repo

### Steps To Reproduce:

i Have no fucking idea how you can reproduce it if it is a private repo, take code from screenshot if needed

### Expected result

no leading spaces or give me option to stop prettier from auto wrapping

**Comment by DomPilipu** [comment]
![image](https://user-images.githubusercontent.com/893410/88772842-9dffe100-d181-11ea-861f-d1eaf43f9331.png)

**Comment by ntotten** [comment]
If you can't reproduce it, i'm not really sure how I am supposed to fix the bug. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
