### ISSUE TITLE
bracketSpacing option not doing what it's supposed to.

### ISSUE THREAD

**Issue by SamHep0803** [prettier/prettier-vscode#1492]
### Summary

_Short summary of what is going on or to provide context_.
When I try to enable the bracketsSpacing objects, it tells me that it's on but when I save, all the other formatting happens but the spacing between the brackets doesn't work. And when I manually add the spacing, it auto formats it to remove the spaces.

### Steps To Reproduce:

1.  Install the extension.
1.  Turn brackets spacing on, auto format on save on and make prettier vscodes default formatter.
1. `foo.bar('foo');` should be turned into `foo.bar( 'foo' );`

### Expected result

_Describe what should have happened_.
The formatter should've changed `foo.bar('foo');` to `foo.bar( 'foo' );`

### Actual result

_Describe what actually happened instead_.
`foo.bar('foo');`

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.47.3

**Prettier Extension Version**:
5.1.3

**OS and version**:
W10 1903 18362.959

## Prettier Log Output

On save to format:
```
["INFO" - 5:49:45 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": true,
  "vueIndentScriptAndStyle": false,
  "filepath": "\\\\wsl$\\Debian\\home\\samuel\\discord-dashboard-test\\backend\\src\\routes\\index.js",
  "parser": "babel"
}
```

**Comment by ntotten** [comment]
The example you are showing is not what `bracketSpacking` does. See: https://prettier.io/docs/en/options.html#bracket-spacing
