### ISSUE TITLE
Apex file is not formatting - when I click format document

### ISSUE THREAD

**Issue by nkggit** [prettier/prettier-vscode#1497]
["INFO" - 2:50:48 pm] Formatting d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\sfdx-source\hsp\main\default\classes\PlanServiceStd.cls
["INFO" - 2:50:48 pm] Using ignore file (if present) at d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\.prettierignore
["INFO" - 2:50:48 pm] Loaded module 'prettier@2.0.5' from 'd:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js'
["INFO" - 2:50:48 pm] File Info:
{
  "ignored": false,
  "inferredParser": "apex"
}
["INFO" - 2:50:48 pm] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 2:50:48 pm] Prettier Options:
{
  "filepath": "d:\\Nayana - V2\\Projects\\ABC\\ABC Workspace\\hsp\\sfdx-source\\hsp\\main\\default\\classes\\PlanServiceStd.cls",
  "parser": "apex",
  "trailingComma": "none"
}
["ERROR" - 2:50:49 pm] Error formatting document.
Error: spawnSync d:\Nayana - V2\Projects\ABC\rABC Workspace\hsp\node_modules\prettier-plugin-apex\vendor\apex-ast-serializer\bin\apex-ast-serializer.bat EOF
	at Object.spawnSync (internal/child_process.js:1041:20)
	at spawnSync (child_process.js:620:24)
	at parseTextWithSpawn (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier-plugin-apex\src\parser.js:25:27)
	at Object.parse (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier-plugin-apex\src\parser.js:489:21)
	at Object.parse (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:11370:19)
	at coreFormat (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:14784:25)
	at format (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:15019:75)
	at formatWithCursor (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:15035:12)
	at d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:51620:12
	at Object.format (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:51640:12)
	at t.default.<anonymous> (c:\Users\nayana\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:58387)
	at Generator.next (<anonymous>)
	at s (c:\Users\nayana\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:53305)

I am using prettier for the first time. I get this error whenever I click format document.

**Comment by ntotten** [comment]
Please open an issue with the apex plugin.

**Comment by HoloPoint** [comment]
> ["INFO" - 2:50:48 pm] Formatting d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\sfdx-source\hsp\main\default\classes\PlanServiceStd.cls
> ["INFO" - 2:50:48 pm] Using ignore file (if present) at d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp.prettierignore
> ["INFO" - 2:50:48 pm] Loaded module 'prettier@2.0.5' from 'd:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js'
> ["INFO" - 2:50:48 pm] File Info:
> {
> "ignored": false,
> "inferredParser": "apex"
> }
> ["INFO" - 2:50:48 pm] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
> ["INFO" - 2:50:48 pm] Prettier Options:
> {
> "filepath": "d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\sfdx-source\hsp\main\default\classes\PlanServiceStd.cls",
> "parser": "apex",
> "trailingComma": "none"
> }
> ["ERROR" - 2:50:49 pm] Error formatting document.
> Error: spawnSync d:\Nayana - V2\Projects\ABC\rABC Workspace\hsp\node_modules\prettier-plugin-apex\vendor\apex-ast-serializer\bin\apex-ast-serializer.bat EOF
> at Object.spawnSync (internal/child_process.js:1041:20)
> at spawnSync (child_process.js:620:24)
> at parseTextWithSpawn (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier-plugin-apex\src\parser.js:25:27)
> at Object.parse (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier-plugin-apex\src\parser.js:489:21)
> at Object.parse (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:11370:19)
> at coreFormat (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:14784:25)
> at format (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:15019:75)
> at formatWithCursor (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:15035:12)
> at d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:51620:12
> at Object.format (d:\Nayana - V2\Projects\ABC\ABC Workspace\hsp\node_modules\prettier\index.js:51640:12)
> at t.default. (c:\Users\nayana.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:58387)
> at Generator.next ()
> at s (c:\Users\nayana.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:53305)
> 
> I am using prettier for the first time. I get this error whenever I click format document.

I experienced this exact problem.  Thinking it was a one time issue, I restarted VS Code and then noticed it was looking at an invalid JAVA_HOME environment variable (old version).  It's likely that Prettier uses JAVA_HOME as it doesn't have this setting in VS Code Preferences.

After updating JAVA_HOME and restarting VS Code -- it started working.
