### ISSUE TITLE
Allow prettier to be disabled globally

### ISSUE THREAD

**Issue by danrneal** [prettier/prettier-vscode#1506]
What I would love is to be able to set the following in my user settings.json

```
"prettier.enable": false
```

And then vscodes usual formatters will work without all the [language] tags

Then in a workspace folder I could do

```
"prettier.enable": true,
"json.format.enable": false,
"html.format.enable": false,
"javascript.format.enable": false,
"typescript.format.enable": false
```

And now prettier doesn't conflict with any of vscodes formatters.  Again no [language] tags necessary.

I thought the "require config" option was exactly what I was looking for where prettier would be enabled or disabled automatically based on a config file.  But alas even with this option chosen vscode complains about multiple formatters and makes you set a [language] tag is settings.

**Comment by ntotten** [comment]
This is essentially already a feature of VS Code. You can disable an entire extension globally and then only enable it for certain workspaces as you need. 

![image](https://user-images.githubusercontent.com/282782/91214421-0ab6be80-e6e1-11ea-972b-92142cd0646c.png)

Also, if you set the default formatter to whatever you want to use as the default one you shouldn't get warnings of multiple formatters every time.

![image](https://user-images.githubusercontent.com/282782/91214703-76009080-e6e1-11ea-8cc6-21069452f334.png)

**Comment by danrneal** [comment]
@ntotten 

On your first point where you can disable an entire extension globally and then enable for certain workspaces, this is true.  But not having it in settings.json makes it a lot less portable to other workstations or colleagues.  Having a settings.json option would reduce friction greatly and also be in line with what vscode has done with their own formatters.

On your second point. You can set prettier as the default formatter in the workspace and be fine.  However, you cannot set vscode's default formatters as default globally since there is a different one for each of json, html, js, and ts and if you set the json one as default for example, and try to format an html doc, it will error.  This seems like an error on vscode's part rather than prettier.  However, if there were a way to disable prettier globally and then enable on a workspace by workspace basis, the problem is solved.  Currently the way to do this is as you described above, however, it suffers from portability and convenience.

I love having a boilerplate settings.json that I can just paste in the workspace and boom, my usual config is set up in a sharable way without affecting any other workspaces that might depend on other global settings.

I understand if this is still not something you want to pursue even given my above comments, just wanted to offer my perspective and use-case as food for thought.  I know maintaining an extra option can be a pain and thus there is a high bar for it.  However, it seems that an "enabled" option would be a less-complex option to maintain and it is in line with other formatters for vscode.

**Comment by ntotten** [comment]
Added in version 5.5.0
