### ISSUE TITLE
Register prettier-vscode to custom languages.

### ISSUE THREAD

**Issue by lukesneeringer** [prettier/prettier-vscode#1509]
I have the [Better Jinja](https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml) extension installed, which provides languages like `jinja-md`, `jinja-html`, etc. for using these underlying languages with the Jinja templating language. I want to format my Jinja template files (with filenames like `*.md.j2`) with prettier. I also want the syntax highlighting provided by Better Jinja, so I do not want to just set the language in VS Code to `markdown` (or `html` or whatever).

I tried to make this work by adding the following to `settings.json`:

```json
"[jinja-md]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
},
```

It does not work, because `esbenp.prettier-vscode` does not claim to be a provided for the `jinja-md` language.

Would it be possible to provide a configuration option to do this? This seems to be possible because [js-beautify does it](https://github.com/Microsoft/vscode/issues/65189#issuecomment-454869470).

**Comment by ntotten** [comment]
I just added this in version 5.3.0. You can register custom glob paths for the extension to provide formatting for. See: https://github.com/prettier/prettier-vscode#prettierdocumentselectors

**Comment by lukesneeringer** [comment]
Cheers, thanks so much.
