### ISSUE TITLE
Extension Prettier - Code formatter cannot format src/App.js

### ISSUE THREAD

**Issue by capndave** [prettier/prettier-vscode#1518]
## Background
I set up eslint and prettier to work with my create-react-app project. I have a `.vscode` directory at project root, with `extensions.json` and `settings.json` files. Prettier is correctly applying my eslint settings in the editor and I've set it up to format on save, which works correctly. 

## Problem
The one part that doesn't work is formatting files in real time, without saving, using ctrl + shift + I (which I mapped) or `Format Document`. When I try to do so I get a message at the bottom of vscode which says `Extension Prettier - Code formatter cannot format src/App.js`, `Extension Prettier - Code formatter cannot format src/index.js`, etc. 

Ctrl + Shift + I does format my `settings.json` file! Could this be because VSCode doesn't recognize the path to my `src` directory? Could it recognize `.json` files but not `.js` ones?

## Further Info
You can find my github repo at https://github.com/gardenbuilder-app/frontend/tree/linter-issues

**Comment by ntotten** [comment]
You have Prettier disabled for javascript: https://github.com/gardenbuilder-app/frontend/blob/linter-issues/.vscode/settings.json#L13-L15
