### ISSUE TITLE
Extremely slow Startup activation

### ISSUE THREAD

**Issue by gethari** [prettier/prettier-vscode#1525]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `5.3.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 853,
		"activateCallTime": 4037,
		"activateResolvedTime": 8,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "esbenp.prettier-vscode",
				"_lower": "esbenp.prettier-vscode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

![image](https://user-images.githubusercontent.com/20477956/91385026-977e8b00-e84d-11ea-9610-d448540ae8e6.png)

**Comment by ntotten** [comment]
Can you share the repo that you opened that caused this or a similar reproduction?
