### ISSUE TITLE
JS Formatter is breaking code

### ISSUE THREAD

**Issue by spyx08** [prettier/prettier-vscode#1526]
I was using prettier as default formatter + format on save every day during several month but since this morning the formatter is breaking the code. 

On JS object it add extra comma on last props. 

Original: 
``` 
const t = {
 foo:"bar",
 bar:"foo"
}
```

After format: 
``` 
const t = {
 foo:"bar",
 bar:"foo",
}
```
On single parameter arrow function it add parenthesis. 
Original: 
``` 
const t = value => value
```

After format: 
``` 
const t = (value) => value
```

There's maybe other problems, we have linter and code quality verification on our project, I had to disable prettier to make it work.

**Comment by ntotten** [comment]
That code isn't broken, its just in a different format - the default for prettier. You either need to [change your linter to work with prettier](https://github.com/prettier/prettier-vscode#linter-integration) or set the [options](https://prettier.io/docs/en/options.html#trailing-commas) to what you want.
