### ISSUE TITLE
Spacing hell

### ISSUE THREAD

**Issue by b5414** [prettier/prettier-vscode#1527]
**Is your feature request related to a problem? Please describe.**
Spaces. Spaces are everywhere - where I need and do not.

**Describe the solution you'd like**
A few new options, or post-process (replace all: `} else {` to `}else{`, _crutch alert_)

I very like the clean code, and every space is a symbol which useless for me and understanding the code. Also when you move the text-caret(I prefer that instead of pixel hunting by mouse, because it is more stable) you need to hit the button a few more times... multiply that by +-5 hours of development every day and it will sound like a waste of time

**Describe alternatives you've considered**
[Question](https://stackoverflow.com/questions/63278148/prettier-spacing)

**Additional context**
I need settings to disable spaces:
- on arrow functions to `const a=()=>{};` instead `const a = () => {};`
- on `} else {` to the clear one: `}else{`
- same with `if ()` and `for ()`

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

That being said, we wont add the option. See: See: https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue

**Comment by b5414** [comment]
@ntotten thank you for email and info, I changed the text of the ticket.. 

I don't think disabling the space is such a big problem(+opt-philosophy concept), because the settings already have a similar option (_prettier.bracketSpacing for example_)
Can I add\develop an extension for prettier-extension somehow? (Can't find the guide for module creators)

**Comment by ntotten** [comment]
This response is accurate: https://github.com/prettier/prettier/issues/9100#issuecomment-683272901
