### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by kannansgithub** [prettier/prettier-vscode#1535]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `5.5.0`
![Capture](https://user-images.githubusercontent.com/45405245/91860161-f5193a00-ec88-11ea-93e7-bbeed2c8c10d.PNG)

- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
![image](https://user-images.githubusercontent.com/45405245/91860110-dfa41000-ec88-11ea-8170-d38efa31e30c.png)

**Comment by ntotten** [comment]
Needs clipboard contents.
