### ISSUE TITLE
Graphql format like golang struct

### ISSUE THREAD

**Issue by sooxt98** [prettier/prettier-vscode#1543]
Is it possible to make format look like the top one?

![image](https://user-images.githubusercontent.com/13378059/92404266-afb3ab80-f165-11ea-86d8-eb9d7edc18c4.png)

**Comment by ntotten** [comment]
Please post questions to StackOverflow.

**Comment by sooxt98** [comment]
hi @ntotten , i have posted on stackoverflow, but is there ant clue to make it work?
https://stackoverflow.com/questions/63796340/is-it-possible-to-format-graphql-schema-like-golang-struct
