### ISSUE TITLE
Support bash language

### ISSUE THREAD

**Issue by frani** [prettier/prettier-vscode#1544]
**Describe the solution you'd like**
I was reading [ohmyzsh code style guide](https://github.com/ohmyzsh/ohmyzsh/wiki/Code-Style-Guide) and for a moment I lookup if Prettier support bash code to formatting, following a configuration.

**Additional context**
I believe this can be helpful in any kind of bash open source community

**Comment by ntotten** [comment]
https://prettier.io/docs/en/plugins.html
