### ISSUE TITLE
Consider switching to onStartupFinished

### ISSUE THREAD

**Issue by jasonwilliams** [prettier/prettier-vscode#1548]
This plugin currently activates on `*` which affects VSCodes startup performance https://github.com/prettier/prettier-vscode/blob/main/package.json#L59

Seeing as Prettier doesn’t need to be started straight away it would be good to use “onStartupFinished” instead https://code.visualstudio.com/api/references/activation-events#onStartupFinished this would help with performance and user experience.

It would mean bumping the minimum version from 1.41 to 1.46

**Comment by ntotten** [comment]
Good idea, I didn't notice they added that event. Changed in a3b961568aa19f0da69c64a3a1b56d9f19e7df8a

**Comment by jasonwilliams** [comment]
Thanks for the speedy response @ntotten !
