### ISSUE TITLE
Support VSCode 1.49 format modified lines feature

### ISSUE THREAD

**Issue by AlCalzone** [prettier/prettier-vscode#1562]
VS Code doesn't support this natively. We would only add this if VS Code's edit providers add this type of API.

_Originally posted by @ntotten in https://github.com/prettier/prettier-vscode/issues/630#issuecomment-545127877_

Since version 1.49, VSCode has the option to apply auto-formatting only to modified lines. Maybe its worth revisiting the referenced issue now.

**Comment by ntotten** [comment]
I'll look into it. Prettier formatting of partial documents though tends to be not very good.

**Comment by villecoder** [comment]
Fairly certain https://github.com/microsoft/vscode/issues/107151 is related to this.

**Comment by CoLdAs1cE** [comment]
Any update on this, would be awsome!

**Comment by jbmanning** [comment]
@CoLdAs1cE This plugin supports formatting modified lines. Instead of running the `Format Document` command, you will need to run the `Format Modified Lines` command.

**Comment by CoLdAs1cE** [comment]
Sorry, for uber late replay. 
found the command but i get 
![image](https://user-images.githubusercontent.com/1981573/111765853-25cb6480-88a5-11eb-9732-3e7a50d2227c.png)
when it try to run it

**Comment by CoLdAs1cE** [comment]
> 
> 
> @CoLdAs1cE This plugin supports formatting modified lines. Instead of running the `Format Document` command, you will need to run the `Format Modified Lines` command.

yeah that seems to work somewhat, but dont like jsx 😄, if u have a
`return (
    <div className=''>
        <div className=''></div>
    </div>
`
it will format both the or all the divs inside ( not the div with className you added or removed)

**Comment by ntotten** [comment]
Range formatting doesn't work very well in prettier. There are many issues open with the core library: https://github.com/prettier/prettier/issues?q=is%3Aissue+is%3Aopen+range+
