### ISSUE TITLE
Graphql indentation is different

### ISSUE THREAD

**Issue by sooxt98** [prettier/prettier-vscode#1564]
### Summary

The indentation works fine on 5.0.0 but not 5.6.0, both behaves defferently

### Steps To Reproduce:

1.  Cmd+Shift+P
1.  Format Document

### Expected result

``` graphql
input GuestFcmRegisterInput {
    merchant_key: String!
        @hashids(connection: "merchant")
        @rules(apply: ["exists:merchants,id"])
    fcm: String! @rules(apply: ["required", "min:100"])
}
```

### Actual result

``` graphql
input GuestFcmRegisterInput {
    merchant_key: String!
    @hashids(connection: "merchant")
    @rules(apply: ["exists:merchants,id"])
    fcm: String! @rules(apply: ["required", "min:100"])
}
```

### Additional information

**Prettier Extension Version**: 5.6.0

**Comment by ntotten** [comment]
I need the logs. Also have you tried reproducing this in prettier playground?
