### ISSUE TITLE
Question: warnings in the left panel?

### ISSUE THREAD

**Issue by markpalfreeman** [prettier/prettier-vscode#157]
Our team has a differs from Prettier's opinions in a couple small areas, so I set out to implement `prettier-eslint` using a VS Code extension (which this one seems to support).

Both the "Format document" and auto-formatting on save work perfectly in VS Code—everything formats properly with `prettier-eslint`, first using prettier, than picking up my additional eslint rules.

What I'm missing, though, is **warnings** on the left panel of the editor when my code differs from prettier (before I either save or manually format it). Is that possible with this extension? If not, do you have a suggestion of how to integrate this plugin with `prettier-eslint` in a way where all the proper prettier/eslint changes are warned correctly in the editor?

(I realize this question is 50/50 about the extension and `prettier-eslint` itself)

**Comment by CiGit** [comment]
If you have eslint rules, eslint extension should warn you about those errors. At least those covered by eslint and your plugins/configs

We could compare the current text with this extensions output.
- Performance?
- UX? 

I feel this is out of our scope and more a linter thing.

What do you call *left panel*?

**Comment by markpalfreeman** [comment]
Sorry, I meant the left panel in VS Code where it's standard to see warnings (like eslint, etc).

So it sounds like the VS Code extension does not (by design) show any prettier "lint" errors in the editor itself—it's purely for manually, or automatically on save, formatting the code through `prettier` or `prettier-eslint` 👍

That's all I was curious about... I'll have to continue exploring how to get these two things working together.

**Comment by CiGit** [comment]
If you haven't, you should check eslint extension. A linter :-)
I may suggest  https://github.com/prettier/eslint-plugin-prettier

**Comment by markpalfreeman** [comment]
Yes, that's the ESlint plugin I've been using. 

Once I added that, I got warnings for all the linting issues, but then when I ran the plugin formatter in VS Code, it defaulted back to formatting prettier rules *only* (my additional ESlint rules seem to be ignored/overridden).

I don't want to go outside the scope of this project, but I'm basically curious how to use this in tandem with `prettier-eslint`, and have all the same rules show lint warnings in VS Code before formatting.

**Comment by CiGit** [comment]
Have you enabled `prettier.eslintIntegration`?

**Comment by CiGit** [comment]
Can you share your eslint config?

**Comment by markpalfreeman** [comment]
Yes, I have the `eslintIntegration` enabled. Here's a GIF example of what's going wrong:
1) File in the state that I want based on eslint rules
2) Observe prettier error (via eslint config) - prettier rules seem to override eslint "space-before-function-paren" rule
2) Save file (`vscode-prettier` should run `prettier-eslint`)
3) Observe file is re-formatted with just plain prettier formatting, ignoring additional eslint rules
4) Observe new eslint "space-before-function-paren" error

**.eslintrc.json**
```
{
    "extends": "eslint:recommended",
    "parser": "babel-eslint",
    "root": true,

    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true,
        "mocha": true
    },

    "plugins": ["react", "prettier"],

    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "module"
    },

    "rules": {
        "prettier/prettier": [
            "error",
            {
                "singleQuote": true,
                "bracketSpacing": false,
                "printWidth": 100,
                "tabWidth": 4
            }
        ],
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1
            }
        ],
        "quotes": ["error", "single"],
        "semi": "error",
        "curly": "error",
        "strict": "error",
        "eqeqeq": "error",
        "one-var": ["error", "never"],
        "guard-for-in": "error",
        "no-floating-decimal": "error",
        "no-nested-ternary": "error",
        "no-multi-spaces": "error",
        "radix": "error",
        "keyword-spacing": "error",
        "space-before-blocks": "error",
        "space-before-function-paren": [
            "error",
            {
                "named": "never",
                "anonymous": "always",
                "asyncArrow": "always"
            }
        ],
        "spaced-comment": [
            "error",
            "always",
            {
                "exceptions": ["-"]
            }
        ],
        "wrap-iife": "error",
        "eol-last": "error",
        "handle-callback-err": "error",
        "comma-dangle": "error",
        "no-console": "off",
        "no-unsafe-negation": "error",
        "quote-props": [
            "error",
            "as-needed",
            {
                "keywords": true,
                "unnecessary": false
            }
        ],
        "valid-jsdoc": [
            "error",
            {
                "requireReturn": false
            }
        ],
        "semi-spacing": "error",
        "dot-notation": "error",
        "space-infix-ops": "error",
        "comma-spacing": "error",
        "new-cap": "error",
        "no-extra-bind": "error",
        "no-shadow": "error",
        "func-call-spacing": "error",
        "no-loop-func": "error",
        "key-spacing": "error",
        "no-trailing-spaces": "error",
        "camelcase": "error",

        "react/display-name": "error",
        "react/jsx-boolean-value": "error",
        "react/jsx-equals-spacing": ["error", "never"],
        "react/jsx-no-undef": "error",
        "react/jsx-uses-react": "error",
        "react/jsx-uses-vars": "error",
        "react/no-did-mount-set-state": "error",
        "react/no-did-update-set-state": "error",
        "react/no-multi-comp": "error",
        "react/no-unknown-property": "error",
        "react/prop-types": "error",
        "react/react-in-jsx-scope": "error",
        "react/self-closing-comp": "error",
        "react/sort-prop-types": "error",
        "react/wrap-multilines": "error"
    }
}
```

**Comment by markpalfreeman** [comment]
I'm realizing this might be more of an issue between the interplay of `eslint-plugin-prettier` and `prettier-eslint`, but I thought I'd start here since I'm saving via VS Code.

**Comment by CiGit** [comment]
To me this seems to be conflicting rules. I could reproduce it with
```json
{
  "env": {
    "es6": true
  },
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "bracketSpacing": false,
        "printWidth": 100,
        "tabWidth": 4
      }
    ],
    "space-before-function-paren": [
      "error",
      {
        "named": "never",
        "anonymous": "always",
        "asyncArrow": "always"
      }
    ]
  }
}
```

```js
call(function() {});
```
Sorting rules differently doesn't change the outcome

**Comment by CiGit** [comment]
Note: with the formater, prettier wins :-)

**Comment by markpalfreeman** [comment]
Obviously if I remove eslint-plugin-prettier and only use the extension, the formatting works correctly (since it runs `prettier` then `eslint --fix`). But then I don't get the linting help along the way.
I'm not sure how to use the two at the same time :/

**Comment by CiGit** [comment]
I've tried to debug this quickly,
I see two troubles with this case:
`call( function     ())` -> prettier -> `call(function() {})` -> eslint -> error: missing space -> eslint --fix -> `call(function() {})` (no fix)

And the fact that what ever you fix, it will conflict with the other rule.

**Comment by azz** [comment]
`eslint-plugin-prettier` and `prettier-eslint` contradict by definition. 

* `eslint-plugin-prettier` will create an error for every code fragment that doesn't match prettier's output. 
* `prettier-eslint` will run `eslint --fix` after `prettier --write`, thus writing non-prettier code to disk.

You should remove `eslint-plugin-prettier`. As far as I know there is no `eslint-plugin-prettier-eslint`, which is what you're really after.

**Comment by markpalfreeman** [comment]
^ haha precisely. I almost mentioned that `eslint-plugin-prettier-eslint` is the equivalent.
For now, I've added all the rules to my `.eslintrc` that I want to "lint/warn" in VS Code, even the ones that come by default within prettier's opinions already (not ideal). This way I get the linting hints, but my ESlint config is far more bloated than it really needs to be.

**Comment by azz** [comment]
I decided to give this a crack: https://github.com/prettier/eslint-plugin-prettier/pull/38

**Comment by CiGit** [comment]
Seems answered.
