### ISSUE TITLE
support overrides in global default configuration file

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier-vscode#1572]
**Is your feature request related to a problem? Please describe.**
I use prettier to format 'svg'.
FIrst, I add following to vscode settings:
```json
{
"prettier.documentSelectors": ["**/*.svg"],
"[svg]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
 }
}
```
Then I set global default configuration in `~/.prettierrc`:

```json
{
    "trailingComma": "all",
    "tabWidth": 4,
    "semi": true,
    "singleQuote": true,
    "endOfLine": "auto",
    "printWidth": 100,
    "overrides": [
        {
            "files": "*.svg",
            "options": {
                "parser": "html"
            }
        }
    ]
}
```

But vscode-prettier doesn't respect to it `overrides` option. If I add configuration above to project root, all works well, but I don't want to add a config file to event a temp svg file. It would better to support global `overrides` config.

**Describe the solution you'd like**

VSCode-prettier should respect to global default `overrides` option.

**Describe alternatives you've considered**

None.

**Additional context**

![screenshot_2020-09-24_01-17-00](https://user-images.githubusercontent.com/41773861/94047457-b51b2200-fe04-11ea-8c73-93833434dfab.png)

**Comment by ntotten** [comment]
The extension and prettier search the entire file tree down to find config. It should find your global config at ~/.prettierrc and use those options. I am not super thrilled with the idea of adding more config options to VS Code as this could get really complicated. My take on the VS Code config is that it is only for the most simple cases. 

I just released version 5.7.1 which adds a log line stating which config file is being used. Can you upgrade to that and see what it says. There might be a bug that is causing it to not get the right config. Ultimately, i would rather fix that and support global prettier config rather than add new options to vscode.

**Comment by tjx666** [comment]
I found my config above works on MacOS, but not on Windows. Following is my log from prettier:
```
["INFO" - 下午9:43:29] Extension Name: esbenp.prettier-vscode.
["INFO" - 下午9:43:29] Extension Version: 5.7.1.
["INFO" - 下午9:43:29] Enabling prettier for languages: ansible, css, graphql, home-assistant, html, javascript, javascriptreact, json, json5, jsonc, less, markdown, mdx, mongo, postcss, scss, typescript, typescriptreact, vue, yaml
["INFO" - 下午9:43:29] Enabling prettier for file extensions: .JSON-tmLanguage, ._js, .avsc, .bones, .cjs, .component.html, .css, .es, .es6, .frag, .geojson, .gltf, .gql, .graphql, .graphqls, .gs, .har, .htm, .html, .html.hl, .ice, .inc, .jake, .js, .js.flow, .jsb, .jscad, .jsfl, .jsm, .json, .json5, .jsonc, .jsonl, .jss, .jsx, .less, .markdown, .mcmeta, .md, .mdown, .mdwn, .mdx, .mir, .mjml, .mjs, .mkd, .mkdn, .mkdown, .njs, .pac, .pcss, .postcss, .reek, .ronn, .rviz, .scss, .sjs, .ssjs, .st, .sublime-build, .sublime-commands, .sublime-completions, .sublime-keymap, .sublime-macro, .sublime-menu, .sublime-mousemap, .sublime-project, .sublime-settings, .sublime-syntax, .sublime-theme, .sublime-workspace, .sublime_metrics, .sublime_session, .syntax, .tfstate, .tfstate.backup, .topojson, .ts, .tsx, .vue, .webapp, .webmanifest, .workbook, .xht, .xhtml, .xsjs, .xsjslib, .yaml, .yaml-tmlanguage, .yaml.sed, .yml, .yml.mysql, .yy, .yyp
["INFO" - 下午9:43:29] Enabling prettier for user defined selectors: **/*.svg
["INFO" - 下午9:43:29] Enabling prettier for range supported languages: graphql, javascript, javascriptreact, json, typescript, typescriptreact
["INFO" - 下午9:43:39] Formatting c:\code\drawing-demos\MDN-SVG\BasicShapes.svg\rect.svg
["INFO" - 下午9:43:39] Using ignore file (if present) at c:\code\drawing-demos\.prettierignore
["INFO" - 下午9:43:39] Using bundled version of prettier.
["INFO" - 下午9:43:39] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 下午9:43:39] Parser not inferred, trying VS Code language.
["ERROR" - 下午9:43:39] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

**Comment by thorn0** [comment]
Prettier doesn't support global configuration. It's supposed to be configured per project. See https://prettier.io/docs/en/configuration.html
