### ISSUE TITLE
Can't set a relative path to prettier config file in package.json

### ISSUE THREAD

**Issue by Esporia** [prettier/prettier-vscode#1578]
I have the same problem than this issue : https://github.com/prettier/prettier-vscode/issues/925

However the solution provided, (installing https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode (preview version of prettier-vscode)) doens't work for me, and I can't specify a relative path to my prettier config file in package.json 
``json
	"prettier": "config/.prettierrc.json",
``
 Output : ``Error: Cannot find module 'config/.prettierrc.json' from 'path/to/projec'``

How can I fiw that ?

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
