### ISSUE TITLE
Format XML

### ISSUE THREAD

**Issue by infacto** [prettier/prettier-vscode#1579]
Please add XML format feature. Reference: #505
Prettier has an official plugin for that: https://github.com/prettier/plugin-xml

I wonder, Prettier formats xml but not natively xml? Weird, but ok. It's slightly different.
Anyway, it would be great if the prettier-vscode extension supports formatting xml. 
The "XML Tools" extension also formats XML. But really ugly. I like the behavior of Prettier for HTML. e.g. split attributes in line on line overflow, etc.

Alternative: How to tell Prettier / VS Code to handle XML like HTML to format the XML as HTML. I think this will work in the very most of cases. For example: I want to format SVG. But also default XML.

Update: A workaround could be: In VS Code settings.json:

```json
"files.associations": {
  "*.svg": "html",
  "*.xml": "html"
},
```

It works more or less. That has to be tested for longer time. This is just a workaround. I hope for an official solution. Maybe just use the html-formatter for xml and co (svg) for the first step.

**Comment by ntotten** [comment]
Use the plugin. https://github.com/prettier/prettier-vscode#plugins
