### ISSUE TITLE
Format on save modifications improper indentation

### ISSUE THREAD

**Issue by mhuggins7278** [prettier/prettier-vscode#1585]
Issue Type: <b>Bug</b>

When saving a JS file with the format modification option set the file ends up with improper indentation and the editor then shows prettier warnings if I save the same with the format on save set to the whole file it works fine

Extension version: 5.7.1
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|-psn_0_1970657 --crash-reporter-id 2783618e-5e39-49a8-9ff2-276cd973aee5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ntotten** [comment]
This doesn't have any info needed to repro.

**Comment by dawnerd** [comment]
I'm having a similar issue. Only happens when format on save is set to modifications instead of full file.

It's hard to repro 100% but using the modified setting should make it happen after a while.

Before save:
![image](https://user-images.githubusercontent.com/24781/95031302-18f5e400-066a-11eb-85af-1a85de2b1fc2.png)

After Save:
![image](https://user-images.githubusercontent.com/24781/95031315-2c08b400-066a-11eb-8b63-d81af8d48016.png)

```
["INFO" - 12:50:41 AM] Formatting /home/troy/Projects/opencoaster-web/pages/_app.jsx
["INFO" - 12:50:41 AM] Using ignore file (if present) at /home/troy/Projects/opencoaster-web/.prettierignore
["INFO" - 12:50:41 AM] Loaded module 'prettier@2.0.5' from '/home/troy/Projects/opencoaster-web/node_modules/prettier/index.js'
["INFO" - 12:50:41 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 12:50:41 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 12:50:41 AM] Using config file at '/home/troy/Projects/opencoaster-web/.prettierrc.json'
["INFO" - 12:50:41 AM] Prettier Options:
{
  "filepath": "/home/troy/Projects/opencoaster-web/pages/_app.jsx",
  "parser": "babel",
  "rangeEnd": 1099,
  "rangeStart": 1068
}
["INFO" - 12:50:41 AM] Formatting completed in 25.843831ms.
```
