### ISSUE TITLE
printWidth can not prevent wrapping lines  in js.

### ISSUE THREAD

**Issue by wgf4242** [prettier/prettier-vscode#1587]
I've set   ` "prettier.printWidth": 180,` , not worked for js file, but worked for keybindings.json
### Additional information

![录制_2020_10_03_14_30_37_560](https://user-images.githubusercontent.com/3336626/94985060-9136a980-0585-11eb-9f78-502eb21a803a.gif)

**VS Code Version**:
1.49.3
**Prettier Extension Version**:
v5.7.1
**OS and version**:

## Prettier Log Output
```
["INFO" - 下午2:32:46] Formatting d:\vue-html\1.js
["INFO" - 下午2:32:46] Using ignore file (if present) at d:\vue-html\.prettierignore
["INFO" - 下午2:32:46] Using bundled version of prettier.
["INFO" - 下午2:32:46] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 下午2:32:46] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 下午2:32:46] Using config file at 'd:\vue-html\.prettierrc'
["INFO" - 下午2:32:46] Prettier Options:
{
  "filepath": "d:\\\vue-html\\1.js",
  "parser": "babel",
  "prettier.printWidth": 180,
  "proseWrap": "never"
}
["INFO" - 下午2:32:46] Formatting completed in 10.158ms.
```

**Comment by ntotten** [comment]
That's not how printWidth works. What you are seeing is the expected result. Test it out with prettier playground: https://prettier.io/playground/
