### ISSUE TITLE
Official Solidity Style Guide Divergence

### ISSUE THREAD

**Issue by gitpusha** [prettier/prettier-vscode#1595]
Hi everyone, 

Nice work! Thank you first of all. 

One thing that bugged me the last time I used this plugin some while ago was that the auto-formatted style diverges quite far from the official Solidity [Style Guide.](https://solidity.readthedocs.io/en/latest/style-guide.html) 

Notably in the [function declaration modifier](https://solidity.readthedocs.io/en/latest/style-guide.html#function-declaration) parts for example:

![image](https://user-images.githubusercontent.com/36712489/95470090-a85c0980-0980-11eb-8b41-ef61e4fb69fe.png)

Where this plugin formats the modifiers onto the same line, right?

Are there any plans for this plugin to follow the official Style Guide more closely, or was this done deliberately?

**Comment by ntotten** [comment]
No, this uses prettier only.

**Comment by gitpusha** [comment]
yep sorry, wrong repo
