### ISSUE TITLE
prettier extension too slow and also makes vs code slower

### ISSUE THREAD

**Issue by AhmetEnesKCC** [prettier/prettier-vscode#1599]
- Issue Type: `Speed`
- Extension Name: `prettier-vscode`
- Extension Version: `5.7.1`
- OS Version: `Linux x64 5.4.0-48-generic`
- VSCode version: `1.50.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ntotten** [comment]
Missing info needed to diagnose.
