### ISSUE TITLE
process.cwd() result is always equals '/'

### ISSUE THREAD

**Issue by glook** [prettier/prettier-vscode#1604]
### Summary

In our project we using prettier with [import-sort plugin](https://github.com/ggascoigne/prettier-plugin-import-sort) and [module-and-prefix](https://github.com/ronyclau/import-sort-style-module-and-prefix) style which uses a [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) package to find configuration object from `package.json` or `.importSortPrefixrc` file.

Im find out that vscode prettier plugin can't run this prettier plugin correctly because process.cwd() result is always equal `/`with no difference prettier installed locally or globally.

----
By default [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) using `process.cwd()` as default parameter to searchForm property in searchSync function. But because cwd is always equal / cosmiconfig can't find configuration.

[ExplorerSync.ts](https://github.com/davidtheclark/cosmiconfig/blob/07e7637b74cb01b23f351bc1586390d20eed881f/src/ExplorerSync.ts#L17)
```
public searchSync(searchFrom: string = process.cwd()): CosmiconfigResult {
    const startDirectory = getDirectorySync(searchFrom);
    const result = this.searchFromDirectorySync(startDirectory);

    return result;
  }
```

### Github Repository to Reproduce Issue

You can repoduce this issue in this [repository](https://github.com/glook/webpack-typescript-react)

### Steps To Reproduce:

1.  install dependencies
2.  try to reformat some of `*.ts,*.tsx,*.js,*.js` file which contains imports
### Expected result
all imports now sorted in grouped using rules from [.importSortPrefixrc](https://github.com/glook/webpack-typescript-react/blob/master/.importSortPrefixrc) file:

```typescript
import 'core-js/stable';
import 'regenerator-runtime/runtime';

import '@styles/styles.less';
import '@styles/styles.scss';

import React from 'react';
import ReactDom from 'react-dom';

import {App} from '@components/app/app';

ReactDom.render(<App />, document.getElementById('root'));
```

### Actual result

absolute modules is imported after relative modules, that's not correct

```typescript
import React from 'react';
import ReactDom from 'react-dom';
import '@styles/styles.less';
import '@styles/styles.scss';

import 'core-js/stable';
import 'regenerator-runtime/runtime';


import {App} from '@components/app/app';

ReactDom.render(<App />, document.getElementById('root'));
```

### Additional information

I created a [pull request](https://github.com/prettier/prettier-vscode/pull/1605) that can fix this issue

**VS Code Version**:
1.50.0

**Prettier Extension Version**:
2.1.2

**OS and version**:
Mac os x 10.15.7, have same issue on windows 10 too

## Prettier Log Output

```
["INFO" - 12:47:08 AM] Formatting /Users/andrey/Sites/github/webpack4-es6-sass/src/index.tsx
["INFO" - 12:47:08 AM] Using ignore file (if present) at /Users/andrey/Sites/github/webpack4-es6-sass/.prettierignore
["INFO" - 12:47:08 AM] Loaded module 'prettier@2.1.2' from '/Users/andrey/Sites/github/webpack4-es6-sass/node_modules/prettier/index.js'
["INFO" - 12:47:08 AM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}`
["INFO" - 12:47:08 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 12:47:08 AM] Using config file at '/Users/andrey/Sites/github/webpack4-es6-sass/.prettierrc'
["INFO" - 12:47:08 AM] Prettier Options:
{
  "filepath": "/Users/andrey/Sites/github/webpack4-es6-sass/src/index.tsx",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 4,
  "singleQuote": true,
  "trailingComma": "all",
  "semi": true,
  "arrowParens": "always",
  "bracketSpacing": false,
  "endOfLine": "lf",
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false
}
["INFO" - 12:47:08 AM] Formatting completed in 33.165648ms.
```

**Comment by ntotten** [comment]
I'm not entirely sure this is the a bug related to this extension. That prettier plugin feels like a bit of an abuse of the prettier plugin API. Let me ask what the core prettier team thinks about this and ill let you know.

**Comment by ntotten** [comment]
Just chatted with the team. This type of plugin that modifies the behavior of the output isn't supported with prettier. Plugins are meant to add new langjuages. This extension is really a pretty big hack that is super easy to break. As such, we won't support it in VS Code either.

**Comment by ntotten** [comment]
Also relevant: https://github.com/simonhaenisch/prettier-plugin-organize-imports
