### ISSUE TITLE
Prettier not working with the latest VS Code update

### ISSUE THREAD

**Issue by rajkamal3** [prettier/prettier-vscode#1607]
Issue Type: <b>Bug</b>

Prettier is not formatting any file except .prettierrc

Extension version: 5.7.1
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.55GB (1.30GB free)|
|Process Argv|--crash-reporter-id 7f868c4b-cd1e-42ce-929a-d67b9eba191f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pickypg** [comment]
FYI, this is the same as https://github.com/prettier/prettier-vscode/issues/1598, which has a workaround listed at https://github.com/prettier/prettier-vscode/issues/1598#issuecomment-706420105.

**Comment by ntotten** [comment]
Dup of #1598
