### ISSUE TITLE
Unexpected characters (). in Prettier output pane, anb the output pane opens and gets focus when VS Code starts

### ISSUE THREAD

**Issue by thernstig** [prettier/prettier-vscode#1627]
### Summary

When I open VS Code with the Prettier extension installed, using remote SSH, I oftentimes get this output in the Output view:
`Unexpected characters ().`

### Github Repository to Reproduce Issue

It is a private project, I cannot share this and have not been able to repro it with a minium repro.

### Steps To Reproduce:

1.  All I do is to open a repo on a remote SSH host

### Expected result

I should not get any output with the text `Unexpected characters ().`

### Actual result

I do get the output `Unexpected characters ().` **and** the output view pane is opened and focused every time I restart VS Code due to this error.

### Additional information

This only happens due to Prettier output, not due to other extensions.

![output](https://user-images.githubusercontent.com/30827238/97551699-985da580-19d3-11eb-8f91-f662db2345c4.png)

**VS Code Version**: 1.50.1

**Prettier Extension Version**: 5.7.1

**OS and version**: Windows 1909 locally, Ubuntu 18.04 remotely

## Prettier Log Output

```
Unexpected characters ().
```

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
