### ISSUE TITLE
semicolon added as first character on save to html files

### ISSUE THREAD

**Issue by brewster1134** [prettier/prettier-vscode#1629]
each time i save an html file, prettier adds a semicolon to the left of my html tag `;<html>`. i remove it, save the file, and it is added back

i went through disabling extensions until i found out prettier was causing it, but am unable to change/find any settings that fix the issue. its possible this has been an issue for awhile, but i am just noticing it. is this a known issue, and if so, is there a known fix for it?

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
