### ISSUE TITLE
prettier doen't work with create-react-app 

### ISSUE THREAD

**Issue by kentBui** [prettier/prettier-vscode#1630]
### Summary

prettier doen't work with create-react-app 

Dear all !
i have some problem with prettier:
1. when i use npx create-react-app. i dont see prettier in status bar. and dont format with it.
vs code show notification: There is no formatter for 'javascript' files installed.
npx version : 6.13.4
prettier version: v5.7.1
2. I can use prettier in normal js app.
 can you help me?

**Comment by donbfry** [comment]
I had this same issue. Something from the initial create-react-app setup is overriding the formatting settings. I was able to resolve this by creating a `.vscode` folder in my projects main directory and saving
```
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true
}
```
into a file called `settings.json`.

There's probaby a better and/or easier way around this but this is just what I did to get it to work.

**Comment by kentBui** [comment]
thanks for your help
