### ISSUE TITLE
How to use .prettierignore to ignore all except one path?

### ISSUE THREAD

**Issue by ronaldgj** [prettier/prettier-vscode#1631]
I want to ignore all files in my folder, except the a React app folder nested in my project. How can i do this?

```
/*
!/web/folder/to/custom/react-app
```

This doesn't seem to work. I use Prettier in my VS Code editor and in the log I can see the files within de `react-app` folder are ignored.

Can somebody help me understand how to make this working?

**Comment by ntotten** [comment]
Please use stackoverflow for support and questions.
