### ISSUE TITLE
prettier does not work i have enabled format on save and made it my default formater but when i actually save it does nothing and the code is the same with no format done to it in html code 

### ISSUE THREAD

**Issue by Aly60** [prettier/prettier-vscode#1642]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `5.7.2`
- OS Version: `Windows_NT x64 10.0.15063`
- VSCode version: `1.51.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
