### ISSUE TITLE
Not formatting on command in .vue files

### ISSUE THREAD

**Issue by csicky** [prettier/prettier-vscode#1643]
After updating today VS Code to 1.5.1.1, and Prettier to 5.7.2 and Vetur to 0.30.0, one of them has some problem as it is not formatting anymore **on command in .vue** files. It does format on save. In .js files it formats also on command.

I can't tell which one of the above updates caused this, as I have updated at the same time today.

Might be a duplicate of #1598 but this is a bit different.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by csicky** [comment]
still not working
