### ISSUE TITLE
format document with when a language is disabled

### ISSUE THREAD

**Issue by basaran** [prettier/prettier-vscode#1644]
**Is your feature request related to a problem? Please describe.**
Prettier uses the following syntax to disable itself on a per language basis.

```javascript
   "prettier.disableLanguages": [
        "json",
        "jsonc",
        // "vue",
        "javascript",
        "typescript"
    ],
```
and VS Code has a `format document with` command, that allows you to pick a formatter manually to format a document. At the moment, even when the language is disabled through the settings, it shows in the VS code command list (which is good):

![image](https://user-images.githubusercontent.com/30809170/99157431-b2b3a680-2696-11eb-8073-c645809b63eb.png)

However, upon selecting `prettier` while the `language` (i.e javascript) is disabled, prettier does not execute on the file.

**Describe the solution you'd like**
It should execute even if the language is disabled when doing `format document with` and selecting `prettier`

**Comment by ntotten** [comment]
I don't see why it would execute when the language is disabled. This seems like it would be extremely confusing.

**Comment by basaran** [comment]
Well, sometimes you just want to quickly format a pasted snippet or selection, and meanwhile keep using an instance of eslint/prettier combination for the on-save events. If you are invoking prettier with the format-with it should format.

main confusion here, is the prettier showing up in the menu and not formatting.
