### ISSUE TITLE
Prettier not installing

### ISSUE THREAD

**Issue by rjptechsolutions** [prettier/prettier-vscode#1664]
Failed to install 'esbenp.prettier-vscode'.
download manually
and
Corrupt ZIP: end of central directory record signature not found
It shows when  I clicked on to install button this notification comes.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
