### ISSUE TITLE
Force format of document that is ignored by config

### ISSUE THREAD

**Issue by edwardgalligan** [prettier/prettier-vscode#1672]
### Preface

This ticket is a 2-parter:

1. **Bug report:** no error message is shown to the user
2. **Feature request:** it would be nice if this would "just work" with no error

### Summary

Prettier is too aggressive in adhering to the `prettierignore` file. I have a `prettierignore` file checked into my project to prevent "format on save" from automatically affecting certain files; e.g. generated files, `node_modules`, etc.

I'd also like to use the manual `Format Document with... Prettier` to quickly format some of these files for readability during development.

When trying to do this manual format action on ignored files, Prettier fails silently: no error message is displayed.

### Github Repository to Reproduce Issue

N/A / private.

### Steps To Reproduce:

1.  Add a file to the `prettierignore` file
2. Open that file in a VSCode editor
3. Manually select `Format Document with..` > `Prettier - Code formatter` from the vscode command pallette

### Expected result

**Desired result:** File should be formatted; it would be cool if Prettier could differentiate between project settings for automatic actions, and IDE preferences for manual IDE UI commands.

**Acceptable result:** Prettier should at least give a visible error message explaining why the file was not formatted.

### Actual result

Nothing happens. UI does not give feedback of any kind.

**VS Code Version**: 1.43.2

**Prettier Extension Version**: 5.5.0

**OS and version**: macOS Catalina

## Prettier Log Output

```
["INFO" - 11:33:23] Formatting <PATH_TO_FILE>.json
["INFO" - 11:33:23] Using ignore file (if present) at <PATH_TO_IGNORE_FILE>
["INFO" - 11:33:23] Loaded module 'prettier@2.2.0' from '<PATH_TO_PROJECT>/node_modules/prettier/index.js'
["INFO" - 11:33:23] File Info:
{
  "ignored": true,
  "inferredParser": null
}
["INFO" - 11:33:23] File is ignored, skipping.
```

**Comment by ntotten** [comment]
There is UI in the bottom bar. I'm not going to show an error message every time as that would be extremely disruptive.

<img width="446" alt="Screen Shot 2020-12-09 at 3 16 08 PM" src="https://user-images.githubusercontent.com/282782/101682395-9145a080-3a31-11eb-9e3a-dd10c783adff.png">

As far as overriding the prettierignore, that is against the philosophy of this extension. We follow the prettier config - the goal is that the result will always be the same if you run prettier from VS Code or from the extension.

**Comment by edwardgalligan** [comment]
> I'm not going to show an error message every time as that would be extremely disruptive.

Just to clarify as it seems this was misinterpreted: this is about showing an error message on explicit user action, not about loudly erroring on any frequent automatic/background action. For example:

<img width="588" alt="Screenshot 2021-01-26 at 17 00 10" src="https://user-images.githubusercontent.com/170268/105877480-f5c7b980-5ff7-11eb-9d04-aa392d02c7f1.png">

Currently when one runs `Format Document` manually, it simply fails silently without any message returned to the user.

**Comment by ntotten** [comment]
It doesn't fail silently, there is a status shown in the bottom bar. The only other option is a dialog box which must be manually dismissed. We had something like that at one point and it was way too noisy.

**Comment by ntotten** [comment]
This has been added in version 6.1.0. Note the 6.0 release is still in preview to try it out see: https://github.com/prettier/prettier-vscode/wiki/Testing-Preview-Releases
