### ISSUE TITLE
yml pretier built in

### ISSUE THREAD

**Issue by KamranShahid** [prettier/prettier-vscode#1678]
I am Visual studio .net user who use to just do ctl K, ctrl D for formating. now need some work on .yml file
I was searching for some extension for formatting and found this one. but there is no straight built in support. have read that i can add .prettierrc.yml but where to add this file and how is not metnioned clearly

**Comment by ntotten** [comment]
You can see prettier's docs here: https://prettier.io/docs/en/index.html
