### ISSUE TITLE
Ctrl + Shift + P -- not work

### ISSUE THREAD

**Issue by jorjik** [prettier/prettier-vscode#1679]
screen https://i.imgur.com/so3n5CQ.png

**Comment by jorjik** [comment]
log:
["INFO" - 14:05:07] Extension Name: esbenp.prettier-vscode.
["INFO" - 14:05:07] Extension Version: 5.8.0.
["INFO" - 14:05:07] Enabling prettier for languages: ansible, css, graphql, home-assistant, html, javascript, javascriptreact, json, json5, jsonc, less, markdown, mdx, mongo, postcss, scss, typescript, typescriptreact, vue, yaml
["INFO" - 14:05:07] Enabling prettier for file extensions: .JSON-tmLanguage, ._js, .avsc, .bones, .cjs, .component.html, .css, .es, .es6, .frag, .geojson, .gltf, .gql, .graphql, .graphqls, .gs, .har, .htm, .html, .html.hl, .ice, .inc, .jake, .js, .js.flow, .jsb, .jscad, .jsfl, .jsm, .json, .json5, .jsonc, .jss, .jsx, .less, .markdown, .mcmeta, .md, .mdown, .mdwn, .mdx, .mir, .mjml, .mjs, .mkd, .mkdn, .mkdown, .njs, .pac, .pcss, .postcss, .reek, .ronn, .rviz, .scss, .sjs, .ssjs, .st, .sublime-build, .sublime-commands, .sublime-completions, .sublime-keymap, .sublime-macro, .sublime-menu, .sublime-mousemap, .sublime-project, .sublime-settings, .sublime-syntax, .sublime-theme, .sublime-workspace, .sublime_metrics, .sublime_session, .syntax, .tfstate, .tfstate.backup, .topojson, .ts, .tsx, .vue, .webapp, .webmanifest, .workbook, .wxs, .wxss, .xht, .xhtml, .xsjs, .xsjslib, .yaml, .yaml-tmlanguage, .yaml.sed, .yml, .yml.mysql, .yy, .yyp
["INFO" - 14:05:07] Enabling prettier for range supported languages: graphql, javascript, javascriptreact, json, typescript, typescriptreact
["INFO" - 14:09:55] Formatting d:\dev\tmp\tmp.html
["INFO" - 14:09:55] Using ignore file (if present) at undefined
["INFO" - 14:09:55] Using bundled version of prettier.
["INFO" - 14:09:55] File Info:
{
  "ignored": false,
  "inferredParser": "html"
}
["INFO" - 14:09:55] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 14:09:55] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\dev\\tmp\\tmp.html",
  "parser": "html"
}
["ERROR" - 14:09:55] Error formatting document.
["ERROR" - 14:09:55] Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (227:1)
  225 | <%end vendors%>
  226 | </ul>
> 227 | </div>
      | ^^^^^^
  228 | </nav>
  229 | <%endif%>
  230 | <%end block_shop_vendors%>
SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (227:1)
  225 | <%end vendors%>
  226 | </ul>
> 227 | </div>
      | ^^^^^^
  228 | </nav>
  229 | <%endif%>
  230 | <%end block_shop_vendors%>
	at vt (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\parser-html.js:41:48413)
	at Mn (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\parser-html.js:113:2409)
	at Un (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\parser-html.js:113:4175)
	at Object.parse (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\parser-html.js:113:4895)
	at Object.parse (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\index.js:13625:19)
	at coreFormat (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\index.js:14899:14)
	at format (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\index.js:15131:14)
	at c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\index.js:57542:12
	at Object.format (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\node_modules\prettier\index.js:57562:12)
	at t.default.<anonymous> (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:17599)
	at Generator.next (<anonymous>)
	at s (c:\Users\Evgeniy\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:11597)
["INFO" - 14:09:55] Formatting completed in 171.4923ms.

**Comment by thorn0** [comment]
```
Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (227:1)
```
This means your file contains a syntax error. Prettier can't format it.
