### ISSUE TITLE
no more popup warnings :(

### ISSUE THREAD

**Issue by smooJitter** [prettier/prettier-vscode#168]
I use to get this nice popup warnings when I would try to save a file with critical errors. I upgrade prettier-vscode and I did change a few settings (I'm not sure what, but I no longer get the nice popup warnings.  When there's error the file would save but prettier will not reformat the code.  Pretter only reformats the code when there are areas.  Although this too is a nice feature, I miss the popups directing me to the error.  How can I get the popup warning back?

**Comment by RobinMalfait** [comment]
The popups were annoying for many users. There is a new output channel where the errors are posted. There is also a statusbar item which indicates if there are errors or not.

Output channel:

![](http://d.rbn.nu/NYFasg+)

Statusbar item:

![](http://d.rbn.nu/zQRSM+)

**Comment by smooJitter** [comment]
lol Understood.  I'll miss them.

**Comment by alexozer** [comment]
@RobinMalfait Would it be reasonable to add an option to disable the Output from prettier? It seems jarring to have eslint problems reported subtly with squiggly lines in the editor but have prettier use Output.

**Comment by orta** [comment]
I shipped a PR to disable the output
