### ISSUE TITLE
Prettier putting trailing commas in the end of object definitions.

### ISSUE THREAD

**Issue by furkangercek** [prettier/prettier-vscode#1687]
Hello, I am using Prettier 5.8.0 with Visual Studio Code alongside vscode-icons extension.

My issue is even though I've changed **Preferences > Settings > Prettier > Trailing Commas : none**

and added  this code below to my .prettierrc file in the root folder

```
{
  "printWidth": 120,
  "trailingComma": "none"
}
```
Prettier is still adding comma in the end of properties, single functions and so on.
I am aware of the fact that this is becoming a common use of the modern JS but in my new workplace, it's becoming really tiresome to check for commit changes when there are changes in every file I touch.

Expected result : 
![image](https://user-images.githubusercontent.com/38816094/101479080-ae5f6e00-3962-11eb-973f-4fd549ccef1c.png)

Actual result : 
![image](https://user-images.githubusercontent.com/38816094/101479111-b5867c00-3962-11eb-87ff-6eaadbc6606b.png)

**VS Code Version**: 1:51.1

**Prettier Extension Version**: 5.8.0

**OS and version**: Windows 10 64bit 1909

## Prettier Log Output

```

["INFO" - 14:40:24] Formatting c:\Users\Scyther\Desktop\cheetah-ui-2\cheetah-ui\src\services\pricing\results.ts
["INFO" - 14:40:24] Using ignore file (if present) at c:\Users\Scyther\Desktop\cheetah-ui-2\cheetah-ui\.prettierignore
["INFO" - 14:40:24] Loaded module 'prettier@2.2.1' from 'c:\Users\Scyther\Desktop\cheetah-ui-2\cheetah-ui\node_modules\prettier\index.js'
["INFO" - 14:40:24] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 14:40:24] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 14:40:24] Using config file at 'c:\Users\Scyther\Desktop\cheetah-ui-2\cheetah-ui\package.json'
["INFO" - 14:40:24] Prettier Options:
{
  "filepath": "c:\\Users\\Scyther\\Desktop\\cheetah-ui-2\\cheetah-ui\\src\\services\\pricing\\results.ts",
  "parser": "typescript",
  "printWidth": 120,
  "prettier.trailingComma": "none"
}
["INFO" - 14:40:24] Formatting completed in 43.5695ms.

```

**Comment by thorn0** [comment]
Something looks wrong in the log output:
```
"prettier.trailingComma": "none"
```
Why is it "prettier.trailingComma" instead of "trailingComma"?
