### ISSUE TITLE
Prettier not working

### ISSUE THREAD

**Issue by matthewbrice** [prettier/prettier-vscode#1689]
I'm new to VS Code but installed Prettier.  It was working for a short time, but now in status bar it says "Extension: 'Prettier - Code Formatter' cannot format <filename>".  I have added in json, etc.  When going to "Configure Default Formatter..." the only option to select now is "Python".  (Used to show Prettier).  Not sure how to troublshoot from here. 

`{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[python]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}`

**Comment by ntotten** [comment]
Try asking on stackoverflow. I don't provide support here.
