### ISSUE TITLE
format code only if prettier file exists vscode 

### ISSUE THREAD

**Issue by jimyhdolores** [prettier/prettier-vscode#1711]
I have Prettier installed in my vscode and set the requireConfig option to true, but I can't find any option that indicates to format the code with the prettier specifications only if the .prettierrc file exists, it is very annoying to be changing the formatter in each project that I don't use prettier

**Comment by ntotten** [comment]
The setting is called requireConfig

**Comment by jimyhdolores** [comment]
Hello, thanks for answering, I don't think you explain me well, look, I already have that property activated in the configurations of my vscode, but when I try to format the code in a project that does not have the file, in theory I should take the formatter of vscode, but it does not do it since the Prettier formatter is by default, the solution is to change the default formatter to vscode, but to do this for each project as it is not viable, there should be a hierarchy, if there is no prettier that take default vscode settings.

**Comment by ntotten** [comment]
The extension has no control over that. It's the behavior of VSCode.
