### ISSUE TITLE
Linting on HTTP headers is inconsistent.

### ISSUE THREAD

**Issue by TovrikTheThird** [prettier/prettier-vscode#172]
If I have a header like: 

`headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Authorization': 'Basic Y29tbW9ucG9asdffOnBvd2Vyc2Nob29s'
 }`

Prettier will force the single-quotes around Authorization to be dropped but won't do this on Content-Type (obviously because it can't since it is hyphenated). Either this needs a fix, or there needs to be some way to customize this setting so this no longer happens. If one already exists, please let me know :D

**Comment by RobinMalfait** [comment]
Hey @TovrikTheThird 

You can use eslint for this specific use case.
If you already have an eslint file you can add the following rule.

http://eslint.org/docs/rules/quote-props.html

```
quote-props: ["error", "consistent"]
```

You can also enable `prettier.eslintIntergration` to use the eslint file as well.

**Comment by CiGit** [comment]
There is prettier/prettier#2461 about that. @RobinMalfait gave a workaround.
