### ISSUE TITLE
Check mark is in the opposite position to ESLint

### ISSUE THREAD

**Issue by birtles** [prettier/prettier-vscode#1724]
### Summary

The status symbol from Prettier is in the opposite position to ESLint.

### Github Repository to Reproduce Issue

n/a

### Steps To Reproduce:

1. Install prettier-vscode
1. Install [ESLint by Dirk Baeumer](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
1. Open a project that uses prettier and ESLint

### Expected result

The check marks should have the same position with regards to their labels.

### Actual result

They do not have the same position. After considerable deliberation, I think the ESLint ordering is preferable. Also colons as delimeters seem to be going out-of-fashion when not strictly necessary.

### Additional information

![image](https://user-images.githubusercontent.com/1232595/104258732-7d271000-54c3-11eb-88a2-1f1d019c6c0f.png)

**VS Code Version**: 1.52.1

**Prettier Extension Version**:  5.8.0

**OS and version**: Windows 10

## Prettier Log Output

```
["INFO" - 9:43:23 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 9:43:23 AM] Extension Version: 5.8.0.
["INFO" - 9:43:23 AM] Enabling prettier for languages: ansible, css, graphql, home-assistant, html, javascript, javascriptreact, json, json5, jsonc, less, markdown, mdx, mongo, postcss, scss, typescript, typescriptreact, vue, yaml
["INFO" - 9:43:23 AM] Enabling prettier for file extensions: .JSON-tmLanguage, ._js, .avsc, .bones, .cjs, .component.html, .css, .es, .es6, .frag, .geojson, .gltf, .gql, .graphql, .graphqls, .gs, .har, .htm, .html, .html.hl, .ice, .inc, .jake, .js, .js.flow, .jsb, .jscad, .jsfl, .jsm, .json, .json5, .jsonc, .jss, .jsx, .less, .markdown, .mcmeta, .md, .mdown, .mdwn, .mdx, .mir, .mjml, .mjs, .mkd, .mkdn, .mkdown, .njs, .pac, .pcss, .postcss, .reek, .ronn, .rviz, .scss, .sjs, .ssjs, .st, .sublime-build, .sublime-commands, .sublime-completions, .sublime-keymap, .sublime-macro, .sublime-menu, .sublime-mousemap, .sublime-project, .sublime-settings, .sublime-syntax, .sublime-theme, .sublime-workspace, .sublime_metrics, .sublime_session, .syntax, .tfstate, .tfstate.backup, .topojson, .ts, .tsx, .vue, .webapp, .webmanifest, .workbook, .wxs, .wxss, .xht, .xhtml, .xsjs, .xsjslib, .yaml, .yaml-tmlanguage, .yaml.sed, .yml, .yml.mysql, .yy, .yyp
["INFO" - 9:43:23 AM] Enabling prettier for range supported languages: graphql, javascript, javascriptreact, json, typescript, typescriptreact
```

**Comment by ntotten** [comment]
Merged change. Thanks!
