### ISSUE TITLE
Format Selection isn't working

### ISSUE THREAD

**Issue by bsvipas** [prettier/prettier-vscode#173]
Hello, I opened issue in VS Code, but seems this is `Prettier` problem. Format Selection is formatting ALL file, not the selection. I'm using latest VS Code (stable) and latest Prettier plugin. Here is my opened issue in VS Code https://github.com/Microsoft/vscode/issues/30712.

**Comment by CiGit** [comment]
Are you using eslintIntegration? #137

**Comment by bsvipas** [comment]
@CiGit Yes, you're right, but it also didn't working properly. I have installed ESLint locally and I have this extension without Prettier installed as a package, I'm using built-in Prettier in extension.

```json
  "prettier.eslintIntegration": true,
  "prettier.printWidth": 120,
  "prettier.singleQuote": true
```

**Comment by CiGit** [comment]
can you share your eslint config?
Format selection is a known issue with eslint #137. Still don't know what to do with it.
@RobinMalfait you may have an idea, your extension was based on it :-)

**Comment by invisor** [comment]
I have the same problem

**Comment by wbern** [comment]
I have the exact same problem. :(

**Comment by CiGit** [comment]
Duplicate of #137

**Comment by mallikarjuna-sharma** [comment]
Format selection is not showing vs code.
