### ISSUE TITLE
Add support for breakBeforeElse

### ISSUE THREAD

**Issue by mviens** [prettier/prettier-vscode#1743]
**Is your feature request related to a problem? Please describe.**
It is super annoying that I cannot use prettier because it lacks an option of specifying a line break before an "else" statement. I have had to use Prettier Now, which does have this option, but it is older and does not support everything that Prettier does. 

**Describe the solution you'd like**
Please add an option for adding a line break before an "else". This has been implemented on Prettier Now.

**Describe alternatives you've considered**
Yes, Prettier Now supports "breakBeforeElse", but it is older and does not support everything that Prettier supports.
https://github.com/remimarsal/prettier-now-vscode

**Additional context**
n/a

**Comment by ntotten** [comment]
See: https://prettier.io/docs/en/option-philosophy.html
