### ISSUE TITLE
Issue on M1

### ISSUE THREAD

**Issue by ThongKun** [prettier/prettier-vscode#1746]
Issue Type: <b>Bug</b>

ARM architechture

Extension version: 5.8.0
VS Code version: Code - Insiders 1.53.0-insider (1a4b35c2023a41efae1af2661026d57cea90ef5c, 2021-01-21T05:14:13.256Z)
OS version: Darwin arm64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id 6ece0878-bf5c-4299-b54e-8ffc25c3e9db|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry914:30244316
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30247032
core-portspanelcf:30233468

```

</details>

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
