### ISSUE TITLE
Infinite "Prettier - Code formatter" on save React with onClick attributes

### ISSUE THREAD

**Issue by MKlblangenois** [prettier/prettier-vscode#1754]
### Summary

When I add `onClick={() => setState(stateValue)}` on any element and I save, Prettier make an infinite loading of `Formatter` task

### Steps To Reproduce:

1.  Going into a React project (I've tried on create-react-app, Gatsby and Next, and I got the same issue)
2. Try to add `onClick` on any button like `onClick={() => console.log('foo')}`
3. Save your file

### Actual result

The only way to got my save back is to close VS code and relaunch it, Prettier will no longer block on this argument.

### Additional information

<img width="952" alt="Capture d’écran 2021-01-28 à 10 29 56" src="https://user-images.githubusercontent.com/42929225/106118853-d85c3200-6154-11eb-80c4-232208e4ae64.png">

**VS Code Version**: v1.52.1

**Prettier Extension Version**: v5.8.0

**OS and version**: MacOS v11.0.1 (Intel Mac)

## Prettier Log Output

```
["INFO" - 10:30:45 AM] Formatting /Users/loganblangenois/Documents/Sites/Next/biowallonie-fournisseurs-bio/layouts/index.js
["INFO" - 10:30:45 AM] Using ignore file (if present) at /Users/loganblangenois/Documents/Sites/Next/biowallonie-fournisseurs-bio/.prettierignore
["INFO" - 10:30:45 AM] Using bundled version of prettier.
["INFO" - 10:30:45 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 10:30:45 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:30:45 AM] Using config file at '/Users/loganblangenois/Documents/Sites/Next/biowallonie-fournisseurs-bio/.prettierrc'
["INFO" - 10:30:45 AM] Prettier Options:
{
  "filepath": "/Users/loganblangenois/Documents/Sites/Next/biowallonie-fournisseurs-bio/layouts/index.js",
  "parser": "babel",
  "trailingComma": "es5",
  "tabWidth": 3,
  "semi": true,
  "singleQuote": false,
  "bracketSpacing": true,
  "proseWrap": "never",
  "printWidth": 200000,
  "jsxBracketSameLine": false
}
```

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
