### ISSUE TITLE
Prettify all changed files before commit

### ISSUE THREAD

**Issue by itsmeneartou** [prettier/prettier-vscode#1755]
**Is your feature request related to a problem? Please describe.**
I feel frustrated going to each file and prettify it just before a commit. I would like to prettify all changed files at once.

**Describe the solution you'd like**
I would like to prettify all changed files at once using a keyboard shortcut. 

**Describe alternatives you've considered**
N/A

**Additional context**
Currently I go to each changed file and press 'Ctrl+Shift+P' and then make a commit but I would like to have a feature such that I can prettify all the files that are changed since the last commit. I don't know If it already exists. Thank You in advance.

**Comment by ntotten** [comment]
I'd recommend using a pre-commit hook: https://prettier.io/docs/en/precommit.html
