### ISSUE TITLE
how to make a blank space between chinese characters and english characters.

### ISSUE THREAD

**Issue by tykdn** [prettier/prettier-vscode#1759]
how to make a blank space between chinese characters and english characters.

### Like this：
***before prettier***：
const str = 'my name is汉字'；
***after prettier***：
const str = 'my name is 汉字'；

Thanks !

**Comment by tykdn** [comment]
Supplement，In React project.

**Comment by MapleCCC** [comment]
Prettier is a code formatter, not a natural language formatter. The formatting you require could be realized by [pangu.js](https://github.com/vinta/pangu.js).

**Comment by tykdn** [comment]
Thanks, closed.
