### ISSUE TITLE
Operators on new lines?

### ISSUE THREAD

**Issue by aminomancer** [prettier/prettier-vscode#1760]
I noticed something that seems a little inconsistent to me though maybe it's intentional. Prettier seems to do something like ESLint's operator-linebreak rule. I have been using the airbnb config, plus eslint-config-prettier to clear up the inconsistencies, but that just prevents warnings about the operators that Prettier puts at the end of the line.

The thing is, I kind of prefer to put all operators at the beginning of the line, not to have a special exception for the ternary operator. I might format my code with Prettier like 30 times a day, but only auto-fix eslint problems like once or twice at most. So although I'm able to tell eslint to put my operators at the beginning of the line, I can't tell Prettier to. I don't want to auto-fix every time I format if that makes sense. As it is, I just have eslint's rule set to match Prettier's, (the eslint default, not airbnb's) but it's the opposite of what I actually use in my own personal code.

I think it'd be a useful feature for prettier to just have a basic toggle for the operator-linebreak rule, since it's something that comes up so often. THanks 😊

**Comment by ntotten** [comment]
See: https://prettier.io/docs/en/option-philosophy.html
