### ISSUE TITLE
Defining shared prettier configuration in package.json file throws error on format

### ISSUE THREAD

**Issue by adamtay** [prettier/prettier-vscode#1764]
### Summary

`prettier-vscode` throws an error when using the `prettier` key in the `package.json` file that is referencing a shared prettier config file from an external npm package.

However, there are no issues when defining a `prettier.config.js` file that extends from the shared prettier config instead from the exact same external npm package.

### Steps To Reproduce:

Shared `prettier.json` configuration file (`@my-org/prettier-config`):

```json
{
  "$schema": "http://json.schemastore.org/prettierrc",
  "singleQuote": true
}
```

Application's `package.json` file:

```json
{
  "name": "application",
  "version": "1.0.0",
  "scripts": {
    "format": "prettier --write src"
  },
  "dependencies": {
    "prettier": "^2.2.1"
  },
  "prettier": "@my-org/prettier-config"
}
```

VSCode Prettier Output:

```
["INFO" - 10:27:43 AM] Formatting /my/path/to/some/application/src/App.tsx
["ERROR" - 10:27:43 AM] Invalid prettier configuration file detected.
["ERROR" - 10:27:43 AM] Cannot find module '@my-org/prettier-config' from '/my/path/to/some/application'
Error: Cannot find module '@my-org/prettier-config' from '/my/path/to/some/application'
    at Function.resolveSync [as sync] (/Users/user/.vscode/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/index.js:21003:13)
    at resolve$1 (/Users/user/.vscode/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/index.js:21141:20)
    at Object.transform (/Users/user/.vscode/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/index.js:25542:30)
    at run (/Users/user/.vscode/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/third-party.js:9851:51)
    at cacheWrapper (/Users/user/.vscode/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/third-party.js:9703:20)
    at cacheWrapper (/Users/user/.vscode/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/third-party.js:9703:20)
    at Explorer.search (/Users/user/.vscode/extensions/esbenp.prettier-vscode-5.8.0/node_modules/prettier/third-party.js:9836:22)
    at async Promise.all (index 0)

```

The below works and formats as expected when defining a `./prettier.config.js` file instead (no `prettier` key present in the `package.json` file).

```js
module.exports = require("@my-org/prettier-config");
```

VSCode Prettier Output:

```
["INFO" - 10:37:06 AM] Formatting /my/path/to/some/application/src/App.tsx
["INFO" - 10:37:06 AM] Using ignore file (if present) at /my/path/to/some/application/.prettierignore
["INFO" - 10:37:06 AM] Loaded module 'prettier@2.2.1' from '/my/path/to/some/application/node_modules/prettier/index.js'
["INFO" - 10:37:06 AM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 10:37:06 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 10:37:06 AM] Using config file at '/my/path/to/some/application/prettier.config.js'
["INFO" - 10:37:06 AM] Prettier Options:
{
  "filepath": "/my/path/to/some/application/src/App.tsx",
  "parser": "typescript",
  "singleQuote": true
}
["INFO" - 10:37:06 AM] Formatting completed in 123.521096ms.

```

### Expected result

As per the prettier documentation, https://prettier.io/docs/en/configuration.html#sharing-configurations

Sharing a Prettier configuration is simple: just publish a module that exports a configuration object, say @company/prettier-config, and reference it in your package.json:

```json
{
  "name": "my-cool-library",
  "version": "9000.0.1",
  "prettier": "@company/prettier-config"
}
```

`prettier-vscode` should be able to support this situation when dealing with shared configurations from a external npm package.

### Actual result

`prettier-vscode` throws an error as per above log listed in the reproduction steps.

### Additional information

**VS Code Version**: 1.52.1

**Prettier Extension Version**: 5.8.0

**OS and version**: macOS 10.14.6

**Node and NPM version**: node: v12.16.2 & npm: 6.14.4

**Comment by edouard-lopez** [comment]
Got a similar issue when configuration is in `.prettierrc.json`

**Comment by ntotten** [comment]
Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
