### ISSUE TITLE
Pass @prettier plugin settings from settings.json to prettier

### ISSUE THREAD

**Issue by piejanssens** [prettier/prettier-vscode#1769]
**Is your feature request related to a problem? Please describe.**
I use @prettier/plugin-xml to format XML files. There is no quick way to open an XML file in vscode and format it using @prettire/plugin-xml as a config is required to suit my formatting preferences.

**Describe the solution you'd like**
 and that needs to be provided via a config file. I would like to see the possibility to define the configuration for that plugin via the vscode settings.json. At the moment AFAIK you can work with a config file on project level or you can overrule any default config location by setting the config path. This last option would also ignore the (shared) project settings.

**Describe alternatives you've considered**
notepad++, no really, I wouldn't know how to achieve this non-project related Prettier XML formatting in vscode.

**Comment by ntotten** [comment]
I'm not super interested in adding new settings for every prettier extension. Maybe there is a generic solution. Feel free to suggest an implementation that would work for any plug-in. Maybe a json config blob?

**Comment by piejanssens** [comment]
Wouldn't it be possible to use a single `prettier.pluginConfiguration` configuration property which is in itself of type `object`?

**Comment by ntotten** [comment]
Closing as I haven't seen a PR on this.
