### ISSUE TITLE
Mark "prettier.packageManager" setting as deprecated instead of deleting it

### ISSUE THREAD

**Issue by yume-chan** [prettier/prettier-vscode#1773]
**Is your feature request related to a problem? Please describe.**
"prettier.packageManager" setting is no longer required since #1700, however it might persist in many users' settings.json. Now Code only displays a very subtle "hint" reads "unknown configuration setting" (see microsoft/vscode#115957)

**Describe the solution you'd like**
As noted by @usernamehw in the linked issue, we can use `deprecationMessage` / `markdownDeprecationMessage` to tell our users it's now deprecated and the reason.

**Describe alternatives you've considered**
N/A

**Additional context**
https://code.visualstudio.com/api/references/contribution-points#contributes.configuration

**Comment by ntotten** [comment]
Fixed.
