### ISSUE TITLE
[Feature Request] prettier.enableLanguages

### ISSUE THREAD

**Issue by lonix1** [prettier/prettier-vscode#1786]
**Is your feature request related to a problem? Please describe.**
If I need to format only scss files, and let other formatters handle other file types, then I must do this:
````
prettier.disableLanguages: [
  "html",
  "json",
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "json",
  "graphql",
  "...",    // and maybe more?
]
````

I got those languages from [here](https://github.com/prettier/prettier-vscode/blob/main/src/LanguageResolver.ts#L17) and [here](https://github.com/prettier/prettier-vscode/blob/main/src/LanguageResolver.ts#L47).

That is extra config, for something so simple. Also I'm not even sure where to find the languages this plugin supports, and what are their names, etc.

**Describe the solution you'd like**
An easier approach is: `prettier.enableLanguages`.

If it exists, only those languages will be targeted. No need to disable anything.

And if both settings exist, then `prettier.enableLanguages` is ignored, to be backwards compatible.

**Comment by ntotten** [comment]
Set the default formatter for whatever you want. See: https://stackoverflow.com/questions/49640469/how-do-you-determine-which-formatter-is-being-used-for-vs-code

**Comment by lonix1** [comment]
Thank you.

Note though that its a workaround, not a solution.

There are already default formatters for all those languages. But this plugin adds itself as an option, unnecessarily. An "enable" option would be better.

**Comment by ntotten** [comment]
I'm don't really agree. The whole point of being able to pick formatters in VS Code is to allow you to customize which of the possibly many formatters you have registered. A simple solution if you only want to use Prettier for a few languages is to set your default formatters like this:

```
{
  "editor.defaultFormatter": null,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

This way prettier will only run on the languages you specify. 

I am actually probably going to get rid of the disabledLanguages setting entirely as it is now redundant between the vscode setting and prettierignore.

**Comment by lonix1** [comment]
I understand.

But just a thought:

`"editor.defaultFormatter": null,`: then you'd need to explicitly set a formatter for every language you use.

When not setting it to null, the correct one is automatically chosen ("just works").

**Comment by ntotten** [comment]
Let me think about it. I want to simplify the config in v6.

**Comment by lonix1** [comment]
Simpler config would be great... Thanks!

**Comment by ntotten** [comment]
Moving discussion to #1854
