### ISSUE TITLE
Don't report formatting capability for disabled languages

### ISSUE THREAD

**Issue by rafifos** [prettier/prettier-vscode#1787]
**Is your feature request related to a problem? Please describe.**

The problem is: I have prettier enabled, and I want to disable it (via `settings.json`) for a language that already has a formatter (like `json`). When trying to format it, `vscode` prompts to choose a formatter for that language.

**Describe the solution you'd like**

Ideally, the extension shouldn't report the capability to format the languages set by `prettier.disableLanguages` setting. I'd take a quick look at the code and it _seems_ possible, but I don't know if it have any other implications.

See:

https://github.com/prettier/prettier-vscode/blob/4fb0cd18ea5f7b61379eabd605a40742187e3798/src/LanguageResolver.ts#L33

**Describe alternatives you've considered**

The most cheap alternative is to just set the default formatter for that `languageId`, but creating a language entry just for disabling Prettier seems not... _okay_(?)

There's also the possibility to disable Prettier for a workspace that you use another formatter, but again, this don't seem _okay_(?)

**Additional context**

--

**Comment by ntotten** [comment]
It should be disabled for languages set as such. I'll need more info to repro.

**Comment by lonix1** [comment]
Same problem here

````
"prettier.disableLanguages": [
  // ...
  "typescript",
]
````

But when opening a `.ts` file, I get "choose your formatter" prompt.

I can suppress the prompt by doing:
````
"[typescript]": { "editor.defaultFormatter": "vscode.typescript-language-features" }
````

But that seems unnecessary. And I need to do that for every language.

Related to my issue #1786. Prettier is too aggressive. There should be a `prettier.enableLanguages` setting to eliminate this problem altogether.

**Comment by rafifos** [comment]
It's like @lonix1 said, it's too much complexity. You _can_ live with setting the default formatter for *every* language that you don't run prettier, or you can choose to enable prettier on *every* language that you use it, or you can (on a workspace basis) disable/enable prettier and other formatters.

**Comment by ntotten** [comment]
I'm not planning on doing this. It seems like a lot of work just to get rid of a little icon in the corner. Happy to take a PR if somebody cares about this a lot.
