### ISSUE TITLE
Reopen #716

### ISSUE THREAD

**Issue by cabello** [prettier/prettier-vscode#1792]
Hi,

I love prettier, thank you for making this and sharing with the world :purple_heart:.

I've been affected by #716 but the bot is a bit aggressive, so it just closed and locked the issue preventing new collaborators to join the discussion.

Would you mind unlocking that one please?

Thank you, 🙏

**Comment by ntotten** [comment]
See: https://github.com/prettier/prettier-vscode/issues/716#issuecomment-582080980

My recommendation is to open an issue with Microsoft. As of now, there isn't anything we can do about it.
