### ISSUE TITLE
Format of braces

### ISSUE THREAD

**Issue by Gigasoft** [prettier/prettier-vscode#1814]
Hi,

I am working with a company that has an odd set of coding standards. For javascript they want braces on a new line with a tab in front (two apaces). In other words ...

if -space-(condition)
-space-space{
-space-space}
else 
-space-space{
-space-space}

if (blah)
  {
  }
else
  {
  }

Is it possible to customize your extension to do the same thing? Or is this a new feature?

They plan on changing their standard down the road for new products. But they have reams of JS files with this format,. 

Right now, we use visual studio and it is a nightmare to keep this format. It sometimes requires us to use notepad. 

I would like to use Visual Studio Code and your extension to releave the pane.

Any suggestions are appreciated.

Thanks,
Tom

**Comment by ntotten** [comment]
Prettier has a few options because of history. But we won’t add more of them. For more details see: https://prettier.io/docs/en/option-philosophy.html
