### ISSUE TITLE
Prettier not working again

### ISSUE THREAD

**Issue by natakusuma38** [prettier/prettier-vscode#1820]
_the version im using : v5.9.2_

**The Prettier wont work**
the problem : all my setting is correct and i do all the requirement for the extension to work well, all work fine but after typing (html) for like 3 file then all feature is stop working and doesnt do anything when i save some files (format on save ON, esbenp.prettier-vscode is selected)

**Im trying to fix the problem**
yes, im trying so hard to fix the problem but none if them is work , even i reinstall and switching between another extension still not work

**Sorry for my bad english**

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
