### ISSUE TITLE
Error: Couldn't resolve parser "css". Parsers must be explicitly added to the standalone bundle.

### ISSUE THREAD

**Issue by n1developer-ubt** [prettier/prettier-vscode#1825]
Error: Couldn't resolve parser "CSS". Parsers must be explicitly added to the standalone bundle.

Unable to use any parser, prettier always gives the same error, nodejs.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
