### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by bhaireshm** [prettier/prettier-vscode#1829]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `5.9.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 2069,
		"activateCallTime": 2958,
		"activateResolvedTime": 12,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "esbenp.prettier-vscode",
				"_lower": "esbenp.prettier-vscode"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": []
}
```

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
