### ISSUE TITLE
The tag has already been closed by another tag

### ISSUE THREAD

**Issue by bhavik4it** [prettier/prettier-vscode#1834]
SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (372:29)

  <img src="/images/secure.svg"
                style="width: 60px;float: left;vertical-align: middle;position: absolute;top: -32px;background: white;padding: 10px;" >
                
                
on research found that it is because of missing closing of Image  but what settings needed to fix or ignore?

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
