### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Syed-Mohammad** [prettier/prettier-vscode#1837]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `6.2.0`
- OS Version: `Linux x64 5.8.0-44-generic`
- VSCode version: `1.54.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
