### ISSUE TITLE
Extension 'Prettier - Code formatter' cannot format ....

### ISSUE THREAD

**Issue by Namukk** [prettier/prettier-vscode#1838]
### Summary

_Short summary of what is going on or to provide context_.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

It should have made my code prettier

### Actual result

It doesn't work

### Additional information

<img width="552" alt="스크린샷 2021-03-14 오후 10 30 18" src="https://user-images.githubusercontent.com/63292204/111070488-544be700-8515-11eb-998c-3f08f8baeab1.png">

**VS Code Version**: 1.54.2

**Prettier Extension Version**: 6.2.0

**OS and version**: macOs Big Sur 11.2.3

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREESHOT, COPY AND PASTE THE TEXT
```
["INFO" - 10:18:56 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 10:18:56 PM] Extension Version: 6.2.0.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
