### ISSUE TITLE
duplicate items in vscode dropdown menu

### ISSUE THREAD

**Issue by elixiao** [prettier/prettier-vscode#1840]
Why have two duplicate items? Which one should I use?

![image](https://user-images.githubusercontent.com/68963108/111111224-eb0db780-8598-11eb-809c-fb7356b5a139.png)

**Comment by ntotten** [comment]
My guess is you installed the beta. Uninstall the "prettier.prettier-vscode-beta" extension.

**Comment by bdielman** [comment]
I'm noticing a similar issue after the most recent VSCode update. Notifications are reporting multiple formatters and I'm seeing this when prompted to choose one (beta not installed):

<img width="454" alt="Screen Shot 2021-03-15 at 10 19 07 AM" src="https://user-images.githubusercontent.com/94547/111168170-306dbd00-8578-11eb-9fbf-043cce8a9dcf.png">
<img width="364" alt="Screen Shot 2021-03-15 at 10 19 14 AM" src="https://user-images.githubusercontent.com/94547/111168181-34014400-8578-11eb-80e1-037f97fa2161.png">

**Comment by vodoleev-vladislav** [comment]
Same problem here. Beta not installed. Deleted all extensions and cache and reinstalled prettier to test this. 
Every time i change any setting related to prettier i get one more duplicate until i restart vs code.

**Comment by SamuelQuinones** [comment]
+1 also having this issue, beta not installed.  Tried uninstalling and re-installing to no avail.  Also in my most recent attempt to fix it, it showed up 6 times in the list ... Which was admittedly kind of funny

**Comment by ntotten** [comment]
Ah, I think I know the problem. Is this a large project with multiple `package.json` files?

**Comment by SamuelQuinones** [comment]
Well in my case, the presence of a package.JSON file has no bearing.  I opened a workspace without one and the issue still occurred

**Comment by bdielman** [comment]
Just one `package.json` in the project that I'm seeing the issue.

**Comment by ntotten** [comment]
This should be fixed in `6.3.1`. Please try and let me know.

**Comment by SamuelQuinones** [comment]
the issue appears to be resolved for me

**Comment by bdielman** [comment]
> This should be fixed in `6.3.1`. Please try and let me know.

This fixed the issue. Thanks!
