### ISSUE TITLE
continually complains "Failed to load module"

### ISSUE THREAD

**Issue by felix9** [prettier/prettier-vscode#1846]
### Summary

1. `git clone https://github.com/prettier/prettier-vscode.git test-repo`
2. do not run `yarn install` or `npm install` in test-repo.
3. Using a fresh install of vscode 1.54.3 and prettier-vscode 6.2.0
4. `code test-repo`

an error pops up every time I open a js file:
> Failed to load module. If you have prettier or plugins referenced in package.json,
ensure you have run `npm install`
Attempted to load Prettier module from ...

this is extremely annoying. I know I didn't run yarn install. I'm deliberately not running yarn install because I'm just browsing the code, I'm not trying to build it, I don't even have yarn installed at all.

workaround: disable vscode-prettier for all the repos I'm just browsing (or disable globally and just enable for the few that I am actually working on)

**Comment by ntotten** [comment]
Fixed in 6.3.0
