### ISSUE TITLE
Configuration for disabling formatting

### ISSUE THREAD

**Issue by ntotten** [prettier/prettier-vscode#1854]
Previously, you could disable languages with the `disableLanguages` config. However, this was unreliable because the extension also registers formatters for document selectors. There needs to be a way to globally disable prettier for languages/selectors.

There has also been a request to have a `enableLanguages` feature. There needs to be a way to do this without a lot of complicated configuration.

**Comment by donocode** [comment]
Interested to see how this goes, since the move from the previous configuration style to the current one I have not been able to find a configuration that successfully prevents prettier from formatting my yaml files.

**Comment by ntotten** [comment]
There seems to be very little interest in this issue. I will plan on closing it fairly soon unless I get some more feedback and suggestions.

**Comment by lonix1** [comment]
Would avoid the issue mentioned in #1786

**Comment by ntotten** [comment]
I am closing this as there has been almost zero interest.
