### ISSUE TITLE
vscode typescript format

### ISSUE THREAD

**Issue by codercmd** [prettier/prettier-vscode#1858]
I use vscode typescript.
setting:  "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.formatOnSave": true,

my code change like this: 
if (a == 6) {
      let b = 1;
}

I wish like this:
if (a == 6)
 {
      let b = 1;
 }

how to make I wish it?

**Comment by ntotten** [comment]
Prettier has a few options because of history. But we won’t add more of them. For more details see: https://prettier.io/docs/en/option-philosophy.html
