### ISSUE TITLE
ignore-path

### ISSUE THREAD

**Issue by LeeDou** [prettier/prettier-vscode#1860]
.prettierignore file do not effected as i think.

for example, i open a workspace and different project in this with VSCode. each project have their .prettierignore file，in fact, this .prettierignore donot effected like .ignore file in project.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
