### ISSUE TITLE
prettier-vscode not working for files managed by plugin when installed through pnpm

### ISSUE THREAD

**Issue by wighawag** [prettier/prettier-vscode#1878]
### Summary

prettier-vscode ignore plugins when used in a vscode workspace in a mono repo installed with pnpm

### Github Repository to Reproduce Issue

https://github.com/wighawag/issue-prettier-pnpm

### Steps To Reproduce:
 1. git clone https://github.com/wighawag/issue-prettier-pnpm
 2. pnpm install
 4. open vs code
 5. edit a `.svelte` file and save

### Expected result

Expect prettier to prettify every files, including the one handled by prettier plugins (like .svelte file)

### Actual result

The .svelte file are completely ignored by vscode, even though the plugin for svelte is installed.

Note that it works fine when the mono repo is installed with yarn, see yarn branch here : https://github.com/wighawag/issue-prettier-pnpm/tree/yarn

**VS Code Version**: 1.52.0

**Prettier Extension Version**: 5.8.0

**OS and version**: Windows 10

## Prettier Log Output

When saving a .svelte file no log get outputed. also the prettier icon do not show up for these files

**Comment by GitGangGuy** [comment]
Just tested switching my repository from Yarn Classic/v1 to `pnpm` (after having unsuccessfully tried using Yarn v2/PnP cause it breaks everything) and was surprised by the speed bump, less disk space usage and that everything continued to work fine. This appears to be the only caveat I have found with using pnpm so far; I'm not sure if this is pnpm's fault or if pnpm simply hasn't been accounted for by the prettier devs, but I'd really like to see prettier plugins work again in my IDE 😄

**Comment by wighawag** [comment]
@GitGangGuy yes the bug is specific to prettier-vscode extension
even if you specify the plugin path, the extension fails to use it

**Comment by bryanmylee** [comment]
As a temporary workaround, I've configured a run on save script whenever working with Svelte files. Simply install the Run on Save extension for VSCode, and add the following script.

`settings.json`
```json
{
  "emeraldwalk.runonsave": {
     "commands": [
       {
         "match": "\\.svelte$",
         "cmd": "npx prettier --write --plugin-search-dir=. ${file}"
       }
    ]
  }
}
```

**Comment by willsoto** [comment]
As a workaround for this, you can create a `.prettierrc.js` in the monorepo and use `require.resolve` to generate the complete path to the plugin. Example:

```js
module.exports = {
  plugins: [require.resolve("prettier-plugin-svelte")]
}
```

**Comment by ntotten** [comment]
I'm happy to take a pull request on this, but this isn't something I plan on doing myself.
