### ISSUE TITLE
Not adopting rules from tslint.json

### ISSUE THREAD

**Issue by vajahath** [prettier/prettier-vscode#188]
My tslint.json is at workspace root.
but prettier seems to follow its own rules..

**Comment by CiGit** [comment]
We use prettier-eslint which reads from eslint only.
See prettier/prettier-eslint#92

**Comment by vajahath** [comment]
@CiGit Let me know if there is something I can do to fix this issue.

**Comment by CiGit** [comment]
I think @azz has something which may help for that issue.

**Comment by azz** [comment]
I'd like to add tslintIntegration to this extension but it's blocked on azz/prettier-tslint#1

**Comment by Zephir77167** [comment]
Looking forward to it! Thanks for both awesome plugins :+1:

**Comment by carsonpowers** [comment]
Anxiously looking forward to this feature! Keep up the good jorb.

**Comment by YouYue123** [comment]
Looking forward for this feature!!

**Comment by zheeeng** [comment]
Expecting on this intIntegration!

**Comment by Jancat** [comment]
Is there any progress?

**Comment by hantsy** [comment]
Any updates?

**Comment by ummahusla** [comment]
Would be supa useful

**Comment by elibolonur** [comment]
Any updates yet? Looking really forward for this feature

**Comment by ummahusla** [comment]
@jordandrako yep, you are correct, so @CiGit can we carry on bumping this issue? 😄

**Comment by CiGit** [comment]
PR in progress #414

**Comment by whitecolor** [comment]
So it is correct that it is already working with `"prettier.tsLintIntegration": true` in vscode settings, and issue may be closed?
