### ISSUE TITLE
Formatter hangs forever

### ISSUE THREAD

**Issue by stoplion** [prettier/prettier-vscode#1880]
![image](https://user-images.githubusercontent.com/231343/113350759-bdda3c80-92ee-11eb-8671-11d965e8e70c.png)

**Getting this message several times every hour:**

`Saving 'index.css': Running 'Prettier - Code formatter' Formatter`

The formatter hangs and I have to restart VSCode. It isn't fun.

-----------

- [x] Write a summary of your issue
"Click the "Prettier" button in the bottom toolbar and copy all the out put log here."

- [🤔] Include a link to a github repo that can be used to reproduce the issue or exact reproduction steps.

I'm not sure how I would go about creating a repo that reproduces an extension bug in VSCode

- [x] Provide the expected result

Expected result is it DOES NOT hang forever.

- [x] Provide the actual result

It hangs forever.

- [x] Include extension, os, and vs code information

`Prettier - Code formatter [6.3.1]`
`VSCode Version: 1.55.0-insider`
`OS X 10.15.7`

- [x] Include Prettier extension log
I've enabled the prettier debug output. 
Not seeing any output here. But I do see this..
![image](https://user-images.githubusercontent.com/231343/113351738-20800800-92f0-11eb-9460-cc5928f2d0a4.png)

### Summary

_Short summary of what is going on or to provide context_.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**Prettier Extension Version**:

**OS and version**:

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREESHOT, COPY AND PASTE THE TEXT
```

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
