### ISSUE TITLE
v6.3.2 throws cannot format xxxx

### ISSUE THREAD

**Issue by Marckon** [prettier/prettier-vscode#1888]
### Summary

I update vscode yesterday and found I got latest version of prettier too, `v6.3.2`. Whatever file I was trying to format it throws `cannot format xxx` error and I can see no output. Plus, I cannot see the status bar of prettier in this version.I reversed to `v6.3.1` and it works fine.

### Github Repository to Reproduce Issue

undefined

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**Prettier Extension Version**:

**OS and version**:

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREESHOT, COPY AND PASTE THE TEXT
```

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
