### ISSUE TITLE
printWidth doesn't work with string interpolation

### ISSUE THREAD

**Issue by elladan06** [prettier/prettier-vscode#1896]
### Summary

The option printWidth doesn't work with string interpolation.

### My settings

```
{
  "singleQuote": true,
  "jsxSingleQuote": true,
  "trailingComma": "all",
  "printWidth": 80,
  "overrides": [
    {
      "files": "*.ts",
      "options": {
        "singleQuote": true,
        "prettier.printWidth": 80
      }
    }
  ]
}
```

### Expected result

The line should be formatted like this
```
this.logger.debug(
  `[${params.gib}]. Reason summary status ---> total duration : ${
    statusSummary.totalDuration
  } seconds. total occurrences ${statusSummary.totalOccurrences}.`,
);
```
Another dev use WebStorm and the line is formatted like my example by prettier.

### Actual result

It's formatted like this
```
this.logger.debug(
  `[${params.gib}]. Reason summary status ---> total duration : ${statusSummary.totalDuration} seconds. total occurrences ${statusSummary.totalOccurrences}.`,
);
```
The line is 159 column width in my file but I ask for 80 column width in my setting.

**VS Code Version**: 1.55.1

**Prettier Extension Version**: 1.18.2

**OS and version**: Windows 10

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
