### ISSUE TITLE
Prettier ESLint should be invoked for TypeScript files

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-vscode#190]
ESLint supports TypeScript files through [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser).

However, when `eslintIntegration` is enabled, this extension will silently skip prettier-eslint for TypeScript files: https://github.com/prettier/prettier-vscode/blob/7431dd3dc8c0e324be98378efcd1a90ce4f547fa/src/PrettierEditProvider.ts#L118

Are you happy for me to raise a PR that changes this, so TypeScript files do run through prettier-eslint?

**Comment by CiGit** [comment]
I'm somewhat embarrassed with that. I would highly prefer to use tslint with TS files.
What happens if you have a project with eslint for your JS and tslint for your TS ?

Relevant  #188

**Comment by OliverJAsh** [comment]
As far as I'm aware this project doesn't support tslint.

To give you some context, we are incrementally migrating a JS codebase to TS. We don't want to complicate the migration by also switching linter. ESLint works fine for TS files.

**Comment by CiGit** [comment]
> As far as I'm aware this project doesn't support tslint.

You are right, but it could: prettier/prettier-eslint#92

I can give you another context.
We are migrating a flow codebase to typescript. We have flow parser for eslint.

**Comment by ericwooley** [comment]
So, i'm a little confused. Can we add tslint integration?

Or have it run tslint --fix after?

**Comment by OliverJAsh** [comment]
I think we need to support users who use both ESLint and tslint with their `.ts` files. How exactly tslint integration should work is probably best discussed in the separate issue #92.

**Comment by OliverJAsh** [comment]
Any updates on this? My team is having to manually apply this patch on every update.

**Comment by jasperjn** [comment]
`prettier-eslint` supports ts files with `typescript-eslint-parser` since v7.1.0.
