### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nushankodikara** [prettier/prettier-vscode#1900]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `6.3.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Nusha\AppData\Local\Temp\esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by aravindvnair99** [comment]
@nushankodikara You didn't attach your file.

Same issue here and here's my file: [esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/6312625/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)
