### ISSUE TITLE
"arrowParens:avoid" not working if .editorconfig file present

### ISSUE THREAD

**Issue by satche** [prettier/prettier-vscode#1906]
### Summary
The proprety `prettier.arrowParens: avoid` is not working if there is a .editorconfig file in the project wich apply rules on js files

### Steps To Reproduce:
1.  Create project (with all extension disable)
2. Install/enable prettier extension with `arrowParens` proprety to `avoid`
3. Create `.editorconfig` and add any rule which concern js file

### Expected result
`let hello = foo => bar`

### Actual result
`let hello = (foo) => bar`

When formatting, parantheses are added. This behaviour does not happen if the rule in `.editorconfig` don't target a js file

### Additional information
What I understand from the output log, Prettier detect the `.editorconfig` and decide to not use the VScode plugin settings. According to prettier docs, "Prettier will parse it (.editorconfig file) and convert its properties to the corresponding Prettier configuration"

**VS Code Version**:
1.55.2

**Prettier Extension Version**:
6.3.2

**OS and version**:
macOS Big Sur – 11.2.3

## Prettier Log Output

```
["INFO" - 4:22:54 PM] Formatting /Users/.../.../test/index.js
["INFO" - 4:22:54 PM] Using ignore file (if present) at /Users/.../.../test/.prettierignore
["INFO" - 4:22:54 PM] Using bundled version of prettier.
["INFO" - 4:22:54 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 4:22:54 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 4:22:54 PM] Prettier Options:
{
  "filepath": "/Users/.../.../test/index.js",
  "parser": "babel",
  "useTabs": true
}
["INFO" - 4:22:54 PM] Formatting completed in 15.227832ms.
```

**Comment by ntotten** [comment]
Editorconfig doesn't support prettier specific settings. It only supports some basic options for tabs, etc. See https://editorconfig.org

**Comment by satche** [comment]
Thank you for your answer, @ntotten !

As I understood the part of the documentation that I quoted, prettier is supposed to merge/override its rules with the ones specified in editorconfig, and keep its "none basic" ones (like `arrowParens`).

Which surprise me is that it's not keeping the `arrowParens` rule; so I guess it just ignores the prettier configuration and let editorconfig do the job ?

Is that correct or did I misunderstood something ? If so, is this the expected behaviour ?

**Comment by ntotten** [comment]
If ANY config is present (i.e. editorconfig) then VS Code settings are not used. Vs Code settings are ONLY a fallback when no other config is available. 

Does that make sense? Maybe I'm not understanding the issue.
