### ISSUE TITLE
Prettier global package not working

### ISSUE THREAD

**Issue by aravindvnair99** [prettier/prettier-vscode#1907]
I installed the extension and installed `prettier` globally.

```cmd
>where prettier
C:\Program Files\nodejs\prettier
C:\Program Files\nodejs\prettier.cmd
```

But VS Code says when adding the first one as `prettier` path:

```
["ERROR" - 10:55:53 pm] Error loading node module 'C:\Program Files\nodejs\prettier'
["ERROR" - 10:55:53 pm] missing ) after argument list
C:\Users\username\AppData\Roaming\nvm\v14.16.0\prettier:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

And for 2nd path, it says:

```
["ERROR" - 10:55:44 pm] Error loading node module 'C:\Program Files\nodejs\prettier.cmd'
["ERROR" - 10:55:44 pm] Invalid or unexpected token
C:\Users\username\AppData\Roaming\nvm\v14.16.0\prettier.cmd:1
(function (exports, require, module, __filename, __dirname) { @ECHO off
                                                              ^

SyntaxError: Invalid or unexpected token
```

OS: Windows 10 20H2 (19042.928)
VS Code: 1.55.2 system setup
prettier global version: 2.2.1
prettier-vscode version: 6.3.2

**Comment by ntotten** [comment]
You need to set module path, not ClI path. See: https://github.com/prettier/prettier-vscode#prettierprettierpath

**Comment by aravindvnair99** [comment]
> You need to set module path, not ClI path. See: https://github.com/prettier/prettier-vscode#prettierprettierpath

Thanks @ntotten, for pointing that out! I had misread. I changed to `C:\Program Files\nodejs\node_modules\prettier` and it works now.
