### ISSUE TITLE
Ternaries forced onto single line?

### ISSUE THREAD

**Issue by mrweiner** [prettier/prettier-vscode#1908]
I've found a few ternary tickets related to code style, but I don't know if this quite falls under that. If I try to write a ternary that breaks across multiple lines, it is getting reformatted onto a single line. So this

```
const var = conditional
  ? 'opt1'
  : 'opt2'
```
is getting forced onto a single line
```
const var = conditional ? 'opt1' : 'opt2'
```
Is this normal/intended behavior? It feels like a bug, but maybe I'm just unfamiliar with the tool.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by mrweiner** [comment]
Sorry about that. Thanks!
