### ISSUE TITLE
Format Document cmd missing

### ISSUE THREAD

**Issue by Maxhodges** [prettier/prettier-vscode#192]
I installed Prettier but there is no `>Format Document` command on OSX. 

![image](https://user-images.githubusercontent.com/957271/29002318-6e09af40-7ada-11e7-821a-d463ef8c4ae2.png)

**Comment by RobinMalfait** [comment]
It works using the default built in formatter. I just commented on the other issue #51

**Comment by CiGit** [comment]
I can't really tell from your screenshot but is your active file one supported by prettier? It looks like text.

**Comment by Maxhodges** [comment]
that was it. sorry I'm new to VS code. 
The interactive playground doesn't show the Format Document command in the command panel, but oddly you can use the shift+option+F command in their code blocks

![image](https://user-images.githubusercontent.com/957271/29005729-7bd58d1e-7b1c-11e7-8456-f3296e0c413d.png)
