### ISSUE TITLE
Do not add space inside empty curly braces

### ISSUE THREAD

**Issue by CharlyPoppins** [prettier/prettier-vscode#1920]
### Summary

❌ When formatting with the VSCode extension : Formatter add space inside empty curl braces, I don't found how to disable this feature.

✅ When formatting with the CLI : Formatter DO NOT add space inside empty curl braces.

### Steps To Reproduce:

This is sample before format.
```
modal.result.then(
  () => {
    console.log('OK')
  },
  () => {},
)
```

### Expected result

No changes.

### Actual result

Formatter add a space inside the empty curly braces
```
modal.result.then(
  () => {
    console.log('OK')
  },
  () => { },
)
```

### Additional information

**VS Code Version**: 1.55.2

**Prettier Extension Version**: v6.3.2

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by CharlyPoppins** [comment]
Hello, I was thinking that the proper behaviour was to NOT add space inside empty curl braces.

So Prettier CLI applies the correct behaviour.

Can you confirm or inform @ntotten ?

**Comment by ntotten** [comment]
Apologies, I misunderstood the issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Could you provide a sample Github repo that I can use to duplicate this issue? For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).

**Comment by CharlyPoppins** [comment]
Hello, sorry for late response.
Actually the problem was a conflict with another formatter, even with this config :
````
"editor.defaultFormatter": "esbenp.prettier-vscode"
````
I had to force the formatter for typescript too.
````
"[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
  ````
