### ISSUE TITLE
Command 'Format Document With...' resulted in an error (command 'npm.packageManager' not found)

### ISSUE THREAD

**Issue by khanakia** [prettier/prettier-vscode#1921]
### Summary
It does works first them when i reinstall the extension. But when i reload the VS CODE it stops working again.

### Github Repository to Reproduce Issue
Just use any Javascript File

### Steps To Reproduce:

1.  CMD + SHIFT + P
2.  Format Document With
3. Prettier Code Formatter

### Expected result
It should format the code

### Actual result

It's giving error `Command 'Format Document With...' resulted in an error (command 'npm.packageManager' not found)`

### Additional information

_Feel free to attach a screenshot_.
<img width="1079" alt="Screenshot 2021-04-27 at 9 12 11 PM" src="https://user-images.githubusercontent.com/2174170/116271019-3ec90e80-a79d-11eb-8c28-8db46f3062d9.png">

**VS Code Version**: 1.55.2

**Prettier Extension Version**: 6.3.2

**OS and version**:  OSX Catalina 10.15.6 (19G73

## Prettier Log Output

```
["INFO" - 9:06:10 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 9:06:10 PM] Extension Version: 6.3.2.
["INFO" - 9:06:12 PM] Formatting /Volumes/D/www/php/wordpress/wp-content/plugins/analyzify/assets/analyzify-frontend.js
["INFO" - 9:06:12 PM] Using ignore file (if present) at /Volumes/D/www/php/wordpress/.prettierignore
["INFO" - 9:09:33 PM] Formatting /Volumes/D/www/php/wordpress/wp-content/plugins/analyzify/assets/analyzify-frontend.js
["INFO" - 9:09:33 PM] Using ignore file (if present) at /Volumes/D/www/php/wordpress/.prettierignore

```

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).

**Comment by khanakia** [comment]
@ntotten check this repo https://github.com/khanakia/prettier_issue

**Comment by khanakia** [comment]
@ntotten I think i found the issue 👍  when i have this config is set to true `"prettier.resolveGlobalModules": true` then it gives the above mentioned error.

**Comment by ntotten** [comment]
Thanks for the added info. I'll check this ASAP and get a fix out. Hopefully in the next few days.

**Comment by gebeer** [comment]
I am having the same issue on Arch Linux. Node installed with nvm. Integrated terminal shows correct node and nvm versions, so vscode seems to be aware of them. 
Added this to .bash_profile
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```
and this to settings.json: 
```
"terminal.integrated.shellArgs.linux": ["-l"]
```
Still no luck.
Also having ```"prettier.resolveGlobalModules": true``` in my settings

**Comment by asheroto** [comment]
> @ntotten I think i found the issue 👍 when i have this config is set to true `"prettier.resolveGlobalModules": true` then it gives the above mentioned error.
> 
> So please enable that setting and then test it also i am attaching the vscode **settings.json** file [settings.json](https://github.com/prettier/prettier-vscode/files/6388813/settings.txt)

This resolved it for me, thanks.

**Comment by luboshanus** [comment]
happened today, `julia 1.8.5`

```
Command 'Format Document With...' resulted in an error

Failed to format document: ErrorException("Error while PARSING formatted text:\n\n1   using LinearAlgebra\n2 .....
```
