### ISSUE TITLE
html doesn't render correctly

### ISSUE THREAD

**Issue by j0k4rX** [prettier/prettier-vscode#1925]
i used prettier on vscode (in windows)
& after i made prettier my default formatter, the html codes were formatted incorrectly

the html feature isn't great though default vscode formatter for html is better.
i hope you all fix this soon

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by j0k4rX** [comment]
try it in vscode.. html doesn't render correctly

**Comment by ntotten** [comment]
Ok, but I still don't have any useful info to solve this. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
