### ISSUE TITLE
Not running when saving a diffs view

### ISSUE THREAD

**Issue by SteveALee** [prettier/prettier-vscode#193]
Having set up prettier to run on save I find if I edit the right hand file in a diffs view and save it then code's formating take effect, not prettier.

**Comment by CiGit** [comment]
Can't reproduce this. Prettier does it's job in my case. This is weird as we replace VSCode's formatter for language we support.
Can you share your settings? 
Enabled extensions? 
File type?

**Comment by SteveALee** [comment]
Would you believe that hard as I try I cannot now get it to happen!? I'll put it down to one of those things.

Sorry for the noise. :(
