### ISSUE TITLE
Status menu quick disable

### ISSUE THREAD

**Issue by SaltySousChef** [prettier/prettier-vscode#1939]
Often I quickly need to edit a compiled JS file that has no defining file name like .min or .map which results in prettier going nuts trying to solve the problem of making it beautiful. I think it could be nice if there was a tab in the quick menu on the bottom right to quickly disable and reenable without going in to plugins. 

Many thanks to you all for building and maintaining this plugin!

**Comment by ntotten** [comment]
Is this because you have format on save enabled? What about using the command "Save (Without Formatting)" which is built-in to VS Code?

**Comment by hosekhoshtaghaza** [comment]
I was unaware of this command, thanks! I will use that on singular files, however when using find and replace multiple it still tries to format all unless you disable before hand. I get that this could easily be worked around but I still think it would be a nice feature to quick toggle the formatter on and off without having to go in to the settings.

**Comment by ntotten** [comment]
Makes sense. There is related discussion in #1824.

**Comment by ntotten** [comment]
Closing in favor of #1854
