### ISSUE TITLE
Do not take over my focus when syntax error being detected

### ISSUE THREAD

**Issue by be5invis** [prettier/prettier-vscode#194]
That popup blocks me from editing.

**Comment by CiGit** [comment]
I agree with that.
It happens on the first error.
Panel opens, and is focused.
We should remove that focus.
cc @RobinMalfait

**Comment by RobinMalfait** [comment]
I'll take a look at this later today/this weekend.

**Comment by RobinMalfait** [comment]
Fixed in #196
