### ISSUE TITLE
getFileInfo is not a function

### ISSUE THREAD

**Issue by iTrustGuid** [prettier/prettier-vscode#1952]
![image](https://user-images.githubusercontent.com/10825268/118138864-6248b600-b439-11eb-9404-b28682216584.png)

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
