### ISSUE TITLE
`prettier.prettierPath` not working outside the project folder

### ISSUE THREAD

**Issue by b5414** [prettier/prettier-vscode#1953]
### Summary

`prettier.prettierPath` not working outside the project folder

### Github Repository to Reproduce Issue

```javascript
const sleep=(ms)       =>new Promise((r)=>setTimeout(r,ms));
```

### Steps To Reproduce:

1. Clone and build the prettier (with some changes, you can use mine(windows only))
1. You should have this extension in vscode
1. In option `prettier.prettierPath` enter `<...>\dist` from step one
1. `Open project folder` in vscode
1. Hit the format (any) file, _you will see the modified prettier (thats cool, but)_
1. If you move same file on your desktop, then drop it back into the vscode and hit format again, then you will get the result of formatting with the default prettier (thats the issue)

### Expected result

Both formatting through a modified prettier

### Actual result

Modified prettier works only inside the project folder. Outside the project folder - working the default prettier, which comes with this extension.

### Additional information

https://imgur.com/a/7Dmu6uW

**VS Code Version**: latest

**Prettier Extension Version**: latest

**OS and version**: win10 lastest

## Prettier Log Output

```
["INFO" - 11:45:25] Formatting f:\user\desktop\basic_script.js
["INFO" - 11:45:25] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 11:45:25] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 11:45:25] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": false,
  "endOfLine": "crlf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": true,
  "jsxSingleQuote": true,
  "printWidth": 200,
  "proseWrap": "never",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 4,
  "trailingComma": "all",
  "useTabs": true,
  "vueIndentScriptAndStyle": true,
  "filepath": "f:\\user\\desktop\\basic_script.js",
  "parser": "babel"
}
["INFO" - 11:45:25] Formatting completed in 34.0485ms.

```

**Comment by ntotten** [comment]
What is the `<...>\dist` path pointing to? I doubt this is correct as the path should be the node module root path like `<...>/node_modules/prettier/`.

**Comment by b5414** [comment]
> What is the `<...>\dist` path pointing to?

@ntotten to the modified version, from the step 1 (cloned repo)

When I change this setting, the extension should only work with the prettier that is specified there, i.e. it shouldn't take into consider other prettiers and the node_modules folder at all

**Comment by ntotten** [comment]
I think you need to remove  "dist" from the path. The path needs to be to where the package.json is.

**Comment by b5414** [comment]
@ntotten you do not seem to understand

I want my modified prettier to always work for me, and never the default one.

And now even if I specified [ "src prettier": `< MY prettier path to builded dist folder with package.json >` !important; ] (by `prettier.prettierPath`), and when I format a file !!!outside the project folder!!! then SOME-WHY it take the standard in the folder with the extension 🙃

**Comment by knownasilya** [comment]
I'm seeing similar issues, but the extension doesn't pickup the one in my workspace at all. I have two folders in my workspace and each has prettier installed. If I run prettier with `yarn prettier --write <path>` it formats as expected, but if I use vscode save I get formatting from an older version.

**Comment by ntotten** [comment]
I'm happy to take a PR on this, but probably not something I will do myself.

**Comment by ntotten** [comment]
Closing as I haven't seen any interest in anyone opening a PR
