### ISSUE TITLE
Can't use linux prettierPath in WSL

### ISSUE THREAD

**Issue by Maxim-Mazurok** [prettier/prettier-vscode#1955]
### Summary

I'm using this extension inside VSCode connected to WSL2 Ubuntu on my Windows PC.
When I set `prettier.prettierPath` to the path inside of my WSL2 Ubuntu (`/home/maxim/bla-bla/node_modules/.bin/prettier`)- it doesn't work:
```
["ERROR" - 1:40:46 PM] `prettierPath` option does not reference a valid instance of Prettier. Please ensure you are passing a path to the prettier module, not the binary. Falling back to bundled version of prettier.
["ERROR" - 1:40:46 PM] The Prettier extension is blocked from execution in this project.
```
I have to set it to Windows path (`\\wsl$\Ubuntu\home\maxim\bla-bla\node_modules\.bin`) only then it works. So, I assume that it runs prettier under my Windows environment and not inside the remote WSL environment, not what I want.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1. Create a project in WSL2 (`~/prj`)
1. Install prettier as local dependency of the project:
	```
   	cd ~/prj
	npm init
	npm i --save prettier
	```
1. Add config `~/prj/.vscode/settings.json`:
  	```json
	{
	  "prettier.configPath": ".prettierrc",
	  "prettier.prettierPath": "~/prj/node_modules/.bin/prettier",
	  "prettier.requireConfig": true
	}	```
1. Try to format something using prettier (might have to reload window, might have to allow using module)
1. Observe the following log:
	```
	["INFO" - 1:48:28 PM] Extension Name: esbenp.prettier-vscode.
	["INFO" - 1:48:28 PM] Extension Version: 6.4.0.
	["ERROR" - 1:48:28 PM] `prettierPath` option does not reference a valid instance of Prettier. Please ensure you are passing a path to the prettier module, not the binary. Falling back to bundled version of prettier.
	["ERROR" - 1:48:28 PM] The Prettier extension is blocked from execution in this project.
	```

### Expected result

I expect prettier to work fine with the Linux path because I expect it to run inside of the Linux WSL environment, not in the Windows environment.

### Actual result

Error:
```
["INFO" - 1:48:28 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 1:48:28 PM] Extension Version: 6.4.0.
["ERROR" - 1:48:28 PM] `prettierPath` option does not reference a valid instance of Prettier. Please ensure you are passing a path to the prettier module, not the binary. Falling back to bundled version of prettier.
["ERROR" - 1:48:28 PM] The Prettier extension is blocked from execution in this project.
```

### Additional information
![image](https://user-images.githubusercontent.com/7756211/118430190-e12e3f00-b716-11eb-983f-9e3d7c25fe31.png)

**VS Code Version**:
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0

**Prettier Extension Version**:
v6.4.0

**OS and version**:
OS: Windows_NT x64 10.0.19042

## Prettier Log Output

```
["INFO" - 1:48:28 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 1:48:28 PM] Extension Version: 6.4.0.
["ERROR" - 1:48:28 PM] `prettierPath` option does not reference a valid instance of Prettier. Please ensure you are passing a path to the prettier module, not the binary. Falling back to bundled version of prettier.
["ERROR" - 1:48:28 PM] The Prettier extension is blocked from execution in this project.
```

**Comment by ntotten** [comment]
Per the error you are setting the path to the cli path, not the node module path.

**Comment by Maxim-Mazurok** [comment]
Oh wow, I don't know how I missed that part of the error, sorry to bother you!
