### ISSUE TITLE
Possible mistake in behavior of "prettier.requireConfig"

### ISSUE THREAD

**Issue by Avivhdr** [prettier/prettier-vscode#1979]
From the README file:
![image](https://user-images.githubusercontent.com/23265867/120012090-56372980-bfdf-11eb-9ca4-710fa01bf851.png)

The extension is enabled.
I don't have a `.prettierrc` file.
I do have an `.editorconfig` file.

My `settings.json`:
![image](https://user-images.githubusercontent.com/23265867/120012205-7ff05080-bfdf-11eb-9093-29d6901bd915.png)

When I format a document I expect that prettier not to work (due to the settings).
But when I right-click and format the document, the document is formatted and in the `Prettier` terminal I receive this message:
![image](https://user-images.githubusercontent.com/23265867/120061867-760e3200-c05f-11eb-8cfd-67b7d6c15276.png)

While the docs mention that using `prettier.requireConfig` will enable prettier only if a prettier config file is present, the real behavior  (and as seen in the terminal message is that `prettier` is being used if a prettier config **or an editorconfig** files are present.

I'm working on several projects that some have prettier and some not.
I want to use this property (`prettier.requireConfig`) to enable prettier conditionally **only** if a .prettierrc is present

**Comment by ntotten** [comment]
Any allowed config is considered valid so we count editorconfig. However if you disable the setting `prettier.useEditorConfig` the the editorconfig won't be used.

**Comment by Avivhdr** [comment]
So by setting `prettier.useEditorConfig: false`, prettier will format the file solely based on the `.editorconfig` file and not based on the default prettier configuration?

Would you agree that the docs would be more accurate if they were written this way:
`Requires a prettier configuration (or a .editorcongif) file to format files.`

**Comment by ntotten** [comment]
Yeah, I think the docs could be better on that. What it probably should do is check that the editorconfig has formatting related config. It probably doesn't make sense to run prettier if an editorconfig file exists, but doesn't contain any settings prettier uses.

**Comment by Coteh** [comment]
Just ran into this issue while taking a look at the [mithril](https://github.com/MithrilJS/mithril.js) project. They have an [.editorconfig](https://github.com/MithrilJS/mithril.js/blob/48e7fd17117501a673a8e2d86e2782bbc65a063b/.editorconfig) file but do not appear to use prettier.

It would be nice if the docs clarified that `.editorconfig` is considered a prettier configuration file by this extension, and to only auto-format on prettier config files specifically, you need to set `prettier.useEditorConfig` to false.

**Comment by ntotten** [comment]
Resolved using 5624041037fcf9c8c4612796dc4c083f0159b521

**Comment by Avivhdr** [comment]
Hi @ntotten,
Thank for the fix 🤠

Just for clarification, now, it doesn't look for `.editorconfig` at all, if the `prettier.useEditorConfig` is set to true, right?
I don't see in the PR that you check is the `.editorconfig` contains formatting rules.

btw, I think it is more intuitive like this (without checking the content of the `.editorconfig` file)

**Comment by ntotten** [comment]
Now requireConfig ONLY looks for a prettier config file and does not take into account editorconfig when determining if prettier should be enabled for a repo/folder. The editorconfig config values will be used on formatting if the editorconfig setting is true.
