### ISSUE TITLE
Treat `.blade.php` files as `.html` files

### ISSUE THREAD

**Issue by jeroenvanrensen** [prettier/prettier-vscode#1996]
## Is your feature request related to a problem? Please describe.

Yes. I have a `.blade.php` file (Laravel Blade) and I want it to be formatted with Prettier's HTML formatted. I configured file associations in the VsCode config, but that does not work.

```json
"files.associations": {
    "*.blade.php": "html"
}
```

## Describe the solution you'd like

I would like to have an option to treat any file extension as HTML files.

Or I would like it if the plugin looks at the configured language in VsCode (with file associations).

## Describe alternatives you've considered

Switching to other formatters, but I really like Prettier.

**Note**: I don't use any js configuration, I just installed the plugin and set it as the default formatter.

**Comment by ntotten** [comment]
See the documentation for the setting `prettier.documentSelectors`.

**Comment by jeroenvanrensen** [comment]
Thanks!
