### ISSUE TITLE
How to config prettier to using global node module

### ISSUE THREAD

**Issue by nguyennb9** [prettier/prettier-vscode#200]
I need to use the same version with my team (`0.1.0`) but can't find any place to configure it. Beside of that, is it possible to downgrade to version `0.1.0`?

**Comment by RobinMalfait** [comment]
Install that version as a Dev dependency and we will use that package instead.

**Comment by CiGit** [comment]
Which 0.1.0?
Prettier has no 0.1.0 version `0.0.10 -> 0.11.0`
and our 0.1.0 doesn't load local prettier. It's packed with prettier@0.0.3 :scream:

**Comment by nguyennb9** [comment]
@CiGit seem that I confuse between `prettier` and `prettier-vscode` version, I get it from here https://marketplace.visualstudio.com/items/esbenp.prettier-vscode/changelog.
Anyway, I have installed `prettier-vscode` extension and it using `prettier` somewhere else, not in my global node_module (module install with -g option) and I want to config that.

**Comment by CiGit** [comment]
We don't load your global modules. To use a specific version @RobinMalfait 's answer is how to do it 
> Install that version as a Dev dependency and we will use that package instead.

**Comment by RobinMalfait** [comment]
If you have a `prettier` installed yourself either *locally* or *globally* (I'm not sure about this one) we will use that one. If you **don't** have anything installed, we use the `prettier` that's bundled with this `prettier-vscode` extension.

**Comment by CiGit** [comment]
We don't use the global one.

**Comment by RobinMalfait** [comment]
I was not sure, edited my comment ^^

**Comment by nguyennb9** [comment]
I got the idea, thank you guys
