### ISSUE TITLE
Bump Prettier Version From 2.3.0 To 2.3.1 For Supporting Typescript 4.3.2

### ISSUE THREAD

**Issue by mahdi-farnia** [prettier/prettier-vscode#2004]
Prettier Extension For VSCode Does Not Support New Typescript Syntax (v4.3)
- override modifier in classes
- get, set for type members
- static indexed signatures

**Comment by quasarea** [comment]
There are also fixes for yaml formatting https://github.com/prettier/prettier/issues/10822

**Comment by ntotten** [comment]
Released in 7.0.0
