### ISSUE TITLE
add .mongodb formatting

### ISSUE THREAD

**Issue by brauliodiez** [prettier/prettier-vscode#2006]
**Description**
I have started working with mongoDB Plugin, it generates JavaScript files saved with the extension _.mongodb_ so I don't get automatic prettier formatting (for complex queries is a pain in the neck not getting autoformatting).

This seemed to be solved in this issue:
https://github.com/prettier/prettier/issues/6769

And merged here

https://github.com/prettier/prettier/pull/6848/files

But now it seems is not working, maybe the plugin has got some update? (e.g. the file extensión has changed to _.mongodb_).

**Possible solution**
Adding support would be great, a more generic solution could be to add a setting in the Prettier configuration allowing to add custom file extensions (e.g. https://www.reddit.com/r/vscode/comments/ixsxkd/formatter_for_mongodb_queries/).

**Alternatives I have considered**
I have tried renamed the file to JS then the Mongo plugin does not show the play button (run query).

I have tried to change the language to JS then the Mongo plugin does not show the play button (run query).

**Additional context**

**Comment by ntotten** [comment]
For this to work you still need an extension that registers the language `mongo` for the file `.mongodb` otherwise you can use this config: https://github.com/prettier/prettier-vscode#prettierdocumentselectors
