### ISSUE TITLE
[Question] Update to 1.6.0

### ISSUE THREAD

**Issue by chemitaxis** [prettier/prettier-vscode#201]
https://github.com/prettier/prettier/releases/tag/1.6.0

Do I need to do something for updating to last version? 

Thanks!

**Comment by RobinMalfait** [comment]
Yep, just wait ^^

unless you have prettier locally installed, than you have to update the dependency.
There is also a PR open #167 which will soon be merged and a new version will be published soon.

**Comment by chemitaxis** [comment]
Thanks!! :) Close!
