### ISSUE TITLE
prettier doesn't format any files, when vscode installed by .rpm/yum 

### ISSUE THREAD

**Issue by and-bulk** [prettier/prettier-vscode#2015]
![image](https://user-images.githubusercontent.com/79831859/122837661-84b9d300-d305-11eb-9c49-228cb27eb280.png)

gets error when try to format any js/ts/json file in [latest version vscode](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions)

![image](https://user-images.githubusercontent.com/79831859/122838233-acf60180-d306-11eb-9f6b-4123a2352dca.png)

i think that's bug is from
`sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc`
`sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'`

other extensions for vscode works fine, so hardly a problem in the vscode

but how can i fix that?
also when i install vscode by .deb package all works fine

**Comment by michaeltroya** [comment]
Looks like there is a bug with version 7.0.0 the fix for me was downgrading my extension to 6.4.0. 

You can downgrade by going to the Prettier extension and clicking the dropdown next to uninstall.

**Comment by Rechdan** [comment]
Here `7.0.0` is buggy too!

I'm using VSC inside my local VM through SSH.

**Comment by ntotten** [comment]
Changes from 7.0.0 were reverted and a new version 7.1.0 was published.

**Comment by and-bulk** [comment]
> Changes from 7.0.0 were reverted and a new version 7.1.0 was published.

thanks, but i get same error

![image](https://user-images.githubusercontent.com/79831859/122842122-c0f13180-d30d-11eb-99a0-c4d08e1677f0.png)
