### ISSUE TITLE
Version 7.1.0 (also) seems broken

### ISSUE THREAD

**Issue by ewh** [prettier/prettier-vscode#2016]
I'm seeing the same sort of error as 7.0.0:

```
[2021-06-21 19:52:04.838] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-21 19:52:04.838] [exthost] [error] Error: Cannot find module 'prettier'
Require stack:
- /home/ewh/.vscode/extensions/esbenp.prettier-vscode-7.1.0/dist/extension.js
```

(Downgrading back to version 6.4.0 works.)

**Comment by ntotten** [comment]
Yeah, it turns out its not something with the changes. Its something with the build process or that changed in VS Code. I'm contacting Microsoft to try to get them to revert as I can't produce a working build anymore.

**Comment by ewh** [comment]
If anyone else stumbles on this issue, here are the [instructions for downgrading back to 6.4.0](https://github.com/prettier/prettier-vscode/issues/2013#issuecomment-865381924). (It's not directly helpful, but I'm just posting this because I didn't know how to downgrade VSC extensions before today.)

**Comment by ahuggins** [comment]
Encountered this too. In VSCode I downgraded to 6.4.0 and it started working again

**Comment by ntotten** [comment]
Should be fixed now. It looks like it was an issue with `vsce` which is the tool that bundles the extension. I downgraded to an older version and rebuilt. 7.1.1 seems to be working. Let me know.

**Comment by martywallace** [comment]
7.1.1 is working correctly for me 👍

**Comment by rmzNadir** [comment]
It seems to work again with the newest (7.1.1) version
