### ISSUE TITLE
How do I set different tab size for css and js files?

### ISSUE THREAD

**Issue by arshdkhn1** [prettier/prettier-vscode#203]
I want one tab equals to 2spaces in js files but for css files I want 1tab equal to 4spaces.

**Comment by CiGit** [comment]
create a `.prettierrc` file with 
```json
{
    "tabWidth": 2,
    "overrides": [
        {
            "files": "*.css",
            "options": {
                "tabWidth": 4
            }
        }
    ]
}
```

**Comment by arshdkhn1** [comment]
@CiGit Is there anyway to create global rc file instead of .rc fie in each project

**Comment by CiGit** [comment]
Sort of
Create it at `/.prettierrc`.
keep in mind it will read the first encountered .prettierrc upwards
Or if you keep all your projects in `/Users/me/Projects` create `/Users/me/Projects/.prettierrc`

**Comment by arshdkhn1** [comment]
Ok, that works. thanks @CiGit !
