### ISSUE TITLE
Format on save stopped working (Prettier)

### ISSUE THREAD

**Issue by Kizmar** [prettier/prettier-vscode#2033]
Issue Type: <b>Bug</b>

I've done quite a bit of troubleshooting on this. Saw some people have issues with prettier when using settings sync. Turned that off. Completely removed the extension and reinstalled. No luck.

When I set Prettier as the default formatter and turn "format on save" on, I see a "Extension 'Prettier - Code Formatter' cannot format '...file path'". In the developer tools, I see an error: "Activating extension 'esbenp.prettier-vscode' filed. Cannot find module 'prettier'". Then it lists the file path where it's looking for "extension.js". That file does exist at the path it listed. So I'm not sure what to do here.

For the record; I tried searching for similar issues and didn't find specifically what I'm running in to with this.

Extension version: 8.0.0
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.10GB free)|
|Process Argv|--crash-reporter-id 55902eed-5576-46ee-b343-6ba59e3b08e0|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by zachbharris** [comment]
I'm currently having the same issue as well. Was working fine last week, but after VS Code update it gives the same error that @Kizmar is seeing. Have verified that default formatter is Prettier.

**Comment by andrevenancio** [comment]
Same! Driving me crazy. On Mac VSCode on version 1.57.1

**Comment by kevin-lindsay-1** [comment]
Please refer to https://github.com/prettier/prettier-vscode/issues/2029

**Comment by ntotten** [comment]
#2029

**Comment by Kizmar** [comment]
Side note: I did try to downgrade to both 7.1.1 and (after reading #2029) 6.4.0, but now it just doesn't format anything on save. No errors, no formatting.
