### ISSUE TITLE
Prettier >v7.1.1 "Extension 'Prettier - Code Formatter' cannot format 'nuxt.config.js'"

### ISSUE THREAD

**Issue by Eckhardt-D** [prettier/prettier-vscode#2034]
### Summary

*VSCode v1.57.1 and Prettier >V7.1.1*  Prettier Formatter does not appear in right bottom of window. No output logs available. No changes were made to config files. When saving a file Prettier message appears on bottom bar of window *Extension 'Prettier - Code Formatter' cannot format 'nuxt.config.js*. This issue is subject to all files, not only nuxt.config.js. Workspace trust was allowed.

OS - Microsoft Windows 10 Pro 64-bit

### Github Repository to Reproduce Issue

```js
 () => void
```

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  Install Prettier@latest Extension on latest VScode version.
2.  Open empty directory.
3. Create:
`index.js`
```js
module.exports = { "test":
'test'}
```
4. Edit VScode settings
```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
}
```
5. Create `.prettierrc`
```json
{
    "trailingComma": "es5",
    "tabWidth": 4,
    "semi": false,
    "singleQuote": true
}
```

### Expected result

The Expected result is that the extension formats the file:

```js
module.exports = { test: 'test' }
```

### Actual result

Prettier does not format the file, syntax stays the same and the message `Extension 'Prettier - Code Formatter' cannot format 'index.js'`

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.57.1

**Prettier Extension Version**: 8.0.0, 8.0.1

**OS and version**: Microsoft Windows 10 Pro | 64 Bit | Version 2004

## Prettier Log Output

```
N/A No logs were output and prettier does not exist in the toolbar.
```

**Comment by louisgv** [comment]
Also seeing the same issue. When I do CTRL + SHIFT + P and tell prettier to "format with", I got a list of eslint:

![image](https://user-images.githubusercontent.com/6723574/123099012-c2028b80-d3ff-11eb-92b5-f284eee29575.png)

Picking any of the ESlint correctly formatted my code.

**Comment by raffizulvian** [comment]
Try to look at #2033

**Comment by ntotten** [comment]
Upgrade to version 8. Version had a build issue.
