### ISSUE TITLE
Void HTML elements are formatted as self-closing tags

### ISSUE THREAD

**Issue by jost-s** [prettier/prettier-vscode#2035]
### Summary

In a Vue project with single file components, void HTML elements like `<img>`, `<hr>` or `<br>` are formatted to self closing tags `<img />`, `<hr />` and `<br />` respectively. Running the ES linter from the command line `npm run lint` formats the elements correctly, so I assume it's an issue with the prettier extension,

### Github Repository to Reproduce Issue

https://github.com/jost-s/vscode-prettier

### Steps To Reproduce:

1.  run `npm run lint` and verify the `img` tag in `HelloWorld.vue` is not self-closing
2.  open `HelloWorld.vue` in the editor and format it using option-shift-f

### Expected result

The `img` tag remains as it is.

### Actual result

The `img` tag is converted to self-closing.

### Additional information

![image](https://user-images.githubusercontent.com/28270981/123123728-58a66b00-d447-11eb-929b-c90ce3e895b5.png)

![image](https://user-images.githubusercontent.com/28270981/123123784-66f48700-d447-11eb-89dd-146beaa619c5.png)

**VS Code Version**:
1.57.1

**Prettier Extension Version**:
8.0.1

**OS and version**:
macOS 11.4

## Prettier Log Output

```
["INFO" - 5:22:03 PM] Formatting /Users/jost/Desktop/dev/nodejs/prettier/src/components/HelloWorld.vue
["INFO" - 5:22:03 PM] Using config file at '/Users/jost/Desktop/dev/nodejs/prettier/.prettierrc'
["INFO" - 5:22:03 PM] Using ignore file (if present) at /Users/jost/Desktop/dev/nodejs/prettier/.prettierignore
["INFO" - 5:22:03 PM] File Info:
{
  "ignored": false,
  "inferredParser": "vue"
}
["INFO" - 5:22:03 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:22:03 PM] Prettier Options:
{
  "filepath": "/Users/jost/Desktop/dev/nodejs/prettier/src/components/HelloWorld.vue",
  "parser": "vue",
  "semi": true,
  "arrowParens": "always",
  "endOfLine": "auto",
  "singleQuote": true,
  "trailingComma": "none",
  "jsxBracketSameLine": true,
  "tabWidth": 2,
  "printWidth": 100
}
["INFO" - 5:22:03 PM] Formatting completed in 16.09184ms.
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
