### ISSUE TITLE
Prettier hangs onSave forever

### ISSUE THREAD

**Issue by mah51** [prettier/prettier-vscode#2040]
### Summary

Occasionally, whilst saving a file prettier will hang as mentioned in #1880. A small message comes up like so 
![image](https://user-images.githubusercontent.com/47287285/123519493-6f48fe00-d6a3-11eb-94e3-86edc71b8c34.png)
and the code is shown as an error and remains unformatted:

![image](https://user-images.githubusercontent.com/47287285/123519501-7c65ed00-d6a3-11eb-80bb-f6a45e053f53.png)

I am not sure if this is exclusive to typescript, but I have been working on typescript projects recently and it has been happening alot.  Not exclusive to single project and does not happen at regular intervals, can happen at different points and I can't seem to see a correlation

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

https://github.com/michael-hall.me - Any of my projects have this problem and it doesn't happen immediatly it seems to happen randomly on save

### Expected result

Formatting of code.

### Actual result
No formatting, small error line, vscode message saying prettier is formatting in the corner

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
1.57.1
![image](https://user-images.githubusercontent.com/47287285/123519562-f5fddb00-d6a3-11eb-8dda-96dbd2721db1.png)

**Prettier Extension Version**:
Happens with versions 8.01 & 6.4.0
**OS and version**:
Windows 10 Pro 20H2
## Prettier Log Output

```
["INFO" - 17:20:24] Using ignore file (if present) at d:\Everything\Files\Code\Web\personal-site\.prettierignore
["INFO" - 17:20:24] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 17:20:24] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 17:20:24] Prettier Options:
{
  "filepath": "d:\\Everything\\Files\\Code\\Web\\personal-site\\src\\components\\MDXComponents\\MDXComponents.tsx",
  "parser": "typescript",
  "printWidth": 100,
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "jsxSingleQuote": true,
  "trailingComma": "es5",
  "arrowParens": "avoid",
  "htmlWhitespaceSensitivity": "css"
}
["INFO" - 17:20:24] Formatting completed in 65.0004ms.
["INFO" - 17:20:35] Formatting d:\Everything\Files\Code\Web\personal-site\src\components\MDXComponents\MDXComponents.tsx
["INFO" - 17:20:35] Using config file at 'd:\Everything\Files\Code\Web\personal-site\.prettierrc.js'
["INFO" - 17:20:35] Using ignore file (if present) at d:\Everything\Files\Code\Web\personal-site\.prettierignore
["INFO" - 17:20:35] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 17:20:35] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 17:20:35] Prettier Options:
{
  "filepath": "d:\\Everything\\Files\\Code\\Web\\personal-site\\src\\components\\MDXComponents\\MDXComponents.tsx",
  "parser": "typescript",
  "printWidth": 100,
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "jsxSingleQuote": true,
  "trailingComma": "es5",
  "arrowParens": "avoid",
  "htmlWhitespaceSensitivity": "css"
}
["INFO" - 17:20:35] Formatting completed in 66.4619ms.
```

**Comment by mah51** [comment]
Hi, I think I have narrowed this down to a problem with the interaction between this plugin and [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag) It seems to cause the prettier extension to hang, not sure why.

**Comment by ntotten** [comment]
Sounds like this is another extension. Closing.
