### ISSUE TITLE
`Format Selection` formats the entire file

### ISSUE THREAD

**Issue by wenfangdu** [prettier/prettier-vscode#2041]
### Summary

`Format Selection` formats the entire file instead of the selected code.

### Github Repository to Reproduce Issue

https://github.com/wenfangdu/prettier-format-selection-repro

### Steps To Reproduce:

![2021-06-27 08_17_47](https://user-images.githubusercontent.com/28700378/123529155-3c911b00-d720-11eb-989f-c7c1aff3d953.gif)

### Expected result

Formats the first line.

### Actual result

All lines got formatted.

**VS Code Version**: v1.57.1

**Prettier Extension Version**: v8.0.1

**OS and version**: Windows 10

## Prettier Log Output

```
["INFO"] Extension Name: esbenp.prettier-vscode.
["INFO"] Extension Version: 8.0.1.
["INFO"] Formatting d:\prettier-format-selection-repro\test.js
["INFO"] Using ignore file (if present) at d:\prettier-format-selection-repro\.prettierignore
["INFO"] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO"] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO"] Prettier Options:
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine": "auto",
  "htmlWhitespaceSensitivity": "ignore",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "useTabs": false,
  "vueIndentScriptAndStyle": true,
  "filepath": "d:\\prettier-format-selection-repro\\test.js",
  "parser": "babel"
}
["INFO"] Formatting completed in 58.0383ms.
```

**Comment by ntotten** [comment]
Range formatting doesn't work very well in prettier. There are many issues open with the core library: https://github.com/prettier/prettier/issues?q=is%3Aissue+is%3Aopen+range+
