### ISSUE TITLE
Add possibility to change Prettier execution from node_modules on all workspaces

### ISSUE THREAD

**Issue by d4ve02** [prettier/prettier-vscode#2046]
**Is your feature request related to a problem? Please describe.**
After cloning a git repo and opening it, I got the following prompt:

> The Prettier extension will use 'node_modules/prettier/index.js' for validation, which is installed locally in folder 'folder name'. Do you allow the execution of the Prettier version including all plugins and configuration files it will load on your behalf?
Press 'Allow Everywhere' to remember the choice for all workspaces.

After pressing "Allow Everywhere", I can't find the specific setting to turn this feature off for all workspaces.

**Describe the solution you'd like**
If this feature is not present yet, maybe add a way to turn this off for all workspaces since it's a security risk.

**Describe alternatives you've considered**
I've seen there's a
> Prettier: With Node Modules

setting but I'm not quite sure this is what the prompt was referring to and whether this applies to all workspaces.

**Comment by ntotten** [comment]
The implementation of the trusted workspace isn't an extension feature, we just consume the API. You'd need to open an issue on VSCode for this feature.

See: https://code.visualstudio.com/docs/editor/workspace-trust
