### ISSUE TITLE
Does not work well with handlebars (.hbs) files

### ISSUE THREAD

**Issue by psbanka** [prettier/prettier-vscode#205]
When saving a .hbs file in VSCode with the prettier-vscode extension, it mangles the file. Can we get an option to avoid these files?

![Saving .hbs](https://cl.ly/1I2l021o201n/download/Screen%20Recording%202017-08-29%20at%2002.03%20PM.gif)

**Comment by RobinMalfait** [comment]
I know it is closed already. But for people searching for this problem:

At the time of this issue, prettier VScode doesn't format HBS files. This is probably the default formatter or a custom formatter taking action.
