### ISSUE TITLE
Let other extensions provide plugins for Prettier

### ISSUE THREAD

**Issue by Janther** [prettier/prettier-vscode#2051]
**Is your feature request related to a problem? Please describe.**
At the moment the extension `juanblanco.solidity` uses Prettier to format `.sol` files.
It misses some of the details that `esbenp.prettier-vscode` improvements since `juanblanco.solidity` focuses in more specialised Solidity things than formatting.

**Describe the solution you'd like**
 Would it be possible for that extension to completely rely on this extension to format and just provide the plugin?
At the moment I believe `esbenp.prettier-vscode` relies only on the project's `node-modules` folder and by using an approach like this we might not even need a `node-modules` in projects that don't use node.

**Describe alternatives you've considered**
My idea would be that `juanblanco.solidity` could:
  1. clean it's formatting module
  2. require `esbenp.prettier-vscode` as an `extensionDependensy`
  3. proxy the formatting calls to `esbenp.prettier-vscode` and providing the `prettier-plugin-solidity` as the plugin to be used.

This could open the doors for other community plugin extensions most likely not related to npm to add to their prettier formatting in an easy way.
Open to other ideas here

**Comment by ntotten** [comment]
I'm not opposed to this. Feel free to propose an api and send a PR.

**Comment by juanfranblanco** [comment]
@Janther So the idea is that esbenp.prettier-vscode will start including plugins in a similar way to vscode solidity? That is a great idea, it will surely help standardizing prettier as a formatter enabling plugins on the extension, as most people don't use npm to install prettier, specially the ones that don't use node or javascript  :). I guess the possibility of sharing formatting across languages, would be rather interesting.

Regarding the installation of esbenp.prettier-vscode as a dependency I have some worries about that specially for users that would not want the extension as they may not want to use prettier, other marketplaces, like the eclipse one, or just simple dependency restriction. 

But proxying is a great idea, and obviously I can see  esbenp.prettier-vscode growing this way with more options, so what it could be done (trying to achieve the best from both worlds) is detect the installation or have it as one of the configurations, and then do the proxying there if detected or configured. If it is not installed, configured, it can revert to the current formatter or none, depending on the users needs.

**Comment by ntotten** [comment]
Feel free to propose a pull request.
