### ISSUE TITLE
I cannot put the start and closing tags on new lines

### ISSUE THREAD

**Issue by vrindavan** [prettier/prettier-vscode#2076]
Prettier is always putting them in one line which I do not want. I posted the question on [SO](https://stackoverflow.com/questions/68302553/how-do-i-make-the-start-and-end-tags-appear-in-a-new-line-everytime-instead-of-b)  also but no luck yet.

**What I am getting:** 

![image](https://user-images.githubusercontent.com/50140643/125159639-47bf5e80-e196-11eb-926a-aa2814afca8b.png)

**What I want:** 
![image](https://user-images.githubusercontent.com/50140643/125159645-53ab2080-e196-11eb-9337-c2425160af4c.png)

**Comment by ntotten** [comment]
Prettier has a few options because of history. But we won’t add more of them. For more details see: https://prettier.io/docs/en/option-philosophy.html
