### ISSUE TITLE
python sys.path.append()

### ISSUE THREAD

**Issue by vivekvardhanadepu** [prettier/prettier-vscode#2082]
### Summary
libs which I want to import after inserting/appending the path are pushed to the top 
### Github Repository to Reproduce Issue
https://github.com/vivekvardhanadepu/apertium-lexical-training/blob/main/tests/check_config_test.py

### Steps To Reproduce:

1.  add below code to python file
```
sys.path.append('../')
from check_config import check_config
```
2. format it using prettier and save 

### Expected result

It should stay as it is because check_config is in path `../`

### Actual result

The code turned to
```
from check_config import check_config
sys.path.append('../')
```
causing import problems
### Additional information

**VS Code Version**: 1.58

**Prettier Extension Version**: 8.0.1

**OS and version**: 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-1kali1

## Prettier Log Output

```
["INFO" - 9:09:57 am] Extension Name: esbenp.prettier-vscode.
["INFO" - 9:09:57 am] Extension Version: 8.0.1.
```

**Comment by ntotten** [comment]
This seems to be an issue with the python prettier plug-in.

**Comment by vivekvardhanadepu** [comment]
@ntotten Any idea where to report for the same?
