### ISSUE TITLE
prettier always uses default settings. 

### ISSUE THREAD

**Issue by Lotram** [prettier/prettier-vscode#209]
Hi guys, 

I've recently switched from Sublime Text to VS Code for JS programming. The first thing I did was of course to install prettier and eslint. My problem is I tried to overwrite settings (such as printWidth and singleQuote), but when I save (I also enabled formatOnSave), it always uses the default settings. 
I also checked that I did not have any .prettierrc or .prettier.config.js file, but it's not the case. Do you know what could be the problem ? Like I said, I'm new to VS Code, so maybe I missed something.

Thanks, 

Laurent

**Comment by pirkkahuhtala** [comment]
Yep I have the same issue.

**Comment by kumarharsh** [comment]
Yup, it seems like the plugin is not reading any of the config from my workspace settings or .prettierrc

**Comment by CiGit** [comment]
For all of you:
- Does calling `format Document` action do what you expect?
- What if you disable other extensions?
- Please share your setup.

**Comment by pirkkahuhtala** [comment]
Yep. Had the fork version also. Maybe this can be closed? Sorry for the hassle.

**Comment by CiGit** [comment]
Does the extension you had point to this repository?
I'd like to avoid issues from others :smiley:

**Comment by kumarharsh** [comment]
For me, it was a more subtle issue - eslint has a rule to always expect a comma in an object, but prettier removes a comma from the last item of an object **if the last item happens to be a destructuring assignment**. I mistakenly assumed prettier was not working, although it's an eslint's issue and I think it's fixed in more recent versions of eslint.

```js
const {
  a,
  b,
  ...otherProps  // <- prettier removes the comma here, which is valid, but eslint says it's invalid.
} = this.props;
