### ISSUE TITLE
When saving a simple HTML file a semicolon is added to the end of the HTML code

### ISSUE THREAD

**Issue by grahamfowles** [prettier/prettier-vscode#2090]
When developing with Angular, sometimes the template files get a semicolon added to the end.  Usually this happens for simple HTML files that have no angular markup.  I have confirmed that disabling the prettier extension solves the issue.

I'm using v8.0.1 but this has been happening for some time

I have also tried disabling all other extensions and this issue still persists

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
