### ISSUE TITLE
prettier formats .json5 file as javascript

### ISSUE THREAD

**Issue by jefshe** [prettier/prettier-vscode#2099]
### Summary

When creating a json5 file, `prettier` makes my json invalid because it formats the data as javascript

### Github Repository to Reproduce Issue

None required it happens anywhere.

### Steps To Reproduce:

1.  Create a new file called "test.json5"
1.  add  `{ "valid": "json" }` to the file
1. save the file and prettier will break it

### Expected result

prettier doesn't break the file
### Actual result

prettier breaks the file
### Additional information

<img width="226" alt="Screen Shot 2021-07-23 at 1 27 39 pm" src="https://user-images.githubusercontent.com/30220932/126734376-966a9bc8-eb0d-4e89-8aef-264739c7409c.png">

**VS Code Version**:
1.58.2
**Prettier Extension Version**:
v8.0.1
**OS and version**:
Mac OS 11.4 Big Sur
## Prettier Log Output

```
["INFO" - 1:30:50 PM] Formatting /Users/jeff/repos/api/.github/legacy/test.json5
["INFO" - 1:30:50 PM] Using config file at '/Users/jeff/repos/api/.prettierrc'
["INFO" - 1:30:50 PM] Using ignore file (if present) at /Users/jeff/repos/api/.prettierignore
["INFO" - 1:30:50 PM] File Info:
{
  "ignored": false,
  "inferredParser": "json5"
}
["INFO" - 1:30:50 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 1:30:50 PM] Prettier Options:
{
  "filepath": "/Users/jeff/repos/api/.github/legacy/test.json5",
  "parser": "json5",
  "printWidth": 150,
  "trailingComma": "all",
  "singleQuote": false,
  "arrowParens": "always"
}
["INFO" - 1:30:50 PM] Formatting completed in 5.380375ms.```

**Comment by ntotten** [comment]
`{ valid: "json" }` is valid JSON5. If you want normal style json don't add the `.json5` extension. See: https://json5.org/

**Comment by jefshe** [comment]
sorry should've RTFM'd
