### ISSUE TITLE
first attribute on the same line tag opener

### ISSUE THREAD

**Issue by Baira** [prettier/prettier-vscode#210]
Hi,
Thanks for the awesome work. Great plugin.

Here is what prettier does : 
```jsx 
<input
    type="text"
    className="new-todo"
    placeholder="What needs to be done?"
    onKeyUp={this.handleChange}
/>
```
Here is what I want : 
```jsx
<input type="text"
    className="new-todo"
    placeholder="What needs to be done?"
    onKeyUp={this.handleChange}
/>
```
How to achieve this with prettier settings ? Thanks in advance.

**Comment by CiGit** [comment]
Hey,

This is prettier (an _opinionated_ formatter) deciding. For those discussions, these should go in prettier's repository. I can't remember having seen such issue, but I'm pretty sure this won't change.

**Comment by CiGit** [comment]
Closing as this discussion doesn't belong here.
