### ISSUE TITLE
Existing formatter config is (sometimes) overridden/ignored with default settings

### ISSUE THREAD

**Issue by Relequestual** [prettier/prettier-vscode#2101]
**Is your feature request related to a problem? Please describe.**

It's frustrating when prettier runs when I don't expect or want it to run.
I ran into a problem where Prettier was changing my double quotes to single quotes, and I didn't expect prettier to be running.

I cloned a project that had a `.editorconfig` file, but does not use prettier.
I have the "require config" option enabled.
I do not have prettier installed globally in my cli environment.
Having a `.editorconfig` seems enough to enable formatting (as per documented).
I still want eslint formatting, and have "format on save" turned on.

**Describe the solution you'd like**

I would like to see Prettier not running by default when I have a `.editorconfig` file and Prettier is not a development dependency. (This could be changeable by config if required).

**Describe alternatives you've considered**

1. I have added a .prettierignore file, but that looks strange when the project doesn't use Prettier.
It's probably bad practice to add config files to prevent things which happen only when a specific plugin is installed.

2. A config option to NOT use the bundled version of Prettier. I only want to run Prettier when it is known and expected by the project.
Unless this was enabled by default, it would not solve the issue.

I would like anyone cloning this repo to be able to work without running into the same potential problem, **by default**.

**Additional context**

I wondered if I had Prettier installed globally, but I did not.
It seems like falling back to the bundled version is something people might expect, but when cloning existing projects, this may have conflicting interactions with project defined format configurations and expectaions.

Having a default that causes problems in some situations seems more detrimental than having a default that means no formatting takes place unless it is expected.

I'm not the only person to[ run into this issue](https://github.com/prettier/prettier-vscode/issues/1979#issuecomment-864471060), but I couldn't see it or a suggestion to improve it filed.

**Comment by ntotten** [comment]
Resolved with 5624041037fcf9c8c4612796dc4c083f0159b521

**Comment by Relequestual** [comment]
🙇‍♂️Thank you for your speedy resolve. Heres to auto releases!
