### ISSUE TITLE
Possiblity to turn off prettification of specific types

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier-vscode#212]
e.g. I wanted to turn off prettification of JSON, but it doesn't work.

At first I thought that maybe `"prettier.jsonEnable": []` will do. It makes prettier not work in JSON, but it's only because it starts to treat file as JavaScript.

**Comment by azz** [comment]
See #208 for  `.prettierignore` support.

**Comment by medikoo** [comment]
@azz still it'll be better to turn it off globally within this plugin. So it automatically affects all projects, and only when working from within VSCode.

e.g. I personally want to have it off, due to lack of support for `.editorconfig` (prefer no prettier for JSON than creating additional `.prettierrc` file in every project (on my computer 200+ of them))

**Comment by CiGit** [comment]
I dont' understand fully you initial post.
`"prettier.jsonEnable": []` disables json parser support. If you put `json` in any other array, it will try to format with the given parser your json files.

You can put `.prettierrc` at the root. It walks the file system tree up to find it.

**Comment by medikoo** [comment]
> I dont' understand fully you initial post. "prettier.jsonEnable": [] disables json parser support

I observed situation when it tried to apply JS parser in that case, but now I don't see that. I probably had not all settings reloaded.

Indeed it seems that `"prettier.jsonEnable": []` does the job, I'm closing this then
