### ISSUE TITLE
Prettier does not pick up .editorconfig

### ISSUE THREAD

**Issue by JustinGrote** [prettier/prettier-vscode#2130]
Issue Type: <b>Bug</b>

I have a .prettierrc.yml confgured as well as a .editorconfig where I have my tab config, and the tab config info is not being loaded unless I put it directly into .prettierrc.yml

![image](https://user-images.githubusercontent.com/15258962/128623199-580557f1-fdf8-4234-af5c-5a0b8b79fe3a.png)

```json
["INFO" - 11:28:17 PM] Prettier Options:
{
  "filepath": "c:\\Users\\JGrote\\Projects\\vscode-adapter\\src\\extension.ts",
  "parser": "typescript",
  "singleQuote": true,
  "trailingComma": "none",
  "arrowParens": "avoid",
  "semi": false
}
```

Extension version: 8.1.0
VS Code version: Code - Insiders 1.60.0-insider (49af1cbe00271ac2ea36cfc5f7352fe31a7b0094, 2021-08-06T06:41:50.275Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (5.13GB free)|
|Process Argv|--crash-reporter-id 4453efaa-0821-4555-88e2-3de8bad9109e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30348854
dockerwalkthrucf:30348714

```

</details>

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
