### ISSUE TITLE
More clear doc needed

### ISSUE THREAD

**Issue by kid1412621** [prettier/prettier-vscode#2136]
**Is your feature request related to a problem? Please describe.**
Is the setting, eslintIntegration, removed or deprecated or not? I cannot find the relative info I need.
And according to the [changelog](https://github.com/prettier/prettier-vscode/blob/ffb9d524793458364d6ecb3c8bee65421452c1da/CHANGELOG.md#0160) , it says, Use `prettier-eslint` under the hood. So do I need to install `prettier-eslint` locally or not?

The Prettier [official site](https://prettier.io/docs/en/integrating-with-linters.html) says there's 2 ways to integrate with Linters. But I'm not sure how this works with this vscode extension.

btw, I've read [this disscuse](https://github.com/prettier/prettier-vscode/issues/958).

**Describe the solution you'd like**
More clear doc needed.

**Describe alternatives you've considered**
maybe some demo? fine, just more clear doc

**Additional context**

**Comment by ntotten** [comment]
Happy to accept a pull request.
