### ISSUE TITLE
Doesn't work when VSCode is set to autosave

### ISSUE THREAD

**Issue by pmbanugo** [prettier/prettier-vscode#214]
I noticed when I enable vs code autosave feature, prettier doesn't work. Do I need extra configuration?

**Comment by CiGit** [comment]
Do you mean formatOnSave?

**Comment by pmbanugo** [comment]
yes formatOnSave

**Comment by CiGit** [comment]
Does it work if you call `Format Document` ?
Does it take time? ~ 1sec

**Comment by leogeng** [comment]
I have the same problem, and it works when calling `format Document`

**Comment by pmbanugo** [comment]
@CiGit If I do format_document makes it work. but then I don't want the extra keys. What I've done now is to change from afterDelay to onFocusChange for my `files.autosave` setting, and it works.

**Comment by CiGit** [comment]
Documentation for formatOnSave:
>// Format a file on save. A formatter must be available, the file must not be auto-saved, and editor must not be shutting down.
  "editor.formatOnSave": false,

**The file must not be auto-saved** for the important part here.
