### ISSUE TITLE
Single Line Comments

### ISSUE THREAD

**Issue by Stamimail** [prettier/prettier-vscode#2146]
https://www.w3schools.com/js/js_comments.asp
I want to use single line comments at the end of each line to explain the code,
but sometimes after saving, prettier change the location of the comment from the end of the line and move it down to a new line.
It's unwanted behaviour.

Is there an option to fix this behaviour?

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
