### ISSUE TITLE
Format the selected text not work ?

### ISSUE THREAD

**Issue by jerryc127** [prettier/prettier-vscode#2153]
### Summary

use prettier to format the selected text will formal all the text instead of the selected text

i try to use another fomat extension called beautify, it work and format the selected text

so it is bug of prettier ?

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**Prettier Extension Version**:
v8.1.0

**OS and version**:
windows 10 21h1

## Prettier Log Output

```
["INFO" - 下午4:11:06] Formatting c:\Users\Jerry\Documents\Github\butterfly-dev\themes\butterfly\source\js\main.js
["INFO" - 下午4:11:06] Using ignore file (if present) at c:\Users\Jerry\Documents\Github\butterfly-dev\.prettierignore
["INFO" - 下午4:11:06] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 下午4:11:06] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 下午4:11:06] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "c:\\Users\\Jerry\\Documents\\Github\\butterfly-dev\\themes\\butterfly\\source\\js\\main.js",
  "parser": "babel",
  "rangeEnd": 20545,
  "rangeStart": 20521
}
["INFO" - 下午4:11:07] Formatting completed in 221.1292ms.
```

![動畫1](https://user-images.githubusercontent.com/16351105/131211460-1d6a0074-af75-4186-955c-5f07aee8beba.gif)

**Comment by ntotten** [comment]
See: https://github.com/prettier/prettier-vscode/issues/2041#issuecomment-886810289
