### ISSUE TITLE
The `prettier.proseWrap` in the settings.json file is not applied

### ISSUE THREAD

**Issue by LitoMore** [prettier/prettier-vscode#2155]
### Summary

I added the `"prettier.proseWrap": "always"` to `settings.json`, but I can't see this configuration applied in the log.

I haven't tested the behavior on other options. Only know it has bug from the `proseWrap` option.

I don't have any other configuration files in my project. Only `settings.json`.

### Steps To Reproduce:

1. Setup the `settings.json` in `.vscode` with this content below:
  ```json
  {
    "prettier.enable": true,
    "prettier.proseWrap": "always",
    "editor.defaultFormatter": null,
    "[markdown]": {
      "editor.formatOnSave": true,
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
  }
  ```
2. Try to format a markdown file
3. Check the log

### Expected result

```
{
  "filepath": "/Users/litomore/Git/computer-science-notes/the-swift-programming-language/README.md",
  "parser": "markdown",
  "proseWrap": "always",
  "endOfLine": "lf"
}
```

### Actual result

```
{
  "filepath": "/Users/litomore/Git/computer-science-notes/the-swift-programming-language/README.md",
  "parser": "markdown",
  "endOfLine": "lf"
}
```

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: Visual Studio Code - Insiders 1.60.0-insider

**Prettier Extension Version**: v8.1.0

**OS and version**: macOS 12.0 Beta (21A5304g)

## Prettier Log Output

```
["INFO" - 11:05:51 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 11:05:51 PM] Prettier Options:
{
  "filepath": "/Users/litomore/Git/computer-science-notes/the-swift-programming-language/README.md",
  "parser": "markdown",
  "endOfLine": "lf"
}
["INFO" - 11:05:51 PM] Formatting completed in 116.77575ms.
```

**Comment by ntotten** [comment]
The extension seems to have detected a `.prettierrc` or `.editorconfig` setting:

```
["INFO" - 11:05:51 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
```

See: https://github.com/prettier/prettier-vscode#configuration

**Comment by colinsmetz** [comment]
So if I understand, if a `.editorconfig` file is present, the VS Code settings are completely ignored? I was hoping that the precedence rules explained in the doc would apply _per parameter_.

This is an issue for me as I have a `.editorconfig` with the `max_line_length` setting, that I would like to use. However, this setting has no effect unless I pass the `prose-wrap always` option to `prettier` (when I run it with the CLI). And, as far as I know, there is no way to configure `proseWrap` from the `.editorconfig`.

What can I do? (if I should open a new issue, please tell me)
