### ISSUE TITLE
prettier-ignore comments not working for inline scripts in VSCode

### ISSUE THREAD

**Issue by MadeByMike** [prettier/prettier-vscode#216]
Prettier has the ability to ignore blocks of code.
https://github.com/prettier/prettier#excluding-code-from-formatting

If you have one of these comments in an inline scripts such as:

```
<script>
  // prettier-ignore
  {{ test: "test" }}
</script>
```
It will not ignore the block. 

As far as I am aware prettier does not support inline script tags like this, so I assume `prettier-vscode` is instructing prettier to format these sections?

**Comment by CiGit** [comment]
We don't handle inline script. Isn't that an other formatter you have? default one?

**Comment by MadeByMike** [comment]
@CiGit Add the above to a file and format it with prettier-vscode, you will see that the script is formatted resulting in something like: 
```
<script>
// prettier-ignore
{
  { 
    test: "test" 
  }
}
</script>
```
It's not respecting the `// prettier-ignore` but if you prettier from the terminal it does ignore the block. I'm trying to pinpoint where the issue lies is this a vs-code, prettier-vscode or an issue with prettier?

It should work according to:
https://github.com/prettier/prettier#excluding-code-from-formatting

**Comment by CiGit** [comment]
What's this file type? html?
What are your settings?

I tried with a html file. It's not the default formatter as it doesn't expand collapsed block statements.
By default prettier doesn't run on html.
Have you tried with prettier-vscode disabled?

**Comment by MadeByMike** [comment]
Thanks! I thought prettier replaced the default document formatting, I didn't realise they worked together. I think this is a VS code thing.
