### ISSUE TITLE
Run prettier version defined in package.json

### ISSUE THREAD

**Issue by jurosh** [prettier/prettier-vscode#217]
In new Prettier 1.6 there are some bugs and we cannot use it right now. Need to stick to 1.5 version, but VS Code plugin just shipped new version with it, so is not using prettier defined in package.json.

Would be nice if developers can specify version of prettier which to use either way:
- use prettier from node_modules
- define version it in some setting (less prefered)

Without this functionality formatting would be out of sync with CLI formatter, and it would not be possible to use prettier cross IDE/CLI.

**Comment by azz** [comment]
This extension should use prettier from node_modules before it falls back to a bundled version. Is there anything in the output panel under the "Prettier" entry?

Out of curiosity, what are the bugs that are preventing you from using 1.6?

**Comment by jurosh** [comment]
Ah, issue was that I started VS Code with cleaned dependencies and then installed node_modules... after restarting VSCode it's working again with proper version.

Because of formatting of JSX, it's more messy after latest changes. Eg. https://github.com/prettier/prettier/issues/2751
