### ISSUE TITLE
Don't accidentally disallow use of `prettierx` because of a strict version check

### ISSUE THREAD

**Issue by shaylew** [prettier/prettier-vscode#2175]
**Is your feature request related to a problem? Please describe.**
Prettierx is a drop-in replacement for prettier that supports a few more options -- in particular, compatibility with `standard`. Because it's essentially API compatible, you can just change the prettier path in prettier-vscode's options to point to `node_modules/prettierx` and everything works...

... Almost. Alas, prettierx uses a different versioning scheme, and prettier-vscode refuses to load it because it thinks it's too old. If you circumvent the version check by manually editing prettierx's `package.json`'s version field, it does in fact work just fine.

**Describe the solution you'd like**
If the prettier path points to `prettierx`, don't throw it out for not matching a known prettier version. I'd be fine with "assume the user knows what they're doing and ignore the version", but in fact `prettierx` has done the legwork here and already includes a `prettier-version` field in their package.json indicating which version of prettier they're equivalent to. All you'd have to do to add support is fall back to this field rather than failing hard.

**Describe alternatives you've considered**
- [aMarCruz/prettier](https://github.com/aMarCruz/prettier) is a compatibility shim that re-exports prettierx under the prettier name with a different version number. This works... except it's pinned to an old version of prettierx, and (as far as active maintenance goes) by far the weakest link in the tool chain here, so having to depend on it to make your editor keep working seems like a bad idea.
- Just change the version in prettierx's package.json 🙃. Obviously a bad idea, and an even worse idea to try to get a whole team to do it.
- Convince prettierx to change their version numbering scheme to be the same as prettier's. Worth a try, I guess, but not a reasonable thing to expect -- they can't simultaneously do semver for their own features and stay in lockstep with prettier version numbers.
- Ditch prettier-vscode and make some other tool handle format-on-save for us? Fork something? IDK.

**Comment by ntotten** [comment]
We only support prettier. Not interested in alternatives.
