### ISSUE TITLE
prettier-vscode doesn't honor root prettier version

### ISSUE THREAD

**Issue by yipei1028** [prettier/prettier-vscode#2184]
### Summary
As documentation point out: `This extension will use prettier from your project's local dependencies (recommended).`, `prettier-vscode` supposed to take local version of `prettier` as formatting standard.

I use `prettier: v.1.18.2` as dependency in my project (I don't have any prettier configuration file: `.prettierrc` or `.prettierignore`), rule "trailingComma" should be "none". However, with `prettier-vscode`  installed and execute on saving, `prettier-vscode` apply "trailingComma" to "es5" (looks like `prettier` default behavior after v2.x)

### Github Repository to Reproduce Issue

No. Same issue happens under different local project.

### Steps To Reproduce:

1.  `npm install prettier@1.18.2 -D`
2.  format with `prettier-vscode`

### Expected result

The version of `prettier `applied to `prettier-vscode` should align to the version installed as local dependency.
Not sure if there is any potential rules changed. At least, "trailingComma" should be applied `none`.

### Actual result

The version of `prettier `applied to `prettier-vscode` use its opinionated version.
Rule "trailingComma" change to `es5`.

### Additional information

**VS Code Version**:
 1.59.0

**Prettier Extension Version**:
8.1.0

**OS and version**:
macOS Mojave 10.14.6

## Prettier Log Output

```
["INFO" - 12:18:21 AM] Formatting /myProject/packages/line/lib/line.js
["INFO" - 12:18:21 AM] Using ignore file (if present) at /myProject/.prettierignore
["INFO" - 12:18:21 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 12:18:21 AM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 12:18:21 AM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/myProject/packages/line/lib/line.js",
  "parser": "babel"
}
["INFO" - 12:18:21 AM] Formatting completed in 69.80393ms.
```

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
