### ISSUE TITLE
Helm yaml format issue on {{ and }}

### ISSUE THREAD

**Issue by allamand** [prettier/prettier-vscode#2196]
Issue Type: <b>Bug</b>

When working on Kubernetes with Helm template, we need to manipulate lots of yaml file with the syntax {{ some.paramaters }}.

The extension is now changing this to:

{ { some.parameters } } which breaks the yaml templating feature.

I need to find a way that {{ and }} are not inserted with white space

Extension version: 8.1.0
VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1048-aws
Remote OS version: Linux x64 5.4.0-1048-aws
Remote OS version: Linux x64 5.4.0-1048-aws
Remote OS version: Linux x64 5.4.0-1048-aws
Fetching remote diagnostics for 'ssh-remote+cloud9' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.97GB free)|
|Process Argv|--crash-reporter-id f9d23254-435a-439d-b105-a87d4a7e30a5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cloud9|
|OS|Linux x64 5.4.0-1048-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (32 x 3207)|
|Memory (System)|123.06GB (36.08GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cloud9|
|OS|Linux x64 5.4.0-1048-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (32 x 3207)|
|Memory (System)|123.06GB (36.08GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cloud9|
|OS|Linux x64 5.4.0-1048-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (32 x 3207)|
|Memory (System)|123.06GB (36.08GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cloud9|
|OS|Linux x64 5.4.0-1048-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (32 x 3207)|
|Memory (System)|123.06GB (36.08GB free)|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+cloud9' timed out.
</details>

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by terracota-p** [comment]
There is one already (unsolved): https://github.com/prettier/prettier/issues/6517
