### ISSUE TITLE
Code formatting anomaly using Prettier

### ISSUE THREAD

**Issue by bryanfromlv** [prettier/prettier-vscode#2198]
Issue Type: <b>Bug</b>

Not a show stopper, just curious why two chunks of the same basic code are formatted differently by Prettier. Details in screenshot.

Extension version: 8.1.0
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by bryanfromlv** [comment]
![vscode_prettier_anomoly](https://user-images.githubusercontent.com/57161175/133862349-fddcf6b0-4cec-4e96-b637-8b8e517fc6be.png)

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
