### ISSUE TITLE
Key combination not working

### ISSUE THREAD

**Issue by GantMan** [prettier/prettier-vscode#220]
When I press `command+shift+p` this pops up, instead of formatting.
![image](https://user-images.githubusercontent.com/997157/30390103-a0723afc-987a-11e7-992f-2dad4734d765.png)

**Comment by RobinMalfait** [comment]
That's expected. The popup you see is called the `Command Palette`.

When inside the command `Command Palette` you can search for `Format Document` as described in the [usage section](https://github.com/prettier/prettier-vscode#usage) in the readme file.

You can define a shortcut yourself or use the built in formatter (also default). In my case it is <kbd>shift</kbd> + <kbd>alt</kbd> + <kbd>f</kbd>.

![](http://d.rbn.nu/G17aMH.png)

**Comment by GantMan** [comment]
thanks so much!
