### ISSUE TITLE
Failed to resolve a parser, skipping file with overrides in prettierrc for erb file

### ISSUE THREAD

**Issue by joshunger** [prettier/prettier-vscode#2200]
### Summary

Prettier is not formatting .erb files and throwing an error even when I have defined an override in `.prettierrc`. Maybe this is a configuration issue on my end?

```
["WARN" - 4:05:04 AM] Parser not inferred, trying VS Code language.
["ERROR" - 4:05:04 AM] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

Even though there is an override in `.prettierrc`.

The prettier command line works.

### Github Repository to Reproduce Issue

I can provide one if the steps to reproduce do not reproduce.

### Steps To Reproduce:

1.  Install prettier.
2. Install @prettier/plugin-ruby
3. Install prettier-plugin-erb
4. Add a `.pretterrc` file

```
{
  "printWidth": 150,
  "singleQuote": true,
  "plugins": [],
  "overrides": [
    {
      "files": "*.erb",
      "options": { "parser": "erb" }
    }
  ]
}
```

Edit your settings
```
  "prettier.documentSelectors": [
    "**/*.erb"
  ]
```

4. Open .erb file in Visual Studio.
5. Format with > Prettier.

### Expected result

.erb file should be formatted.

### Actual result

Nothing happens an error is in the logs

```
["WARN" - 4:05:04 AM] Parser not inferred, trying VS Code language.
["ERROR" - 4:05:04 AM] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
```
Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:09:14.403Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Prettier Extension Version**:
```
❯ code --show-versions --list-extensions | grep prettier
esbenp.prettier-vscode@8.1.0
```

**OS and version**:
```
OS: Darwin x64 20.6.0
```

## Prettier Log Output
```
["INFO" - 4:05:04 AM] Formatting /Users/junger/drive/dev/public/test.erb
["INFO" - 4:05:04 AM] Using config file at '/Users/junger/drive/dev/public/test/.prettierrc'
["INFO" - 4:05:04 AM] Using ignore file (if present) at /Users/junger/drive/dev/public/test/.prettierignore
["INFO" - 4:05:04 AM] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 4:05:04 AM] Parser not inferred, trying VS Code language.
["ERROR" - 4:05:04 AM] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).

**Comment by joshunger** [comment]
@ntotten thanks for trying to reproduce the issue! I'll create a Github repo or close as necessary this week.
