### ISSUE TITLE
Format bug on `+=`,`-=`,`*=`,`/=` and `%=`

### ISSUE THREAD

**Issue by bolan9999** [prettier/prettier-vscode#2216]
### Summary

Format bug on `+=`,`-=`,`*=`,`/=` and `%=`

### Github Repository to Reproduce Issue

No Link.

### Steps To Reproduce:

Try to format code below with prettier:
```
a *= (b+1);
```

### Expected result

```
a *= (b + 1);
```

### Actual result

```
a *= b + 1;
```

### Additional information

**VS Code Version**:

Version: 1.60.2
Submit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T11:59:27.195Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.5.0

**Prettier Extension Version**:

Sorry, I do not know how to do it.

**OS and version**:
macOS Big Sur 11.4

## Prettier Log Output

```
["INFO" - 10:23:42 PM] Formatting completed in 0.019ms.
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
