### ISSUE TITLE
Tooltip with a version of prettier

### ISSUE THREAD

**Issue by rogovdm** [prettier/prettier-vscode#223]
By hovering in the bottom bar we can see the version of prettier being used.

![here](https://www.dropbox.com/s/2vpdfyj7itb7br5/9l92mr08.png?raw=1)

Would be nice.

**Comment by RobinMalfait** [comment]
That would be a nice improvement. Maybe we can add if we use the local prettier or the bundled prettier. Let me tackle this problem. What do you think @CiGit ?

**Comment by RobinMalfait** [comment]
I provided a PR that shows this information: 

![](http://d.rbn.nu/F50Vsv.png)

**Comment by RobinMalfait** [comment]
`Bundled with package` should be `Bundled with extension` fixing it now.
