### ISSUE TITLE
Include official prettier plugins by default

### ISSUE THREAD

**Issue by ivangretsky** [prettier/prettier-vscode#2235]
Good day! Thanks for the plugin! 

Could you please include [official plugins](https://prettier.io/docs/en/plugins.html#official-plugins) in the downloadable prettier version? I and my team are working with php with no node-based build step and it is pretty complicated to explain how to install prettier with node and configure plugins. Having them in the downloadable version would solve the problem.

**Comment by ntotten** [comment]
I don't think we'll do this. There are too many plugins. Not everyone wants them all.

**Comment by ivangretsky** [comment]
There are only 4 official ones.
