### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SamNickGammer** [prettier/prettier-vscode#2237]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `9.0.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.61.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by ntotten** [comment]
Without the clipboard data there isnt any information to solve this.
