### ISSUE TITLE
Codespaces - Use existing configuration options

### ISSUE THREAD

**Issue by robence** [prettier/prettier-vscode#2239]
**Is your feature request related to a problem? Please describe.**
There's a new version of this extension that already works inside Github Codespaces (github.dev) which is nice. I've experienced it, but saw it only formats using the default prettier options.

**Describe the solution you'd like**
I'd like to see formatting based on configuration found in root/.prettierrc[.js|.json]

**Describe alternatives you've considered**
Not sure what this section means. Current alternative is cloning Github repository and developing locally.

**Comment by marcelocra-hubla** [comment]
@ntotten

Any idea why it doesn't work in github.dev?
