### ISSUE TITLE
Doesn't run the .eslintrc rules with eslintIntegration is true

### ISSUE THREAD

**Issue by lcc19941214** [prettier/prettier-vscode#225]
I set `prettier.eslintIntegration` to `true` in my vscode and add `"react/jsx-max-props-per-line": [2, { "maximum": 1 }]` to my .eslintrc.
vscode throw error while there are multiple props in one line, however prettier can't format this.
prettier only formats multiple props when line width is longer than the line width.

![bug-report](https://user-images.githubusercontent.com/11664604/30800947-462a4662-a1a7-11e7-9f25-62c81528ec64.png)

**Comment by azz** [comment]
Prettier doesn't support eslint rules, you should turn those rules off. [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) is designed to do this for you.

**Comment by RobinMalfait** [comment]
@azz `eslintIntegration` is enabled so it should format it.

Do you have other typo's or do you see a `Prettier: ✔︎` in the bottom of your vscode?

**Comment by lcc19941214** [comment]
@azz yep, I have already enabled `eslintIntegration`, so it seems I don't need to use `eslint-config-prettier`.

**Comment by lcc19941214** [comment]
@RobinMalfait I'm sure there is no `Unexpected token` or any other typo's, and prettier run successfully with other code except multiple props in one line with jsx.

**Comment by CiGit** [comment]
`jsx-max-props-per-line` is auto-fixable since [7.1](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.1.0). Have you a recent version of this package?

**Comment by ma53** [comment]
I'm having a similar issue.  prettier-vscode does not seem to be calling eslint at all.

My relevant vscode user settings:
```
{
    "editor.formatOnSave": true,
    "prettier.eslintIntegration": true,
    "prettier.tabWidth": 4,
    "prettier.singleQuote": true
}
```

My .eslintrc.json:
```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "module"
    },
    "plugins": ["html"],
    "rules": {
        "no-const-assign": "warn",
        "no-this-before-super": "warn",
        "no-undef": "warn",
        "no-unreachable": "warn",
        "no-unused-vars": "warn",
        "constructor-super": "warn",
        "valid-typeof": "warn",
        "brace-style": ["error", "stroustrup"]
    }
}
```

Sample js code:
```
var a;
if (true) {
    a = true;
} else {
    a = false;
}
```

Running the vscode-eslint extension manually enforces the Stroustrup brace-style:
```
var a;
if (true) {
    a = true;
}
else {
    a = false;
}
```

Saving the file (thus triggering prettier) reverts to One True Brace:
```
var a;
if (true) {
    a = true;
} else {
    a = false;
}
```

**Comment by CiGit** [comment]
Is that `brace-style` fixable with your eslint version?

**Comment by ma53** [comment]
Yes.

**Comment by CiGit** [comment]
Just tried. Had to install `eslint-plugin-html` to make it work, but was working for me.

**Comment by SzHeJason** [comment]
+1 , `newline-per-chained-call` doesn't work. 
```
   "newline-per-chained-call": ["error", { ignoreChainWithDepth: 4 }]
```
```
   // before
   "ASD".split("").reverse().join("");
   
   // after
   "ASD"
     .split("")
     .reverse()
     .join("");
```

**Comment by azz** [comment]
prettier-eslint runs Prettier then ESLint. @SzHeJason  Prettier will convert your code to the `// after` block, and I don't think ESLint will move it back into one line.

**Comment by SzHeJason** [comment]
Even if `eslintIntegration` is enabled , `newline-per-chained-call`  still can't working in `prettier-eslint`,is it right?

**Comment by azz** [comment]
I'd just turn off that rule and let prettier handle it. Using that rule in conjunction with prettier will produce strange behaviours like the one you documented.

**Comment by CiGit** [comment]
[newline-per-chained-call](https://eslint.org/docs/rules/newline-per-chained-call) seems to be fixable. Maybe it can only expand. Try to run eslint --fix on your file.

**Comment by SzHeJason** [comment]
```
   // VScode setting
   "prettier.eslintIntegration": true

   // ESlint rule
   "newline-per-chained-call": ["error", { ignoreChainWithDepth: 4 }]
```

```
   // test.js
   "s".anchor().anchor().anchor().anchor();
    
   // eslint --fix test.js
   // no error

   //format document
  "s"
    .anchor()
    .anchor()
    .anchor()
    .anchor();

```

**Comment by CiGit** [comment]
I've misread the rule. Seems both (on one line and expanded) are valid with this eslint rule. This rule only forces you to expand.

Closing this as initial discussion is stalled. Open new issue for anything else. Thanks.
