### ISSUE TITLE
Change the JSX bracket-same-line option to the new bracketSameLine one

### ISSUE THREAD

**Issue by GhislainDamou** [prettier/prettier-vscode#2260]
Since a few weeks, prettier deployed an option which extends possibility to force bracket to close on the same line and not on a new line. The option is called bracketSameLine and replace jsxBracketSameLine but is not implemented yet on the vscode prettier's extension.

Do you guys think it is possible to implement this as well as it is on Prettier ?

Thanks for reading me.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by GhislainDamou** [comment]
The feature already exist in the Prettier library as you can see there : https://prettier.io/blog/2021/09/09/2.4.0.html

**Comment by ioagiannis** [comment]
It will be very useful to add "bracketSameLine" rule to Prettier-VSCode settings.

**Comment by Avishayy** [comment]
Can we please add this option? If `bracketSameLine` exists in the config file (`.prettierrc.json`) it gets ignored and you are forced to set the deprecated option.

**Comment by kskrlinnorth2** [comment]
This option still not available?

**Comment by adrianbienias** [comment]
I'm using VS Code extension, and there's `jsxBracketSameLine` option only.
That setting doesn't affect HTML files, which is what I'm hoping for.
Any ideas on how to turn this rule for HTML files using Prettier VS code extension?

**Comment by ntotten** [comment]
Version 9.7.0
