### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dungnq81** [prettier/prettier-vscode#2265]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `9.0.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\NTH\AppData\Local\Temp\esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sacummings91** [comment]
What's the reason for closing this? I'm having the same issue
