### ISSUE TITLE
Change JSX bracket-same-line option to the new bracketSameLine

### ISSUE THREAD

**Issue by GhislainDamou** [prettier/prettier-vscode#2268]
Sorry to repost but I think you guys didn't see my message after closing my last issue.

The feature already exist in the Prettier library as you can see there : https://prettier.io/blog/2021/09/09/2.4.0.html

_Originally posted by @GhislainDamou in https://github.com/prettier/prettier-vscode/issues/2260#issuecomment-958839272_

**Comment by whoisYeshua** [comment]
yeah, this will be very helpful
