### ISSUE TITLE
Extension not using correct version

### ISSUE THREAD

**Issue by iRoachie** [prettier/prettier-vscode#227]
The extension is always using the bundled version of prettier (1.7.0), even though the installed version is 1.6.1.

**Comment by CiGit** [comment]
How have you defined that ? 
We bundle 1.6.1 currently

**Comment by iRoachie** [comment]
Running prettier directly from the command line and using your extension is producing two different outputs. When I then upgraded my local prettier to 1.7, and ran from the command line it produced the same output as the extension

**Comment by CiGit** [comment]
Stalled, closing
