### ISSUE TITLE
Add trailingComma to the last var of function

### ISSUE THREAD

**Issue by nerdmax** [prettier/prettier-vscode#228]
This is my Prettier settings:
  "prettier.eslintIntegration": true,
  "prettier.trailingComma": "none",

I enable the eslintIntegration. Prettier will add the trailingComma to the last item of an object. That's fine. However, it will also add the comma to the last var of a function if the function's var that I pass in has "`" symbol

Eg1: (Shouldn't add comma to the last var)

> data = changeVar('blobsettingsfilename', packagejson.nextGenConfig.blobsettingsfilename, `${ngWeb.newWebName}.BlobSettings`, data);

Becomes:

>     data = `changeVar(`
>       'blobsettingsfilename',
>       packagejson.nextGenConfig.blobsettingsfilename,
>       `${ngWeb.newWebName}.BlobSettings`,
>       data,
>     );

Eg2: (Without "`" symbol, works fine)

> data = changeVar('stagingcompanyname', packagejson.nextGenConfig.stagingcompanyname, '', data);

Becomes:

> data

 = changeVar('stagingcompanyname', packagejson.nextGenConfig.stagingcompanyname, '', data);

**Comment by azz** [comment]
Can you reproduce this [on the playground](https://prettier.io/playground/)?

**Comment by nerdmax** [comment]
Sorry, it's due to my eslintConfig inside package.json. I didn't notice that it's there. I am so sorry about that. Thx to @azz 's fast response. Closing it
