### ISSUE TITLE
feature request: only format if prettier config is found (as in prettier-atom)

### ISSUE THREAD

**Issue by jokeyrhyme** [prettier/prettier-vscode#229]
OMG, prettier plugins are so amazing!

The Atom plugin for Prettier has this neat option:
"Only format if a Prettier config is found"
https://github.com/prettier/prettier-atom/blob/v0.40.0/src/config-schema.json#L131

It would be terrific if this plugin for VSCode had a similar feature

**Comment by CiGit** [comment]
There is a discussion on that in #199 
We should merge this together.

**Comment by jokeyrhyme** [comment]
Thanks for the link! (I did check but my search terms were different)
