### ISSUE TITLE
Support VSCode's format modifications feature

### ISSUE THREAD

**Issue by ajbrun** [prettier/prettier-vscode#2295]
Given prettier does support [range formatting](https://prettier.io/docs/en/options.html#range), can this original request be re-opened?
https://github.com/prettier/prettier-vscode/issues/1562

I know the original request was closed due to prettier having issues reported with range formatting, however:
* Have the most severe of these been solved since the original ticket was closed?
* In any case, given this is a published feature prettier supports and is non-default in vscode, can it be implemented within this extension so it can be used if enabled?

Thanks :)

**Comment by ntotten** [comment]
It's something I am willing to take a PR on, but I'm not going to do it. It would be a lot of work and prettier still doesn't support ranges super well.
