### ISSUE TITLE
Prettier forcing new lines suddenly

### ISSUE THREAD

**Issue by Jordz2203** [prettier/prettier-vscode#2298]
Hey guys, for some reason in the last 2 or so weeks Prettier has been forcing line breaks and formatting my code weirdly. For example the issue that made me report this was prettier making my code go to a new line for every HTML Tag ending, for example here I placed my text in a <strong> tag and it forced new lines. 
![image](https://user-images.githubusercontent.com/29569801/142860122-7626100c-19ba-469c-8fc7-4f088215f295.png)

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
