### ISSUE TITLE
bracketSameLine not work on v9.0.0 but v8.2.0

### ISSUE THREAD

**Issue by fyeeme** [prettier/prettier-vscode#2309]
my config is here :
```json
{
  "semi": false,
  "singleQuote": true,
  "printWidth": 100,
  "trailingComma": "none",
  "bracketSameLine": true
}
```
when using this config in vue 2 project  `bracketSameLine` not work. but when I downgrade to v8.2.0, `bracketSameLine` this works well, may something is  wrong with the lastest version.
- [x] Write a summary of your issue
- [x] Include a link to a github repo that can be used to reproduce the issue or exact reproduction steps.
- [x] Provide the expected result
- [x] Provide the actual result
- [x] Include extension, os, and vs code information
- [x] Include Prettier extension log

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
