### ISSUE TITLE
Enable Prettier only for specifics folders

### ISSUE THREAD

**Issue by CaptainYouz** [prettier/prettier-vscode#2311]
**Is your feature request related to a problem? Please describe.**
For some projects, i use prettier, for others, i don't. In my vscode, I have a folder (my `dev` folder), that contains those projects. I was wondering if there is a way to only enable prettier for specific folders, so i don't have to disable/re-enable it manually (I didn't find anything on the doc)

**Describe the solution you'd like**
A configuration option to specify some folders where prettier extension will be applied

**Comment by ntotten** [comment]
https://github.com/prettier/prettier-vscode#prettierrequireconfig-default-false
