### ISSUE TITLE
HTML markup specific tab oor printWidth width ?

### ISSUE THREAD

**Issue by j-meds** [prettier/prettier-vscode#2313]
When working on Vue files the lines of the files can get lengthy due to the formatted HTML. Vue components or html elements are bounded by attributes so their width most likely always exceeds the defaults and it makes a one line element into 4+.

**Describe the solution you'd like**
HTML specific printWidth or tabWidth.

**Describe alternatives you've considered**
Increading printWidth to around 140 or setting tabWidth to 2.

**Additional context**
I want specific prettier options on HTML and the other programming logic. Sometimes the default prettier quadruples a file line size, which then takes a while too access vue component logic.

**Comment by ntotten** [comment]
#2315
