### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ChristianH545** [prettier/prettier-vscode#2323]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `9.0.0`
- OS Version: `Linux x64 5.11.0-41-generic`
- VS Code version: `1.63.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by PabloLION** [comment]
what's exactly the error? or is this a spam?

**Comment by ntotten** [comment]
Need clipboard data
