### ISSUE TITLE
Doesn't take .prettierrc settings

### ISSUE THREAD

**Issue by guyisra** [prettier/prettier-vscode#233]
I am using latest version (0.24) on mac with latest prettier installed in the project
No matter that I put in .prettierrc or the user settings, when I do `Format Document` it doesn't take the settings into account

This is my prettierrc
{
  "printWidth": 100,
  "semi": false,
  "singleQuote": true,
}

**Comment by CiGit** [comment]
Is there a reason you closed this issue?

**Comment by guyisra** [comment]
I don't know if it was just my situation, but I had prettier-eslintintegration settings turned on, and once I removed it from the user settings prettier worked according to the .prettierrc

Is that a feature or a bug?

**Comment by azz** [comment]
I can't remember if cosmiconfig supports json5/trailing comma, I don't think it does.

**Comment by CiGit** [comment]
I don't know which one takes precedence in prettier-eslint, prettierrc or eslint, but it may collide
