### ISSUE TITLE
Prettier suddenly unable to format anything

### ISSUE THREAD

**Issue by bojidaryovchev** [prettier/prettier-vscode#2331]
![image](https://user-images.githubusercontent.com/8954749/146672494-138eaab5-f903-4487-a95e-d03a7993e206.png)

Prettier v2.5.1
TypeScript v4.5.2

Suddenly prettier cannot format anything (not even plain javascript files, I am getting that same error I have posted a picture of, but it says 'JavaScript'-files instead)

here is my VS Code settings.json

![image](https://user-images.githubusercontent.com/8954749/146672532-133b6e7f-08bf-43db-93b1-53307cc50bdc.png)

and my package.json

![image](https://user-images.githubusercontent.com/8954749/146673137-e6bd70f3-b1ad-4053-932e-40b4870b0513.png)

**Comment by bojidaryovchev** [comment]
after tried the vscode version from september the problem remains

**Comment by bojidaryovchev** [comment]
also tried disabling the built-in typescript and javascript language features, still doesnt work, I am unable to format anything

**Comment by ste163** [comment]
Getting the exact same issue on my laptop running Linux Mint 20.2. Works fine on my Mac Book Pro though...

**Comment by bojidaryovchev** [comment]
ok I managed to figure out what my problem was.. if you see my package.json you can see the prettier-plugin-typescript in there, it used to work some days ago but maybe a version has changed so now it doesn't work.. after removing it I am able to format again
