### ISSUE TITLE
Enable formatOnSave only if there is a prettierrc

### ISSUE THREAD

**Issue by ForbesLindesay** [prettier/prettier-vscode#234]
I would like to enable `formatOnSave` only for projects that have a `.prettierrc` file.  Currently, I have to keep disabling it whenever I'm editing code that belongs to someone else, so I don't end up with massive diffs.  If it only applied when there was a `.prettierrc` file, it would just automatically only be enabled for projects that use prettier.

**Comment by azz** [comment]
Merging into #199. Related: #229,  prettier/prettier#2907
