### ISSUE TITLE
The extension have a conflict with VSCode's autocomplete

### ISSUE THREAD

**Issue by igor-gorlov** [prettier/prettier-vscode#2344]
It seems like autocomplete runs and interferes with the formatting process while `Prettier` is doing its work; sometimes
this situation leads to fatal consequences. Consider the case below.

We have the following `HTML` document (looks very strange, but this is a radically simplified example):

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Prettier Formatting Test</title>
	</head>

	<body>
		<header>
			<nav>
				<ul>
					<li>
						<ul>
							<li id="contents-terminology-partitioning"><a href="#terminology-partitioning">Partitioning</a></li>
						</ul>
					</li>
				</ul>
			</nav>
		</header>
	</body>
</html>
```

Note the longest (fifteenth) line which represents an internal link entitled `Partitioning`.

OK, let's format our document with the following `.prettierrc` file:

```
{
	"printWidth": 120,
	"tabWidth": 4,
	"useTabs": true,
	"trailingComma": "none",
	"bracketSpacing": false,
	"bracketSameLine": true,
	"proseWrap": "always",
	"endOfLine": "crlf",
	"htmlWhitespaceSensitivity": "strict"
}
```

The result is:

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Prettier Formatting Test</title>
	</head>

	<body>
		<header>
			<nav>
				<ul>
					<li>
						<ul>
							<li id="contents-terminology-partitioning"
								><a href="#terminology-partitioning">Partitioning</a></li
							>
						</ul>
					</li>
				</ul>
			</nav>
		</header>
	</body>
</html>
```

The fifteenth line has been split into three smaller ones.

Later, we decide to change the formatting method by relaxing the whitespace sensitivity requirement from `strict` to
`css`. We make the appropriate modification to the config file and then reformat the current version of the document.
The result looks as follows:

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Prettier Formatting Test</title>
	</head>

	<body>
		<header>
			<nav>
				<ul>
					<li>
						<ul>
							<li id="contents-terminology-partitioning"></li>
								<a href="#terminology-partitioning">Partitioning</a>
							</li>
						</ul>
					</li>
				</ul>
			</nav>
		</header>
	</body>
</html>
```

The syntax is broken!

Look at the problematic place:

```
							<li id="contents-terminology-partitioning"></li>
								<a href="#terminology-partitioning">Partitioning</a>
							</li>
```

There is a redundant closing tag `</li>` suddenly added right after the openning one. The autocompletion `VSCode`
feature works very same when we are typing manually. Moreover, if we press `Control + Z` (undoes the last action), the
redundant tag disappears, but the formatting remains:

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Prettier Formatting Test</title>
	</head>

	<body>
		<header>
			<nav>
				<ul>
					<li>
						<ul>
							<li id="contents-terminology-partitioning">
								<a href="#terminology-partitioning">Partitioning</a>
							</li>
						</ul>
					</li>
				</ul>
			</nav>
		</header>
	</body>
</html>
```

I have experience neither with `Prettier` codebase nor with the sources of `Prettier` `VSCode` extension, but I think
the issue demonstrated above is caused by incorrect interraction between the extention and the editor.

* `VSCode` version: `1.63.2`
* `Prettier` extention version: `9.0.0`
* OS: `Windows 10 21h1`

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
