### ISSUE TITLE
Unable to install extension 'esbenp.prettier-vscode' as it is not compatible with VS Code '1.51.1'.

### ISSUE THREAD

**Issue by liute110** [prettier/prettier-vscode#2353]
### Summary

Hi: 
    I want to install prettier in vscode to help format my code. But I got follow error when installed the extension.

![image](https://user-images.githubusercontent.com/19482770/148020419-a40c4a81-4e91-49a5-8654-a9cdc7f9cc31.png)

### Expected result

Could install prettier extension in vscode(1.51.1)

### Actual result

this extension is not compatible with vscode(1.51.1)

**VS Code Version**:
1.51.1

**Prettier Extension Version**:
v9.1.0

**OS and version**:
windows10

**Comment by ntotten** [comment]
You should update to a newer version of VSCode, 1.51.1 is more than a year old. This extension only works with version 1.60.0 or newer.
