### ISSUE TITLE
broken html formatting

### ISSUE THREAD

**Issue by olhapi** [prettier/prettier-vscode#236]
Is there an option to disable formatting for html documents?

**Comment by CiGit** [comment]
Yes! `"html.format.enable": false` to disable default formatter.

**Comment by olhapi** [comment]
Seems like it is, I didn't enable html formatting by myself. I enabled format on save only and there is 

```
  // Enable/disable default HTML formatter
  "html.format.enable": true,
```

in the default vscode settings.
