### ISSUE TITLE
Ability to format selection for python

### ISSUE THREAD

**Issue by intiocean** [prettier/prettier-vscode#2360]
Would it be possible to add python to the list of languages that can format a selection (rather than only the whole file)?

Code: https://github.com/prettier/prettier-vscode/blob/v1.6.1/src/utils.ts#L42-L51
Mentioned in this issue: https://github.com/prettier/prettier-vscode/issues/134#issuecomment-416336597

At the moment, this is stopping me from using prettier on my python files.

**Comment by ntotten** [comment]
What plugin are you using? Most languages in prettier don't support range formatting.
