### ISSUE TITLE
.prettierc overrides are ignored

### ISSUE THREAD

**Issue by QuentinRoy** [prettier/prettier-vscode#237]
It seems the plugin ignores prettier's overrides options. E.g. the following `.prettierc` fails for the directory `build_tools`:

```yaml
{
  "trailingComma": "all",
  "overrides": [
    {
      "files": "build_tools/*.js",
      "options": {
        "trailingComma": "es5"
      }
    }
  ]
}
```

It works fine if I run prettier from the command line.

**Comment by CiGit** [comment]
This may need some investigations. My first though:
We are giving an absolute path to prettier. It is able to find your prettierrc file but globs don't match in that case.
I've no time right now, but I think globs should be tested against
```js
path.relative(absPathToPrettierrc, absPathToFile)
```

Any idea @azz ?

**Comment by CiGit** [comment]
Just to confirm my hypothesis, can you run with an absolute path on the command line?
`prettier absPathToYour'build_tools/file.js'`

**Comment by QuentinRoy** [comment]
It seems prettier is OK with the absolute path..

**Comment by azz** [comment]
Could it be  prettier/prettier#3005?

**Comment by QuentinRoy** [comment]
Yes, I think it is probably it.

**Comment by gyzerok** [comment]
It seems like referenced issue was solved, but the bug still exists. Any ideas?

Here is how my `.prettierrc` looks like:

```
{
  "printWidth": 90,
  "tabWidth": 2,
  "useTabs": false,
  "overrides": [
    {
      "files": ["src/**/*.ts", "src/**/*.tsx"],
      "options": {
        "jsxBracketSameLine": true,
        "bracketSpacing": true,
        "semi": true,
        "trailingComma": "all",
        "singleQuote": true,
        "parser": "typescript"
      }
    }
  ]
}
```

**Comment by jakub300** [comment]
It looks like `prettier-vscode` is resolving config for file [using bundled prettier](https://github.com/prettier/prettier-vscode/blob/cd5e2002dad801438e23f0918f22d3b058229e9b/src/PrettierEditProvider.ts#L104) and is using local prettier only for formatting so we have to wait for updated `prettier-vscode`.

**Comment by gyzerok** [comment]
It seems like https://github.com/prettier/prettier/issues/3005 got resolved in October already, so it might be a different issue then.

**Comment by gyzerok** [comment]
Ah, I see now, it's so that version should be updated here.

**Comment by CiGit** [comment]
We need to update to prettier 1.8. Ongoing in #256

**Comment by RobinMalfait** [comment]
Since this requires an update of prettier which is already happening in #256, can this issue be closed then or not yet?
