### ISSUE TITLE
Add option to only enable Prettier when a config or local install is present.

### ISSUE THREAD

**Issue by guidobouman** [prettier/prettier-vscode#238]
The linter-eslint package in Atom has a setting that allows you to disable the plugin when there's no config found. (in package.json or .eslintrc)

This would help a lot when using Prettier on only some projects. Not all projects have Prettier enabled by default. A lot of legacy open source projects use ESLint for their linting without disabling their formatting rules. To make matters worse, Prettier now conflicts with ESLint when ESLint is set up to work with the highly popular default AirBnB config.

When switching projects I now have to disable and enable Pettier by hand.

There's two ways to approach this problem:
- Add an option to disable Prettier when there's no config to be found.
- Add an option to disable Prettier when no local installed package of Prettier is present.

Either would do if you ask me.

**Comment by azz** [comment]
Merging in with https://github.com/prettier/prettier-vscode/issues/199

**Comment by guidobouman** [comment]
@azz Oops, forgot to properly search apparently. I thought I searched for exactly that title.
