### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Djamilson** [prettier/prettier-vscode#2382]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `9.1.0`
- OS Version: `Linux x64 5.13.0-27-generic`
- VS Code version: `1.63.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
