### ISSUE TITLE
Apply HTML to XML and XLF files

### ISSUE THREAD

**Issue by Caaarrrlll** [prettier/prettier-vscode#2389]
**Prettier has an XML extension but the VSCode Prettier only does JS, TS and HTML**
The formatter does not allow setting file associations per language.

**Allow formatting by file associations**
If a language is setup i.e. HTML, allow associations to be set for any file that contains that structure, like XML etc.

**Installing multiple formatters**
The only other solution is using the prettier NPM package and configuring it for the languages I use but that is not ideal or installing multiple formatters.

**Comment by ntotten** [comment]
Could be easier, but it is supported: https://github.com/prettier/prettier-vscode/wiki/Custom-File-Extension-Configuration
