### ISSUE TITLE
Default configuration change after update prettier from 1.1.0 to 1.7.1

### ISSUE THREAD

**Issue by nguyennb9** [prettier/prettier-vscode#239]
I install global `prettier` version `1.1.0` everything working well like this
![image](https://user-images.githubusercontent.com/12994001/31443122-bc48bacc-aec2-11e7-81e6-9a5f47f55d87.png)

After update to version `1.7.1`, there are a lot of line break inserted like this:
![image](https://user-images.githubusercontent.com/12994001/31443113-b52b948a-aec2-11e7-8d41-30a611020983.png)

Here are all of my configs, I haven't changed anything since I install prettier a few months ago.
```
  "prettier.singleQuote": true,
  "prettier.parser": "flow",
  "prettier.jsxBracketSameLine": true,
  "prettier.printWidth": 100,
  "prettier.eslintIntegration": true,
```

How can I re-config to makes prettier work like before the update?

**Comment by azz** [comment]
This behavior was changed in https://github.com/prettier/prettier/pull/2673. Prettier doesn't have configuration for these kinds of changes. It's an opinionated formatter. 

There's discussion here: https://github.com/prettier/prettier/issues/1565
