### ISSUE TITLE
Feature request for CSS

### ISSUE THREAD

**Issue by Samyak-Bumb** [prettier/prettier-vscode#2400]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Increase CSS Formatting (Linear Gradient, Box-Shadow).
Add it one upon one to understand about it.

**Additional context**

Above **Linear Gradient** is Formatted By Me & Below Formatted By Prettier
![Screenshot (17)](https://user-images.githubusercontent.com/88429776/151661780-343f3294-ab98-4ece-8af4-3eaa170c3768.png)

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
