### ISSUE TITLE
The extension uses an old prettier version if a new one is installed

### ISSUE THREAD

**Issue by Balastrong** [prettier/prettier-vscode#2409]
**Is your feature request related to a problem? Please describe.**
When opening VSCode, the extension loads prettier from node_modules.
If the local instance is updated (e.g. npm install a different version) the extension keeps using the old one.

**Describe the solution you'd like**
When a new version is installed, the extension automatically updates.

**Describe alternatives you've considered**
Closing and reopening VSCode is enough, but it would be much better if this is automatic.

**Additional context**
Spent hours debugging why formatting from cli had different results than the extension, turns out it was because I didn't close VSCode and the extension was using a different version.

**Comment by lsandoval0000** [comment]
I got the same problem, I was trying to use the new option from Prettier 2.6, "singleAttributePerLine", but VSCode extension was using an old one, and in my case, it doesn't let me use that new option.

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).

**Comment by holmesadrianh** [comment]
I have

> I got the same problem, I was trying to use the new option from Prettier 2.6, "singleAttributePerLine", but VSCode extension was using an old one, and in my case, it doesn't let me use that new option.

I have the same issue. I have the option in the config file, I see it being loaded in the prettier log, yet its not making a difference. Attributes are still formatted each on a new line. I know this is good practice, but for the project I am working on its really not needed and would be much neater and easier to navigate without this formatting. Is there a way to manually update the version?

**Comment by lsandoval0000** [comment]
> 

Yes, for me, the way was to install Prettier 2.6 on my project, and if the extension does not recognize the new version (that was the case for the man who opened the issue and me), you need to close VS Code and open again (I have to close all VS Code windows because the extension was "locked").
