### ISSUE TITLE
Optimize startup time

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier-vscode#2452]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `9.3.0`
- OS Version: `Darwin x64 21.3.0`
- VS Code version: `1.66.0-insider`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/156916647-d00651ec-1a43-428d-b70e-5ab2d5a43eec.png">

Other frontend tool like eslint only takes 8ms.

**Comment by ntotten** [comment]
Happy to take a pr
