### ISSUE TITLE
"prettier.vueIndentScriptAndStyle": true ,  it never works.

### ISSUE THREAD

**Issue by Cazaea** [prettier/prettier-vscode#2454]
"prettier.vueIndentScriptAndStyle": true
No matter what the settings are, it never works.
What should i do?

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by Cazaea** [comment]
I'm sorry, I have understood that for the VS Code development tool, for the formatting of the vue file, the following configuration needs to be added to settings.json

`
"[vue]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
`
