### ISSUE TITLE
Prettier isn't formatting my code.

### ISSUE THREAD

**Issue by sambit089** [prettier/prettier-vscode#2458]
Hi,
Although I have installed the extension properly, Prettier is unable to format my code.
Please advise.
Thanks.

**Comment by stuprog** [comment]
Hi, can you show in a video how did you use it to understand more the problem ?

**Comment by sambit089** [comment]
Hi Sami,
Please have a look at the video sent from my email. The extension is properly installed and used as the default formatter.
However, when I make some changes to my code and expect it to auto format on save, it's not working.

Please help.

**Comment by stuprog** [comment]
Hello, 

I didn't receive the video from your email  can you try to upload it here .
