### ISSUE TITLE
Markdown parser not found using the web-based editor

### ISSUE THREAD

**Issue by mathieu1** [prettier/prettier-vscode#2460]
### Summary

Markdown parser is not found when using the web-based editor. 

### Github Repository to Reproduce Issue

This repository

### Steps To Reproduce:

1.  Open the [VS Code web-based editor on this repo](https://github.dev/prettier/prettier-vscode)
1.  Make sure the Prettier extension is installed and enabled
1.  Open `README.md` for editing
1.  Remove the second line (between header and first paragraph)
1.  Save
 
### Expected result

Format-on-save is supposed to happen, re-introducing the blank line between the header and the text

### Actual result

Nothing happens.

### Additional information

Format-on-save works for `*.js` and `*.json` files at least: after modifying e.g. `.eslint.js` and saving, format-on-save works correctly.

**VS Code Version**:

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:30.517Z (19 hrs ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0

**Prettier Extension Version**:

v9.3.0

**OS and version**:

Intel Mac OS X 10.15

## Prettier Log Output

```
["INFO" - 11:20:24] Extension Name: dev.prettier-vscode.
["INFO" - 11:20:24] Extension Version: 0.0.0.
["INFO" - 11:20:24] Using standalone prettier
["INFO" - 11:20:24] Using standalone prettier
["INFO" - 11:20:29] Formatting vscode-vfs://github/prettier/prettier-vscode/README.md
["INFO" - 11:20:29] Using standalone prettier
["INFO" - 11:20:29] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 11:20:29] Parser not inferred, trying VS Code language.
["ERROR" - 11:20:29] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

**Comment by keawade** [comment]
I'm running into this issue as well for markdown and JSON files. JS files format as expected.

Markdown file output:
```text
["INFO" - 4:37:24 PM] Formatting vscode-vfs://github-path-to-my-repo/foo.md
["INFO" - 4:37:24 PM] Using standalone prettier
["INFO" - 4:37:24 PM] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 4:37:24 PM] Parser not inferred, trying VS Code language.
["ERROR" - 4:37:24 PM] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

JSON file output:
```text
["INFO" - 4:35:06 PM] Formatting vscode-vfs://github-path-to-my-repo/bar.json
["INFO" - 4:35:06 PM] Using standalone prettier
["INFO" - 4:35:06 PM] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 4:35:06 PM] Parser not inferred, trying VS Code language.
["ERROR" - 4:35:06 PM] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

**Comment by markerikson** [comment]
Yep, seeing this as well when trying to edit and tweak Markdown files in various PRs.  Would be great to see this fixed!

**Comment by Cerix** [comment]
I'm running into this issue as well for bash files using vscode insiders for mac.

```
["INFO" - 18:39:32] Extension Name: esbenp.prettier-vscode.
["INFO" - 18:39:32] Extension Version: 9.10.4.
["INFO" - 18:39:55] Forced formatting will not use ignore files.
["INFO" - 18:39:55] Formatting file://entrypoint.sh
["INFO" - 18:39:55] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 18:39:55] Parser not inferred, trying VS Code language.
["ERROR" - 18:39:55] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.

```

**Comment by marcelocra** [comment]
It is quite weird, this one. I even defined the override to tell prettier which parser to use, but it still gives the same error.

My  `.prettierrc`:

```json
{
  "printWidth": 80,
  "proseWrap": "preserve",
  "endOfLine": "lf",
  "tabWidth": 4,
  "overrides": [
    {
      "files": "*.md",
      "options": {
        "parser": "markdown",
        "printWidth": 80,
        "proseWrap": "always"
      }
    }
  ]
}
```

**Comment by markerikson** [comment]
Still very much a problem last time I checked.

**Comment by haochuan9421** [comment]
Still the same error! Seems It was closed because no one was handling it.

**Comment by karlhorky** [comment]
@ntotten can you reopen this issue and prevent it from being auto-closed? It's still relevant.

Or @mathieu1 could create a new issue...
