### ISSUE TITLE
Visual Studio Code Plugin -> Bracket Line Option is not working

### ISSUE THREAD

**Issue by caglarduman** [prettier/prettier-vscode#2462]
We are trying to make "Bracket Line = false" options in Visual Studio Code Plugin

According to this doc => https://prettier.io/docs/en/options.html

![image](https://user-images.githubusercontent.com/1950239/157970394-64f011fa-f185-4b17-8e83-4ebee6d16877.png)

But in Visual Studio Code Prettier Plugin (v9.3.0) we can't use this options :

![image](https://user-images.githubusercontent.com/1950239/157970480-3c8f0f19-f2cb-4153-ad0c-b939026a9712.png)

According to your doc => https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

![image](https://user-images.githubusercontent.com/1950239/157970596-64d4c95f-4840-4774-82b8-473e58e472f3.png)

prettier.jsxBracketSameLine is deprecated ! So this options is not working now. Any ideas ?

**Comment by ntotten** [comment]
Happy to take a PR fixing this
