### ISSUE TITLE
Cannot use Prettier formatting (Maybe VS code update broke it?)

### ISSUE THREAD

**Issue by DMLON** [prettier/prettier-vscode#2466]
### Summary

Cannot use formatter, getting "Extension is configured as a formatter but it cannot format "JavaScript" files

### Steps To Reproduce:

1. Right click document
2. Click Format Document
3. Get error saying it cannot format document
4. Check default formatter
5. Prettier is missing from list

### Additional information

![image](https://user-images.githubusercontent.com/29444416/158292441-6ee2723c-1f9b-4a7f-bdd2-5dfd0cdbed8b.png)

**VS Code Version**:

Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Prettier Extension Version**:

Name: Prettier - Code formatter
Id: esbenp.prettier-vscode
Description: Code formatter using prettier
Version: 9.3.0
Publisher: Prettier
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

## Prettier Log Output

When checking developer console i get:

Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'c:\Users\damia\.vscode\extensions\esbenp.prettier-vscode-9.3.0\dist\extension'
Require stack:
- c:\Users\damia\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\damia\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\damia\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js

I cannot get prettier logs, missing the prettier button on the bottom bar

**Comment by harvanchik** [comment]
Confirmed. I am getting the same error.

**Comment by harvanchik** [comment]
Is no one else having this issue?  All of my projects no longer can be formatted automatically.  Something must have broke the extension because I have not changed any setting that would have broke it.

**Comment by DMLON** [comment]
Found a fix, had to manually compile the extension, then copy the dist files and node_modules/prettier to 

C:\Users\%USER%\.vscode\extensions\esbenp.prettier-vscode-9.3.0

Also edit the package.json file in there to have the "main" and "browser" keys to have ".js" at the end of the files.

Weird thing all these files aren't shipped in prettier-vscode 9.3.0

**Comment by owen-duncan-snobel** [comment]
> 

I have the same thing happening for me. No longer formatting across my js projects and html and nothing changed.

**Comment by luastoned** [comment]
Disabling and enabling the extension fixed the issue for me.

**Comment by harvanchik** [comment]
> Disabling and enabling the extension fixed the issue for me.

No luck for me when I tried that.

**Comment by ntotten** [comment]
Related https://github.com/microsoft/vscode/issues/146103

**Comment by DMLON** [comment]
Having no issues with prettier 9.5.0 and vscode 1.65.2. Uninstalled and installed it again with no problem.

**Comment by icepole-jon** [comment]
uninstall vscode and delete all prettier folders from userprofilepath/.vscode/extensions
reinstall vscode and prettier
good luck.
