### ISSUE TITLE
Not formatting html tags correctly, splits html tags on several lines

### ISSUE THREAD

**Issue by hakonamatata** [prettier/prettier-vscode#2469]
### Summary

Working on a large Angular project. Been using esbenp.prettier-vscode for several years, everything works fine except one thing that has annoyed me for years. HTML tags are split in two, on two different lines. This makes no sense. 

### Steps To Reproduce:

take this code: 

```
    <app-ice-card type="error" padding=".5rem"
      ><span class="alert-label">Title</span>Blabla blabla ablabla ablablabla</app-ice-card
    >
```

and click save, nothing happens. 

or take this code: 

```
  <app-ice-card type="error" padding=".5rem"><span class="alert-label">Title</span>Blabla blabla ablabla ablablabla
    </app-ice-card >
```

click save/format, and you get this: 

```
  <app-ice-card type="error" padding=".5rem"
    ><span class="alert-label">Title</span>Blabla blabla ablabla ablablabla
  </app-ice-card>
```

When it should be 

```
  <app-ice-card type="error" padding=".5rem">
    <span class="alert-label">Title</span>Blabla blabla ablabla ablablabla
  </app-ice-card>
```

### Expected result

```
  <app-ice-card type="error" padding=".5rem">
    <span class="alert-label">Title</span>Blabla blabla ablabla ablablabla
  </app-ice-card>
```

### Actual result

```
    <app-ice-card type="error" padding=".5rem"
      ><span class="alert-label">Hemmelig kunde</span> Vær forsiktig med sensitiv informasjon.</app-ice-card
    >
```

**VS Code Version**:

```
Version: 1.65.2 (system setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Prettier Extension Version**:

`
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
`

**OS and version**:

Same result on Windows and Mac 

### Log

```
["INFO" - 16:26:57] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 120,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "c:\\Users\\user\\AppData\\Roaming\\Code\\User\\settings.json",
  "parser": "json"
}
["INFO" - 16:26:57] Formatting completed in 0.009ms.
```

**Comment by j-f1** [comment]
This is intentional behavior, see [the blog post for the release that introduced this feature](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) and [the docs for the option to control it](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity). Adding spaces manually will cause Prettier to reformat your code in a more “normal” way (but that could affect your page layout, as described in the links).
