### ISSUE TITLE
Support set prettier as default formatter for [jsonc]

### ISSUE THREAD

**Issue by laggage** [prettier/prettier-vscode#2477]
**Is your feature request related to a problem? Please describe.**
.vscode/settings.json has the language id which is `jsonc`, however, I cannot set prettier as the default formatter for it

<img width="882" alt="image" src="https://user-images.githubusercontent.com/38829279/159839145-8d35a47d-0fc9-4632-b6d5-d85fc1144dcb.png">

**Describe the solution you'd like**
Support set prettier as default formatter for [jsonc]

**Comment by laggage** [comment]
Manually add `"editor.defaultFormatter": "esbenp.prettier-vscode"` to `[jsonc]` section in settings.json, and then run format, it alert an error

<img width="910" alt="image" src="https://user-images.githubusercontent.com/38829279/159839532-b2c18bc1-3151-4a7c-b998-22b9cf937520.png">

**Comment by laggage** [comment]
#1032 seems relate to this

**Comment by ntotten** [comment]
Closing in favor of https://github.com/prettier/prettier-vscode/issues/2498
