### ISSUE TITLE
Do not use editor configuration if project uses prettier

### ISSUE THREAD

**Issue by k15a** [prettier/prettier-vscode#248]
Prettier VSCode shouldn't merge the custom editor configuration with the configuration from the projects as this leads to a different style than the one from the CLI. It would be great if the custom configuration would be only used when the project doesn't use Prettier directly.

**Comment by nicu-chiciuc** [comment]
This caused a lot of problems in the projects I've been working on. Ideally the plugin shouldn't provide any of its own configurations.  Currently there are cases in which the CLI result differs from the result of the plugin even if no configuration is set in either.

This shouldn't be labeled as enhancement but as a bug.
