### ISSUE TITLE
Why CMD + shift + p not work?

### ISSUE THREAD

**Issue by sqfbeijing** [prettier/prettier-vscode#250]
![https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) .
The document says:

```
1. CMD + Shift + P -> Format Document
OR
1. Select the text you want to Prettify
2. CMD + Shift + P -> Format Selection
```
I Follow the documentation, CMD + Shift + P didn't work.
But option + shift + F (the vscode default format keybinds) work.
I see CMD + Shift + P is the default key binding of vscode, for 'workbench.action.showCommands',  
I am very confused  why prettier use this and produce a conflict. and, how to resolve the problem.?? Help..

**Comment by azz** [comment]
<kbd>CMD</kbd><kbd>Shift</kbd><kbd>P</kbd> will bring up the command palette. From there you  can select "Format Document" or "Format Selection" (as documented). This is the same as the <kbd>CMD</kbd><kbd>Shift</kbd><kbd>F</kbd>

**Comment by sqfbeijing** [comment]
Oh oh, i misunderstanding before.  Thanks very much.😁

**Comment by victorvasujoseph** [comment]
You can also change it to your desired key set. Press the 'Setting's icon' in the left end bottom corner and select->keyboard shortcuts. Then type in 'Format Document'. Click the edit icon in the right and select the desired key using your keyboard. Happy coding !!

**Comment by DustyBest** [comment]
Just took me a hot minute to realize that we have to go to 'FORMAT DOCUMENT' after bringing up the command palette. I also thought that it would be like a hot-key that just formats the document. ***face-palm***

**Comment by HemantRMali** [comment]
Simple:
Go to extensions, Select Prettier, UnInstall, use opt(alt)+shift+F (VSCode Native)

**Comment by devinrhode2** [comment]
Capto screen recording was intercepting cmd+shift+p for me.
