### ISSUE TITLE
e2e extension tests

### ISSUE THREAD

**Issue by christian-bromann** [prettier/prettier-vscode#2503]
**Is your feature request related to a problem? Please describe.**
It seems that this extension has no tests at all and I wonder if you would be interested adding some e2e tests to ensure the basic functionality is working on all operating systems. I am happy to take a stab at this.

**Describe the solution you'd like**
I've been working on an [e2e testing solution](https://github.com/webdriverio-community/wdio-vscode-service) for VSCode extensions and wanted to battle test it on some of the popular VSCode extensions.

**Comment by ntotten** [comment]
There are tests, but we'd be happy to have more!
