### ISSUE TITLE
Glob patterns not respected in .prettierignore

### ISSUE THREAD

**Issue by corydeppen** [prettier/prettier-vscode#251]
It doesn't look like the extension is respecting glob patterns within the `.prettierignore` file. My ignore file includes a line `/Content/scripts/**/*`, which ignores `/Content/scripts/app/app.js` file as expected when I use Prettier from the command line but not from when I save the file in VS Code.

**Comment by gregmcguffey** [comment]
I am having the same issue. I have a file in .prettierignore. When I use command line, it is used, but during save, it formats the file.

**Comment by vjonas** [comment]
same here, isn't that supposed to work?

**Comment by CiGit** [comment]
That's in our implementation of ignore. I'm right @azz ?

**Comment by CiGit** [comment]
Is this fixed by #280 ?

**Comment by CiGit** [comment]
Seems fixed
