### ISSUE TITLE
Update `ext.config.requireConfig` in `package.nls.zh-tw.json` in order to uniform to `prettier configuration`

### ISSUE THREAD

**Issue by roottool** [prettier/prettier-vscode#2511]
### Summary

`package.nls.json` and `package.nls.zh-cn.json` say `prettier configuration`, whereas `package.nls.zh-tw.json` says `prettierconfig`.

### Expected result

`package.nls.json`, `package.nls.zh-cn.json` and `package.nls.zh-tw.json` will be uniformed to `prettier configuration`.

### Actual result

`package.nls.json` and `package.nls.zh-cn.json` say `prettier configuration`, but `package.nls.zh-tw.json` says `prettierconfig`.

### Additional information

**Code pointer**

- https://github.com/prettier/prettier-vscode/blob/991a53f27df9f6d2abc782d8065512310c120983/package.nls.json#L6
- https://github.com/prettier/prettier-vscode/blob/991a53f27df9f6d2abc782d8065512310c120983/package.nls.zh-cn.json#L4
- https://github.com/prettier/prettier-vscode/blob/991a53f27df9f6d2abc782d8065512310c120983/package.nls.zh-tw.json#L4

**VS Code Version**: 1.66.1

**Prettier Extension Version**: v9.5.0

**OS and version**: Windows 11, Debian bullseye in WSL2

**Comment by ntotten** [comment]
Happy to take a pull request, but those translations are user-contributed as I am not fluent.
