### ISSUE TITLE
integration of `singleAttributePerLine` option 

### ISSUE THREAD

**Issue by sanket-bhalerao** [prettier/prettier-vscode#2520]
**Is your feature request related to a problem? Please describe.**
currently, prettier formats the HTML attributes on the separate lines every time print width is exceeded.
i can see the `singleAttributePerLine` option in prettier 2.6 however I can not see the related option in prettier vscode plugin.

**Describe the solution you'd like**
integration of `singleAttributePerLine` option in prettier vscode extension.

current behavior
![image](https://user-images.githubusercontent.com/9264813/163666036-78ae292a-ac3a-40c2-bbc8-5a4b1bf8d448.png)

expected behavior
![image](https://user-images.githubusercontent.com/9264813/163666067-281ff1ae-2119-47c8-b588-ba3b66e784a8.png)

**Comment by favger** [comment]
same way

![Untitled](https://user-images.githubusercontent.com/25633595/164272208-9dd151b3-96f5-4ec0-b552-b63a7d5ebaee.png)

**Comment by saskosaurus** [comment]
This might help you
_"prettier.printWidth": 10000_

**Comment by ntotten** [comment]
In version 9.7.0
