### ISSUE TITLE
First-argument objects are missing newlines (sometimes indentation, too)

### ISSUE THREAD

**Issue by JanCVanB** [prettier/prettier-vscode#253]
## Input
```js
a({ b: c, d: e }, f);

a(
  { b: c, d: e },
  f
);

a(
  {
    b: c,
    d: e
  },
  f
);
```

## Expected Output ([Link to Prettier Playground demo](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAFMABAIyVsAGiwBN84sBfYgM3QEp6BuAHSjYzay2zwOLJYK1Lljr02zNh3Sjgo7nyILS5USKjdxk1lBCEQEAA4wAltADOyUKgsxkNVABsLcAzgBOqMAGs4MAGUjb1MoAHNkGA8AVzcQEggwB2dXAwArCwAPACEvX38A1ABbOAAZULhklziIaJgjOoAmKtSQYI9XD2QQHFQcAE8naH02j1CYAHVTEhgAC2QADgAGA1ci00iYuItQsKc4AEVoiHgWuJg+qZn5pEaDKNRTJ12AYQgiotRuqGhKg2jXAAVPpWJCOaqUShAA))
```js
a({ b: c, d: e }, f);

a({ b: c, d: e }, f);

a(
  {
    b: c,
    d: e
  },
  f
);
```

## Actual Output (with `"editor.tabSize": 2` in settings)
```js
a({
  b: c,
  d: e
}, f);

a({
    b: c,
    d: e
  },
  f
);

a({
    b: c,
    d: e
  },
  f
);
```

## Thanks for the extension! 😄

**Comment by CiGit** [comment]
Trying with your file I have your expected output.

What version of prettier do you use? There is a tooltip on **Prettier: ✔️** which tells it.

**Comment by JanCVanB** [comment]
@CiGit Thanks for responding!

I'm sorry, but I don't understand. Are you asking what version of Prettier I have installed on my computer? I do not have Prettier installed globally on my computer, but I have the latest (1.7.4) locally in my project. What is "**Prettier:** ✔️"?

**Comment by RobinMalfait** [comment]
He is referring to the right bottom of your vscode: ![](http://d.rbn.nu/xIAYOs.png) if you hover that, a tooltip will appear with information.

**Comment by JanCVanB** [comment]
@RobinMalfait Thanks!

@CiGit Okay, I didn't see a ✔️, so I installed Prettier globally and restarted VisualStudio - now it works as expected! 😄 Must have been some other formatter at work. Sorry for the confusion! Thanks again.
