### ISSUE TITLE
This's not work when the eslint is set up : '"react/jsx-max-props-per-line": [2, {"maximum": 1}]' 

### ISSUE THREAD

**Issue by huangguangpo** [prettier/prettier-vscode#2530]
eg .  on project => .eslintrc file
   "react/jsx-max-props-per-line": [2, {"maximum": 1}]

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
