### ISSUE TITLE
Formatting a file on an NFS mount doesn't  actually write any content to the file.

### ISSUE THREAD

**Issue by C5H8NNaO4** [prettier/prettier-vscode#2532]
### Summary
My working directory is a folder on a mac which is mapped to a local volume on windows through nfs. 
I'm simply trying to format a file. 

### Github Repository to Reproduce Issue
-

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  Share a Folder on your Mac
2.  Map the folder to a volume on windows
3. Format a file using prettier vscode

### Expected result

The file should be formatted and written.

### Actual result

Nothing happens. The log message shows the file is being processed. 

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.66.2

**Prettier Extension Version**: v9.5.0

**OS and version**:10 

## Prettier Log Output

```
["DEBUG" - 02:52:35] Using bundled version of prettier.
["INFO" - 02:52:37] Formatting file:///m%3A/cosuno/frontend/src/components/Project/Viewer/index.tsx
["INFO" - 02:52:37] Using config file at 'm:\cosuno\frontend\.prettierrc'
["DEBUG" - 02:52:37] Local prettier module path: 'm:\cosuno\frontend\node_modules\prettier\index.js'
["INFO" - 02:52:37] Using ignore file (if present) at m:\.prettierignore
```

**Comment by ntotten** [comment]
I don't have any way of reproducing this as I don't have access to an NFS mounted drive. Happy to take a PR though.
