### ISSUE TITLE
Setting to specify what .prettierrc to use

### ISSUE THREAD

**Issue by felixfbecker** [prettier/prettier-vscode#254]
We share a .prettierrc between multiple repos by publishing it as an npm module, running `prettier` with
```
prettier --config ./node_modules/@sourcegraph/prettierc/.prettierrc
```
prettier-vscode currently does not have a way to configure that, it will not detect any config for the repo, so we have to duplicate the settings, which defeats the purpose of sharing the config. It would be nice to have a setting `"prettier.configPath"` like `"prettier.ignorePath"`. I know you don't like new settings but this one is to avoid having to use the other settings ;)

**Comment by azz** [comment]
Workaround, create a `.prettierrc` with:

```js
module.exports = require('@sourcegraph/prettierc');
```

**Comment by felixfbecker** [comment]
That's a great idea!

**Comment by kutyel** [comment]
Regarding this, according to prettier's docs, the `.prettierrc` file could also be  a .yml file but when I try to do so the JSON validation yells at me. Is this intentional? Should I open another issue for this? Thanks in advance! <3

**Comment by azz** [comment]
If you're working with yaml in vscode I'd recommend using `.prettierrc.yml` instead.

**Comment by CiGit** [comment]
@kutyel our extension is associating .prettierrc to JSON. You can change it to yaml if you prefer and it won't yell. Maybe we should remove that default association. And validate only .prettierrc.json

**Comment by kutyel** [comment]
I don't know what is the correct behaviour (cause I am biased) but for me is kinda counter-intuitive that *prettier* itself allows those formats (without changing the extension of the file) and the `vscode-extension` itself doesn't. BTW the apart from that it works perfectly and thanks very much guys for creating it for VSCode! ❤️

**Comment by kachkaev** [comment]
@felixfbecker if you prettier config is in `./node_modules/@sourcegraph/prettierc/.prettierrc`, can you simply create a symlink at the root of your project pointing to that file? That might fix the issue you are having, unless I've misunderstood it.

**Comment by felixfbecker** [comment]
I like to avoid symlinks if they are not needed. Many tools do not follow them (because there is risk of infinite loops) and they don’t work by default on Windows <10 / need special permissions.

**Comment by ntotten** [comment]
Feature added in version 3.0
