### ISSUE TITLE
Please become a verified publisher

### ISSUE THREAD

**Issue by awdr74100** [prettier/prettier-vscode#2555]
**Is your feature request related to a problem? Please describe.**
Becoming verified publisher will help identify the correct extension (too many similar extensions).

**Describe the solution you'd like**
Verify the publisher as described in the [document](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher).

By the way, this program is very helpful for my daily development, thanks to the maintenance team for their efforts!

**Comment by ntotten** [comment]
@isidorn id like to do this, but the main issue is this extension is published as the username of the original contributor. Is there anyway to move the extension to the prettier vscode user without breaking a bunch of stuff?

**Comment by isidorn** [comment]
@ntotten moving the extension will break a bunch of stuff, but we could add a new publisher to the prettier account.
If you would like us to do this can you send an email request to me inikolic@microsoft.com
Make sure to send the email from the email account that is tied to the current prettier publisher

**Comment by ntotten** [comment]
I sent you an email. Until we can move this to the prettier org, I think it's probably not a great idea to verify the current publisher this account is owned by the original author who is no longer involved in the project.
