### ISSUE TITLE
There is a problem with the export type for typescript

### ISSUE THREAD

**Issue by Jeggery** [prettier/prettier-vscode#2558]
example: 
` ["ERROR" - 下午4:27:26] Error formatting document.
["ERROR" - 下午4:27:26] Declaration or statement expected. (5:1)
  3 | import DiffusionWave from '../../../utils/diffusionWave';
  4 | import LineManager from './LineManager';
> 5 | export type { ISpriteMark } from './libs/SpriteClassify';
    | ^
  6 | 
  7 | type Vec = Pick<Vector3, 'x' | 'y' | 'z'>;
  8 | 
SyntaxError: Declaration or statement expected. (5:1)
  3 | import DiffusionWave from '../../../utils/diffusionWave';
  4 | import LineManager from './LineManager';
> 5 | export type { ISpriteMark } from './libs/SpriteClassify';
    | ^
  6 | 
  7 | type Vec = Pick<Vector3, 'x' | 'y' | 'z'>;`

For the new version of typescript, there is a problem with export type and prettier

**Comment by ntotten** [comment]
You are runn
**Recommendation**: Upgrade to the latest version of prettier.

**Explanation**: You are likely using a newer version of Typescript than the version of prettier you have installed supports. Typescript features are added in new prettier releases. See the prettier blog to learn more about what features of typescript are enabled for each version of prettier: https://prettier.io/blog/
