### ISSUE TITLE
Detect global installation of prettier/plugin-php

### ISSUE THREAD

**Issue by mandrasch** [prettier/prettier-vscode#2564]
**Is your feature request related to a problem? Please describe.**

The php plugin for prettier (https://github.com/prettier/plugin-php) is supported by prettier-vscode, but only when plugin-php is installed locally via yarn/npm:

```
npm install --save-dev prettier @prettier/plugin-php
```

A global installation is not detected by prettier-vscode:

```
npm install --global prettier @prettier/plugin-php
```

This is also mentioned here: https://github.com/prettier/plugin-php#vscode

**Describe the solution you'd like**

It would be great if a global installation of prettier/plugin-php could be used when no local package is detected. It would make it a lot easier to use this extension throughout multiple (PHP) projects. Currently for every project you need to run `npm install --save-dev prettier @prettier/plugin-php` and `npm install`, even if no other npm packages are used by the project.

(Additionally it would be totally awesome if the php plugin could be installed inside of the vscode extension of course. I don't know the technical details of this extension yet.)

**Describe alternatives you've considered**
None

**Additional context**
Thanks very much for providing this extension!

**Comment by davidbdeath** [comment]
I'm experiencing the same issue with @prettier/plugin-php@0.18.8 and prettier-plugin-css-order@1.2.0.

I'm on Mac OS 12.4.

It would be nice to not have to install the NPM libraries for every project.

**Comment by ntotten** [comment]
Not something i am planning on doing as the official recommendation is against using global extensions: https://prettier.io/docs/en/install.html

**Comment by davidbdyer** [comment]
I figured a work around by adding this to my workspace settings json.
I've stopped using prettier except for one or two file types anyways. I don't care for some of its opinions.

```json
{
	"prettier.prettierPath": "/usr/local/lib/node_modules/prettier"
}
```

**Comment by mandrasch** [comment]
> Not something i am planning on doing as the official recommendation is against using global extensions: https://prettier.io/docs/en/install.html

Thanks very much for reply and clarification! 

(For interested readers: There is also a setting [`prettier.resolveGlobalModules`](https://github.com/prettier/prettier-vscode/blob/main/README.md#prettier-resolution ) for the vscode prettier plugin. It is not recommend (!), but can be used as workaround for certain use cases. Did not test it myself,  found it [here](https://github.com/prettier/plugin-php/issues/1721#issuecomment-1226498216)
