### ISSUE TITLE
In lastest version vscode, cause semicolon autocomplete problem

### ISSUE THREAD

**Issue by maqic** [prettier/prettier-vscode#257]
![kapture 2017-11-07 at 14 55 08](https://user-images.githubusercontent.com/1974254/32480871-717b9d36-c356-11e7-9c1b-c29bd933766e.gif)

osx: 10.12.6
vscode: 1.17.2 (1.17.2) b813d12980308015bcd2b3a2f6efa5c810c33ba5

After I disable this extension, no longer have this issue

**Comment by CiGit** [comment]
What are you doing here exactly? Copy paste `test`

Can you share your settings ?

I can't reproduce that (even with **formatOnPaste**)

**Comment by CiGit** [comment]
I found out. 
I was in a typescript file ...
Format selection is not working here by selecting the string.
Directive vs Literal??

**Comment by maqic** [comment]
You can reproduce by this step:

- configuration `"editor.formatOnPaste": true`
- Open a `.js` file, write some code like `console.log('test');`
- Copy paste `test`, then you will get a extra semicolon.

**Comment by azz** [comment]
Could it be doing a range format on that string as if it were a directive (`"use strict";`)?

**Comment by CiGit** [comment]
It's fixed in prettier 1.8, 1.7 accepted a string as Source Element (JS was mixed with JSON) prettier/prettier#3069

**Comment by CiGit** [comment]
Strangly it's working with TS and Flow

**Comment by CiGit** [comment]
This should be fixed in prettier 1.8

**Comment by MiLeung** [comment]
I am getting this behavior on 1.9.0. Not ideal.
