### ISSUE TITLE
singleAttributePerLine not working

### ISSUE THREAD

**Issue by TkinterinShanghai** [prettier/prettier-vscode#2570]
### Summary

setting `singleAttributePerLine` to true does not have any effect. 

### Steps To Reproduce:

1.  Your .prettierrc looks like this: 
```
{
    "singleQuote": true,
    "printWidth": 200,
    "semi": true,
    "useTabs": false,
    "trailingComma": "none",
    "arrowParens": "avoid",
    "tabWidth": 4,
    "singleAttributePerLine": true
}
```

2.  Create some HTML file with lots of attributes per node

### Expected result

Each attribute gets put on a separate line

### Actual result

Attributes get squished into a single line

### Additional information

**VS Code Version**:

1.67.2

**Prettier Extension Version**:

9.5.0

**Prettier Library Version**:

2.6.2

**OS and version**:

Mac Monterey, 12.3.1

**Comment by karlitos** [comment]
Affects me too

**Comment by jzsn2018** [comment]
delete this  "printWidth": 200  try again

**Comment by isakigus** [comment]
Not working for me too, option is not reconized

![image](https://user-images.githubusercontent.com/9664843/183883150-95722f72-b5f7-437c-96d5-a466433885f0.png)

**Comment by nathan1658** [comment]
> Not working for me too, option is not reconized
> 
> ![image](https://user-images.githubusercontent.com/9664843/183883150-95722f72-b5f7-437c-96d5-a466433885f0.png)

Seem this feature is not yet released. [CHANGELOG](https://github.com/prettier/prettier-vscode/blob/main/CHANGELOG.md)
