### ISSUE TITLE
Breaks after opening large JSON files

### ISSUE THREAD

**Issue by rogadev** [prettier/prettier-vscode#2572]
### Summary

When opening a large JSON file, even one that is in my .prettierignore file, Prettier will no longer work. I've created a short video for you to watch it happen.
[Link to unlisted YouTube video here.](https://youtu.be/79wJU6Fc6AE)

### Github Repository to Reproduce Issue

GitHub repo is private, but I can share the JSON file. The contents of which is public data, collected for our use.
[Link to the GitHub Gist here.](https://gist.github.com/rogadev/76304f3db226d48dd3fb64fec5cef472)

### Steps To Reproduce:

1. Set up a basic node/express project with just a basic .js file and the above linked .json file.
2. Make a small change to the .json file and save.
3. Make a change to your .js file and save.

### Expected result

Expected Prettier to save in a timely manner.

### Actual result

Gets stuck saving and does not format document. Doesn't crash, but just sits there, "formatting", forever.
![image](https://user-images.githubusercontent.com/61405141/171913184-ab43d9e1-9c33-4ce3-8f7f-711f39441cb5.png)

### Additional information

See attached screenshots and video throughout. 

**VS Code Version**:

Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

**Prettier Extension Version**:

v9.5.0

**OS and version**:

Edition	Windows 10 Education
Version	21H2
Installed on	‎2020-‎08-‎27
OS build	19044.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

## Prettier Log Output

["INFO" - 10:15:11 a.m.] Extension Name: esbenp.prettier-vscode.
["INFO" - 10:15:11 a.m.] Extension Version: 9.5.0.

Note: Because it's not crashing, no log has been created. It just won't seem to run at all.

```
["INFO" - 10:15:11 a.m.] Extension Name: esbenp.prettier-vscode.
["INFO" - 10:15:11 a.m.] Extension Version: 9.5.0.
```

**Comment by NeckBeardPrince** [comment]
Experiencing the same issue on macOS using 1.68.0-insider.

**Comment by ntotten** [comment]
Can you repos the gist, it 404s
