### ISSUE TITLE
FR: keep frontmatter but format document

### ISSUE THREAD

**Issue by Dexus** [prettier/prettier-vscode#2577]
**Is your feature request related to a problem? Please describe.**
I'm frustrated, that all the formatting plugins are always kill my frontmatter data. I would love to see that the frontmatter data will not be touched but all the rest get formatted.

**Describe the solution you'd like**
Add helper like https://www.npmjs.com/package/gray-matter to keep the frontmatters.

**Describe alternatives you've considered**
I tried already multiple formatter tools but non would support the frontmatter :(

**Additional context**

```
---
title: Hello
slug: home
---
<div>
<h1>Hello world!</h1>
<div>
```

should return 

```
---
title: Hello
slug: home
---
<div>
  <h1>Hello world!</h1>
<div>
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
