### ISSUE TITLE
Specify location of .eslintrc

### ISSUE THREAD

**Issue by theetrain** [prettier/prettier-vscode#258]
Hello, thanks for the great work! I use Prettier in all my projects.

Is there a way to specify the location of my **.eslintrc** file? I'd like to place it in the **.vscode** directory, but it only seems to get read by Prettier when it's in the project root.

**Comment by CiGit** [comment]
Hi, thanks for raising that issue.
What you ask is a workflow we do not support. Your .eslintrc doesn't have to be in your root. It can be anywhere between your file and your file-system root. (And maybe even in your $HOME. Not sure about that)

You can also use prettier to format your code and eslint (eslint extension) to validate none styling issues. Or even styling issues.
To do so:
-  disable eslintIntegration
- Use eslint's fix all after you formatted.
- Automatically, `formatOnSave:true, eslint.autoFixOnSave:true`

Drawback : a little slower and your editor may blink: changing the content twice.

**Comment by CiGit** [comment]
Closing as I don't know what to do with that.
