### ISSUE TITLE
Space between arrays on single line

### ISSUE THREAD

**Issue by DoCode** [prettier/prettier-vscode#259]
How to add spaces inside brackets of arrays on single line?

```json
{
  "items": [ "item1", "item2" ]
}
```

**Comment by CiGit** [comment]
This is a prettier feature, It was decided to remove spacing in brackets / parens.
Duplicate of #35 
You can read more about it in prettier/prettier#296

**Comment by DoCode** [comment]
Thank you.

**Comment by CiGit** [comment]
Forgot to mention, if you really want it, you can use 'eslintIntegration' with https://eslint.org/docs/rules/space-in-brackets

**Comment by DoCode** [comment]
@CiGit thanks for the hints!
But with this settings in VSCode it does not work on formatting the document:

```json
  "eslint.enable": true,
  "eslint.options": {
    "rules": {
      "array-bracket-spacing": ["error", "always", { "objectsInArrays": false }]
    }
  },
  "prettier.eslintIntegration": true
```

**Comment by CiGit** [comment]
Good point. We do not read from this settings.

You have to put them in a file .eslintrc

**Comment by DoCode** [comment]
The same behavior when I place a `.eslintrc` file with this content in a directory of json files:
```json
{
  "rules": {
    "array-bracket-spacing": ["always"]
  }
}
```

**Comment by CiGit** [comment]
My bad, I've read your initial post really badly. Thought it was JS not JSON.
Sadly, I've no workaround for you.
