### ISSUE TITLE
Need option for fallback config, `Prettier: Config Path` does not work for this

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier-vscode#2594]
**Is your feature request related to a problem? Please describe.**

I need a fallback config for when a project doesn't have a config file.

However, when I provide a path for `Prettier: Config Path`, it overrides any config in any project I am in, which is not what I wanted.

**Describe the solution you'd like**

Need an option that applies **only** when a project does not have its own configuration file, which is very much _not_ what the `Prettier: Config Path` option currently does.

**Describe alternatives you've considered**

There is no alternative other than undoing the `Prettier: Config Path` option so that project configs will be honored.

**Additional context**

**Comment by DAmNRelentless** [comment]
I'd also like the config path option to set the fallback config. That way you could make language-specific settings for the prettier extension.
Local project configurations should overwrite that though. It would make way more sense.

**Comment by ntotten** [comment]
Happy to take a PR on this.

**Comment by DAmNRelentless** [comment]
Why did you close this as completed?

**Comment by ntotten** [comment]
Because I'm not going to do it. Happy to take a PR.

**Comment by DAmNRelentless** [comment]
But why as completed? This is confusing and I thought this was done although you mentioned a PR is welcome.
Anyways, I will probably take a look into this once I have a bit of time.
