### ISSUE TITLE
Doesn't work when no Prettier found globally/locally

### ISSUE THREAD

**Issue by politician** [prettier/prettier-vscode#2597]
### Summary

When Prettier is neither found locally nor globally, this extension [states](https://github.com/prettier/prettier-vscode/blob/30c32808de8c159fa108e5521eb7b58fe0941724/README.md?plain=1#L118) that it will use a version of Pettier bundled with the extension but it doesn't.

### Github Repository to Reproduce Issue

<https://github.com/politician/prettier-ext-bug/tree/main>

### Steps To Reproduce:

1. Uninstall Prettier globally `npm uninstall -g prettier`
2. Clone the repo `git clone git@github.com:politician/prettier-ext-bug.git`
3. Open VS Code `code prettier-ext-bug`
4. Try to format `package.json` via the extension

### Expected result

Prettier should format my document

### Actual result

Prettier did not format my document

### Additional information

**VS Code Version**:

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:37.209Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0

**Prettier Extension Version**: v9.5.0

**OS and version**: MacOS Monterey 12.4

## Prettier Log Output

```
["INFO" - 10:00:43 AM] Formatting file:///Users/romain/Code/politician/prettier-ext-bug/package.json
["INFO" - 10:00:43 AM] Using config file at '/Users/romain/Code/politician/.prettierrc.yaml'
["INFO" - 10:00:43 AM] Attempted to determine module path from /Users/romain/Code/politician/prettier-ext-bug
["ERROR" - 10:00:43 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 10:00:43 AM] Cannot find module 'prettier' from '/Users/romain/Code/politician/prettier-ext-bug'
Error: Cannot find module 'prettier' from '/Users/romain/Code/politician/prettier-ext-bug'
    at Function.nodeModulesResDir [as sync] (/Users/romain/.vscode/extensions/esbenp.prettier-vscode-9.5.0/node_modules/resolve/lib/sync.js:112:9)
    at t.ModuleResolver.Error [as findPkg] (/Users/romain/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/ModuleResolver.ts:369:11)
    at t.ModuleResolver.logError [as getPrettierInstance] (/Users/romain/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/ModuleResolver.ts:106:43)
    at t.default.format (/Users/romain/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:392:27)
    at t.PrettierEditProvider.provideEdits (/Users/romain/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:322:22)
    at M.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:137239)
["ERROR" - 10:00:43 AM] Prettier could not be loaded. See previous logs for more information.
```

**Comment by omsrg** [comment]
having similar problem. tried everything, prettier extension just stopped working

**Comment by cyrus01337** [comment]
This seems to be an issue with module resolution only from within a project as it happens to be using the extension's bundled version of Prettier just fine when formatting VS Code's settings page.

Another strange situation: copying the body of `package.json`, running `yarn init -2`, then copy/pasting to overwrite the contents appears to use Prettier just fine. In fact, this works up to a single save, then when you try to save after it goes back to raising the posted error. Can anyone else reproduce this?

**Comment by cyrus01337** [comment]
A workaround for users of Yarn PnP is to create a/update your `.yarnrc.yml` and include `nodeLinker: node-modules` - assumedly the extension is able to pick up Prettier just fine from `node_modules/`, this appears to be working for me as a workaround for this post and my own projects.

**Comment by airtonix** [comment]
> A workaround for users of Yarn PnP is to create a/update your `.yarnrc.yml` and include `nodeLinker: node-modules` - assumedly the extension is able to pick up Prettier just fine from `node_modules/`, this appears to be working for me as a workaround for this post and my own projects.

It's not really a solution though is it? at this point you're not using PNP anymore.

We should be looking for a way to make vscode-prettier respect the pnp.cjs

**Comment by hojo0590** [comment]
I'm facing the exact same problem. I try to use it with a project just for formatting some markdown files, and the advertised use of the bundled prettier does not happen but results in the same error message as the first comment states.
VSCode 1.78.2
Prettier extension v9.13.0
