### ISSUE TITLE
Preview extension link 404

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier-vscode#2598]
### Summary

The https://marketplace.visualstudio.com/items?itemName=prettier.prettier-vscode-beta link in [Testing Preview Releases](https://github.com/prettier/prettier-vscode/wiki/Testing-Preview-Releases) leads to a 404 not found error.

Please consider either fixing the link or removing this document if it's no longer supported.

### Github Repository to Reproduce Issue

[Testing Preview Releases](https://github.com/prettier/prettier-vscode/wiki/Testing-Preview-Releases)

### Steps To Reproduce:

1. Visit [Testing Preview Releases](https://github.com/prettier/prettier-vscode/wiki/Testing-Preview-Releases)
2. Click https://marketplace.visualstudio.com/items?itemName=prettier.prettier-vscode-beta

### Expected result

200

### Actual result

404

### Additional information

N/A

## Prettier Log Output

N/A

**Comment by ntotten** [comment]
No preview extensions now, page deleted
