### ISSUE TITLE
Support formatting Markdown files

### ISSUE THREAD

**Issue by lipis** [prettier/prettier-vscode#260]
I'm not sure what should be done, but it would be nice to format the Markdown files as well since they are supported in version 1.8.0.

<img width="914" alt="screen shot 2017-11-09 at 20 14 45" src="https://user-images.githubusercontent.com/125676/32622148-a7ffe69c-c58a-11e7-8e0e-affc15a1dace.png">

**Comment by lipis** [comment]
Oups.. it's coming in #256 right?

**Comment by CiGit** [comment]
Exactly.

**Comment by lipis** [comment]
Good times :)
