### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Hionic** [prettier/prettier-vscode#2606]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `9.5.0`
- OS Version: `Darwin x64 21.5.0`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/vk/l93l3n312bj20k2j7s2j0ktm0000gn/T/esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bastienrobert** [comment]
related to #594
