### ISSUE TITLE
Support for Typescript 4.7 syntax

### ISSUE THREAD

**Issue by jarpoole** [prettier/prettier-vscode#2608]
### Summary

Using syntax introduced in Typescript 4.7, like `Instantiation Types` (see [here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#instantiation-expressions)) causes the extension to throw an error.

This issue has already been resolved upstream by the Prettier team. See the [changelog](https://prettier.io/blog/2022/06/14/2.7.0.html) for version 2.7. Presumably the extension just needs an update!

### Github Repository to Reproduce Issue

A full repo is definitely not required. For example the following code is valid in Typescript 4.7+ ([typescript playground](https://www.typescriptlang.org/play?#code/LAKAZgrgdgxgLgSwPZQAQFsCGBrApgISQA8AeAFQD4AKAN0wBsJcAuVMgSlQG9RVUAnXHAj80XVHUa5UAXwDcoGaBgoAznFQAjYqgC8GHAWIkoEdJtz8KcoA)) but not here.
```
function makeBox<T>(value: T) {
  return { value };
}
const box = makeBox<number>;
```

### Steps To Reproduce:

1.  Paste the above example into vscode with typescript 4.7 and the latest version of the prettier extension.

### Expected result

Prettier extension should format the file.

### Actual result

Prettier extension crashes with unrecognized syntax.

### Additional information

Need to update extension to use Prettier 2.7 which resolves these issues.

**VS Code Version**:

Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

**Prettier Extension Version**: 9.5.0

**OS and version**: Windows 11

**Comment by ntotten** [comment]
Will be enabled in version 9.6.0
