### ISSUE TITLE
How to config Single Attribute Per Line on prettier vscode plugin

### ISSUE THREAD

**Issue by MrHOY** [prettier/prettier-vscode#2619]
I don't see the option  Single Attribute Per Line in the config of prettier vscode plugin

Vscode version: 1.69.0
Prettier - Code formatter plugin version: v9.5.0

**Comment by iSCJT** [comment]
I've also been trying to find solution to this.  If I manually run prettier it works then when I manually save a file the local prettierrc is ignored because I'm assuming the viscose extension hasn't been set up with the new option.

**Comment by iSCJT** [comment]
Was just going to submit a pr but looks like they've already fixed it.  Guess a new release needs pushing to vscode.

https://github.com/prettier/prettier-vscode/commit/c3b340d892ed27d07b70c4049926034d5dad9294

**Comment by bartoligerman497** [comment]
Hello!! The option doesn't appear for me either, I can't use the new variable from my .json either because it doesn't exist:

```json
singleAttributePerLine: true;
```

Hope they add the new feature soon thanks!

**Comment by iSCJT** [comment]
I ended up downloading the latest release from GitHub and manually installing it into vscode. Now working 🙂

**Comment by bartoligerman497** [comment]
Yes??? how did you do it? Could you tell me? I just installed it from GitHub but the attribute still doesn't exist, what I did was install v9.6.0 prettier-vscode-9.6.0.vsix Latest from github dragging it to VSCode but it doesn't work.

**Comment by bartoligerman497** [comment]
Ahh I found in the log that it is the unreleased version, perfect! How do I install it?

**Comment by iSCJT** [comment]
I have an extension to install .vsix files:

https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-install-vsix

I think you can also install it using the command line: code –install-extension extension.vsix

Sean
________________________________

**Comment by MrHOY** [comment]
Hi @bartoligerman497 ,
I don't know how to get prettier-vscode-9.6.0.vsix file
Could you guide me?

**Comment by bartoligerman497** [comment]
Yes!! The URL is [This](https://github.com/prettier/prettier-vscode/releases/tag/v9.6.0)!!

**Comment by MrHOY** [comment]
> Yes!! The URL is [This](https://github.com/prettier/prettier-vscode/releases/tag/v9.6.0)!!

Great! Thank you so much.

**Comment by nathan1658** [comment]
> I ended up downloading the latest release from GitHub and manually installing it into vscode. Now working 🙂

Hello, I uninstalled 9.5.0 from vscode and did install 9.6.0 via the extension. I can see for following logs at prettier:
["INFO" - 10:20:22 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 10:20:22 PM] Extension Version: 9.6.0.
["INFO" - 10:20:27 PM] Formatting xxxx
["INFO" - 10:20:27 PM] Using config file at '/Users/xxxxx/.prettierrc'

But still, the singleAttributePerLine is not working for me, but it works if I run prettier via CLI i.e. prettier -w xxxxxx.vue.
Could you give me some idea on how to solve this? Thank you :)

**Comment by iSCJT** [comment]
If you look in your vscode settings under the vue editor.defaultFormatter does it have prettier listed or maybe volar?

I think I had to change one of my settings files so that prettier was listed for vue rather than volar but I can't remember 100% what I changed, sorry.

**Comment by bartoligerman497** [comment]
The functions have not been added yet, it is a function that has been under discussion for a long time in my opinion, see this thread -> [HERE](https://github.com/prettier/prettier/issues/5751)

Try install Prettier but no from VSCode, install it manually  -> [HERE](https://github.com/prettier/prettier)

Change Log -> [HERE](https://github.com/prettier/prettier-vscode/blob/main/CHANGELOG.md)
![image](https://user-images.githubusercontent.com/53313625/183944962-0a9448ee-f585-4229-b88a-ff861a4c8971.png)

**Comment by nathan1658** [comment]
> If you look in your vscode settings under the vue editor.defaultFormatter does it have prettier listed or maybe volar?
> 
> I think I had to change one of my settings files so that prettier was listed for vue rather than volar but I can't remember 100% what I changed, sorry.

Thanks for the reply🙏
Yup I'm using prettier-vscode 9.6.0, I verified that by changing the .prettierrc file settings and make sure it's reading the correct file. However singleAttributePerLine is not working for prettier-vscode 9.6.0 but it works on prettier cli 2.6.2 (of course it does😅)

**Comment by nathan1658** [comment]
> The functions have not been added yet, it is a function that has been under discussion for a long time in my opinion, see this thread -> [HERE](https://github.com/prettier/prettier/issues/5751)
> 
> Try install Prettier but no from VSCode, install it manually -> [HERE](https://github.com/prettier/prettier)
> 
> Change Log -> [HERE](https://github.com/prettier/prettier-vscode/blob/main/CHANGELOG.md) ![image](https://user-images.githubusercontent.com/53313625/183944962-0a9448ee-f585-4229-b88a-ff861a4c8971.png)

Hi, so it is not included in 9.6.0? I read the comment above so I thought it's supported with 9.6.0😅

**Comment by ntotten** [comment]
Released in 9.7.0
