### ISSUE TITLE
prettier.config.js -- wrong filename in docs

### ISSUE THREAD

**Issue by jeff-kilbride** [prettier/prettier-vscode#263]
Hi all,

Thanks for the extension!

This one had me pulling my hair out for a few minutes. The docs say the correct configuration file is `.prettier.config.js` -- however, the correct file for this format is `prettier.config.js` with no leading dot. Couldn't figure out why my config wasn't working, until I re-vistited the `prettier` site and noticed this discrepancy.

**Comment by RobinMalfait** [comment]
Thanks for the report!

Duplicate #262
