### ISSUE TITLE
Specify prettier version to be used

### ISSUE THREAD

**Issue by ismail-syed** [prettier/prettier-vscode#265]
👋  Awesome plugin!

Is there a way to specify what version of prettier the vscode plugin will run? In prettier `v1.8.0` scss map formatting was introduced. My CLI prettier uses `v1.8.2` which formats the following: 

```
// Before
$map: (color: #111111, text-shadow: 1px 1px 0 salmon)

// After
$map: (
  color: #111111,
  text-shadow: 1px 1px 0 salmon
);
```

It seems like this plugin is pinned to `v1.7.3`, so the CLI formatting get unformatted back to 
```
$map: (color: #111111, text-shadow: 1px 1px 0 salmon)
```

Can we update the plugin to use the latest prettier? I can submit a PR if this is okay to update!

**Comment by RobinMalfait** [comment]
This extension comes pre-bundled with 2 prettier modules:

- `prettier`
- `prettier-eslint` (for eslint-integration)

If you enable eslint-integration, it will use the bundled `prettier-eslint` binary.
If you however specify `prettier` as a dev/dependency inside your package.json, it will use that one.

You can verify which `prettier` version is loaded in the extension when you hover the `Prettier: ✔` in the statusbar in the bottom right corner.

**Comment by CiGit** [comment]
Bundled version updated and I think you had the correct information from @RobinMalfait.
Reopen if I'm wrong.
