### ISSUE TITLE
Feature request: add 'auto' option  support to  tabWidth 

### ISSUE THREAD

**Issue by hefei00** [prettier/prettier-vscode#267]
if the setting `prettier.tabWidth` could accept 'auto' option?  if `prettier.tabWidth` is set to 'auto', then prettier will use the editor's tab width settings. I switch between different projects with different tab width config, every time I use prettier to format my code , I need to change the settings.

**Comment by RobinMalfait** [comment]
Hello, I don't think that this is a good idea. But what you can do is the following:

In VScode when you add user settings, there is a dropdown in the top right ![](http://d.rbn.nu/SrpCvy.png) where you can switch to workspace settings. So for each project you can put the tabWidth in there and you don't have to switch it every single time. 

Is this helpful for you?

**Comment by hefei00** [comment]
@RobinMalfait thanks you! It solve my problem.
