### ISSUE TITLE
[Feature request] Options to auto-install Prettier language plugins 

### ISSUE THREAD

**Issue by jinxdash** [prettier/prettier-vscode#2671]
## **Is your feature request related to a problem? Please describe.**

The Prettier extension has terrible UX for languages supported through non-core plugins:

1. Installation requires running npm commands.
2. Once installed, requires restarting IDE.
3. Updates are manual, and again using npm commands.

_This is a complete deal-breaker for users not familiar with the javascript environment_

### New option dropdown for each language available through plugins:
  - `"latest"` - Every first time formatting the language in session, the extension attempts to update the plugin [1]
  - `"manual"` - disabled behavior
  - `"prompt"` - Asks to install plugin on first attempt to format that language (default)

### When the user attempts to format a language requiring a plugin:
  - Use the plugin if found locally
  - Use the plugin if found globally
    - `"latest"`: attempt update if this is the first time formatting that language in the session [1]
  - No plugin found:
    - `"latest"` - await exec `npm install --global <plugin-name>@latest`
    - `"manual"` - do nothing
    - `"prompt"` - `"Prettier: A plugin is available to format x, would you like to install it?"`  
      - `"Yes"`: install, change option to `"latest"`
      - `"Dismiss"`: do nothing
      - `"Never ask again"`: Change option to "manual"

[1] await exec `npm upgrade --global <plugin-name>@latest`

## **Describe alternatives you've considered**

- Bundle prettier with the plugin in a dedicated extension (e.g. svelte)

## **Additional context**

I'm the author of [`prettier-plugin-rust`](https://github.com/jinxdash/prettier-plugin-rust). I'm competing against the formatter included with the official Rust language server extension.  In order to provide a friction-less way to use Prettier with Rust, I must publish and maintain an extension myself.

**Comment by ntotten** [comment]
This really isn't the norm for vscode extensions. This extension does come with a bundled version of prettier for simple cases, but installing locally prettier and plugins with npm is the recommended approach.
