### ISSUE TITLE
Feature request: re-add the ability to specify a custom language

### ISSUE THREAD

**Issue by ericm546** [prettier/prettier-vscode#270]
In VSCode, the default JavaScript language sometime interfere with the flow extension.  

For that reason, I created a flow extension that implemented a "flow" language. It still have issues and I don't know if I will publish it, but since 0.25, I'm not able anymore to set "flow" in prettier.javascriptEnable to enable prettier on it.

**Comment by CiGit** [comment]
Those `*Enable` settings where removed mostly due to the high amount of parser prettier provides. #256 

IMO your problem lays elsewhere.

**Comment by chrisdhanaraj** [comment]
@CiGit I will say - my team was using `stylus` but with the normal CSS syntax. Prior I could use `cssEnable` to enable it on `styl`

**Comment by ntotten** [comment]
Closing due to inactively and age. Please reopen if still needed.
