### ISSUE TITLE
Format Document hotkey produces different behavior than context menu

### ISSUE THREAD

**Issue by sugardave** [prettier/prettier-vscode#2707]
Type: <b>Bug</b>

This might go beyond just the `prettier` extension, but I have not gone that far.

1. Install `prettier/prettier-vscode` extension and configure the workspace to use it as the default formatter.
2. Make sure whitespace is visible in the editor.
3. Create a config file `.prettierrc.json` at the project root with only
```json
{
  "tabWidth": 2
}
```
4. Format the config file using the context menu or command menu and confirm two spaces for the indentation.
5. Change the value to `4`.
6. Use the hotkey for formatting the document (mine is the default `Shift+Alt+F`) and confirm no change in indentation.
7. Use the context menu to select `Format Document` (verify you used the correct hotkey in 6😉) and confirm the new spacing.
8. Change back to `2` and use the context menu to format and confirm indentation change.

Things get even crazier if you click the status bar to show prettier's output, but I don't feel like documenting that madness at the moment.

Extension version: 9.8.0
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.81GB (5.17GB free)|
|Process Argv|-n .\\v2\\ --crash-reporter-id ab1fa845-097d-4793-b594-d190652a5ebf|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nickph7** [comment]
I have the same issue where the indentation gets fixed only through the command palette > format document and not the hot key. Using the hot-key still fix issues like making lists multiline, or aligning function call and assignment if it can fit into the line
