### ISSUE TITLE
`prettier.stylelintIntegration` is not fixing order imposed by `stylelint-order`

### ISSUE THREAD

**Issue by mmellado** [prettier/prettier-vscode#271]
I'm using https://github.com/hudochenkov/stylelint-order as a plugin for my stylelint configuration. I'm also using `prettier-stylelint` to set the code style for my css + scss files. When I run `prettier-stylelint` with the `--write` option on my files, the property order imposed by `stylelint-order` is respected. However, with the vscode plugin, when enabling the `prettier.stylelintIntergation` option and `editor.formatOnSave` option, the order is not being imposed on save.

I'm pretty sure I saw this working properly last week, but it doesn't seem to be working anymore. 

One change I've made to my project since was updating the prettier settings from using them inline to be picked from a `.prettierrc` file. Could this be related, or is the extension simply using an older version of `prettier-stylelint`?

**Comment by CiGit** [comment]
cc @hugomrdias

**Comment by MrMacStripe** [comment]
I've got the exact same problem. Stylelint is linting the right order in the editor but Prettier does not sort anything.

**Comment by mmellado** [comment]
I think my issue is the opposite, stylelint is sorting in command line but not through the prettier extension

**Comment by maru3l** [comment]
I'm getting the same issue. Is there any change since January? @CiGit 

I'm also getting issue with indentation. When I'm saving with the `formatOnSave` the indentation is all broken but if I'm using the CLI of `prettier-stylelint`, every goes normal.

**Comment by maru3l** [comment]
@CiGit What can I take a look to resolve this issue?

**Comment by CiGit** [comment]
@maru3l You can take a look at our usage of prettier-stylelint API vs prettier-stylelint CLI see what's different.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
