### ISSUE TITLE
There are two same extension in extension market

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier-vscode#2715]
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/41773861/190473951-09d07400-b946-4035-8f3e-292815c2492c.png">

**Comment by kidonng** [comment]
Prettier sure that's a phishing attack. Notice how this extension has a deceiving id:

```diff
- esbenp.prettier-vscode
+ espenp.prettier-vscode
```

But it seems to be removed already.

**Comment by coliff** [comment]
Perhaps would be a good idea to verify Prettier as the official publisher of the extension to help show users that this one if the official one.

Would look a bit like this:
![verified-publishers](https://user-images.githubusercontent.com/1212885/191406272-c13af85c-5570-47c4-b130-5c53b42d7c4b.png)

Details here:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher
