### ISSUE TITLE
enable stylelintIntegration with scss not work with 'prettier-stylelint'?

### ISSUE THREAD

**Issue by vegawong** [prettier/prettier-vscode#273]
i am confused for  a long time, because i can't make my editor to format my scss file crollectly even by this extension.

i try myself change my vscode config for the extension so many time but not work;

i want to format my stylesheet file by my stylelint config.

but i found that when i try to launch the extension and debug that:
https://github.com/prettier/prettier-vscode/blob/8f31fa2c2af98087d9df50f04b15100f0895a303/src/PrettierEditProvider.ts#L111

why condition include `parser === 'postcss'`,   `parser` was equaled 'scss' when i launched and debugged with scss file?   

how can i change the prettier config to make it work?

**Comment by CiGit** [comment]
Thanks for pointing it out!
There is no configuration to help you. It has to be changed in the exact line you pointed out.

`postcss` is what is used in older prettier versions (< 1.7.1, if I remember correctly) 
prettier now has multiple *style* parsers 
- 'css'
- 'less'
- 'scss'

We forgot to handle them in that case. I don't know with which ones stylelint works tho.

cc @hugomrdias

**Comment by vegawong** [comment]
Ha ha!
It is Awkward！
I want to make the code in out team has the same style by prettier with any language-lint, such eslint, tslint, stylelint etc.   
I wish that Only one editor formated key for all of the language with their own lint-config. 

Will it be changed and publiched a new version recently?
