### ISSUE TITLE
Solidity "fallback" function is cropped

### ISSUE THREAD

**Issue by aliveli186** [prettier/prettier-vscode#2736]
In solidity the following function block after formatting becomes a different function.

```
fallback (bytes calldata _input) external payable returns (bytes memory _output) {
}
```

```
fallback() external payable {
}
```

The issue seems to be solved on "prettier-solidity"
https://github.com/prettier-solidity/prettier-plugin-solidity/issues/659

Can we get an update for VS Code?

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by ntotten** [comment]
The vs code extension doesnt ship with any plugins
