### ISSUE TITLE
Change Prettier Format

### ISSUE THREAD

**Issue by MarkSky** [prettier/prettier-vscode#274]
In JavaScript file:
 `$('html, body').stop().animate({  scrollTop: $(selectPageName).offset().top, }, 600);`
I want to this:
 ```
$('html, body').stop().animate({
     scrollTop: $(selectPageName).offset().top,
 }, 600);
```

But use prettier-vscode to format:
```
$('html, body')
                .stop()
                .animate(
                    {
                        scrollTop: $(selectPageName).offset().top,
                    },
                    600,
                );
        });
```

I find in Prtttier could to set prettier-ignore [(Ignoring Code)](https://prettier.io/docs/en/ignore.html#javascript)

How could I set in VS Code? Using "prettier.ignore":  "."?
Or have other way to solve this problem?

**Comment by azz** [comment]
You can use the `// prettier-ignore` comment:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAFAcgBYwLYA2ANAAQBGEAJgJ6YCUAdAM4wQAO6jAhlAJZ5d46YAB0oJCSSZgAThAIEAKuyQkMTOAThgYABS4BzOADkueOIwgAzKxpicGrNkTEBfUgDYADF7oBuMTEAeiCSNhk4GBheOBkAWl4DKAgIsQwcfGJyKlpGFnYHHn5BOGExSSlZeSUVNXQNLR19I1NzSxs7BycXKHcSb18AqDEQIhB2aOgmZFAuFmQrLgINMbIZLjAAa0iAZTYN3igDZBgZAFc4McoIMAWllZBDjRk9dYMBO+XLkAArJgAPABC6y2uzMcAAMoc4J8HhAzjA2AiAEyw777GTPZAgMhcMjUAjQUYgcKHGAAdV4lBg2GQAA4vGNwhANOT1mwTudvhEAI5nXgRXRvD5IRZfMYaPC8TkXCWHAxaACKZwg8DRYxgeMp1NpSGRGvWvAI8oAwhA8CKQMkoDCxmcNIo8dNRfc4K5XEA

**Comment by MarkSky** [comment]
Excuse me!
I would like to know where to set 'prettier-ignore'?
In the user setting that in VS Code? (File>Preferences>Settings)

**Comment by nicu-chiciuc** [comment]
@MarkSky you have to write the comment `// prettier-ignore` before a block of code.

**Comment by MarkSky** [comment]
Yes, it work now.
Thank you.

**Comment by nicu-chiciuc** [comment]
Just try to not abuse this thing :D . I usually use it just for big configuration array in which providing my own indentation makes everything more clear.
