### ISSUE TITLE
prettier cannot be set as formatter for typescript, javascript and variations thereof (typescriptreact)

### ISSUE THREAD

**Issue by Choongkyu** [prettier/prettier-vscode#2744]
- [x] Write a summary of your issue
- [x] Include a link to a github repo that can be used to reproduce the issue or exact reproduction steps.
- [x] Provide the expected result
- [x] Provide the actual result
- [x] Include extension, os, and vs code information
- [x] Include Prettier extension log

PLEASE NOTE: Many of the issues with the extension are heavily based on your specific configuration and source code. In order to improve your chances of having your bug fixed, the number one thing you can do is create a github repository that can be used to reproduce the issue along with the detailed reproduction steps. If you don't provide this info, it is usually the case that we cannot reproduce the issue and the issue will be closed.

### Summary

When I open vs code with the prettier-vscode extension installed and enabled, and have the following in my settings.json
```
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
  },
```
and open any js or ts files and try to format them with prettier on my laptop, I get an error message like
```
Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'TypeScript React'-files
```

### Github Repository to Reproduce Issue

This, among other repos, have the same issue on my installation of vs code but not on github codespaces. Periodically, github codespaces gives me issues with prettier as well with prettier showing on the status bar. So issue may be difficult to reproduce with repo alone.

https://github.com/choongkyu/prettier-vscode-bug

### Steps To Reproduce:

1.  Open `prettier-vscode-bug/pages/_app.tsx`
2. Open command palette with command+shift+p on macos
3. select "Format Document"

### Expected result

Prettier button should show up on bottom toolbar and be shown as an option for formatters and I should not see any errors and file should proceed to be formatted.

### Actual result

I get an error message like
```
Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'TypeScript React'-files
```
and the files do not get formatted
#### prettier is not included in list of formatters to use
<img width="608" alt="Screen Shot 2022-10-08 at 10 21 51 PM" src="https://user-images.githubusercontent.com/1592194/194739493-5975b222-49c2-47a2-93e4-4beb93510c5f.png">

#### no prettier button in the bottom toolbar
<img width="687" alt="Screen Shot 2022-10-08 at 10 10 50 PM" src="https://user-images.githubusercontent.com/1592194/194739206-22f38e8f-6ddd-4deb-be98-3450cab2a8ca.png">

#### no prettier debug output even though it's enabled
https://user-images.githubusercontent.com/1592194/194739265-34a46dc4-37c5-4312-98ce-a50ad44ac405.mov

**VS Code Version**:

Version: 1.72.0 (Universal)
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:21:58.256Z (4 days ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

**Prettier Extension Version**:
9.9.0

**OS and version**:
macos 12.6

## Prettier Log Output

There's no prettier button in the bottom toolbar as shown above nor any output

**Comment by rs3d** [comment]
Same here for me esp. for 'vue'-files wit ver5sion 9.9.0.

VS Code version:
Version: 1.73.0-insider (user setup)
Commit: 8e1235ee25e3aad3598ab58016c071b5596b826a
Date: 2022-10-10T09:52:32.588Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Downgraded to version 9.8.0, which is working for me.
