### ISSUE TITLE
type detection broken in markdown file (.md)

### ISSUE THREAD

**Issue by MrTelanie** [prettier/prettier-vscode#275]
since markdown is supported in prettier there seems to be a problem in the type detection

when in setting.json: 
``` 
"editor.formatOnSave": true
```

it seems that prettier is formatting the .md like typescript or javascript.

the three backticks are moved up inside the source code, which is an indicator for me, that prettier thinks its a javascript file.

my workaround at the moment is 

```
"[markdown]": {
    "editor.formatOnSave": false
  }
```

but i really would like to use that feature for markdowns.

**Comment by azz** [comment]
What's your file extension for markdown files?

**Comment by MrTelanie** [comment]
hello
```.md```
are the markdown files

**Comment by azz** [comment]
Which version of Prettier is being used? (Hover bottom right corner)

**Comment by MrTelanie** [comment]
i only can see your plugin with version [0.25.0] with the prettier version 1.8.2
I have no idea how to influence the prettier version

**Comment by trongthanh** [comment]
Looks like this plugin is not working for current VSCode 1.19.1 + prettier-vscode 1.0 + prettier 1.9.2.

It seems that prettier is assuming **.md** files as JavaScript and throwing syntax errors in output.
For e.g.:

```
Unexpected token, expected ";" (/Users/**/README.md:1:5)
> 1 | NAU JUKEBOX
    |     ^
  2 | ===========
```

**Comment by CiGit** [comment]
Can you share a repo with all config files ? and your vscode user config ? I've no idea how this could happen. We are inferring the parser and giving it to prettier.

**Comment by ellipticaldoor** [comment]
Same here

**Comment by ntotten** [comment]
Closing as I cannot repo in the current version.
