### ISSUE TITLE
vscode format on modifications is not working with sass files with prettier

### ISSUE THREAD

**Issue by chungadesnehal1** [prettier/prettier-vscode#2752]
VScode reference ticket https://github.com/microsoft/vscode/issues/161383

Steps to Reproduce:

Go to vscode settings
click on formatting in user
select modifications option in Format on Save mode
Goto .scss file and make changes
sass files are not getting formatted

Output:
SCSS file is not formatted
Expected behavior:
SCSS file should get formatted

**Comment by bshamblen** [comment]
@chungadesnehal1 I had the same issue today. I had to perform the following steps to fix the issue:

1. Open a file with the `scss` extension. 
2. Manually initiate the "Format Document" command, using `CMD + Shift + P -> Format Document`. 
3. At that point VS Code gave me a warning message that multiple formatters were configured for `scss` files and that I needed to pick a default.
4. I selected `Prettier` from the list.
5. From then on perttier would be used as the default file formatter for `scss` files on save.
