### ISSUE TITLE
Document icon meaning

### ISSUE THREAD

**Issue by kalaracey** [prettier/prettier-vscode#2754]
**Is your feature request related to a problem? Please describe.**
The icon next to "Prettier" in the lower-right hand corner sometimes has a circle with a line through it:

<img width="578" alt="Screen Shot 2022-10-15 at 11 12 23 AM" src="https://user-images.githubusercontent.com/1745582/195994063-1aea52ad-18cd-4448-b930-8b687277aaaf.png">

and other times has two check marks. I don't know what they mean.

**Describe the solution you'd like**
Documentation of the meaning of these icons on https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode.

**Describe alternatives you've considered**
Description of their meaning when hovering over the icon.

**Additional context**
I think what may be going on is that I am editing a Python file, which I suppose Prettier does not support. In that case, perhaps "Prettier" shouldn't appear in the toolbar at all.

**Comment by TimJ0212** [comment]
I would like to take a look into that, but I am not sure how to handle the icons. The icons are from the 'Product Icon Reference' from VSC (https://code.visualstudio.com/api/references/icons-in-labels). 
It seems like there is neither an official hosting from VSC nor an easy way to show them in the markdown.
We should save the SVG files of the icons (https://github.com/PKief/vscode-material-product-icons) somewhere in the repository and shouldn't depend on someone's hosting. 

Should we add another directory to the repository root?
