### ISSUE TITLE
Can't format class attribute when format "typescript" files

### ISSUE THREAD

**Issue by stand-unshaken** [prettier/prettier-vscode#2755]
This space can't be delete when i use prettier.forceFormatDocument(format file).
![image](https://user-images.githubusercontent.com/63765067/195994648-e881f2bb-be05-4775-8a95-2b7e5ce49cd1.png)

This prettier log.

["INFO" - 23:30:26] Forced formatting will not use ignore files.
["INFO" - 23:30:26] Formatting file:///d%3A/Project/vue-ts/src/views/login/index.tsx
["INFO" - 23:30:26] Using ignore file (if present) at d:\Project\vue-ts\.prettierignore
["INFO" - 23:30:26] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 23:30:26] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 23:30:26] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\Project\\vue-ts\\src\\views\\login\\index.tsx",
  "parser": "typescript"
}
["INFO" - 23:30:26] Formatting completed in 13ms.

**Comment by stand-unshaken** [comment]
file type is .tsx

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
