### ISSUE TITLE
.prettierignore not work for yml file

### ISSUE THREAD

**Issue by zzswang** [prettier/prettier-vscode#278]
.prettierignore

```
.travis.yml
```

but it still format .travis.yml file anyway ...

**Comment by natew** [comment]
I'm getting this as well, .prettierignore in my root but it still formats the file.

**Comment by RobinMalfait** [comment]
I think that it is either the default formatter or another formatter because prettier doesn't support yaml yet as far as I know.

**Comment by azz** [comment]
This extension will never run on YAML files so it's likely the default formatter that is running. 

If you want to turn off all formatting on save for YAML you can add 

```json
    "[yaml]": {
        "editor.formatOnSave": false
    }
```

**Comment by zzswang** [comment]
When we say default formatter, is it the one coming along with vscode by default?

But If we turn off this extension, .travis.yml will not be formatted any more.

**Comment by natew** [comment]
Oh for the record I was seeing this on JSON files with vscode. Ill open a
new ticket.
