### ISSUE TITLE
.prettierignore is not working

### ISSUE THREAD

**Issue by infctr** [prettier/prettier-vscode#279]
I know it has been a long awaited feature but I can't seem to make it work.  
I have a simple .prettierignore config that is consumed and applied as expected from cli, but the extension keeps formatting files in the editor. 

```
app/modules/
app/root/
app/utils/
webpack/
tools/
config/
server/
package.json
```

prettier is installed globally in my setup 

```bash
❯ prettier --v
1.8.2

❯ code --version
1.18.1
929bacba01ef658b873545e26034d1a8067445e9
```

Am I doing anything wrong?
Is there any way I can log extension formatting for debug purposes?

**Comment by natew** [comment]
Was just going to open this same one. I have:

```
apps/**/package.json
packages/**/package.json
```

But saving any package.json inside one of those folders doesn't work.

**Comment by MatejMazur** [comment]
The same problem..

**Comment by azz** [comment]
- are you using multi root?
- what is the path to the ignore file and the path to the workspace directory?

**Comment by MatejMazur** [comment]
@azz 
- No, I'm not using multi root.
- The .prettierignore is stored in the root of the project.

**Comment by infctr** [comment]
the same 
- no multi root
- the `.prettierignore` and `.prettierrc` are both in the root of the project

**Comment by CiGit** [comment]
Quickly tested, 

Seems we need to pass a relative to `.prettierignore` path
https://github.com/prettier/prettier-vscode/blob/master/src/ignoreFileHandler.ts#L24

Currently works well for simple ignore which starts with a <kbd>*</kbd> like 
- `**/a/b/x.js`
- `*.js`

**Comment by infctr** [comment]
@CiGit  yep, that works. wildcards could be a workaround for now

**Comment by azz** [comment]
Something like #280? Unable to reproduce locally but I must be doing something wrong.

**Comment by jerlam06** [comment]
2019, and .prettierignore still doesn't work...

**Comment by nshoes** [comment]
I mean, I'm all -1'ing an unhelpful comment as the next developer, but this really doesn't work. `prettier@1.18.2`. Trying ignore an xml file in the root of my app. These don't work:

```
config.xml
/config.xml
./config.xml
*.xml
```

What am I doing wrong?

**Comment by bdares** [comment]
Definitely not working.

.prettierrc contents of:
```
db/entities/*
```

prettier output complains of:
```
db/entities/store_items.js
   5:63  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
```

**Comment by nshoes** [comment]
@bdares where'd you snag that output?

**Comment by PaulMest** [comment]
Yeah, it appears that `.prettierignore` does not work at all for me either in a monorepo. Prettier goes through everything in `node_modules`. I've even tried adding `.eslintignore` which did not help.

I'm hoping that these changes land https://github.com/prettier/prettier/pull/6203/files and will fix the problems my team is having.

**Comment by SGCMarketing** [comment]
Not working for me either - I can't get either .prettierignore or // prettier-ignore to work for me.

**Comment by paradoxinversion** [comment]
Has this been moved to another issue? .prettierignore still does not seem to be working.

**Comment by trickstival** [comment]
It is not working for me either

**Comment by Elliot128** [comment]
Still not working for me. Format on save doesn't respect the `.prettierIgnore` file.

**Comment by moklick** [comment]
For me the problem was the I had another beautifier ("Beautify") installed which formatted the code on save. The problem could be solved by disabling it and reloading vs studio code #440 #439

**Comment by ntotten** [comment]
We have changed how the ignore files are processed and resolved, if somebody has a chance please try to repro this with the preview of version 3.0: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

Also, if somebody can provide a github repro sample i can use to reproduce this issue, that would help as well.

**Comment by philip-swrve** [comment]
This works for me
```
Prettier: Ignore Path (in vscode)
~/.prettierignore
```
Contents of ~/.prettierignore

```
**/folder-to-exclude/**/*
```
