### ISSUE TITLE
It doesn't auto format.

### ISSUE THREAD

**Issue by Jessepinkman412** [prettier/prettier-vscode#2792]
No matter how I write my codes the extension just saves them. It does not make it look nicer. For instance, 

![Screenshot (2)](https://user-images.githubusercontent.com/118404560/202326556-e83bf376-257d-4759-9e20-96a17c9eb97b.png)
See? The extension does not change the formation. It just stays that way.

**Comment by cyrus01337** [comment]
I'd recommend remaking the issue with the issue template and following the necessary steps, they help diagnose what the problem actually is and can paint the solution for you sometimes if this is still a problem you are having.

**Comment by Jessepinkman412** [comment]
This issue has been resolved.
