### ISSUE TITLE
Outdated prettier version (upgrade to 2.8)

### ISSUE THREAD

**Issue by TenType** [prettier/prettier-vscode#2797]
### Summary

Using the new TypeScript [`satisfies` operator](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#satisfies) causes the extension to throw an error. This has already been fixed with the release of [Prettier 2.8](https://prettier.io/blog/2022/11/23/2.8.0.html), but this extension is outdated.

### Github Repository to Reproduce Issue
```ts
const x = 1 satisfies number;
```

### Steps To Reproduce:

1.  Paste the code snippet into Visual Studio Code with TypeScript 4.9 and format the code with the prettier extension.

### Expected result

The file should be formatted.

### Actual result

Crashes with:
```
["ERROR" - 6:02:44 PM] Error formatting document.
["ERROR" - 6:02:44 PM] ',' expected. (1:13)
> 1 | const x = 1 satisfies number;
    |             ^
SyntaxError: ',' expected. (1:13)
> 1 | const x = 1 satisfies number;
    |             ^
```

### Additional information

**VS Code Version**: 1.73.1

**Prettier Extension Version**: 9.9.0

**OS and version**: macOS Big Sur 11.6

**Comment by ntotten** [comment]
Updated in version 9.10.0
