### ISSUE TITLE
Files are formatted for which the extension is not enabled.

### ISSUE THREAD

**Issue by alkatar21** [prettier/prettier-vscode#2813]
### Summary
I only want to format typescript files, but currently all files are formatted, although there is the possibility to set this in the settings.

### Steps To Reproduce:

1. Add the following to the  workspace settings and save:
```jsonc
{
    "editor.formatOnSave": true,
    "editor.defaultFormatter": null,
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "json.format.enable": false,
}
```
2.  Actually only typsecript files should be formatted, but at least also JSON files, like the settings.json itself are formatted.

### Expected result

To only format typescript files, as the README promises (https://github.com/prettier/prettier-vscode#default-formatter).

### Actual result

Files like JSON files are also formated.

**VS Code Version**:

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Prettier Extension Version**: v9.10.3

**OS and version**: Ubuntu 20.04

## Prettier Log Output

```
["INFO" - ] Extension Name: esbenp.prettier-vscode.
["INFO" - ] Extension Version: 9.10.3.
["INFO" - ] Formatting file:///path/.vscode/settings.json
["INFO" - ] Using ignore file (if present) at /path/.prettierignore
["INFO" - ] File Info:
{
  "ignored": false,
  "inferredParser": "json"
}
["INFO" - ] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" -] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/path/.vscode/settings.json",
  "parser": "json"
}
["INFO" - ] Formatting completed in 106ms.
```

**Comment by ntotten** [comment]
This is a VSCode or settings issue. Somehow the formatter is being called. To force prettier to ignore certain files you can use `.prettierignore` or explicitly set a new formatter. I'm not sure if setting a formatter to null has any effect in VSCode, but you'd have to check with their docs.
