### ISSUE TITLE
Conflicts with eslint-graphql-plugin 

### ISSUE THREAD

**Issue by dmiranda2791** [prettier/prettier-vscode#282]
Hi!
I'm using `eslint-graphql-plugin` to validate `.gql` files and I get this error when formatting any file.

![image](https://user-images.githubusercontent.com/4513830/33618839-415b08ee-d9a9-11e7-9474-1909ba32ab18.png)

I think that prettier is looking the .json file in the same directory as the document being formatted but the actual file is in the root of my project.

This is the config on `.eslintrc`

![image](https://user-images.githubusercontent.com/4513830/33619022-b7570426-d9a9-11e7-9e87-8fc9984926b1.png)

**Comment by CiGit** [comment]
Hello, I don't know that plugin, but from the doc 
> `schemaJsonFilepath`: The **absolute** path to your schema as a .json file.

**Comment by CiGit** [comment]
Stalled
