### ISSUE TITLE
Have to reinstall plugin-ruby every time I reset computer or start a new project in order to format ruby files (WSL2 + Ubuntu)

### ISSUE THREAD

**Issue by OmerMessing** [prettier/prettier-vscode#2821]
Hi,

I'm using WSL2 with Ubuntu 22.04, every time I reset the computer or create a new project I have to reinstall prettier and plugin-ruby for VS code to actually format the file. If I try to format the file prior to reinstalling, VS code says:
"There is no formatter for ruby files installed."

After I reinstall using the following command it works fine:
npm install --save-dev prettier @prettier/plugin-ruby

**VS Code version**:
1.74.0

**Prettier Extension Version**:
9.10.3

**OS and version**:
Windows 10 Pro 21H2

**Comment by OmerMessing** [comment]
Update: I might have solved it. I installed plugin-ruby inside the prettier folder in Ubuntu, I thought that's what I initially did. Will keep you posted.

**Comment by OmerMessing** [comment]
Update: I just pulled a new ruby project in git, and the formatting doesn't work.

This is the error log for prettier:

Error: Error: connect ECONNREFUSED /tmp/prettier-ruby-parser-22979.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/prettier-ruby-parser-22979.sock'

**Comment by ntotten** [comment]
This doesnt seem to have anything to do with this extension

**Comment by OmerMessing** [comment]
@ntotten Well, I initially posted it in the plugin-ruby repo but the creator insisted I open another issue in this repo, but he eventually reopened the issue so I guess it's handed back to him.
