### ISSUE TITLE
feat: add ability for `trailingComma` to add a comma to single-line comma-separated syntactic structures.

### ISSUE THREAD

**Issue by damonholden** [prettier/prettier-vscode#2824]
While I can understand the reason for the multi-line-only functionality of the `trailingComma` option, it would be really nice to be able to add the formatting to single-line comma-separated syntactic structures as well. This practice can address errors in code such as where `const coolWords = ['radical', 'mathematical', varThatStoresCoolWord];`, a change such as `const coolWords = ['radical', 'mathematical', varThatStoresCoolWord ('legen' + 'dary')];` would turn `varThatStoresCoolWord` into a function invocation, and display no syntax errors. In addition, its just better logic to say trailing commas **all the time**, rather than trailing commas **sometimes**.

So, for example, with the following line of JavaScript:

```
  const fruits = ['banana', 'watermelon', 'mango'];
```

…a Prettier format including the the following option:

```
//…
trailingComma: "<es5|all>"
//…
```

…should result in:

```
  const fruits = ['banana', 'watermelon', 'mango',];
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by damonholden** [comment]
Apologies, will open this issue at [https://github.com/prettier/prettier]( https://github.com/prettier/prettier) now.
