### ISSUE TITLE
Prettier settings not applied to eslint-plugin-prettier

### ISSUE THREAD

**Issue by shinebayar-g** [prettier/prettier-vscode#2825]
### Summary

Prettier settings of VSCode is not recognized by `eslint-plugin-prettier`. I'm not sure if it belongs here or at https://github.com/prettier/eslint-plugin-prettier, feel free to move to appropriate place.

### Github Repository to Reproduce Issue

See reproducible steps.

### Steps To Reproduce:

1. Create Typescript NextJS project (e.g `npx create-next-app@latest --experimental-app`)
2. Install this extension
3. Install dependencies
```
npm install --save-dev eslint-plugin-prettier eslint-config-prettier prettier
```
4. Edit `.eslintrc.json` provided by next.js to enable prettier plugin settings.
```json
{
    "extends": ["next/core-web-vitals", "plugin:prettier/recommended"]
}
```
5. Apply custom Prettier settings through VSCode `settings.json`
```json
    "prettier.printWidth": 120,
    "prettier.tabWidth": 4,
    "prettier.jsxSingleQuote": true,
    "prettier.singleQuote": true,
```
6. Restart VSCode to make sure that proper changes are loaded.
7. Open any `.tsx` file.
8. Plugin throws errors like 
```
Replace `'@next/font/google'` with `"@next/font/google"`eslint[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)
```

### Expected result

Prettier settings applied through VSCode settings work same as `.prettierrc` file.

### Actual result

VSCode Prettier settings are ignored by `eslint-plugin-prettier`. Only local `.prettierrc` works.

### Additional information

Related: https://github.com/prettier/eslint-plugin-prettier/issues/102

**VS Code Version**:

```
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

**Prettier Extension Version**:

**OS and version**:

```
MS Windows 11 Version 22H2 (OS Build 22621.963)
```

## Prettier Log Output

```
["INFO" - 11:52:19 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 11:52:19 PM] Extension Version: 9.10.3.
["INFO" - 11:52:27 PM] Formatting file:///redacted/app/layout.tsx
["INFO" - 11:52:27 PM] Using ignore file (if present) at /redacted/.prettierignore
["INFO" - 11:52:27 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 11:52:27 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 11:52:27 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": true,
  "printWidth": 120,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 4,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/redacted/app/layout.tsx",
  "parser": "typescript"
}
["INFO" - 11:52:27 PM] Formatting completed in 178ms.

```

**Comment by ntotten** [comment]
This is a bug for either the eslint extension or the library.

**Comment by shinebayar-g** [comment]
Cool, can you move to appropriate place?
