### ISSUE TITLE
As the license is MIT, is it possible to make it available also for VSCodium?

### ISSUE THREAD

**Issue by ZahraBoroujeni** [prettier/prettier-vscode#2851]
**Is your feature request related to a problem? Please describe.**
I cannot see the extension available in VSCodium. VSCodium is MIT version of VSCode.

**Describe the solution you'd like**
As the license of the extension is MIT, is it possible to make it available also in https://open-vsx.org/ ?
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Comment by uhlhosting** [comment]
@ZahraBoroujeni do not even. try to ask anything, just bunch of ignorant pricks who dont even bother to reply.  waste of time, seek other alternatives.

**Comment by ntotten** [comment]
The MIT license allows this.
