### ISSUE TITLE
Couldn't resolve parser "less"

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier-vscode#286]
In one of my projects, the extension doesn't format LESS files. In the Output window I get these messages:
```
2017-12-7 16:16:17:
-------------------
Couldn't resolve parser "less"
```
If I open an empty project and create a LESS file there, it works. What can cause this?

**Comment by CiGit** [comment]
I would say, you have prettier installed in your project and a "parser" key in your prettier config

**Comment by thorn0** [comment]
Yes, I had prettier 1.7.0 installed, without a config though. Upgrading it solved the issue. Thanks!
