### ISSUE TITLE
the creation of `node_modules/.cache/prettier` should be better

### ISSUE THREAD

**Issue by loynoir** [prettier/prettier-vscode#2861]
### Summary

I use `yarn2`, which have no `node_modules`.
I use `esbenp.prettier-vscode`, which create a three level empty directory, `node_modules/.cache/prettier`.
It looks very ugly to me.
```txt
node_modules
└── .cache
    └── prettier

3 directories, 0 files
```

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

https://yarnpkg.com/getting-started/install

### Expected result
Don't create a three level empty directory. 

If `node_modules` not exists, don't create it.

Alternatively, there should be a vscode setting option for prettier cache location.

### Actual result
Created a three level empty directory.
```txt
node_modules
└── .cache
    └── prettier

3 directories, 0 files
```

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**Prettier Extension Version**: v9.10.4

**OS and version**:

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREENSHOT, COPY AND PASTE THE TEXT
```

**Comment by ntotten** [comment]
This extension doesn't create that folder, this might be done by prettier library itself. You may want to open an issue on the prettier core repo.
