### ISSUE TITLE
FormatOnSave adds an unnecessary forward slash at the end of void HTML elements like "link", "img", "meta".

### ISSUE THREAD

**Issue by InNominePatris** [prettier/prettier-vscode#2868]
### Summary

It seems to, when formatOnSave feature is active, it adds a forward slash (/) at the end of any void HTML element like (link, meta. img). That should't happen because the HTML reference provided by the W3C establishes that every void element must not have a forward slash at the end of the closing greater than symbol (>).

### Github Repository to Reproduce Issue

https://github.com/prettier/prettier-vscode

### Steps To Reproduce:

1.  Go to format settings.
1.  Check the box of (Editor: Format on Save).
1. located in the file press ctrl + s to save changes and format using default formatter (prettier).

### Expected result:
```
<meta charset="utf-8">
<img src="images/drinks.gif" alt="Drinks">
<link rel="stylesheet" href="lounge.css">
```
### Actual result:
```
<meta charset="utf-8"/>
<img src="images/drinks.gif" alt="Drinks"/>
<link rel="stylesheet" href="lounge.css"/>
```
### Additional information
[Meta tag reference](https://www.w3schools.com/tags/tag_meta.asp)
[img tag reference](https://www.w3schools.com/tags/tag_img.asp)
[Linkl tag reference](https://www.w3schools.com/tags/tag_link.asp)

**1.75.0**: vs code version

**v9.10.4**: prettier version

**Windows 11** Operative System

## Prettier Log Output

```
["INFO" - 10:34:50 PM] Formatting file:///c%3A/Users/crist/Desktop/HTML%20practices/chapter7/lounge-complete.html
["DEBUG" - 10:34:50 PM] Using bundled version of prettier.
["INFO" - 10:34:50 PM] Using ignore file (if present) at c:\Users\crist\Desktop\HTML practices\.prettierignore
["INFO" - 10:34:50 PM] File Info:
{
  "ignored": false,
  "inferredParser": "html"
}
["INFO" - 10:34:50 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 10:34:50 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "c:\\Users\\crist\\Desktop\\HTML practices\\chapter7\\lounge-complete.html",
  "parser": "html"
}
["INFO" - 10:34:50 PM] Formatting completed in 59ms.
```

**Comment by ntotten** [comment]
This is by design with prettier.
