### ISSUE TITLE
Jump to end of file when formating huge JS file

### ISSUE THREAD

**Issue by x0vr** [prettier/prettier-vscode#2883]
Hi 👋

I think thi behavior occurs since ~Feb 2023.
When I configure VSCode to use for instance "editor.defaultFormatter": "vscode.typescript-language-features" , the issue is gone.

I am using "Prettier - Code formatter" v9.10.4

### Summary

When formating a huge JavaScript file in VSCode using Prettier as default formatter, everytime (most of the time?) I format the document the editor jumps to the end of the file (last line).

### Steps To Reproduce:

1. Open a huge / larger JavaScript file in VSCode
2. Add some blank lines in the code
3. Format document
4. Editor jumps to end of file (last line)

### Expected result

Document should be formatted and the line position in editor should not be changed.

### Actual result

Editor jumps to end of file (last line)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.75.1

**Prettier Extension Version**: 9.10.4

**OS and version**: Win10

## Prettier Log Output

```
["DEBUG" - 3:19:27 PM] Using bundled version of prettier.
["INFO" - 3:19:30 PM] Formatting file:///d%3A/__GIT/_testing/debug/test.js
["DEBUG" - 3:19:30 PM] Using bundled version of prettier.
["INFO" - 3:19:30 PM] Using ignore file (if present) at d:\__GIT\_testing\.prettierignore
["INFO" - 3:19:30 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 3:19:30 PM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 3:19:30 PM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 180,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 4,
  "trailingComma": "es5",
  "useTabs": true,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\__GIT\\_testing\\debug\\test.js",
  "parser": "babel"
}
["INFO" - 3:19:31 PM] Formatting completed in 495ms.
```

Thanks for checking 👍

**Comment by kongku** [comment]
I have the same situation

**Comment by DeoThemes** [comment]
Same issue but with an HTML file, not only JS

**Comment by ralfhandl** [comment]
Same issue, size limit seems to be ~100 KB for JS files.

Had this issue with a JS file of 101 KB, problem vanished after refactoring it to 97 KB.

Maybe this is a feature and not a bug, enticing us to use smaller files 😄

**Comment by wangstar615** [comment]
I had the same problem  😩

**Comment by sbikosfp** [comment]
Yep this issue still exists. It's kinda annoying. I had to disable format on save because of this. 
Is there an estimated date of fixing?

**Comment by ralfhandl** [comment]
Issue still exists, workaround is keeping source files small, which is somewhat painful if I just want to add another test case that thematically belongs into the file that would get too large.

**Comment by ralfhandl** [comment]
Issue still exists

**Comment by mustafa-colakoglu** [comment]
issue still exists

**Comment by bookmountain** [comment]
Hi guys, I found this may be a fix, paste this in the `settings.json`.

```json
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
},
```

**Comment by syvuilliot** [comment]
yes, very annoying issue

**Comment by syvuilliot** [comment]
> Hi guys, I found this may be a fix, paste this in the `settings.json`.
> 
> ```json
> "editor.codeActionsOnSave": {
>     "source.fixAll.eslint": true
> },
> ```

doesn't work for me

**Comment by mustafa-colakoglu** [comment]
> > Hi guys, I found this may be a fix, paste this in the `settings.json`.
> > ```json
> > "editor.codeActionsOnSave": {
> >     "source.fixAll.eslint": true
> > },
> > ```
> 
> doesn't work for me

Hi, can you try "endOfLine": "auto"

**Comment by syvuilliot** [comment]
> > > Hi guys, I found this may be a fix, paste this in the `settings.json`.
> > > ```json
> > > "editor.codeActionsOnSave": {
> > >     "source.fixAll.eslint": true
> > > },
> > > ```
> > 
> > 
> > doesn't work for me
> 
> Hi, can you try "endOfLine": "auto"

I tried with following settings
  "eslint.codeActionsOnSave.mode": "problems",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "prettier.endOfLine": "auto"

but always the same behaviour on large files with cursor moving to end of file :-(

**Comment by mustafa-colakoglu** [comment]
> > > > Hi guys, I found this may be a fix, paste this in the `settings.json`.
> > > > ```json
> > > > "editor.codeActionsOnSave": {
> > > >     "source.fixAll.eslint": true
> > > > },
> > > > ```
> > > 
> > > 
> > > doesn't work for me
> > 
> > 
> > Hi, can you try "endOfLine": "auto"
> 
> I tried with following settings "eslint.codeActionsOnSave.mode": "problems", "editor.codeActionsOnSave": { "source.fixAll.eslint": true }, "prettier.endOfLine": "auto"
> 
> but always the same behaviour on large files with cursor moving to end of file :-(

Hi, my configurasyon file I just added endOfLine auto and fixed, I did not add other configurations. Maybe you should remove other configurations

**Comment by ralfhandl** [comment]
Issue still exists, and is still annoying.

**Comment by Infinite-3D** [comment]
The limit of 100kb (100,000) bytes seems to be hardcoded [here](https://github.com/microsoft/vscode/blob/f125afbc800ec611f5a9ab1333c769832ce424b3/src/vs/editor/common/services/editorSimpleWorker.ts#L492).

It would be nice if there was a setting to increase this.

**Comment by cjbeattie** [comment]
Still exists. Super annoying.

**Comment by inbflat** [comment]
Still Happening

**Comment by costaluu** [comment]
Still happening (up)

**Comment by jacksonthall22** [comment]
Having this issue too, extension is basically unusable right now :'(

**Comment by x0vr** [comment]
The behavior can be reproduced with this document, for example:
https://github.com/turbulenz/turbulenz_engine/blob/master/tslib/canvas.ts

-> Just add a line at the beginning and format document => Editor jumps to eof

**Comment by Infinite-3D** [comment]
I think this is a VSCode issue rather than a Prettier one. The same thing happens with other formatters such as [CSharpier ](https://github.com/belav/csharpier) and the 100k limit is hardcoded in VSCode itself.

**Comment by arcnid** [comment]
How is this still an ongoing thing? I have tried adjusting my settings.json with no luck. I'm moving to Zed, lol

**Comment by inbflat** [comment]
I was able to fix this by setting End of line to auto in prettier settings.

**Comment by Droniukas** [comment]
Seems like none of these fixes work, would be useful to be able to extend the size limit for files...

**Comment by vital487** [comment]
Same problem here...

**Comment by brendansiow** [comment]
I have the same issue but with Go's code, I have uninstalled prettier and turn off format on save, not working

**Comment by rschlack** [comment]
Same issue here.  It's so annoying.  I think it only happens on the Windows version of VSCode.

**Comment by webdev4422** [comment]
> I was able to fix this by setting End of line to auto in prettier settings.

Fix for me too.
In VSCode `settings.json` -> `"prettier.endOfLine": "auto"`

System info: macOS Sonoma 14.4, VSCode v1.87, Prettier v10.4.0

**Comment by FacundoBrum16** [comment]
don't work for me

**Comment by StevenCrocker** [comment]
So this seems to be the issue, at least in my testing.  The end of line character in prettier setting must match the document end of line setting.

The end of line character for Prettier is defaults to "LF" if "prettier.endOfLine" isn't specifically set.  You can set this to "auto", or you can update the document itself to use "LF" instead of "CRLF". Do this by searching for "Change End of Line Sequence" in the command prompt (CTRL+SHIFT+P).  This can also be changed by clicking the CRLF text in the status bar.

Can anyone confirm?

**Comment by eduardoldev** [comment]
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "prettier.endOfLine": "auto"

**Comment by alonemanuel** [comment]
> So this seems to be the issue, at least in my testing. The end of line character in prettier setting must match the document end of line setting.
> 
> The end of line character for Prettier is defaults to "LF" if "prettier.endOfLine" isn't specifically set. You can set this to "auto", or you can update the document itself to use "LF" instead of "CRLF". Do this by searching for "Change End of Line Sequence" in the command prompt (CTRL+SHIFT+P). This can also be changed by clicking the CRLF text in the status bar.
> 
> Can anyone confirm?

Fixed it for me

**Comment by PradipBakutra** [comment]
> > > Hi guys, I found this may be a fix, paste this in the `settings.json`.
> > > ```json
> > > "editor.codeActionsOnSave": {
> > >     "source.fixAll.eslint": true
> > > },
> > > ```
> > 
> > 
> > doesn't work for me
> 
> Hi, can you try "endOfLine": "auto"

Yeah, i added
endOfLine: auto
in my .prettierrc file and it worked thanks a lot man.

**Comment by soham1300** [comment]
For me, adding "prettier.endOfLine": "auto" to settings.json resolved the issue
