### ISSUE TITLE
Prettier should prepend all its commands with `Prettier: `

### ISSUE THREAD

**Issue by thernstig** [prettier/prettier-vscode#2886]
**Is your feature request related to a problem? Please describe.**
As can be seen here, I have no idea from where `Format Document (Forced)` comes from i.e. from which extension. This is problematic, as I use Prettier for most formatting, but for some other languages I use another.

![image](https://user-images.githubusercontent.com/30827238/221896585-8e26694e-12e2-49f5-bd43-e6f9fcd70d83.png)

**Describe the solution you'd like**
Prepend all commands the extension adds with `Prettier: `.

**Describe alternatives you've considered**
None

**Additional context**
I have had real problems with this not knowing what formats documents in some cases when selecting `Format Document (Forced)` and recently just realized it is used only for Prettier.

**Comment by ntotten** [comment]
I am open to this, but would like to get some more feedback as this is a "Breaking change".

**Comment by thernstig** [comment]
Adding some more info here, in that most other extensions does this. Check e.g. for ESlint:

![image](https://user-images.githubusercontent.com/30827238/233623057-34ed217b-26b4-4f09-94e9-ff699a3cdf58.png)

**Comment by thernstig** [comment]
Unstale

**Comment by thernstig** [comment]
@ntotten do you still think this is a good idea?
