### ISSUE TITLE
Tab width setting no longer obeyed in VS Code setting file

### ISSUE THREAD

**Issue by nhustak** [prettier/prettier-vscode#289]
These at the settings I use in the vs code setting file.

  "prettier.singleQuote": true,
  "prettier.tabWidth": 4

Up until today, they were working.  They are now using a value of 2.   The singleQuote option still works.

**Comment by CiGit** [comment]
Do you have an editorconfig file ?

**Comment by nhustak** [comment]
Well apparently Angular CLI created one for me and there you go, it appears the indent_size is set to 2.   So this value is now set in at least 3 places.   The default for VS Code is 4,  I have prettier set to 4 and the .editorconfig has apparently been 2 this whole time.   Strange it suddenly started causing a problem only yesterday - I checked the log on the editorconfig and this file hasn't changed since july of this year.

I know there are editorconfig extensions for VS Code - I can't find if it supports editor config out of the box.   I don't have any of those extensions installed.  Was there a recent change to have Prettier use the editorconfig as the source of truth and VS Code simply isn't using it perhaps?   

In any case, this has fixed my issue.
Thank you!!!

**Comment by jankalfus** [comment]
It looks like Prettier has suddenly started preferring .editorconfig settings over settings in VS Code. It would be a good idea to mention this somewhere.

**Comment by CiGit** [comment]
We use prettier's resolveConfig which reads your editorconfig. I've just mentioned it in the release notes.
We should put a line on that in the readme.
PR Welcome!
code is : https://github.com/prettier/prettier-vscode/blob/067545ed33fd1d82dea38edaceef2bf09b8d840e/src/PrettierEditProvider.ts#L37-L63

**Comment by nhustak** [comment]
Cool.    Man this can get confusing with extensions are using the editor config and the _editor_ is not.   It was driving me nuts getting a 4 space tab when I was working mixed in with the prettier 2 space tab every time I saved.

**Comment by CiGit** [comment]
It was a feature request, reading the editorconfig file. Prettier does it, so we do.
I'll let this opened for now, until we have updated the readme

**Comment by ayyash** [comment]
I don't understand, is there something we can do to ignore prettier's configuration?

**Comment by CiGit** [comment]
Which config do you want to ignore?

**Comment by ayyash** [comment]
honestly? I forgot. I think I had vscode settings and .editorconfig playing together nicely, but prettier as said above prefers .editorconfig, so I ended up commenting out
```
indent_size = 2
```
from .editorconfig

**Comment by CiGit** [comment]
If you have a prettier config file next to your editorconfig with a tabwidth setting, it will be prefered.
closing as this is now documented https://github.com/prettier/prettier-vscode#prettiers-settings
