### ISSUE TITLE
Prettier formatting on save with a Turborepo monorepo

### ISSUE THREAD

**Issue by remy90** [prettier/prettier-vscode#2895]
**Is your feature request related to a problem? Please describe.**
Using a monorepo should format workspaces at the 'parent' level. I'm not sure if this already exists with other solutions (lerna, etc) but i'm using a [basic turborepo template](https://github.com/vercel/turbo/tree/main/examples/basic) and I'm not getting any formatting on save. My settings.json looks like this:

My `.vscode/settings.json` looks like this:

 ```json
{
  "eslint.packageManager": "pnpm",
  "eslint.workingDirectories": [
    "apps",
    "packages"
  ],
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "prettier.printWidth": 100,
  "prettier.arrowParens": "avoid",
  "prettier.enable": true,
  "prettier.endOfLine": "lf",
  "prettier.jsxSingleQuote": false,
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.organizeImports": true
  },
}
```

**Describe the solution you'd like**
I would like to format the file when I click save

**Describe alternatives you've considered**
I've tried adding prettier at the workspace level, rather than how the template has declared prettier at root level

**Additional context**
```json
"prettier-vscode": "9.10.4",
"prettier": "latest",
"turbo": "^1.8.3"
"node":  "16.18.1",
"pnpm": "7.27.1"
```
I also have two ticks, with the debug logs suggesting its loaded successfully as the default formatter.

**Comment by remy90** [comment]
Turns out the issue was relating to `editor.defaultFormatter`. This didn't suffice, I added manual entries for a list of others, e.g.:

 ```json
"[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
```

 and this managed to resolve the issue.

I'd close this but I'm not sure this is necessarily expected?

**Comment by ntotten** [comment]
I am not certain if this is a bug in prettier or VSCode, but if you could post a sample repository, that would allow me to test. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).
