### ISSUE TITLE
Disable formatting when using Replace in Files

### ISSUE THREAD

**Issue by swrobel** [prettier/prettier-vscode#2906]
**Is your feature request related to a problem? Please describe.**
When I'm doing a bulk find & replace across my entire project, it seems strange to me that prettier formats all of the files, for example, if I'm just replacing a single string. 
<img width="282" alt="Screenshot 2023-03-14 at 4 09 52 PM" src="https://user-images.githubusercontent.com/157270/225162146-a806760c-449d-414c-aea0-80605efb2d2e.png">

**Describe the solution you'd like**
Default behavior to not format when running replace over multiple files if formatOnSave is set to true. Alternatively, an option to disable this behavior.

**Describe alternatives you've considered**
Disabling formatOnSave altogether

**Comment by ntotten** [comment]
This is a behaviour of VSCode. not something the extension can change
