### ISSUE TITLE
CSS selector in style tag mixed with PHP

### ISSUE THREAD

**Issue by ksvhlm** [prettier/prettier-vscode#2915]
I've been running into this a lot lately, trying to make dynamic class names etc.
Looks like this in VS Code (red text makes it look like an error):
![image](https://user-images.githubusercontent.com/93324476/225901618-dfb3cab9-665d-4eb4-87db-2744445b9057.png)

So when I make the VS Code extension format the document, the next selector in line after the closing php tag gets pushed next to the closing php tag, even if I had a space between (I want it to be selector li::marker, not selectorli::marker) 

Looks like this:

`<style>
			.blog-posts-builder-item-<?php echo $id; ?>li::marker {
/* code here */
</style>`

What I want it to format to:

`<style>
			.blog-posts-builder-item-<?php echo $id; ?> li::marker {
/* code here */
</style>`

Output in devtools should like:
![image](https://user-images.githubusercontent.com/93324476/225906109-c78a4116-829f-4ec7-8b6a-b4fd38689f61.png)
but ends up like
![image](https://user-images.githubusercontent.com/93324476/225906150-d1cd3b32-a8cd-4bba-ab13-47055ebe04e5.png)

**Comment by ntotten** [comment]
Looks like an issue with the prettier PHP plugin.
