### ISSUE TITLE
prefer node_modules version of prettier instead of bundled version

### ISSUE THREAD

**Issue by krystofbe** [prettier/prettier-vscode#293]
Documentation says
```
Prettier resolution

This extension will use prettier from your project's local dependencies. Should prettier not be installed locally with your project's dependencies, a copy will be bundled with the extension.
```

If i add prettier to my local dependencies after installing the extension, the local prettier will be ignored. Instead, the bundled version will be used. I think it would be better, if the extensions checks for a prettier in local dependencies all the time, not only after installation.

**Comment by CiGit** [comment]
It does check every time you format. It may hit node's cache. If you reload/restart vscode doesn't this extension pick your local prettier?

**Comment by bardware** [comment]
I see this issue being open some time. I'm in the process of getting accustomed to this plugin and I noticed the same behaviour.
I open a JS file and the staus bar reads `Prettier` I save the file and a check mark is added. The tooltip is then available and reads `prettier-eslint@Unknown (bundled)`
My `package.json` file has:
```
	"devDependencies": {
		"eslint": "^5.0.1",
		"eslint-config-prettier": "^2.9.0",
		"eslint-plugin-prettier": "^2.6.2",
		"prettier": "^1.13.7",
		"prettier-eslint": "^8.8.2"
	}
```

Seems this installation is not discovered.

![image](https://user-images.githubusercontent.com/802702/42402358-8bb1dcbe-817a-11e8-9fce-2192ac40ec89.png)

**Comment by RobinMalfait** [comment]
@bardware did you install the node_modules _after_ you opened the project in VSCode? If so, try to reload VScode.

**Comment by bardware** [comment]
Yes, I restarted VSCode.
I looked into your code. There's a file ` PrettierEditProvide.js`
```
        if (vscodeConfig.eslintIntegration && doesParserSupportEslint) {
            return errorHandler_1.safeExecution(() => {
                const prettierEslint = require('prettier-eslint');
                errorHandler_1.setUsedModule('prettier-eslint', 'Unknown', true);
                return prettierEslint({
                    text,
                    filePath: fileName,
                    fallbackPrettierOptions: prettierOptions,
                });
            }, text, fileName);
        }
``` 
This seems to me to be the culprit. The plugin does nothing to find out the version of the installed prettier version.

**Comment by CiGit** [comment]
It uses bundled prettier-eslint which in turn picks up your locally installed prettier / eslint. We are just unable to know which version it used -> `Unknown`
