### ISSUE TITLE
chaining breaking

### ISSUE THREAD

**Issue by trry-github** [prettier/prettier-vscode#2937]
input:
```js
 $axios.get(API.test, {
    baseURL: '/mock/',
    params,
  }).then((res: any) => {
    data.dataList = res.data.list
    pagination.value.total = res.data.total
  })
  ```
  
  output: 
  ```js
    $axios
    .get(API.test, {
      baseURL: '/mock/',
      params,
    })
    .then((res: any) => {
      data.dataList = res.data.list
      pagination.value.total = res.data.total
    })
  ```
  
  
  expect:
  ```
   $axios.get(API.test, {
    baseURL: '/mock/',
    params,
  }).then((res: any) => {
    data.dataList = res.data.list
    pagination.value.total = res.data.total
  })
  ```
  
 How to configure in vscode settings json？

**Comment by ntotten** [comment]
Prettier has a few options because of history. But we won’t add more of them. For more details see: https://prettier.io/docs/en/option-philosophy.html

**Comment by trry-github** [comment]
> Prettier has a few options because of history. But we won’t add more of them. For more details see: https://prettier.io/docs/en/option-philosophy.html

This could be the beginning of the end of prettier's life
