### ISSUE TITLE
Option "printWidth" must be of type

### ISSUE THREAD

**Issue by ray-su** [prettier/prettier-vscode#294]
Hello,   How can I solve this? It used to work just fine, and start getting this error since yesterday.
` Option "printWidth" must be of type:
    number
  but instead received:
    string

  Example:
  {
    "printWidth": 80
  }`

I'm new to VSCode, How can I solve this? 
Thanks

**Comment by CiGit** [comment]
Seems your settings may be wrong.
Check your settings in vscode (workspace, user, folder)
Check those in prettier config files (.prettierrc{,.json,.js,.yml,.yaml}, package.json["prettier"])
Check those in editorconfig. This is new in latest release, so if you didn't touch your settings for some time, I would start here.

**Comment by ray-su** [comment]
I found this in my setting:

`  "prettier.printWidth": 80,` 

It is a number. Is this a bug from VSCode?

**Comment by CiGit** [comment]
VSCode setting's are overridden by prettier config files and editorconfig

**Comment by mlg87** [comment]
im also having this issue. i have integers for all of the `printWidth` values. is `printWidth` supported by editorConfig? [its not listed](https://github.com/editorconfig/editorconfig-vscode)

**Comment by blackstc** [comment]
I'm also having this issue.  I've removed all prettier configurations and just using the default plugin options and still seeing this error.

**Comment by CiGit** [comment]
By editorconfig, I mean a file so named. `prettier.resolveConfig` reads it.
`printWidth` comes from https://github.com/josephfrazier/editorconfig-to-prettier/blob/29aa34459dfec238ce179f1eb5a4fdcefb9c4961/index.js#L30-L32

`max_line_length` is what is transformed to `printWidth`

**Comment by ray-su** [comment]
Thank you for your reply and Sorry Im new to VScode.  How can I access the  prettier config and editorconfig?  I only see "user settings" and "workspace settings", and there nothing related to max_line_length and prettier.printWidth in those 2 settings.

**Comment by CiGit** [comment]
- a prettier config file in your file system https://prettier.io/docs/en/configuration.html
- an editorconfig file in your file system (on the tree path to your file)

**Comment by mlg87** [comment]
@CiGit thanks for the clarification on `max_line_length`. that did it for me

**Comment by ray-su** [comment]
i found `max_line_length` in .editorconfig, and changed the value to 80.  But now im getting another error
`Option "proseWrap" must be of type:
    boolean
  but instead received:
    string

  Example:
  {
    "proseWrap": true
  }`

**Comment by ray-su** [comment]
@mlg87   so did you change the value of 'max_line_length'  ?

**Comment by CiGit** [comment]
@ray-su For proseWrap, this is certainly because you have a prettier 1.8 installed locally.
3 solutions:
- update it
- use a prettier config file with  `{"proseWrap": true}`
- set `prettier.proseWrap` to true in vscode settings (you will have a JSON validation warning)

**Comment by mlg87** [comment]
@ray-su yes, to an integer

**Comment by hidace** [comment]
@CiGit Thanks for the help. Creating a `.prettierrc` file as you mentioned from https://prettier.io/docs/en/configuration.html solved it for me.
