### ISSUE TITLE
Uses default prettier settings no matter what (linux specific?)

### ISSUE THREAD

**Issue by ohjames** [prettier/prettier-vscode#295]
Running vs code on Linux. Have a `.prettierrc` in my project root directory as a yaml file. The command `prettier` uses it just fine.

However this extension always uses the default prettier settings.

So I tried updating VS Code's settings, added these:

```
  "prettier.singleQuote": true,
  "prettier.printWidth": 96,
  "prettier.trailingComma": "all",
```

Same story, still using the default config.

**Comment by ohjames** [comment]
Tried formatting `.prettierrc` as `json` instead of `yaml` but the problem was the same.

**Comment by ohjames** [comment]
Updated description and title, problem is worse than I first thought.

**Comment by CiGit** [comment]
We also read your editorconfig settings. Command line prettier does this too.
VSCode's settings may be overridden by prettier config file and editorconfig.
In my case, on linux, it works well.

If you can debug it, try with a breakpoint https://github.com/prettier/prettier-vscode/blob/067545ed33fd1d82dea38edaceef2bf09b8d840e/src/PrettierEditProvider.ts#L129

Config has been computed at that point.

**Comment by ohjames** [comment]
@CiGit I have no `.editorconfig`, although even if I did I would have thought `.prettierrc` and config options would override them. Maybe I'll try debug it.

**Comment by CiGit** [comment]
Settings priority are:
- prettierconfig
  1. prettierconfig
  1. editorconfig
- No prettier config
  1. editorconfig
  1. vscode config

At least this is what I wanted to code :-)

**Comment by ohjames** [comment]
@CiGit Debugged the code at the point you suggested, none of my settings are present, so it's not picking up `.prettierrc` or the standard vs code options.

**Comment by ohjames** [comment]
Okay found the issue, prettier supports `snake-case` options but this extension does not. I just converted all the options to camel case and it works. Might be worth supporting or documenting or something.

**Comment by CiGit** [comment]
Hum, where does prettier support snake-case (cli excepted)?

**Comment by mbellgb** [comment]
I have the same issue, running VS Code v1.18 on Linux, no editorconfig or prettierrc. My VS Code settings contains these values:

```json
{
  /* ... */
  "prettier.eslintIntegration": true,
  "prettier.trailingComma": "all",
```

But trailing commas get stripped from my files when saving or formatting... could this be related?

**Comment by ohjames** [comment]
@mbellgb cool that sounds like a separate issue worth supporting and explains why my second attempt at fixing the config also failed.

**Comment by ekulabuhov** [comment]
To figure out which config file prettier is using you can type: `prettier --find-config-path <file-to-format>`
