### ISSUE TITLE
Restart Prettier action

### ISSUE THREAD

**Issue by brawaru** [prettier/prettier-vscode#2968]
**Is your feature request related to a problem? Please describe.**
I've had this problem for quite a few times already when I accidentally save file before pnpm completes the installation of the packages. Unfortunately, as I use some Prettier plugins, Prettier VS Code extension stops working altogether, even after changing `.prettierrc` file. The only way to fix it is to restart the extension host altogether or reload the window. Both are somewhat expensive tasks for such a rudimentary problem.

**Describe the solution you'd like**
It would be much better if there was ‘Prettier: Restart Prettier’ action, similar to ‘TypeScript: Restart TS Server’, or ‘ESLint: Restart ESLint Server’, which would allow to quickly recover from this situation.

**Describe alternatives you've considered**
As I noted above, restarting extension host or reloading the window are pretty expensive operations performance-wise, especially if you have many extensions, and using low-end computer. It's also not clear if restarting extension host has any consequences, the command must be marked ‘Developer’ for a reason.

**Additional context**
Relevant issues: #584.

**Comment by Mister-Hope** [comment]
Yes, I think it's not affordable for a user to close/reload the window just to restart this plugin.

Plugins like eslint and volar support reload over context menu. Hope someone can focus on this to get it done.

**Comment by ntotten** [comment]
The issue is Prettier doesn't use a language server like typescript or eslint so we can't just restart prettier - its the same process as VS Code. The way to quickly reload VS Code is to use this
<img width="709" alt="image" src="https://github.com/prettier/prettier-vscode/assets/282782/91301301-0660-48ca-b6c9-565893b1674f">
