### ISSUE TITLE
can open state console for this plugin?

### ISSUE THREAD

**Issue by vegawong** [prettier/prettier-vscode#297]
i found that i can not format my code when i open the code file the first time until wait for a second.

maybe my vscode editor has installed so much plugin and init the edior panel and loaded all the plugin use a long time.   i want to catch prettier-vscode loaded status by the console. but i got nothing in the panel. are there any setting for the console output?

**Comment by CiGit** [comment]
There is no "Ready" message in the console.

Prettier should be ready when "Prettier" shows up in the bottom task bar.

You can start vscode with `code --prof-startup` to see what's happening on start.

**Comment by CiGit** [comment]
Answered. If not, comment / reopen
