### ISSUE TITLE
Format on open

### ISSUE THREAD

**Issue by anogr** [prettier/prettier-vscode#2973]
Some developers may prefer a different format than other developers in the team. For example, they may prefer other settings for semicolons, singleQuote or printWidth.

I suggest a "format on open" option that reads a prettier.local configuration file and formats a file whenever the user opens the file. When the file is saved, it formats using the normal configuration settings as usual. Of course, the prettier.local file must be git ignored.

This way a developer may choose to use other formatting settings than the rest of team without disturbing anyone else.

**Comment by ntotten** [comment]
This isn't an extension point of VS Code so we can't add it. You'd have to get VS Code to add this feature first.
