### ISSUE TITLE
Double Parentheses Format Quesition

### ISSUE THREAD

**Issue by MarkSky** [prettier/prettier-vscode#298]
In order to let Eslint rule (no-mixed-operators) be right.
I write this code:
`x= xa - bbox.left - ((bbox.width - canvas2.width) / 2);`
But after I format, it displayed:
`x= x - bbox.left - (bbox.width - canvas2.width) / 2;`
And then Eslint is alert: message: 'Unexpected mix of '-' and '/'. (no-mixed-operators)'
How should I set the prettier? Or there is another way to write this code?

**Comment by CiGit** [comment]
It seems this rules is not fixable. So nothing you can do with the formatter here.
>Or there is another way to write this code?

Yes! Prettier did it for you ;-)

**Comment by MarkSky** [comment]
Even if I set **prettier.eslintIntegration": true**, it still delete my parentheses.
So should I wait for Prettier solves this problem?

**Comment by CiGit** [comment]
I think you may have to wait a long time. I can remember a discussion about that in prettier's repository (https://github.com/prettier/prettier/issues/187).

An alternative solution, would be to make `no-mixed-operator` fixable.

Closing as there is nothing we can do here.
