### ISSUE TITLE
tabWidth ignored in VS Code and .prettierrc

### ISSUE THREAD

**Issue by tonyonodi** [prettier/prettier-vscode#299]
My full setting overwrites are

```
{
    "sublimeTextKeymap.promptV3Features": true,
    "prettier.trailingComma": "es5",
    "prettier.tabWidth": 2,
    "editor.tabSize": 2,
    "editor.detectIndentation": false,
    "[javascript]": {
      "editor.formatOnSave": true
  }
}
```

But formatting still gives me a tab width of 4.

The only extensions I currently have installed are [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components), [Sublime Text Keymap](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings), and [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode).

I have tried running prettier on a .js file in an otherwise empty directory and it behaves as it should, indenting with 2 spaces, but the problem persists in multiple projects. 

In an attempt to override whatever is causing this I have added a .prettierrc file at the top level of a project with the contents

```
{
    "tabWidth": 2
}
```

But that hasn't worked either.

**Comment by CiGit** [comment]
do you have any editorconfig file?

I would still say a prettierrc file should win...

**Comment by CiGit** [comment]
from the file and upwards I think

**Comment by tonyonodi** [comment]
Wow, I had a .editorconfig in the directory above my project. I'm not sure why that would override .prettierrc and I've no idea where it came from, but I've edited it now and Prettier is indenting as expected.

Thanks for your help, that was driving me mad.

**Comment by CiGit** [comment]
`.editorconfig` shouldn't override `.prettierrc`.
It overrides vscode settings tho.
