### ISSUE TITLE
Formatting before the set column lenght

### ISSUE THREAD

**Issue by nealoke** [prettier/prettier-vscode#300]
Hi, I have been using this superb plugin for a while but as of today when I hit save and it formats (as it should) something horrible goes wrong... Namely it formats everything as short as possible which is very very very annoying:

**Before save (and format)**
```
import moment from 'moment';

import * as ActionTypes from 'state/actionTypes';

const INITIAL_STATE = {
	periodFrom: moment().subtract(30, 'days').toString("YYYY-MM-DD"),
	periodTo: moment().toString("YYYY-MM-DD"),
	accounts: [],
	scores: true,
	customerData: false
};
```

**After save (and format)**
```
import moment from "moment";

import * as ActionTypes from "state/actionTypes";

const INITIAL_STATE = {
	periodFrom: moment()
		.subtract(
			30,
			"days"
		)
		.toString(
			"YYYY-MM-DD"
		),
	periodTo: moment().toString(
		"YYYY-MM-DD"
	),
	accounts: [],
	scores: true,
	customerData: false
};
```

As shown it formats the `periodFrom` which is a total lenght of only 70 columns... This also happens for lines where it is even lower which is driving me nuts. 

Settings I have in my `vscode` environment.
```
    "prettier.eslintIntegration": true,
    "prettier.tabWidth": 4,
```

**Comment by CiGit** [comment]
Check if you have any `.editorconfig` file
with a `max_line_length` which could be a small number.

**Comment by nealoke** [comment]
Hi thanks for taking the time to look at this!

I do have a `.editorconfig` file but it does not seem to have the `max_line_length` in it. 

**`.editorconfig`**
```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
indent_style = tab
indent_size = tab
tab_width = 4
trim_trailing_whitespace = true

# New file
[Makefile]
end_of_line = lf
insert_final_newline = true
indent_style = tab
indent_size = tab
tab_width = 4
trim_trailing_whitespace = true

# Matches the exact files either package.json or .travis.yml
[{package.json,.travis.yml}]
indent_style = space
indent_size = 2
```

**My `.eslintrc.js` file**
```
module.exports = {
	env: {
		browser: true,
		es6: true
	},

	extends: ["airbnb"],

	plugins: ["react", "jsx-a11y", "import"],

	rules: {
		indent: [
			2,
			"tab",
			{
				SwitchCase: 1,
				VariableDeclarator: 1
			}
		],

		"no-tabs": 0,
		"react/jsx-indent": [2, "tab"],
		"react/jsx-indent-props": [2, "tab"],

		"linebreak-style": 0,

		quotes: ["error", "double"],

		semi: ["error", "always"],

		"comma-dangle": [
			"error",
			{
				arrays: "only-multiline",
				objects: "only-multiline",
				imports: "only-multiline",
				exports: "only-multiline",
				functions: "only-multiline"
			}
		],

		"default-case": "off",

		"brace-style": ["error", "stroustrup"],

		"no-unused-expressions": ["error", { allowShortCircuit: true, allowTernary: true }],

		"react/jsx-filename-extension": ["error", { extensions: [".js", ".jsx"] }],

		"react/jsx-no-bind": ["error", {
			"ignoreRefs": false,
			"allowArrowFunctions": false,
			"allowBind": false
		}],

		"import/prefer-default-export": "off"
	},

	settings: {
		"import/resolver": "webpack"
	}
};

```

**Comment by CiGit** [comment]
what if you turn off eslint ?

**Comment by nealoke** [comment]
Do you mean the `"prettier.eslintIntegration": true,`?

**Comment by CiGit** [comment]
Exactly

**Comment by nealoke** [comment]
@CiGit Just tried it, if I have `prettier.eslintIntegration": false` it formats as it should, is there anything I can do to fix this issue?

**Comment by CiGit** [comment]
prettier-vscode was just updated with a new prettier-eslint but I don't think it will change in this case.

Seems, prettier-eslint is inferring printWidth to a _small_ value. Certainly from https://eslint.org/docs/rules/max-len

**Comment by nealoke** [comment]
I just added `max-len: ["error", { "code": 100 }]` to my `.eslintrc.js` and now it correctly formats, should I report this issue somewhere else then?

**Comment by CiGit** [comment]
Maybe this isn't an error at all. `max-len` can be declared in your eslint config (taking `extends` into account) if that's not the case, I would see with prettier-eslint.
You can try with prettier-eslint cli. enable debug logs to see what it computes. (We use prettier-eslint@8.3.1)

**Comment by kilianc** [comment]
@nealoke is the fix still working?

**Comment by ntotten** [comment]
Appears to be an issue with prettier-eslint rather than this plugin. Version 3.0 wont ship with prettier-eslint, but will require you to install locally. As such this is being closed.
