### ISSUE TITLE
Wrong `.prettierignore` file used when using multiple sub folders

### ISSUE THREAD

**Issue by KirianCaumes** [prettier/prettier-vscode#3003]
### Summary

I have a project structure with two folders : `front` and `back`.
Each of the them contains a `.prettierignore` and `.prettierrc.json`. Plus one at the root of the project.
When I'm saving a file (via `"editor.formatOnSave": true`), depending if the file is in the root, `front` or `back` folder, the correct `.prettierrc.json` is used, but not the correct `.prettierignore`.

### Github Repository to Reproduce Issue

Here is a repository to reproduce the issue: https://github.com/KirianCaumes/Prettier-VsCode-Bug 

### Steps To Reproduce:

1.  Open the `./should-be-ignored.yml` file, and save it. It should be skiped thanks to `./.prettierignore`.
1.  Open the `./front/should-not-be-ignored.ymll` file, and save it. It is skiped thanks to `./.prettierignore`, but it should not because of the `./front/.prettierignore`. 

### Expected result

When saving a file in a subfolder with it's own `.prettierignore`, this one should be used, not the one at the root of the project.
The behavior I want, is exactly how it's working now with `.prettierrc.json`.

### Actual result

The root `.prettierignore` is used instead of the closest one.

### Additional information

**VS Code Version**:

Version: 1.78.1 (user setup)
Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
Date: 2023-05-04T09:48:08.683Z
Electron: 22.5.1
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

**Prettier Extension Version**: 

v0.50.0

**OS and version**:

Windows 11

## Prettier Log Output

When saving `should-be-ignored.yml`:

```
["INFO" - 4:06:57 PM] Formatting file:///home/project/should-be-ignored.yml
["INFO" - 4:06:57 PM] Using config file at '/home/project/.prettierrc.json'
["INFO" - 4:06:57 PM] Using ignore file (if present) at /home/project/.prettierignore
["INFO" - 4:06:57 PM] File Info:
{
  "ignored": true,
  "inferredParser": null
}
["INFO" - 4:06:57 PM] File is ignored, skipping.
```

When saving `front/should-not-be-ignored.yml`, we clearly see that the `.prettierrc.json` is the one from the `front` folder, but not the `.prettierignore`:

```
["INFO" - 4:05:09 PM] Formatting file:///home/project/front/should-not-be-ignored.yml
["INFO" - 4:05:09 PM] Using config file at '/home/project/front/.prettierrc.json'
["INFO" - 4:05:09 PM] Using ignore file (if present) at /home/project/.prettierignore
["INFO" - 4:05:09 PM] File Info:
{
  "ignored": true,
  "inferredParser": null
}
["INFO" - 4:05:09 PM] File is ignored, skipping.
```

Thanks a lot 🙏

**Comment by villanuevadani** [comment]
Did you find a solution for this?

**Comment by ValentinGurkov** [comment]
Just bumped into this - it would be great if the maintainer consider this core functionality, using the closest `.prettieringore` when possible, just like with the config file.

**Comment by yanna92yar** [comment]
+1 `.prettierrc` is picked correctly while `.prettieringore` is not !

**Comment by KrishnaPG** [comment]
Came across this while facing the same problem. Not sure why it picks `.prettierrc` correctly (the closest) but looks for `.prettieringore` in the root (far away from subfolder).
