### ISSUE TITLE
.prettierignore settings being ignored for nested subfolders

### ISSUE THREAD

**Issue by coryhouse** [prettier/prettier-vscode#301]
.prettierignore is being ignored for subfolders. I'm running version 1.0.

[Example repo](https://github.com/coryhouse/prettier-vscode-bug)

**Comment by CiGit** [comment]
Thanks for the repo !

Our extension doesn't ignore `subdir/*`, prettier cli does.
`subdir/` works in both cases tho.

**Comment by CiGit** [comment]
Quick debug,
https://github.com/prettier/prettier-vscode/blob/v1.0.0/src/ignoreFileHandler.ts#L25
path.relative() returns `"../subdir/index.js"` it should be `"subdir/index.js"`

**Comment by coryhouse** [comment]
Thanks for the quick reply! I've zeroed in on the issue: The plugin fails to ignore nested folders.

Do a pull on my updated repo for an example of the issue. I've updated the title of this bug accordingly.

**Comment by CiGit** [comment]
Thanks for the repo, I've added it as tests ;-)

**Comment by coryhouse** [comment]
Excellent! Thanks for the quick response! :)

**Comment by goliney** [comment]
I can confirm I have the same issue.
