### ISSUE TITLE
Prettier is adding extra parentheses around a condition assignment inside other parentheses

### ISSUE THREAD

**Issue by sanket-codes** [prettier/prettier-vscode#3010]
The issue relates to the behavior of the Prettier extension in Visual Studio Code, which adds extra parentheses when there is an if condition with an assignment. This formatting inconsistency affects the clarity and intended precedence of the code.

`if ((a = 1)) {
  console.log('hi');
}
`
![Capture](https://github.com/prettier/prettier-vscode/assets/111676569/7fb0f0c2-2d6e-48c6-bc9f-5f50fdcf09ef)

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
