### ISSUE TITLE
New Fragments Syntax not recognized

### ISSUE THREAD

**Issue by cwklausing** [prettier/prettier-vscode#302]
I've updated my prettier to V 1.9.0,  however, the VS extension is still error highlighting the new fragment syntax on components. For ex:

```
<>
    <Component1>
    <Component2>
</>
```

This is a feature I'd love to be able to use, but I won't use until it clears my linting.
Thanks

**Comment by CiGit** [comment]
Are you saying prettier throws on format? It shouldn't be the case since prettier 1.9 (bundled with prettier-vscode 1.0.0)

If you have a locally installed prettier, it may be causing it if it's <1.9.

Or are you saying you have linting errors ? In this case, wrong extension :-)

**Comment by cwklausing** [comment]
You're right, I think I'm mistakened--is this plugin not responsible for syntax highlighting in VS?

**Comment by CiGit** [comment]
No, only formatting (nearly)!
It can be VSCode, but on js/ts files, it's ok on my VSCode.
It can be your typescript version, which VSCode may use.
It can be any other extension ...

I would suppose, your eslint doesn't parse it and you will have to update your dependencies.

**Comment by cwklausing** [comment]
Great, thanks!
