### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by markossankey** [prettier/prettier-vscode#3044]
Type: <b>Bug</b>

Whenever file saves it takes anywhere between 1 - n seconds

Extension version: 9.16.0
VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|17, 10, 7|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv|. --crash-reporter-id f851827b-7000-4708-bbcd-e5e90c8e0b50|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30776458
pythonidxpt:30772539
pythondjangots:30772535
pythonnoceb:30776495

```

</details>

**Comment by caioq** [comment]
Hi @markossankey , I was facing the same issue where it took more than 10-20 seconds to auto format the file on save.
I cleaned up some extensions on vscode. When I uninstalled the Setting Sync extension thats what made difference for me, now it takes around 60ms to auto format.
![image](https://github.com/prettier/prettier-vscode/assets/19962665/abc34102-54fa-4cd1-932a-97ef8babee0d)

**Comment by markossankey** [comment]
> Hi @markossankey , I was facing the same issue where it took more than 10-20 seconds to auto format the file on save. I cleaned up some extensions on vscode. When I uninstalled the Setting Sync extension thats what made difference for me, now it takes around 60ms to auto format.

I just verified that I don't have this extension installed.  I appreciate the recommendation though.

**Comment by CDzungx** [comment]
Same issue on Windows 11

**Comment by flexchar** [comment]
Frankly it sucks I cannot update VS Code as some extensions offer features that require updating and I feel pressured in the corner. 

It also sucks since I don't know how to help the community to debug this. Any ideas?
