### ISSUE TITLE
Regression on package.json finding behavior for globally installed prettier with vscode extension

### ISSUE THREAD

**Issue by wxf-contentgroove** [prettier/prettier-vscode#3045]
### Summary

The prettier vscode extension seems to have had a behavior regression in version 9.16.0. It is no longer able to load the package.json for a globally installed prettier on macOS

### Steps To Reproduce:

1.  Set prettier path to the globally installed version of prettier, typically: /usr/local/lib/node_modules/prettier on macOS
1.  Try to format a file with the "Format document" command

### Expected result

The file is formatted with prettier

### Actual result

The document is not formatted and the prettier extension throws an error. 

### Additional information

Behavior works as expected on extension version 9.15.0. Additionally, prettier is present in the path and can be run as expected from the command line. 

I have not checked if this behavior regression is also present on Windows or Linux. 

EDIT: as per [this reply](https://github.com/prettier/prettier-vscode/issues/3045#issuecomment-1612982190) to the issue, it appears to also effect windows

Here's the ls of the prettier install location ( /usr/local/lib/node_modules/prettier ) 

```
➜  ~ ls  /usr/local/lib/node_modules/prettier
LICENSE              parser-angular.js    parser-meriyah.js
README.md            parser-babel.js      parser-postcss.js
bin-prettier.js      parser-espree.js     parser-typescript.js
cli.js               parser-flow.js       parser-yaml.js
doc.js               parser-glimmer.js    standalone.js
esm                  parser-graphql.js    third-party.js
index.js             parser-html.js
package.json         parser-markdown.js
```

All the correct files appear to be present

**VS Code Version**:

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:19:37.325Z (2 mos ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

**Prettier Extension Version**:

v9.16.0

**OS and version**:
macOS Ventura Version 13.2.1 (22D68)

## Prettier Log Output

```
["DEBUG" - 3:22:59 PM] Local prettier module path: '/usr/local/lib/node_modules/prettier'
["INFO" - 3:22:59 PM] Attempted to load Prettier module from /usr/local/lib/node_modules/prettier
["ERROR" - 3:22:59 PM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 3:22:59 PM] Cannot find Prettier package.json
Error: Cannot find Prettier package.json
	at t.ModuleResolver.loadPrettierVersionFromPackageJson (/Users/user/.vscode/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:3693)
	at t.ModuleResolver.getPrettierInstance (/Users/user/.vscode/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:5087)
	at t.default.handleActiveTextEditorChanged (/Users/user/.vscode/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:10688)
	at t.default.handleActiveTextEditorChangedSync (/Users/user/.vscode/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:10290)
	at t.default.registerDisposables (/Users/user/.vscode/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:13133)
	at /Users/user/.vscode/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:81225
```

**Comment by leejanmorado** [comment]
experiencing this even on local installation

**Comment by PawelBorys** [comment]
I am experiencing the same issue on Windows with globally installed prettier

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: (2 wks ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows NT x64 10.0.22621

Prettier version v9.16.0 

```
["INFO" - 1:35:15 PM] Attempted to load Prettier module from C:\Users\***\AppData\Roaming\npm\node_modules\prettier
["ERROR" - 1:35:15 PM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 1:35:15 PM] Cannot find Prettier package.json
Error: Cannot find Prettier package.json
	at t.ModuleResolver.loadPrettierVersionFromPackageJson (c:\Users\***\.vscode\extensions\esbenp.prettier-vscode-9.16.0\dist\extension.js:1:3693)
	at t.ModuleResolver.getPrettierInstance (c:\Users\***\.vscode\extensions\esbenp.prettier-vscode-9.16.0\dist\extension.js:1:5087)
	at t.default.format (c:\Users\***\.vscode\extensions\esbenp.prettier-vscode-9.16.0\dist\extension.js:1:14402)
	at async t.PrettierEditProvider.provideEdits (c:\Users\***\.vscode\extensions\esbenp.prettier-vscode-9.16.0\dist\extension.js:1:12274)
	at async U.provideDocumentFormattingEdits (c:\Users\***\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:45790)
```

**Comment by hediet** [comment]
It also broke for me in 9.16 (windows). 9.15 works.

**Comment by ntotten** [comment]
The change https://github.com/prettier/prettier-vscode/commit/d04b294a15f9dc20e1dc061013b57c7aa8f2764c from 9.16 was reverted. 9.19 is rolling out now. Thanks for reporting.

**Comment by garyking** [comment]
9.19 is still broken. 9.15 is still good.

**Comment by leejanmorado** [comment]
Still broken

**Comment by 93Akkord** [comment]
> @ntotten Appears to still be broken on 9.19, requesting re-open of the issue. Just tested. and it's throwing the same error.

Yes, same here. Still broken.

**Comment by azat-io** [comment]
@ntotten Can you reopen the issue?

**Comment by Yossri21** [comment]
still broken!

**Comment by HakobjanianDavid** [comment]
Workaround: just return to [previous version](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode&utm_source=www.vsixhub.com) by VSIX [example for python-ext](https://stackoverflow.com/questions/62299687/how-to-install-previous-version-of-python-extension-for-vscode)

**Comment by vsiao** [comment]
> I think this might be the change that broke it: [d04b294](https://github.com/prettier/prettier-vscode/commit/d04b294a15f9dc20e1dc061013b57c7aa8f2764c)

That change is a fix _for_ 9.16, so it cannot be the root cause for this issue. Honestly this sounds like the same issue #3041, which that commit was supposed to fix. @ntotten can you unrevert that and fix #3059?

**Comment by livevie** [comment]
is it now working for anyone? i still can't use it

**Comment by azat-io** [comment]
@ntotten Please reopen this issue

**Comment by paulalbertdev** [comment]
Same pb here

**Comment by carlosmrivera** [comment]
I'm facing this issue on v10.1.0

**Comment by paulalbertdev** [comment]
This seems to do the trick : https://github.com/prettier/prettier-vscode/issues/3100#issuecomment-1666476812

**Comment by oliver841025** [comment]
same pb here

**Comment by paulshestakov** [comment]
same problem

**Comment by ddlaat** [comment]
same problem

**Comment by kachkaev** [comment]
Folks, please use 👍 reaction instead of ‘+1 comments’. The latter clutter Notifications for other devs and don’t any value.

**Comment by ShlokDesai33** [comment]
Please reopen this issue.

**Comment by madaxen86** [comment]
This did the trick for me:
```
-"prettier.prettierPath": "./packages/compiler/node_modules/prettier",
+"prettier.prettierPath": "./packages/compiler/node_modules/prettier/**index.cjs**",
```

**Comment by lazuee** [comment]
@madaxen86 thanks, it works.

```json
{
"editor.formatOnSave": true,
"editor.formatOnType": true,
"editor.formatOnPaste": true,
"prettier.enable": true,
"prettier.withNodeModules": true,
"prettier.requireConfig": false,
# using nodejs-lts from scoop
"prettier.prettierPath": "C:/Users/Admin/scoop/persist/nodejs-lts/bin/node_modules/prettier/index.cjs",
}

**Comment by izeau** [comment]
For [fnm](https://github.com/Schniz/fnm) users:

```json
{
  "prettier.prettierPath": "~/.fnm/aliases/default/lib/node_modules/prettier/index.cjs"
}
```
