### ISSUE TITLE
Doesn't work with .editorconfig files

### ISSUE THREAD

**Issue by andrewreedy** [prettier/prettier-vscode#305]
When using this extension with an `.editorconfig` file in the project, format document and format on save both stop working. When we remove the `.editorconfig` file it immediately starts working.

**Comment by CiGit** [comment]
Prettier now reads editorconfig files.
Do you mind sharing the offending `.editorconfig`

**Comment by andrewreedy** [comment]
```
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
end_of_line = lf
# editorconfig-tools is unable to ignore longs strings or urls
max_line_length = null
```

**Comment by core01** [comment]
As for me Prettier can not read editorconfig files
my .editorconfig
```
root = true

[*]
charset = utf-8
indent_style = tabs
indent_size = 8
end_of_line = lf
insert_final_newline = false
trim_trailing_whitespace = true
```
All this settings such as indent_size, indent_style and insert_final_newline are ignored.

**Comment by CiGit** [comment]
It works pretty fine for me with that `editorconfig` file.
If you can debug it, it would be great :smile: 

@core01 prettier takes only options it can understand. final newline is not configurable in prettier

**Comment by stijnherreman** [comment]
@CiGit are there any plans to support the option, or to disable it completely? The official editorconfig extension supports it, but the newline is added again by prettier.

See also: https://stackoverflow.com/questions/51766545/why-does-the-editor-insert-a-final-newline-for-json-files-despite-configuring-i

**Comment by CiGit** [comment]
If prettier does, we will. But I highly doubt an option would be added for that.

I'll close that issue for now
