### ISSUE TITLE
9.19.0 fails to load from custom prettierPath

### ISSUE THREAD

**Issue by whoisarpit** [prettier/prettier-vscode#3059]
### Summary
#3041 is recurring because of https://github.com/prettier/prettier-vscode/commit/f6ff18b500858b913ef43dbad73ecbae929c3b27

Quoting #3041 below:

In 9.16, when configured with a path to the prettier module (eg. `node_modules/prettier`), the extension fails to load.

### Steps To Reproduce:
Set `prettier.prettierPath` config to `node_modules/prettier`

### Expected result
Extension loads `node_modules/prettier/package.json` successfully.

### Actual result
Extension fails to load. The extension appears to look for `node_modules/packages.json`, then `package.json`, etc.

### Additional information
**VS Code Version**: 1.79.2

**Prettier Extension Version**: 9.16

**OS and version**: Mac OS Ventura 13.4

## Prettier Log Output
Below trace is from [#3038 (comment)](https://github.com/prettier/prettier-vscode/pull/3038#issuecomment-1602659513). cc @mreduar

```
["INFO" - 1:39:28 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 1:39:28 PM] Extension Version: 9.16.0.
["INFO" - 1:39:28 PM] Attempted to load Prettier module from /var/www/html/node_modules/prettier
["ERROR" - 1:39:28 PM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 1:39:28 PM] Cannot load Prettier version from package.json
Error: Cannot load Prettier version from package.json
    at t.ModuleResolver.loadPrettierVersionFromPackageJson (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:3820)
    at t.ModuleResolver.getPrettierInstance (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:5025)
    at t.default.handleActiveTextEditorChanged (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:10626)
    at t.default.handleActiveTextEditorChangedSync (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:10228)
    at t.default.registerDisposables (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:13071)
    at /root/.vscode-server/extensions/esbenp.prettier-vscode-9.16.0/dist/extension.js:1:81163
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by AndrewKvalheim** [comment]
A workaround has been shared at https://github.com/prettier/prettier-vscode/issues/3100#issuecomment-1662693832.

**Comment by trevorr** [comment]
I believe this issue is a regression caused by f6ff18b500858b913ef43dbad73ecbae929c3b27, which was an attempt to fix #3045.

I added a bit of logging to the module resolution to show what's happening:

```
["DEBUG" - 10:16:41 PM] Local prettier module path: '/Users/trevor/git/my_project/node_modules/prettier'
["INFO" - 10:16:41 PM] loadPrettierVersionFromPackageJson: /Users/trevor/git/my_project/node_modules/prettier
["INFO" - 10:16:41 PM] pkgFilePath: /Users/trevor/git/my_project/node_modules/package.json
["INFO" - 10:16:41 PM] pkgFilePath: /Users/trevor/git/my_project/package.json
["INFO" - 10:16:41 PM] Loaded /Users/trevor/git/my_project/package.json
```

Basically, `loadPrettierVersionFromPackageJson` was changed to search for the module with `cwd` set to the parent of the module path, rather than the module path itself. This causes it to read the `package.json` of the containing project rather than the one for prettier. In my monorepo project, there is no `version` in the root `package.json`, which causes the error above.

**Comment by fat0troll** [comment]
This issue is still exist in latest version of VS Code and this extension.

**Comment by nimish-gupta** [comment]
This issue still exist in the latest version, any temp solution for this?
