### ISSUE TITLE
tabWidth for *.js files are always 4

### ISSUE THREAD

**Issue by SystemR** [prettier/prettier-vscode#306]
prettier v1.9.2
prettier-vscode v1.0.0
vscode v1.19.0

Latest updates made my `Format Document` on *.js files to have 4 tabWidth. It still works fine on *.ts.

My settings:
```
{
    "editor.tabSize": 2,  
    "prettier.tabWidth": 2,
    "prettier.stylelintIntegration": true,
}
```

Removing the plugin made vscode conforms to editor.tabSize tabWidth.

**Comment by SystemR** [comment]
It seems to work fine only if you specify it in .prettierrc. Did the config resolver order change?

**Comment by CiGit** [comment]
Yes, it changed, it also reads ".editorconfig"

**Comment by SystemR** [comment]
It should still honor the user settings in preferences if .prettierrc and .editorconfig files aren't there though. Currently it doesn't.

**Comment by CiGit** [comment]
What you mean by it doesn't ? [This](https://github.com/prettier/prettier-vscode#prettiers-settings) is what should happen.

**Comment by SystemR** [comment]
I created a new, clean project and it seems prettier is doing the right thing. I'm going to close this issue. Thank you, @CiGit !
