### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by nguyenthanhtruongntt85** [prettier/prettier-vscode#3068]
Slow when save
<img width="458" alt="Screenshot 2023-07-09 at 11 43 39" src="https://github.com/prettier/prettier-vscode/assets/41815920/20387bbc-ebc8-479f-ac9b-518ae6eddfe3">

**Comment by sosukesuzuki** [comment]
Please show us more detailed log.

**Comment by levino** [comment]
I have the same. It happens when I uses yarn berry with pnp on Mac OS (M1). What can I provide to help? It never finishes after loading forever.

**Comment by levino** [comment]
I can fix it by using `prettier@^2`. Seems to be an issue with using `prettier@^3`.

**Comment by nguyenthanhtruongntt85** [comment]
I only change file settings.json work very fast.
**From**
{
  "eslint.format.enable": true,
  "editor.formatOnSave": true, //call .prettierrc.json,
  "editor.codeActionsOnSave": {
    // Enable automatic import sorting in VS Code
    "source.organizeImports": false
  }
}
**To**
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll": true
  },
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
  "cSpell.words": [
    "reduxjs"
  ],
}

**My In .prettierrc**
{
  "singleQuote": true,
  "semi": true,
  "trailingComma": "all",
  "printWidth": 100,
  "tabWidth": 2,
  "importOrder": ["^react", "^[./]", "^~/(.*)$"],
  "importOrderSeparation": true
}

**My In package json**
"devDependencies": {
  "@trivago/prettier-plugin-sort-imports": "4.1.1",
  "eslint-config-prettier": "8.7.0",
  "eslint-plugin-prettier": "4.2.1",
  "prettier": "2.8.4",
}

**Comment by peterhirn** [comment]
## Partial workaround

Running `yarn unplug prettier` seems to restore base functionality, but I'm unable to load any plugins, eg. `prettier-plugin-tailwindcss`.

**Comment by levino** [comment]
You can also just use version 2.x of prettier. Might be uncool but I see no difference in performance and quality to version 3.

**Comment by slikts** [comment]
This is quite a frustrating issue to run into, particularly because there's no errors, and the repro by @peterhirn works, so it shouldn't be labeled as needing more info.

**Comment by everyt** [comment]
Using yarn pnp seems particularly painful.

**Comment by 0xBurbo** [comment]
Also getting this issue with the following devDependencies:

`{
      "prettier": "^2.0.0",
      "eslint-config-prettier": "8.7.0",
      "eslint-plugin-prettier": "4.2.1",
}`

**Comment by nnmax** [comment]
Any progress?
