### ISSUE TITLE
Language Overrides for printWidth Setting in VS Code

### ISSUE THREAD

**Issue by dbagley1** [prettier/prettier-vscode#3093]
**Problem**
Allow language overrides for the VS Code prettier.printWidth option. VS Code settings are easily synchronized between machines and virtual environments like GitHub Codespaces. User-level Prettier configurations are more difficult to keep synchronized between environments leading to inconsistent formatting.

**Solution**
Update the extension manifest to specify the language-overridable scope on the prettier.printWidth option.

![image](https://github.com/prettier/prettier-vscode/assets/59030213/777257ac-bb62-4827-af46-ebd8f9398ede)

**Additional context**
Language-specific options set in VS Code settings.json would look like:
![image](https://github.com/prettier/prettier-vscode/assets/59030213/9b6dcfd6-c6b0-43f7-b193-0cb097b1c9f0)

Relevant VS Code Documentation: https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema

**Comment by GongT** [comment]
It should support `overrides` fields anyway. https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option

**Comment by dbagley1** [comment]
@GongT You're referring to the prettier configuration option. This issue is about the language-level overrides in VS Code because VS Code settings can be set on a user level that syncs between devices.

**Comment by danlutz** [comment]
Also experiencing this problem. We have language specific overrides for printWidth settings in the prettier configuration file. Works fine when formatting using the CLI, but the "Format Document" or "Format On Save" option in VSCode does not respect this override.

**Comment by SomaticIT** [comment]
Agree with @dbagley1.
I add that all configuration options should have the scope `language-overridable`.

**Comment by benblank** [comment]
I've just run into this limitation myself: I change `printWidth` to 120 in the general case (I primarily use Prettier with source code, which I do believe benefits from longer lines), but strongly prefer to use a more conservative width of 80 for documents (such as Markdown).

To be honest, this feels like a bit of a "regression" compared to the CLI, which allows for per-language (by way of globs, anyway) configuration both when using `.prettierrc` and when using `.editorconfig`. Of course, Prettier's lack of global configuration means it can't really be customized when editing files outside of projects *at all* without using prettier-vscode or similar! I just want to have the best of both worlds. 😉

**Comment by dbagley1** [comment]
Waiting for feedback from reviewers on my pull request. This issue remains unresolved @ntotten

**Comment by dbagley1** [comment]
Replying to keep this issue open.
