### ISSUE TITLE
Prettier not working in monorepo

### ISSUE THREAD

**Issue by smol-honk** [prettier/prettier-vscode#3095]
Type: <b>Bug</b>

Error: Cannot find module 'prettier'

Extension version: 9.19.0
VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|32.00GB (18.00GB free)|
|Process Argv|--crash-reporter-id 4fbf6ff9-981c-4ae7-be94-d2ad3a47d144|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590

```

</details>

**Comment by vajahath** [comment]
I can confirm this is not working with Yarn 3 PNP.

Prettier 3.0.0 (latest)
Extension v9.19.0 (latest)
Yarn 3.6.1 (latest)
VSCode 1.80.0 (latest)

As per https://yarnpkg.com/getting-started/editor-sdks

- installed prettier at root
- ran `yarn dlx @yarnpkg/sdks vscode`
![image](https://github.com/prettier/prettier-vscode/assets/12165822/f975ed4f-cd6a-4caf-9e56-c32cba17d1fa)
- paths automatically updated at vscode settings file

But formatting doesn't work. Complaining prettier cannot be found.

**Comment by vsiao** [comment]
Maybe duplicate of https://github.com/prettier/prettier-vscode/issues/3059?

**Comment by smol-honk** [comment]
Sorry I should also mention that this is happening in a mono-repo.

**Comment by Hrle97** [comment]
same here in a monorepo

i tried to do it manually and got this

```
C:\tools\src\9b3dc\repos\mess\work\mess-dev λ node .\.yarn\sdks\prettier\index.js .\.vscode\settings.json                                                                                      08/04/2023 04:02:51 PM
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\9b3dc\AppData\Local\Yarn\Berry\cache\prettier-npm-3.0.1-d00deab00c-8.zip\node_modules\prettier\index.mjs' imported from C:\Users\9b3dc\AppData\Local\Yarn\Berry\cache\prettier-npm-3.0.1-d00deab00c-8.zip\node_modules\prettier\index.cjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:324:11)
    at moduleResolve (node:internal/modules/esm/resolve:943:10)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:524:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1188:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.17.0
```

idk if this is how this extension does it internally but hopefully its of some help
using yarn@3.6.1 with pnp

**Comment by koshic** [comment]
'yarn unplug prettier' helps me. yarn 4.0.0-rc.48

**Comment by francis-zhao** [comment]
> I can confirm this is not working with Yarn 3 PNP.
> 
> Prettier 3.0.0 (latest) Extension v9.19.0 (latest) Yarn 3.6.1 (latest) VSCode 1.80.0 (latest)
> 
> As per https://yarnpkg.com/getting-started/editor-sdks
> 
> * installed prettier at root
> * ran `yarn dlx @yarnpkg/sdks vscode`
>   ![image](https://user-images.githubusercontent.com/12165822/257195426-f975ed4f-cd6a-4caf-9e56-c32cba17d1fa.png)
> * paths automatically updated at vscode settings file
> 
> But formatting doesn't work. Complaining prettier cannot be found.
> 
> The output from debug console:
> 
> ```
> ["INFO" - 16:18:15] Extension Name: esbenp.prettier-vscode.
> ["INFO" - 16:18:15] Extension Version: 9.19.0.
> ["INFO" - 16:18:43] Formatting file:///home/xxx/index.ts
> ```
> 
> And it seem stuck.

My situation is exactly the same as yours. VSCode hangs forever on `FormatOnSave` with Prettier installed by Yarn PnP.
