### ISSUE TITLE
v10.0.0 extension not working 

### ISSUE THREAD

**Issue by 700software** [prettier/prettier-vscode#3099]
Getting this when attempting to format a `.js` or `.tsx` file:

>Visual Studio Code
> Configure Default Formatter
>
> Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'JavaScript'-files
>
> Configure... | Cancel

![image](https://github.com/prettier/prettier-vscode/assets/20981023/591bd00a-9f49-44e3-87b3-8deb4fc17deb)

![image](https://github.com/prettier/prettier-vscode/assets/20981023/904f505d-7d62-4545-a03a-a0cfb7cbf692)

Then when clicking Configure... The extension is no longer listed as a possible formatter
![image](https://github.com/prettier/prettier-vscode/assets/20981023/4ed51e2d-dfc2-424e-8c22-79f6757639a2)

I tried manually setting `  "editor.defaultFormatter": "esbenp.prettier-vscode", "[typescript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },` etc. in the repository's `.vscode/settings.json` as well as my User `settings.json` and it has no effect.

**VS Code Version**:

Version: 1.80.2 (user setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

**Prettier Extension Version**: v10.0.0

**OS and version**: Windows 10

## Prettier Log Output

![image](https://github.com/prettier/prettier-vscode/assets/20981023/27c8dfac-db82-4592-80c8-a6fd4b6df9ee)

**Comment by mscherr-fastspot** [comment]
+1

**Comment by lyt8384** [comment]
+1

**Comment by shenawy29** [comment]
Same here.

**Comment by nathnhughes** [comment]
Yup, same here

**Comment by asportnoy** [comment]
Dupe #3098

**Comment by fish-can** [comment]
Same here.
I try to downgrade to 9.x, it works again.

**Comment by chrisella** [comment]
+1

**Comment by sosukesuzuki** [comment]
We'll revert and re-release sorry

**Comment by ntotten** [comment]
Reverting changes to prettier 3.0.0 in version 10.1.0 (which is the same as the previous 9.x release) we are going to see what happened and rerelease in the next few days.

**Comment by SimeonC** [comment]
With prettier installed locally in node_modules (but not using any specific settings) I found that `9.20.0` will format using prettier v3, but `10.x` will not
