### ISSUE TITLE
.prettierignore pattern to ignore an entire folder

### ISSUE THREAD

**Issue by tomeraz** [prettier/prettier-vscode#311]
I have some folders I want to disable prettier completely, and let it run on other folders with formatOnSave.
tried to add .prettierignore with ```**/* and **/``` with no effect - prettier still formats the code.
What can I do to make this work?

**Comment by CiGit** [comment]
What do you mean by _folder_ ?
You can disable the extension for certain workspace.
Try with `**`

**Comment by tomeraz** [comment]
If I put .prettierignore at a folder root and open it using 'open folder' it doesn't get picked up by the extension?

**Comment by CiGit** [comment]
By default it picks up `.prettierignore` in your opened folder yes.

**Comment by tomeraz** [comment]
I've placed a .prettierignore in a folder with ```**``` like you said (thanks).
If I open my project via file-->open workspace... the extension uses .prettierignore
but if I open my project via file-->open folder, the extension doesn't use .prettierignore and the code is getting prettified in unwanted places (such as python templates).

I usually don't use workspaces, just folders and 'open folder'.
Is there a way to make the extension use .prettierignore when opening a folder, without opening a workspace?

**Comment by CiGit** [comment]
I don't get it, If I do `Open folder`, vscode opens a workspace with one folder and prettierignore works as expected.

**Comment by thepeted** [comment]
I have the same issue: vscode 1.21.1, MacOS 0.13.3
