### ISSUE TITLE
When formatting a large ts file (ts file,4000, 5000 lines), the cursor will move to the end of the file

### ISSUE THREAD

**Issue by dnjat** [prettier/prettier-vscode#3119]
When formatting a large ts file (ts file,4000, 5000 lines), the cursor will move to the end of the file

**Comment by Jheovanny** [comment]
same problem

**Comment by sylvainpolletvillard** [comment]
https://github.com/prettier/prettier-vscode/assets/566536/76bd47bd-1384-4952-b7c7-3d258526a123

Reproduction on video. It jumps to the end when saving (Ctrl+S )

**Comment by shap-po** [comment]
I have the same problem, also it unfolds everything which is very annoying.
Found two similar issues: https://github.com/prettier/prettier-vscode/issues/408, https://github.com/prettier/prettier-vscode/issues/2742. Both are closed and the recommended solution (switching `editor.foldingStrategy` to `indentation`) did not work for me.

**Comment by mustafa-colakoglu** [comment]
Same problem here, as i see, limit is 100kb

**Comment by shap-po** [comment]
> Same problem here, as i see, limit is 100kb

Good to know the limit. Just converted indentation from spaces to tabs and got another 20kb until the problem reappears 😀

**Comment by mustafa-colakoglu** [comment]
> > Same problem here, as i see, limit is 100kb
> 
> Good to know the limit. Just converted indentation from spaces to tabs and got another 20kb until the problem reappears 😀

I m glad to helped you :D I hope prettier can help to me like this :D

**Comment by mustafa-colakoglu** [comment]
another thing is, when i tried on my macbook, there is no 100kb limit, its works, I think this is a from Windows, maybe

**Comment by mustafa-colakoglu** [comment]
Hi all, i found some solution, i inspected and found why. I hope it helps to you.

When I trying some fixed, I want to try to use prettier from cli. I executed from cli, and I saw some differences on my file, but GitLens tool does not see the change, but it says this file is changed. So I compared my original file and changed file from some Hex Editor tool. And I see, endOfLine is different, so, I changed .prettierrc configuration endOfLine to "**auto"**, it fixed for me.

**Comment by shap-po** [comment]
> Hi all, I found some solution, I inspected it and found why. I hope it helps you.
> 
> When I trying some fixes, I want to try to use prettier from cli. I executed from cli, and I saw some differences on my file, but GitLens tool does not see the change, but it says this file is changed. So I compared my original file and changed file from some Hex Editor tool. And I see, endOfLine is different, so, I changed the .prettierrc configuration endOfLine to "**auto"**, it fixed it for me.
> 
> But I think this error still has to be fixed.

You are a lifesaver! That fixed the issue for me as well.

**Comment by mustafa-colakoglu** [comment]
> > Hi all, I found some solution, I inspected it and found why. I hope it helps you.
> > When I trying some fixes, I want to try to use prettier from cli. I executed from cli, and I saw some differences on my file, but GitLens tool does not see the change, but it says this file is changed. So I compared my original file and changed file from some Hex Editor tool. And I see, endOfLine is different, so, I changed the .prettierrc configuration endOfLine to "**auto"**, it fixed it for me.
> > But I think this error still has to be fixed.
> 
> You are a lifesaver! That fixed the issue for me as well.

I m glad helped to you, this bug was bored me too much. Finally we fixed for us but I think we should not add this configuration.
