### ISSUE TITLE
Are the settings per language supported?

### ISSUE THREAD

**Issue by yuheiy** [prettier/prettier-vscode#312]
VSCode settings:

```json
  "[javascript]": {
    "prettier.singleQuote": true
  }
```

This is not works.

**Comment by kaminaly** [comment]
Or If we could use `overrides`, it would be great.
```
"prettier.overrides": [
  {
    "files": [
      "*.js"
    ],
    "options": {
      "singleQuote": true
    }
  }
]
```

**Comment by CiGit** [comment]
VSCode language scope settings are not supported. Only some VSCode specific settings can be put in those.

You can have a [prettier config file](https://prettier.io/docs/en/configuration.html) with settings specific to languages.

**Comment by yuheiy** [comment]
I would like to use VSCode language scope settings. Do you plan to support this in the future?

**Comment by CiGit** [comment]
Once vscode supports it, certainly. We *could* do it currently, but it's really messy.

**Comment by yuheiy** [comment]
I understand. Thank you!

**Comment by luchillo17** [comment]
Has this received any updates? are we still not able to use language scoped settings?

**Comment by Glavin001** [comment]
Subscribe to https://github.com/Microsoft/vscode/issues/26707 for VSCode updates.

**Comment by steph643** [comment]
@CiGit's solution to this issue works perfectly and is detailed here: https://github.com/prettier/prettier-vscode/issues/242#issuecomment-336473702
