### ISSUE TITLE
tslint auto fix and prettier format on save

### ISSUE THREAD

**Issue by ozum** [prettier/prettier-vscode#314]
Hi,

I'm trying to use both tslint auto fix and prettier format on save. My settings is as below:

```js
{
    "editor.formatOnSave": true,
    "[handlebars]": {
        "editor.formatOnSave": false
    },
    "tslint.autoFixOnSave": true
}
```

When I save a file, prettier formats code, but to let tslint fix work I need to save again:

1. Save -> Prettier formats code.
2. Save again -> tslint fixes further.

Is it expected behavior, or I miss something?

**Comment by joaovieira** [comment]
Just coming from converting a project from JS+ESLint to TS+TSLint. I guess we need to have a similar `prettier.tslintIntegration` to use [prettier-tslint](https://www.npmjs.com/package/prettier-tslint) - don't know the status of this project though.

**Comment by CiGit** [comment]
Currently eslintIntegration also works with ts files, but it reads eslintrc files assuming the right parser is set.

I think it should work correctly with autoFixOnSave as long as the process is fast enough.
Seems vscode has a delay after which transformations that occurred during save are dropped.

For prettier-tslint, @azz planned adding it once ready.

**Comment by hantsy** [comment]
I do not think the  eslintIntegration worked well with tslint config.  I have set it,  but it seems still problematic in my vscode. I have installed prettier-vscode extension, and also installed prettier, prettier-eslint in my Angular project `devDependencies` .

**Comment by CiGit** [comment]
@hantsy eslint doesn't read your tslint files. What I meant is using eslint on typescript files.

**Comment by orblazer** [comment]
Hello, an somebody have an news for prettier typescript ?

**Comment by CiGit** [comment]
Initial issue is more about strange behavior of formatOnSave + tslint.autoFixOnSave
For _tslintIntegration_ follow #188.

**Comment by CiGit** [comment]
For the initial issue, there where change in VSCode about formatOnSave lately and also in our code since this issue. Does it still need a _double pass_ ?

**Comment by MOZGIII** [comment]
For me it now works with a single pass

**Comment by CiGit** [comment]
Seems to work as expected.

**Comment by ee0pdt** [comment]
Still seems to need a double-pass for me

**Comment by MOZGIII** [comment]
I noticed it doesn't work properly in a multi-folder workspace.

**Comment by ee0pdt** [comment]
In this case I have just opened my root folder in a window, no workspace. I'm on macOS if that makes any difference.

VSCode: Version 1.26.1 (1.26.1)
node: v10.8.0
npm: 6.2.0
tslint: 5.11.0
prettier: 1.14.2

**Comment by MOZGIII** [comment]
It looks it's something else then, different from the case I've seen.

Seems like it a regression.

**Comment by CiGit** [comment]
I don't see what can be done here for that problem. But you can give a try to our new 🔥 tslintIntegration

**Comment by ee0pdt** [comment]
Understood, I'll give that a try, thanks all!

**Comment by dcsan** [comment]
this doesn't seem to exist for me

```
"tslint.autoFixOnSave": true,
```

![image](https://user-images.githubusercontent.com/514002/58365127-600a8b80-7ef2-11e9-82a3-da5eed4291d6.png)

**Comment by wish4129** [comment]
> this doesn't seem to exist for me
> 
> ```
> "tslint.autoFixOnSave": true,
> ```
> 
> ![image](https://user-images.githubusercontent.com/514002/58365127-600a8b80-7ef2-11e9-82a3-da5eed4291d6.png)

change to this works for me
```
"editor.codeActionsOnSave": {
        "source.fixAll.tslint": true
    },
```
