### ISSUE TITLE
Markdown is automatically formatted, causing React syntax interpretation errors

### ISSUE THREAD

**Issue by Alan3344** [prettier/prettier-vscode#3143]
I'm currently helping translate md documentation using [docusaurus.io](https://docusaurus.io/)

This is part of the [snippet](https://github.com/flet-dev/website/blob/main/blog/2023-02-06-standalone-flet-web-apps-with-pyodide.md?plain=1). line:79-86
Able to be interpreted correctly:
```js
import Card from '@site/src/components/card';
import { translate } from '@docusaurus/Translate';

export const GalleryCard = ({title, liveUrl, sourcesUrl, description, imageUrl}) => (
<Card>
<a className="gallery-live-link" href={liveUrl}>
<img src={"/img/gallery/" + imageUrl} className="screenshot-100"/>
<h2>{title}</h2>
<div className="gallery-description">{description}</div>
</a>
<div className="gallery-footer">
<a className="gallery-github-link" href={sourcesUrl} title="View source code"></a>
</div>
</Card>
);
```

able to be interpreted correctly:
```
import Card from '@site/src/components/card';
import { translate } from '@docusaurus/Translate';

export const GalleryCard = ({title, liveUrl, sourcesUrl, description, imageUrl}) => (
<Card>
<a className="gallery-live-link" href={liveUrl}>
<img src={"/img/gallery/" + imageUrl} className="screenshot-100"/>

<h2>{title}</h2>
<div className="gallery-description">{description}</div>
</a>
<div className="gallery-footer">
<a className="gallery-github-link" href={sourcesUrl} title="View source code"></a>
</div>
</Card>
);
```
This problem causes precompilation to fail.
![image](https://github.com/prettier/prettier-vscode/assets/60773912/fa68fc81-c435-427a-9c68-518499489809)

MacOS Ventura 13.4.1
Both vscode and plug-ins are the latest versions.

**Comment by tats-u** [comment]
You should use `.mdx` instead of `.md`.
For Docusaurus 2, you can format MDX (v1) with Prettier.

**Comment by Alan3344** [comment]
> ~You should use the extension `.mdx` instead of `.md` if you want to export React components.~ ~For Docusaurus 2, you can format MDX (v1) with Prettier.~
> 
> I saw your Markdown. Why don't you surround the code with a code block (`` ``` ~ ``` ``)? MDX treats your code as an actual export declaration.
> 
> https://v1.mdxjs.com/advanced/api

Thank you for your answer. It is because I translated this document that I encountered this problem. This React code block is the content of the original document and will eventually be rendered as a component.
If I were to write the document myself, it would be written according to this specification.

**Comment by tats-u** [comment]
Is the original document also hosted by Docusaurus?
If so it looks weird for me.
I wonder if the Markdown parser in Docusaurus could mistakenly treat `export ...` as the actual MDX export even though this document is `.md` not `.mdx`. (I don't know much about the details of the Markdown parsing process in Docusaurus)

**Comment by Alan3344** [comment]
> Is the original document also hosted by Docusaurus? If so it looks weird for me. I wonder if the Markdown parser in Docusaurus could mistakenly treat `export ...` as the actual MDX export even though this document is `.md` not `.mdx`. (I don't know much about the details of the Markdown parsing process in Docusaurus)

You can run this project. Part of the React code is written directly in the .md file and then finally rendered. Because changing the file will trigger automatic saving and formatting.
I debugged this formatting problem for a long time, and finally I found the reason. There cannot be blank lines in the export statement or component, otherwise the build will fail.
This is also the first time I encountered compilation failure due to formatting.
Reference project [https://github.com/flet-dev/website/tree/main](https://github.com/flet-dev/website/tree/main)

**Comment by tats-u** [comment]
I will.

**Comment by tats-u** [comment]
![image](https://github.com/prettier/prettier-vscode/assets/12870451/0dd9d38f-6b49-451d-8e30-edb471d7dec4)

After renaming to `.mdx`, Prettier seems to work well.

**Comment by Alan3344** [comment]
> ![image](https://user-images.githubusercontent.com/12870451/267652023-0dd9d38f-6b49-451d-8e30-edb471d7dec4.png)
> 
> After renaming the document to `.mdx`, Prettier seems to work well.

That’s right👍, changing the suffix will solve the problem, and formatting will not automatically add line breaks
This is simply awesome 🥹

**Comment by tats-u** [comment]
> changing the suffix will solve the problem, and formatting will not automatically add line breaks
Right. This is the ideal solution.

**Comment by Alan3344** [comment]
> > changing the suffix will solve the problem, and formatting will not automatically add line breaks
> 
> Right. This is the ideal solution. Prettier doesn't support MDX-extended syntax in plain Markdowns `.md`.

Thank you very much, I tried your solution and the problem is now solved

**Comment by Alan3344** [comment]
> I've listed problematic Markdown files and wrote the issue in the project. You can utilize my info there.

Okay👌, I saw it

**Comment by Alan3344** [comment]
It seems that using `.mdx` does not solve the problem. Is it a previous misunderstanding?
I downloaded the plug-in and can parse this document normally, but [`docusaurus.io`](https://docusaurus.io/) still has parsing errors.
It doesn’t seem to be a formatting issue.
![image](https://github.com/prettier/prettier-vscode/assets/60773912/be3b9763-7bd7-4026-bb23-d9b607eed7bd)

Test code

```mdx
---
title: Gallery Test
slug: gallery
---

<!-- import Card from '@site/src/components/card'; -->

import Card from '../../../src/components/card';

export const GalleryCard = ({
  title,
  liveUrl,
  sourcesUrl,
  description,
  imageUrl,
}) => (
  <Card>
    <a className='gallery-live-link' href={liveUrl}>
      <img src={'/img/gallery/' + imageUrl} className='screenshot-100' />
      <h2>{title}</h2>
      <div className='gallery-description'>{description}</div>
    </a>
    <div className='gallery-footer'>
      <a
        className='gallery-github-link'
        href={sourcesUrl}
        title='View source code'></a>
    </div>
  </Card>
);

# Gallery

<div className='margin-top--lg'>
  <section className='gallery-grid'>
    <GalleryCard
      title='Controls gallery'
      imageUrl='controls-gallery.png'
      description='Interactive showcase app for Flet controls with code samples.'
      liveUrl='https://flet-controls-gallery.fly.dev/'
      sourcesUrl='https://github.com/flet-dev/examples/tree/main/python/apps/controls-gallery'
    />
    <GalleryCard
      title='To-Do'
      imageUrl='todo.png'
      description='A classic To-Do app inspired by TodoMVC project.'
      liveUrl='https://gallery.flet.dev/todo/'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/apps/todo/todo.py'
    />
    <GalleryCard
      title='Icons browser'
      imageUrl='icons-browser.png'
      description='Quickly search through icons collection to use in your app.'
      liveUrl='https://gallery.flet.dev/icons-browser/'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/apps/icons-browser/main.py'
    />
    <GalleryCard
      title='Calculator'
      imageUrl='calc.png'
      description='A simple calculator app.'
      liveUrl='https://gallery.flet.dev/calculator/'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/tutorials/calc/calc.py'
    />
    <GalleryCard
      title='Solitaire'
      imageUrl='solitaire.png'
      description='Learn how to handle gestures and position controls on a page.'
      liveUrl='https://gallery.flet.dev/solitaire/'
      sourcesUrl='https://github.com/flet-dev/examples/tree/main/python/tutorials/solitaire/solitaire-final-part1'
    />
    <GalleryCard
      title='Chat'
      imageUrl='chat.gif'
      description='Multi-user realtime chat.'
      liveUrl='https://flet-chat.fly.dev'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/tutorials/chat/chat.py'
    />
    <GalleryCard
      title='Flet animation'
      imageUrl='flet-animation.png'
      description='Implicit animations in Flet.'
      liveUrl='https://gallery.flet.dev/flet-animation/'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/apps/flet-animation/main.py'
    />
    <GalleryCard
      title='Counter'
      imageUrl='counter.png'
      description='Counter with button click event handlers.'
      liveUrl='https://gallery.flet.dev/counter/'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/apps/counter/counter.py'
    />
    <GalleryCard
      title='Routing'
      imageUrl='routing.gif'
      description='URL routing between views.'
      liveUrl='https://gallery.flet.dev/simple-routing/'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/apps/routing-navigation/home-store.py'
    />
    <GalleryCard
      title='Hello, world!'
      imageUrl='hello-world.png'
      description='All examples start with that!'
      liveUrl='https://gallery.flet.dev/hello-world/'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/apps/hello-world/hello.py'
    />
    <GalleryCard
      title='Greeter'
      imageUrl='greeter.png'
      description='Interactive form in Flet.'
      liveUrl='https://gallery.flet.dev/greeter/'
      sourcesUrl='https://github.com/flet-dev/examples/blob/main/python/apps/greeter/greeter.py'
    />
  </section>
</div>

```
