### ISSUE TITLE
Language Specific Indentaion

### ISSUE THREAD

**Issue by ortegamarcel** [prettier/prettier-vscode#3157]
It would be nice to make it possible to have different indentation settings for different languages.

I would like this to work as intended. By default everything has an indentation of 4 spaces, but js and ts files of 2.

**Example settings.json:**

```json
{
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "files.autoSave": "onFocusChange",
    "editor.detectIndentation": true,
    "editor.tabSize": 4,
    "prettier.tabWidth": 4,
    "[javascirpt]": {
        "prettier.tabWidth": 2
    },
    "[typescript]": {
        "prettier.tabWidth": 2
    }
}
```

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
