### ISSUE TITLE
.prettierignore not picking up

### ISSUE THREAD

**Issue by dagda1** [prettier/prettier-vscode#316]
Hi,

I have the following `.prettierignore` file in the root of my project:
```
**/*.ejs
**/*.md
```

I have the following setting:
```
  "prettier.ignorePath": ".prettierignore"
```

But when I save on my .ejs file, it formats the file.

**Comment by azz** [comment]
Prettier doesn't support ejs files. Could you try disabling the extension, reloading the window and saving the file to check that it's actually the built-in code formatter?

**Comment by dagda1** [comment]
Aplologies, must be vscode.
