### ISSUE TITLE
Doens't Prettier Code Formatting on Save

### ISSUE THREAD

**Issue by iwsouza** [prettier/prettier-vscode#3162]
Type: <b>Bug</b>

Take any file and try to save. It isn't formatted.

settings.json
![image](https://github.com/prettier/prettier-vscode/assets/86499400/9b51225e-f142-4c83-9515-88eeb2255619)

extension
![image](https://github.com/prettier/prettier-vscode/assets/86499400/c37cb26c-843d-434e-b736-a2c804289050)

Extension version: 10.1.0
VS Code version: Code 1.82.3 (Universal) (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T11:06:17.496Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 173b653f-801b-4adc-b311-27f13d51619e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by steve-taylor** [comment]
If you're using Prettier 3, downgrade this extension to 9.19.0. It's the last version of the extension that actually works with Prettier 3.

**Comment by Droppix** [comment]
don't work!

**Comment by iwsouza** [comment]
Don't work for me :/

**Comment by iwsouza** [comment]
More than one thing. It doesn't work when I added `postcss.config.js` with `module.exports`

But when I delete it, it doesn't work again.

**Comment by jonnylink** [comment]
> If you're using Prettier 3, downgrade this extension to 9.19.0. It's the last version of the extension that actually works with Prettier 3.
Still getting an invalid version error with prettier v3.0.3

**Comment by austinm911** [comment]
> If you're using Prettier 3, downgrade this extension to 9.19.0. It's the last version of the extension that actually works with Prettier 3.

thanks - this was driving me nuts. the extension wasn't recognizing my config file.

**Comment by ExpliuM** [comment]
@iwsouza 
share also the output 
<img width="1039" alt="image" src="https://github.com/prettier/prettier-vscode/assets/8546103/d89ce142-8e80-40ba-99f1-3821aa37f289">

**Comment by ericbiewener** [comment]
Still an issue on the latest version (10.1.0)
