### ISSUE TITLE
Undefined rule font-family-no-missing-generic-family-keyword

### ISSUE THREAD

**Issue by Eldair** [prettier/prettier-vscode#317]
Hi,

Just noticed this output error on formatting scss file
`Undefined rule font-family-no-missing-generic-family-keyword`

prettier-vscode 1.0.1

**Comment by CiGit** [comment]
Is that with stylelint ?

**Comment by Eldair** [comment]
Yeah, the issue is actually [here](https://github.com/hugomrdias/prettier-stylelint/issues/8)

**Comment by Eldair** [comment]
Is it possible to do something from here ? Nobody is doing anything there and maybe stylelint dependency could be overwritten here to include the latest version.

**Comment by entepe85** [comment]
I actually managed to temporarily solve this problem by installing prettier (^1.11.1) and prettier-stylelint (^0.4.2), but not stylelint as local node modules in my project folder.

**Comment by Eldair** [comment]
Shouldn't this dep. be replaced? There is no work being done on it and no pull requests being merged.

**Comment by ntotten** [comment]
Version 3.0 will require linting extensions to be installed in the local project. This is likely an issue with version mismatch which will no longer be possible when installing yourself.
