### ISSUE TITLE
SCSS map formatting incorrectly

### ISSUE THREAD

**Issue by cdwmhcc** [prettier/prettier-vscode#3174]
### Expected result

``` scss
$card-app: map.merge(
  (
    "text-color": getCssVar("text-color"),
    "subtitle-text-color": getCssVar("text-color", "placeholder"),
    "version-text-color": getCssVar("text-color", "disabled")
  ),
  $card-app
);
```

### Actual result

``` scss
$card-app: map.merge(
                (
                        "text-color": getCssVar("text-color"),
                        "subtitle-text-color": getCssVar("text-color", "placeholder"),
                        "version-text-color": getCssVar("text-color", "disabled")
                ),
                $card-app
);
```

### Additional information

![image](https://github.com/prettier/prettier-vscode/assets/8030134/13bcbf33-8d99-4b00-8535-4ff6782a5b12)

**WebStorm Version**: 2023.2.2

**Prettier Extension Version**: 3.0.3

**OS and version**: windows 11

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
