### ISSUE TITLE
I want to add a space between the JS method function name and the parenthesis. how to set it?

### ISSUE THREAD

**Issue by qingyuun** [prettier/prettier-vscode#318]
I want to add a space between the JS method function name and the parenthesis. how to set it?

**Comment by CiGit** [comment]
There is no such thing in prettier. ref: https://github.com/prettier/prettier/issues/1139
However, this should be possible with eslint https://eslint.org/docs/rules/space-before-function-parentheses

**Comment by antonreshetov** [comment]
Such a situation occurred when I upgraded from 1.0.1 to 1.1.0. I'm using eslint and standard JS style. In 1.1.0 prettier ignores this rule. I rolled back to 1.0.1 and all was well.

Here is a link to 1.0.1 https://esbenp.gallery.vsassets.io/_apis/public/gallery/publisher/esbenp/extension/prettier-vscode/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

After downloading, rename the extension from vsix to vsixpackage and install

**Comment by azz** [comment]
Did the extension stop using `prettier-eslint` entirely, or was it just one rule?

**Comment by azz** [comment]
I think it is this issue. https://github.com/prettier/prettier-eslint/issues/156

@CiGit Maybe bump `prettier-eslint` and release a new version?

**Comment by antonreshetov** [comment]
@azz Not quite understand the question. You say that this problem is related to an outdated version prettier-eslint?

**Comment by azz** [comment]
Yeah, this extension bundles in `prettier-eslint` (which it uses when `prettier.eslintIntegration` is `true`). I _suspect_ the issue your facing is a consequence of the aforementioned issue. You could try `npm install prettier-eslint@latest` and it might work.

**Comment by antonreshetov** [comment]
@azz No, out. Probably not the problem. I have installed the latest prettier-eslint 8.7.5 and still is ignoring the rules

**Comment by CiGit** [comment]
Will update prettier-eslint, but there was no change between 1.0.1 and 1.1.0 ...

@antonreshetov you have to update it in the extension itself, we don't pick your local version.

**Comment by CiGit** [comment]
Isn't it an issue between eslint 3 and eslint 4 ? The rule is named _space-before-function-paren_ in v4. Bundled version is also an eslint@4 in 1.0.1

**Comment by CiGit** [comment]
Just released version 1.1.1

**Comment by antonreshetov** [comment]
I updated to 1.1.1, the result is now somewhat deteriorated

![screenflow2](https://user-images.githubusercontent.com/17480987/35034701-1a4ebdc4-fb80-11e7-9a96-6608293f3c3c.gif)

**Comment by CiGit** [comment]
What's wrong?
Can you post a before / after **text** please :-)

**Comment by antonreshetov** [comment]
Briefly, again not working correctly https://eslint.org/docs/rules/space-before-function-parentheses

**Comment by CiGit** [comment]
>This rule was removed in ESLint v1.0 and replaced by the space-before-function-paren rule

**Comment by Spittal** [comment]
Hey, I'm still having this issue. 

No matter what I do regardless of the rule I have set in my `.eslintrc.js` I can't seem to get prettier to add the space between function and parenthesis.

I am totally up to date with both ESLint and Prettier and have the "Prettier: Eslint Integration" enabled.

I end up with a situation, that when I format document it ends up spitting ESLint errors, because there's no space between function name and parenthesis.

This is after a `Format Document` command
![image](https://user-images.githubusercontent.com/1229177/52367235-6edf3800-2a00-11e9-9909-f747341bb352.png)

**Comment by mike1e** [comment]
@Spittal Were you able to resolve this issue?

**Comment by Spittal** [comment]
Not yet, sorry. @mike1e

**Comment by kivervinicius** [comment]
any update?

**Comment by mesqueeb** [comment]
I want to use Prettier but with Standard JS formatting rules. Does anyone know a good place for me to look first?

**Comment by rlam3** [comment]
same issue. is there a workaround ?

**Comment by opravil-jan** [comment]
Hello,

this bug is really annoying. What  prevents it from resolving this issue?

Thank you

Jan Opravil

**Comment by chroriginal** [comment]
Still an issue, this is very annoying!

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration

**Comment by brodybits** [comment]
FYI the equivalent of space-before-function-paren is supported by my [`prettierx`](https://www.npmjs.com/package/prettierx) fork.
