### ISSUE TITLE
respect rule declaration-colon-newline-after

### ISSUE THREAD

**Issue by zyy7259** [prettier/prettier-vscode#319]
original css

```css
background: url(http://webapi.amap.com/theme/v1.3/images/newpc/poi-1.png) no-repeat;
```

formated css

```css
background: url(http://webapi.amap.com/theme/v1.3/images/newpc/poi-1.png)
    no-repeat;
```

the formatted css does not respect the [rule](https://stylelint.io/user-guide/rules/declaration-colon-newline-after/) `declaration-colon-newline-after: always-multi-line` from [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard/blob/7b76d7d0060f2e13a331806a09c2096c7536b0a6/index.js#L47)

![image](https://user-images.githubusercontent.com/2311742/34564754-f9164a10-f192-11e7-9cea-9a812a8c85b2.png)

**Comment by choi2k** [comment]
@zyy7259 I get the exactly the same issue about this rule, may I know why this question has been closed?

**Comment by zyy7259** [comment]
@choi2k add [stylelint-config-prettier](https://github.com/shannonmoeller/stylelint-config-prettier) to the stylelint config file to turns off all rules that are unnecessary or might conflict with Prettier.

PS: it is just like add [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) to the eslint config file to turns off all rules that are unnecessary or might conflict with Prettier (for js).

**Comment by choi2k** [comment]
@zyy7259 umm... It may be a temporary solution but I am looking for a way to make it works instead of just turn it off. Let see if others working on it or not .. :(

**Comment by zyy7259** [comment]
@mike-rotate This issue is closed as I think it's not a problem.

The [`stylelint-config-prettier`](https://github.com/prettier/stylelint-config-prettier) config will disable the rule [`declaration-colon-newline-after`](https://stylelint.io/user-guide/rules/declaration-colon-newline-after/)

Which means prettier can format the document whatever it likes, and stylelint won't give any warnings or errors about the result.

**Comment by mike-rotate** [comment]
ah i see - thanks for the reply/info!
