### ISSUE TITLE
Prettier does not format in multi-folder repositories whilst using the .code-workspace config.

### ISSUE THREAD

**Issue by aidanm1999** [prettier/prettier-vscode#3201]
### Summary

Prettier does not format in multi-folder repositories whilst using the `.code-workspace` config.

### Github Repository to Reproduce Issue

https://github.com/aidanm1999/prettier-vscode-multi-workspace-config

This repository is set up like so:

- `workspace-1` - a folder containing a dummy JSON document to simulate formattable files
- `group-1` - a folder containing 2 workspaces
  - `workspace-2` - a folder containing a dummy JSON document to simulate formattable files
  - `workspace-3` - a folder containing a dummy JSON document to simulate formattable files 
- `.prettierrc` - default prettier config
- `.prettierignore` - default prettier ignore config 
- `repo.code-workspace` - file containing workspace config

### Steps To Reproduce:

1.  Open the repository through the `repo.code-workspace`
1.  This will open the repo with workspaces
1.  Open the Prettier output pane
1.  Open `repo.code-workspace` and comment out folders 1, 2 and 3
    - This is to ensure the files open through the 'Root' folder
1.  Then open any of the JSON documents and format the file
1.  Should format successfully 
1.  Uncomment the folders in the `repo.code-workspace`
1.  Now re-open the document and try to format

### Expected result

The Prettier output should have logged a successful reformat 

### Actual result

The prettier output errors out: 

```
["INFO" - 17:04:20] Formatting file:///Users/me/Developer/prettier-vscode-multi-workspace-config/group-1/workspace-2/doc.json
["ERROR" - 17:04:20] Invalid prettier configuration file detected.
["ERROR" - 17:04:20] ENOENT: no such file or directory, open '/Users/me/Developer/prettier-vscode-multi-workspace-config/group-1/workspace-2/.prettierrc'
Error: ENOENT: no such file or directory, open '/Users/me/Developer/prettier-vscode-multi-workspace-config/group-1/workspace-2/.prettierrc'
```

Now this would be fine if you could write `${workspaceFolder:Root}/.prettier`, however this does not resolve: 

```
Error: ENOENT: no such file or directory, open '/Users/me/Developer/prettier-vscode-multi-workspace-config/group-1/workspace-2/${workspaceFolder:Root}/.prettierrc'
```

It would be ideal if the Prettier extension could resolve the `workspaceFolder` or bubble up a search to look at parent, grandparent or great-grandparent directories.

### Additional information

**VS Code Version**: `1.84.2`

**Prettier Extension Version**: `10.1.0`

**OS and version**: `MacOS Sonoma 14.1`

## Prettier Log Output

Relevant logs logged above

**Comment by aidanm1999** [comment]
Still an issue

**Comment by jhgeluk** [comment]
Still an issue
