### ISSUE TITLE
Sorry, but there is no formatter for 'php'-files installed.

### ISSUE THREAD

**Issue by Tanmccuin** [prettier/prettier-vscode#322]
May seem an obvious fix but i'm not sure where to go from here. when I attempt to format a page of PHP, I get the above error. 

Have NPM / Node / Homebrew installed as well, is there a separate VSCode package that I need to grab?

**Comment by azz** [comment]
Prettier doesn't support PHP yet. There's a work in progress plugin at https://github.com/prettier/prettier-php, but it hasn't been published yet.

**Comment by saber13812002** [comment]
there are php formatter if search in extension toolbar
