### ISSUE TITLE
how many of the 1594 closed tasks were swept under the rug due to "staleness"?

### ISSUE THREAD

**Issue by anxpara** [prettier/prettier-vscode#3244]
example of a bot auto closing a task due to lack of response from repo maintainers: https://github.com/prettier/prettier-vscode/issues/3083

it's not the task filer's responsibility to prevent the task from becoming "stale" or being closed. and once the bot closes a task, it's not possible for the filer to re-open it.

this repo has 50 open tasks and 1594 closed tasks. makes you wonder how many bugs and issues have been swept under the rug.

**Comment by anxpara** [comment]
tagging the first person in the list of contributors

@ntotten

**Comment by ntotten** [comment]
Feel free to send a PR to fix whatever you want. Nobody here gets paid to do this. ¯\_(ツ)_/¯
