### ISSUE TITLE
Prettier is trying to access "node-modules", should be accessing "node_modules"

### ISSUE THREAD

**Issue by anxpara** [prettier/prettier-vscode#3245]
Running the VS Code Prettier plugin on Windows.

Versions 9.15.0 through 9.19.0 are broken. 9.14.0 is the last working version for me.

I don't use format on save, i just use ctrl+shift+f. When I hit my shortcut, nothing happens. If i use ctrl+shift+p and then type "format document with" and then select prettier, I get an actual error dialog. "Error loading node module 'c:\Users........\node-modules\prettier"

node_modules has an underscore, not a hyphen

(re-opening as new issue since I can't re-open the original https://github.com/prettier/prettier-vscode/issues/3083 )

**Comment by anxpara** [comment]
@ntotten

**Comment by AkiraVoid** [comment]
And there's no response to you in 2 weeks (nor to others).

**Comment by lts20050703** [comment]
@anxpara Is there any reason you're not using v10.1.0?

**Comment by anxpara** [comment]
> @anxpara Is there any reason you're not using v10.1.0?

versions listed are what were available when the issue was first posted. this is a repost

**Comment by lts20050703** [comment]
> > @anxpara Is there any reason you're not using v10.1.0?
> 
> versions listed are what were available when the issue was first posted. this is a repost

The latest version now is v10.1.0, maybe it is fixed?

**Comment by anxpara** [comment]
Did more digging, and the '-' was my fault. I don't remember what original issue caused me to try setting the path myself, but it's gone now.
