### ISSUE TITLE
Update extension name on README

### ISSUE THREAD

**Issue by nfriend** [prettier/prettier-vscode#327]
Currently, the README reads:

> Install through VS Code extensions. Search for "Prettier - JavaScript formatter"

But the extension is now named "Prettier - Code formatter".

The only reason that this is an issue is that there are now other extensions named "Prettier - JavaScript formatter", which might cause people to accidentally install the wrong one (I almost did):

![image](https://user-images.githubusercontent.com/1638631/34827646-3ccf33de-f6b1-11e7-9080-cdcd4b0f239b.png)

**Comment by azz** [comment]
Good catch! Do you want to open a PR for this?

**Comment by nfriend** [comment]
Sure, here's a PR: https://github.com/prettier/prettier-vscode/pull/328

**Comment by CiGit** [comment]
Thanks for your PR!
