### ISSUE TITLE
VS Code outlining expanded on save with prettier

### ISSUE THREAD

**Issue by sergeyzwezdin** [prettier/prettier-vscode#329]
I use `autoFixOnSave`. When I collapse outlining of some piece of code, it expanding back on save because of prettier.
Is it possible to make prettier to keep outlinings in their current state?

![outlining](https://user-images.githubusercontent.com/800755/34967197-b54eb0bc-fa82-11e7-92b2-9b884f114d07.gif)

**Comment by azz** [comment]
`autoFixOnSave` is an vscode-eslint thing, you should move this issue there.

https://github.com/Microsoft/vscode-eslint/issues

**Comment by tysonmatanich** [comment]
I'm having the same issue but with `"editor.formatOnSave": true,` which I believe is Prettier not ESLint.

**Comment by Shaker-Hamdi** [comment]
I'm having the same issue ever since I started using Prettirer. 
Did anyone figure this one out?
