### ISSUE TITLE
Prettier uninstalled itself

### ISSUE THREAD

**Issue by tomy8910** [prettier/prettier-vscode#331]
I restarted my vscode-insiders Version 1.20.0-insider (1.20.0-insider). After I reopened it, the prettier extension surprisingly uninstalled itself. And now whenever I try to download it, it either causes my insiders-build to crash or not install at all. Is there any way to resolve this?

**Comment by CiGit** [comment]
Uninstalled! :scream: 
Is the extension still in your extensions folder? `$HOME/.vscode-insiders/extensions`

If it's still there, remove it and try reinstalling. 
Check your debugger console for a potential useful log.

**Comment by tomy8910** [comment]
That helped! Thank you so much for your help and this wonderful extension!

**Comment by euanmillar** [comment]
Happening to me too.  VS Code removed Prettier automatically and it took a very long time for it to reinstall although it did it eventually.  Perhaps it is too soon to close this?

**Comment by tonymckendry** [comment]
This happened to myself and a coworker when updating to 1.20.0 yesterday - seems to still be an issue
