### ISSUE TITLE
What's the usage??

### ISSUE THREAD

**Issue by 7--** [prettier/prettier-vscode#333]
I don't have a command key. 
1. CMD + Shift + P -> Format Document
OR
1. Select the text you want to Prettify
2. CMD + Shift + P -> Format Selection

**Comment by 7--** [comment]
and i want it formatted like this https://angular.io/tutorial/toh-pt2

**Comment by azz** [comment]
## Using Command Palette (CMD/CTRL + Shift + P)

https://github.com/prettier/prettier-vscode#using-command-palette-cmdctrl--shift--p

**Comment by 7--** [comment]
Theres no commands found that say "format selection". I see prettier installed in the bottom right

**Comment by azz** [comment]
You need to share more information for us to be able to help.

- Are you using `prettier.eslintIntegration`? 
- What is your `.eslintrc` file (if any?)
- What is in your `.prettierrc` file (if any?)
- What are your vscode settings `settings.json`?

**Comment by 7--** [comment]
Thank you but nevermind decided to format myself in Notepad++
