### ISSUE TITLE
prettier-ignore doesn't work with table title

### ISSUE THREAD

**Issue by seven1240** [prettier/prettier-vscode#3332]
**Is your feature request related to a problem? Please describe.**

`<!-- prettier-ignore -->` works in #762 but when a table has a title, the inserted `<!-- prettier-ignore -->` might cause trouble on some markdown parser, e.g. Pandoc would ignore the title when rendering the following table.

```
: table title
<!-- prettier-ignore -->

| a | b|
|--| ---|
| aaa | bbb|
```

As it's not possible to let all markdown parser to ignore the *comment*, Is it possible to put the prettier-ignore before the title and still ignores the following table? 

e.g. 

```
<!-- prettier-ignore -->
: table title
```

**Describe the solution you'd like**

```
<!-- prettier-ignore -->
: table title

| a | b|
|--| ---|
| aaa | bbb|
```

**Describe alternatives you've considered**

**Additional context**

Thanks.

**Comment by tv42** [comment]
@seven1240 https://prettier.io/docs/en/ignore.html#range-ignore

**Comment by seven1240** [comment]
nice. it works, thanks.
