### ISSUE TITLE
VSCode Prettier 10.1.0 - doesn't work with angular Angular Control Syntax 

### ISSUE THREAD

**Issue by radek-vizlib** [prettier/prettier-vscode#3334]
I've set `.prettierrc` with:
```json
"overrides": {
    "files": ["*.html"],
    "options": {
        "parser": "angular"                  
     }
 }
```
as suggested in https://github.com/prettier/prettier/issues/15833
But seems that it doesn't work with the VSCode extension.

As in [PLAYGROUD LINK](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgMwAQApJQAm6M60AlNsNhjrgIZQQwAWcATgMLTGkVUAdKAB5iANwB8AQQBCnYQHpxEoQF9s61HAA2AZziCRygCIBRAGKLlakABoQEAA58ou5KHrt2EAO4AFTwQ3FHptH3oATzd7ACN2ejAAazgYAGV6AFs4ABl0KDhkTFD9WPiklNTHBLyAc2QYdgBXOHt9DPR6ppaQOAAPRw50LNhQgBUOKE90OGCivW7dWu04AEVG5gKkOZKQACtdXtSl1fX4QuLugEdTuD9vR2CQel0AWny4Qg+7EAb6dG1atwMhl6MgntptN9FlAasspDAGugYo14H4OLl8ud5vYWDAMtoAOosEgzKpgOCpIIkdBiEgRMFgXTREBiZoASSICDSYHY6GcUiIqRgEWWWJ2jm8+gJ8UcYIlMw4YgK9jy+nYMDu9BqILF3Sq7DVYMYNUa2k83wleRgBPQhFYyAAHAAGezsODXdBuzXa0FbC72GD0GI2u0sZAAJnsjX0oyDs39PQyMQ+n0I2WNjS1cHMEHYIIRtSNKIgIFUqiAA) 

Expected behavior:
INPUT:
```html
@if (condition) { @if (anotherCondition) {
<div>ABC</div>
} } @else {
<div>DEF</div>
}
````
OUTPUT:
```html
@if (condition) {
  @if (anotherCondition) {
    <div>ABC</div>
  }
} @else {
  <div>DEF</div>
}
```
But it doesn't work.

**Comment by akostmOR** [comment]
The same problem here, I needed to disable the plugin, with @switch I have the same behaviour. Horrible and really hard to read.

**Comment by Tucaen** [comment]
Having something like this
```
@if (condition) {
    <div>ABC</div>
}

@if (anotherCondition) {
   <div>DEF</div>
} 

@if (thirdCondition) {
  <div>GHI</div>
}
```
results in 
```
@if (condition) {
    <div>ABC</div>
} @if (anotherCondition) {
   <div>DEF</div>
} @if (thirdCondition) {
  <div>GHI</div>
}
```

Don't know if this is intended, but I think it should keep the input as it is in such a case. The received output looks like a if-elseif- else statement at first glance.

**Comment by jonelleamio** [comment]
I use prettier inside eslint, so i tried this :
```
  {
      "files": ["*.component.html"],
      "extends": ["plugin:@angular-eslint/template/recommended", "plugin:prettier/recommended"],
      "rules": {
        "@angular-eslint/template/prefer-control-flow": "warn",
        "prettier/prettier": ["error", { "overrides": [{ "options": { "parser": "angular" } }] }]
      }
    }
```
    
    which doesn't  work
    while this inside .prettierrc works
    
```
    "overrides": [
    {
      "files": "*.component.html",
      "options": {
        "parser": "angular"
      }
    }
  ]
```
  
 Can someone help ?

**Comment by radek-vizlib** [comment]
The root cause is here https://github.com/prettier/prettier-vscode?tab=readme-ov-file#prettier-version-3

This is workaround: 
Add to `devDependencies` prettier that supports angular parser e.g. `npm i prettier@3.2.5 -D`
Then it will works as expected.

**Comment by tomasdev** [comment]
For anyone using a context without a package.json, you can do the following:

1. Enable `"prettier.resolveGlobalModules": true` in your VSCode settings.json
2. `npm i -g prettier` to install latest prettier globally, as of today that is 3.2.5 
3. Ensure `parser: angular` in your prettier config as stated above.

This gave my .ng.html templates sooooo much better syntax than before.

**Comment by gindyo** [comment]
For me it turned out I had a reference to old version of prettier in my dev dependencies in package.json I updated it to v3.2.5  and it is working as it should.

**Comment by xylplm** [comment]
Unfortunately, the configuration did not take effect in the latest Angular 18+VSCode. Still not supporting new syntax
![image](https://github.com/user-attachments/assets/616c52e1-254b-430f-9272-fb6b3be366ba)

As shown in the figure, the new syntax, such as @ if, does not have indentation and is mixed together.I have installed the latest version of Prettier - Code shaper
】VS code extension. Its version is v11.0.0.
