### ISSUE TITLE
Support .prettierrc with dashed options

### ISSUE THREAD

**Issue by omahlama** [prettier/prettier-vscode#334]
Prettier supports both `print-width` and `printWidth` in .prettierrc, when you run it on the command line. Prettier-vscode works only with `printWidth`. Same for all other properties with dashes. This should be either fixed or a note should be added in readme to use camel case.

**Comment by azz** [comment]
> Prettier supports both print-width and printWidth in .prettierrc

Not intentionally, `.prettierrc` files should always be camel cased. I think there was a bug in Prettier which allowed camel-cased config, but I thought it was fixed.

**Comment by azz** [comment]
Just tested it, you're right, there must have been a regression.

**Comment by azz** [comment]
Raised a bug here: https://github.com/prettier/prettier/issues/3756

**Comment by omahlama** [comment]
Ok good to know, anyway I fixed our config to be camel cased, but wanted to open an issue in case someone else runs into this.

**Comment by azz** [comment]
Yeah, when we fix this in Prettier you'll get a warning when you use dashed options so there will be no room for confusion here.
