### ISSUE TITLE
Inconsistent doctype case formatting

### ISSUE THREAD

**Issue by MrDanielHarka** [prettier/prettier-vscode#3358]
No, I don't have a preference if the doctype is lowercase or uppercase, like the below mentions:
- [Print <!doctype html> lowercase rather than uppercase](https://github.com/prettier/prettier/issues/6502) #6502
- [Print HTML5 doctype in lowercase](https://github.com/prettier/prettier/pull/7391) #7391
- [!DOCTYPE is forced to lowercase](https://github.com/prettier/prettier/issues/15096) #15096
- [Prettier breaks XHTML documents by incorrectly lowercasing DOCTYPE](https://github.com/prettier/prettier/issues/15476) #15476

I really don't care. But please make it at least consistent. Now I get changes in git just because Prettier formats it inconsistently.

**Prettier v10.4.0**

**Case 1:** Prettier auto-formatting in VSCode with extension.

Input:

```
<!doctype html>
```

Output:
```
<!DOCTYPE html>
```

**Case 2:** Prettier CLI formatting using `bunx prettier index.html`

Input:

```
<!DOCTYPE html>
```

Output:
```
<!doctype html>
```

**Expected behavior:**
The two tools should have the same case formatting for the doctype tag, whichever it is.

**Comment by studioswong** [comment]
Seconding this issue as I had just experienced the same while formatting my code via the CLI, and was confused about the discrepancy - what is the prettier's team's recommendation on this? ( I noticed multiple discussions on the debate between uppercase and lowercase, including [this one](https://github.com/prettier/prettier/issues/15096) - while my understanding is that the prettier team recommends lowercase and enforces it by default back in 2019, I wonder is this still the case now?)

**Comment by eligrey** [comment]
Lowercase is invalid XML. This shouldn't be difficult to resolve.

**Comment by omichel** [comment]
I found the reason for this problem: it seems that the Prettier VSCode plugin version 10.4.0 uses Prettier version 2.8.8 whereas the latest version of Prettier is 3.3.2 (as of today). Prettier 2.8.8 produces `<!DOCTYPE html>` whereas version 3.3.2 produces `<!doctype html>`. If you want the CLI version to match with the VSCode plugin, you should install Prettier 2.8.8 CLI. See [details](https://marketplace.visualstudio.com/items/esbenp.prettier-vscode/changelog).

**Comment by ntotten** [comment]
The vscode extension resolves the local version of prettier if there is one, otherwise it falls back to 2.8.8. It is recommended that you install prettier in your project to keep the results consistent.

**Comment by infanasotku** [comment]
> The vscode extension resolves the local version of prettier if there is one, otherwise it falls back to 2.8.8. It is recommended that you install prettier in your project to keep the results consistent.

Thanks! It works fine for me.
