### ISSUE TITLE
Use prettier-eslint And prettier-stylelint

### ISSUE THREAD

**Issue by MarkSky** [prettier/prettier-vscode#336]
I set VSCode:
```
prettier.eslintIntegration: true
prettier.stylelintIntegration: true
```

Should I use NPM to install in my project? Or Prettier-VSCode has already include them?
```
npm install --save-dev prettier-eslint
npm install prettier-stylelint --save-dev
```

**Comment by azz** [comment]
They're built into the extension so you don't need to install them.

**Comment by MarkSky** [comment]
Thank you for your reply.
But I found it didn't work in css file, and I got a notice:
No configuration provided for dd:\Project\HClientNew\css\Site.css::\Project\HClientNew\css\Site.css
I don't know what to do.

**Comment by CiGit** [comment]
Maybe you _must_ have to provide a stylelintrc file.

/cc @hugomrdias

**Comment by kanlukasz** [comment]
I can't configure that too and what is worst i can't find good instructions 😕
I enable `"prettier.stylelintIntegration": true,` in VSCode settings.json but what now?

1. Do i need to install the stylelint?
2. From where should i take settings? from here?  https://stylelint.io/user-guide/example-config
2. Where should i put settings from stylelint?
3. Can i put that in VSCode settings.json? (i would like to keep this settings globally, not only per project)

Can anyone help with this? or someone have any step by step guide maybe ?

**Comment by ntotten** [comment]
See documentation on linting integration: https://github.com/prettier/prettier-vscode#vs-code-eslint-and-tslint-integration
