### ISSUE TITLE
Use LanguageStatusItem API for the status bar item

### ISSUE THREAD

**Issue by mlntr** [prettier/prettier-vscode#3363]
Use VS Code's [LanguageStatusItem API](https://vscode-api.js.org/interfaces/vscode.LanguageStatusItem.html) instead of having a unique implementation that is inconsistent with other language utility extensions and formatters. 
It's easy to show/hide when the user wants it (can pin to the status bar too) rather than cluttering being in the way if it's not disabled.

![image](https://github.com/prettier/prettier-vscode/assets/17552475/043e6911-31de-4efc-ac86-e2d017b9902a)

**Comment by ntotten** [comment]
Added in https://github.com/prettier/prettier-vscode/pull/3507
