### ISSUE TITLE
prettier bug in Vue

### ISSUE THREAD

**Issue by haro1d** [prettier/prettier-vscode#3367]
Before using prettier:
`
@click="row = scope.row; visible = true"
`

After:
@click="
    row = scope.row
    visible = true
"

Please note: Missing ";" results in an error

**Comment by haro1d** [comment]
> This issue has been labeled as stale due to inactivity. Reply to keep this issue open.

But the bug does exist and should be fixed,I'm still waiting

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
