### ISSUE TITLE
Prevents re-do of files changes after file Save

### ISSUE THREAD

**Issue by benfrain** [prettier/prettier-vscode#337]
This plugin seems to be preventing the default redo functionality of VSCODE.

- VSCode Version: Version 1.20.0-insider (1.20.0-insider)
- OS Version: Mac 10.12.6 (16G1114)

With this extension enabled, here are the steps to reproduce:

1. Edit a CSS/TS file a few times and save
2. Undo the prior changes with <kbd>CMD</kbd>+<kbd>Z</kbd> and save the file
3. Attempt to redo the changes with <kbd>Shift</kbd>+<kbd>CMD</kbd>+<kbd>Z</kbd>

Does this issue occur with prettier-vscode extension disabled?: 

No. With this extension disabled, it is possible to redo changes after save.

Not sure if this is a limitation with Prettier in general??

**Comment by CiGit** [comment]
I think you have format on save enabled.
When saving, it formats your file and thus changes it's content.
The history is overwritten with the new text. Thus you can't redo (go forward).

If the formatted code is the same as the input code, it shouldn't change the history (this is fine in my VSCode (1.19.2).
I'm pretty sure this limitation is with every extension that changes your text. Even with the default formatter. It avoids patch conflict at least

**Comment by RobinMalfait** [comment]
Yeah it is expected behaviour when you format on save 😅

**Comment by itsgracian** [comment]
thanks.
