### ISSUE TITLE
Vetur html format does not work with prettier-vscode > 1.0.1

### ISSUE THREAD

**Issue by ericcirone** [prettier/prettier-vscode#338]
All versions past 1.0.1 will not work with Vetur when setting Vetur to format html with js-beautify-html. Installing version 1.0.1 of prettier-vscode fixes this issue. Not sure if its a prettier-vscode issue or a Vetur issue.

Vetur issue here is: https://github.com/vuejs/vetur/issues/658

**Comment by CiGit** [comment]
Since prettier-vscode@1.1 we register a "vue" formatter for that language. The one provided by prettier. You can disable it with `prettier.disableLanguages: ["vue"]`

Currently prettier for vue does not format the template part of your vue SFC

**Comment by octref** [comment]
I suggest opt-in instead of opt-out for users to use prettier-vscode as formatter for Vue files.

Prettier's support for Vue is still very sparse: https://github.com/vuejs/vetur/issues/658#issuecomment-358737575

I do plan to help contribute to prettier for better Vue support. But at its current state I don't think it should be set as default formatter for Vue.

**Comment by azz** [comment]
Any way we can do it dynamically, i.e. If vetur is installed and running, don't register the vue language?

**Comment by azz** [comment]
@octref We'd love your help in improving Prettier's Vue support. Getting HTML support in Prettier completed is something that we've been super slow with.

**Comment by octref** [comment]
> Any way we can do it dynamically, i.e. If vetur is installed and running, don't register the vue language?

Yes with `vscode.extensions.getExtension('octref.vetur')`

> Getting HTML support in Prettier completed is something that we've been super slow with.

OK I'll start looking into it

**Comment by azz** [comment]
> Yes with `vscode.extensions.getExtension('octref.vetur')`

This sounds like the best avenue to me then, if someone is using this extension without vetur it will work as expected, and if they're using both they'll get vetur's formatting which is more feature-rich at the moment. 

> OK I'll start looking into it

❤️

**Comment by CiGit** [comment]
> Yes with `vscode.extensions.getExtension('octref.vetur')`

I'm not sure this is the best solution. If someone wanted to try prettier on vue files (for whatever reason), it would be hard to enable it. You would have to uninstall/disable vetur **and** install any other extension providing vue grammar (or at lease file association) to be able to use prettier.

I think we can simply disable it by default. Changing 1 option / reload seems easier to me. Maybe disable vetur's formatter if this is possible -> 2 options. This is maybe not easier, but certainly more common.

**Comment by octref** [comment]
Yeah, I agree having `prettier.disableLanguages: ["vue"]` seems to be better for now. Later when prettier has html formatter we can look into how we might collaborate.

Another quite popular need is to have initial indentation for style/script sections, but I don't know if that's something prettier wants to add.

**Comment by azz** [comment]
> If someone wanted to try prettier on vue files (for whatever reason), it would be hard to enable it.

vetur already runs Prettier, so you only need to use one extension at a time - I'm not sure I see the reasoning here.

**Comment by CiGit** [comment]
If I understood vetur correctly, it doesn't run prettier in "vue" mode.
It splits SFC and sends each supported section to prettier

**Comment by azz** [comment]
That's basically what Prettier 1.10 does anyway. They should be functionally identical with the exception of vetur handing the html to a different formatter.

**Comment by octref** [comment]
It also does a bunch of other things, some of which I don’t think it would make sense to add to prettier 
https://github.com/vuejs/vetur/issues/658#issuecomment-358737575

**Comment by azz** [comment]
Stylus is the only other lang missing? Doesn't seem unreasonable to make a prettier plugin for Stylus.

**Comment by octref** [comment]
Allow choice among multiple formatters might not be what prettier want to do. Many people prefer the TS formatter from TS language service instead of prettier's. 

Another is initial indentation, like so

```html
<script>
  // indent here
</script>
<style>
  // indent here
</style>
```

The community is half-half on this style choice, but I doubt adding Vue specific options here would be beneficial to prettier since it seems to be against prettier's philosophy.

**Comment by samburgers** [comment]
this comment got my .vue files formatting top to bottom in VSCode

https://github.com/vuejs/vetur/issues/543#issuecomment-358762077

**Comment by CiGit** [comment]
"vue" is now disabled by default
