### ISSUE TITLE
possible to autofix missing commas within object/array definitions?

### ISSUE THREAD

**Issue by AylwSt01** [prettier/prettier-vscode#339]
Is it possible to have prettier autofix missing commas in objects blocks and arrays?

var object = {
prop1:'this'  <----auto insert comma on this line (and any other that missing the comma
prop2:'this2'
}

i know this seems lazy, but i keep coming back to this thinking this would be useful!

**Comment by CiGit** [comment]
Your feature request belongs to https://github.com/prettier/prettier

Prettier must have valid JS as input, currently at least, parsers must understand your code.
