### ISSUE TITLE
prettier.tabWidth not working

### ISSUE THREAD

**Issue by borisyordanov** [prettier/prettier-vscode#340]
I have added a `.prettierrc` to the root of a project i am working on and have set tabWidth to be 4. When i format a document the code gets formatted but the tab width is 2 spaces wide. This happens to all types of files (.js, .scss, .css, etc). 

In the VSC User Settings i have also `"editor.tabSize": 4,`

I am using the latest versions of VSC and Prettier on Windows 10. Can anyone tell me why i can't change the tab width?

![image](https://user-images.githubusercontent.com/12392666/35184417-b031b626-fdf5-11e7-88b1-abdd45d6ec69.png)

**Comment by azz** [comment]
Looks like you've confused the vscode settings with the Prettier settings. It should simply be `"tabWidth": 4` rather than `prettier.tabWidth`.

**Comment by azz** [comment]
If you press ctrl-space you should get completions

**Comment by borisyordanov** [comment]
@azz You're right, when i removed "prettier" before the variables it stated working. Thank you!

**Comment by aalaap** [comment]
I'm having the exact opposite issue. On a default installation of VSCode with only Prettier installed, it works fine (i.e. formats on save and uses two spaces per indent) for my basic files, eg. `server.js`, `app.js` and one of the data files `data/data.js`. but one particular file called `data/cities.js` gets 4 spaces per indent. I created a new file called `data/testing.js` with the same content, but it still gets 4 spaces. I have modified no settings (other than turning off semi-colons) and I have no ignore file or anything else. 

I had to disable `editor.detectIndentation` and then set `editor.tabSize` to 2 for these particular files to get 2 spaces. Is there any way to check the Prettier log to see what's happening or if it's even being used?

**Comment by borisyordanov** [comment]
You can check Prettier's output by opening the terminal panel, going to Output and selecting Prettier from the dropdown.

Keep in mind that your editor's tabSize AND prettiers need to match

**Comment by aalaap** [comment]
Even without them matching, the other .js files were being formatted just
fine with Prettier. It's only these certain files that don't work. I hope
setting the native tabSize doesn't affect my Python and PHP code...

I'll look for the output.

**Comment by borisyordanov** [comment]
@aalaap Try changing the indentation settings on the files that aren't being formatted - https://stackoverflow.com/questions/34174207/how-to-change-indentation-in-visual-studio-code/51607879

**Comment by aalaap** [comment]
All of them are .js files. The ones that get formatted correctly as well as
the ones that don't.

**Comment by borisyordanov** [comment]
I'm not sure what you mean by that. I suggested you check the indentation settings of the files using the link i sent. I never said anything about changing their format.

**Comment by azz** [comment]
Are you sure you're not accidentally using the VSCode default formatter? Quick way to check is:

- write some code, e.g. `console.log ( 'test' )`
- press format, observe changes
- undo changes
- insert `// prettier-ignore` comment above the code
- press format again, this time there should be no changes
