### ISSUE TITLE
Bundled prettier gets used in monorepo

### ISSUE THREAD

**Issue by Andarist** [prettier/prettier-vscode#341]
Hi!
I've noticed this error warning
```
Failed to load prettier from /Users/user/Desktop/project/packages/ui-kit/node_modules/prettier. Using bundled
```

It seems that it has problem with resolving `prettier` as its hoisted to `~/Desktop/project/node_modules` in our monorepo (lerna) setup.

**Comment by azz** [comment]
Hi, good catch!

https://github.com/prettier/prettier-vscode/blob/b15ed4b8742744a48bdb12454656f733c3e14ca9/src/requirePkg.ts#L21

Hopefully this should just be:

```patch
-        return path.resolve(res.path, '..', 'node_modules/', pkgName);
+        return require.resolve(res.path, '..', 'node_modules/', pkgName);
```

**Comment by Andarist** [comment]
Not sure how `require.resolve` works for this case, but shouldn't something like `require.resolve(pkgName, { paths: [res.path] })` be enough?

I have not tested this syntax, just checking against [docs](https://nodejs.org/api/modules.html#modules_require_resolve_request_options)

**Comment by azz** [comment]
I edited my post because I realised that as soon as I posted. I usually use [`resolve`](https://www.npmjs.com/package/resolve) for that use case.

**Comment by Andarist** [comment]
Will try to check this out the fix in a moment to see if it helps.
