### ISSUE TITLE
Prettier indentation not working/overrides.

### ISSUE THREAD

**Issue by CHBaker** [prettier/prettier-vscode#344]
Hello, I use the John Papa Angular essentials package. I like my editor to have indentations of 4 spaces. My editor was set at 4 spaces, and when I downloaded angular essentials (I believe) Prettier overrides that.

My settings:
```
{
    "editor.fontSize": 14,
    "editor.insertSpaces": true,
    "window.zoomLevel": 1,
    "editor.detectIndentation": false,
    "workbench.iconTheme": "material-icon-theme",
    "editor.tabSize": 4
}
```

I tried adding the prettier settings to keep up with the tabSize:
```
{
    "editor.fontSize": 14,
    "editor.insertSpaces": true,
    "window.zoomLevel": 1,
    "editor.detectIndentation": false,
    "workbench.iconTheme": "material-icon-theme",
    "editor.tabSize": 4,
    "prettier.tabWidth": 4,
    "prettier.singleQuote": true,
}
```
After this, my editor still specifies a tab size of 2
![capture](https://user-images.githubusercontent.com/14304935/35234975-0c7b7b90-ff60-11e7-8ce4-cc1e297e2e41.PNG)

and when I click the spaces icon, it says configured tab size is 4. If configured is 4, why is 2 selected everywhere? I can manually click 4, on each file, but if I quit/reload the editor everything is back at 2. How can I fix my formatting?

**Comment by jmls** [comment]
I have the same problem - everything is set at 4, yet when I save it's set to 2 spaces. Extremely frustrating :(

**Comment by jmls** [comment]
oh, ok .. I seem to have fixed it ..

I created a `.prettierrc` file in the root of my project with the following content

```
{
	"singleQuote": true,
	"printWidth": 80,
	"editor.formatOnSave": true,
	"proseWrap": "always",
	"tabWidth": 4,
	"requireConfig": false,
	"useTabs": false,
	"trailingComma": "none",
	"bracketSpacing": true,
	"jsxBracketSameLine": false,
	"semi": true
}

```

and now I get 4 spaces for indentation

**Comment by CiGit** [comment]
The right setting to have prettier indent with 4 spaces is [`prettier.tabWidth: 4`](https://github.com/prettier/prettier-vscode#prettiertabwidth-default-2)

@CHBaker We do not read from `editor.tabSize`. It may be written 2 due to `editor.detectIndentation`

@jmls `editor.formatOnSave` is useless in a .prettierrc file. (you may also have a warning about that)

**Comment by jmls** [comment]
@CiGit : true - didn't see that. However, the fact is that atm I *need* to have a .prettierrc file for format on save to respect the tabwidth. If I don't it *always* is set to 2

**Comment by CiGit** [comment]
Do you have an .editorconfig?

**Comment by jmls** [comment]
dear god. yes. I do.

`indent_size = 2`

*blushes*

**Comment by CHBaker** [comment]
So I don't have detect indentation on, but let me try and create a .prettierrc file in my root when I get home. Do I need to include it somewhere? or will prettier auto-detect it

**Comment by CiGit** [comment]
As long as it is upper in the file hierarchy.
You should also check for a `.editorconfig` file

**Comment by CHBaker** [comment]
I do have a `.editorconfig`, that's what I posted above

**Comment by alberpad** [comment]
Sometimes there are problems if you have activated more than one formatter. Check if you have others like Beautify or JS-CSS-HTML Formatter.

**Comment by devTomek** [comment]
"prettier.tabWidth": 4 
works but remember to save file every time you are making changes!

**Comment by abelikov5** [comment]
Hi, you cat try like this:
<img width="1056" alt="Screen Shot 2020-02-28 at 17 09 49" src="https://user-images.githubusercontent.com/48707335/75555500-64e60800-5a4d-11ea-8525-e54c59485eea.png">

**Comment by saedyousef** [comment]
> oh, ok .. I seem to have fixed it ..
> 
> I created a `.prettierrc` file in the root of my project with the following content
> 
> ```
> {
> 	"singleQuote": true,
> 	"printWidth": 80,
> 	"editor.formatOnSave": true,
> 	"proseWrap": "always",
> 	"tabWidth": 4,
> 	"requireConfig": false,
> 	"useTabs": false,
> 	"trailingComma": "none",
> 	"bracketSpacing": true,
> 	"jsxBracketSameLine": false,
> 	"semi": true
> }
> ```
> 
> and now I get 4 spaces for indentation

This is great, thanks
