### ISSUE TITLE
Single Quote isn't applied on save or format document/selection

### ISSUE THREAD

**Issue by akrueger** [prettier/prettier-vscode#345]
The semi colon rule works fine on save or formatting document, but the single quote will not resolve. If I run `prettier --write`, it picks up the `.prettierrc` and correctly changes to single quotes.

Even if I directly set the `"prettier.singleQuote": false` in VSC configuration and remove the `.editorconfig` completely this still happens.

I have uninstalled and reinstalled the extension several times without any luck.

VSC: `1.19.2`
VSC Prettier Extension: `1.1.2`
Prettier: `1.10.2`

VSC user settings:
`"editor.formatOnSave": true`

`./.prettierrc`:

```
{
  "semi": false,
  "singleQuote:": true
}
```

`./.prettierignore`:
```
.prettierrc
package.json
client/build
```

`./.editorconfig`:
```
root = true

[*]
indent_style = space
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[*.{js, ts, json, jsx, html}]
indent_size = 2

[*.java]
indent_size = 4
```

**Comment by CiGit** [comment]
We will need some debug logs to help with those issue I think...

**Comment by akrueger** [comment]
Looks like I fat-fingered my config!

```
console.ts:123 [Extension Host] ● Validation Warning:

  Unknown option "singleQuote:" with value true was found. Did you mean "singleQuote"?
  This is probably a typing mistake. Fixing it will remove this message.
```

Kudos for the excellent warning message!

**Comment by akrueger** [comment]
Looks like I fat-fingered my config!

```
console.ts:123 [Extension Host] ● Validation Warning:

  Unknown option "singleQuote:" with value true was found. Did you mean "singleQuote"?
  This is probably a typing mistake. Fixing it will remove this message.
```

Kudos for the excellent warning message!
