### ISSUE TITLE
Ignore `CODEOWNERS` file

### ISSUE THREAD

**Issue by coliff** [prettier/prettier-vscode#3457]
**Is your feature request related to a problem? Please describe.**
I have a CODEOWNERS file in my projects. The first line I have is a comment formatted like this:
```
# About CODEOWNERS - <https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners>
```
The second is a catch-all formatted as this:

```
* @username
```

As such, VS Code auto-detects the sort of file the CODEOWNERS file is and assumes it's markdown... so Prettier autoformats and changes the `* @username` to `- @username` (as it thinks its a list) - this causes the CODEOWNERS file to not work as expected.

**Describe the solution you'd like**

Ideally it'd be good if CODEOWNERS could be added to a global ignore somehow.

**Describe alternatives you've considered**

I know we can add `CODEOWNERS` to our own `.prettierignore` files for now, but a global fix would be welcome!

**Comment by ntotten** [comment]
Using prettierignore is the correct way of doing this. THe extension is not opinionated about this type of thing.
