### ISSUE TITLE
Doesn't work with version 1.19.2

### ISSUE THREAD

**Issue by saeidalidadi** [prettier/prettier-vscode#346]
This extension doesn't work after updating `vscode` to version `1.19.2`

**Comment by sutter** [comment]
Yep me too.

**Comment by jenkey2011** [comment]
Uninstall prettier， and try again ~

**Comment by sutter** [comment]
Hum SCSS Format doesn't work after reinstall prettier. Just Javascript work fine

**Comment by rayjsiu** [comment]
For some reason, the Prettier extension disappeared completely from my installed extensions.
I had to install it, uninstall it, and then install it again and reload VS Code for it to work again.
Thanks @jenkey2011

**Comment by apolloinfinity** [comment]
I have the same issue. I installed VS Code on my laptop. Tried to install Prettier and it takes a long time to install. I stop it. Close VSCode. I check my extensions and it isn't there. Then I try to install again from the extensions list and the same thing happens. Prettier just doesn't want to install on this version of VS Code.

**Comment by apolloinfinity** [comment]
After much frustration, it finally installed and worked.

**Comment by xiaoyueyue165** [comment]
I still can not use it in 1.19.2. I have uninstalled it and reloaded it twice.

**Comment by apolloinfinity** [comment]
@xiaoyueyue165 You know what I did and its maybe the reason it worked for me? I used RevoUninstaller and used that to find every file that was linked to VSCode. Then I installed it again and it worked fine. I'm not sure if that will fix it for you but it worked for me using RevoUninstaller on Windows.

**Comment by CiGit** [comment]
Seems something wrong between vscode and this extension.
1. Uninstall it
1. Quit vscode
1. Delete the extension's folder `$HOME/.vscode/extensions/esbenp.prettier-vscode` if it still exists
1. Install the extension
1. Restart vscode

If it still doesn't work, debugging it is the last thing I see.

**Comment by fqborges** [comment]
@CiGit 
It worked here, but there is a caveat. You should install the extension and immediately close the vscode, then open vscode.

When I installed and reloaded the window to load the extension, it didn't work, even after restarting/closing/reopening vscode.

**Comment by xiaoyueyue165** [comment]
@apolloinfinity 
So you are saying that you reinstalled vscode with a professional uninstall tool, is that right?

**Comment by CiGit** [comment]
@sutter Seems to be partially working. Do you have any other formatter for scss ?

**Comment by johny** [comment]
Doesn't work for me for JS/JSX react components. It reports an error in the console but I am not able to reformat code. Version 1.19.3

**Comment by CiGit** [comment]
@johny Do you mind sharing the error ?

**Comment by mehas** [comment]
Doesn't work for me with SCSS in VS Code 1.20 either. 

Uninstalled the plugin, manually deleted the folder from disk, reinstalled plugin, closed and reopened VS Code. `Format Document` does nothing, no errors in console.

The [VS Code stylefmt plugin doesn't work anymore either](https://github.com/mrmlnc/vscode-stylefmt/issues/138), is there _any_ plugin that will allow me to format SCSS according to my stylelint configuration?

**Comment by EthanNYT** [comment]
Broken for me again in VS Code 1.21.1. I followed [the instructions in this comment](https://github.com/prettier/prettier-vscode/issues/346#issuecomment-360453862) and it still doesn't work.

Running `Format document` on a SCSS file results in the checkmark appearing next to "Prettier" at bottom right:

![screen shot 2018-03-23 at 1 33 04 pm](https://user-images.githubusercontent.com/29407693/37844704-ffaddd90-2e9e-11e8-9470-544426dbbce8.png)

...but none of the formatting rules from my stylelint config are applied. Not even basic indentation. No errors in the Output console. `prettier.stylelintIntegration` is set to  `true` in my User Settings and the extension was working previously.

**Comment by CiGit** [comment]
VSCode is now at v1.22.2. As there are no more input here, I would assume this is _fixed_

**Comment by PJCHENder** [comment]
Still facing the same issue, "SCSS Format doesn't work after reinstall prettier. Just Javascript work fine"

**Comment by dougbacelar** [comment]
followed all the steps on this thread and still didn't work for me. 
VSCode version `1.30.2`
Prettier extension `1.7.3`

I don't have a `prettierrc.json` on my home folder...


It works for JS/JSON files.

![image](https://user-images.githubusercontent.com/9267678/51598646-e471e100-1ef5-11e9-86b8-c1f889d381ee.png)

**Comment by jensbodal** [comment]
I gave up on this. Ended up installing stylelint and its VSCode extension, then adding the stylelint-prettier plugin.  So now stylelint checks my scss files and includes errors from prettier like I wanted.

* https://github.com/prettier/stylelint-prettier
* https://github.com/shinnn/vscode-stylelint

So this gets me almost there. I can't use the `Fix All` command in VSCode to run prettier, but if I run `Format Document` then it does runs prettier and fixes the problems.

* Errors are reported by stylelint in VSCode using the extension + stylelint-prettier npm package
* Actual prettier is used by running `Format Document` in VSCode

As a side note, running `Format Document` works regardless of the style lint plugin being installed, but by installing it you can see the errors in VSCode.

**Comment by LukasV** [comment]
I've managed to make the Prettier format my .scss file by changing following line in my User/settings.json:

`"editor.defaultFormatter": "vscode.configuration-editing",`
->
`"editor.defaultFormatter": "esbenp.prettier-vscode",`

I hope this helps
