### ISSUE TITLE
How to set the `rangeStart` configuration for the `prettier-vscode` extension in VS Code? 

### ISSUE THREAD

**Issue by wangrongding** [prettier/prettier-vscode#3466]
How to set the `rangeStart` configuration for the `prettier-vscode` extension in VS Code? Currently, it formats the entire file by default. Sometimes I just want to format the selected code by using `Cmd + K & Cmd + F`.    

It can be achieved in the config configuration file in the project, but sometimes there is no such configuration in new projects, and I just want to have a default configuration option in vscode.  

![image](https://github.com/prettier/prettier-vscode/assets/42437658/b7401f4d-c24e-4cbb-aea7-a86d02c4f087)

**Comment by wangrongding** [comment]
Currently, there is no such configuration in the configuration items of prettier-vscode. 

![image](https://github.com/prettier/prettier-vscode/assets/42437658/233c5a2d-f9ca-482a-960b-a11934c0f388)

**Comment by ntotten** [comment]
Range formatting is not supported
