### ISSUE TITLE
Prettier extesion not working on version 10.4.0

### ISSUE THREAD

**Issue by marcellino-ornelas** [prettier/prettier-vscode#3479]
### Summary

Prettier extension version `10.4.0` is not working. Getting the following error when trying to running "format document"

```
Extension 'Prettier - Code formatter' is configured as formatter but it cannot format 'TypeScript JSX'-files
```

![Screenshot 2024-07-24 at 2 15 24 PM](https://github.com/user-attachments/assets/14548562-d02f-489e-bf18-5ed6bcdc12c4)

`.vscode/settings.json`
```
{
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "[typescriptreact]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode",
    }
}
```

Downgrading to `10.3.0` fixes this issue.

### Github Repository to Reproduce Issue

N/A its a private repo so wont be able to share. Happy to provide you more context.

### Steps To Reproduce:

1.  Install prettier extension 10.4.0
2. go to any tsx/js/ts file and save.
3. Prettier doesn't format even tho `formatOnSave` is `true`
4. Run "Format document" and you get pop up

### Expected result

Should format code

### Actual result

![Screenshot 2024-07-24 at 2 15 24 PM](https://github.com/user-attachments/assets/14548562-d02f-489e-bf18-5ed6bcdc12c4)

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

```
Version: 1.90.2 (Universal)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:37:41.291Z (1 mo ago)
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
```

**Prettier Extension Version**: v10.4.0

**OS and version**: Darwin x64 23.5.0

## Prettier Log Output

No output only pop up

```
["INFO" - 2:14:22 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 2:14:22 PM] Extension Version: 10.4.0.
```

**Comment by JoShMiQueL** [comment]
Same here 🙋🏻‍♂️

**Comment by JoShMiQueL** [comment]
However, this error no longer occurs with the new version 11.0.0, it can be closed.

**Comment by kevinpruett-prime** [comment]
Getting the same behavior with 11.0.0 🤔
