### ISSUE TITLE
Docs seem wrong for windows ?

### ISSUE THREAD

**Issue by astannard** [prettier/prettier-vscode#348]
The docs show: 
Using Command Palette (CMD/CTRL + Shift + P)

this opened up the command pallet for me, however using the below worked:
Shift + Alt + F

**Comment by RobinMalfait** [comment]
Yes, you even said it yourself. `Using Command Palette` opens the `Command Palette`. 
You can also use the shortcut that you defined.

![](http://d.rbn.nu/RvYhH2.png)
