### ISSUE TITLE
Markdown formula incorrectly formatted

### ISSUE THREAD

**Issue by mcwindy** [prettier/prettier-vscode#3482]
Type: <b>Bug</b>

Formular like
$$ (x',y') = \frac{(k_1k^{-1}_{2}k_3+k_3)G + (k_1k^{-1}_2k_3+k_3)P}{1+(d_Ud_C-1)} $$
will be converted to 
$$ (x',y') = \frac{(k*1k^{-1}*{2}k_3+k_3)G + (k_1k^{-1}\_2k_3+k_3)P}{1+(d_Ud_C-1)} $$
after code format by this extension.

Extension version: 10.4.0
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 6.8.0-39-generic
Modes:

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
