### ISSUE TITLE
[FR] `prettier.pluginsPath`

### ISSUE THREAD

**Issue by wenfangdu** [prettier/prettier-vscode#3488]
Currently, `prettier-vscode` reads plugins from the project root `node_modules` folder, which might not be the actual plugins location.
```
["ERROR" - 1:52:33 PM] Error handling text editor change
["ERROR" - 1:52:33 PM] Error resolve node module 'prettier-plugin-lint-md'
Error: Error resolve node module 'prettier-plugin-lint-md'
```
Similar to `prettier.prettierPath`, `prettier.pluginsPath` is needed to rectify this issue.

**Comment by ntotten** [comment]
Happy to take a PR

**Comment by wenfangdu** [comment]
After looking at the [source code](https://github.com/prettier/prettier-vscode/blob/b8d9e42b8900c88e2210bc72615d9f925439b058/src/ModuleLoader.ts#L37), I found a workaround:

.prettierrc

```json
{
  "plugins": ["./tests/node_modules/prettier-plugin-lint-md/dist/prettier-plugin-lint-md.js"]
}
```
