### ISSUE TITLE
Shortcuts conflict to no friends

### ISSUE THREAD

**Issue by xiaoyueyue165** [prettier/prettier-vscode#351]
Sorry, I can not use this plugin, shortcuts to no friends conflict, custom keyboard shortcuts it is not a custom plug-in? Give you a suggestion, use **ctrl + shift + l** as a shortcut key, all the format plug-in is a conflict, covering, do not say.

**Comment by xiaoyueyue165** [comment]
I have modified the shortcut conflicts, but I still can not use it in 1.19.2. I have uninstalled it and reloaded it twice.

**Comment by azz** [comment]
Ctrl-shift-F is the default vscode shortcut for formatting a file. You can change it in keybindings.json

**Comment by xiaoyueyue165** [comment]
I said this,I have modified the shortcut conflicts, but I still can not use it in 1.19.2. I have uninstalled it and reloaded it twice.
