### ISSUE TITLE
We plan to feature your VS Code extension

### ISSUE THREAD

**Issue by auchenberg** [prettier/prettier-vscode#353]
Hi,

It's Kenneth from VS Code. I'm reaching out to tell you that we plan to feature your awesome VS Code extension on our marketplace https://marketplace.visualstudio.com/#VSCode in the next iteration. I'm opening an issue here as there seem to many contributors on this extension!

Please work with your community to resolve any major issues, as you'll probably see a significant bump in new users trying your extension.

Thanks for the great work, and happy coding! 

/k

------
Kenneth Auchenberg
Visual Studio Code
Program Manager, Microsoft

**Comment by CiGit** [comment]
Seems this is what caused this download increase :smile: 
over 1,4 M currently
If I remember correctly it was near 800 K at the beginning of the year
