### ISSUE TITLE
when prettier.eslintIntegration is true, dont take .editorconfig(meant for other editors)

### ISSUE THREAD

**Issue by sagiavinash** [prettier/prettier-vscode#355]
Our web scaffold has `.editorconfig` file. and its meant for editors other than vscode that dont use prettier or any other autoformat extensions
Now for the sake of vscode `prettier-eslint` to work i need to remove that file.
Can u make sure that when prettier.eslintIntegration is true, prettier shouldn't take .editorconfig
and ignore the `.eslintrc` completely.

PS: my .editorconfig file and `.eslintrc` doesnt have conflicting rules its just that `.editorconfig` file has just things like tabWidth and `.eslintrc` has the entire styleguide. so when `.editorconfig` file is there its picking very small set of rules

**Comment by sagiavinash** [comment]
@RobinMalfait I asked to ignore `.editorconfig` not `.eslintrc` when `prettier.eslintIntegration === true`

and I also mentioned in my `PS` that my `.editorconfig` and `.eslintrc` are not conflicting, the tabWidth is same in both of them. the problem is prettier is not considering `.eslintrc` when `.editorconfig` is present

**Comment by sagiavinash** [comment]
@RobinMalfait Please let me know if u need any more information

**Comment by RobinMalfait** [comment]
Hello @sagiavinash can you provide a small reproduction repo with the eslint/editorconfig in it?

**Comment by agjs** [comment]
We could introduce another property e.g. ignoreEditorconfig that people could potentially ignore if their .editorconfig is mainly used in other IDE'S. @RobinMalfait, thoughts?

**Comment by CiGit** [comment]
Not using an editorconfig feels wrong to me.
If I use an other IDE, I would have different [tab width, whatever] ?
