### ISSUE TITLE
Prettier does not support new angular template syntax

### ISSUE THREAD

**Issue by marekdon** [prettier/prettier-vscode#3550]
### Summary

Since angular 17, we can use new template syntax. Prettier does not seem to format html document in a proper way, when new template syntax is present.

### Github Repository to Reproduce Issue

Screenshot attached

### Steps To Reproduce:

1.  Use new template syntax in angular project
2.  Save the document

### Expected result

```
@if (true) {
  <div>
    @if (true) { 
      @if (true) {
        <div></div>
      }
    }
  </div>
}
```

### Actual result

```
@if (true) {
<div>
  @if (true) { @if (true) {
  <div> </div>
  } }
</div>
}
```

### Additional information

<img width="364" alt="image" src="https://github.com/user-attachments/assets/19537e12-c4e2-4373-8bb6-ba2db78da1fb">

**VS Code Version**:

Version: 1.94.0 (Universal)

**Prettier Extension Version**:

v.11.0.0

**OS and version**:

iOS 15.0.1 (24A348)

## Prettier Log Output

```
{
  "parser": "angular",
  "useTabs": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "semi": true,
  "singleQuote": true,
  "arrowParens": "always"
}
```

**Comment by LeQuyetTien** [comment]
Same problem with me.

**Comment by sm-sayedi** [comment]
This is exactly what I am facing and it is so annoying. WebStrom does an incredible job with formatting the new syntax. Sometimes, I think of switching to WebStorm for my Angular projects!

**Comment by M0ns1gn0r** [comment]
Is there an update on this? The `@let x = 123` syntax seems to be not supported as well.

**Comment by M0ns1gn0r** [comment]
It turns out, the syntax support was added in https://github.com/prettier/prettier/pull/16474.

To make VS Code extension use the newest version of prettier, add (or update) a development dependency to `prettier` in your `package.json`.
