### ISSUE TITLE
Formatter does not work in latest version - or works but takes 7-10s

### ISSUE THREAD

**Issue by rossvz** [prettier/prettier-vscode#356]
I generally use WebStorm or Atom as my editor, but we recently switched to using prettier across our repos for standardization. I wanted to get VS code set up with prettier, but after 2 hours I can't seem to get it to format code at all.

VSCode Version: Version 1.19.3 (1.19.3)
Prettier plugin: 1.1.2

We are using prettier-eslint, here's the user settings:
```
// Place your settings in this file to overwrite the default settings
{
	"editor.formatOnSave": true,
	"prettier.eslintIntegration": true,
	"eslint.autoFixOnSave": false,
	// "javascript.format.enable": false,
}
```

I've tried various combinations of the javascript.format.enable, eslint.autoFixOnSave and different settings for saving, but none of them seem to actually format the code.

With the combination above I can get the code to format, but it takes an average of 8s to fix one incorrect line. I opened the same file in Atom and it fixed the same issue almost instantaneous to me hitting the save key.

**Comment by CiGit** [comment]
`eslint.autoFixOnSave` should be disabled, you are already using `eslintIntegration`, thus doing `eslint --fix` twice.

Trying to narrow down where the issue comes from.
- Can you disable prettier extension and enable `javascript.format.enable` (reload) and see if it's fast with the default formatter ?
- Can you set `"prettier.eslintIntegration": false` ?

- Is your CPU idle when you try to format the file?

**Comment by szokrika** [comment]
I have the same issue,  

```
"editor.formatOnSave": true,
"prettier.eslintIntegration": true,
```

will still formats the code based on the `.prettierrc` file, it seems that the `prettier.eslintIntegration: true` option does not stick.

**Comment by szokrika** [comment]
![image](https://user-images.githubusercontent.com/2699972/39824299-3d91b41e-536c-11e8-909e-1b1a7e046a9a.png)

For reference, on save it formats as such then I get the problems as shown

**Comment by gisderdube** [comment]
Same here, trying to get this to work for weeks now. in earlier versions, it was working quite well. Now however, it is horrible and things get mixed up really bad.

**Comment by harleyguru** [comment]
right, simply disable beautify, it should work!

**Comment by asiajacko** [comment]
Just commented // "prettier.eslintIntegration": true, and is working

**Comment by CiGit** [comment]
Is that still an issue ?

**Comment by harleyguru** [comment]
@CiGit This is not an issue. 
But I think this should be noticed for further facing users.
Compatibility issue with beautify extension.

I love Prettier, Thanks for your amazing work!

**Comment by CiGit** [comment]
I was talking about the initial issue.
I'll close that as it diverged a lot. Please open a new issue for anything.
