### ISSUE TITLE
Disabling .eslintrc rules

### ISSUE THREAD

**Issue by standingdreams** [prettier/prettier-vscode#357]
I've been all over trying to find a solution to this issue that you can see in the gif.  I have the settings set to `"prettier.eslintIntegration": true`. I tried setting `"prettier.printWidth"` to 180. I've tried setting `"function-paren-newline"` and `"no-unexpected-multiline"` in the `.eslintrc.json`. 

The error that I get AFTER the code formats itself is `Unexpected newline between object and [ of property access (no-unexpected-multiline)`. I've tried adding all the different plugins.

![prettier-v2](https://user-images.githubusercontent.com/942959/35602218-163ce76c-0605-11e8-8e8c-ae9683673e6c.gif)

**Comment by CiGit** [comment]
"no-unexpected-multiline" is not `fixable`. https://eslint.org/docs/rules/no-unexpected-multiline

Both code you have (before / after) have the same meaning. It doesn't break your code.
