### ISSUE TITLE
Defect - while prettifying the following condition.

### ISSUE THREAD

**Issue by gauravkakkar87** [prettier/prettier-vscode#359]
I recently installed this extension and it is quite helpful making code look cleaner and shorter. However I recently discovered that prettying didn't shorthand the following condition correctly:

My statement was :
`true || (true && true) && true`
which Prettier changed to 
`true || (true && true && true)`

Because I rely on prettier's shorthand a lot, I didn't give it a second thought and committed the code which resulted a defect opened to my name. I resolved it using the doubles brackets around my condition. 

`(true || (true && true)) && true`

**Comment by CiGit** [comment]
Both `true || (true && true) && true` and `true || (true && true && true)` are equivalent.

`(true || (true && true)) && true` is not equivalent to `true || (true && true) && true`
