### ISSUE TITLE
NextJS <style jsx>{``}</style> format breaks

### ISSUE THREAD

**Issue by Aorewen** [prettier/prettier-vscode#363]
Hi there, 
Thanks for this awesome extension.

I would like to get my JSX CSS styled highlighted and benefit the snippets of another extension.
For those, I need the following syntax : 

https://derniercri.d.pr/HwrnEN

-------------
Now I have this : 
https://derniercri.d.pr/UnknWY

There is a way to fix this ?
Or at least to configure an exception for the <style jsx> tag ?

I'm using VSCode on MaCOS, my file is detected as Javascript React and i'm using Prettier latest version.

Thanks

**Comment by CiGit** [comment]
I think there are 2 problems here:
- Your syntax highlight should work in both cases.
- Prettier does something odd to me in formatting this thing. You should open an issue in prettier's repository. If I'm not mistaken both mean exactly the same.
Without putting anything before opening and after closing brackets, prettier output is what you expect.
```js
<style jsx>/*NOTHING HERE*/{`
.m{background-color: hotpink}
`}/*NEITHER HERE*/</style>
```
[Example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjAngGzgAgCt0APAPmAAMAdKAOgFtgAjAQzAGsBzAJwgFcoAEwC0kHBB5J8ACwgwADgEsoHAL61Ka1AHpMuOGRAAaEBAUwl0dMlCsefAO4AFewhspWANwhKhJkFZMZAAzVhx0OFNmHnYOOBgAZQV2FS5kGB5+KJAhCDBQ8MjTFUieGGdYrgZWQoic4hIAIVjOBMTWBjgAGRU4OuKzfkVhgCYBnJSeMuQQNmZcaACFHhUYAHU-GBlkAA4ABlMViEj12IVZlbgyr37THjgAR34lB8rWatqkMPrTSIYlBksjl0Gk8ABFfjyfrfIo5GCsZibITbZCjUyZVhKHBpADCEAYNVmUGgdxA-EiABVER4fpE1GogA)

**Comment by Aorewen** [comment]
This VSCode extension is up to date with Prettier.io ?
My bad if it is the case, I shouldn't have to open an issue here.

I resolved the issue thanks to ur example, I had the brackets on another line for the closing tag also. By putting the bracket and the tag on the same line, everything works like a charm.

Thanks

**Comment by CiGit** [comment]
>This VSCode extension is up to date with Prettier.io ?

We try to :smiley:
