### ISSUE TITLE
how to apply prettier formatting on all files within a folder?

### ISSUE THREAD

**Issue by vesper8** [prettier/prettier-vscode#364]
In Jetbrains I could select a folder from the explorer and do the keyboard combination associated with "format document" and it would format all files in that folder

Any way to do the same thing with this extension?

**Comment by CiGit** [comment]
There is no such thing with this extension. But thanks for the tip on Jetbrains IDEs ;-)

Your best bet would be to use prettier's cli.

**Comment by CiGit** [comment]
This could be a vscode thing, would work for every formatter.
