### ISSUE TITLE
Show prettier.config.js errors

### ISSUE THREAD

**Issue by pscanf** [prettier/prettier-vscode#366]
When `prettier.config.js` throws an error, the extension "doesn't work" (files are not fromatted) and the user is not notified: nothing is printed in the **Output** tab, the error is only logged in the developer tools console (which the user probably doesn't open). I don't know if VSCode should be catching those errors and report them in **Output** (in which case I guess this would be a VSCode bug), or if the extension should take care of that. I remember other errors being reported there (eg issue #341), so I thought it might be an issue with the extension.

You can use the following `prettier.config.js` to reproduce the issue:
```js
throw new Error("prettier.config.js error");
```

**Comment by CiGit** [comment]
We should catch that.
Maybe better, validate config files:
- parse issue
- unknown config props
- Path location.

**Comment by agjs** [comment]
@CiGit can you assing this one to me, I can go ahead and fix it.

**Comment by CiGit** [comment]
I can't assign it to you (you are not part of the project), but you can have it. Assigning myself.
