### ISSUE TITLE
Cannot find module 'require-relative'

### ISSUE THREAD

**Issue by Moeriki** [prettier/prettier-vscode#368]
Since a few days my prettier VSCode extension is no longer working and has this error in its output panel.

```
Cannot find module 'require-relative'
```

I'm using VSCode `Version 1.21.0-insider (1.21.0-insider)`.

Anyone knows what's up? Cheers.

**Comment by CiGit** [comment]
Can you tell me what's in there:
`ls $HOME/.vscode-insider/extensions/esbenp.prettier-vscode-1.1.3/node_modules/require-relative`

Should be: 
```
index.js
package.json
README.md
```
Then try reinstalling

**Comment by Moeriki** [comment]
`$HOME/.vscode-insiders/extensions/esbenp.prettier-vscode-1.1.3/node_modules` has no `require-relative.`.

Reinstall with VSCode UI didn't work.

This did work.

1. Close VSCode
2. `rm -rf $HOME/.vscode-insiders/extensions/esbenp.prettier-vscode-1.1.3`
3. Open VSCode
4. Install Prettier

All is good. 👍
