### ISSUE TITLE
editor.formatOnSave ignores eslint-specific settings for no-debugger

### ISSUE THREAD

**Issue by doque** [prettier/prettier-vscode#369]
Hi,

in our `.eslintrc`, we disallow `debugger` statements by setting `no-debugger: "error"`.

When saving files using `"editor.formatOnSave": true` and `"prettier.eslintIntegration": true`, any `debugger` statements are stripped from the source code (as they should).

But - there is no way to disable this behavior. This debugger statement will also be removed:
```js
// eslint-disable-next-line no-debugger
debugger;
```

Same with
```js
debugger; //eslint-disable no-debugger
```

I've tried passing specific settings to `eslint`:
```js
  "eslint.options": {
    "rules": {
      "no-debugger": "off"
    }
  }
```

Disabling `prettier` doesn't seem to work, either
```js
debugger; // prettier-ignore
```

Any chance to fix this?

**Comment by CiGit** [comment]
```
// eslint-disable-next-line no-debugger
debugger;
```
should work...
I just tried it and it works for me. It is removed without the comment and stays with it.

Can you try with prettier-eslint-cli ? Trying to find out where your issue is.

We do not read from "eslint.options". This is an other extension's options.

**Comment by TrevorBurnham** [comment]
@doque I believe you want

```jsx
debugger; //eslint-disable-line no-debugger
```

instead of

```jsx
debugger; //eslint-disable no-debugger
```
