### ISSUE TITLE
Prettier intermittently failing on the latest version

### ISSUE THREAD

**Issue by ForbesLindesay** [prettier/prettier-vscode#370]
I'm using prettier with typescript (`.tsx`) files and my config is:

```json
{
    "editor.fontFamily": "FiraCode-Regular, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "window.zoomLevel": 2.5,
    "editor.formatOnSave": true,
    "[json]": {
        "editor.formatOnSave": false
    },
    "editor.tabSize": 2,
    "prettier.requireConfig": true
}
```

Prettier seems to intermittently fail when saving a file. When it fails, it sometimes deletes characters at random from the file being prettiered. It started happening about 1 week ago, and since then it's happened fairly frequently.

I realise this isn't much to go on, but I'm opening it in case other people are experiencing the same thing.

**Comment by ForbesLindesay** [comment]
My hypothesis is that the built in formatter is being used in place of prettier, but I'm not sure.

**Comment by ForbesLindesay** [comment]
I just got a warning linking to: https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt

Not sure if this is prettier or some other plugin.

**Comment by CiGit** [comment]
Prettier deletes some characters, but theses (white space, semicolon, comma, parentheses, ...) are certainly not what you mean and certainly not random.

The built in formatter shouldn't remove characters other than white space I think.

We do not (conscientiously) _patch_ VSCode.
Try disabling all extensions, reinstalling.
Enable extensions one by one to find out which leads to a corrupt install.

**Comment by ForbesLindesay** [comment]
I have not had any lock with that. I have found that disabling and then re-enabling the prettier plugin seems to fix this each time it happens.

**Comment by CiGit** [comment]
I would prefer if it would not happen instead of having to work around it...

**Comment by ForbesLindesay** [comment]
I agree. I'm just trying to narrow down when it could be being caused. I'm increasingly thinking this may be a vscode bug rather than a prettier/plugin bug.

**Comment by ForbesLindesay** [comment]
I think I've narrowed it down.  I set `"prettier.requireConfig": false,` and found that I no longer get the bug where it all goes completely haywire, but prettier often fails to detect my `.prettierrc` file.

**Comment by CiGit** [comment]
Do you have an _exotic_ file system?

**Comment by ForbesLindesay** [comment]
no, just the default for a MacBook Pro (2018)

**Comment by CiGit** [comment]
Reading this issue from start, I'm not quite sure I understand what your issue is.
- Does it delete some random characters?
- It doesn't read the config file (not finding it)

**Comment by ForbesLindesay** [comment]
I'm not sure anymore. I'll try and get back to you in a few days if it happens again.

**Comment by ForbesLindesay** [comment]
I haven't experienced this since.
