### ISSUE TITLE
Breaks flow generic

### ISSUE THREAD

**Issue by smikheiev** [prettier/prettier-vscode#373]
Hi. There is such issue with prettier + flow.
For example there is such long line:
`const variableName: Array<SomeType> = somethingWithLongName.getSomethingWithLongName()`
Prettier formats it in the next way:
```
const variableName: Array<
  SomeType
> = somethingWithLongName.getSomethingWithLongName()
```
As you can see it breaks `Array<SomeType>`

**Comment by azz** [comment]
Closing as a duplicate of https://github.com/prettier/prettier/issues/1825
