### ISSUE TITLE
.prettierignore not picked up when not in root folder

### ISSUE THREAD

**Issue by guidobouman** [prettier/prettier-vscode#375]
The following folder structure works for the `.prettierrc`, but the `.prettierignore` does not apply. Do I need to move the prettier settings to the root of the project? Because this would mean a discrepancy between eslint & prettier. When placed in subfolders, .eslintignore works as expected.

Folder stucture:
```
- projectdir
  - sub_project1
    - .prittierrc
    - .prittierignore
  - sub_projec2
    - ...
  - sub_projec3
    - ...
```

The `.prettierrc` file:
```
{
  "singleQuote": true,
  "trailingComma": "all"
}
```

The `.prettierignore` file:
```
# Ignore everything, just to test
**/*
*
**
```

**Comment by CiGit** [comment]
Prettier works differently with ignore. It doesn't search for it. By default it's
`.prettierignore` from working directory. We mapped it to Folder root (you can however specify this file in a per folder setting `prettier.ignorePath`).

You can use vscode's multiple folder feature if you have multiple ignore file across your sub_project#

**Comment by entozoon** [comment]
Searching up the tree for one would be mighty convenient, not gonna lie.

Expected behaviour (in my mind) is the same as a .gitignore but that isn't currently the case

**Comment by CiGit** [comment]
We would implement that if prettier implements it :-)

**Comment by entozoon** [comment]
Fair point!

**Comment by dguo** [comment]
Here is the relevant Prettier issue: https://github.com/prettier/prettier/issues/4081

**Comment by lucasconstantino** [comment]
By the way: until @bmalehorn [work](https://github.com/prettier/prettier/pull/6203) isn't merged, I'm currently adding a symbolic link to from the ./root/.prettierignore to ./root/sub-project/.prettierignore for this to work... quite ugly, but works.

**Comment by mrcoles** [comment]
@CiGit FWIW my experience with the emacs version https://github.com/prettier/prettier-emacs is that it finds the nearest one. I could see this being rooted in emacs not using a concept of a workspace root, but I was surprised when things worked differently for me in vscode.
