### ISSUE TITLE
Use .prettierrc.json instead of VSCode settings config

### ISSUE THREAD

**Issue by wgoolsby** [prettier/prettier-vscode#376]
I'm on Mac OS.

Currently if I utilize the following in the VSCode settings config I'm able to have formatting work on save.
```
  "prettier.eslintIntegration": false,
  "editor.formatOnSave": true,
  "prettier.printWidth": 120,
  "prettier.tabWidth": 2,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "none",
  "prettier.bracketSpacing": true,
  "prettier.jsxBracketSameLine": false,
  "prettier.parser": "flow",
  "prettier.semi": true,
  "prettier.useTabs": false,
```

I've recently added a couple developers to my team, so I've pulled all of the prettier. things out, except for prettier.eslintIntegration: false. I created a .prettierrc.json that looks like this. It is in the top directory of my project, but when I save, nothing happens.

```
{
   "printWidth": 120,
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "none",
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "parser": "flow",
  "semi": true,
  "useTabs": false,
}
```

Is there a config to point to this file or an additional setting to use a configuration file?

**Comment by CiGit** [comment]
By _nothing_ you mean ?

>  .prettierc.json

If this is the real name, you should add a <kbd>r</kbd>

**Comment by wgoolsby** [comment]
It is .prettierrc.json Autocorrect got the better of me. Sorry about that.

By nothing I mean, it does absolutely nothing. If i run the cli command the output will respect the .prettierrc.json file, but VSCode acts like the file doesn't even exist and no formatting takes place when I save or when I choose 'Format Document' from the Command Palette.

**Comment by CiGit** [comment]
Any error in the dev console / output panel ?

**Comment by RobinMalfait** [comment]
I'm not sure that json files can contain trailing commas (,). Change `"useTabs": false,` to `"useTabs": false`

**Comment by wgoolsby** [comment]
@RobinMalfait You are correct in that son files can not use trailing commas. Unfortunately, my inclusion of the trailing comma was just a typo.

Turns out, once I actually looked in the Developer tools, that I had a React Snippets plugin installed that was just breaking VSCode. 

Closing. I apologize for the wasted time.

**Comment by RobinMalfait** [comment]
No worries @wgoolsby, glad it's fixed now! Have a nice weekend!

**Comment by w5mix** [comment]
Thanks @wgoolsby.  This helped me too.

**Comment by vikbert** [comment]
used `.prettierrc` as config file and works perfect for me always.
