### ISSUE TITLE
prettier.requireConfig does not exclude files outside the root folder

### ISSUE THREAD

**Issue by papandreou** [prettier/prettier-vscode#377]
I have `prettier.requireConfig` and `editor.formatOnSave` enabled. When I have a vscode window open with a project that uses prettier, I sometimes open another file in that same window by going `code /some/other/project/package.json`. When I save that file, it is automatically prettier-fied, even though there isn't a `.prettierrc` in any of its parent directories.

You could argue that I should try to kick the habit of opening such out-of-root files in the same window, and TBH it mostly happens by accident when I don't remember whether I already have a vscode window open for that particular project. Still, it seems to me like a bug in the code that honors `prettier.requireConfig`. What do you think?

**Comment by RobinMalfait** [comment]
I think that it is because you open it in the same "workspace". For example all your ESlint rules will be applied as well if I'm not mistaken. 

I sometimes use Quokka to quickly test stuff, and it gets prettified based on the current workspace as well.

Can you verify that it also happens with tools like ESlint and Quokka? If not, than I think it is a bug on our side. If you can reproduce, it might be VSCode related?

**Comment by papandreou** [comment]
@RobinMalfait, I've played around with this some more, and I've concluded that what I'm seeing isn't prettier-vscode's fault. It's simply the `editor.formatOnSave` feature that makes vscode apply its own autoformatting of js/json files in the absence of a prettier config to override it.

90% of the time I don't want this. Do you know if there is a way to disable vscode's autoformatting while still having `editor.formatOnSave` behavior in projects/roots that do use prettier?

Sorry for the misdiagnosis, and thanks for the help!

PS: I found that the eslint rules of the project don't apply to out-of-workspace files. If the out-of-workspace file is in another project that has an eslint config of its own, the right rules will be applied -- so at least that works :)

**Comment by CiGit** [comment]
It should pickup any prettier config file/eslint config you have in your file's tree. I think it also picks up your User's settings where things may be disabled.

Something to try: disable format on save globally (User settings) and enable it (Folder/Workspace settings) where you use prettier. It _may_ work ...

**Comment by papandreou** [comment]
Good idea, that would probably achieve it. I'm trying to avoid per-project vscode configuration, so I'm not ready to give up and do that yet, though :)

Anyway, thanks for taking the time. I'll close the issue now :)
