### ISSUE TITLE
End of Central Directory Record Signature Not Found on installing the extension

### ISSUE THREAD

**Issue by xfumihiro** [prettier/prettier-vscode#382]
![screen shot 2018-03-02 at 10 59 26 am](https://user-images.githubusercontent.com/12194969/36881394-d696fb72-1e08-11e8-8beb-ed4f5ef44717.png)

versions:
vscode - 1.20.1
os - mac osx 10.11.6

**Comment by xfumihiro** [comment]
Manually install works.

**Comment by CiGit** [comment]
See https://github.com/Microsoft/vscode/issues/2384
