### ISSUE TITLE
prettier.arrowParens setting type

### ISSUE THREAD

**Issue by SkeLLLa** [prettier/prettier-vscode#383]
With `"prettier.arrowParens": "always",` i receive following error
```
● Validation Error:

  Option "arrowParens" must be of type:
    boolean
  but instead received:
    string

  Example:
  {
    "arrowParens": false
  }
```

With `"prettier.arrowParens": true,` in setting I receive:
```
Invalid `"arrowParens"` value. Expected "always" or "avoid", but received `true`.
```

**Comment by CiGit** [comment]
Certainly same cause as #313

**Comment by dc165015** [comment]
@CiGit [#313](https://github.com/prettier/prettier-vscode/issues/313) solution is to update prettier to 1.9.  I installed prettier@1.9.2 but got the same error: Invalid `"arrowParens"` value. Expected "always" or "avoid", but received `true`.

**Comment by afeinman** [comment]
Check to make sure you don't have two versions of a prettier extension installed. E.g. I had both "Prettier" and "Prettier Now" installed; the latter had the old boolean value in my config file.
