### ISSUE TITLE
vsCode not using the prettierrc file settings

### ISSUE THREAD

**Issue by Gandrwin** [prettier/prettier-vscode#384]
On the current project I am working my vscode is not using the global prettierrc.json settings file. For everyone else works fine but for me ( the only one with vsCode ) it just doesn't want to read the file. 
If I work on a branch without the prettierrc file, and use the same settings in the editor user settings, it works.
I am open to any suggestion on how to further test this, or what to add, change

**Comment by CiGit** [comment]
Is there a log in prettier's output panel ? developer console?

You can also debug this extension to see what's happening.
Reading prettierrc files is https://github.com/prettier/prettier-vscode/blob/v1.2.2/src/PrettierEditProvider.ts#L45-L52

**Comment by Gandrwin** [comment]
Works perfectly now. It was and error in the Developer Tool and I was not aware of it. Thanks for the help and sorry for bothering :+1:

**Comment by CiGit** [comment]
Was this error in relation to this extension?
In which case we should catch it and show it in the output panel.

**Comment by Gandrwin** [comment]
I am sorry for this (really) late reply. It was no in relation with the extension so everything works as it should. :+1:

**Comment by mawburn** [comment]
@Gandrwin 

![error](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
