### ISSUE TITLE
bracket notation not recognised by prettier

### ISSUE THREAD

**Issue by norbertK** [prettier/prettier-vscode#385]
I am using code like this:
fromProperty = "top";
...
fieldFilter['fromProperty'] = 500;

prettier transforms this to :
fieldFilter["fromProperty"] = 500;

which is wrong

**Comment by RobinMalfait** [comment]
Why is `fieldFilter["fromProperty"] = 500;` wrong and `fieldFilter['fromProperty'] = 500;` correct?

Prettier will use `"` because it is preferred.

**Comment by CiGit** [comment]
Both have the exact same meaning (in JS) ie: Access `fieldFilter.fromProperty`.

I think you want to access `fieldFilter.top` in which case you need a computed property: `fieldFilter[fromProperty]` notice the absence of quotes

**Comment by norbertK** [comment]
I always used property accessors with the single quote
(Syntax : 
object.property === object['property']
)
I tried it without the quotes, and it works fine.
I still think fieldFilter['xyz'] should be recognised by Prettier as a property accessor, because that is still valid.

**Comment by norbertK** [comment]
sorry - all good - problem was in my code

**Comment by RobinMalfait** [comment]
Alright, glad it worked out! I'm closing this issue :)
