### ISSUE TITLE
No support for language specific settings

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier-vscode#386]
e.g. having in VS Code settings:

```json
"[markdown]": {
  "prettier.tabWidth": 2
},
```
Is reported as _Uknown editor configuration setting_ and indeed has no effect

**Comment by CiGit** [comment]
VSCode only allows _some_ settings in language settings. mostly `editor. ...` like `editor.formatOnSave`

Extensions are unaware of those settings when using Settings API.(Without re-implementing the logic)

**Comment by CiGit** [comment]
Thanks for the link.

> `workspace.getConfiguration().get('[markdown]')['prettier.tabWidth']`

This is what I meant by re-implementing

I'm pretty convinced this should be implemented by VSCode.
We may have to annotate our settings tho. We already do that to support multiple workspace (`scope: "resource"`)

We already have a mean to scope settings by language, prettier config files support that.
https://prettier.io/docs/en/configuration.html#configuration-overrides

**Comment by CiGit** [comment]
Seems you use `.editorconfig` overrides should also work :smiley:

**Comment by medikoo** [comment]
> Seems you use .editorconfig overrides should also work 

Sure, but I just wanted to address the _prettier_ specificity, that for no code snippets it uses spaces instead of tabs (and then I would like to have it kept at `2`).

Now it seems wrong to put it in `editorconfig`, as it's general (not just for prettier), and I don't want to force `tabsWidth` setting when project is indented with tabs (`tabsWidth` should be up to developer liking).

> We already have a mean to scope settings by language, prettier config files support that.

If I can have config at home directory that will affect any project, then  indeed it can be solution (otherwise I don't want to pollute every single project repo with that).
I'll check it, thanks
