### ISSUE TITLE
.editorconfig settings not respected for Markdown files

### ISSUE THREAD

**Issue by medikoo** [prettier/prettier-vscode#387]
I have in .editorconfig:

```
[*]
indent_style = tab
```

While VSCode sees that properly and inserts _tabs_ on indentation, prettier converts indentation to spaces (it's not the case in JS, where prettier behaves as expected)

**Comment by CiGit** [comment]
Parser used seems to break with tabs. Prettier disables them for now
Source: 
prettier/prettier#3223

**Comment by medikoo** [comment]
@CiGit that's not true with latest version see:
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IJBMyAZiQA2BOBgBGZEmADWcGAGUs03FADmyGGQCuYkOwhgBw0RlWiyMGlLUBbEsZF6AVgQAeAISmz5CkrbgAGVU4R1NMbRgsSIAmML1lMgtkEHsyGQMqKC4sMlUYAHUOGAALZAAOAAYMXIhRAqksFNy4C2ZQjDI4AEdtXC7rEjsHJEEnDFFbXE0dPQJVNSE4AEVtCHh4jBgScSL2UuQYralcIQWAYQhbexSoaA6QbVEAFR3GLV0AX0+gA

**Comment by medikoo** [comment]
It's about JS snippets in code. 

Prettier with `useTabs`, inserts tabs in JS snippets within Markdown.

Problem is that `useTabs` does not seem to be set correctly for Markdown files by this plugin (the JS snippets are filled with spaces not tabs)

**Comment by CiGit** [comment]
Reopening, this will need some investigations

**Comment by ntotten** [comment]
We are respecting the config of the editorconfig in version 3.0. This issue is tracked with prettier here: https://github.com/prettier/prettier/issues/3223
