### ISSUE TITLE
Correct path to the "eslint" module error on Windows

### ISSUE THREAD

**Issue by marekkaczkowski** [prettier/prettier-vscode#391]
Windows 7
node `7.10.1`
VS Code `1.20.1`
Prettier `1.2.2`

Getting error in VS Code DevTools:
`[Extension Host] prettier-eslint [ERROR]: There was trouble getting "eslint". Is 
"C:\Users\*****\AppData\Roaming\npm\eslint" a correct path to the "eslint" module?`

Eslint installed globally
C:\Users\*****\AppData\Roaming\npm\eslint
`>eslint --version` prints out `v4.18.2`

**Comment by CiGit** [comment]
Have you installed eslint in your project?
How is your setup?

**Comment by marekkaczkowski** [comment]
Yes, with config-standard
`"eslint": "4.15.0",`
`"eslint-config-standard": "10.2.1",`

Looks like **VS Code 1.21.1 update fixed** eslint issue.

**Comment by CiGit** [comment]
Seems fixed, closing
