### ISSUE TITLE
Format code only using .prettierrc file

### ISSUE THREAD

**Issue by davidavz** [prettier/prettier-vscode#392]
I'm wondering if it's possible to format my code only applying settings which are in my `.prettierrc` file and not the VS Code default settings.

I think the plugin is merging config file settings and then VS Code default settings, is there a way to just have my config file settings?

**Comment by CiGit** [comment]
This is how it works.
What you may experience is prettier using its default settings, which are the same as our default.

**Comment by davidavz** [comment]
Ok this is the first time I use Prettier. 
Thanks for this information :+1:
