### ISSUE TITLE
Usability: error feedback easy to miss

### ISSUE THREAD

**Issue by joliss** [prettier/prettier-vscode#393]
When an error occurs during prettification, it can look like Prettier is just failing silently, with no apparent cause.

For example, say I have the following JavaScript file:

```js
export { foo };

export function foo() {
  console.log(       1,    2,          3);;
}
```

When I run the "Format Document" command, I'm expecting the file to be reformatted. However, since there is a syntax error that I didn't notice (`foo` is exported twice), prettification fails. To me, it looks like nothing is happening at all; the file is simply not being formatted.

After some sleuthing, I discovered that there is a clickable "Prettier" entry in the status bar, and that it changes to "X" when an error occurs:

<img width="484" alt="status bar" src="https://user-images.githubusercontent.com/524783/37483500-0dff7c90-287e-11e8-839c-d3772be0d52a.png">

It was not obvious to me that I should look for an error indicator in the status bar. For the longest time, I assumed that "Format Document" would simply silently stop working at random times, and I wasn't sure why.

Perhaps usability could be improved by providing a clearer error notification.

**Comment by RobinMalfait** [comment]
Since the notifications are now in the bottom left we have to re add them? Are you willing to provide a PR?

**Comment by joliss** [comment]
There's a bunch of other open source things I need to do, so I'm afraid it's unlikely I'll be able to send a PR for this in the near future.

**Comment by RobinMalfait** [comment]
I'll see if I can find some time in the near future. Thanks for the report though! Once I start working on it I'll mention you so that we can ping pong some ideas to make it usable!

**Comment by atombender** [comment]
As someone who does not have the status bar turned on, this is a pretty annoying problem. Prettier frequently stops working for unknown reasons. ESLint has the same issue, where operational errors (e.g. a package referenced by `.eslintrc` doesn't load) are hidden in the "ESLint Output" panel.

**Comment by RobinMalfait** [comment]
Ok I am going to bookmark this and add it to my todos since I totally forgot about this...

**Comment by CiGit** [comment]
Back with notifications !

**Comment by etiennejcharles** [comment]
@CiGit @joliss 

Is there something that pushed us to revert that commit? 
It was merged, but reverted 2 days right after [here](https://github.com/prettier/prettier-vscode/commit/ce62204e52b41064b195d9346cd588bea264eb46). 

And yup I did expect some visual feedback more _violent_  than the "X" I looked for maybe an hour scratching my head, to find out it wasn't my HTML formatter not working, but rather "prettier" being the issue - 

What's your take on this ?

**Comment by shlajin** [comment]
@CiGit @joliss I'm also interested in this popup, since this little "X" just stays away of the sight most of the time. Is there any chance we can bring the popup back?
