### ISSUE TITLE
Missing way set --config option

### ISSUE THREAD

**Issue by hayes** [prettier/prettier-vscode#394]
Prettier exposes a --config option to specify a path to a config file.  This is useful if you want to put you config for prettier in a shared module.  Currently the vscode plugin does not expose any way to set this option.

**Comment by CiGit** [comment]
You can use your shared config by requiring it. 
.prettierrc.js
```js
module.exports = require('path/to/shared/settings')
```

**Comment by hayes** [comment]
Yup, not a hard problem to work around, just something that could be nice to have in the future. If I have some time later this weekend I might try to put a PR together

**Comment by CiGit** [comment]
Closing as duplicate of #254
