### ISSUE TITLE
Format on paste creates crazy indentation

### ISSUE THREAD

**Issue by MarkKahn** [prettier/prettier-vscode#398]
Minimal test case:

```js
export default class Foo {
  fn = () => 42;
}
```

Highlight the 2nd line.  Copy & paste.  Yields:

```js
export default class Foo {
                 fn = () => 42;
               }
```

**Comment by CiGit** [comment]
Seems to be indented relative to `class`.
Issue with prettier's range formatter.

**Comment by CiGit** [comment]
See prettier/prettier#4206

**Comment by lumixraku** [comment]
Does this bug solved?

**Comment by wKich** [comment]
In VSCode 1.34 seems work as expected.

**Comment by ntotten** [comment]
I am not able to reproduce this anymore in version 3.0. Please reopen if you are still seeing this issue.

Note, version 3.0 preview is available here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
