### ISSUE TITLE
requireConfig setting not working

### ISSUE THREAD

**Issue by tylerthehaas** [prettier/prettier-vscode#400]
In my project I don't have a prettier config file or a editorconfig file however prettier is still being run. I currently have my settings in user settings 

```
  "prettier.requireConfig": true,
  "prettier.trailingComma": "all",
```

**Comment by tylerthehaas** [comment]
That is not what the documentation says...

https://github.com/prettier/prettier-vscode#prettierrequireconfig-default-false

**Comment by tylerthehaas** [comment]
actually it was a setting on my eslint extension that was causing this. Sorry for the confusion.

**Comment by RobinMalfait** [comment]
Oh whoops I thought you just had some setting regarding styling. My bad, I'm sorry!

> **Note to self:** read the issues completely!
