### ISSUE TITLE
Wrong prettier.ignorePath provided

### ISSUE THREAD

**Issue by warpdesign** [prettier/prettier-vscode#401]
I am getting this error:

```
Wrong prettier.ignorePath provided in your settings. The path (e:\docs\dev\onmap_v6\yo\.prettierignore) does not exist.
```

The problem is that the path exists.

Here is my configuration:

```
"prettier.ignorePath": "e:\\docs\\dev\\onmap_v6\\yo\\.prettierignore"
```

The path exists:

```
dir e:\docs\dev\onmap_v6\yo\.prettierignore
Directory of e:\docs\dev\onmap_v6\yo
23/03/2018  11:44                99 .prettierignore
```

It's on Windows 10 with prettier plugin `1.2.2` and the latest VSCode insider:

Version 1.22.0-insider
Commit b75321329388d74e34f79dcfcb789246e31836a8
Date 2018-03-22T06:16:52.928Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by CiGit** [comment]
`e:\docs\dev\onmap_v6\yo.prettierignore` vs ` "e:\\docs\\dev\\onmap_v6\\yo\\.prettierignore"` ?

**Comment by warpdesign** [comment]
@CiGit I have to escape the `\` in the config file because it's inside a string. I don't need to do that when using the path inside the terminal.

Every VSCode setting with Windows style path uses `\\`, like: `"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",` and it works as expected.

**Comment by CiGit** [comment]
Seems in that case you can also use <kbd>/</kbd> it works in on my windows machine.

What I was asking was mostly `yo.prettierignore` vs `yo\\.prettierignore`

**Comment by warpdesign** [comment]
It's a typo in my GitHub comnent, I didn't properly escape `\.` so the \ was eaten. I corrected it.

**Comment by CiGit** [comment]
That error message comes from `fs.existsSync(path)`

**Comment by ntotten** [comment]
Is this still an issue? This is super old and I'm not able to reproduce. Please let me know.

**Comment by warpdesign** [comment]
I'll give it a try and let you know.

**Comment by warpdesign** [comment]
I had a quick look and could not reproduce: I tried to specify a prettierignore file with Windows style separators and it was used as expected:
>   "prettier.ignorePath": "C:\\\Users\\\warpd\\\Dev\\\react-explorer\\\\.prettierignore",

With latest VSCode `1.44.0` and vscode-prettier `4.2.0`.

Closing the issue.
