### ISSUE TITLE
Prettier is not working with multiply .eslintrc with 'eslintIntergartion' flag set to 'true'

### ISSUE THREAD

**Issue by Ateiri** [prettier/prettier-vscode#403]
Hello! I stuck with a problem of using multiply eslint configurations and prettier.

For example I'm using `"eslint.workingDirectories": ["/src/server", "/src/client"]` in my configuration for VSCode for Eslint plugin, but as I know `prettier` relates only to one configuration in application's root and can't handle both.

It makes sense, because I would like to autofix problems on both sides by one click.

**What about to specify directories where eslint configurations located and automatically apply rules for all nested directories?**

**Or maybe better to use CLI variant with shortcut?**

Thank you!

**Comment by AndyTyurin** [comment]
I found a solution, just to add .eslintrc to project directory, setup rules, plugins and other main settings, then just to extend base eslintrc by specific eslintrc of  the `"/src/server"` and  `"/src/client"` directories.

So prettier we look to base .eslintrc where get information about main styles and settings, for my goals it will be enough (fix on save).
My server's and client's eslints are looking for `webpack.config.[server|client].settings` just to resolve modules, so I haven't seen any errors in my vscode.

But I think it still workaround, so the problem still there.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
