### ISSUE TITLE
Attempting to undo an auto format can create invalid code

### ISSUE THREAD

**Issue by nickretallack** [prettier/prettier-vscode#404]
I'm not sure if this is a bug in Prettier or VSCode.  Here's what I did:

I generated a project using `create-razzle-app` and it created this file as `index.js`:

```javascript
import app from './server';
import http from 'http';

const server = http.createServer(app);

let currentApp = app;

server.listen(process.env.PORT || 3000, (error) => {
  if (error) {
    console.log(error)
  }
  
  console.log('🚀 started')
});

if (module.hot) {
  console.log('✅  Server-side HMR Enabled!');

  module.hot.accept('./server', () => {
    console.log('🔁  HMR Reloading `./server`...');
    server.removeListener('request', currentApp);
    const newApp = require('./server').default;
    server.on('request', newApp);
    currentApp = newApp;
  });
}
```

I set my VSCode preferences like this:

```json
{
    "editor.tabSize": 2,
    "editor.insertSpaces": false,
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,
    "editor.minimap.enabled": false,
    "prettier.semi": false,
    "prettier.arrowParens": "always",
    "prettier.trailingComma": "all",
    "prettier.bracketSpacing": false,
    "prettier.useTabs": true,
}
```

Then I hit Save on that file, and then hit control-Z.  Now it looks like this:

```javascript
import app from './server';
import http from 'http';

const server = http.createServer(app);

let currentApp = app;

server.listen(process.env.PORT || 3000, (error) => {
  if (error) {
    console.log(error)
  }
  
  console.log('� started')
});

if (module.hot) {
  console.log('✅  Server-side HMR Enabled!');

  module.hot.accept('./server', () => {
    console.log'🔁  HMR Reloading `./server`...');
    server.removeListener('request', currentApp);
    const newApp = require('./server').default;
    server.on('request', newApp);
    currentApp = newApp;
  });
}
```

As you can see, a parenthesis was removed from the final call to console.log.  Now the syntax is invalid.  If I fix the syntax error by adding that parenthesis back, then hit save again, Prettier deletes a parenthesis from the first console.log.

Something strange is going on with the undo history, and it probably has something to do with those special characters being in string literals.

**Comment by nickretallack** [comment]
Update: If I set my Prettier settings to `"prettier.singleQuote": false` and format razzle's `index.js`, then set it to `"prettier.singleQuote": true` and format it again, it causes exactly the same bug, no undo-ing necessary.

**Comment by CiGit** [comment]
I've similar errors with that file, although not at the same place as you.
Seems to be produced by those symbols. 
I've quickly tried to debug it: when it is formatted, prettier gives a correct output, we then create a TextEdit which is passed to VSCode. At that point it seems to be correct.
