### ISSUE TITLE
Prettier on VS Code unfolds my code blocks on save

### ISSUE THREAD

**Issue by Mahan-F** [prettier/prettier-vscode#408]
I'm using Prettier on VS Code with the `editor.formatOnSave` enabled. Every time I save my javascript file and prettier runs it unfolds all my functions. Is there a way to prevent this from happening?

I have a large javascript file and would like to keep the functions collapsed.

You can see in the GIF below that even adding a blank line unfolds a bunch of my functions.
![](https://i.scrny.me/8vhH.gif)

**Comment by RobinMalfait** [comment]
My guess is that VS Code can't keep track anymore and therefor unfolds all the functions.

I don't know a solution immediately but here are some options which may or may not be an option.

1. Split up your code in multiple files so it is easier to manage (might not be an option for you)
2. Use a keyboard shortcut to unfold all functions (http://d.rbn.nu/vpPaHq.png)

**Comment by CiGit** [comment]
You may try out this experimental feature as of VSCode 1.22 https://code.visualstudio.com/updates/v1_22#_syntax-aware-folding

**Comment by cozuya** [comment]
@CiGit Toggling this from `auto` to `indentation` made prettier stop un-folding everything.

**Comment by alexamy** [comment]
seems that **syntax-aware-folding** setting is gone in vscode 1.30.1
does anyone know how to solve this problem?

**Comment by bgold0** [comment]
Did anyone ever solve this?

**Comment by CiGit** [comment]
`editor.foldingStrategy` is the setting. experimental setting disappeared tho. It is now enabled by default as of VSCode 1.24

as @cozuya said, setting `editor.foldingStrategy` to "indentation" is maybe what you are looking for.
I'll close this issue as there is nothing we can really do here. And VSCode seems to handle it already.

**Comment by protoEvangelion** [comment]
@CiGit setting `editor.foldingStrategy` to "indentation" does not resolve the issue. Do you know where I can start looking to try to resolve this?

**Comment by CiGit** [comment]
@protoEvangelion Sorry, I don't. In vscode's repo maybe 😞
