### ISSUE TITLE
Migrate repository to new prettier organization?

### ISSUE THREAD

**Issue by ConAntonakos** [prettier/prettier-vscode#41]
@esbenp Would you be perhaps open to this?

Here is the original Twitter thread: https://twitter.com/ConAntonakos/status/834084544655527937

**Comment by esbenp** [comment]
Yes of course, I think that would be for the better. People like @CiGit have also been working far harder on this than I do so it makes total sense :-)

**Comment by ConAntonakos** [comment]
Fantastic! I created a new issue under the prettier repository: https://github.com/prettier/prettier/issues/781.

**Comment by ConAntonakos** [comment]
Hey, all. Are we still interested in doing this? If not, no worries. I can close this. Pinging @esbenp. Thanks!

**Comment by RobinMalfait** [comment]
It would be nice to do it, just to make it more "official" to new users. But `prettier-vscode` is mentioned as an official plugin on the prettier website. https://prettier.io/

**Comment by esbenp** [comment]
Hey all. I am interested in moving this to the organization since I have no time for working on this. Big shoutout to @CiGit and the rest of you for keeping things moving. The only thing I am not sure on how to do is handing over the VS Code Extension? Does anyone know where I can hand it over to someone else?

**Comment by CiGit** [comment]
It seems the only way to do it (*now*) would be to unpublish and publish with a new publisher. However, there are no redirects, stats etc... This is discouraged for a popular extension. 
> 115,848 installs

I think we belong to this category.

Sources in case I missed something: 
- https://github.com/Microsoft/vscode/issues/3670
- https://github.com/Microsoft/vscode/issues/4772
- https://github.com/Microsoft/vscode/issues/10551

**Comment by esbenp** [comment]
Alright, I do not remember; I added you as a member in the extension admin, right? I do not mind keeping it in my account I just dont have the time to contribute too it. But if you have full access that is good enough for me- then I just need to migrate this repo to the prettier organization. What do you think?

**Comment by CiGit** [comment]
I can publish this extension with your publisher (esbenp). I don't think I can do more.
To handle admin tasks, it would be better if we are 2 at least. OSS is time costly for everyone, I have unavailability too.

**Comment by azz** [comment]
Extension ownership and repository ownership are independent issues, right?

@esbenp You should have sufficient permissions to move this repository to the `prettier` organisation. Do you still want to do that? 

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization

**Comment by esbenp** [comment]
![screen shot 2017-08-02 at 11 02 44](https://user-images.githubusercontent.com/934819/28866070-225332f8-7772-11e7-8103-329f752c73d9.png)

Woohooo what a day :-) :+1:

**Comment by esbenp** [comment]
As a note: if anyone finds a way to transfer ownership of the extension I am interested in that as well :-)

**Comment by CiGit** [comment]
Hum seems you lost your admin rights, can we add @RobinMalfait as a collaborator on this repo? If he still agrees. He's helping a lot 😄
