### ISSUE TITLE
Untitled files and eslintIntegration uses babylon parser

### ISSUE THREAD

**Issue by ghost** [prettier/prettier-vscode#412]
Seems Prettier is not supporting JSON formatting because every time I get errors if I'm trying to format JSON.

Example try to format this code:

```json
{"name": "Benas"}
```

So why it's not disabled by default?

I need to do this by myself to disable it with:

```json
  "prettier.disableLanguages": [
    "vue",
    "json"
  ],
```

**Comment by CiGit** [comment]
Prettier supports json and jsonc. 
Mind sharing your errors?

**Comment by bsvipas** [comment]
```
2018-4-11 15:17:07:
-------------------
Unexpected token, expected ";" (Untitled-3:1:8)
> 1 | {"name": "Benas"}
    |        ^

2018-4-11 15:17:11:
-------------------
Unexpected token, expected ";" (Untitled-3:1:8)
> 1 | {"name": "Benas"}
    |        ^

```

**Comment by CiGit** [comment]
Seems to use a wrong parser.
Is your language correctly set for this untitled file?
Your error looks like a _babylon_ one

**Comment by bsvipas** [comment]
![image](https://user-images.githubusercontent.com/30043375/38616495-e0aeae1c-3d9c-11e8-8459-36c25de3f990.png)

![image](https://user-images.githubusercontent.com/30043375/38616533-045e2450-3d9d-11e8-844a-639cb3623cdd.png)

**Comment by CiGit** [comment]
Found!

It is with eslintIntegration turned on and Untitled files. It tries to infer a parser from file's extension. In this case: none -> babylon.

Current workaround:
- Disable eslintIntegration
- Save your file

**Comment by bsvipas** [comment]
Thanks, maybe it's possible somehow to check if it's Unitled file and use `none` parser instead of `babylon` if extension is `json`? I want somehow to contribute maybe any explanation or share your ideas and I will try to open a PR.

**Comment by CiGit** [comment]
The problem is here: https://github.com/prettier/prettier-vscode/blob/v1.2.2/src/PrettierEditProvider.ts#L162

We pass "Untitled-#" to eslint. ( and same for stylelint)
I think Untitled files should go straight to prettier. They have no existence, reading a config file which is file system based makes no sens to me.

**Comment by bsvipas** [comment]
@CiGit I can agree

**Comment by monkindey** [comment]
hi, Any progress about this. It would be nice that I can quick format code copied from otherwhere.

**Comment by ntotten** [comment]
This should now be fixed, we use the parser based on the language set in VS Code for untitled files. You can try out version 3.0 preview which has this fix here: https://marketplace.visualstudio.com/items?itemName=prettier.prettier-vscode
