### ISSUE TITLE
Disabling editor.formatOnSave has no effect after update

### ISSUE THREAD

**Issue by isurugiu** [prettier/prettier-vscode#415]
Hi,

I have recently updated to Version 1.22.2 on my Mac but I am not able to disable the editor.formatOnSave. I have set it to false both on the workspace and user settings and also checked the extensions but neither of that lead to happiness.

Can anyone reproduce it on their ends?

Best,
-Iulian

**Comment by CiGit** [comment]
I'm quite sure this has nothing to do with this extension. Can you confirm by disabling this extension and trying with the default formatter on a javascript file?
