### ISSUE TITLE
installing prettier from market place does not add a json formatter

### ISSUE THREAD

**Issue by Pomax** [prettier/prettier-vscode#418]
STR:
- clean install of visual studio code
- visit https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
- click the install button
- allow windows to open that with visual studio code
- let the install finish
- open a .json file in visual studio code
- hit alt-shift-f to auto-format

expected result: prettier-formatted JSON
actual result: "there is no formatter for json files installed".

**Comment by CiGit** [comment]
Some strange things here.

I've never seen an install button on the marketplace. Only install instructions.

There is at least a default JSON formatter in VSCode (OOTB), a formatter should exist. Can you try without prettier extension ? 
And installing it in the extension panel ?

**Comment by Pomax** [comment]
I went for prettier because I got was getting that "there is no formatter" on a vanilla install of vscode.

**Comment by CiGit** [comment]
From settings:
```json
// Enable/disable default JSON formatter (requires restart)
  "json.format.enable": true
```
Seems you have some troubles with VSCode's install ...

Every time you install an extension, VSCode asks for a reload (restart?)
Seems you managed to make it work. Closing

**Comment by rafsawicki** [comment]
@Pomax I had similar issue after manually setting loader to `"typescript"` (following some SO answer). It didn't parse JSON files correctly and thus prettier wasn't able to format them. After removing this setting and allowing prettier to choose loader dynamically the problem went away.
