### ISSUE TITLE
Flow and prettier no longer works (when TypeScript and Javascript Language Features disabled)

### ISSUE THREAD

**Issue by pbeshai** [prettier/prettier-vscode#419]
prettier-vscode v1.3.0
flow-for-vscode v0.8.0
vscode v1.22.2 (this just updated today for me)

Prettier and flow used to work together in vscode as recently as yesterday. Today, I'm seeing an error when I run Format Document:

> There is no formatter for 'javascript'-files installed.
![image](https://user-images.githubusercontent.com/793847/38770632-ddace9ec-3fe3-11e8-884d-f6bf6bdab53f.png)

I've figured out this error goes away and Prettier works again if I enable TypeScript and Javascript Language features. Sadly I have to disable this to do programming with Flow.

![image](https://user-images.githubusercontent.com/793847/38770639-fe449e48-3fe3-11e8-980f-f7475dfeb2d5.png)

[Description from the Flow extension that references disabling the built-in plugin](https://github.com/flowtype/flow-for-vscode)
> You will want to disable the TypeScript built-in extension for your project

So now it seems I have to choose whether to have prettier enabled in the editor by leaving the Typescript and Javascript Language features enabled and not be able to use flow, or to use flow and not use prettier in vscode. It probably isn't ideal that Typescript and JS are in a single builtin extension, but that seems out of our hands.

**Comment by CiGit** [comment]
the built-in extension is the one providing default formatter .
Can you try to reinstall prettier and restart VSCode, I've no such issue with the same setup you have...

**Comment by pbeshai** [comment]
Seems the update to 1.3.1 has fixed it (didn't have a chance to uninstall/reinstall). Who knows! Back to happiness at least, thanks for all your efforts on this project.
