### ISSUE TITLE
Prettier turns typescript function call with generics into something weird that doesn't work

### ISSUE THREAD

**Issue by AlmaasAre** [prettier/prettier-vscode#420]
My code turns from:

```typescript
const result: ApolloQueryResult<ITermScreenQueryResult> =
      await apolloClient.query< ITermScreenQueryResult > (options);
```

into:

```typescript
const result: ApolloQueryResult<ITermScreenQueryResult> =
      (await apolloClient.query) < ITermScreenQueryResult > options;
```

And not sure what could be causing this :|

Using prettier, editorconfig and tslint:

editorconfig

```
# http://editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

```

tslint:

```
{
  "rules": {
    "ban": false,
    "class-name": true,
    "comment-format": [true, "check-space", "check-lowercase"],
    "curly": true,
    "forin": true,
    "interface-name": true,
    "jsdoc-format": true,
    "label-position": true,
    "member-ordering": [true, "public-before-private", "variables-before-functions"],
    "no-angle-bracket-type-assertion": true,
    "no-arg": true,
    "no-bitwise": true,
    "no-console": [true, "debug", "info", "time", "timeEnd", "trace"],
    "no-construct": true,
    "no-parameter-properties": false,
    "no-debugger": true,
    "no-duplicate-variable": true,
    "no-empty": true,
    "no-eval": true,
    "no-invalid-this": true,
    "no-string-literal": false,
    "no-switch-case-fall-through": false,
    "no-unused-expression": true,
    "no-var-requires": false,
    "no-var-keyword": true,
    "radix": true,
    "switch-default": true,
    "triple-equals": [true, "allow-null-check"],
    "typedef": [
      "call-signature",
      "parameter",
      "property-declaration",
      "variable-declaration",
      "member-variable-declaration"
    ],
    "variable-name": false
  }
}

```

Prettier:

```
{
    "useTabs": false,
    "printWidth": 100,
    "tabWidth": 2,
    "singleQuote": true,
    "trailingComma": "all",
    "jsxBracketSameLine": true,
    "parser": "babylon"
}

```

**Comment by CiGit** [comment]
We do not read from tslint files (yet #414 ) But I don't get this output on latest version at least.

Can you check which prettier version you use ? Over bottom right _prettier_ a tooltip says which version this extension used lately.

**Comment by AlmaasAre** [comment]
Alright, I'm using 1.3.0

**Comment by CiGit** [comment]
You didn't install prettier in your project?

**Comment by AlmaasAre** [comment]
Prettier is installed in my project. When I run the script in terminal, it formats the code correctly. But when I format the code in vscode is make this weird formatting of some function calls. Might be prettier colliding with something else? Not quite sure why it would format it like this, and why you were able to reproduce it. 

Using prettier 1.10.2 in the project, but vscode uses 1.12. The script in my package.json:

```json
{...
"autoformat": "prettier es5 --write --loglevel=error '**/*.{ts,tsx,json,js,jsx,css,scss}'",
...
}
```

**Comment by CiGit** [comment]
Are you using eslintIntegration and have an eslint config somewhere?

**Comment by AlmaasAre** [comment]
No, I have a babelrc, but that shouldn't be a problem..

```
{
  "sourceMaps": "both",
  "presets": [
    "es2016",
    [
      "es2015",
      {
        "modules": "commonjs"
      }
    ],
    "stage-0",
    "react"
  ]
}
```

**Comment by CiGit** [comment]
Could you try your file in an empty project?
Or even better, try to debug that output :relaxed: 
I'm out of ideas...

**Comment by AlmaasAre** [comment]
Will you support the typescript-parser any time soon?

**Comment by CiGit** [comment]
Prettier supports typescript. But I'm not sure I understood your question correctly.

**Comment by AlmaasAre** [comment]
Yeah, need the typescript-parser instead of the babylon-parser to make it work correctly. See that you have progress on that part here: https://github.com/prettier/prettier-vscode/pull/414

**Comment by CiGit** [comment]
#414 is a new option which will read your tslint config file.
You still have a problem with parsing your typescript file.

can you try to remove `"parser": "babylon"` from your prettier config file? Let the tool infer the right parser.

**Comment by AlmaasAre** [comment]
That actually seemed to do the trick! Thanks!
