### ISSUE TITLE
markdown table

### ISSUE THREAD

**Issue by ZhenpengWu** [prettier/prettier-vscode#421]
When I add a table in the md, prettier cannot auto format this file. I have tried reinstall prettier plugin in the vscode, but it also doesn' work. 

<img width="390" alt="screen shot 2018-04-18 at 17 04 17" src="https://user-images.githubusercontent.com/18113526/38964251-a1cddc3e-432a-11e8-83a3-7c3d668bb993.png">

**Comment by ZhenpengWu** [comment]
nvm, I think it is conflict with other extensions.

**Comment by XYShaoKang** [comment]
I also encountered this problem.
After testing, it found conflicts with the `Markdown All in One` extension.
Add `"markdown.extension.tableFormatter.enabled": false` to `User Settings` and restart `vscode` to solve this problem.

**Comment by gtaylor1981** [comment]
See the bug raised here: https://github.com/yzhang-gh/vscode-markdown/issues/317
