### ISSUE TITLE
Can't format unsaved document

### ISSUE THREAD

**Issue by garyking** [prettier/prettier-vscode#422]
If I create a new document, without giving it a filename, etc. and type some JS code, then use `Format document`, then VSC falls back to the built-in JS formatter rather than Prettier.

Is it possible instead to have Prettier work even on unsaved documents, with no filenames?

**Comment by CiGit** [comment]
It should work on unsaved documents.
Does it work on saved files in your case?

**Comment by garyking** [comment]
Yep it works on saved files just fine.

**Comment by CiGit** [comment]
I think prettier is in both cases. The default formatter doesn't add semicolons.
I would say the difference comes from settings
In the _file_ case you have a config file instructing prettier to use single-quote. Configuration which can't be resolved when the file doesn't exist. There is no path to look at.

**Comment by garyking** [comment]
Okay thanks that would explain it.
