### ISSUE TITLE
Adds extra undo step even if no changes were made

### ISSUE THREAD

**Issue by garyking** [prettier/prettier-vscode#423]
I enable `formatOnSave` for JS files and use Prettier as my formatter. I save a file. No changes were made. Yet this ext still adds an extra step to the undo history, so that when I hit Undo, nothing happens, because the first undo step is from Prettier, even though no changes were made.

This is probably the same problem as [this issue](https://github.com/Microsoft/vscode/issues/46075), and therefore could use a similar solution.

**Comment by CiGit** [comment]
I just tried and don't see this issue.
Have you tried with only prettier installed ?
It may be any other extension doing something _onSave_

**Comment by garyking** [comment]
Okay thanks for confirming, I will continue investigating.

**Comment by garyking** [comment]
@CiGit I think I'm just experiencing this in JSON files, not JS. Can you check with JSON files to confirm?
