### ISSUE TITLE
css formatter base64 bug

### ISSUE THREAD

**Issue by missy0u** [prettier/prettier-vscode#424]
# My base64:

`background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAABYCAMAAACwAkWeAAABrVBMVEVMaXH////////////////////////////////////////////////////////////1Mz31NT30Mz3////////////////////////////////////////////////////////////////1Mz3////////////////////////////////////////////////////////////////////////////////////1Mz3////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////1OkP2TVX1N0D2U1v7trr////0Mzz1PUb7r7L3X2ctnWcvAAAAinRSTlMA0aLFHQ7mHO0BsOMEEqYlyGW9hg27nA8QCfGtLKcrbuQL8/Olr9iESJXiGPD9PjNm9P6hOFzMAogZQoqPLXCz4X8iqEaOsvWTNnngX+UHjQxPEZdZG8CCIGOHSe7ZFbpYm958GmLoBc4K8ve53T3NA0p3JFepuOus1ecy12rWO7bf6coU+9j34EZgVDUdAAACA0lEQVR42u3VVW8bURRF4e0mjT11wHbixEkahjZMDZVSZmZmZmbmrsBv7tXI8tj1+E5emofK39uRjmT5XI2W/lZTXdJ/pWubggxFcW0tl1XFXtJ6ZHWQjLeyKL8BDftSVZXAlGVvdxI4LWlyAkZq18hfWy0YfTJWgTFWIR+nzuM6JOMJrnelylMVxYic2eJO5Y8/jWJ8/pZ3526Mo3XK+PgBIzmpXJUYLcpW9xVjWDkGMTYqV2oC+FKjbCXA9vx3egO8V5ZmoLVNecaBh/K4Z9ujfI96gbA8J7w51xTwTJ52uC8/q4Fqb6wH7snPU+CyN14DKuWnAmj0xlJgmfwsB1b8y8UqoFZ+6oEduUdYJ187ocSbWoBh+QpBxMlMY8BK+doFZL6dC3fhlvw9ALqUthkYVwEhGN0gV18EWm+qgLPARUeG8wK4roIagasyqoEZFXZkEwwck4YG4HWdLJojcCes58CgrC4BPXoJHL4tiwNrgaj6WZR2vWJRkirthWDnzAunToYasBrpXh/WEtiPq0xBOnF1Kkg4ghE5ruDNprKyJsu/XIoWOvFYR0cs7gS18Hdi1pWYDmjhr9m0hGNt4fxsRtzawgVvMWZt4Zy32GFt4fesRWsLY1k/bW1h3FuMW1voJLzz2Fs4nd78MR3UQvOEP+cW5ostLLaw2MJiC/+rFv4BHHP+Y8aIQxcAAAAASUVORK5CYII=)`

# After formatting:

`background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAABYCAMAAACwAkWeAAABrVBMVEVMaXH////////////////////////////////////////////////////////////1Mz31NT30Mz3////////////////////////////////////////////////////////////////1Mz3////////////////////////////////////////////////////////////////////////////////////1Mz3////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////1OkP2TVX1N0D2U1v7trr////0Mzz1PUb7r7L3X2ctnWcvAAAAinRSTlMA0aLFHQ7mHO0BsOMEEqYlyGW9hg27nA8QCfGtLKcrbuQL8/Olr9iESJXiGPD9PjNm9P6hOFzMAogZQoqPLXCz4X8iqEaOsvWTNnngX+UHjQxPEZdZG8CCIGOHSe7ZFbpYm958GmLoBc4K8ve53T3NA0p3JFepuOus1ecy12rWO7bf6coU+9j34ezgvdudaaaca0leqvr42u3vvw8burrf4e0mjt11whbixekahjzmdzvszmzmzmbmrsbv7txi8tj1+E5emofK39uRjmT5XI2W/lZTXdJ/pWubggxFcW0tl1XFXtJ6ZHWQjLeyKL8BDftSVZXAlGVvdxI4LWlyAkZq18hfWy0YfTJWgTFWIR+nzuM6JOMJrnelylMVxYic2eJO5Y8/jWJ8/pZ3526Mo3XK+PgBIzmpXJUYLcpW9xVjWDkGMTYqV2oC+FKjbCXA9vx3egO8V5ZmoLVNecaBh/K4Z9ujfI96gbA8J7w51xTwTJ52uC8/q4Fqb6wH7snPU+CyN14DKuWnAmj0xlJgmfwsB1b8y8UqoFZ+6oeduudyj187ocsbwobh+QpBxMlMY8BK+doFZL6dC3fhlvw9ALqUthkYVwEhGN0gV18EWm+qgLPARUeG8wK4roIagasyqoEZFXZkEwwck4YG4HWdLJojcCes58CgrC4BPXoJHL4tiwNrgaj6WZR2vWJRkirthWDnzAunToYasBrpXh/WEtiPq0xBOnF1Kkg4ghE5ruDNprKyJsu/XIoWOvFYR0cs7gS18Hdi1pWYDmjhr9m0hGNt4fxsRtzawgVvMWZt4Zy32GFt4fesRWsLY1k/bW1h3FuMW1voJLzz2Fs4nd78MR3UQvOEP+cW5ostLLaw2MJiC/+rFv4BHHP+Y8aIQxcAAAAASUVORK5CYII=)`

**Comment by RobinMalfait** [comment]
Is the problem that it somehow converted lowercase values to uppercase values?

![](http://d.rbn.nu/ZV9Ijh.png)

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
