### ISSUE TITLE
Wrong formatting of nested ternary operator by prettier

### ISSUE THREAD

**Issue by bondom** [prettier/prettier-vscode#425]
In my project I use `eslint` with `prettier`(default config)

I have the following piece of code:
```
fetch(request.url, {
      mode: 'cors',
      method: method,
      headers: getHeaders(),
      body: request.data
        ? method !== 'get' 
          ? JSON.stringify(request.data) 
          : undefined
        : undefined
    })
```

This piece of code is valid for prettier, you can check it in [prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzOMwAsAUAnOARwFc4BnGAOmLwBsAaAAmAB0pGPOBbCAEziSMA5JDxkh9Np24YsfQV1l9J7aYyxwAhvzGCA5hgASWnWRwBKFWsYAjPgE9BBEuSq9NMTVOuMA-I0UYOV5GAEIAXnDhAxghRm8fP0YAKQBlAHkAOUoKPABLKD081Ht8IlIKSndPc3jVRMFiKH5UArheBLVG5rhWqHbOgF9zEHoQCAAHGDzoMmRQTTw8CAB3AAVFhDmUTQA3CDzeUZAbPE0wAGsMVInzgr1kGDxSMYKyODwYNbO9Lk1kVCaWjvMYAKzIAA8AEJnS7XTSKAAybQBQJBIFuYg+yBOmhs9lo0GOE3ysAA6ocgsgABwABjGJIg7zJZwmOJJ5A+uzgx2cxDyBG+ml+-yQgOBcDG7y4eUez0lIDI91ocAAisQIPBURKxp4bBTeFSkAAmXVnPK0e4AYQgXD+OKg0B5Y2I7wAKnjtuL3oNBkA)

Also when I use WebStorm  **with the same config** this piece of code is also valid.

But when I use VScode with this plugin, prettier complains about formatting, and if I turn on autoformat, code above is formatted to:
```
fetch(request.url, {
  mode: 'cors',
  method: method,
  headers: getHeaders(),
  body: request.data
    ? method !== 'get' ? JSON.stringify(request.data) : undefined
    : undefined
});

```

It seems that there is a problem with this plugin...

I am interested because in our project some developers use VSCode, some developers - WebStorm

**Comment by mubaidr** [comment]
Do you have `eslint` integration enabled? 

Please check this: https://github.com/prettier/prettier-vscode/issues/465#issuecomment-394253763

**Comment by bondom** [comment]
Yes, eslint integration is enabled

**Comment by mubaidr** [comment]
Then most probably: 

> You need to add prettier to eslint config file, this will make sure eslint ignore rules related to prettier formatting. i.e.

> extends: ['standard or any other set of rules', 'prettier'],
and make sure to install this package in your project root (where eslint is installed):

> npm install eslint-config-prettier

**Comment by CiGit** [comment]
This extension also picks up your project's prettier if any. You may have an older prettier version.
