### ISSUE TITLE
Command "Format Document" doesn't work

### ISSUE THREAD

**Issue by ChristianHardy** [prettier/prettier-vscode#426]
When i use format document from command pallette  (Ctrl + P) Visual Studio Code format the document avoiding all my user settings from prettier.*

**Comment by ChristianHardy** [comment]
I asume that "format document" its running the editors default

**Comment by RobinMalfait** [comment]
Could you share your prettier settings, prettier version (hover over the left bottom prettier status bar item) and your vscode version?

Also using `format document` vscode will run all its formatters it has registered for the file/extension. This extension registers itself as a formatter so that should not be a problem.

**Comment by jsundquist** [comment]
I recently started to run into the same or similar issue within the past few weeks. Prettier suddenly started to not format full documents or ignored prettier configuration settings.

VS Code: 1.22.2
Prettier: 1.3.1

Previously I was able to format both the html and javascript within a Vue.js file. Beginning recently however, only the script section of the file would be formatted. The section would also ignore the configuration rules that I have set.

For instance if I have the configuration values of 

```
{
    "prettier.singleQuote": true,
    "prettier.trailingComma": "all",
}
```

and code of 

```
<template>
  <div>
            <h1>{{msg}}</h1>
  </div>
</template>

<script>
export default {
  props: ['msg'],
}
</script>
```

Prettier would format the code as 

```
<template>
  <div>
            <h1>{{msg}}</h1>
  </div>
</template>

<script>
export default {
  props: ["msg"]
}
</script>
```

where I would expect it to format it as

```
<template>
  <div>
    <h1>{{msg}}</h1>
  </div>
</template>

<script>
export default {
  props: ['msg'],
}
</script>
```

**Comment by ChristianHardy** [comment]
**My Visual Studio Code "About"**
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Prettier extension version: 1.3.1**

**Comment by ChristianHardy** [comment]
@RobinMalfait have some news/suggestions about this problem?

**Comment by nikosk93** [comment]
It's not working for me too even though it shows up in status bar.
I use the command line tool until it's fixed.

**Comment by RobinMalfait** [comment]
This is in there by default, is that the problem? https://github.com/prettier/prettier-vscode#prettierdisablelanguages-default-vue

**Comment by ChristianHardy** [comment]
Some news about this issue??
I have unistalled my VS code and install a new one.

![screenshot_1](https://user-images.githubusercontent.com/9417617/40080503-c54fa198-5850-11e8-9495-5eb13057b9d1.jpg)

![screenshot_2](https://user-images.githubusercontent.com/9417617/40080528-dc71d972-5850-11e8-8d6a-fa1ff8c8d9df.jpg)

About VS Code:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by ChristianHardy** [comment]
:(

I have to unistall prettier completely and use other alternative, so sad for me, thanks to all, i will close this issue for lose attention

**Comment by lukebatchelor** [comment]
Heya @ChristianHardy I think your issue may have been the same as mine and a few other peoples.

https://github.com/prettier/prettier-vscode/issues/439
https://github.com/prettier/prettier-vscode/issues/440
https://github.com/prettier/prettier-vscode/issues/468

If you wanted to take a look, see if you have any other extensions installed that might be trying to formatOnSave or override the "format document" command.

**Comment by janat08** [comment]
lol installing beautify also worked for me :D.

**Comment by janat08** [comment]
I set requireconfig to true.

**Comment by SgtPooki** [comment]
Format document was not working on a workspace `.settings.json` file when setting

```json
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```

But I can change it to 

```json
  "[jsonc]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
```

and formatting returns. I found out that I had set `"prettier.requireConfig": true,`.. changing that to false solved my problem.
