### ISSUE TITLE
Single Quote and trailing comma rules conflict with tslint

### ISSUE THREAD

**Issue by rc-chandan** [prettier/prettier-vscode#428]
Related to #206
## Project settings:
1. tslint  config has rule defined to wrap strings in single quotes and trailing comma enabled.
2. This is my vscode user settings 
```javascript
{
  "tslint.autoFixOnSave": true,
  "editor.formatOnSave": true
}
```
3. This is my prettier config:
```javascript
export default {
  useTabs: false,
  printWidth: 80,
  tabWidth: 2,
  singleQuote: true,
  trailingComma: "all"
};
```
## Issue:
1. Saving the files toggle between double quotes and single quotes.
2. Same for trailing comma also, saving once adds trailing comma, saving again removes it.
3. **If I remove the prettier config file** and set the below configs in vscode user setting, then it works fine.
```javascript
{
  "tslint.autoFixOnSave": true,
  "editor.formatOnSave": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all"
}
```

**Comment by CiGit** [comment]
your prettier config file runs on nodejs. it should be `module.exports = ...`

**Comment by rc-chandan** [comment]
I have tried with the JSON version also .prettierrc file. It also behaves the same way.

**Comment by CiGit** [comment]
Closing, stalled.
@dbuezas Maybe you can open an issue on that config?
