### ISSUE TITLE
Not formatting anything

### ISSUE THREAD

**Issue by Nxt3** [prettier/prettier-vscode#430]
Just switched to VS Code from Atom. I only have the `prettier` extension installed currently.

No matter what I do, I can't get Typescript or JSON files formatted using `Format Document` in the command palette.

My settings:
    "prettier.singleQuote": true,
    "prettier.trailingComma": "none",
    "prettier.printWidth": 120,
    "prettier.requireConfig": false,
    "prettier.eslintIntegration": false

I'm using 1.23.0 VS Code Insiders and Prettier 1.3.1.

**Comment by Nxt3** [comment]
I installed the stable version of VS Code and prettier works again.

**Comment by ChristianHardy** [comment]
@Nxt3 can you give me the link for windows please?? because in the site i just can find the 1.22.2

**Comment by jpboliv** [comment]
Hey! I've been having troubles with prettier formatting for a while now but with rails files, both .erb and .rb. With javascript files it works fine though.

I'm using VS Code 1.22.2 and prettier 1.3.1, I've tried with both "editor.formatOnSave": true and "editor.formatOnSaveTimeout": 500 and none of those work.

**Comment by CiGit** [comment]
@Nxt3 I've not tried insider version lately, but we had report that reinstalling (cleanly) prettier would correct some strange issues. Seems this is what you did with "stable" version.

Prettier doesn't format ruby (rails)

**Comment by Nxt3** [comment]
Uninstalling and reinstalling prettier in the Insider build didn't work.

**Comment by CiGit** [comment]
Even after removing `$HOME/.vscode-insider/extensions/esbenp.prettier-vscode${VERSION}` ?

**Comment by Nxt3** [comment]
Correct. That was the first thing I tried.

**Comment by louisnguyen1012** [comment]
Hi all,

I also have this issue.
I have more its information.

![image](https://user-images.githubusercontent.com/3841162/39452028-c72a1498-4c9e-11e8-941a-cc66b2076336.png)

**Comment by ChristianHardy** [comment]
@CiGit in this issue https://github.com/prettier/prettier-vscode/issues/426 i have been reported the same problem, but using Javascript files and VS v 1.22.2

More info about VS here

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Prettier extension version: 1.3.1

The problem: Using the format command "Shift + Alt + F" doesn't format the file with prettier, use de Vs default parameters

**Comment by CiGit** [comment]
VSCode **insider** is now **stable**. Problems mentioned with it have been resolved so far. Mostly due to an other installed formatter.
Closing !

**Comment by idoo** [comment]
now we have https://github.com/prettier/plugin-ruby
