### ISSUE TITLE
couldn't resolve parser 'css'

### ISSUE THREAD

**Issue by gastonmorixe** [prettier/prettier-vscode#432]
I have manually removed the `dynamicParsers` part, defaulting now to `babylon` even for `.css` extension and now it is working. 

Why is this happening? 

Thanks

**Comment by gastonmorixe** [comment]
For `css` extension I was getting `couldn't resolve parser 'css'`. I patched the extension as I mentioned previously and now it works.

**Comment by CiGit** [comment]
Could you send a patch so that I can understand correctly.

Are you using babylon to format css?
