### ISSUE TITLE
Prettier ignore pattern as a vscode setting option

### ISSUE THREAD

**Issue by gyandeeps** [prettier/prettier-vscode#435]
I want to ignore certain dir/file patters (regex) so that `vscode-prettier` can ignore those files. This can be different than what the project dictates.

**Use case:** I use prettier by calling it through command line and only supplying patterns which i want it to fix and not all the files. This way i don't have to maintain a `.prettierignore` file.

Sorry if this is a repeated question. I did search and I was not able to find any related issue.
If i can help to implement this with some direction on where to start with.

**Comment by CiGit** [comment]
I don't see the value here.
Maintaining prettierignore or _ignoreMeSettings_ doesn't feel different. One being available across IDE/cli tho.

**Comment by CiGit** [comment]
You can disable some languages with `disableLanguages`

**Comment by gyandeeps** [comment]
for example, do not prettiefy `package.json` for any project i work on (regardless whether the project says or not).
Because npm command doest its own formatting and their is constant fight.

This way i as a user can say i will ignore certain patterns for my own preference.

**Comment by CiGit** [comment]
Why can't you put it in a prettierignore file?

**Comment by gyandeeps** [comment]
then you have to start putting that inside every project you contribute to. what if the project doesnt have a prettierignore file (because they might not need it)?

**Comment by CiGit** [comment]
You can put it in any file and make you global setting point to it.

**Comment by CiGit** [comment]
you will have to set it back to `.prettierignore` in folder which have such a file.

**Comment by gyandeeps** [comment]
good idea. I just dont want to counter every point you make.
Since I use setting sync plugin, it sync my settings between different devices and if i get a new device its all synced. With this latest suggestions, i will have to keep in mind to always create a ignore file globally and then keep that in sync.

Just a hassle but not a show stopper. :smile:

**Comment by CiGit** [comment]
What about supporting ignore path to be an array ?

Example: ['/my/path/to/files/I/dont/want/prettier/to/touch/ever', '.prettierignore'] (defaults to '.prettierignore')

\cc @azz

**Comment by azz** [comment]
For package.json specifically, I'd rather do https://github.com/prettier/prettier/issues/3671.

**Comment by ntotten** [comment]
We are removing VS Code prettier settings in version 3.0. The supported way to ignore files is to use the `.prettierignore` file.

**Comment by quackingduck** [comment]
x
