### ISSUE TITLE
v1.3.1 advertises Prettier 1.12.1 but uses older version when using ESLint

### ISSUE THREAD

**Issue by ag-kylemh** [prettier/prettier-vscode#436]
I wanted to ensure that I'm seeing things correctly before I make a pull request. I love this extension!

I went down a rabbit hole when I opened https://github.com/prettier/prettier/issues/4410 😅 

The release notes for the latest version of Prettier VS Code state that `prettier@1.12.1` is in use. I think this may be the case for those who use prettier without eslint configuration, and I wanted to know if anybody was opposed to stating as such in the change log.

I understood the changelog as saying that the entire extension is always leveraging `prettier@1.12.1`, but if I have `prettier.eslintIntegration` activated, I use `prettier-eslint` instead of `prettier` leaving me on `prettier@1.7.0` https://github.com/prettier/prettier-eslint/blob/master/package.json#L25

Let me know if you're okay with me submitting a PR to clarify in the changelog language.

**Comment by ag-kylemh** [comment]
The real problem was me having `prettier` installed globally >.<

Sorry for the time waste.

**Comment by CiGit** [comment]
@ag-kylemh Well, you can still submit a PR to mention that. I wasn't even aware of ...
@RobinMalfait  Is prettier-eslint searching for prettier globally ?

**Comment by ag-kylemh** [comment]
Doubling down on my incorrect assertions. I didn't realize my project's prettier was on `1.11.1` explaining my specific issue.

**Comment by CiGit** [comment]
Thanks for your feedback :wink:

**Comment by RobinMalfait** [comment]
@CiGit I think it uses a bundled prettier. I have to check though...
