### ISSUE TITLE
Cannot find module 'core-js/library/fn/is-iterable

### ISSUE THREAD

**Issue by michaelsharpe** [prettier/prettier-vscode#437]
This just started happening a few days ago.  No idea what has changed on my system.  Don't remember what it was last working, but it was within the past week or so.  Screen shot of the error:

<img width="1376" alt="screen shot 2018-05-03 at 10 30 01 am" src="https://user-images.githubusercontent.com/2397603/39592900-17b853e6-4ebd-11e8-8f57-79515da8d651.png">

Whenever I go to format or save with prettier, I get this error message in the output.  No idea how to even start trying to track it down.  I have tried reinstalling the plugin, reloading VSCode, installing core-js locally and globally, all with no luck.

Any help would be appreciated.

Thanks!

**Comment by michaelsharpe** [comment]
Hmmmm, looks like it is only partly a prettier-vscode issue. I set the flag `prettier.eslintIntegration` to `false` and it starts working fine.  Not sure if anyone else can reproduce this however, but something to be aware of.

**Comment by CiGit** [comment]
Can you try to reinstall the extension and any eslint / prettier-eslint / prettier you have in your project. 

Who depends on core-js?
