### ISSUE TITLE
[Edited] Option to hide status bar item

### ISSUE THREAD

**Issue by yzhang-gh** [prettier/prettier-vscode#438]
I notice that there is a "Prettier" status bar item at the right bottom corner when editing Markdown file.
Clicking on it will open an empty output panel.
But when editing JS/CSS files, the status bar item disappears.
I am confused with what it is. Can I hide it?

**Comment by CiGit** [comment]
Hum, our toolbar lead may answer that question :smiley: 
@RobinMalfait

**Comment by CiGit** [comment]
you can't hide it but it shouldn't disappear

**Comment by neilsustc** [comment]
I just tested it again, it seems to work as designed.

**Comment by RobinMalfait** [comment]
@neilsustc can this issue be closed or do you need / want something else, like improvements?

**Comment by neilsustc** [comment]
Can we have an option to hide that status bar item?

**Comment by RobinMalfait** [comment]
@CiGit should we add an option to show/hide it?

**Comment by neilsustc** [comment]
Because the status bar is crowded enough. I'd like to have as less items as possible since I don't need it.

![image](https://user-images.githubusercontent.com/7588612/39692495-97e80274-5213-11e8-860f-3341400adec2.png)

**Comment by neilsustc** [comment]
And from the angle of UX, IMHO, a status bar item is something that provides actions/operations.
Of course it can be used as an indicator, but in my experience I have never seen other editors/IDEs having a formatter status bar indicator.
Just popping up an error message when formatter fails is sweet enough I think.

**Comment by RobinMalfait** [comment]
We do have a popup in a PR #434, maybe we can drop the statusbar all together?
But then again, every issue we have  we had to ask for the prettier versions and what not, and the statusbar is used for that.

Or we could create a command to `report` a problem which provides all the necessary information?

**Comment by CiGit** [comment]
That status bar item provides:
- a success / failure feedback
- an informative tooltip: version used (although not for eslint)
- An action to open the output panel.

I don't find it that useful as a user (**I** barely look at it)
It is _sometimes_ useful in issues.
> Or we could create a command to report a problem which provides all the necessary information?

This would be really useful I think. I would not call it `report`, it feels like it would open an issue directly. Maybe more something like `check` / `info` / `debug`.
It could also be a _loglevel_ option. I've no opinion right now...

I think we could do better with that new notification area. It's a little less invasive than the previous one.

**Comment by Lexicality** [comment]
To add to this - I've got way too many status bar indicators at the moment and they interfere with the Vim extensions command input. I'd appreciate being able to get rid of at least one.

**Comment by bn-l** [comment]
May to December and still not even an option to **toggle** this. Lots of nice discussion though.

**Comment by hediet** [comment]
I also use many custom commands in my statusbar and would love if prettier's status indicator could be hidden.

**Comment by richard-ling** [comment]
I'd like it to do something more useful when clicked -- show an option to toggle auto-formatting on/off.  Every other status bar indicator I have does something useful when clicked:
- JS - shows option to choose a different language
- LF - shows option to choose a different line ending
- Ln 37, Col 73 - shows option to type a line number to jump to
- Spaces: 2 - show options for spacing and tabs
- UTF-8: show option to choose encoding

I can probably work around this for now using the Formatting Toggle extension...

**Comment by lllopo** [comment]
Maybe would be nice to reduce it to an (informative) icon, so it doesn't clutter the statusbar so much.

**Comment by ntotten** [comment]
Status bar has been removed in version 3.0

**Comment by Nxt3** [comment]
but what if you liked the status bar icon? You could already hide status bar icons in VS Code so if you didn't want Prettier there, you'd just hide it.

**Comment by ntotten** [comment]
@Nxt3 what did you like about it? I think the main thing that it did was help to ensure that prettier was being used as a formatter on that file, but since vscode introduced the ability to pick a formatter that doesn't seem necessary. 

I'm willing to add it back, but I'd like to understand why it is useful.

**Comment by Nxt3** [comment]
For me, it was a quick way to make sure that formatting was working on the current document. I have it setup to format on save, and sometimes I'd save but the document wouldn't format; I could tell this because of the status bar icon. It's also just a quick way to tell if prettier is capable of formatting your current document without having to dig into settings.

**Comment by sleepwalky** [comment]
I have the same use case as @Nxt3 described. Now I have to open prettier output tab in vscode to verify if formatting was applied correctly

**Comment by thelovesmith** [comment]
I agree with @Nxt3 and @sleepwalky Having the status bar icon def provided us an easy and quick way to know if its being used successfully especially when you're editing multiple projects at once. Especially if you don't want to dig into each project's settings. It was pretty comforting seeing the icon down there. Just my honest opinion.

**Comment by ntotten** [comment]
The status bar is back again in version 3.6.0, please update. :)
