### ISSUE TITLE
vs plugin 1.3.1 not working suddenly

### ISSUE THREAD

**Issue by catalsdevelop** [prettier/prettier-vscode#439]
I make extension.autoUpdate:true, so I don't know when it happened.
`.prettierrc` not working, config fields in `workspace settings` or `user settings` all down, but other config fields in `user settings` worked fine, so I think prettier-vscode didn't startup.

vs code: 1.23.0
prettier-vscode: 1.3.1

I have tried:
1.  uninstall/reinstall prettier-vscode
2. uninstall prettier-vscode, quit vscode, del `~/.vscode/extensions/esbenp.prettier-vscode-1.3.1`, start vscode, install prettier-vscode, reload
3. disable some other plugin may infect prettier-vscode.

any tips? I can not work now, any save will format js file to a strange style  like follows

```code
const Web3 = require('web3')
  const fs = require('fs')

    const abi = JSON.parse(fs.readFileSync('./abi.json'))
      const abi1 = JSON.parse(fs.readFileSync('./abi.1.json'))
        const _ = require('lodash')

          process.on('unhandledRejection', error => {
            console.error(`unhandledRejection ${error.message}, ${error.stack}`)
          })
          // var web3 = new Web3(new
          // Web3.providers.WebsocketProvider('ws://localhost:28546')) const web3 = new
          // Web3('http://localhost:28545')
          const web3 = new Web3('http://localhost:28545')
            // const web3 = new Web3('https://mainnet.infura.io/OohIOgg40bERWpGmYGZp') const
            // web3 = new Web3('https://api.myetherapi.com/eth')
            const BN = web3.utils.BN

              const abiDecoder = require('abi-decoder')
                abiDecoder.addABI(abi)
                abiDecoder.addABI(abi1)

                const InputDataDecoder = require('ethereum-input-data-decoder')
                  const decoder = new InputDataDecoder(abi)

                    const getHashByBlockNumber = async number => {
                        const block = await web3
                          .eth
                          .getBlock(number)
                        return {hash: block.hash, transactions: block.transactions}
                      }
                      const unknown = [],
                        errorTx = []
```

**Comment by DaniyarJakupov** [comment]
I have similar issues. Prettier started to format stuff completely off. Here is JSX for example:

<img width="1072" alt="screen shot 2018-05-04 at 09 12 13" src="https://user-images.githubusercontent.com/17025967/39616398-819d7412-4f7b-11e8-9bc1-32a0417ebadb.png">

I tried to reinstall, then completely removed folder extension and installed version 1.3.0, still have this problem

**Comment by DaniyarJakupov** [comment]
> Could you try to disable/remove other extension ?

Removed eslint extension, didn't help. Everything else shouldn't effect code formatting (syntax highlighting / code snippets / etc.)

>Do you have this behavior only "on Save" or also when calling "format document". In the later case, it may be an other formatter extension getting precedence over prettier.

Both

**Comment by pgmanutd** [comment]
This is happening after upgrading vscode to 1.23.0

**Comment by sebastiendavid** [comment]
I deactivated Beautify plugin (https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) and now it works again.

**Comment by catalsdevelop** [comment]
thx, @sebastiendavid and @CiGit.  After a half day dig, I found the extension `react-beautify` https://marketplace.visualstudio.com/items?itemName=taichi.react-beautify is the bad boy. don't know when to installed and enabled. Disable it and prettier come back.

**Comment by sergiu11** [comment]
I have same problem. I can't make Beautify 1.3.2 to work. I am new in this and I have know idea what to modify.

 Can someone guide me?

Thanks

**Comment by AhmedElsir** [comment]
@catalsdevelop this actually work, but in my case I installed rc-beautify
 extension and disable it.

**Comment by PrimarchAlpharius** [comment]
Suddenly stopped working for me in version 1.8.1 and I don't use any other related plugins. Works dandy when reverted to 1.7.3.
