### ISSUE TITLE
[vsCode 1.23.0] Prettier seems to ignore stylelint config on save

### ISSUE THREAD

**Issue by ekfuhrmann** [prettier/prettier-vscode#440]
I'm not entirely sure if this is a prettier or stylelint issue, but it's just popped up with the most recent update of vsCode (1.23.0)

Prior to 1.23.0, Prettier would execute the linting rules set forth within my `.stylelintrc.json` file when I had `"prettier.stylelintIntegration": true,`. Now it seems to be disregarding the lint rules and just formatting based on default rules.

**Comment by pcate-fls** [comment]
I'm have the same issue with the latest update of VSCode (1.23.0)

**Comment by natsukagami** [comment]
[vsCode 1.23.0] I experience a weirder case when the extension switching back and forth the default configuration and mine (eslint and tslint) on every invoke.

**Comment by CiGit** [comment]
Do you have any output in prettier's output panel / dev console?

**Comment by ekfuhrmann** [comment]
Nope, I'm getting absolutely no messages in the output panel. 

The simplest way to probably recreate the issue is to create a new project with a stylelint config that has the following rule:
```json
"no-missing-end-of-source-newline" : true
```

Then if you set prettier to use the stylelint rules, and create a simple sass file such as the following:
```scss
    a { color: pink; }
    \n
/** ↑
 * This newline */
```

On save it will remove that new line at the end of the file regardless of the lint rule enforcing it.

**Comment by CiGit** [comment]
We have report about other formatter taking precedence over prettier since VSCode 1.23.0
You may have the same issue with an other formatter installed.
When you format, do you have a :heavy_check_mark: next to `prettier` bottom right of VSCode? (this means prettier formatted successfully last time)

**Comment by ekfuhrmann** [comment]
Nope, I'm not seeing any ✔️on save. Seems like the other formatter taking priority on save is what's going on here.

Let me know if you need me to try anything else for you.

**Comment by ekfuhrmann** [comment]
I found the culprit, [VS Code Beautify](https://github.com/HookyQR/VSCodeBeautify).

It seems that something with 1.23.0 gives it precedent over Prettier since this was never an issue prior to the update. I don't really use this extension much anymore since I now use Prettier, so there is no issue for me to remove it, but with it being as popular as it is, there may well be other issues like this cropping up as people update to 1.23.0.

If you have no further questions for me, please feel free to close. Thanks for the help!

**Comment by guilhermedecampo** [comment]
For me was the [React Beautify](https://marketplace.visualstudio.com/items?itemName=taichi.react-beautify)

**Comment by CiGit** [comment]
Same as #439. Closing.
Thanks for your debugging
> Beautify is not Prettier

**Comment by nerdmax** [comment]
For me it was the React Beautify as well.
There is a open ticket in CodeBeautify ([(vsCode 1.23.0) Beautify formatter on save takes precedent over Prettier](https://github.com/HookyQR/VSCodeBeautify/issues/230))

Thanks to @jamesplease . He provides a solution:
"beautify.ignore": "**/*"
