### ISSUE TITLE
Prettier no longer works on VSCode 1.23.0

### ISSUE THREAD

**Issue by younanjo** [prettier/prettier-vscode#441]
Hi guys,

After i updated to the latest VSCode `v1.23.0` when formatting document it doesn't seem to be prettier formatted code, especially the function arguments and flow types. It behaves differently to how prettier.io formats the same function. 

![vscode-prettier](https://user-images.githubusercontent.com/957874/39658837-018722b6-505f-11e8-8a00-9d5df0231582.gif)

My user setting.json:

```
{
	"prettier.singleQuote": true,
	"prettier.trailingComma": "es5",
    "prettier.proseWrap": true,
}
```

I tried uninstalling Prettier extension and reinstalling it but it makes no difference. Anyone else having this issue?

**Comment by CiGit** [comment]
Prettier didn't format your code here. This is certainly an other extension formatter.
See #440 and #439
