### ISSUE TITLE
Prettier format, How can I get rid of the semicolon after the arrow function?

### ISSUE THREAD

**Issue by Anberm** [prettier/prettier-vscode#445]
Prettier format, How can I get rid of the semicolon after the arrow function? e.g.:
prettier format submitForm = ($event: any) => {} then submitForm = ($event: any) => {};,but I don't need a semicolon.

**Comment by RobinMalfait** [comment]
Have you tried this option?

https://github.com/prettier/prettier-vscode#prettiersemi-default-true

**Comment by Anberm** [comment]
thank you

**Comment by RobinMalfait** [comment]
I think that an arrow function is just an expression. So if you want to get rid of the semi colon there you would have to use an eslint rule for that.

**Comment by Anberm** [comment]
thanks
