### ISSUE TITLE
destructuring/object literals are always expanded to multiline.

### ISSUE THREAD

**Issue by finalclass** [prettier/prettier-vscode#446]
The prettier vscode plugin is amazing. However I cannot use it for the whole file because it always expands objects/destructuring to multiline:

Before:

```js
const { a } = {};
```

After:
```
const {
    a
} = {};
```

Before:

```js
const a = { a: 5 };
```

After: 

```js
const a = {
    a: 5
};
```

This is not a problem with prettier but most probably with the plugin itself because as suggested by @j-f1 it does work well in the playground: https://github.com/prettier/prettier/issues/2550#issuecomment-387359141

However in vscode it does not:

![ezgif-1-d9de541b60](https://user-images.githubusercontent.com/1343930/39757768-25cc84b0-52ce-11e8-94a8-3b2762f4af98.gif)

**Comment by CiGit** [comment]
This is most certainly an other formater running. When prettier runs, bottom right _prettier_ ends in prettier: :white_check_mark: or prettier: :x: (success or failure).

See #439

**Comment by finalclass** [comment]
Indeed some other formatter https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify
was running. Sorry for not checking it first.

**Comment by amandakoster** [comment]
Hello, I do not have beautify snippet running and am still encountering this issue. It looks like there is a PR out (15 days ago) for the prettier 'object-property-newline.js'. Anyone know more about this?
https://github.com/eslint/eslint/pull/9563 (edited)
