### ISSUE TITLE
Intermittent small printWidth?

### ISSUE THREAD

**Issue by wmertens** [prettier/prettier-vscode#451]
I seem to have something similar to #300 but I don't use Eslint integration.

What happens is that sometimes, formatting results in breaking open all single-line objects, as if the printWidth is suddenly much lower.

It used to be that I could just undo the formatting, format a few different files until it stopped doing it, and then do the formatting correctly, but lately it seems that only reloading the window will get it out of this state.

This is my user config:
```
	"prettier.singleQuote": true,
	"prettier.trailingComma": "es5",
	"prettier.bracketSpacing": false,
	"prettier.printWidth": 80,
	"prettier.semi": false,
	"prettier.useTabs": true,
```

I have no idea why it does that, prettier never does it from the command line. It used to do it just after loading a window, but now it seems to be the reverse.

**Comment by wmertens** [comment]
Hmm - to test, I disabled the prettier plugin, and "format document" still worked. I then disabled the built-in js and json formatters, and "format document" still worked. I then disabled the `beautify` plugin which I installed for HTML, and finally it errorred saying there's no formatter for javascript.

I think somehow prettier was no longer the primary formatter, which would explain a lot.

Perhaps this situation can be detected by the plugin somehow? If not, this can probably be closed; #300 may be a similar problem.

**Comment by CiGit** [comment]
I've currently found no (usable) solution to detect multiple formatter.
This is something internal to VSCode.

**Comment by IlyaSemenov** [comment]
I was getting the same problem in Vue single file components. It turned out that Vetur's default HTML formatter is not prettier but prettyhtml, which resulted in it **sometimes** taking precedence over prettier (in like 20% of saves).

<img width="369" alt="Screenshot 2019-08-29 at 13 27 47" src="https://user-images.githubusercontent.com/128121/63915722-ec33ce00-ca60-11e9-86bc-ffbdb543444e.png">
