### ISSUE TITLE
Breaking up HTML tags in JSX upon save

### ISSUE THREAD

**Issue by CosmonautJones** [prettier/prettier-vscode#452]
Hey guys, I've been using prettier for about 6 months now and never had an issue. but I recently updated VSCode and I ran into this problem today with it breaking out my HTML tags in my JSX and spacing it all wildly. 
Example follows:
**Before save:**
```
return (
    <div className="input-group mb-3">
      <div className="input-group-prepend">
        <span className="input-group-text">
          <i className={icon} />
        </span>
    </div>
    <input
      className={classnames("form-control form-control-lg", {
        "is-invalid": error
      })}
      placeholder={placeholder}
      name={name}
      value={value}
      onChange={onChange}
    />
      {error && <div className="invalid-feedback">{error}</div>}
    </div>
  );
}; 
```

**After save**
``` 
return ( <
      div className = "input-group mb-3" >
      <
      div className = "input-group-prepend" >
      <
      span className = "input-group-text" >
      <
      i className = {
        icon
      }
      /> <
      /span> <
      /div> <
      input className = {
        classnames("form-control form-control-lg", {
          "is-invalid": error
        })
      }
      placeholder = {
        placeholder
      }
      name = {
        name
      }
      value = {
        value
      }
      onChange = {
        onChange
      }
      /> {
        error && < div className = "invalid-feedback" > {
            error
          } < /div>} <
          /div>
      );
    }; 
```

I can provide additional info if needed. Such as my settings, etc.

UPDATE 6/4/18: Resolved by disabling Beautify, which was causing issues with Prettier.

**Comment by CosmonautJones** [comment]
Images just for completeness sake
![beforesave](https://user-images.githubusercontent.com/31292511/39882485-919ef566-5449-11e8-8fe0-7391e9906f0f.PNG)
![aftersave](https://user-images.githubusercontent.com/31292511/39882484-918e4f90-5449-11e8-9026-81bb4162d371.PNG)

**Comment by sonbuiGFD** [comment]
I have the same issue after update VScode today.

**Comment by jtbandes** [comment]
I'm having a similar problem but sometimes it seems to format the document correctly. If I Format Document repeatedly, it seems to alternate between correctly and incorrectly formatted, as if it's sometimes using prettier + its config from my repo, and sometimes using a different formatter or prettier with the wrong configuration.

**Comment by jtbandes** [comment]
I narrowed this down to the [clang-format extension](https://github.com/xaverh/vscode-clang-format-provider). Adding this to my settings fixes the problem:
```
    "clang-format.language.javascript.enable": false
```

**Comment by Greenie10** [comment]
I was experiencing the same problem, even though I didn't have the clang-format extension installed. Installed it, and added the false setting suggested by @jtbandes above, and all is now well.  Seems a bit mad though.

**Comment by jtbandes** [comment]
I'm not sure but I just updated to 1.23.1 and I think the issue has gone away.

**Comment by nielskrijger** [comment]
Having had the same issue yesterday, it does appears to work better with 1.23.1.

One issue remains though;

```
import objectMapper, { getKeyValue } from 'object-mapper';
```

is transformed into:

```
import objectMapper, {
  getKeyValue
} from 'object-mapper';
```

Where before it would keep the oneliner.

**Comment by jlibman** [comment]
Updating to 1.23.1 did not work for me.

**Comment by jtbandes** [comment]
Yeah, I think I spoke too soon — still having issues in some cases, but with clang-format installed and `"clang-format.language.javascript.enable": false` it hasn't been a problem.

I kinda suspect this is a VSCode issue (not this extension's fault). I would encourage someone to file an issue at https://github.com/Microsoft/vscode/issues  if you can come up with exact steps to reproduce the problem, and link back here for context. (I'm not at the right computer to do this at the moment)

**Comment by sonbuiGFD** [comment]
@jtbandes Thank you so much 👍 
FYI:
it conflicts with beautify so we add:
"beautify.ignore": [
        "**/*.js",
        "**/*.jsx"
    ]

and it fixed =))

**Comment by DevAbas** [comment]
After ignore beautify everything went ok. 
`"beautify.ignore": [
        "**/*.js",
        "**/*.jsx"
    ]`
This code fix the problem.

**Comment by beanditis** [comment]
mandem works like a charm 👍 
"beautify.ignore": [ "**/*.js", "**/*.jsx" ]

**Comment by shyamsha** [comment]
thanks man

**Comment by kajangid** [comment]
thank you man............ @lipis

**Comment by lipis** [comment]
@kajangid you are welcome, but what have I done to deserve the "thank you"?

**Comment by AMINEDGE** [comment]
I've suddenly encountered this weird problem, and the thing is that I did nothing with configs and extensions between the last time that it was okay and now, could it be a vscode bug? any suggestions

**Comment by Aarbel** [comment]
me too

**Comment by yukriss** [comment]
Thanks you I had the same problem. I disabled Beautify extension and all works flawlessly

**Comment by yukriss** [comment]
beautify seems to be the culprit disabled it =>reloaded and everything works flawlessly.
Thank you.

**Comment by beevekmgr** [comment]
> Oh, thank the heavens, the linked issue at jsbeautify solved it for me. Disabled the Beautify plugin on my vscode and all is well.

JUst uninstall beautify extension still not work on mine

**Comment by Aarbel** [comment]
reload vs code

**Comment by victorbf** [comment]
I uninstall beautifying and it works!

**Comment by Rodrigoandfamily** [comment]
it worked thanks get back to coding

**Comment by soriasayer** [comment]
Put the following code both in .prettierrc and in settings.json file.

"beautify.ignore": [ "**/*.js", "**/*.jsx" ]

it works for me.

**Comment by soriasayer** [comment]
Put the following code in settings.json and as well as in .prettierrc files.
"beautify.ignore": [ "/*.js", "/*.jsx" ]
it works for me.

**Comment by Mecca757** [comment]
> Resolved by disabling Beautify, which was causing issues with Prettier.

What if you don't have beautify installed?

**Comment by rizwanalam836** [comment]
Thanks man,,its just worked for me after uninstalling Beautify and reloaded again
