### ISSUE TITLE
Prettier is not formatting javascript file correctly.

### ISSUE THREAD

**Issue by chanlito** [prettier/prettier-vscode#453]
So prettier is not formatting javascript file correctly from time to time.

I have to manually `reload the editor` or change format to `typescript` then run format with prettier again and it works.

This behavior happened after I updated vscode to the latest version `1.23.1`.

**Comment by nfantone** [comment]
Same here. Sometimes, it just dies and _Format Document_ does absolutely nothing. Reloading the editor makes it work again for a brief period of time.

**Comment by methodbox** [comment]
I'm not sure if this is Prettier or TypeScript doing this, but I have this same issue when JS files are generated on compile. The tab spacing is 4 instead of 2; Prettier is formatting the TS files but not the generated JS files, unless I manually save them again.

Any suggestions?

**Comment by CiGit** [comment]
@methodbox can you open another issue. I don't get exactly what you are asking for tho.

I'll close that one due to vscode 1.33 which makes formatter work a bit differently.

**Comment by methodbox** [comment]
Will do.
