### ISSUE TITLE
Single quotes removed in JS object

### ISSUE THREAD

**Issue by kyalha** [prettier/prettier-vscode#455]
Hi everyone,

I got a problem here using Prettier with Ubuntu.
The single quotes are being totally removed within the objects in my file (all words containing no hyphen)
i.e:
let colors = {
  'transparent': 'transparent',
  'black': '#22292f',
  'grey-darkest': '#3d4852',
  'grey-darker': '#606f7b',
  'grey-dark': '#8795a1',
  'grey': '#b8c2cc',
  'grey-light': '#dae1e7',
  'grey-lighter': '#f1f5f8',
  'grey-lightest': '#f8fafc',
  'white': '#ffffff'
}

would become:
let colors = {
  transparent: 'transparent',
  black: '#22292f',
  'grey-darkest': '#3d4852',
  'grey-darker': '#606f7b',
  'grey-dark': '#8795a1',
  grey: '#b8c2cc',
  'grey-light': '#dae1e7',
  'grey-lighter': '#f1f5f8',
  'grey-lightest': '#f8fafc',
  white: '#ffffff'
}

Would anyone has an idea about why I have this?
Thanks a lot!

**Comment by RobinMalfait** [comment]
That is because the keys without special characters like spaces and dashes don't require quotes around them so prettier removes them.

If, however you want that it is consistent you can look into setting up eslint with this plugin https://eslint.org/docs/rules/quote-props
