### ISSUE TITLE
Wrong formatting in JSX with renderProps

### ISSUE THREAD

**Issue by tobiastimm** [prettier/prettier-vscode#458]
When I add a 4th argument to the apollo arrow function prettier is pretty confused ^^
![image](https://user-images.githubusercontent.com/10043789/40204954-8cb58ce0-5a2a-11e8-90e7-eff11bbd6fd1.png)

I don't have a .prettierrc in my repo only this .eslintrc

```
{
  "parser": "babel-eslint",
  "plugins": ["flowtype", "babel"],
  "extends": ["airbnb", "plugin:flowtype/recommended"],
  "rules": {
    "react/jsx-filename-extension": ["error", {
      "extensions": [".js", ".jsx"]
    }]
  },
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    }
  }
}
```
In my settings.json is only `"prettier.eslintIntegration": true,`

I don't have js-beautify or beautify installed

**Comment by CiGit** [comment]
Does it happen with `eslintIntegration: false`? 
Can you paste your code, It's hard to copy an image. Thanks
