### ISSUE TITLE
add a command: create .prettierrc file

### ISSUE THREAD

**Issue by capaj** [prettier/prettier-vscode#459]
I often add this to my projects, so it would save me a few keystrokes if I had this as a command.

ideally you can preset how the default template will look like it in the config

if it already exists, it would just show a notification.

**Comment by azz** [comment]
I usually just do 

```
cp ../some-other-project/.prettierrc .
```

**Comment by CiGit** [comment]
I don't think it's worth. We would have to be able to create every different 'prettier config' files, not only `.prettierrc`

I don't think this is an action that occurs frequently. If it is, it can be in your clipboard :-)
Also, the content may depend on prettier's version (settings change).

**Comment by capaj** [comment]
> Also, the content may depend on prettier's version (settings change).

That's why by default it would just create an empty file.

> I don't think this is an action that occurs frequently. If it is, it can be in your clipboard :-)

consider users like @sindresorhus- he probably creates couple of new repos each day. Granted, he does not use prettier-he uses xo for code formatting, but hey-such users exist that need to run this quite often.

Clipboard doesn't make the action faster because I have to first find a source where I want to copy from and actually copy it.
Feel free to close this if you are against having one extra command, I'll create a separate code extension with just that single action in worst case scenario.

**Comment by azz** [comment]
I'd recommend using yeoman for that kind of thing.

I have a generator I wrote exactly for this kind of purpose, but it creates more than just `.prettierrc`. 

https://github.com/azz/generator-npm-package

**Comment by mubaidr** [comment]
I think this is useful, just as `vscode-eslint` expose a command to create a config file in the project.

Can we add a command which creates a config file based on the current editor settings for a starter template.

**Comment by muuvmuuv** [comment]
It would really reduce time creating a new project! As @mubaidr wrote, it would be a template so modifying would still be possible but it would reduce searching for a prettier config elsewhere.

**Comment by capaj** [comment]
in the mean time I've created a CLI utility just for this exact purpose: https://github.com/capaj/be-pretty

**Comment by azz** [comment]
Also we just merged a PR to core Prettier to support [shared configurations](https://github.com/prettier/prettier/pull/5963).

Probably no need to add it to the plugin.
