### ISSUE TITLE
Format is not working well when editor is word-wrapping

### ISSUE THREAD

**Issue by se** [prettier/prettier-vscode#461]
Screenshot;
![image](https://user-images.githubusercontent.com/491844/40284823-28ac29c8-5c9d-11e8-851c-c1d61d84070d.png)

Is it enough to explain?

**Comment by CiGit** [comment]
I don't see what you mean by word-wrapping here.
Prettier added two line breaks in your string interpolation `ctx.from.last_name`. This doesn't change the AST.

**Comment by CiGit** [comment]
Closing as this is expected.
