### ISSUE TITLE
wrong format on windows

### ISSUE THREAD

**Issue by littlee** [prettier/prettier-vscode#465]
```js
this.imgData = [
  {
    type: 'textList',
    textList: [
      {
        text: '我是第',
        line: 1,
        fontSize: '20px'
      }
    ],
    fillColor: '#fff'
  },
  {
    fontSize: '26px'
  },
  {
    position: [0, 0, 640, 1008]
  },
  {
    position: [150, 150, 0, 0]
  },
  {
    position: [0, 0, 150, 150]
  }
];
```

will be formatted to
```js
this.imgData = [{
    type: 'textList',
    textList: [
      {
        text: '我是第',
        line: 1,
        fontSize: '20px'
      }
    ],
    fillColor: '#fff'
  },
  {
    fontSize: '26px'
  },
  {
    position: [0, 0, 640, 1008]
  },
  {
    position: [150, 150, 0, 0]
  },
  {
    position: [0, 0, 150, 150]
  }
];
```

and this only happens on windows, but not mac, in latest vscode

**Comment by CiGit** [comment]
Is eslintIntegration enabled ? It can be an eslint config laying around somewhere.

**Comment by littlee** [comment]
@CiGit  "prettier.eslintIntegration" is set to false, and I also found that it only happens on Windows 10, but not on Windows 7.

I don't think eslint config make a difference here, because after prettier format, the code doesn't pass eslint.

<img width="345" alt="wx20180602-003411 2x" src="https://user-images.githubusercontent.com/7534668/40852555-5ff0952c-65fd-11e8-887e-101c8abbfd90.png">

**Comment by CiGit** [comment]
Does it also happen if you remove other extensions ?
Maybe a prettier version installed in your project.

**Comment by littlee** [comment]
@CiGit I still can not figure out what's wrong with my editor 😞 

and I tried install `prettier` with npm in my project, and use `npx` to format my code, and it outputs the right formatted code.

So I think it's a editor issue.

**Comment by mubaidr** [comment]
You need to add `prettier` to `eslint` config file, this will make sure `eslint` ignore rules related to prettier formatting. i.e. 
```js
extends: ['prettier'],
```

and make sure to install this package in your project root (where `eslint` is installed): 
```sh
npm install eslint-config-prettier
```

**Comment by littlee** [comment]
@mubaidr I've solved my problem.

After uninstall the extension called `Beautify`, prettier works normally again.
