### ISSUE TITLE
ES Lint configuration Overridden

### ISSUE THREAD

**Issue by jcald1** [prettier/prettier-vscode#467]
I'm using Visual Studio Code 1.23.1 with ESLint 1.4.10. and Pretter-Code 1.3.1. I have the prettier.eslintIntegration: true  and "editor.formatOnSave": true options set in my VSC configuration.

In my ES Lint configuration I'm inheriting the airbnb configuration.  When saving/formatting, prettier is changing the formatting in such a way that is causes ES Lint to error out.  For example, it changes single quotes to double quotes.  So I've had to override specific prettier configurations so it doesn't override the ES Lint settings.

ES Lint configuration

```js
{
  "extends": "airbnb",
  "rules": {
    "no-console": 0,
    "semi": 0,
    "consistent-return": "warn",
    "no-use-before-define": ["error", { "variables": false }]
  }
}
```

(**NOTE:** Edited by @RobinMalfait, used codeblocks for eslint config example)

**Comment by RobinMalfait** [comment]
What is your question exactly?

- Did you install your dependencies and airbnb plugin locally so that prettier can find it?
- Did you restart vscode after doing the step above?
- Do you have other formatters in your vscode?

**Comment by jcald1** [comment]
@RobinMalfait, it looks like my global installation was the problem.  I uninstalled eslint globally and reinstalled it locally with -D.
