### ISSUE TITLE
Won't let me Disable or Reinstall Prettier plugin.

### ISSUE THREAD

**Issue by sterlingssmith** [prettier/prettier-vscode#469]
- Extension Name: prettier-vscode
- Extension Version: 1.0.1
- OS Version: Darwin x64 17.5.0
- VSCode version: 1.23.1

 We have written the needed data into your clipboard. Please paste:

**Comment by mubaidr** [comment]
This plugin might be dependency of some other extension pack which prevents its removal/disable.

**Comment by RobinMalfait** [comment]
And if the package is not part of an extension pack, try the following:

1. Close vscode
2. Go to `~/.vscode/extensions`
3. Find the folder that starts with `esbenp.prettier-vscode-` (It has a version number on the end, but that is not important)
4. Remove that folder completely
5. Open vscode and the extension should be gone. Then you can either reinstall it or keep it as is.

**Comment by CiGit** [comment]
Stalled closing
