### ISSUE TITLE
Upgrade perttier new version v1.13.2

### ISSUE THREAD

**Issue by kpman** [prettier/prettier-vscode#470]
The latest version of prettier is `v1.13.2`.

But when I fork this repo and run `npm install prettier@1.13.2` on my local machine.
The npm will update a lot of version in `package-lock.json`.

My npm version is `6.0.1`.
My node version is `10.1.0`

Do you have any suggestion about upgrade the prettier version?
Thanks.

**Comment by valerii-cognite** [comment]
That would be nice to see the plugin upgrade to a newer prettier version!

**Comment by David-Else** [comment]
It is 1.13.3 now!

https://github.com/prettier/prettier/blob/master/CHANGELOG.md

Really looking forward to the new version :)

**Comment by CiGit** [comment]
Seems it also will be 1.13.4 soon :-)

**Comment by mubaidr** [comment]
https://github.com/prettier/prettier-vscode/pull/473

**Comment by CiGit** [comment]
published
