### ISSUE TITLE
Prettier resolution broken?

### ISSUE THREAD

**Issue by lehni** [prettier/prettier-vscode#471]
I am aware that as of #39, prettier-vscode should resolve to the locally installed version of prettier, but in my configuration that does not seem to be the case. I have prettier `1.13.2` installed in my project, with the new rules for _parentheses in math expressions_, but when I use the `editor.formatOnSave` feature of VSCode, these get replaced with the way prettier was handling them in `1.12.1` and below. It looks like prettier-vscode is using the internal prettier module, despite #39? And due to #470, prettier-vscode's prettier is still at `1.12.1`.

I was trying to find some debugging information to provide better information for this issue, but wasn't able to find any. What can I do to understand / log what's going on with my configuration?

**Comment by CiGit** [comment]
Did you restart VSCode after you update prettier in your project?
You can debug it here: https://github.com/prettier/prettier-vscode/blob/master/src/PrettierEditProvider.ts#L93

**Comment by lehni** [comment]
Yes I restarted multiple times...

**Comment by CiGit** [comment]
Is that enought to start ? https://github.com/prettier/prettier-vscode#contribute

**Comment by lehni** [comment]
Ok, I think I managed to run this locally and debug the extension. But when I set a break point at the line you've referenced, I never seem to hit that breakpoint. Just to be sure I've added a `debugger` statement, and also a `console.log()`, and none of them seem to have any effect. I doubt that this code gets ever executed, yet my file gets formatted with the wrong version of prettier.

**Comment by lehni** [comment]
I've managed to get the code execution to break in the constructor of `PrettierEditProvider` and also log from there, so that's not it... I've added some logging statements to `requireLocalPkg()` but that never gets executed. Super strange.

**Comment by kaisermann** [comment]
In my case, for the first *opened* file, vscode uses prettier with the correct config, although, after opening any other file, the "format document" starts to format WITHOUT prettier

**Comment by CiGit** [comment]
If the formatter is not called, try disabling other extensions :-)

**Comment by lehni** [comment]
I did :) And then I ran out of time, also to report back here. What I found was that it was Vetur that was applying the formatting in Vue.js files, also through Prettier in my set-up, but obviously not through the `prettier-vscode` plugin. I mean to look into this further but haven't found the time yet. This can probably be closed now.
