### ISSUE TITLE
Having Issue With Liquid Tags

### ISSUE THREAD

**Issue by ellemaker** [prettier/prettier-vscode#472]
Before 
{module_webapps render="collection" sortType="weight" id="22331" filter="all" collection="staffCollection" template=""}
{% for item in staffCollection.items %}

{% endfor %}

After
{module_webapps render="collection" sortType="weight" id="22331" filter="all" collection="staffCollection" template=""} {%
    for item in staffCollection.items %} {% endfor %}

**Comment by RobinMalfait** [comment]
What file format is this? I don't think we support that.
Try disabling prettier and see if you still have this behaviour.

You probably have another formatter installed.
