### ISSUE TITLE
QUESTION: what difference between another prettier>

### ISSUE THREAD

**Issue by cybermerlin** [prettier/prettier-vscode#476]
e.g.
https://github.com/remimarsal/prettier-now-vscode

**Comment by mubaidr** [comment]
This:

prettier-now-vscode is a: 
> VS Code package to format your Javascript using Prettier Miscellaneous. Based on Esben Petersen's extension and Bastian Kistner's extension. Prettier Miscellaneous is a fork of Prettier and allows more customization of the output.
This extension is a wrapper around Prettier Miscellaneous, please report issues regarding the output on Prettier Now or Prettier Miscellaneous.

**Comment by RobinMalfait** [comment]
Technically we are the OG extension and the others are mostly forks / clones (We are also in the https://github.com/prettier namespace on GitHub).
Feel free to use whatever extension you want.

If you have any questions or issues, make sure to open issue on the correct extension.
