### ISSUE TITLE
[BUG] Prettier is not disabled for vue

### ISSUE THREAD

**Issue by mubaidr** [prettier/prettier-vscode#478]
By default prettier is disabled for `vue` language. But this setting is not respected by prettier. Prettier formatter is always on for `.vue` files unless I toggle formatter on/off. 

No local or global installation of prettier package. 

Windows 10 x64

**Comment by CiGit** [comment]
by default "vue" is in `prettier.disableLanguages`.
I don't get what you mean. Your vue file can be formatted by Vetur extension

**Comment by mubaidr** [comment]
Although, vue is disabled for prettier, but prettier still tries to format the vue document. (Unless I disable formating in vscode completely)

**Comment by CiGit** [comment]
Disable Vetur ?

**Comment by mubaidr** [comment]
Off-course this: `"vetur.format.defaultFormatter.html": "js-beautify-html"` is the problem!
