### ISSUE TITLE
TypeScript - incorrect semicolon added to method with ECMAScript 6 arrow syntax 

### ISSUE THREAD

**Issue by nhustak** [prettier/prettier-vscode#479]
Example of method declaration in a class.  
 
` receiveBroadcast = (message: string): void => {
         this.broadcastMessage = message;
    };`

Prettier added the semicolon at the end of the method.  I've confirmed this by flipping the semi setting to false and observing the result.

**Comment by CiGit** [comment]
Why is that incorrect? This is an assignment expression.

**Comment by nhustak** [comment]
Valid point.   It works but tslint doesn't like it.   Maybe it's a tslint issue.

**Comment by nhustak** [comment]
There are lots of thing that are technically correct (i.e. work) but aren't best practices.   So I guess the question is, what IS the correct practice here?

**Comment by CiGit** [comment]
You have to put those semi in a case like:
```
class {
	b:()=>1;
	[computedMethodName](){}
}
```
I think it's not the case with a block statement tho.
