### ISSUE TITLE
Disable error messages.

### ISSUE THREAD

**Issue by noobiept** [prettier/prettier-vscode#481]
Is there a way to disable the messages that appear at the bottom-right? I find it extremely distracting, since they appear while I'm still writing the code and don't go away either.

**Comment by CiGit** [comment]
It appears only when you format something and there is an error. You can press <kbd>ESC</kbd> to hide it.

**Comment by noobiept** [comment]
Any way to disable them?

**Comment by RonanQuigley** [comment]
Just to second this: the inline-error on its own is obvious enough for me. Having pop-ups as well gets really annoying.

Using escape works, but it should just have an option to turn it off. . Your only option seems to be to disable:

``` 
"[javascript]": {
        "editor.formatOnSave": false
    },
```

though that obviously means format on save is gone. Is this a new feature as I can't recall having this as a problem before?

**Comment by CiGit** [comment]
Well, thinking about it.
This is really meant to attract user's attention: Something went wrong.
In most cases, these are syntax errors. Seems redundant with a linter. Some users seem happy with it.

In my case, I don't need a notification for a syntax error. But I would need it for any other uncommon error this extension may produce (reading fs mostly). But as I said, those notification seem to please some users.

**Comment by noobiept** [comment]
There's already plenty of clues about the issue being presented on the editor, to me an extra message is redundant, but again, thats my opinion, other people might prefer to have the extra message. 

Thats solvable by adding a setting, this way people can make it work the best for them.

**Comment by RonanQuigley** [comment]
Yep @noobiept sums it up. Furthermore, if like me, you use a lot of unit testing. you already get continuous feedback for this sort of thing. I can see its use, but this is just bloat in my setup.

**Comment by starquake** [comment]
Agree with @noobiept. It distracts from all the other things that are also errors.

**Comment by dnutels** [comment]
This used to work though... (as in, before the latest updates on VSCode Insiders) there is a status-bar with corresponding icon for a reason.

**Comment by breathe** [comment]
I resoundingly agree with those who don't want the notifications -- especially the notifications don't appear when the syntax errors are corrected ...

These popups are horribly annoying.

**Comment by kristian-puccio** [comment]
Another thing to note is that if you use the vim plugin hitting esc doesn't dismiss the error popup.
So the only way to dismiss it is to use the mouse, which sort of ruins the experience of using vim bindings.

**Comment by vbarrancos** [comment]
I compulsively press Cmd+S several times per minute while working, even if I'm just jumping around code and there's a syntax error from an incomplete line I was typing.  While it's a bit of a pointless habit these days, it's just one I built over many years of computing and I'm not likely to break it anytime soon.  I almost treat Cmd+S as a second Format Code hotkey now.

As you'd expect, I've started seeing these popups frequently as a result of this habit, and they're basically never useful.  My linter is already telling me about syntax errors inline and in the Problems view, so it's just redundant information from Prettier, made worse by how the notifications persist after fixing whatever error.  This means they just sit there ignored for a while until I need to use ESC to dismiss an intellisense popup or something, whereupon they intercept the ESC keypress and irritate me.

I could see how these notifications might be helpful for other workflows, but for the way I work they're just incredibly intrusive and not at all useful, so I'd really appreciate some way to disable them.  Alternatively, if they'd just dismiss themselves after a couple seconds (if this is even possible with the VSCode extension API) it'd be a non-issue.

**Comment by aaroncraig10e** [comment]
Pleeeeease yes let's disable this!

**Comment by andrewnaeve** [comment]
Another disable vote. I know its hard to make devs happy, but for professionals staring at the same screen for 8+ hours a day, this is a pretty unpleasant distraction.

**Comment by xiaoyu-tamu** [comment]
Please add an option to disable it.

**Comment by CiGit** [comment]
Hot topic!
I really want to avoid options :smile: 

We will simply disable it for now. Expect them to come back for different errors. I do not expect prettier to be used as a linter and the output panel should be enough for that if a linter is missing.
Currently, we do a pretty bad job at showing various errors, other than syntax errors.

**Comment by danawoodman** [comment]
Idea: If notifications are show, it would be nice if they would hide after a few seconds or clear when prettier returns successfully

**Comment by CiGit** [comment]
Depends on vscode. closing as I'm cleaning out opened issues
