### ISSUE TITLE
Language-specific settings not working in multi-root workspaces

### ISSUE THREAD

**Issue by metrip** [prettier/prettier-vscode#482]
In a workspace with two root folders, the folder-level configuration

```
"[typescript]": {
  "editor.formatOnSave": true,
},
```

does nothing. Formatting is not done on save. Removing the language tag makes formatting work again, but leads to unwanted behavior.

The same configuration works as expected in a non-multi-root workspace.

**Comment by CiGit** [comment]
I don't think this is an issue with this extension. I don't think this is an issue at all.

If you try disabling prettier for a specific folder you can currently:
`"prettier.disableLanguages":['javascript', 'vue', ...]`

**Comment by metrip** [comment]
It it indeed an issue with Vscode itself, nothing to do with this extension. Closing.
