### ISSUE TITLE
Couldn't resolve parser "json-stringify"

### ISSUE THREAD

**Issue by ntotten** [prettier/prettier-vscode#483]
When trying to format json files I am getting this error. 

This happens in our monorepo when attempting to format any JSON file. Repo is here: https://github.com/forcedotcom/salesforcedx-vscode

Prettier VSCode Version 1.4.0
VS Code Version: 1.23.1
Node Version: v8.11.2
NPM Version: 6.0.1

**Comment by RobinMalfait** [comment]
Hello @ntotten 

I think that you forgot to include your actual error.

**Comment by vazexqi** [comment]
@RobinMalfait - Sorry, here it is (from the Output > Prettier panel in VS Code):

2018-6-5 13:01:32:
------------------
Couldn't resolve parser "json-stringify"

2018-6-5 13:01:56:
------------------
Couldn't resolve parser "json-stringify"

2018-6-5 13:02:02:
------------------
Couldn't resolve parser "json-stringify"

2018-6-5 14:54:22:
------------------
Couldn't resolve parser "json-stringify"

....

**Comment by samturner** [comment]
We're also seeing the same issue. Running Prettier in the command line works find, but the VSCode extension fails.

---

Prettier VSCode Version 1.4.0
VS Code Version: 1.23.1
Node Version: v9.5.0
NPM Version: 5.6.0

**Comment by Xrampino** [comment]
Seconded

**Comment by CiGit** [comment]
Found, I've a patch coming in in next hours.
