### ISSUE TITLE
Doesn't use json-stringify parser for package.json and package-lock.json files

### ISSUE THREAD

**Issue by Nxt3** [prettier/prettier-vscode#486]
As of `prettier@1.13.0`, by default, `package.json` and `package-lock.json` use the `json-stringify` parser. `prettier-vscode` doesn't respect this change and instead seems to continue to opt for the `json` parser.

Maybe related to #485?

**Comment by Nxt3** [comment]
Seems to have been fixed by #485!

**Comment by CiGit** [comment]
Yes, it also fixes that ;-)
