### ISSUE TITLE
Improve parser inferrence

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier-vscode#487]
This only works because of the order getSupportInfo().languages is defined
https://github.com/prettier/prettier-vscode/blob/v1.5.0/src/utils.ts#L19-L27

We should do something which doesn't break if the order changes.

Labeled as bug because it _could_ be one.

**Comment by CiGit** [comment]
We should also take file extension into account if multiple parser match. Angular vs html for instance.

**Comment by ntotten** [comment]
Done in version 3.0
