### ISSUE TITLE
Typescript file contents emptied - not sure cause

### ISSUE THREAD

**Issue by joeandaverde** [prettier/prettier-vscode#489]
From time to time over the past week I’ve had the content of my typescript files emptied. They are typically files I had edited recently or part of a refactor rename. I am not able to revert the change as the undo history is emptied. 

I am not sure this is a prettier bug, vscode, both, or neither. Has anyone else experienced this? Are there any safeguards to be considered that could prevent an entire file being replaced with no content? I can investigate just wanted to get this out ASAP in case others witness the same issue.

Version: 1.5.0
VSCode: 1.24.0, 1.23.1
Settings:
```    
"[typescript]": {
        "editor.formatOnSave": true
},

"editor.formatOnPaste": false,

"files.trimTrailingWhitespace": true,
```

**Comment by joeandaverde** [comment]
I see that getting the document text, calling prettier, and adding the edit is performed at different runs of the event loop:

Async function
https://github.com/prettier/prettier-vscode/blob/12a2990821c136b8c532a979ce38a0cb486d8050/src/PrettierEditProvider.ts#L90

Saving after event loop:
https://github.com/prettier/prettier-vscode/blob/12a2990821c136b8c532a979ce38a0cb486d8050/src/PrettierEditProvider.ts#L265

Perhaps there's a rare situation where the contents before and after the event loop are not consistent? Maybe other plugins are running at the same time and modifying the document in a non-deterministic order?

Perhaps passing the text document in to the asynchronous function rather than calling getText could prevent any strange behavior? Or, if none of the plugins require async making the entire call synchronous. The API to prettier is synchronous as far as I can tell.

I'm grasping for straws here, but this behavior has caused me a lot of grief. I'm looking to see if there are any bugs in other formatters with similar behavior.

**Comment by joeandaverde** [comment]
Similar issue description: https://stackoverflow.com/questions/44975755/visual-studio-code-empties-html-files-on-save

**Comment by CiGit** [comment]
We have something which looks like that: #474 
Can you reproduce it with other extensions disabled/removed ?

I don't see why getting the text content synchronously would be a problem.

Feel free to try out your assumptions ;-)
