### ISSUE TITLE
TS Server broken after formating

### ISSUE THREAD

**Issue by mgambati** [prettier/prettier-vscode#490]
[Reported](https://github.com/Microsoft/vscode/issues/51279) on vscode repo too.

After formatting file, TS Server breaks, no error reported. Restarting fixes until next save, changing file ending works too.

I'm on Windows.

![image](https://user-images.githubusercontent.com/813131/41074821-e7e48e10-69d7-11e8-8349-141d41ff62a6.png)

**Comment by CiGit** [comment]
I'm using typescript and this extension daily. I've never seen a problem after a formatting. I'm not using formatOnSave tho.


I've seen the TS server stuck when I make some uncommon types :disappointed: (usually involving tuples and recursive types)

**Comment by mgambati** [comment]
I don't know if it ever happened on Linux, from my memories this on happens only on Windows. I have no idea what happens to cause this.
