### ISSUE TITLE
Extension formatting and CLI differ

### ISSUE THREAD

**Issue by bkilrain** [prettier/prettier-vscode#492]
A build step in my project checks that all files are formatted correctly by running `prettier '**/*.{js,jsx,ts,tsx,json}' '*.{js,json}' --list-different`. I also have formatOnSave set in my vscode config. When I save a certain file in the editor, the extension formats this line:
![screen shot 2018-06-08 at 9 23 26 am](https://user-images.githubusercontent.com/17045351/41169394-b81ee3d4-6afd-11e8-92f4-8ce7d9013b81.png)
in this way: 
![screen shot 2018-06-08 at 9 23 35 am](https://user-images.githubusercontent.com/17045351/41169404-bfa9149e-6afd-11e8-93b3-43d84cbf27e4.png)

However, the CLI complains that this change isn't correct and I have to run the prettier cli to format before any commits to make sure my builds don't break.

The initial line length is 115 characters. The second formatting is applied even when I don't have typescript annotations (73 characters). 

My `.prettierrc.json`:
```
{
  "printWidth": 120,
  "trailingComma": "es5",
  "semi": true
}
```
I've tried disabling all other extensions and restarting vscode to no avail.

**Comment by bkilrain** [comment]
Ah - looks like I'm using prettier v 1.10 while the extension depends on 1.13.

**Comment by CyxouD** [comment]
In my case it was because prettier wasn't added as dependency. I added it as recommended here https://prettier.io/docs/en/install.html
