### ISSUE TITLE
Leading zero

### ISSUE THREAD

**Issue by xereda** [prettier/prettier-vscode#493]
In a project, I apply lint validation in css (scss) codes, but specifically in .vue files (single file component of vue.js).

One of the validations determines that values below 1 need not contain 0 before the point. This validation is called "number-leading-zero" or simply "leading-zero".

https://stylelint.io/user-guide/rules/number-leading-zero/

The problem is that prettier converts by default all values smaller than 1 to a 0 and more its decimal place.

I need to allow values below 1 to be entered without 0 before the period, conforme o exemplo abaixo:

**this is valid:** 

```css
border: .5px;
```

**this is not valide:** 
```css
border: 0.5px;
```

How do I disable automatic conversion to "leading zero" in vscode?

**Comment by RobinMalfait** [comment]
I have no idea what you mean with 'leading zero'.
Is it related to prettier or is this a general vscode question?

Can you give more information?

**Comment by xereda** [comment]
@RobinMalfait I'm sorry for the lack of information. I supplemented in more detail.

**Comment by CiGit** [comment]
See https://github.com/prettier/prettier/issues/2705

**Comment by CiGit** [comment]
This is a Prettier decision. closing
