### ISSUE TITLE
Unable to add a space before function parens

### ISSUE THREAD

**Issue by SeanGroff** [prettier/prettier-vscode#494]
Default behavior for ESLint is to add a space before function parens. This is also a defined rule with StandardJS.

[eslint space-before-function-paren](https://eslint.org/docs/rules/space-before-function-paren)

Currently, if you use the Prettier VS Code extension and enable `"editor.formatOnSave": true` in your settings.json the space between the function name and parens is removed on save. There is no way to control this behavior in Prettier.

![space-parens](https://user-images.githubusercontent.com/4367312/41302586-7720760a-6e30-11e8-96de-79fae9153265.gif)

**Comment by CiGit** [comment]
Does it work as expected if you call Format document instead of relying on formatOnSave?

**Comment by SeanGroff** [comment]
@CiGit I forgot to mention I tried this as well and it does not make a difference. Any other information that might be helpful to include on this issue?

**Comment by CiGit** [comment]
I will suppose you enabled eslintInegration.

Would need some debugging.

**Comment by connorlufei** [comment]
I got the same problem here, it just remove the space before function parens no matter how you config the eslintrc.js

**Comment by lilililee** [comment]
same problem +1

**Comment by DaanGeurts** [comment]
Same problem here +1

**Comment by paulsmithkc** [comment]
Same problem +1

**Comment by felipebalbi** [comment]
same here

**Comment by maxmannen** [comment]
Same here

**Comment by flm8620** [comment]
+1

**Comment by kamaladenalhomsi** [comment]
+1

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration

**Comment by SevenElement** [comment]
+1

**Comment by jcperez-ch** [comment]
I guess it's one of those cases where a linting rule conflicts with a prettier rule.  Unfortunately in prettier there is no way we can sync the desired behaviour described on a lint configuration.
The only way I see I can stop focusing about linting and keep focus on code is to disable this lint rule in favour of what prettier offers.  I really would like to see more integration between prettier and linters, specially for `pretty code` rules.

**Comment by paulsmithkc** [comment]
This isn't a problem with linting as much as it is a case of overreach and lack of configurability. The whole point of the original post is that it is turning an export into a function call, which changes the execution of that line of code.

**Comment by jaonoctus** [comment]
same problem +1

**Comment by acarlstein** [comment]
Even when I add `spaceBeforeFunctionParen` as `true` in the `.prettierrc` file, when running Format Document in a `vue` file, the space between the keyword `function` and the parenthesis is removed. So from `data () {}` (which is what I need so ESLint doesn't complain) it turn into `data() {}`. :(

**Comment by moreant** [comment]
Same here

**Comment by kothanzaw** [comment]
same +1

**Comment by TiagoHA** [comment]
same problem +1

**Comment by davideprevosto** [comment]
The same is happening to me

**Comment by TheDoctor96** [comment]
same

**Comment by gustavocardoso** [comment]
Same here!

**Comment by kamaladenalhomsi** [comment]
same +1

**Comment by Vorelli** [comment]
^^

**Comment by yuvachang** [comment]
I'm having this issue too. Any resolution yet?

**Comment by Vorelli** [comment]
> I'm having this issue too. Any resolution yet?

I just went and disabled the rule in my eslint config.

**Comment by rebeccapeltz** [comment]
same problem

**Comment by thanhdevapp** [comment]
same problem + 1

**Comment by igortullio** [comment]
Same here

**Comment by ilan274** [comment]
Same issue here.

**Comment by zindont** [comment]
Same issue with vue :(

**Comment by alexkhimich** [comment]
+1

**Comment by pwasem** [comment]
+1

**Comment by unickq** [comment]
+1

**Comment by ntotten** [comment]
So this is really just a difference of opinion of the formatter and linter. The only solution is to match eslint with what prettier allows. The recommendation is to disable formatting rules in eslint and just let prettier handle this: https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules

If you would like a setting in prettier for this, you will need to open an issue in the core repo to suggest that option: http://github.com/prettier/prettier
