### ISSUE TITLE
Format Document command no longer works

### ISSUE THREAD

**Issue by nevetsmik** [prettier/prettier-vscode#495]
Format On Save works but Format Document doesn't work using the Command Pallete or the keyboard shortcuts

**Comment by arvigeus** [comment]
Had similar issue. Deleting VS Code's plugins directory to reset everything fixed the issue. Reinstalling the plugin alone did not help.

**Comment by RobinMalfait** [comment]
Yes I don't know exactly why vscode keeps folders from extensions even though you removed it. This has had errors previously. So you can indeed try this solution to check if it fixes your problem.

https://github.com/prettier/prettier-vscode/issues/469#issuecomment-393083642

**Comment by nevetsmik** [comment]
Thanks @arvigeus and @RobinMalfait! Removing the folder and then reinstalling worked!
