### ISSUE TITLE
"Overlapping ranges are not allowed!"

### ISSUE THREAD

**Issue by lourinaldi** [prettier/prettier-vscode#497]
v1.5.0

I get this error "Overlapping ranges are not allowed!" when attempting to format a very large (10,000+ lines) Markdown document. No further detail or context is provided but a quick web search reveals that other vscode extensions have had similar problems in the past.

**Comment by CiGit** [comment]
Would need some investigations. Could you link us what you already found out?

IMO this is a limitation with vscode.

**Comment by jhoanborges** [comment]
same here getting Overlapping ranges are not allowed! when i attempt to re-indent

**Comment by lourinaldi** [comment]
@CiGit see:

https://github.com/Microsoft/vscode/issues/20757

https://github.com/Microsoft/vscode-tslint/issues/183

**Comment by ntotten** [comment]
This appears to be a VS Code issue. If not, could somebody provide a github repo so i can reproduce this?
