### ISSUE TITLE
.vue file can not format when set `prettier.eslintIntegration` in vscode setting config

### ISSUE THREAD

**Issue by xunan007** [prettier/prettier-vscode#498]
VSCode: v1.24.1
OS: win10
prettier: 1.5.0(vscode plugin)
eslint: 1.4.12(vscode plugin)

I use both prettier and eslint in vscode. When I set `prettier.eslintIntergration: true` in vscode setting config, prettier can not format .vue file. 

output from Vue Language Server：
![image](https://user-images.githubusercontent.com/19498847/41448627-4b755b28-708e-11e8-81df-ef25ede7ba48.png)

My .eslintrc.js is:
```javascript
module.exports = {
  root: true,
  extends: ['plugin:vue-libs/recommended']
}
```

Thx!

**Comment by CiGit** [comment]
I think your issue is with vetur extension.
We do not output anything in "Vue Language Server" and neither support eslint on vue files.

**Comment by snipebin** [comment]
+ 1

**Comment by donglegend** [comment]
I have the same problem!

**Comment by zyy7259** [comment]
Maybe this problem can be fixed by `vetur`. See this [pull request](https://github.com/vuejs/vetur/pull/846).

**Comment by wfzong** [comment]
I have the same problem!....

**Comment by fekata** [comment]
I have the same problem!

**Comment by stevennzhou** [comment]
At last I change the config and use two commands...
i. Set vetur.format.defaultFormatter.js
```
"vetur.format.defaultFormatter.js": "vscode-typescript"
```
ii. then use keyboard shortcuts to `format Document` and `Fix all auto-fixable Problems`

**Comment by ishen7** [comment]
I have the same problem! I'm current using `"vetur.format.defaultFormatter.js": "vscode-typescript"` to fix
