### ISSUE TITLE
Prettier Stylelint integration not working.

### ISSUE THREAD

**Issue by marbuser** [prettier/prettier-vscode#500]
This is my current `stylelint.config.js`.
```
module.exports = {
  "extends": [
    'stylelint-config-idiomatic-order',
    './node_modules/prettier-stylelint/config.js',
    'stylelint-config-standard',
    'stylelint-config-recommended-scss'
  ],
  "ignoreFiles": '**/*.{vue, html, js}',
  "plugins": [
    'stylelint-scss'
  ],
};
```

I have the `prettier.stylelintIntegration` property set to true in my vscode settings, but despite this, in scss files it does not obey any of these extended rules.
A good example is this;
(How the file should look, minus the error of `color` not being in the correct order.)
![image](https://user-images.githubusercontent.com/34422459/41595771-93b2a872-73fa-11e8-8c4b-515451fdd82b.png)

And now here is what happens upon formatting.
(`color` not reordered, and removes all whitespace despite configs saying to leave it.)
![image](https://user-images.githubusercontent.com/34422459/41595827-c19c5350-73fa-11e8-8248-741d1a6c5d70.png)

This leads me to believe the default VSCode formatter is being applied to scss rather than prettier, as this works perfectly in regular css files.

**Comment by CiGit** [comment]
Try disabling other extensions to validate your assumption :-)

**Comment by JoshuaSoileau** [comment]
+1

**Comment by CiGit** [comment]
@mrchief please open an other issue. Initial issue is stalled. Closing
