### ISSUE TITLE
Can't set printWidth value to more than 100

### ISSUE THREAD

**Issue by tree4pl** [prettier/prettier-vscode#503]
I can set lower value but setting anything more than 100 is not working as code is trailed to 100.

**Comment by RobinMalfait** [comment]
I am going to tell you a little secret. Use `80` or `100` don't go bigger :)

That being said, do you have any tools like eslint or editorconfig that override this value? Or do you have a prettierrc file that conflicts with the vscode settings.

**Comment by akuma** [comment]
+1

**Comment by akuma** [comment]
I have a prettierrc file, but it is not working.

.prettierrc
```json
{
  "printWidth": 100
}
```

**Comment by CiGit** [comment]
Stalled, closing
