### ISSUE TITLE
Other ways to resolve prettier package

### ISSUE THREAD

**Issue by mattsjones** [prettier/prettier-vscode#504]
I work on some apps that have shared tooling packages (similar to create-react-app) and due to this, the prettier dependency is not listed in the apps package.json file. 

This causes the editor plugin to use the inbuilt version of prettier which can get out of sync. Would you be open to resolving prettier from node_modules instead of package.json? I'd be happy to submit a PR.

**Comment by CiGit** [comment]
This is what we had in the beginning :-) 
There should be a _next_ version where you could specify prettier's location.
#488 #232
