### ISSUE TITLE
XML formatting

### ISSUE THREAD

**Issue by ThePlenkov** [prettier/prettier-vscode#505]
Hi,

Could you please add XML formatting

Standard prettier playground easily does this. It's the only tool which formats XML exactly how I need.

However VS code doesn't recognize this extension as XML formatter.

Thank you!

**Comment by RobinMalfait** [comment]
Prettier doesn't have support for xml. It does have support for JSX though.
It probably recognizes it as JSX.

For example: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D5UD0WeIANCBAA4ybQDOyoAhgE4sQDuACqwgyk2wRM6MiABGLJmADWcGAGVK0zFADmyGCwCuccqrpwWMLlLUBbJsgBmTADaHyAKzoAPAEJTZ8hU3NwAGVU4G3tHEGUWQxZkCSZxAE87aDFKFlUYAHURGAALZAAOAAZyNIhDTKlKWLS4aOwQ8hY4AEdtTGbTJgsrJFsHPRBDc0xNHUG6VTU7OABFbQh4UIHyGHjs9DzkACZVqUw7KYBhCHNLWKhoRpBtQwAVeP5+wwBfF6A

The div is now self-closing, which is probably not what you want for XML.

**Comment by ThePlenkov** [comment]
But this is the only tool which formats XML exactly how I want )) https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAtgNzEgagSzgHcACAD3QBsoBnJSAJzgF4AdEGgQwAcA6AV3y9GcdqyisYkkuSq0kWMGw48BQkb0ViJUmDIrU66ZVz7ptk6bMPKARhAgBrfFADma3q4RwG+MMOgYBghKGgtdfTk6MH4aGAh0ABFOGE5lAAsYGG4kAHpcmjB0uHROGl5TAPQCnkEAVly4MnhafGgavkEApl4AYVj4pJTOXIBGcKsDeVTbShZ2Sq6ZufYSSFhgyjmGADlOdHmQeycXdy6vKB8-Xh4+Gm5KfBgAGXw4gI2Q7d4AWTL4BgAJTgNH4lBgYRAAD5xJJUABlUoMGAAFU4szgJAQMCeAE94XAYMpgLcoY1YHiCTAAL6rGhImAAMXw4J8AEkACbKABmLIBACFOAw6QzcEL8JxYCZReLJVIQFioOi5gBBfjxfkuDmnZRBfiiBXcHw0N4tMC4gDScFxxO16ChjmttIVsTgAFEyNwIMiURAPWA4JQeZxQgaSDR0hAiGiMQAFY3QENvFJtKDB0MTXSSGJxBLJVJIbhMGjYlPQMW+OUARX4Sd5Plt+HtRZBpZx5dlsBrdcIDGdsKzuhzg3znCQj0ubPg6G7j3rDEb9oncCnJVn+HnzpItjg3O9cGBti1Mbmymg-N3+8Px+VYd5MF6gU4Lgb7D1YcecVX6BRJQeKUOYASG4IUISQEgAG0AHI7Shad-3gKCABoSCg0lcjtBATWgGgoIAXRIFC9wYUosh8cCoM8QlXi-adf3QBC4Cgkgt3wLkFgZE8w2WOAUVxI1lBVJVKFxHEwBDLj2BhHQ4SeEoaGkyxdFQHikC4khMDefAMXTEt2FyaSMCQGi9FcYIiB1N8GH1VYzKjU54TATZKF9Z4IE4diQHfWzzNOFF0mLSNKE8gAmAAGOlIyIAB5TAfEoTgbSsmyFRcMBKH4DkV2nNkoAJOYwHbNNkrDdAICy5R4VOOZ8rgQq-jiHxVhcEsiXYbkQz01Lp1jYsaDPKBv16kFIUUwdUFydBjNNMa4VyOT0AUgc4WHBJfRCWwhVm5SpvWyhNoYDStJ09rOoNAzlpgCbVp-Bx9q2gcJsRUCuMMybsDwQgiChEAkJACBuCKmhkFAIVzNjIUsOQEBOEwCA2N+o4GE4MBHRgeEQLAU5kHfP6Wp8GBes4VxSmQDrQz+gArGgyH5ZHUcJeF9jgV5LjJs6-pAhgSwYaHNtsXFKGgRGixcGAAHU2JgdJkAADjCznghLcXke4aGWx5uLEaYABHQQmCJknOHZimOBKfAcesuA-pNNw5hrCB4BNks-pmSWOWl5AQtd5GWVOR90FJlAoGgOBEddGNgaQcmS2pakgA

**Comment by ThePlenkov** [comment]
I think babylon does the magic

**Comment by ThePlenkov** [comment]
ah.. ok - I see semicolon in the end - so it actually parses it as JS - agree

**Comment by RobinMalfait** [comment]
@ThePlenkov What I suggest is to open an issue on the Prettier repo itself or creating an XML plugin for Prettier. Once it is in prettier it will be in this extension very shortly after that.

**Comment by rattrayalex** [comment]
There is now an official plugin for xml: https://github.com/prettier/plugin-xml
