### ISSUE TITLE
Pass options to prettier-eslint?

### ISSUE THREAD

**Issue by ipchikin** [prettier/prettier-vscode#507]
Is there any way I could pass options to the prettier-eslint on vscode? I want to add html file extension to options.eslintconfig for prettier-eslint. Any way to do it?

**Comment by CiGit** [comment]
Prettier doesn't support HTML currently.
Passing options to eslint is done in eslintrc files

**Comment by devinrhode2** [comment]
I am actually wondering if there's a way to pass options to prettier-eslint, for different purposes - I just want to set prettierLast to true in the options passed to prettier-eslint, please let me know if there's any way to do this currently! :)

**Comment by CiGit** [comment]
There is no way to do that (except modifying extension's code).
There is however a way do _simulate_ prettierLast: 
Remove all formatting options from eslint and let prettier do it's thing. It should even be faster (less rules)

IMO: once you removed formatting rules from eslint, -fix(able) rules should be rare. Thus using prettier-eslint is not interesting.

**Comment by devinrhode2** [comment]
Ok so the ideal setup for most devs would probably be:
eslint config to warn about various little annoying javascript things (name your functions with func-names, for example) - these should appear as you are editing code, and are not auto fixable
On save, run prettier

Only question is - what eslint rules are auto fixable, which prettier doesn't count for? Right now I'm using airbnb's eslint config+prettier via this package
