### ISSUE TITLE
Respect new line per chained call and binary operator wrapping

### ISSUE THREAD

**Issue by Vandivier** [prettier/prettier-vscode#508]
In [eslint we have](https://eslint.org/docs/2.0.0/rules/newline-per-chained-call) `newline-per-chained-call`.

In the JS ecosystem including Prettier there are a number of solutions involving binary operator wrapping (aka short-circuiting conditionals, etc). One example is seen on the Prettier issue "[Force break conditional when `if` test breaks](https://github.com/prettier/prettier/issues/868)."

I'd like these two options available in prettier-vscode. If they already exist then please just point me in the right direction. Alternatively, if there is a way to get these formatting requirements outside of prettier-vscode, I'd love to hear about that too.

A couple code snippet images are below. I prefer the left hand but my current prettier-vscode is resulting in the right hand. My VS Code `settings.json` is as follows:

    {
        "editor.formatOnSave": true,
        "html.format.wrapAttributes": "force-aligned",
        "javascript.preferences.quoteStyle": "single",
        "prettier.eslintIntegration": false,
        "prettier.printWidth": 140,
        "prettier.singleQuote": true,
        "prettier.tabWidth": 4,
        "prettier.trailingComma": "es5",
        "typescript.preferences.quoteStyle": "single"
    }

Wrap chains:
![image](https://user-images.githubusercontent.com/5559355/42179551-69a2738e-7e02-11e8-8f5c-2ceef8327d74.png)

Wrap binary operators / short-circuiting checks / conditionals
![image](https://user-images.githubusercontent.com/5559355/42179621-a44b3c46-7e02-11e8-8732-306a7333857d.png)

Notice that it took the code off-screen...*cringes*

A small note on binary operator wrapping: I've seen some solutions keep the operator at the End of Line and wrap the next line, but I think it's better to have the operator at the start of the line if possible.

**Comment by CiGit** [comment]
You won't have more in this extension you can have with prettier or prettier-eslint.
You may find (one or more) eslint rule which does what you want. (`--fix` rule)
