### ISSUE TITLE
Trailing-comma "all" stopped working

### ISSUE THREAD

**Issue by valimaggi** [prettier/prettier-vscode#509]
This setting stopped working for me suddenly. 

These things I tried:
- set `"prettier.trailingComma": "all"` in user settings
- set `"prettier.trailingComma": "all"` in workspace settings 
- disabled all other plugins

But no luck. It simply doesn't add those trailing commas when I save the file while it does the formatting just fine (single quote setting works too).

I don't remember when this started to occur exactly but I it has been like this maybe like 1 week and I use VS Code daily. I have the newest version of VS Code (1.24.1)

**Comment by CiGit** [comment]
Have you installed an old version of prettier in your project?

Can you look at dev console ?

**Comment by matteocng** [comment]
@valimaggi it could be like @CiGit said an older prettier version, or you might have `"prettier.eslintIntegration": true` in your VS Code user or workspace settings.

I had the same issue with that setting and the following setup (sharing my solution in case someone stumbled upon this too):

Visual Studio code: 1.25.0 (1.25.0)
Prettier in `node_modules`: 1.13.7
Eslint in `node_modules`: 5.1.0

Prettier configuration in `package.json`:

```json
  "prettier": {
    "bracketSpacing": true,
    "singleQuote": true,
    "jsxBracketSameLine": true,
    "trailingComma": "all",
    "printWidth": 80,
    "semi": false
  },
```

Result of: `yarn eslint --print-config .eslintrc.js | grep \"comma-dangle\" -A 8`

```json
    "comma-dangle": [
      "off",
      {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "always-multiline"
      }
```

I modified that configuration in `.eslintrc.js` ([full file](https://gist.github.com/matteocng/592e823e2521ae771a0f05c74ba8a932)) this way:

```json
    "comma-dangle": [
      "error",
      {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "always-multiline"
      }
```

Result of: `yarn eslint --print-config .eslintrc.js | grep \"comma-dangle\" -A 8`

```json
    "comma-dangle": [
      "error",
      {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "imports": "always-multiline",
        "exports": "always-multiline",
        "functions": "always-multiline"
      }
```

VS Code user settings:
```json
{
    "window.zoomLevel": 2,
    "editor.rulers": [
        80,
    ],
    "editor.formatOnSave": true,
    "workbench.startupEditor": "newUntitledFile",
    "editor.minimap.enabled": true,
    "prettier.eslintIntegration": true,
    "explorer.confirmDragAndDrop": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
}
```

VS Code workspace settings:

```json
{
	"settings": {},
}
```

It now works well.

**Comment by valimaggi** [comment]
@CiGit might be that also, but it was definitely what @matteocng said, I had that `"prettier.eslintIntegration": true` setting and wanted it that way also. We fixed our issue like @matteocng explained by modifying the eslint configuration in `.eslintrc.js`
