### ISSUE TITLE
HTML tags are not being correctly formatted

### ISSUE THREAD

**Issue by andreshg112** [prettier/prettier-vscode#510]
Visual Studio Code
Versión: 1.24.1
Confirmación: 24f62626b222e9a8313213fb64b10d741a326288
Fecha: 2018-06-13T17:47:35.732Z
Shell: 1.7.12
Representador: 58.0.3029.110
Nodo 7.9.0
Arquitectura x64

Prettier 1.5.0

Before formatting:
![image](https://user-images.githubusercontent.com/15859884/42292045-57a3397c-7f95-11e8-9e88-4f89b3bbd236.png)

After formatting:
![imagen pegada el 2018_07_04 11_16 am](https://user-images.githubusercontent.com/15859884/42291985-d32ceb7a-7f94-11e8-85db-7fa96f482c0f.png)

Notice that scripts and styles are being correctly formatted, however, the template is not (line 11).

Even if I do the next thing it doesn't work:
![image](https://user-images.githubusercontent.com/15859884/42292115-c67fb56e-7f95-11e8-8e9c-57ba032f8239.png)

**Comment by CiGit** [comment]
Prettier doesn't format `template` part of vue files.
I think Vetur does it with an other formatter.

**Comment by andreshg112** [comment]
Neither Vetur do it!

**Comment by CiGit** [comment]
Prettier currently doesn't support html / vue's template.
Tracked on prettier's repository
