### ISSUE TITLE
Disappointing formatting on Ts file

### ISSUE THREAD

**Issue by Sampath-Lokuge** [prettier/prettier-vscode#515]
Please see the attached `gif`. I have used `shift + alt + F` keys on win 8.1 PC.

We need:`It should stay on the single line.`

[Issue as Gif file](https://imgur.com/a/K0VzEsX)

Prettier - Code formatter Ver : `1.5.0`

**Comment by Sampath-Lokuge** [comment]
I have completely remove this buggy plugin and VS code default formatting perfectly fine for me.

**Comment by knight-bubble** [comment]
This one should fix it https://github.com/prettier/prettier-vscode/pull/414.

**Comment by azz** [comment]
Working as intended.
