### ISSUE TITLE
Error formatting JSON with eslintIntegration

### ISSUE THREAD

**Issue by texastoland** [prettier/prettier-vscode#517]
Attempting to format JSON with `"prettier.eslintIntegration": true` reports a parse error.

The plugin checks whether the file's parser is in the `JavaScript` group:

https://github.com/prettier/prettier-vscode/blob/12a2990821c136b8c532a979ce38a0cb486d8050/src/PrettierEditProvider.ts#L127-L129

But that includes JSON:

https://github.com/prettier/prettier/blob/65d595d60aa6b7d5e8798c2a5fca962f2305c196/src/language-js/index.js#L89-L92

A possible fix is to filter JSON:

```js
const doesParserSupportEslint = getGroup('JavaScript').some(lang =>
  lang.tmScope !== 'source.json' && lang.parsers.includes(parser)
);
```

**Comment by RobinMalfait** [comment]
Is this also the problem when you reloaded the VSCode window? Or is this also the case when you open the json file in its own dedicated window?

You can also try this in your vscode settings:

```js
"[json]": {
  "prettier.eslintIntegration": false
},
```

This will assure that the 'normal' prettier is used instead of the prettier-eslint binary.

**Comment by texastoland** [comment]
Right `prettier-eslint` wasn't what I wanted. `eslint-plugin-prettier` is. I was just reporting a bug with links to the cause and a possible solution. It doesn't affect me.

**Comment by CiGit** [comment]
Can you share the parse error? prettier doesn't work on syntactically incorrect files

**Comment by texastoland** [comment]
@CiGit to reproduce open a JSON file with that option enabled. I took the time to find out why, link where in your own source code, with a gist in the description, and propose a (correct) solution. Honestly I'm not using the feature anymore. You can close the ticket if you don't want to fix it.

**Comment by CiGit** [comment]
That's exactly what I did and it formatted without error. I'll close then
