### ISSUE TITLE
There is no document formatter for 'javascript'-files installed.

### ISSUE THREAD

**Issue by lorensr** [prettier/prettier-vscode#518]
`Format Document` and `Format Selection` have no effect. The first time I try to format after reloading the window, I get a message box that says `There is no document formatter for 'javascript'-files installed.` The behavior persists after uninstalling, deleting `~/.vscode/extensions/esbenp.prettier-vscode-[version]`, restarting vscode, and installing. There are no errors under Help -> Developer Tools -> Console, and nothing that mentions prettier. Is there anything else I can do to diagnose the issue?

**Comment by lorensr** [comment]
Looks like there are a number of people with this issue in #288

**Comment by meowwwls** [comment]
I'm having the same issues. `.json` and `.html` files are the only files where formatting is currently working. For everything else, when trying to format from the command palette, I get the same error. When trying to format on save, all fail silently.

I tried uninstalling and reinstalling and restarting several times and nothing works. I'm not sure how this just happened because everything was fine yesterday and I have not changed or updated anything.

**Comment by lorensr** [comment]
@meowwwls do `.js` files work in other windows, or in other projects? The issue has somehow gone away for me

**Comment by xiaodeaux** [comment]
Had this problem when I opened vscode and it reopened the previous workspace I had open, and then I created a new `.js` file and tried to format it.

**Comment by lorenz068** [comment]
I confirm this happen after a new file is created

**Comment by eranraveh** [comment]
> Had this problem when I opened vscode and it reopened the previous workspace I had open, and then I created a new `.js` file and tried to format it.
> 
> **EDIT**
> I just closed vscode and then when I did a little window popped up briefly saying that is was updating vscode. Perhaps this has something to do with the vscode updater?

I can confirm, I had updates in the pipe while had this issue. I installed and restarted the vsc and voila - all goods again!

**Comment by CiGit** [comment]
IS this still an issue ? 
vscode 1.33 changed things in the formatting area :-)

**Comment by JonathanTroyer** [comment]
This happened to me just today in 1.35.0. As some suggested in #288, I toggled `javascript.format.enable` which had no effect. However, restarting VSCode fixed the issue.

**Comment by arunk01** [comment]
just re-installed stand formatter , and the issue resolved. As you might know , run the folllowing command

npm install -g standard
