### ISSUE TITLE
Prettier cannot format the code to use tab as indentation

### ISSUE THREAD

**Issue by uilnauyis** [prettier/prettier-vscode#519]
I want to use tab as indentation and want the size of the tab to be four, for which I set my user settings and workspace settings as shown in following screenshots:
![user-settings](https://user-images.githubusercontent.com/39727054/43036107-c2a436b0-8d4e-11e8-8c20-5d8b3d1481f6.PNG)
![workspace-setting](https://user-images.githubusercontent.com/39727054/43036110-c54d415e-8d4e-11e8-90d1-d7858c62d698.PNG)
As you can see I set 'prettier.useTabs' to true and 'prettier.tabWidth' to 4. However, when I open javascript/typescript files and run 'format document' command in command palette, the indentation after formatting is 2 spaces instead of tabs of size 4.

![format-before-disable-prettier](https://user-images.githubusercontent.com/39727054/43036148-ae0c5e20-8d4f-11e8-92f9-30efa757c3eb.PNG)

I then disabled prettier and now 'format document' command works well. So I think it could be a bug with prettier.

![after-disabling-prettier](https://user-images.githubusercontent.com/39727054/43036152-cb115d36-8d4f-11e8-8af5-5317d0566c67.PNG)

**Comment by CiGit** [comment]
You are looking for *editor.tabSize* I think

**Comment by uilnauyis** [comment]
Hi, 'editor.tabSize' has already been set to '4' but it does not help. Also, the problem is that the spaces are not converted to tabs, not with the width of tabs.

**Comment by CiGit** [comment]
:confused: So you want to format with tabs but prettier outputs spaces ?

Do you have any `editorconfig` file with `indent_style = space` in it ?

**Comment by simonh1000** [comment]
I had a related issue - trying to get 4 space indent. What I see is that cmd-A + format selection works, format document does not (on Mac)

**Comment by CiGit** [comment]
@simonh1000 Seems not related to me. Eslint was not mentioned in OP. please open a new issue.
And it seems to me your issue is with your configuration

Closing as stalled
