### ISSUE TITLE
Nothing happens when formatting markdown?

### ISSUE THREAD

**Issue by GandalfSaxe** [prettier/prettier-vscode#521]
As a test, I expect indented unordered sublists of 4 spaces to be reduced to 2 spaces as such: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAFTgZxgHSkICp148SzcCp11Tya6HrDLH3Xa76qLvmfGmyggANCAgAHGAEtoOZKACGAJ1UQA7gAU1CRSmUA3CLIAm4kACNVysAGs4MAMpS7sqAHNkMVQFc4CQ8cOFUYbVtPAFtlZAAzZQAbEIkAKxwADwAhWwcnZ2UouAAZDzh4pJSQN1UQ1WQQGNV7My1RCSlVDxgAdXMYAAtkAA4ABg6NEJ7bKQbO3FCjcolVOABHP1lViOVo2KQE5MCQEKjZH39jnA9PRLgART8IeAqjiRhlKz6zQeQAJnetlkiRuAGEIFEYg0oNBliA-CFMJ8DIcQgBfNFAA

However running `Format Document` changes nothing if run on the test markdown code above?

This is not the same as #402 because I don't get the error message "There is no formatter for 'markdown'-files installed".

**Comment by GandalfSaxe** [comment]
Haven't touched the prettier default settings, so I have `"prettier.eslintIntegration": false`.

Tried Reinstalled prettier, quit VSCode, nothing helps. Nothing happens still.

I'm on VSCode Insiders 1.26 portable edition on the Mac, can test VSC-insiders 1.26 portable for windows later.

**Comment by RobinMalfait** [comment]
I'll try the vscode insiders later today / this week. If I find something I'll report back. If you somehow can figure out why things are happening I would love to hear that. 

If interested, you can try to debug the extension via vscode and check if you have any errors. (You can try to open the devtools as well)

![](http://d.rbn.nu/OIDeb6.png)

**Comment by GandalfSaxe** [comment]
Do you mean cloning the repo, running `npm install` from within it, then launching the extension through the debugger? Still new to this :)

**Comment by RobinMalfait** [comment]
That's also an option, you can also open the devtools and see if you see any logs when you save.

**Comment by GandalfSaxe** [comment]
Ah so they're equivalent for the purposes of debugging?

I don't see anything from prettier in there. Not before or after I invoke "Format Document". Only some errors from vscode-icons, which should be [fixed](https://github.com/vscode-icons/vscode-icons/pull/1651) in the next release to support portable mode.

**Comment by anishmittal2020** [comment]
Any updates? Facing the same issue...

**Comment by borekb** [comment]
I'm observing the same issue on this version in VSCode 1.31.1 on macOS. @GandalfSaxe, did you manage to work it out?

**Comment by GandalfSaxe** [comment]
Can't remember, but I don't think I found the solution at the time.

**Comment by ntotten** [comment]
Is this issue still happening? Can somebody provide me a github repo that reproduces it?
