### ISSUE TITLE
Use global `prettier` package as a fallback when Prettier is not installed inside a project.

### ISSUE THREAD

**Issue by ryanpcmcquen** [prettier/prettier-vscode#522]
When inside a directory with a `package.json` that has `prettier` as a dependency, this extension will not format a document until I run `yarn install` (or `npm install`), even if I have `prettier` installed globally on the machine. Seems like the extension should check for a global fallback rather than just failing.

**Comment by kurtextrem** [comment]
This extension has a bundled version integrated, however I agree it should use this method of checking:
`global > local > bundled`

**Comment by CiGit** [comment]
It's true, it fails if you have a prettier declared in your deps but not installed.
It uses a bundled version if it's not specified. 

We should show an error message in the first case.

**Comment by RobinMalfait** [comment]
The order that @yuhr provided makes more sense. If you work in a team and have a certain version locally than you want to use that version. Otherwise use the global one, if you don't have it, use the bundled one.
