### ISSUE TITLE
Support for custom file extensions

### ISSUE THREAD

**Issue by artus9033** [prettier/prettier-vscode#523]
The extension lacks support for specifying custom file extensions that should be inspected & written, which is extremely problematic, for example, in case of using `node --experimental-modules module.mjs`.

The esm loader forces all ES6 modules to have the .mjs extension, so they cannot be changed to remain the ability to run such code without transpiling it to ES5 beforehand, which makes prettier-vscode simply ignore them during editing.

**Comment by CiGit** [comment]
This extension is base on the languageId your file uses. Which one do you use?
If you set your file to *javascript*, it should format.

**Comment by FDiskas** [comment]
what about `*.handlebars` or `*.hbs` ? :warning:

**Comment by trkoch** [comment]
I'd like to format `.erb` files. It seems to work just fine with the HTML formatter.

**Comment by CiGit** [comment]
hbs or erb are not supported by prettier. Maybe by plugins we should support soon. 

AFAIK it only _seems_ to work with HTML formatter. 
Closing as OP seems solved
