### ISSUE TITLE
User/Workspace JSON formats differently?

### ISSUE THREAD

**Issue by GandalfSaxe** [prettier/prettier-vscode#524]
If I format my User Settings, all empty lines are removed.
If I format any Workspace Settings, single empty lines are allowed.

Single empty lines in User Settings are allowed if new VSCode window is opened without opening any folder or files, but just opening settings straight away.

What is going on?

**Comment by CiGit** [comment]
This is certainly because we register a formatter for your workspace only.
I'm planing to change that.

**Comment by GandalfSaxe** [comment]
Sounds good 👌
