### ISSUE TITLE
Why are Windows and macOs formatted differently

### ISSUE THREAD

**Issue by hms181231** [prettier/prettier-vscode#525]
windows： 
![image](https://user-images.githubusercontent.com/15353926/43190908-ae32bbbc-902c-11e8-9549-fb010e0b5712.png)

macOS：
![image](https://user-images.githubusercontent.com/15353926/43190966-c50df856-902c-11e8-9212-d6216b0b5241.png)

error:
![image](https://user-images.githubusercontent.com/15353926/43191187-3dccad6e-902d-11e8-9209-58427038f701.png)

**Comment by RobinMalfait** [comment]
Are you on the same version on both machines?

**Comment by Hal-pan** [comment]
yes,  the same version.

![image](https://user-images.githubusercontent.com/15353926/43212068-a5a56506-9065-11e8-828e-e6f1f54833a1.png)

**Comment by CiGit** [comment]
There may be some fallback to editorconfig maybe which may be different on both machines.

Aside, you are using redundant prettier tools.

**Comment by zcuric** [comment]
I have exact same issues with all latest `eslint` and `prettier` packages. 
My env is `node@10.14.0` and `npm@6.4.1`, MacOS Mojave. I also experienced this issue on a different MacOS computer. Windows/Linux behave the same.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
