### ISSUE TITLE
Extension doesn't notify user of syntax error in config files

### ISSUE THREAD

**Issue by vhfmag** [prettier/prettier-vscode#526]
Prettier supports a lot of configuration file names, as noted on the following list, from their docs' [configuration page](https://prettier.io/docs/en/configuration.html):

> Prettier uses cosmiconfig for configuration file support. This means you can configure prettier via:
> - A .prettierrc file, written in YAML or JSON, with optional extensions: .yaml/.yml/.json/.js.
> - A prettier.config.js file that exports an object.
> - A "prettier" key in your package.json file.

I tried both .prettierrc.js and prettier.config.js. Prettier works as usual, following my configurations, but the extension doesn't seem to look for either of them, falling back to default settings. It outputs the following message: `Failed to resolve config for /home/user/example/file/name.js. Falling back to the default config settings.`

Just for context, I'm configuring prettier by javascript to be able to require a template configuration from a npm package.

Does anyone else have had the same issue before? I searched for the error message, but couldn't find any related issue.

Thanks!

**Comment by vhfmag** [comment]
It actually looks like both [.prettierrc.js](https://github.com/prettier/prettier-vscode/blob/78b34af4d1372313ecb3b3aab8e02ac79f62bd08/src/configCacheHandler.ts#L13) and [prettier.config.js](https://github.com/prettier/prettier-vscode/blob/78b34af4d1372313ecb3b3aab8e02ac79f62bd08/src/configCacheHandler.ts#L5) are looked for, as seen in https://github.com/prettier/prettier-vscode/blob/78b34af4d1372313ecb3b3aab8e02ac79f62bd08/src/configCacheHandler.ts. In that case, I have got no idea about why running prettier and formatting via the extension have distinct behaviors.

Just to make it easier for debugging, that's my `prettier.config.js` file:
```js
const defaultConfig = require("@cubos/prettier");

module.exports = {
    ...defaultConfig,
};
```

**Comment by CiGit** [comment]
Does it work if you `require(./relative/path/to/node_modules/@cubos/prettier')`

**Comment by vhfmag** [comment]
I just tested it and it doesn't seem to work with either relative or absolute paths. I'm using VSCode 1.25.1 and Prettier VSCode 1.5.0 under Ubuntu 18.04, if this helps.

**Comment by vhfmag** [comment]
Ok, so that's the part of the code that emits the error message:

```ts
const { config: fileOptions, error } = await resolveConfig(fileName, {
    editorconfig: true,
});

if (error) {
    addToOutput(
        `Failed to resolve config for ${fileName}. Falling back to the default config settings.`
    );
}
```

And that's resolveConfig definition:

```typescript
const bundledPrettier = require('prettier') as Prettier;

/**
 * Resolves the prettierconfig for the given file.
 *
 * @param filePath file's path
 */
async function resolveConfig(
    filePath: string,
    options?: { editorconfig?: boolean }
): Promise<ResolveConfigResult> {
    try {
        const config = await bundledPrettier.resolveConfig(filePath, options);
        return { config };
    } catch (error) {
        return { config: null, error };
    }
}
```

So I tried running `prettier.resolveConfig(myFilePath, { editorconfig: true })` just like Prettier VSCode does (with the same prettier version too), but it actually works and resolves the config as expected. I'll try to debug the extension and see what actually is the value of `error`.

**Comment by CiGit** [comment]
I think it has something to do with current working directory

**Comment by vhfmag** [comment]
Ok, I found the issue. The error triggered was `SyntaxError: Unexpected token ...`, and it refers to the following:

```module.exports = {
    ...defaultConfig,
};```

As of VSCode 1.25.1, the Node version seems too be 7.9.0, which doesn't support spreading object properties. Which, I guess, means my issue never had anything to do with Prettier VScode itself?

Sorry for the inconvenience!

**Comment by CiGit** [comment]
Ow right !

We should have notified the user about the error
And that's not the only error we hide to the user I think

**Comment by vhfmag** [comment]
Should I rename the issue to something like 'Extension doesn't notify user of syntax error'?

**Comment by CiGit** [comment]
You can with a precision : in config files

**Comment by vhfmag** [comment]
Done :)

**Comment by vhfmag** [comment]
How should it be notified? Would it be something like how it's handled in [src/errorHandler.ts:131](https://github.com/prettier/prettier-vscode/blob/5961c2a50302b6fa393527c3bb591c57657d3faf/src/errorHandler.ts#L131)?

```ts
addToOutput(addFilePath(err.message, fileName));
updateStatusBar('Prettier: $(x)');
```

Maybe the `$(x)` could be misleading, since the formatting itself didn't fail, it just won't use the user configuration file, so `$(alert)`?

**Comment by CiGit** [comment]
Yes, same as already done (extract a log function if it's not already done)
We should maybe fail fast. Don't format if there is an error, it mostly won't format as the user wanted it in the first place.
@RobinMalfait Any idea?

**Comment by vhfmag** [comment]
I have had the following experience several times:
- I edit a file and save
- The extension fails to load my configuration, loads default and formats the file
- I hit undo, disable "editor.formatOnSave" and save again

So I would definitely prefer if the extension just failed. :)

**Comment by ntotten** [comment]
Version 3.16.0 will now show an error when an invalid configuration file is detected.
