### ISSUE TITLE
Format Selection in scss files doesn't work

### ISSUE THREAD

**Issue by electricarts** [prettier/prettier-vscode#529]
Do I have to turn on the Format Selection of scss files somewhere? Format document is working but Format Selection gives a "There is no selection formatter for 'scss'-files installed." error.

**Comment by RobinMalfait** [comment]
Do you have eslint integration enabled?

If so, try this:

```json
"[scss]": {
  /** PRETTIER */
  "prettier.eslintIntegration": false
},
```

**Comment by electricarts** [comment]
No. prettier.eslintIntegration is already set to false.

**Comment by electricarts** [comment]
Did some testing. Fresh installation of VSC on a Virtual Machine. No other extensions than Prettier installed. New scss file. Same issue and error message. 

![screen shot 2018-08-02 at 05 57 41](https://user-images.githubusercontent.com/625286/43561851-4d767672-9619-11e8-93ab-80c8531cabf3.png)

**Comment by CiGit** [comment]
We enabled range formatting on some file types only. SCSS is not part of those as prettier doesn't support it.
This would first need to be implemented in prettier.

**Comment by rowild** [comment]
Is there a documentation for what is possible to be range-formatted and what not?
