### ISSUE TITLE
No longer formats on save

### ISSUE THREAD

**Issue by jisuo** [prettier/prettier-vscode#531]
I've looked at the issues below and others, nothing there helps.

https://github.com/prettier/prettier-vscode/issues/440
https://github.com/prettier/prettier-vscode/issues/439

I have so far:

- Disabled/enabled prettier plugin
- Re-installed prettier plugin
- Restarted VS Code multiple times
- Updated prettier to latest version 1.14.0
- Updated vs code to latest version (1.25.1)
- Restarted mac os
- disabled ALL other plugins

Format document command does nothing and there is no check next to Prettier in bottom corner after saving.

I was away on vacation and came back and it didn't work anymore. :)

settings enabled:

```
"editor.formatOnSave": true,
  "[javascript]": {
    "editor.formatOnSave": true
  },
  "prettier.singleQuote": true,
```

**Comment by CiGit** [comment]
I don't get it exactly. Is your issue with format on save? or `Format Document`

You can increase `editor.formatOnSaveTimeout` in the first case.

**Comment by jisuo** [comment]
Also editor.formatOnSaveTimeout seems to have fixed it. 👍

**Comment by CiGit** [comment]
Glad you found the problem.

But this shouldn't fix Format Document which seemed to also fail 
>Format document command does nothing and there is no check next to Prettier in bottom corner after saving.

**Comment by jisuo** [comment]
Format Document (Shift + alt + F) seems to be working now as well (it formats using prettier rules). And I haven't made any changes to vs code (except to the editor.formatOnSaveTimeout setting), I just used a different IDE since I had this issue. I really don't understand.
