### ISSUE TITLE
Comments in JS, CSS, & HTML ( Add user settings to stop moving Comments)

### ISSUE THREAD

**Issue by neddyusa** [prettier/prettier-vscode#534]
Please add 3 separate user settings to VScode Prettier.
1 for JavaScript, 1 for CSS, and 1 for HTML.
Each of them should turn off ( moving comments on a line that has code on it. ) and even to 
  stop moving my comments on a separate line (without code on it ).
When I add comments on the SAME line as my code, I like to move it to the right and keep it 5 or 10 
spaces away from the code on the left side.   I can read the comments easier that way.
Sometimes I line up the Comments from line to line ( in a row ).

Please consider these new User Setting options.
Kind Regards,
Norm

**Comment by CiGit** [comment]
This issue belongs to the prettier/prettier repository. There is nothing we can do here.
