### ISSUE TITLE
Vscode prettier extension doesn't seem to work when I have prettier as a dependency in package.json

### ISSUE THREAD

**Issue by Galabov93** [prettier/prettier-vscode#537]
I have set a pre-commit hook using prettier in package.json
`{
    "name": "client-strombaron",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
        "react": "^16.4.1",
        "react-dom": "^16.4.1",
        "react-scripts": "1.1.4"
    },
    "scripts": {
        "precommit": "lint-staged",
        "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
        "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
        "start-js": "react-scripts start",
        "start": "npm-run-all -p watch-css start-js",
        "build-js": "react-scripts build",
        "build": "npm-run-all build-css build-js",
        "test": "react-scripts test --env=jsdom",
        "eject": "react-scripts eject"
    },
    "lint-staged": {
        "*.{js,jsx,json,css}": [
            "prettier --write",
            "git add"
        ]
    },
    "devDependencies": {
        "node-sass-chokidar": "^1.3.3",
        "npm-run-all": "^4.1.3",
        "husky": "^0.14.3",
        "lint-staged": "^7.2.0",
        "prettier": "^1.14.0"
    }
}`
Apparantly the line  "prettier": "^1.14.0" breaks the extension, because when it is removed it works.

Anyone else facing the same issue and knows how to fix it?

**Comment by CiGit** [comment]
Did you npm / yarn install ?

**Comment by Galabov93** [comment]
Thank you! That fixed the problem
