### ISSUE TITLE
ESLint integration is broken

### ISSUE THREAD

**Issue by quentez** [prettier/prettier-vscode#543]
Since the last update today, only `prettier` gets applied and not `prettier-eslint`.
We have `prettier.eslintIntegration` enabled in our configuration.

Running `prettier-eslint` manually produces the correct output.
Everyone on our team has had to revert the extension.

I don't see anything obvious in the changes from `1.5.0` to `1.6.0` that could explain this...
I'm not sure how to debug VSCode extensions to actually see what's going on.

**Comment by quentez** [comment]
It looks like the `doesParserSupportEslint` is `false` when it should be `true`.

**Comment by svipben** [comment]
Same here for `tslint` integration.

**Comment by CiGit** [comment]
I'm currently working on a fix for eslint. 

@svipben please open a new issue this concerns eslint.
Tslint is definitely an other case. And explain what is _worst_

**Comment by svipben** [comment]
@CiGit I was wrong, everything is fine with `tslint` integration, the problem is with this issue: https://github.com/palantir/tslint/issues/2814. That's why it doesn't respect `indent` rule.

**Comment by quentez** [comment]
Thank you for the quick fix :) !
