### ISSUE TITLE
yml formatting broken 1.16.0

### ISSUE THREAD

**Issue by dbroadhurst** [prettier/prettier-vscode#545]
prettier is replacing '---' with '...' in yml files.

--- is used in kubernetes definition files to separate tasks defined in the same yml file.

**Comment by CiGit** [comment]
What do you mean by 1.16.0 ?
this extension (1.6.0) is bundled with prettier 1.14.0
1.6.1 is bundled with 1.14.2 which corrects https://github.com/prettier/prettier/issues/4955
