### ISSUE TITLE
Ignore Node modules by default (to match CLI behaviour)

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-vscode#548]
[Prettier's CLI ignores `node_modules` by default](https://github.com/prettier/prettier/pull/1683). However, for this VSCode extension, users must manually specify `node_modules` in a `.prettierignore`.

Could we make this extension's default behaviour match that of the CLI, which is to ignore `node_modules`?

**Comment by RobinMalfait** [comment]
It is an option, but I wonder why you edit files in the node_modules folder? What's your use case?

**Comment by OliverJAsh** [comment]
Debugging (e.g. adding `console.log`s), and then occasionally I "commit" changes to `node_modules` via [`patch-package`](https://github.com/ds300/patch-package).

**Comment by CiGit** [comment]
Ignoring _node_modules_ makes sens when you format an entire folder (glob).
When formatting a file, you expect that file to be formatted (maybe except when specifically ignored)

We don't use the CLI but the API which hasn't that option by the way.

**Comment by OliverJAsh** [comment]
Hmm, I see your point, but that's quite subjective. In my case, I like to define include/exclude globs for projects, and then have consistent behaviour on both the command line and in my IDE. I guess that's a matter of preference—we could leave this issue open to see who else wants that?
