### ISSUE TITLE
I have a problem with making beautify  to work

### ISSUE THREAD

**Issue by sergiu11** [prettier/prettier-vscode#549]
I don't know exactly what happened. 

I had installed Beautify ad it worked. I checked online to see what other extension I can add for VS Code to make my it easier to use. After I installed a new  extension (I don't remind which) Beautify stopped working.

I deleted all extension. I installed again Beautify. .Still not working.

Also I deleted the VS Code and reinstalled the windows (I wasted to make that app to work), I installed VS Code and I added just Beautify. Still not working.

Can you help me with some solution?
What setting should I modify?

**Comment by RobinMalfait** [comment]
This is the prettier-vscode extension, there are known issues if you have both installed. Keep one of them.

**Comment by sergiu11** [comment]
Thank You
