### ISSUE TITLE
Formatting SCSS  `Unexpected token, expected`

### ISSUE THREAD

**Issue by pureth** [prettier/prettier-vscode#551]
Hello!
I wonder if somebody can shed some light on this issue: after spending a couple of hours trying to get the `Prettier` plugin working for SCSS files (it works wonderfully for JS files), I've given up.

I tried changing settings all over the place (rc file, workplace settings, global settings) and read all the top 10 results on Google. Am i missing something basic here?

Is css/sass unsuported without additional config?

#### RC files:
![screenshot 200](https://user-images.githubusercontent.com/12846819/44038030-b95ad55c-9f0d-11e8-8318-cfa99895c0ba.png)

#### After running CMD + SHIFT + P:
![screenshot 199](https://user-images.githubusercontent.com/12846819/44038029-b944e6c0-9f0d-11e8-8b5b-705a6e187905.png)

**Comment by RobinMalfait** [comment]
Look at the line before it.
If you have

```scss
@import "..." <- missing ; will

@import "...";
        ^ Will actually show up here for some reason.
```

**Comment by pureth** [comment]
It looks like removing the `"parser": "babylon"` setting fixes the issue. SCSS now formats as expected!
It's kinda strange though, is it not? I was under the impression that Babylon was the default parser.

**Comment by CiGit** [comment]
Babylon **was** the default parser. ie: when none was specified.
The parser is now inferred from file's extension.
In your case, you just said: Use babylon whatever file I'm using. In this case a CSS file which indeed couldn't be parsed by it

**Comment by CiGit** [comment]
Closing as it is resolved

**Comment by pureth** [comment]
@CiGit thanks you made my day, SASS is pretty!
