### ISSUE TITLE
"eslintIntegration: true" formats JSX incorrectly

### ISSUE THREAD

**Issue by delgermurun** [prettier/prettier-vscode#552]
```jsx
import React from 'react';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1 className="App-title">Welcome to React</h1>
      </header>
      <p className="App-intro">
        To get started, edit <code>src/App.js</code> and save to reload.
      </p>
    </div>
  );
}

export default App;
```

becomes

```jsx
import React from 'react';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1 className="App-title">Welcome to React</h1>
      </header>
      <p className="App-intro">
        To get started, edit
        {' '}
        <code>src/App.js</code>
        {' '}
and save to reload.
      </p>
    </div>
  );
}

export default App;
```

`and save to reload.` line jumps to beginning of the line. But it should be indented same level as it's above line.

I've installed only `Prettier` v1.6.1 plugin, no other plugins.
VScode version: `1.26.0` and `1.26.0-insider`

Changing file type into `javascriptreact` doesn't help.

**Comment by CiGit** [comment]
Have you prettier installed in your project, this output is from an old prettier I think

**Comment by delgermurun** [comment]
@CiGit Yes I can. Can you help me on how and what to debug exactly? Thanks.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
