### ISSUE TITLE
prettier.parser

### ISSUE THREAD

**Issue by svipben** [prettier/prettier-vscode#553]
Hi, there are way much more parsers: https://prettier.io/docs/en/options.html#parser. In config I see only `flow | babylon`. We definitely need `typescript` parser. Or it's changed automatically according to file type?

**Comment by CiGit** [comment]
Based on file's `languageid` this extension infers the correct parser. This is only used for javascript files as mentioned in the doc: 
> prettier.parser (default: 'babylon') - JavaScript only
