### ISSUE TITLE
Allow markdown(*.md) file to use editor.action.formatSelection

### ISSUE THREAD

**Issue by ZSkycat** [prettier/prettier-vscode#555]
The default formatting will generate a lot of blank lines, very ugly.
But the formatting of the table is very useful. If can format the selected text, it would be great.

**Comment by ZSkycat** [comment]
add `markdown` in https://github.com/prettier/prettier-vscode/blob/master/src/utils.ts#L42-L51
invalid formatting

The bug has been found
https://github.com/prettier/prettier/issues/5008

**Comment by CiGit** [comment]
This needs to be implemented in prettier first.
