### ISSUE TITLE
Keyboard shortcut doesn't work on TS files: ESlint fix failed due to an eslint error

### ISSUE THREAD

**Issue by kennethvl** [prettier/prettier-vscode#556]
I currently code in TypeScript on VS Code in Mac, but whenever I'm trying to format the whole/selected .tsx or .ts files using the shortcut Option + Shift + F it won't formatted automatically and there's an error:

```
console.ts:136 [Extension Host] prettier-eslint [ERROR]: eslint fix failed due to an eslint error
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:209
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
```

The prettier will work well if I'm using the lamp icon that appears beside the line that has an error or if I'm using the keyboard shortcut on the .js files.

Please help, thanks!

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
