### ISSUE TITLE
prettier.semi not adding any semicolons to the end of a line

### ISSUE THREAD

**Issue by stevenmchoi** [prettier/prettier-vscode#562]
I have in VSCode `"prettier.semi": true`, `"prettier.eslintIntegration": true`, and `"editor.formatOnSave": true` (as well as "paste" and "type"), so I would expect Prettier to add semicolons to the end of lines whenever appropriate. However, since installing Prettier, I haven't seen it add any semicolons, which is strange because it seems to be formatting everything else correctly.

**Input:**
```jsx
import randCommonWord from "../components/text_field/rand_common_word"
import renderText from "../components/text_field/render_text"
import sleep from './sleep'

...

renderText()
```

**Output:**
```jsx
// No change
import randCommonWord from "../components/text_field/rand_common_word"
import renderText from "../components/text_field/render_text"
import sleep from './sleep'

...

renderText()
```

**Expected behavior:**
```jsx
import randCommonWord from "../components/text_field/rand_common_word";
import renderText from "../components/text_field/render_text";
import sleep from './sleep';

...

renderText();
```

Not sure what's with my set up that's causing this.

**Comment by stevenmchoi** [comment]
Reposted from https://github.com/prettier/prettier/issues/5002

**Comment by CiGit** [comment]
To test:
disable eslintIntegration.
if it doesn't fail anymore, investigate your eslint config.

**Comment by stevenmchoi** [comment]
@CiGit Hi, disabling eslintIntegration works, but now I think there was a different problem that caused me a lot of difficulty.

When I first disabled eslintIntegration, it didn't work, so I tried closing the folder and quitting and restarting VSCode. Somewhere in the middle, when I loaded the file, it automatically added the semicolons, but not when I saved. Now, it adds the semicolon whenever I save, so that's great.

Then I decided to not use eslintIntegration, since my global eslint seems to be causing some issues, so I tried changing some prettier settings:

```
{
    "prettier.useTabs": true,
    "prettier.tabWidth": 4,
}
```

Now, prettier has stopped adding semicolons on save (only when I load VSCode with the project folder), and it uses tabs but still has a `tabWidth` of 2, not 4.

Would I be right in guessing that this means that there's an issue with VSCode reading my User Settings or with `"editor.formatOnSave": true,`?

Much appreciated!

**Comment by CiGit** [comment]
an editorconfig file ? We read from it :-)

**Comment by stevenmchoi** [comment]
@CiGit ? Sorry, I'm not sure what you mean.

**Comment by stevenmchoi** [comment]
@CiGit, no, but the default settings suddenly decided to start working again, for some unexplainable reason. Which describes a good percentage of bugs that happen around me X(

Thanks, though!
