### ISSUE TITLE
Inconsistent formatting of package.json compared to other JSON files

### ISSUE THREAD

**Issue by geekox86** [prettier/prettier-vscode#564]
Greetings awesome Prettier team,

Thank you for your wonderful library and VS Code plugin.

I noticed that when I use Prettier Playground to format my package.json, I get this correct formatting:
```
{
  "name": "vue-apollographql",
  "version": "1.0.0",
  "description": "Vue integration with Apollo GraphQL library",
  "main": "builds/index.js",
  "author": "geekox86",
  "scripts": {
    "test": "jest --watch",
    "build": "webpack --config wpconfig.ts"
  },
  "license": "MIT",
  "dependencies": {
    "apollo-client": "^2.4.0",
    "graphql": "^0.13.2"
  },
  "prettier": {
    "semi": false,
    "singleQuote": true
  },
  "jest": {
    "collectCoverage": true,
    "coverageReporters": ["text"],
    "moduleFileExtensions": ["js", "jsx", "ts", "tsx"],
    "testEnvironment": "node",
    "testMatch": ["**/?(*.)test.ts?(x)"],
    "transform": {
      "\\.tsx?$": "ts-jest"
    }
  }
}

```

However, when I use the VS Code plugin to format the same file, I get this incorrect formatting:
```
{
  "name": "vue-apollographql",
  "version": "1.0.0",
  "description": "Vue integration with Apollo GraphQL library",
  "main": "builds/index.js",
  "author": "geekox86",
  "scripts": {
    "test": "jest --watch",
    "build": "webpack --config wpconfig.ts"
  },
  "license": "MIT",
  "dependencies": {
    "apollo-client": "^2.4.0",
    "graphql": "^0.13.2"
  },
  "prettier": {
    "semi": false,
    "singleQuote": true
  },
  "jest": {
    "collectCoverage": true,
    "coverageReporters": [
      "text"
    ],
    "moduleFileExtensions": [
      "js",
      "jsx",
      "ts",
      "tsx"
    ],
    "testEnvironment": "node",
    "testMatch": [
      "**/?(*.)test.ts?(x)"
    ],
    "transform": {
      "\\.tsx?$": "ts-jest"
    }
  }
}

```

Expected formatting:
The jest configuration at the end should be similar to the output formatting from the Prettier Playground.

Versions:
```
prettier 1.14.2
Prettier - Code formatter 1.6.1
VS Code 1.27.0-insider
```

Thank you!

**Comment by CiGit** [comment]
The parser used for package.json files is `json-stringify`
If you use the cli `prettier package.json` it would output the same you see with the extension.
See [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEm0igQwFs5ckcQA3AVzgFp8AHCAG2YgHMAnRgCwEdmuADQZsuCnE4BnAJbRS5AIwA6AAxrho8gBM4UsJxkMYcqAtwA1Gphmw4XfCeiYA7jJg9MAQSasImAHFuBh4ARQAZTGYZACNuTgBPTSxyQnxbcxAYqhlmbSkAeltdAA9lACspZLEQfCoPCE5M9jg4AGsIEoAOADZq8n1DYyrkTHQUmvgpGEzyvRhMWloXRzAefprs3O1MlzgYhnwwNsXaSCgAMxl2VwZzq-ZlGBGtAF8RFNxosAQpElHcABZACSABV+rhdAwELooGAZHoFONsDVGCw2GdoggZgCQAA9ABMygALBoQB8UeQHCEBJk8epFABmZQE3BvCnkBicOAwEySJFaGp-QgyBQXfDMP4coW2djMOChKgQeAKGCcGjsrS4ObTAUTciQVhwMAwADCEAk3BaqvVcGlBotknwLQASnAmJx4NIFABtXDwEo4gC69twhAg2io8oAYrk4ABRQO-UwjMh+kCVYTkSolLP+kZCcjPXMgEOCovzeNQCgyTjQYiwTJQCP-UMgKYwQGrdajdMAKj7BQA-AAKPvKACUHaeUlHJQnuDL+v93CgUgujUIespNTQe7QM5KQ4AJJlnrQdTjy683hhXuSQBBjCnkKB8Jw6y4AArv37IWoUBAMjaA+cRHG0PIAMqHPCUDsMgao0EIIC2H8npflaaTIOKkp2hmUglAAQtwxxQUQcDhLYcDYRKUogIc0iSP+lTQLQ0yGHBMgXAkD5crYMAAOrAR4yBdKoyFchAfwCcE-5cnokgSA+3J8Dk3IYc6WFIDhdHCjICG2shshwfKirKtR2m0XhMD4DEQnaCJSAEsharpNEcHmoQWl4NA1HIVQfygrZUg0bhryvEAA)
