### ISSUE TITLE
Create option to disable multiline formatting 

### ISSUE THREAD

**Issue by dnistreanu** [prettier/prettier-vscode#565]
When prettier is formatting javaScript, it tends to separate for loops, arrays and others into multiple lines. This makes code less readable for me and members of my team and I want to disable/remove it. Please make this possible.

**Comment by CiGit** [comment]
This extension gives you the output from prettier and as such provides no more formatting options than prettier's.
Such issue should go in https://github.com/prettier/prettier/issues. There is nothing we will/can do about that in this extension.
There are - most certainly - issues opened (or already closed) about that.
