### ISSUE TITLE
Only formatting TypeScript files...

### ISSUE THREAD

**Issue by mikeerickson** [prettier/prettier-vscode#567]
I have an issue where Format Document only formats TypeScript (.ts) files, it ignores JavaScript files (.js).   Now, I could have SWORN this has worked in the past, not quite sure what is happening. 

I installed the latest Insiders version today, curious if that is the culprit? Is there something that should be defined in `.prettierrc` file to determine which files should be formatted.

If I format the document manually (Command-Shift-P -> Format Document) it will format correctly, however, when I save the file it formats something different (in my case, it reverts double quotes to single quotes)

What are the configuration rules, etc. which are used by Format Document?  It is always confusing to me

![image](https://user-images.githubusercontent.com/183153/44737455-e3ec3000-aaa6-11e8-8210-1859cda9ea94.png)

**Comment by CiGit** [comment]
I'm on 1.27 now (not insider) and haven't any trouble.

Settings are https://github.com/prettier/prettier-vscode#prettiers-settings

You would need to debug it.

**Comment by methodbox** [comment]
I am seeing this issue still. I'm not sure if it's because the JS files are generated by the TypeScript compiler, but it doesn't format those files according to the Prettier rules, until I either save or "Format Document".

As an example, the tab width is always 4 instead of 2, which is a "feature" of the TS compiler.

**Comment by CiGit** [comment]
@methodbox prettier doesn't touch generated files if you don't call prettier on them. 

Closing as OP seems solved
