### ISSUE TITLE
prettier.tabWidth doesn't work in .js files

### ISSUE THREAD

**Issue by DTX-92** [prettier/prettier-vscode#568]
In settings i have:
`"prettier.tabWidth": 3`
But it doesn't work.
However if i change spaces from the bottom bat in file, "Format Selection" will use it, but not "Format Document"
![1](https://user-images.githubusercontent.com/20479161/44798549-77625580-abba-11e8-8255-b1e98ba6f95d.gif)

**Comment by DTX-92** [comment]
@CiGit i tried disabling all other extensions, but it didnt help.
![15](https://user-images.githubusercontent.com/20479161/45551724-7591c680-b837-11e8-8872-f1847ab53003.gif)

**Comment by DTX-92** [comment]
Okay, i noticed weird thing. It works with "User settings", but not with "Workspace setting" js files:
![16](https://user-images.githubusercontent.com/20479161/45552142-a6263000-b838-11e8-9f56-56ed7dbda49c.gif)

**Comment by iChard** [comment]
@DTX-92 How did you fix it?I had the same problem

**Comment by DTX-92** [comment]
@iChard I deleted .editorconfig file _-
