### ISSUE TITLE
Create option to ignore files (like webpack.config.js)

### ISSUE THREAD

**Issue by raphi011** [prettier/prettier-vscode#57]
Hi! I'd love to have an option to include / exclude paths or files so that my webpack.config.js doesn't get ruined everytime I save the file

**Comment by esbenp** [comment]
Seems like a good idea to me. Would you dare to take a crack at a PR?

**Comment by raphi011** [comment]
yea sure, i'll try to get to it this week :)

**Comment by CiGit** [comment]
If you find your webpack config getting ugly maybe the best thing to do would be to open an issue on prettier.
I'm not against that option even if I personally see no use case currently. You can still put a `// prettier-ignore` on a block you don't want prettier to modify.

If this is tackled, I think it shouldn't break EVERY formatter, this way you can still format your ignored files with the default formatter (or any other formatter) to have it indented correctly.

**Comment by raphi011** [comment]
I went to the prettier issues and someone asked a similiar question [here](https://github.com/prettier/prettier/issues/787). 

They said we should create an option for the extensions which use prettier, not for prettier itself.

I agree with not breaking other formatters!

**Comment by CiGit** [comment]
I was mentioning [`//prettier-ignore`](https://github.com/prettier/prettier#excluding-code-from-formatting) which is not for an entire file and thus doesn't let us pass it to the next formatter (I think).

And I've seen a use case: not all files are processed the same way, build files vs babel files.
For that case I think the right solution would be to provide different options (`trailing-comma` I can think of) but that's an other issue :-)

**Comment by kengoldfarb** [comment]
Any movement on this issue lately?  It'd be a really helpful feature to have.

**Comment by CiGit** [comment]
What's your use case ? 
- Ignore files completely
- Having different config per language
- Having different config per files (same language)
- Other?

**Comment by kengoldfarb** [comment]
@CiGit ignoring files completely.  Specifically, I'm seeing prettier destroy my flow-type module definitions.  Temporarily turning off format on save or putting in a bunch of ```// prettier-ignore``` comments is a workaround but not ideal.

**Comment by CiGit** [comment]
Would prettier/prettier#2195 fit your needs? I won't duplicate a feature which may be in prettier ;-)

**Comment by kengoldfarb** [comment]
Yes, if they actually implement it.  However, https://github.com/prettier/prettier/issues/1428 and https://github.com/prettier/prettier/issues/787 makes it look like it hasn't been a priority.

**Comment by mgutz** [comment]
@CiGit Prettier causes errors when saving vscode's settings.json. See [Microsoft/vscode#29701](https://github.com/Microsoft/vscode/issues/29701). Obviously it's not valid JSON since it has comments but it's how the configuration is. Would be nice to be able to ignore that file.

**Comment by CiGit** [comment]
Hum ... right... 
As a current work around:
- Disable formatOnSave
- set `prettier.jsonEnable:[]` (ie disable 'json' formatting)
- Remove `// Place your settings in this file to overwrite the default settings`. But it still fails with a trailing comment.

**Comment by HelloDeadline** [comment]
I have the same issue with webpack.config.js - I don't want to run prettier for this file.
I tried to add  webpack.config.js in  `.eslitignore` and  in `eslintIgnore` in `package.json`. 
No luck. 

It would be nice if Prettier could take `.eslitignore` into account. 

I also tried to use `overrides` 
```json
{
"overrides": [{
    "files": ["webpack.config.js"],
    "rules": {
      "comma-dangle": ["error", "never"]
    }
  }]
}
```
But it didn't work for me: both prettier and eslint plugin for vscode ignore that. 

Am I doing smth wrong?

**Comment by HelloDeadline** [comment]
My project's simplified structure:

```
[dev]
[test]
webpack.config
```

What I ended up is to move my eslint config into a folder and create multiple `.eslintrc` files that extend from base config.

```
[eslint-config]
    .eslintrc  // Actual configuration
[dev]
    .eslintrc 
        { "extends": "../eslint-config/.eslintrc" }
[test]
    .eslintrc 
        { "extends": "../eslint-config/.eslintrc" }
webpack.config
.eslintrc
     { "extends": "./eslint-config/.eslintrc",  "rules": {  "comma-dangle": ["error", "never"] } }
```
Not clean enough, but at least works.

**Comment by ButuzGOL** [comment]
vote for this feature because i have three projects in one env and only one is using Prettier and it makes big pain to enable/disable formatOnSave

**Comment by CiGit** [comment]
Will a `.prettierignore` fit your needs? 
https://github.com/prettier/prettier/pull/2412

**Comment by ButuzGOL** [comment]
yes but as understand this feature is not released yet

**Comment by CiGit** [comment]
Not yet, maybe in next prettier release (it has been merged) :-)
While we are at it:
 - Prevent formatting only on `formatOnSave`
 - Prevent formatting always (formatOnSave, User wants to format)

Arguments so far:
### Prevent on save
@azz 
> Its bad UX to format something on save that should be formatted. When it is an explicit action (like alt-shift-f) the UX is ok.

Certainly was *should **NOT** be formatted*
### Prevent always
@cigit 
> If you ignore it, means you don't want it to be formatted, ever. We will prevent a mistake.


### Side note
This is not an argument but we can't implement to prevent only on save without changing the complete architecture. VSCode's API doesn't give us any reason on why format was called (maybe I've not found)

**Comment by azz** [comment]
To be clear, I wasn't arguing _for_ prevent only on save, I was explaining why it is something people will tend to expect from the extension.

**Comment by CiGit** [comment]
@azz Got it :-) and you are right. 
In the end it will still do something: Log a message (in any case).

**Comment by joaovieira** [comment]
Can't wait for this. Tired of unnecessary git diffs in `package.json` as `npm` also formats it on each install.

**Comment by CiGit** [comment]
We still have to do it. @joaovieira volunteer ? :smiley: #198

**Comment by jantimon** [comment]
Could we just ignore all files from `.gitignore`? (might be a setting)

**Comment by CiGit** [comment]
It should once implemented. I see a new settings called `ignorePath` which defaults to _.prettierignore_ syntaxe is the same as a the one used in _gitignore_

**Comment by jackson-sandland** [comment]
This would be a great feature. Why would we want to prettify anything in .gitignore - especially node_modules.
