### ISSUE TITLE
.prettierrc ignored if empty

### ISSUE THREAD

**Issue by kirkstrobeck** [prettier/prettier-vscode#570]
I want to use this preference

```json
  // Require a 'prettierconfig' to format
  "prettier.requireConfig": true,
```

- However, my project uses all prettier defaults, so nothing should be specified and the file. `.prettierrc` should be empty.

- In my local test, the `.prettierrc` ignored and Prettier was disabled until I added content.

Request: Honor `.prettierrc` file presence as enough to enable Prettier

**Comment by CiGit** [comment]
Seems I've already seen this. Cosmiconfig is given us the config. You need to put at lease `{}` inside the file for it to be defined

**Comment by kirkstrobeck** [comment]
I tried that and it still didn’t see the file. Perhaps I did something else wrong.
