### ISSUE TITLE
Usage with mdx in vscode

### ISSUE THREAD

**Issue by tobiastimm** [prettier/prettier-vscode#571]
I saw that prettier is supporting `mdx`. 
Do I need to configure `vscode` in any way to format my mdx files? 

At the moment the prettier statusbar button is not visible in `mdx` files.

I get the error `There is no document formatter for 'mdx'-files installed.`

**Comment by CiGit** [comment]
Not yet published. It should be automatic once we bundle a version which has this support

**Comment by johncmunson** [comment]
I'm running into this same issue when trying to run the npm script below. Any idea this will land in an official release?

`"format": "prettier --write '{,!(node_modules|.cache|public)/**/}*.{js,json,css,md,mdx}'"`

**Comment by johncmunson** [comment]
Sorry, looks like I may have posted in the wrong repo? So is it `prettier` itself that is waiting for this update, or just `prettier-vscode`?

**Comment by RobinMalfait** [comment]
@johncmunson if you have the newest version installed locally in your project that supports mdx than it is prettier. However this project prettier-vscode also comes with a bundled version for cases if you don't have the prettier installed locally in your project. We should also update that one once mdx is available in prettier.

Note: I don't the status of mdx in prettier.

**Comment by dotlouis** [comment]
For reference, prettier has merged a PR for MDX support. It should land in 1.15
https://github.com/prettier/prettier/pull/4975

**Comment by CiGit** [comment]
It is now live
