### ISSUE TITLE
Setting for wrapping params to multiple lines

### ISSUE THREAD

**Issue by Albyzai** [prettier/prettier-vscode#574]
Hi,

Prettier seems to miss a setting for when it should wrap the parameters of a function.
I have attached 2 images, the first one is the desired output. And the second is the way it formats it when saving the file.

The format seems to be triggered by the length of the individual parameters. 

![How i want it](https://puu.sh/BnWwv/380ca7f3ff.png)

![How it formats](https://puu.sh/BnWwU/6040b15fee.png)

**Comment by nickcabral** [comment]
The line in question has 82 characters. Prettier's default printWidth is configured to 80, meaning it  will wrap any line that goes over that (I think it's actually a bit more complicated than that; seems like it tries to wrap long param lists that come close to that value, even if they aren't over it).

Add a `.prettierrc` file to the root of your app with the following contents and see if that helps:
``` json
{
  "printWidth": 100
}
```

**Comment by nickcabral** [comment]
Also, you can check out the other available options you can set for prettier [on this page](https://prettier.io/docs/en/options.html).

**Comment by CiGit** [comment]
@nickcabral explained it.

**Comment by webCoderJ** [comment]
![image](https://user-images.githubusercontent.com/19652730/50465739-23367900-09d4-11e9-81fa-60b426626725.png)

![image](https://user-images.githubusercontent.com/19652730/50465770-5547db00-09d4-11e9-9ff5-dc483e440908.png)


I switch the `Prinit Width` to 200, it seems not work。I do hate this style... Oh my goddess!!!
