### ISSUE TITLE
When "prettier" is in a package.json but not installed it fails

### ISSUE THREAD

**Issue by peterbe** [prettier/prettier-vscode#577]
Steps to reproduce:

```
~/tmp/sampleproject
▶ npm install --dev prettier
npm WARN package.json sampleproject@1.0.0 No description
npm WARN package.json sampleproject@1.0.0 No repository field.
npm WARN package.json sampleproject@1.0.0 No README data
prettier@1.14.2 node_modules/prettier

~/tmp/sampleproject
▶ ./node_modules/.bin/prettier --version
1.14.2

~/tmp/sampleproject
▶ rm -fr node_modules

~/tmp/sampleproject                                                                                                                                                                                               
▶ mkdir src

~/tmp/sampleproject
▶ touch src/Foo.js

~/tmp/sampleproject
▶ code .
```

Error:
```
ERR Cannot find module 'prettier' from '/Users/peterbe/tmp/sampleproject/package.json': Error: Cannot find module 'prettier' from '/Users/peterbe/tmp/sampleproject/package.json'
```

<img width="1307" alt="screen shot 2018-09-05 at 9 38 25 am" src="https://user-images.githubusercontent.com/26739/45096857-803db480-b0ef-11e8-9f2f-d09a5ba1e2d1.png">

**Comment by peterbe** [comment]
The reasons this problem comes up for me is that I run my node code inside a Docker container and since I volume mount the `./src` directory I set `NODE_PATH=/tmp` inside the Docker container so that `node_modules` is installed in `/tmp`. 

One solution to this problem would be an option to set the path to the `prettier` executable. Then I could use `/Users/peterbe/.config/yarn/global/node_modules/.bin/prettier` instead.

**Comment by CiGit** [comment]
Seems this is something we will have to do. At least to support plugins.

**Comment by xeoneux** [comment]
I just spent 2 hours figuring out why prettier was not working for my repo.

It would be useful to display a notification that the local prettier package was not installed and then ask the user to either continue with the global installation or advice to manually install the packages.

**Comment by betaorbust** [comment]
Just ran into this as well. Working on a shared Mac/Windows host and couldn't figure out why installing prettier locally broke prettier. 
A setting to allow direct selection of which instance of prettier to use would be fantastic 👍

**Comment by giotiskl** [comment]
+1 for this

**Comment by eszthoff** [comment]
+1 for this
I spent a lot of time trying to figure it out. Once prettier was enabled all formatting of file stopped functioning without any warnings. I guess it cannot find the module because I'm running the code in a docker container.

**Comment by anisjonischkeit** [comment]
I have forked this repo and added a work around that makes it so if it can't find a local prettier, it will use whatever prettier you have globally installed: https://github.com/anisjonischkeit/prettier-vscode/releases

**Comment by jole78** [comment]
I also have this problem with running my app inside docker. I develop it locally but almost never run yarn install on my host. EsLint works with globally installed version so it would be nice if prettier did to. Now we have to document this for new developers instead.

**Comment by ntotten** [comment]
In version 3.0 we now show an error message if this happens. You can test the preview version here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
