### ISSUE TITLE
Prettier suddenly stopped formatting line length

### ISSUE THREAD

**Issue by cmcnicholas** [prettier/prettier-vscode#579]
I've been using this plugin no issues for a few months now. Suddenly it has stopped formatting line length e.g.

![image](https://user-images.githubusercontent.com/41394833/45116458-ad6b8080-b14a-11e8-8544-3450f8b4ee68.png)

I have disabled all other extensions and I get the same behaviour, no formatting of long lines to be broken onto new lines.

My `package.json` includes:

```
"prettier": {
  "singleQuote": true,
  "trailingComma": "all",
  "arrowParens": "always"
}
```

My workspace settings are:

```
{
    "editor.rulers": [
        120
    ],
    "editor.formatOnSave": true,
    "files.trimTrailingWhitespace": true,
    "prettier.singleQuote": true,
    "prettier.trailingComma": "all",
    "prettier.arrowParens": "always",
}
```

My user settings are: 

```
{
  "editor.rulers": [
    120
  ],
  "editor.formatOnSave": true,
  "files.trimTrailingWhitespace": true,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "prettier.arrowParens": "always"
}
```

**Comment by sebastos01** [comment]
I have the same issue for Visual Studio Code version 1.26.1 and up. Version 1.25.1 works fine.

**Comment by CiGit** [comment]
I don't think prettier is wrapping comments... (ASCII art)

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
