### ISSUE TITLE
Incorrect formatting for .cshtml files, razor syntax

### ISSUE THREAD

**Issue by vishnu4** [prettier/prettier-vscode#580]
i have a .cshtml that is built like the following:

@using Kendo.Mvc.UI;
@model CoBRAMVC4Portal.Areas.Admin.Models.UserModel
@{
    ViewBag.Title = CoBRALocalization.MVC.RootResource.CreateUserTitle;
    bool isDataAdmin = false;
    if (System.Web.HttpContext.Current.User.IsInRole("DataAdmin"))
    {
        isDataAdmin = true;
    }
}
@using (Html.BeginForm("Create", "User", FormMethod.Post, new { enctype = "multipart/form-data", autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.RedirectToSubOrg)
    @Html.ValidationSummary(false, CoBRALocalization.MVC.RootResource.CreateUserTitle + " " + CoBRALocalization.MVC.RootResource.UnsuccessfulText)
    <span>test</span>
}
@section Scripts {
    <script src="@Url.Tag("~/build/webpack/test.js")"></script>
}

but when i save the file, prettier automatically formats it to be:

@using Kendo.Mvc.UI; @model CoBRAMVC4Portal.Areas.Admin.Models.UserModel @{ ViewBag.Title = CoBRALocalization.MVC.RootResource.CreateUserTitle; bool isDataAdmin = false; if (System.Web.HttpContext.Current.User.IsInRole("DataAdmin")) { isDataAdmin = true;
} } @using (Html.BeginForm("Create", "User", FormMethod.Post, new { enctype = "multipart/form-data", autocomplete = "off" })) { @Html.AntiForgeryToken() @Html.HiddenFor(m => m.RedirectToSubOrg) @Html.ValidationSummary(false, CoBRALocalization.MVC.RootResource.CreateUserTitle
+ " " + CoBRALocalization.MVC.RootResource.UnsuccessfulText)
<span>test</span> } @section Scripts {
<script src="@Url.Tag(" ~/build/webpack/test.js ")"></script>
}

which actually doesn't work at all.  If i try to load the page it's actually broken.  Is cshtml supported?  Or should it be?

**Comment by CiGit** [comment]
It isn't supported. Prettier shouldn't even be enabled on those files. Are you sure this is this extension formatting ?

**Comment by vishnu4** [comment]
You're right, i apologize.  the issue was with https://marketplace.visualstudio.com/items?itemName=Kookweb.razor-formatter instead
