### ISSUE TITLE
Prettier adding multiple blank lines when formatting

### ISSUE THREAD

**Issue by Talhah** [prettier/prettier-vscode#581]
Using VSCode Version 1.27.1 - macOS Mojave

Prettier is adding multiple blank lines each time an html document is formatted.

**Comment by khaeransori** [comment]
+1

**Comment by CiGit** [comment]
HTML is not supported by prettier (yet). This extension is not enabled on HTML files.
Other formatter?

**Comment by Talhah** [comment]
I am closing this issue as I was able to fix it by deleting VSCode completely and re-install installing it.
