### ISSUE TITLE
ESLint integration: `.eslintignore` is not honoured

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-vscode#582]
When I use the prettier-eslint CLI or via the Node API, I can see that when a file is ignored by ESLint via `.eslintignore`, it gets formatted with Prettier but ESLint auto fixes do not apply afterwards. This is as expected.

However, when I try the same via this extension, the ESLint auto fixes are applied. This is not expected.

I believe this might be related to the fact that the prettier-eslint Node module is the one bundled with the package: when I invoke prettier-eslint from inside the folder containing the `.eslintignore`, it is honoured, but I invoke it from a folder outside (such as is the case with this extension), it is not honoured.

This might be an upstream bug, but filing here for reference. What do you think?

**Comment by john-griffin** [comment]
Just hit this too.

**Comment by CiGit** [comment]
How are eslintignore resolved?

**Comment by OliverJAsh** [comment]
> How are eslintignore resolved?

Presumably ESLint does this? I don't know though.

Can we re-open this issue?

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
