### ISSUE TITLE
Truncation of PHPDoc blocks

### ISSUE THREAD

**Issue by mynetx** [prettier/prettier-vscode#583]
When PHP files are formatted, PHPDoc blocks are truncated.
Please see this video for how the line is cropped upon multiple saves.

![bildschirmaufnahme 2018-09-15 um 12 13 35](https://user-images.githubusercontent.com/6348321/45585430-46855e80-b8e4-11e8-9126-3e526688ab12.gif)

**Comment by CiGit** [comment]
This extension is not formatting PHP files. 
Disable prettier and see if it still happens.
