### ISSUE TITLE
couldn't resolve babel-parser

### ISSUE THREAD

**Issue by lokesh1729** [prettier/prettier-vscode#585]
Hi,

I am on a latest version of vscode. prettier seems not working. I have seen the debug info and found `couldn't resolve babel-parser`. Here are my settings.

```
"prettier.eslintIntegration": false,
 "prettier.singleQuote": true,
 "prettier.tabWidth": 4,
 "editor.formatOnSave": true,
 "editor.formatOnPaste": true,
 "prettier.stylelintIntegration": true,
 "prettier.disableLanguages": [],
```

Even installed parser globally with `npm install @babel/parser -g` didn't work.

**Comment by CiGit** [comment]
Seems a missing dependency somewhere. Have you prettier installed in your dependencies? Try reinstalling it. And try reinstalling this extension.

**Comment by lokesh1729** [comment]
Hey @CiGit , I have installed ESLint and TSLint, then the extension started working. Are those dependencies for it ???
