### ISSUE TITLE
One line if else formatting, applied to some line, not in others

### ISSUE THREAD

**Issue by tanmoy12** [prettier/prettier-vscode#591]
Prettier seems to format one line into three but leaves the other lines intact. 

`data.name = !isEmpty(data.name) ? data.name : "";`
`data.email = !isEmpty(data.email) ? data.email : "";`
`data.passwordConfirm = !isEmpty(data.passwordConfirm)`
	`? data.passwordConfirm`
	`: "";`
`data.password = !isEmpty(data.password) ? data.password : "";`

**Comment by CiGit** [comment]
Your _breaking_ line is longer than 80 chars that's why prettier breaks it. That's how prettier works. You can tweak `printWidth` to have longer/shorter lines
