### ISSUE TITLE
Add `enable` switch, to be used in workspaces

### ISSUE THREAD

**Issue by garyking** [prettier/prettier-vscode#592]
Please add a `prettier.enable` switch, so we can disable this extension on a per-workspace basis. This would be particularly useful when we clone another repo, and we can't add `.prettierrc` or any other files to the repo, so then we can instead set `prettier.enable` to `false` for that workspace, without committing any extra files or settings to the repo.

I know there are other ways, like disabling format on save, or for certain file extensions, but those are still workarounds.

**Comment by CiGit** [comment]
You can disable prettier (and any other extension) on a per workspace basis. 
https://github.com/Microsoft/vscode/issues/15611
