### ISSUE TITLE
Wrongly formats JSON with array as root as JS

### ISSUE THREAD

**Issue by Kadrei** [prettier/prettier-vscode#593]
When having a file which vs code recognizes as JSON (e.g. `test.json`) which contains an array as the root entry it gets formatted as it would be a javascript file.

Input:
```
[{"test":"test"}]
```

Output:
```
;[{ test: 'test' }]
```

This does not seem to be a `prettier` issue because running `prettier` in the terminal on the `.json` file directly does not cause the issue.

Custom Settings:
`.prettierrc`:

```
arrowParens: always
singleQuote: true
parser: babylon
semi: false
printWidth: 100
trailingComma: es5
```

Relevant VS Code Settings:

```
  ...
  "prettier.parser": "babylon",
  "prettier.printWidth": 100,
  "prettier.semi": false,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "es5",  
  "eslint.autoFixOnSave": true,
  "prettier.eslintIntegration": true,
  ...
```

**Comment by CiGit** [comment]
Try removing "parser": "babylon" from your config file

**Comment by Kadrei** [comment]
Thank you that worked :)

**Comment by jbmusso** [comment]
Just got bitten by this, thanks for sharing a workaround.
Could anyone please share some insights on why this is happening? I though .json files would be rendered/prettified with JSON semantic, rather than JavaScript semantics, irrespective of the parser being used.
