### ISSUE TITLE
Setting the prettiet.printwidth property does not work

### ISSUE THREAD

**Issue by wanghaooo** [prettier/prettier-vscode#595]
I set the prettier.printWidth property to 500, but the line is still wrapped after formatting

<img width="548" alt="2018-10-04 10 21 01" src="https://user-images.githubusercontent.com/26863173/46480590-19153c00-c824-11e8-86ff-33030987fc99.png">
<img width="704" alt="2018-10-04 10 21 28" src="https://user-images.githubusercontent.com/26863173/46480607-216d7700-c824-11e8-91e9-9c3c86c5df95.png">

I want the block of code to be a little bit longer and I'm going to wrap it, but do I need to set some places besides the printwidth property?

**Comment by clamkong** [comment]
Seems like this issue happens for any config greater than 100 at least

**Comment by wanghaooo** [comment]
Some are not used to code blocks so short line breaks

**Comment by DavidHenri008** [comment]
In my case the wrap does not even work for small numbers. 
If I set 
`"printWidth": 70` 
with code like 
`const a = function afterAll(aaaaa, sssss, ddddd, fffff, ggggg, hhhhhh, jjjjj, kkkkk) {};`
it never wraps.

**Comment by CiGit** [comment]
I see a tslintIntegration. Do you have anything in your tslint config which could cause printWidth to be smaller?

**Comment by DavidHenri008** [comment]
@alvarodp which configuration do you put in .prettierrc to make it work (make it wraps the line after 140 char)?
Thanks

**Comment by alvarodp** [comment]
To make it work I must include the "prettier.printWidth" property.
`{
  "overrides": [
    {
      "files": "*.ts",
      "options": {
        "singleQuote": true,
        "prettier.printWidth": 140
      }
    }
  ]
}
`
But I want to set this property in the workspace, not in the .prettierrc.

**Comment by CiGit** [comment]
If you have a prettier config file, we discard settings from VSCode. That's why you see default values for them.
Explained: https://github.com/prettier/prettier-vscode#prettiers-settings.

You should set `printWidth`, not `prettier.printWidth` in your config file. Prefix are only for VSCode

**Comment by alvarodp** [comment]
True, without the prefix. So there's no "merge" with vscode settings and it's not planned.

**Comment by DavidHenri008** [comment]
Here is the content of my .prettierrc filr
```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "useTabs": false,
  "singleQuote": true,
  "printWidth": 100,
  "bracketSpacing": true,
}
```
My code never wraps when my line of code exceeds 100 characters.

**Comment by DavidHenri008** [comment]
@alvarodp Unfortunately adding your override suggestion to my .prettierrc did not work for me.
```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "useTabs": false,
  "singleQuote": true,
  "printWidth": 100,
  "bracketSpacing": true,
  "overrides": [
    {
      "files": "*.js*",
      "options": {
        "prettier.printWidth": 50
      }
    }
  ]
}
```

**Comment by CiGit** [comment]
@alvarodp It was the case in older versions of this extension but was removed to stay consistent with prettier cli and other IDE which do not read from VSCode's settings. No settings means default ones.

@DavidHenri008 it's `printWidth` not `prettier.printWidth`. Check if you don't have any other extension formatting your given file and your config file is above your file (file path wise)

**Comment by DavidHenri008** [comment]
@CiGit Unfortunately, even with `printWidth` only it still does not work. The syntax or the whole command id wrong.

**Comment by DavidHenri008** [comment]
@ph55 if it works for you, could you post your complete `.prettierrc` file content.

**Comment by jakeleventhal** [comment]
i have this same issue

**Comment by jabacchetta** [comment]
@CiGit I'm having the same issue as @DavidHenri008, where the formatting **does _not_ wrap at all.**

The issue appears to happen for me only **when the ESLint Integration option is enabled**. However, all of my other ESLint rules appear to be working fine. It just does not seem to recognize any sort of printWidth at all (i.e. [max-len rule](https://eslint.org/docs/rules/max-len)).

- My ESLint config extends `airbnb`, so it should infer 100.
- I also have the prettier option set in my `package.json`: `"printWidth": 100`
- And I have the prettier option set in my VSCode settings: `"prettier.printWidth": 100,`

**Comment by Mulperi** [comment]
> The issue appears to happen for me only **when the ESLint Integration option is enabled**.

THANK YOU. Unchecked ESLint integration from VSCode options -> Works again.

**Comment by guoshuai93** [comment]
如果项目集成 eslint 和 .prettier ，vscode 的配置同步改一下就好。
![image](https://user-images.githubusercontent.com/17941245/59586676-0a528900-9116-11e9-8636-a91b3d040243.png)

**Comment by rhefner** [comment]
I have been wondering why VSCode is doing one thing and prettier CLI another..  I would expect that the prettier config file (in my case, `.prettierrc.yaml`) would be the end-all.  Shouldn't the config override any workspace/user settings that are set?

I checked that I didn't have ESLint Integration set, but VSCode prettier was still wrapping a long line even though prettier CLI didn't.  My `.prettierrc.yaml` file:

`singleQuote: true
semi: true
tabWidth: 2
useTabs: false
proseWrap: 'never'
printWidth: 120
bracketSpacing: true
arrowParens: 'always'`

But ... I had my `"prettier.printWidth": 80` in my User settings.  I made it `120` to match the prettier config file and voila -- It now works.

And, I didn't have anything set (directly) for `printWidth` in my `tsconfig.json` file, but I am extending `["tslint:latest", "tslint-plugin-prettier", "tslint-config-prettier"]`

**Comment by ntotten** [comment]
This setting is being removed in version 3.0. Use prettier configuration files.

**Comment by blackmad** [comment]
I'm confused. I've been struggling to get this working for weeks. It seemed like vscode wasn't picking up my .prettierrc.

I just added "prettier.printWidth" to .vscode/settings.json and it finally worked correctly. Why isn't vscode picking up my .prettierrc?

here are my configs + their names and paths
![image](https://user-images.githubusercontent.com/445616/73546741-b928a880-440b-11ea-9644-11099529a96b.png)

**Comment by ntotten** [comment]
@blackmad Please post a new issue about the prettierrc and include the log data and ideally a sample project that can be used to reproduce the issue.
