### ISSUE TITLE
Three dashes for YAML directive being removed

### ISSUE THREAD

**Issue by mrlesmithjr** [prettier/prettier-vscode#596]
Is there currently a way to disable removing `---` in the start of YAML files? Whenever I save a YAML file they are removed from the beginning of the file and would be awesome if there was a way to stop that.

Any info would be much appreciated.

**Comment by j-f1** [comment]
Please check out https://github.com/prettier/prettier/issues/5013, which is the issue opened to discuss exactly this problem in the main Prettier repository.

**Comment by mrlesmithjr** [comment]
Perfect and thanks. I missed this during my search unfortunately.
