### ISSUE TITLE
An option to map other language ids to languages prettier knows?

### ISSUE THREAD

**Issue by coolreader18** [prettier/prettier-vscode#597]
For example, telling prettier that handlebars/liquid/other templating languages are just html, and can be formatted as such?

**Comment by CiGit** [comment]
HTML is now formatted by prettier. It should work on supported languages

**Comment by complyue** [comment]
Still got "There is no document formatter for 'jinja-html'-files installed." Any way to add jinja-html to prettier's supported languages list ?
