### ISSUE TITLE
Extension is broken in 1.29 Insiders

### ISSUE THREAD

**Issue by Nxt3** [prettier/prettier-vscode#598]
Formatting doesn't work, and prettier doesn't appear in the statusbar at the bottom.

<img width="1722" alt="screen shot 2018-10-08 at 4 07 26 pm" src="https://user-images.githubusercontent.com/2940826/46631089-5de6ee80-cb14-11e8-924a-33ab3359aa3c.png">

**Comment by finchlanger** [comment]
I have the same issue

**Comment by samdenty99** [comment]
Related issue: https://github.com/vuejs/vue-test-utils/issues/936

**Comment by Y2zz** [comment]
This problem has been found in 1.28

**Comment by Nxt3** [comment]
Seems this has been fixed in the 10/9 release of Insiders.
