### ISSUE TITLE
prettier-vscode does not resolve packages in Prettier configuration

### ISSUE THREAD

**Issue by astorije** [prettier/prettier-vscode#601]
Assuming the dependency `@my-org/my-prettier-config` exposes the following configuration through the `"main": "my-config.js"` field of its `package.json` file:

```js
module.exports = {
  singleQuote: true,
  trailingComma: 'all',
};
```

and that a project depending on `my-prettier-config` has the following `prettier.config.js` file:

```js
module.exports = require('@my-org/my-prettier-config');
```

`prettier-vscode` ignores the configuration (it does not resolve the package above) and prettifies using the defaults configuration.
If I replace the content of `prettier.config.js` with the JS object above, `prettier-vscode` prettifies correctly according to this configuration.

A shared configuration is what my company uses to make sure all repos have consistent styling, which is why we do it that way.
Thanks! :)

**Comment by CiGit** [comment]
Do you have the same problem if you use prettier CLI ?
from a directory outside your project ?

**Comment by astorije** [comment]
Hi @CiGit!

> Do you have the same problem if you use prettier CLI ?

Nope, CLI works fine. In fact, I was using the equivalent Atom package before switching to VS Code and it was working fine as well.

> from a directory outside your project ?

Can you clarify what you mean by this?

**Comment by CiGit** [comment]
I mean:
1. Install prettier somewhere (global). It should not have `@my-org/my-prettier-config` collocated
1. Go to any folder not in your project
1. run `prettier relative/path/to/file`
1. Observe

This nearly mimics what's happening inside the extension.

**Comment by nathanvale** [comment]
After using a globally installed prettier CLI on a file from inside and outside of my project directory the file is formatted just fine.

I don't think this issue should be closed as I am still faced with the problem on not being able to use shared  prettier.config.js files :(
