### ISSUE TITLE
broken tag

### ISSUE THREAD

**Issue by stevebao2000** [prettier/prettier-vscode#602]
index.js:
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';
import 'bootstrap/dist/css/bootstrap.css';
import Counters from './components/counters';

ReactDOM.render( < Counters / > , document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
=================================================
Please look at above document: <Counters /> became < Counters / >. It added extra space between / and >.

This problem happened only after I add another file: counters.jsx
import React, { Component } from "react";
import Counter from "./counter";

class Counters extends Component {
  state = {
      counters: [
          {id: 101, value: 4},
          {id: 102, value: 0},
          {id: 103, value: 0},
          {id: 104, value: 0}
      ]
  }; 
  render() {
    console.log("props", this.props);
    return (
      <div>
        {this.state.counters.map(counter => 
        <Counter key={counter.id} value={counter.value} id={counter.id}>
        </Counter>
        )}
      </div>
    );
  }
}

export default Counters;

**Comment by CiGit** [comment]
can you use code blocks ? 
from what I get you have an other formatter installed. beautify maybe ?

**Comment by mausworks** [comment]
Having similar problems #646,

Here's what OP said:

#### index.js

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';
import 'bootstrap/dist/css/bootstrap.css';
import Counters from './components/counters';

ReactDOM.render(< Counters />, document.getElementById('root'));
// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
```

Please look at above document: became `< Counters / >`. 
It added extra space between `/` and `>`.

This problem happened only after I add another file: 

#### counters.jsx

```jsx
import React, { Component } from "react";
import Counter from "./counter";

class Counters extends Component {
  state = {
    counters: [
      { id: 101, value: 4 },
      { id: 102, value: 0 },
      { id: 103, value: 0 },
      { id: 104, value: 0 }
    ]
  };
  render() {
    console.log("props", this.props);
    return (

      {
        this.state.counters.map(counter =>


)
      }

    );
  }
}
```

@stevebao2000, you can use four spaces, or surround your code with ` ``` ` if for code blocks, it's impossible to read what you wrote.

**Comment by oumaimaab** [comment]
> Having similar problems #646,
> 
> Here's what OP said:
> 
> > #### index.js
> > ```js-jsx
> > import React from 'react';
> > import ReactDOM from 'react-dom';
> > import './index.css';
> > import App from './App';
> > import * as serviceWorker from './serviceWorker';
> > import 'bootstrap/dist/css/bootstrap.css';
> > import Counters from './components/counters';
> > 
> > ReactDOM.render(< Counters />, document.getElementById('root'));
> > // If you want your app to work offline and load faster, you can change
> > // unregister() to register() below. Note this comes with some pitfalls.
> > // Learn more about service workers: http://bit.ly/CRA-PWA
> > serviceWorker.unregister();
> > ```
> > 
> > 
> > Please look at above document: became `< Counters / >`.
> > It added extra space between `/` and `>`.
> > This problem happened only after I add another file:
> > #### counters.jsx
> > ```js-jsx
> > import React, { Component } from "react";
> > import Counter from "./counter";
> > 
> > class Counters extends Component {
> >   state = {
> >     counters: [
> >       { id: 101, value: 4 },
> >       { id: 102, value: 0 },
> >       { id: 103, value: 0 },
> >       { id: 104, value: 0 }
> >     ]
> >   };
> >   render() {
> >     console.log("props", this.props);
> >     return (
> > 
> >       {
> >         this.state.counters.map(counter =>
> > 
> > 
> > )
> >       }
> > 
> >     );
> >   }
> > }
> > ```
> 
> @stevebao2000, you can use four spaces, or surround your code with `` ``` `` if for code blocks, it's impossible to read what you wrote.

I am having the same problem, please tell me what to do if fixed

**Comment by CiGit** [comment]
As of vscode 1.33 you can call `Format document with ...` and select prettier. see if this issue still persists. (I definitely think this is an other formatter)
