### ISSUE TITLE
Saving in sequence gives different output 

### ISSUE THREAD

**Issue by Avcajaraville** [prettier/prettier-vscode#604]
Im having issues using autosave for vue files. Im not quite sure if this is a bug or a feature.

So, given Im using prettier over a vue files, I get different output each time I hit the save key (without changes).

Here is a small video to demonstrate my issue:

![grabaciondepantalla201810](https://user-images.githubusercontent.com/2271201/47270415-b59d4500-d56b-11e8-8962-628a722a9772.gif)

On the video, Im saving three times till I get a "stable" output. When using prettier-eslint-cli I get a final nice output.

Im wondering if this a limit of one on the iterations over the code or an issue with vscode integration.

This is my settings.json on vscode:
```json
{
  "editor.formatOnSave": false,
  "javascript.format.enable": false,
  "eslint.autoFixOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.options": {
    "extensions": [ ".html", ".js", ".vue", ".jsx" ]
  },
  "eslint.validate": [
    { "language": "html", "autoFix": true },
    { "language": "vue", "autoFix": true },
    { "language": "javascript", "autoFix": true },
    { "language": "javascriptreact", "autoFix": true }
  ],
  "prettier.eslintIntegration": true,
  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatter.css": "prettier"
}
```

I have prettier vscode extension installed and enabled, along with eslint vscode extension.

**Comment by RobinMalfait** [comment]
You have `"eslint.autoFixOnSave": true,` and `"editor.formatOnSave": false,` so prettier and eslint are fighting to be the first. Use one of them on the correct files, not both.

**Comment by Avcajaraville** [comment]
Hey @RobinMalfait, thanks for your quick response, but I still dont understand... How can I do what you are suggesting ? Thanks !

**Comment by Avcajaraville** [comment]
Still struggling here, any help please ?

**Comment by RobinMalfait** [comment]
@Avcajaraville how do you use ESlint currently? Do you use the prettier eslint plugin?
If so, you can disable prettier integration.

If you don't, than you can disable
`"eslint.autoFixOnSave": true,` because `"prettier.eslintIntegration": true,` will already take care of it.

**Comment by Avcajaraville** [comment]
@RobinMalfait This way, for JS files all work nice, but I get no format on vue files.

This is my current configuration, and yes, Im using prettier plugin.

```
{
  "editor.formatOnSave": true,
  "eslint.autoFixOnSave": false,
  "javascript.format.enable": false,
  "eslint.alwaysShowStatus": true,
  "eslint.options": {
    "extensions": [".html", ".js", ".vue", ".jsx"]
  },
  "eslint.validate": [
    { "language": "html", "autoFix": true },
    { "language": "vue", "autoFix": true },
    { "language": "javascript", "autoFix": true },
    { "language": "javascriptreact", "autoFix": true }
  ],
  "prettier.eslintIntegration": true,
  "prettier.disableLanguages": [],
  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatter.css": "prettier"
}

```

**Comment by CiGit** [comment]
At the time this issue was opened, this extension did not format `<template>` section of vue files. 
Since 1.7: I think you have to disable vetur's formatter entirely (I don't know how to do it)
