### ISSUE TITLE
prettier behaves unexpectedly with unassigned array

### ISSUE THREAD

**Issue by kcouliba** [prettier/prettier-vscode#605]
When a line starts with an unassigned array, prettier behaves unexpectedly.

Not formatted
```javascript
[1, 2, 3].map(n => n)

console.log('hello world')
[(1, 2, 3)].map(n => n)

console.log('hello world')

[(1, 2, 3)].map(n => n)

function name() {
  [1, 2, 3].map(n => n)
}

```

After prettier formatting
```javascript
;[1, 2, 3].map(n => n)

console.log('hello world')[(1, 2, 3)].map(n => n)

console
  .log('hello world')

  [(1, 2, 3)].map(n => n)

function name() {
  ;[1, 2, 3].map(n => n)
}
```

**Comment by RobinMalfait** [comment]
That's because there is a bug in your code.

When you have this:

```js
console.log('hello world')

[1, 2, 3].map(n => n)
```

and you minify it, it becomes 

```js
console.log('hello world')[(1, 2, 3)].map(n => n)
```

Therefore prettier inserts a `;` to be safe.

Try the code snippets in devtools:

![](http://d.rbn.nu/dLj8af.png)

**Comment by kcouliba** [comment]
@RobinMalfait  Thanks for your reply
I understand the point with console.log, but what about unassigned array at line start ?
