### ISSUE TITLE
Option to let Prettier format files with additional extensions? (e.g. .eex)

### ISSUE THREAD

**Issue by x-ji** [prettier/prettier-vscode#606]
I need to format `.html.eex` files, which are view templates for Elixir. They are mostly HTML anyways, and if I manually change the language to HTML then run Prettier, the output seems fine.

Is there a way to let `.html.eex` be treated like `.html` files by Prettier? For now I've only seen options to **disable** formatting certain extensions/languages, but not enable formatting on additional extensions.

**Comment by x-ji** [comment]
Well it turns out that sometimes Prettier would result in some errors, though I'd still want the option to at least run Prettier on such files, and manually fix any potential errors later.

**Comment by CiGit** [comment]
At the time you opened this issue, html was not supported. 
Supported files are given to this extension be `supportInfo`.
You can map your *.html.eex files to html to have HTML support.

**Comment by jeff-kilbride** [comment]
I am also having issues with handlebars (*.hbs) files. I would like prettier to format them as html, but not change the language association in vscode due to syntax highlighting. I was hoping to use an override in my `.prettierrc.json` file like this:
```
  "overrides": [
    {
      "files": "*.hbs",
      "options": {
        "parser": "html"
      }
    }
  ]
```
But this doesn't work. Does this extension honor the "overrides" key in prettier config files?

I can get the formatting to work using the following in my vscode user settings:
```
  "files.associations": {
    "*.hbs": "html"
  },
```
But, again, this turns off my syntax highlighting for `{{variables}}`, `{{> blocks}}`, etc... It would be much nicer to do this through the prettier config, if possible.

**Comment by CiGit** [comment]
The extension doesn't read your config file(s) while it starts. This is the point where it enables formatting on known languages. Those languages are given to use through prettier's `getSupportInfo()`.

Allowing users to add a `languageId -> parser` mapping may also break some time like @x-ji mentioned. This breakage may be unnoticed. Thus, clearly not safe to do.
 
You can also quickly change current languageid with `ctrl+k ctrl+m` command.

**Comment by ntotten** [comment]
While it seems that you have made prettier mostly work with languages that aren't supported, I dont want to add this to the plugin. Prettier doesn't actually support handlebars (https://github.com/prettier/prettier/issues/5340) or elixer (https://github.com/prettier/prettier/issues/5286). 

Once prettier adds support for them, we will register those languages and formatting will work. Anything else will be a hack.

If you truely are writing something in a supported language, but using a different extension, the correct way to do this is to set the file association in vs code:

```
  "files.associations": {
    "*.my-html": "html"
  },
```

**Comment by maxwondercorn** [comment]
Handlebars can be formatted with prettier's built-in glimmer parser. There is an vscode addon specifically for handlebars that uses the glimmer parser. Works okay but doesn't read any prettier config files.

**Comment by nuno-bento-biglight** [comment]
> I am also having issues with handlebars (*.hbs) files. I would like prettier to format them as html, but not change the language association in vscode due to syntax highlighting. I was hoping to use an override in my `.prettierrc.json` file like this:
> 
> ```
>   "overrides": [
>     {
>       "files": "*.hbs",
>       "options": {
>         "parser": "html"
>       }
>     }
>   ]
> ```
> 
> But this doesn't work. Does this extension honor the "overrides" key in prettier config files?
> 
> I can get the formatting to work using the following in my vscode user settings:
> 
> ```
>   "files.associations": {
>     "*.hbs": "html"
>   },
> ```
> 
> But, again, this turns off my syntax highlighting for `{{variables}}`, `{{> blocks}}`, etc... It would be much nicer to do this through the prettier config, if possible.

Hi @jeff-kilbride I am having exactly the same problem. Did you find a solution in the end?
