### ISSUE TITLE
Alphabetization in typescript imports is completely broken

### ISSUE THREAD

**Issue by y-spreen** [prettier/prettier-vscode#611]
So with tslint support enabled, imports should be alphabetized by default. Here's an example:
![image](https://user-images.githubusercontent.com/12631527/47604871-6b024980-d9ff-11e8-8c8d-31e5ba4edf7a.png)
Explanation:
![image](https://user-images.githubusercontent.com/12631527/47604874-748bb180-d9ff-11e8-8e25-d7dc8e5f6596.png)

Now when I save (format on save enabled), prettier turns it into this:
![image](https://user-images.githubusercontent.com/12631527/47604878-89684500-d9ff-11e8-80de-c438943871f0.png)

This is really driving me crazy, since I don't have permission to change our tslint policy so thus I have to rearrange imports manually all the time. Please fix

**Comment by y-spreen** [comment]
Same thing for order of declaration like this:
![image](https://user-images.githubusercontent.com/12631527/47605045-c6353b80-da01-11e8-88e6-3d0381056cdb.png)

**Comment by CiGit** [comment]
#608 has something in common ?
