### ISSUE TITLE
files.autoSave and editor.formatOnSave

### ISSUE THREAD

**Issue by manu1222** [prettier/prettier-vscode#613]
> "files.autoSave": "afterDelay",
> "editor.formatOnSave": true,

These settings are not working together, i.e. file is being auto saved when I write my code but it's doesn't format it at the same time, I have to click ctrl + s in order to format, but this is contradictory to the setting "files.autoSave".

**Comment by CiGit** [comment]
>// Format a file on save. A formatter must be available, the file must not be auto-saved, and editor must not be shutting down.
  "editor.formatOnSave": false,

From settings. This is a limitation of VSCode
