### ISSUE TITLE
v1.6.1 does not use the prettier described in package.json devDependencies

### ISSUE THREAD

**Issue by kkpoon** [prettier/prettier-vscode#615]
`"prettier": "^1.14.3"` is installed by `npm install --save-dev prettier`

`.prettierrc.yaml` is located at the same directory with `package.json`

```yaml
trailingComma: "es5"
tabWidth: 4
```

While editing the `.js` files in vscode with prettier-vscode. It formats the code like this

```js
const {
    Hello
} = require("../hello");
```

It differs from the result by running `./node_modules/.bin/prettier --write src/**/*.js`.

```js
const { Hello } = require("../hello");
```

**Comment by CiGit** [comment]
Are you using eslint/tslint Integration ?

**Comment by kkpoon** [comment]
No. I am not.

**Comment by CiGit** [comment]
Seems this extension gets a `printWidth` < 38 somewhere.
can you try to debug it ? or share a repo we could checkout and reproduce this?

Quickly creating the setup you described gives me 
```js
const { Hello } = require("../hello");

```

**Comment by kkpoon** [comment]
I have created a repo with minimal setup.
https://github.com/kkpoon/demo-prettier

The problem occurs randomly. Sometime it format correctly as 
```const { Hello } = require("../hello");```.

I tried to exit, restart and format, it formatted to 
```
const {
    Hello
} = require("../hello");
```
again.
