### ISSUE TITLE
prettier-vscode conflict with prettier-cli over brackets on package.json

### ISSUE THREAD

**Issue by fillipvt** [prettier/prettier-vscode#616]
Hello

Got this weird problem. I implemented `prettier` but haven't been able to avoid the following conflict:

```bash
 FAIL   format  ./package.json
- Expected
+ Received

@@ -28,13 +28,11 @@
      "hooks": {
        "pre-commit": "lint-staged && npm run test:e2e:run"
      }
    },
    "lint-staged": {
-     "*.js": [
-       "jest --findRelatedTests"
-     ]
+     "*.js": ["jest --findRelatedTests"]
    },
    "repository": {
      "type": "git",
      "url": "git@gitlab.com:wagglio-group/wagglio.co/index.git"
    },
```

`prettier-vscode` puts the brackets on the same line and `prettier-cli` on different lines but I can't find the option to configure this on the prettier docs, is there even an option for this?

My `.prettierrc` config is:

```
{
  "arrowParens": "avoid",
  "bracketSpacing": false,
  "jsxBracketSameLine": false,
  "printWidth": 80,
  "proseWrap": "always",
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "useTabs": false
}
```

And I got VS Code to match this rules just in case there's a problem with priorities, but still this error occurs.

**Note**: I'm using `jest-runner-prettier` to detect these errors.

I would like to keep the `formatOnSave` for all files supported, including JSON, I'm just looking to avoid conflict on this specific rule.

Any help would be appreciated! Thanks for your time and thanks for reading.

**Comment by CiGit** [comment]
It should be on multiple lines.
What prettier version do you have in your project?
