### ISSUE TITLE
Upgrade prettier to 1.15

### ISSUE THREAD

**Issue by alexw10** [prettier/prettier-vscode#617]
Prettier version 1.15 was just released which supports HTML, Vue, and Angular now which are highly anticipated. Can we get the extension updated?

https://prettier.io/blog/2018/11/07/1.15.0.html

**Comment by choyongjoon** [comment]
And please add support for HTML, Vue, Angular and MDX.

**Comment by kachkaev** [comment]
It might be rational to solve the problem of adding new extensions by implanting plugin support in general: https://github.com/prettier/prettier-vscode/issues/395

Every language in Prettier comes from a plugin, no matter if it’s a core one or a third party. Prettier CLI can provide the list of plugins and thus file extensions via `--support-info`. There also exists `--file-info` to help editors know if a given file can be formatted.

Prettier for Atom has been supprting this approach for a few months, so they don’t need to do anything to let people start using 1.15 (if it is installed globally or as a project dependency).

**Comment by CalebKester** [comment]
https://github.com/prettier/prettier-vscode#prettier-resolution

It should use whatever you have installed in the project. However I'm still trying to get it to work in vuejs to format html. I'll let you know what i find.

**Comment by StevenSwitten** [comment]
1.7 is out

**Comment by vielhuber** [comment]
Hmm, I have "prettier-vscode" v. 1.7.2 installed and locally inside the project 1.15.2.

But when I open a *.vue file, the part on top does not get linted.

Am I'm doing something wrong?
