### ISSUE TITLE
rust code in markdown

### ISSUE THREAD

**Issue by zsytssk** [prettier/prettier-vscode#621]
prettier latest version  [1.7.0] format rust code in markdown, will add new line between each line, never stop!
```rs
let a = 1;
```

**Comment by dobble11** [comment]
all code block in markdown will also appear

**Comment by CiGit** [comment]
Prettier doesn't format rust code. can you share your input source?
```js
let a = 1;
```
is also JS

I don't get your 
> new line between each line, never stop

**Comment by CiGit** [comment]
New lines issue has been fixed in latest version
