### ISSUE TITLE
Prettier on-click="test" => onclick="(test)"

### ISSUE THREAD

**Issue by liicos** [prettier/prettier-vscode#622]
`<div on-click="test"></div>`
prettier ↓
`<div on-click="(test)"></div>`

How to avoid ?

**Comment by CiGit** [comment]
Except disabling prettier for that language, I think you can't.
As I don't know that syntax, I can't say what it does.

**Comment by loopingz** [comment]
It creates issue with on-click handler for Polymer at least

**Comment by SPessall** [comment]
This bug has broken our polymer application. In what circumstances is it correct to add parentheses to a html attribute?

**Comment by lyonsbp** [comment]
Any update on this?

This issue completely breaks Polymer, forcing me to disable Prettier for the project. (Really just html files, but thats 90% of a polymer project 🙃)

I _think_ the reason for this is that normal `on-click` attributes allow any js expression, not just a method call. So in that case it would make sense to explicitly wrap the method call. But this should be configurable as to allow Polymer users to take advantage of Prettier's awesome features.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by CiGit** [comment]
I think this is caused by #487
