### ISSUE TITLE
New blank lines are added to code block in Markdown files when saving the file

### ISSUE THREAD

**Issue by paolovanini** [prettier/prettier-vscode#624]
When I save a Markdown file containing code blocks to highlight the syntax, some new blank lines are added to that code block.

For example, in a markdown file called "test.md", I inserted the following text with the triple back-tick and the "powershell" as language type:
\```powershell
dir
\```

After I saved the file, I found an extra line after the "dir" code like this:
\```powershell
dir
\
\```

If a keep saving the file, another new blank line is added:
\```powershell
dir
\
\
\```

For a code block containing 5 lines of "typescript" code, with just 1 save, hundreds of new lines were added between each line.

**Comment by CiGit** [comment]
What version of prettier do you use?

I can't reproduce your issue

**Comment by paolovanini** [comment]
I'm using version 1.7.1
It always worked fine and then suddenly yesterday the issue appeared.
I saw here on GitHub that version 1.71 was just been published and I thought that was the cause because I didn't see any another change in Visual Studio Code configuration.
I already tried to reinstall the extension itself and to disable other extensions that could be related to markdown files (I'm also using "markdownlint") but the issue still persists.

**Comment by paolovanini** [comment]
It seems I have the same problem of issue #621

**Comment by CiGit** [comment]
You didn't install prettier in your workspace.
Can you share your settings related to this extension?

**Comment by paolovanini** [comment]
I don't know how to share my settings for the extension, sorry. Could you help me?
If you're referring to "Workspace Settings" I don't have them and my "User Settings" are the following:
{
    "workbench.colorTheme": "Visual Studio Dark",
    "git.enableSmartCommit": true,
    "explorer.confirmDelete": false,
    "npm.enableScriptExplorer": true,
    "files.autoSave": "off",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "editor.formatOnSave": true,
    "workbench.iconTheme": "material-icon-theme",
    "terminal.external.windowsExec": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\\\powershell.exe",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "git.confirmSync": false,
    "window.zoomLevel": 0
}

The issue is present even in a project with a single markdown file, with no other files.
Sorry but I don't know how to help you in a better way :-)

**Comment by paolovanini** [comment]
It seems the problem could be caused by end of line sequence.
If I set to "LF" everything works fine but with "CRLF" I have the issue

**Comment by paolovanini** [comment]
Could it be a "prettier" issue, maybe related to this one?
https://github.com/prettier/prettier/issues/5373

**Comment by NightFalcon650** [comment]
i've got the same issue, but in a html file (like in the link).
I didn't have this problem before. I don't know how to fix it, but i know when i removed prettier it didn't happend anymore. 
My problem is i don't know how to fix it :-(

**Comment by CiGit** [comment]
Things you can do now:
 - downgrade prettier or this extension
 - use LF instead of CRLF
 - wait for a fix in prettier

Can someone open a new issue about markdown and CRLF in prettier's repository? I'm on a phone right now and won't have a computer before some time. Thanks

**Comment by ikatyang** [comment]
prettier/prettier#5413

**Comment by CiGit** [comment]
Thanks @ikatyang , also for the fix
This extension now bundles prettier 1.15.2
