### ISSUE TITLE
React native formatting is not working

### ISSUE THREAD

**Issue by itsmasud** [prettier/prettier-vscode#628]
After enabling autosave formatting enabled, the formatting of following changed into the the later given formatting

Before:
`      <View style={style.wrapper}>
        <View>
          <Text style={style.title}> Hello World!</Text>
        </View>
        <Text> Powered by react native </Text>
    </View>`

After:
`      View style = {
        style.wrapper
      } >
      <
      View >
      <
      Text style = {
        style.title
      } > Hello World! < /Text> <
      /View> <
      Text > Powered by react native < /Text> <
      /View>`

How can I make that working?

**Comment by kachkaev** [comment]
@itsmasud can you share a playground link? What's the file name in which this is happening?
