### ISSUE TITLE
"Format Changed Lines" command

### ISSUE THREAD

**Issue by ryaninvents** [prettier/prettier-vscode#630]
When I use "Format on Save", it formats the entire document. This introduces changes on lines I have not touched, making code review much more difficult.

I would like to have the option to check only changed lines, as measured by the active SCM plugin. This would prevent formatting changes from concealing the actual work done in a pull request, while still ensuring that the code I have modified is "Prettier".

I'd be willing to take a shot at this. Please let me know if this would be better handled in the Prettier project or the VS Code project.

**Comment by CiGit** [comment]
Some quick pointers:

# Prettier's range formatter
Currently prettier as a range formatter which is far from prefect and works only on some languages. It formats the first common parent of your range which is a valid `Program`.
## Example 
```js
myFn({
	opt1: "val",
	opt2: "val2",
})
```
Now adds `opt3 : "val3"` and range format it: It will format the entire snippet.

## Multiple ranges

Prettier supports only 1 range per format call. Having multiple (one for each change) should be faster (1 parse)

# Prettier VSCode

We should have a way to obtain _changed_ ranges. This is maybe already possible. We shouldn't have to include a dependency on every SCM out there.

This would allow us -- with the help of first point -- to format changed lines

## VSCode

We may do it as a specific action `prettier.formatChangedLines` or it may be something provided by vscode's formatter API. Maybe like `registerChangedLinesFormatter`

# Linter integration

They do not support giving them a range. #137

**Comment by bjornicus** [comment]
FWIW, there's an extension that does something like this: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.format-modified#review-details but it looks like it's using clang-format instead of prettier; perhaps that can help with adding this functionality to Prettier VSCode

**Comment by yagudaev** [comment]
Any updates on this?

**Comment by ntotten** [comment]
VS Code doesn't support this natively. We would only add this if VS Code's edit providers add this type of API.
