### ISSUE TITLE
Changes in .editorconfig will be ignored without a restart

### ISSUE THREAD

**Issue by axelf** [prettier/prettier-vscode#633]
Hi,

.editorconfig will be ignored. Via docs the priority is 1 if no .prettierrc exists. But if so, only the defaults are affected.

**Comment by CiGit** [comment]
Could you clarify what you mean?

**Comment by axelf** [comment]
I created a .editorconfig file in order to use the settings from this file. The plugin uses only the default settings and not the settings from .editorconfig.

**Comment by CiGit** [comment]
And what have you put inside your .editorconfig?

**Comment by axelf** [comment]
This is the content, but indent and tab size are 2 and not 4 like in this file.

`root = true

[*]
indent_style = space
indent_size = 4
tab_width = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true`

**Comment by CiGit** [comment]
```
indent_style = space
indent_size = 4
```
Are what prettier understands. Rest comes from `prettier.*` settings

What's wrong?

**Comment by axelf** [comment]
`indent_size` is always 2 and not 4 (like in the `.editorconfig`).

**Comment by CiGit** [comment]
Did you restart VSCode after changing .editorconfig ?

**Comment by axelf** [comment]
Hi,

after a restart of VSCode it's working. Didn't know that i had to restart after changing the .editorconfig. Thank you

**Comment by CiGit** [comment]
You shouldn't have to. That's the issue.

**Comment by CiGit** [comment]
Corrections goes in https://github.com/prettier/prettier-vscode/blob/master/src/configCacheHandler.ts

**Comment by CiGit** [comment]
It also seems there is currently a problem in `prettier.clearConfigCache`. see https://github.com/prettier/prettier/issues/5311 for prettier config files. don't know about .editorconfig

**Comment by ntotten** [comment]
This is fixed in version 3.0.8 (in preview now). You can install the preview version here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
