### ISSUE TITLE
When work in vscode workspace, it can not detect prettier config file

### ISSUE THREAD

**Issue by futurechallenger** [prettier/prettier-vscode#634]
When a project is opened in a workspace including more than one project. 
Prettier-vscode can not find the config file **.prettierrc.js** in the project. 
Or we can say that it does not work as expected.

**Comment by CiGit** [comment]
Can you share a setup where this doesn't work ?

Prettier config files work in a Tree manner. We search a config file from the formatted file and upwards.

**Comment by ernsheong** [comment]
![image](https://user-images.githubusercontent.com/1343284/49337750-d79de300-f652-11e8-9654-ee24dcaba065.png)
 I unchecked this and things are working again.
