### ISSUE TITLE
Vue template support not working in 1.7.2

### ISSUE THREAD

**Issue by vielhuber** [prettier/prettier-vscode#635]
Prettier VS Code v. 1.7.2
Visual Studio Code 1.29.0

When I open a *.vue file, only the JS and CSS part gets prettied on save, but not the vue template part.

In the last version this should be supported.

Am I doing something wrong?

**Comment by vielhuber** [comment]
OK, it works now (i had to do two things):
- "prettier.disableLanguages": [], inside my global vscode settings
- disable "Vetur" vscode extension

**Comment by c01nd01r** [comment]
> disable "Vetur" vscode extension

or
```json
  "vetur.format.defaultFormatter.html": "none",
  "vetur.format.defaultFormatter.css": "none",
  "vetur.format.defaultFormatter.postcss": "none",
  "vetur.format.defaultFormatter.scss": "none",
  "vetur.format.defaultFormatter.less": "none",
  "vetur.format.defaultFormatter.stylus": "none",
  "vetur.format.defaultFormatter.js": "none",
  "vetur.format.defaultFormatter.ts": "none"
```

**Comment by vesper8** [comment]
I've done all of this but still prettier only formats the javascript and css portions of my .vue files, it doesn't format the html inside the template tags
