### ISSUE TITLE
Add the missing option to disable crappy Prettier VSCode HTML formatter

### ISSUE THREAD

**Issue by micobarac** [prettier/prettier-vscode#636]
Latest version of **Prettier - Code formatter** [1.7.0] makes crappy HTML formatting when VSCode **Format on Save** is active.

Please, either allow through the Prettier VSCode settings to disable its bad HTML formatter and let the built-in HTML formatter do its thing or disable Prettier VSCode HTML formatter until you make it decent enough to be useful.

Original:

```html
<!-- Name -->
<mat-form-field>
  <input matInput type="text" formControlName="name" required placeholder="{{ 'OpenFunctionTranslation.Name' | translate }}"
    autocomplete="off" />
</mat-form-field>
<small *ngIf="name.touched && !name.value.length" class="mat-warn">
  {{ 'OpenFunctionTranslation.NameRequired' | translate }}
</small>
<small *ngIf="name.touched && !name.valid && name.value.length" class="mat-warn">
  {{ 'invalidNameFormat' | translate }}
</small>
```
Bad Prettier Formatting:

```html
<!-- Name -->
<mat-form-field> <input matInput type="text" formControlName="name" required placeholder="{{ 'OpenFunctionTranslation.Name' | translate }}" autocomplete="off" /> </mat-form-field>
<small *ngIf="name.touched && !name.value.length" class="mat-warn"> {{ 'OpenFunctionTranslation.NameRequired' | translate }} </small> <small *ngIf="name.touched && !name.valid && name.value.length" class="mat-warn"> {{ 'invalidNameFormat' | translate }} </small>
```
I falsely accused VSCode for the issue. The initial issue was created here:

[Format on save messes up original HTML file format](https://github.com/Microsoft/vscode/issues/62996)

This way I can either stop using VSCode **Format on Save** or disable  **Prettier - Code formatter**  VSCode extension.

Btw, Typescript and SCSS formatters are flawless.

**Comment by micobarac** [comment]
[Format on save messes up original HTML file format](https://github.com/Microsoft/vscode/issues/62996)

**Comment by micobarac** [comment]
Btw, Typescript and SCSS formatters are flawless.

**Comment by micobarac** [comment]
Actually, this is a setting that disabled Prettier formatter for HTML files:

```json
"prettier.disableLanguages": ["html"]
```

**Comment by micobarac** [comment]
Nevertheless, Prettier HTML formatting needs a huge makeover.

**Comment by krokofant** [comment]
I've been noticing this for a couple of weeks now at least. It's horrible :(

**Comment by RobinMalfait** [comment]
@krokofant weeks? It was released 4 days ago...

**Comment by krokofant** [comment]
@RobinMalfait Well then, that is awkward. I might have stumbled upon the wrong issue.

Input code:
```html
  <a [nzTitle]="'MainScreen' | translate" nzPlacement="bottom" nz-tooltip class="mainurl" [href]="mainUrl" [nzMouseEnterDelay]="0.5" [nzMouseLeaveDelay]="0">Hello World</a>
```

And formatting with prettier now renders:
```html
	<a
		[nzTitle]="'MainScreen' | translate"
		nzPlacement="bottom"
		nz-tooltip
		class="mainurl"
		[href]="mainUrl"
		[nzMouseEnterDelay]="0.5"
		[nzMouseLeaveDelay]="0"
		>Hello World</a
	>
```

**Comment by kurtommy** [comment]
this is the way to go

{
  "editor.formatOnPaste": true,
  "prettier.singleQuote": false,
  "prettier.trailingComma": "none",
  **"prettier.disableLanguages": ["html"],**
  "editor.formatOnSave": true,
  "editor.rulers": [110],
  "html.format.wrapAttributes": "force",
  "html.format.enable": true,
  "html.format.wrapLineLength": 110
}
this will keep ts lint enabled while for html we use the standard vscode formatting

**Comment by CiGit** [comment]
Seems you found a way to disable formatter for HTML.

You may want to read https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting 

```html
<a>Hello</a
>
```
may seem faulty but it's valid HTML. It may break some syntax highlighter.

@micobarac I would say you have a pretty high `printWidth`

There is some discussion about HTML formatting on prettier's repository https://github.com/prettier/prettier/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+HTML+whitespace+

HTML formatter is quite new (~ 1 week). Community feedback is somewhat expected.

I'll close that one as the initial issue (disable HTML formatter) has been answered: Option already exists

**Comment by onkarjit** [comment]
Pretty Formatter VSCode extension by mblode seems pretty good so far at formatting HTML.
