### ISSUE TITLE
Feature request: Add ability to disable formatting if there are eslint errors

### ISSUE THREAD

**Issue by kiliman** [prettier/prettier-vscode#637]
I have setup Prettier to remove semi-colons. Because of this, if I forget to insert a semi-colon where it is ambiguous, namely where parens and brackets start a new line, then Prettier doesn't format the intent of the code.

``` javascript
const a = 1

(function foo() {})()
```

becomes 

``` javascript
const a = 1(function foo() {})()
```

This is obviously not what you want. See https://github.com/prettier/prettier/issues/4749

I have an `eslint` rule enabled `no-unexpected-multiline` https://eslint.org/docs/rules/no-unexpected-multiline

VSCode displays the error, but unfortunately when I save the file (I have Format on Save enabled), if I don't catch it, the file is formatted anyway, and I'll end up with syntactically "valid" code that was not the intent.

I understand that to fix the issue, I simply need to place a semi-colon before the open parentheses. However, this is one of those things that can easily fall through the cracks.

Anyway, I have a fork of this extension that checks for `eslint` errors before formatting and bails out if there are any errors present.

So this is what the update looks like. Here is some sample code that has `eslint` errors. You can see them in the Problems panel. When I try to save, it will see there are errors and prevent the formatting. You can see that the Prettier entry in the status bar has an X.

![image](https://user-images.githubusercontent.com/47168/48510390-c87cff80-e821-11e8-8e89-3af026810806.png)

Switching to the Output panel shows the error message from the Prettier extension

![image](https://user-images.githubusercontent.com/47168/48510478-011cd900-e822-11e8-9c9a-e245aa3f8469.png)

Once you fix the errors, you can save and format. The code has been formatted and Prettier now displays the checkmark in the status bar.

![image](https://user-images.githubusercontent.com/47168/48510551-2e698700-e822-11e8-9573-ce08ad60fea4.png)

I wanted to create this issue to discuss this feature. Would it be something that you would be interested in adding to the extension? If so, what configuration options do you think we need?

I can see having the option to filter by *source*: `eslint`, etc. And perhaps by *code*, so you only filter for specific eslint rules like `no-unexpected-multiline` and not all, like `no-unused-vars`.

![image](https://user-images.githubusercontent.com/47168/48510811-e9922000-e822-11e8-8414-34b94e672864.png)

Hope this will spur some discussion.

Thanks!

**Comment by CiGit** [comment]
Hey, thanks for the suggestion.

This doesn't belong to this extension I think. Maybe in prettier-eslint.
Without formatting, your code would still fail. Prettier may even make it easier to notice.

Except `no-unexpected-multiline` are there other errors which are _unexpected_?
Preventing formatting because `expected indent of 4 instead 2` would be somewhat boring.
Eslint errors do not have the same value. Maybe make an extension which _highlights_ errors which have a high chance to break the code (Revive `<marquee>`)

I also don't think an extension should do too much. Let's try to make this one format when users ask to do so.

We could also explore a _plugin_ extension. If I remember correctly, an extension can depend on an other and call things in it.

**Comment by kiliman** [comment]
Thanks for the feedback. The whole point of this addition was to prevent prettier from formatting when certain `eslint` errors occur. The sample I showed above didn't filter for which errors. That was something I would add in configuration.

The issue with `prettier-eslint` is that it runs `eslint --fix` **AFTER** `prettier`. My enhancement is to check for errors **BEFORE** formatting, which it does via VS Code diagnostics.

There are plenty of closed issues on prettier itself with people asking for this functionality (some even wanted prettier to add the missing semi-colon, which I can understand was not something they wanted to do).

I'll see if prettier plugins will solve my use case.

Thanks.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
