### ISSUE TITLE
Prettier-VSCode does not respect .prettierrc configuration for HTML formatting

### ISSUE THREAD

**Issue by yenoiwesa** [prettier/prettier-vscode#638]
I am having similar issues to the ones that have been raised before, `prettier-vscode` does not seem to respect my project's `.prettierrc.json` configuration when formatting HTML files. The print width seems to be defaulted to 80 instead of our custom value of 100.

```json
{
    "printWidth": 100,
    "tabWidth": 4,
    "singleQuote": true
}
```

My vscode is setup to format on save, and our project's `package.json` references `"prettier": "1.15.2"`.
The extension is up to date in vscode too.
Our project does not have a print width setting in the `.editorconfig` file either.

I created a video reproduction of the issue where I save an AngularJS template file in vscode and it gets wrongly re-formated, and then apply the Prettier CLI on that file which puts it back to its correct format.

The video is available [here (Dropbox - 2.1 MB)](https://www.dropbox.com/s/lv2952pza3zzyvg/prettier-vscode.mp4?dl=0).

**Comment by CiGit** [comment]
Can you share the repo shown in your video? (Not private)
Can you debug it?

**Comment by yenoiwesa** [comment]
I created the following repository with one html file that reproduces the issue: [vscode-prettier-bug.zip](https://www.dropbox.com/s/taww38r48u1ach7/vscode-prettier-bug.zip?dl=0)

<img width="841" alt="screen shot 2018-11-16 at 9 12 05 am" src="https://user-images.githubusercontent.com/1464666/48585110-bd3fe600-e97f-11e8-97c0-586d6026331a.png">

**Comment by wghglory** [comment]
I wanna use default vscode formatter for html. I guess perviously prettier doesn't have html formatter, but in 1.7.2, prettier tries to format html, so it doesn't respect vscode default html formatter. I also tried to set `"prettier.disableLanguages": ["html"]`, but this disables default vscode formatter as well.

**Comment by levinit** [comment]
same problem,  install 1.6.1, it works .(this problem happened since ver1.7.0+ )
Also you can disable html in settings,`"prettier.disableLanguages": ["html"]` @wghglory .

**Comment by gk0r** [comment]
My extension does not respect configuration at all for any file type :/

**Comment by Santosh8055** [comment]
In my case, another extension was causing this issue. I uninstalled "XML Tools" and it started working!

**Comment by ntotten** [comment]
VS Code now prompts you to select which formatter to use when you have multiple on the same file type.
