### ISSUE TITLE
.prettierignore results in no formatting at all

### ISSUE THREAD

**Issue by Vandivier** [prettier/prettier-vscode#639]
Observed:
If I specify a file in .prettierignore, editor.formatOnSave appears disabled within that file.

Desired:
If I specify a file in .prettierignore, editor.formatOnSave will still be executed using VS Code built-in rules*

*Or perhaps Prettier would be ignored but eslint would still execute over the file. But then if the file is specified both within .prettierignore and .eslintignore, it would be treated with built-in VS Code rules.

Note:
Perhaps this is expected. If so, can we document that? Are there any workarounds to achieve the desired result?

**Comment by aballerr** [comment]
I'm having an issue with this as well, please fix ASAP thank you.

**Comment by djarekg** [comment]
Please fix, this is causing issues with git merges

**Comment by ntotten** [comment]
If the file is specified in `.prettierignore` it will always be ignored. This is by design.
