### ISSUE TITLE
prettier typescript breaks on null postfix operator

### ISSUE THREAD

**Issue by audiolion** [prettier/prettier-vscode#640]
Since 2.0 Typescript has had the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) but it seems prettier breaks not expecting it

```
Unexpected token, expected "," (/src/SendMessageController/index.tsx:47:83)
  45 |             };
  46 | 
> 47 |             let existingEdge = cache.conversation.messages.edges.find(edge => edge!.node!.id === data.sendMessage!.message!.id);
     |                                                                                   ^
  48 |             let updatedEdges = cache.conversation.messages.edges.map(edge => edge!.node!.id === data.sendMessage!.message!.id ? newEdge : edge);
  49 |             if (!existingEdge) {
  50 |               updatedEdges.unshift(newEdge);
```

I am not sure if this belongs somewhere else, figure we can have the issue transferred if so.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
