### ISSUE TITLE
Different HTML formatting between prettier-cli and prettier-vscode

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [prettier/prettier-vscode#641]
I am using prettier-vscode 1.7.2 and prettier-cli 1.15.2. The following HTML code is formatted differently between prettier-cli and prettier-vscode. 

```
<div class="details">
<span>{{ foo.bar }}</span>
</div>
<div class="details">
<span>aaaaaaaaaaaaa</span>
</div>
```

Prettier-vscode results in 
```
<div class="details">
  <span>{{ foo.bar }}</span>
</div>
<div class="details"><span>aaaaaaaaaaaaa</span></div>
```

And prettier-cli results in 
```
<div class="details"><span>{{ foo.bar }}</span></div>
<div class="details"><span>aaaaaaaaaaaaa</span></div>
```

The cause for this deviation in formatting seems to be how the template literal `<span>{{ foo.bar }}</span>` is handled.

The project where I am testing this has some vscode workspace settings:

```
{
  "editor.formatOnSave": true,
  "files.exclude": {
    "dist": true,
    "node_modules": true,
    "coverage": true,
  },
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
  "prettier.requireConfig": true,
  "versionlens.showVersionLensesAtStartup": false,
  // This should format HTML attributes properly (one attribute per line)
  "html.format.wrapAttributes": "force-aligned",
}
```

A config file for prettier

```
{
  "$schema": "http://json.schemastore.org/prettierrc",
  "singleQuote": true,
  "printWidth": 160,
  "trailingComma": "all"
}
```

And also an editorconfig file:

```
# Editor configuration, see http://editorconfig.org
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
max_line_length = off
trim_trailing_whitespace = false
```

However, none of these settings seem to affect how template literals are formatted.

In order to use prettier-cli I defined the following scripts in package.json:
```
"prettier-list-files": "prettier -l \"src/**/*.{ts,scss,html}\"",
"prettier-format-and-overwrite-files": "prettier --write \"src/**/*.{ts,scss,html}\""
```

Except for [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and [EditorConfig for VS Code](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) no other formatting extensions are beeing used.

**Comment by jvik** [comment]
I have a similar issue

Prettier-cli does this
`<button
	type="submit"
	class="btn btn-light submit btn-lg btn-block"
	@click="editGame"
>
	Save changes
</button>`

Prettier-vscode does this
`<button
	type="submit"
	class="btn btn-light submit btn-lg btn-block"
	@click="editGame"
>Save changes</button>`

Vscode version: Version 1.32.3 (1.32.3)
Prettier VSCode: 1.8.0
Prettier-cli: 1.16.4

**Comment by jvik** [comment]
My bad. Vetur was using incorrect formatter.

**Comment by ntotten** [comment]
I am not able to reproduce this issue in version 3.0. Please try the preview version out and reopen if you still have the bug: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

**Comment by centigrade-thomas-becker** [comment]
I am not using 3.0 yet, but the problems seems to be gone in 2.3.0
