### ISSUE TITLE
Prettier does not run when I do format document

### ISSUE THREAD

**Issue by dmaksimovic** [prettier/prettier-vscode#642]
Let me start off by saying I don't understand why you tied it to "format document", instead of having a separate independent command Run prettier. But anyway, it does not work for me. I looked in other issues where they say it started working after enable/disable -- it did not work for me. I also uninstalled Eslint that I had in the beginning, it didn't help either. I then uninstalled Vim extension - did not help. I do not have any other extensions, I have only installed VSCode today.

**Comment by ntotten** [comment]
Please provide an example code sample and reproduction steps.
