### ISSUE TITLE
Formating breaks on paste (editor.formatOnPaste: true)

### ISSUE THREAD

**Issue by whitecolor** [prettier/prettier-vscode#645]
Just figured out that this is because of `editor.formatOnPaste` was `true`. So still probably a bug?

Here created a sample workspace, disabled all extensions except perttier.

![image](https://user-images.githubusercontent.com/736697/48794096-c54eab80-ed1a-11e8-8d2b-20dc59ca1a7c.png)

Copy `p: number` and insert it inside parm brackets:

![image](https://user-images.githubusercontent.com/736697/48794135-db5c6c00-ed1a-11e8-922d-4cb97b94bdd6.png)

Code formatting breaks. And it happens periodically while editing in my real projects.

The sample code:
```ts
//p: number

export const someFunction = (p: number) => {
  return { a: "1", b: "2" };
};
```

I have formatting onSave enabled.

Vscode 1.29.1 Windows 10.

**Comment by zenoven** [comment]
same issue, it's closed in this issue [Weird auto-formatting of code upon paste](https://github.com/prettier/prettier-vscode/issues/245)

it's still not resolved

**Comment by ntotten** [comment]
Appears to be a prettier issue: https://github.com/prettier/prettier/issues/4206

**Comment by ntotten** [comment]
Closing as its a bug in prettier.
