### ISSUE TITLE
Shared repos: decouple Prettier from editor.formatOnSave setting

### ISSUE THREAD

**Issue by tneck** [prettier/prettier-vscode#652]
### Summary
It's useful that when **editor.formatOnSave** is enabled, Prettier will run on save. However, there should be an option to run Prettier on save without requiring **editor.formatOnSave** to be enabled, because the latter setting causes all sorts of issues when multiple contributors have a different code formatter installed.

### Problem
Imagine you have a repo with several contributors and all the files have been formatted with Prettier, and you enable **editor.formatOnSave** for the workspace so any changes will be formatted instantly. If someone who does not have the Prettier extension comes in and changes a file, then upon pressing save every line will be formatted with whatever formatter they have installed (e.g. eslint or VS-Code's built-in one), including lines they did not touch. As you can imagine, if you have 3 people with 3 different formatters installed, the **editor.formatOnSave** setting will cause a messy formatting battle between them.

### Solution
An independent option **prettier.formatOnSave** would allow workspaces to enable formatOnSave for only those who have Prettier, so the above problem is avoided and all those with Prettier installed will still enjoy the benefits of formatOnSave.

**Comment by ntotten** [comment]
Closing as this is not something we will pick up, but happy to review a PR.
