### ISSUE TITLE
Formatting .ejs creates wrong code

### ISSUE THREAD

**Issue by MohGanji** [prettier/prettier-vscode#654]
I had an `.ejs` file, that was working with prettier (not working well, just working).
prettier formatted the html code and I was happy with it, but when I tried changing the file recently(none of the configs changed, I only changed some other unrelated part of the code) but after saving the document, prettier changed the formatting and resulted in ejs code not compiling.
here is a [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UBMqAllAA4CuMABKgKR1kBmAFAISs4CGA5gEpgdRnjoATMgGdeAIxxwJDRgF8xdAPSEoqTZlx4QAGhARKMMtGnJQvAE72IAdwAKDhDZS8AbhDISJiBy9rxgANZwMADKlGEU-Mgw9tRwpgY4AOroZPDScWBw0Z65ZD65AJ7I4NI2phTScPYwrqH8WLzIrLw4jaYAVtIAHgBCoRFR0bxYcAAyFHBdPX0gg0PRCYoAitQQ8Eu9aSBx9o321RlBlPYUMJkBMOjIABwADKbXEI2ZoZTV13Azj5FqZ7HAAI7UMhg1oCDoHFaNLBkJIpI7STZwHZ7RZIbqHUwweT3CSPZAAJkJoTIOASAGEIFh4SgoNAQSBqI0ACryLz4la8aQwBFHCQQMAi0wQWg0GDkkWqVRAA) for the issue.

I know that you don't support .ejs at the moment, but you did not change the ejs part of the code either, but now it seems like I cannot code .ejs with prettier at all.

I created [this issue](https://github.com/prettier/prettier/issues/5474) in prettier repository but after some discussions to resolve the problem, it seems like the issue is related to the VSCode-prettier integration. so @ikatyang recommended that I create an issue here.

**Comment by Stanzilla** [comment]
Same issue here

```
{
	"resource": "/c:/Users/Benjamin/VCS/Git/WeakAurasCompanion/src/index.ejs",
	"owner": "eslint",
	"code": "prettier/prettier",
	"severity": 8,
	"message": "Parsing error: Unexpected token",
	"source": "eslint",
	"startLineNumber": 1,
	"startColumn": 2,
	"endLineNumber": 1,
	"endColumn": 2
}
```

that line is `<!DOCTYPE html>`

**Comment by ntotten** [comment]
Version 3.0 (preview) of the extension has fixed this issue. You can download the preview here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

If you are still seeing the problem in 3.0 preview, please reopen.
