### ISSUE TITLE
prettier.singleQuote not working with vetur@0.14.2

### ISSUE THREAD

**Issue by moudicat** [prettier/prettier-vscode#659]
`"prettier.singleQuote": true` is not working with vertur latest version.

Check vetur git history:
https://github.com/vuejs/vetur/commit/cf893ed856347a85701b4f887027769a28a0c313

so, I found that I might need to add following code to vscode settings. And it works...

```json
"vetur.format.defaultFormatterOptions": {
    "prettier": {
      "singleQuote": true
    }
  },
```

**Comment by moudicat** [comment]
https://github.com/vuejs/vetur/issues/986

close.

**Comment by dustinrpatterson** [comment]
> `"prettier.singleQuote": true` is not working with vertur latest version.
> 
> Check vetur git history:
> [vuejs/vetur@cf893ed](https://github.com/vuejs/vetur/commit/cf893ed856347a85701b4f887027769a28a0c313)
> 
> so, I found that I might need to add following code to vscode settings. And it works...
> 
> ```json
> "vetur.format.defaultFormatterOptions": {
>     "prettier": {
>       "singleQuote": true
>     }
>   },
> ```

THANK YOU!
