### ISSUE TITLE
Formatting self closing slash incorrectly in .vue files

### ISSUE THREAD

**Issue by ztolley** [prettier/prettier-vscode#661]
**vscode: 1.29.1**

vscode plugins
---------------
Prettier - Code formatter: 1.7.2
Eslint: 1.7.0

package.json
-------------
Prettier: 1.15.2
eslint-config-prettier: 3.3.0
eslint-plugin-prettier: 3.0.0
eslint: 5.9.0

.eslintrc.js
--------
```
module.exports = {
  env: {
    browser: true,
    es6: true,
    jest: true,
    node: true
  },
  extends: ['plugin:vue/essential', 'standard', 'prettier'],
  globals: {},
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  plugins: ['vue', 'standard', 'prettier'],
  root: true,
  rules: {
    'prettier/prettier': 'error'
  }
}
```

.prettierrc
----------
```
{
  "bracketSpacing": true,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "none"
}
```

Description
-----------
I'm setting up eslint, prettier and vscode for a vue js project. In visual studio code I have enabled format on save.

If I use vue js cli to create a starter project and edit and save .js files they are correctly formatted. When I save and lint .vue files they clash with respect to the spacing before a self closing tag.

For example if I have:

```
<template>
  <div class="VueToNuxtLogo">
    <div class="Triangle Triangle--two" />
    <div class="Triangle Triangle--one" />
    <div class="Triangle Triangle--three" />
    <div class="Triangle Triangle--four" />
  </div>
</template>
```

When I save the file it transforms the self closing tags to:

`<div class="Triangle Triangle--two"/>`

This causes eslint to highlight that there is an error that violates the prettier/prettier rule in my eslint.rc file.

If I run prettier from the command line it correctly formats the tag again as:

`<div class="Triangle Triangle--two" />`

I even edited my settings.json file with:

```
"eslint.validate": [
    {
      "language": "vue",
      "autoFix": true
    },
    {
      "language": "html",
      "autoFix": true
    },
    {
      "language": "javascript",
      "autoFix": true
    }
  ]
```

**Comment by busheezy** [comment]
I'm having an issue with this as well. I'm kinda losing my mind right now trying to sort it out. Everything was working before but somewhere along the way it died.

**Comment by ffxsam** [comment]
Prettier seems to completely disregard `.eslintrc.js`. As an example, I have `vue/max-attributes-per-line` set to enforce multiple lines for more than one attribute. When I format with Prettier, it collapses into a single line.

**Comment by mutefiRe** [comment]
same problem here, `.eslintrc` is being ignored.

**Comment by shijunti19** [comment]
因为它我都无法进行工作了
Because I can't work anymore.

**Comment by KerimG** [comment]
In my case, prettier completely removes the closing slash.

**Comment by rdunk** [comment]
Same as @ztolley here, formatting via command line fixes all warnings, but saving with VSCode reintroduces incorrect formatting.

**Comment by jvik** [comment]
Same problem

**Comment by Applicafroguy** [comment]
> In my case, prettier completely removes the closing slash.

Same problem, this is annoying

**Comment by jvik** [comment]
@Applicafroguy Not sure if you have the same problem as me, but Vetur in vscode was set to using incorrect formatter. Changing HTML formatter to prettier in vetur settings solved it for me.

**Comment by mutefiRe** [comment]
> @Applicafroguy Not sure if you have the same problem as me, but Vetur in vscode was set to using incorrect formatter. Changing HTML formatter to prettier in vetur settings solved it for me.

that solved it for me, thank you :+1:

**Comment by Eckhardt-D** [comment]
> @Applicafroguy Not sure if you have the same problem as me, but Vetur in vscode was set to using incorrect formatter. Changing HTML formatter to prettier in vetur settings solved it for me.
Thank you very much!

**Comment by rasikas** [comment]
I have a bigger problem where it completely removes internal attributes and replace with `undefined`
I have `button` tag with certain attributes (vue template)
```
<button type="text" class="btn btn-clearable icon icon-clear" aria-label="clear" @click="clear()"></button>
```
when I format the code (on save) it changes to the following
```
<button>undefined</button>
```

When I disable the plugin it doesn't so it should be related to this plugin

**Comment by ntotten** [comment]
Looks like this is resolved.
