### ISSUE TITLE
User Settings will not be used

### ISSUE THREAD

**Issue by IngressoDev** [prettier/prettier-vscode#662]
Hello,
i'm using this extension and it's working perfect (if you configurated it correct).

And that is the problem. I have multiple projects where i'm using the same prettier configuration.
So i saved them into the global "User Settings". This settings file is located on the user directory.
But this config will not be loaded from prettier.

> Prettier's Settings
> Settings will be read from (listed by priority):
> 1. [Prettier configuration file](https://prettier.io/docs/en/configuration.html)
> 1. `.editorconfig`
> 
> Or if no prettier configuration file exist
> 1. `.editorconfig`
> 1. VSCode prettier's settings (described below with their default)

So i have to create a .eslintrc.js file in every project folder to have the same config.

It would be great if prettier would load the "user settings.json" too if no other configs where found except the default editor config.

**Comment by ntotten** [comment]
We will be removing the Prettier VS Code settings in the next version so this seems to no be relevant. The recommendation is to put a prettier config in every project.
