### ISSUE TITLE
option for requireConfig to search through ancestor folders

### ISSUE THREAD

**Issue by jasonkuhrt** [prettier/prettier-vscode#664]
The `requireConfig` option is great, and I see its becoming more central in #488. However it appears to not work in a monorepo case where sub-packages each have their own `package.json` files but only the monorepo-root package.json has prettier settings configured.

Am I mistaken?

If not consider this a feature request.

**Comment by CiGit** [comment]
When formatting a file, we search for a configuration file above it. prettier's `resolveConfig`

I'm quite unsure if there is a stop at $HOME or "/"

**Comment by jasonkuhrt** [comment]
@CiGit IIUC you're saying that this vscode extension is bound by the prettier API? If so we should probably close this issue :)

**Comment by CiGit** [comment]
The find config tool is provided by prettier but I was mostly saying it should cover your use case.
