### ISSUE TITLE
In Vscode, FormatOnSave -> option is not prettifying the code as per the project prettierrc file

### ISSUE THREAD

**Issue by PavanGangireddy** [prettier/prettier-vscode#665]
For Example,

Somewhere among the import statements written on top of file,

Case1:
```
import withAnalyticsAPI, { AnalyticsConstants } from '../../components/withAnalyticsAPI'
```

When formatOnSave is enabled in vscode, and ctrl+s is pressed

Expected Output:

```
import withAnalyticsAPI, {
  AnalyticsConstants
} from '../../components/withAnalyticsAPI'
```

_But apparently there are no changes to the import statement._

Additional Observations:

Observation1: 
It gives expected results if the same statement is written in this way:

```
import { withAnalyticsAPI, AnalyticsConstants } from '../../components/withAnalyticsAPI'
```

Observation2:

It gives expected results, respecting the prettierrc -> PrintWidth, on formatting the file through prettier-cli 

> prettier --write path/to/filename

Observation3:

It gives expected results, respecting the prettierrc -> PrintWidth, on formatting the file through precommit hook using lint-staged

_**_**Configuration:**_**_

Prettierrc:

`{
  "singleQuote": true,
  "semi": false,
  "printWidth": 80
}
`

lintstagedrc: 
`{
    "linters": {
       "src/**/*.js": [
            "lint:eslint",
            "prettier --write",
            "git add"
        ]
    }
}
`

Versions:

>  "prettier": "1.14.3"
 "eslint": "4.19.0"
 "eslint-config-airbnb": "16.1.0"
 "eslint-config-react-app": "2.1.0"
 "eslint-import-resolver-babel-module": "4.0.0",
  "eslint-loader": "1.9.0",
    "eslint-plugin-babel": "4.1.2",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.12.0",
    "eslint-plugin-jest": "21.22.0",
    "eslint-plugin-jsx-a11y": "6.0.3",
    "eslint-plugin-react": "7.9.1",
"babel-eslint": "8.2.3",
    "husky": "1.1.0",
    "lint-staged": "6.0.1",
   
**Vscode Version : Version 1.20.1 (1.20.1)**

**Comment by CiGit** [comment]
It seems I can't reproduce your issue based on what you provided. Can you setup a repository with everything needed inside to reproduce this ?
