### ISSUE TITLE
Disable Vue components new lines

### ISSUE THREAD

**Issue by pawel-miczka** [prettier/prettier-vscode#667]
So, I have this code:

```
<template>
   <my-awesome-component :good="true" :bad="true" :ugly="true"></my-awesome-component>
</template>
```

and after save i get this:

```
<template>
   <my-awesome-component 
      :good="true" 
      :bad="true" 
      :ugly="true"
   ></my-awesome-component>
</template>
```

How to disable this?

**Comment by OneHungryByte** [comment]
I need to know this.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
