### ISSUE TITLE
Single quote:true on Markdown file breaks file

### ISSUE THREAD

**Issue by narrative1st** [prettier/prettier-vscode#668]
Have an issue where saving a Markdown file in VS, Prettier changes the double quotes in title attribute of reference link to single quote:

this:

```[1]: http://pixar.com "Pixar"```

to this:

```[1]: http://pixar.com 'Pixar'```

The end result is Markdown parser rejects single quotes and reference link is displayed wholesale.

I want to keep Prettier for all other code, but can't figure out a way to disable it universally for Markdown files?

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
