### ISSUE TITLE
<strong> tags breaking up in .HTML

### ISSUE THREAD

**Issue by drawcard** [prettier/prettier-vscode#669]
Hi, in my .html file, the following happens:

**Expected result**
````html
          <p class="quote">
            <strong>"Lorem ipsum dolor sit amet consecetur lorem ipsum dolor sit
              consecetur."</strong>
          </p>
````

**On save error**
````html
          <p class="quote">
            <strong
              >"Lorem ipsum dolor sit amet consecetur lorem ipsum dolor sit
              consecetur."</strong
            >
          </p>
````

Note how the <strong> tags are split up into new lines.

**Comment by alenl** [comment]
This is not only <strong>. Seems that if any tag has contents text that is longer than wrap-chars, the closing angle-bracket of the opening tag is always move to the next line.

**Comment by koopcodes** [comment]
This has been driving me **crazy**. Any other suggestions besides @alenl 's suggestion to add leading spaces?

**Comment by CiGit** [comment]
html is new in prettier. Things are changing. 

You can play with a setting _htmlWhitespaceSensitivity_. Use with care as it can change the meaning of your whitspace.

There is nothing more we can do in this extension about that.

**Comment by morikawa77** [comment]
breaking line after tag solve to me:

```
<strong>
  text
</strong>
```
