### ISSUE TITLE
Markdown list indents following (trailing) paragraphs

### ISSUE THREAD

**Issue by Norfeldt** [prettier/prettier-vscode#675]
I had to disable prettier for markdown files because of the correction mistake of auto-indenting paragraphs that follows an unordered list (adding two lines after the list doesn't work since one save removes double lines to single, and hitting save again indents the following paragraphs).

Hopes this illustrate what happens:

![prettier markdown list issue](https://user-images.githubusercontent.com/678806/49895048-ca050c00-fe4f-11e8-8034-fb9a233b6f54.gif)

Every time it changes is because I hit `save`.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
