### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by magicspon** [prettier/prettier-vscode#676]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.7.2`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.30.0`

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2680417/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by c0b41** [comment]
Same :/

**Comment by bryanjhv** [comment]
Just to note: I started having this issue after enabling ESLint integration.
Without it, this runs just fine and everything works smooth.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
