### ISSUE TITLE
Moves cursor to end of .vue-file

### ISSUE THREAD

**Issue by kabforks** [prettier/prettier-vscode#677]
Hello.

I'm having a problem where the cursor moves to the end of the file (or it seems the </script> tag) in large .vue-files.

It does not happen with "shorter" files. It have been working great for a while, but now the cursor jumps down on format. It's really frustrating.

Here is an example:
https://pastebin.com/bCmdSQ2U

The code in the example is just gibberish, just for illustration purposes. 

If you remove some code or comments, formatting may work as expected. For example, if I remove all the comments from the example above, the cursor does not jump.

My extensions: 
- IIS Express
- npm
- Prettier - code formatter (1.7.3)
- Vetur (0.14.3)
- vscode-icon

Versions:
Version: 1.30.0 (user setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by ntotten** [comment]
I am not able to reproduce this in version 3.0 (preview). You can install the latest preview here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
