### ISSUE TITLE
Prettier works in some directories but not others

### ISSUE THREAD

**Issue by rwang301** [prettier/prettier-vscode#679]
Prettier is working on some directories but not others, have tried literally everything. 
- Reinstalled, reloaded
- Removed extension file from $HOME/.vscode{,-insider}/extensions and re-installed
- Format Document doesn't work either for the directories prettier won't work in
- Settings are all correct

This is super frustrating as the team I am working with use Prettier and I cannot for the files that I need it for. Please help.

**Comment by poub** [comment]
Hi,
Same error solved by remplacing the User Settings.json file in vs code. Make it basic like that

{
  "terminal.integrated.fontFamily": "Fira mono for Powerline",
  "window.zoomLevel": 1,
  "editor.formatOnSave": true
}
