### ISSUE TITLE
Leave one-liners alone

### ISSUE THREAD

**Issue by Zaseth** [prettier/prettier-vscode#681]
What I want:

```javascript
const key = Math.random().toString(36).substr(2, 4)
```

What I get using Prettier:
```javascript
const key = Math.random()
            .toString(36)
            .substr(2, 4)
```

**Comment by kachkaev** [comment]
Hi @Zaseth! This is not quite the right repo to report your issue. VSCode extension just wraps Prettier and does not influence how the output looks.

See https://github.com/prettier/prettier/issues/4125 and feel free to close this one.
