### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Sadhr** [prettier/prettier-vscode#683]
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2710046/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.7.3`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Duplicate of #676
