### ISSUE TITLE
inline html not formatted in prettier-vscode but in prettier-cli

### ISSUE THREAD

**Issue by yorrd** [prettier/prettier-vscode#685]
in the cli, prettier does perfect formatting. 

in vscode, prettier doesn't format inline HTML in **some** files. I've tried to make a small reproduction but can't seem to figure out the issue. I'll keep looking.

What I don't understand is why there are differences at all, if I just let the prettifier run separately with the `--write`-option, it works as expected. That's my workaround for now

**Comment by CiGit** [comment]
May that be #638 ?

**Comment by yorrd** [comment]
@CiGit it doesnt format at all, not only with the wrong config

**Comment by CiGit** [comment]
Prettier runs based on the languageid. So if your HTML file is not html, it won't do anything.
