### ISSUE TITLE
Prettier CLI ignores HTML line width / multiline. But Prettier in VS Code works.

### ISSUE THREAD

**Issue by Domvel** [prettier/prettier-vscode#687]
**Prettier (npm) 1.15.3**
**Prettier (esbenp.prettier-vscode) 1.7.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABMRnAIYAmeqA9OpTUaagEYRUCehJpZAQgC0Q4gCU4AZwCuOGMQoAzeACdiAcwCW8yFizaAdMQAymqHGI5N++ZsnFN6qBBVwqRkb35kqmgG7EkjBcOHAAvAQgihAQSMTREJHEAFRQ6gCSihFRMQkJABQAlJFe3j7+pWXlAWA4FJKS2XkxQs0Q8bktCSUsVfyovjV1DU2dEK1jSUEh4ZEJcW09fH39g8S9K9619Y1zkyAbm6QA2mkAwsOSALrZwPMdEG1t+QmFADQP9wJPYwWvHz9Yp9fjEigCYgsQWMIPkAIyFAC+kUORxeMUKo0eYzREGKB2Wm0qmwG-mI2xGe3agImVJiJXogyJKwZFRRZRZfiZ-TojLZHKJ-MOh1QwlEAFEAB4ABzgYHg7mIABV0HZiK4ZHJiFQIFJ1iAAGIuLAUeQAEQgYGkWAQMCS+QAyirlABqACCcmd+sKDhIADV7cQzpw4B4hAK1tNQpjIYkQCk0plMc88VySZy2aw1uTdjkseM2sD83SQFzvGmyZck119oFglHKTHuiWM+zBi2qtmq7H22VTuoLjsbpFgD2qvdAc9-qOym04t8oZP0W9p95AY2oWCV-xx1C8zD4Vukfijt4cRjKYvcciCStS31y53KYWEjSHvSeayb-eP+mv2Wf3egpfkB-68nw9AcNwvD0JguB4CAbwgBAUowJo0CSMgoAUCoKgQAA7gACthCAYSgFB+BAmhUAhIBsCoFBgAA1nAMD2lKDFmOoyAwCo0hwIhsE4AA6iq8CSOxYBwPaJHaP42hcMg4ANDRZiSHAKgwAR9HqMayCKBQOBqYhABWkgSgAQvRTEsfaFDWqY5h6QZRkgKZEr2pxoQAIrSBA8BOYZ-EgOxKhqSoimCTRUoqGYMBCVRMDoMgsIAEwAAyIdFEBqUJ9FSop0VSOpfhwDRrgAI7SJorhaRQOkUAFLlqfo3G8UFkieXAPl+aVSA8XxiEwBQbDxVQiXIClg30ZoVjnBAegNSgziOYh0hqYqw2kfpgUIgiQA)

![screen](https://user-images.githubusercontent.com/35452565/50764676-cceaf500-1273-11e9-9b2d-fd33772a19cc.gif)

## Project Setup

In these zips "assets" and "vs-code-settings" are all useful information about my project, extensions and versions.

[assets.zip](https://github.com/prettier/prettier/files/2732486/assets.zip)
[vs-code-settings.zip](https://github.com/prettier/prettier/files/2732538/vs-code-settings.zip)

## Case
I use the [git hook](https://prettier.io/docs/en/precommit.html) to format files in pre-commit.

## Problem
The formatter generally, but it is different between VS Code Prettier: Format Document (`Shift` + `Alt` + `F`) and `Prettier CLI` (npm package used for git hook)

```text
                            |
Pseudo foo { one: 1, two: 2, three: 3 }
                            |
```

## Expected
The code formatted by git hook / prettier cli should format exactly same as the VS Code Prettier extension.

```text
                            |
Pseudo foo {                |
  one: 1,                   |
  two: 2,                   |
  three: 3                  |
}                           |
                            |
```

*VS Code Prettier* Formats like expected. The line (width exceeded) is broken and the angular object pretty formatted in multiline. Perfect.

*Prettier CLI* Formats the document. But ignores the html line width. It does not break and format the object in multiline as expected. Not as VS Code Prettier does.

## Options

`.prettierrc`

```json
{
  "printWidth": 120,
  "singleQuote": true
}
```

Btw: This command also formats the document in the incorrect way.

```bash
prettier --write "src/**/*.html"
```

It's also interessting, that Prettier (npm) does not re-format the document if I formatted the document by Prettier VS Code. So there is no straight format.

You can find all settings and the project setup in the assets.zip (link above). 
For further questions I am available with pleasure.

**Comment by Domvel** [comment]
@j-f1 Wait. The VS Code extension is correct in my opinion. The Prettier CLI (npm package) does not format correctly. VS Code extension breaks the lines and pretty formats in multiline. But the Prettier CLI (called e.g. in git hook) does not break the lines with width exceeded. So I think, this issue has nothing to do with VS Code.

**Comment by CiGit** [comment]
May that be the same as #638 ?

**Comment by ntotten** [comment]
I tested this in version 3.0 and the extension now behaves exactly as prettier does. I am not saying this is the functionality you want, but the extension is just a wrapper on prettier and we aim to behave exactly the same. 

You can test the preview version of prettier vs code 3.0 here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
