### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by like-a-fox** [prettier/prettier-vscode#688]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.7.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/derekmusser/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Please attach the stack trace and reopen.
