### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bradennapier** [prettier/prettier-vscode#690]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.7.3`
- OS Version: `Darwin x64 18.0.0`
- VSCode version: `1.31.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/bradennapier/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bradennapier** [comment]
Why in the world would prettier stop working suddenly?  Is it reliant on the internet for something?  How could it break for everyone randomly without something breaking it ?  Worked fine until tooday...

**Comment by bradennapier** [comment]
This is ridiculously broken all the sudden - never had an issue until randomly now... things dont work, it wont format -- running "Format Document" seems to do the job - its just format on save broken?

I tried changing to 1.6.1 no luck...

no idea what could have randomly broken.

**Comment by bradennapier** [comment]
Was able to fix by setting `editor.formatOnSaveTimeout` to `3000` but that is not good.  why is it 10x slower all the sudden?

**Comment by ntotten** [comment]
Please attach the stack trace and reopen.
