### ISSUE TITLE
requireConfig only for projects

### ISSUE THREAD

**Issue by jdahdah** [prettier/prettier-vscode#693]
I frequently run into the case where I open up a legacy project that doesn't use Prettier, only to have Prettier reformat a document that I didn't intend to. One way to solve this would be to use the `prettier.requireConfig` setting. The problem with this, however, is that it's a global setting. I **do** want Prettier in nearly all other cases. So if I'm editing a single file or setting up a quick new project, it should be active. If I'm opening up a legacy project, it shouldn't. I currently use [Formatting Toggle](https://github.com/Tom-Bonnike/vscode-formatting-toggle) to make this process a little easier, but I sometimes forget to hit that toggle. Alternatively, I could create a `.prettierignore` file for each project that I want to opt out of Prettier, but it doesn't make sense to me to be adding extra files to my repo for software that may or may not be on a collaborator's computer. It would be nice if this were something that Just Works™.

I'm not sure if or how this could be achieved, so I'm just putting out the suggestion. Happy to hear your thoughts!

For what it's worth, I use [Project Manager](https://github.com/alefragnani/vscode-project-manager) to manage all of my projects. Perhaps it's possible to limit `requireConfig` to folders that have been formally defined as a "project", vs. just a directory with files in it.

**Comment by CiGit** [comment]
You could put a prettier config file at the top of your projects hierarchy which use prettier. ie:
pathToLegacyProjects
  p1
  p2
pathToPrettyProjects
  p3
  p4
  .prettierrc.json `{}`

and set requireConfig to true.

**Comment by ntotten** [comment]
This hasn't had any activity in a while and it's not something we are likely to pick. Happy to review a PR.
