### ISSUE TITLE
Prettier does not work with files opened remotely

### ISSUE THREAD

**Issue by gg3l** [prettier/prettier-vscode#694]
I am using the "Remote Workspace" extenion to manage my project via sftp.
The "editor.formatOnSave": true is added to the user settings of VS Code.
Prettier does not work, running it manually or on auto-save, with any file that is opened remotely.
It does, however, work if I create a local file.

VS Code 1.30.2 (Windows)
Prettier 1.7.3
Remote Workspace 0.40.0

**Comment by angel-luis** [comment]
I'm using the Glitch plugin (glitch.glitch) to open a project from Glitch.com.

It doesn't works, the files format are JavaScript. I've the latest version of all.
