### ISSUE TITLE
Use prettier 1.16

### ISSUE THREAD

**Issue by markgoho** [prettier/prettier-vscode#697]
Upgrade to prettier 1.16

**Comment by balupton** [comment]
I wish its resolution worked like so:

1. use the project's prettier if installed, `npm install prettier -D`
2. otherwise use the global prettier if installed, `npm install prettier -G`
3.otherwise  use this vscode extension prettier

That way we wouldn't have to endure this lag.

**Comment by CiGit** [comment]
@balupton it follows point 1 and 3 of your list
