### ISSUE TITLE
prettier works even if add to .prettierignore

### ISSUE THREAD

**Issue by hhshii** [prettier/prettier-vscode#698]
my folder like this:
```
 - root
    - .prettierignore
    - .prettierrc
    - src
       - variable.less 
```

and I have a simple ignore:
```
./src/variable.less
*/variable.less
```

and I found prettier works in `variable.less`, it's anything wrong?

**Comment by GFwer** [comment]
Yes, it still works fine

**Comment by CiGit** [comment]
What do you mean by **fine**

**Comment by CiGit** [comment]
Quicky tried with `src/variable.less` and the less file is not prettier

Can you share a repo which could reproduce that issue?

**Comment by CiGit** [comment]
You may have an other formatter which formats you file

**Comment by GFwer** [comment]
sorry! I think I find the cause of the problem, prettier find the root directory of VSCode.my VSCode open directory with multiple projects.At last, I fix this problem with open the project directly.
