### ISSUE TITLE
breaking import statements : { foo } from 'bar';

### ISSUE THREAD

**Issue by sarbbottam** [prettier/prettier-vscode#699]
Hi there, `prettier-vscode` is converting 

```
import { click, currentURL, visit } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';
import { module, test } from 'qunit';
```
to 
```
import {
  click,
  currentURL,
  visit
} from '@ember/test-helpers';
import {
  setupApplicationTest
} from 'ember-qunit';
import {
  module,
  test
} from 'qunit';
```

however `prettier` binary is not formatting it.
I am wondering why `prettier-vscode` is doing so. Is there something that I need to do?

**Comment by CiGit** [comment]
depending on your settings it can break an import statement to multiple lines.
printWidth with a low value comes to my mind. eslintIntegration or tslintIntegration with their relative config files.

**Comment by sarbbottam** [comment]
`printWidth` came to my mind, but all of them are less than the default `printWidth` limit, i.e. 80.

Please let me know what information I can share.

Also, I am wondering if `prettier-vscode` should respect local `.prettierrc`.

**Comment by nunovieira** [comment]
Looks like I have the same issue.
`prettier-vscode` is breaking lines shorter than the `printWidth` in `.prettierrc`. Eslint/Tslint Integration are disabled. What more info can I provide?
