### ISSUE TITLE
Installing from unlimited time

### ISSUE THREAD

**Issue by shakeel803** [prettier/prettier-vscode#712]
Issue Type: <b>Bug</b>

I clicked on install and its been hours it shows installing. Now I am seeing the same installing message even after days. My email is shakeel803@gmail.com

Kind Regards,
Shakeel

Extension version: 1.7.3
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|7.90GB (3.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by shakeel803** [comment]
![prettier](https://user-images.githubusercontent.com/19165910/52179629-92d32b80-27fe-11e9-8217-230f358c816a.png)

**Comment by ntotten** [comment]
I dont really know what can be done about this. I think this is probably something with VS Code itself. We dont have any impact on how the install happens.
