### ISSUE TITLE
Why does it take 2 applications of Format Document/Selection to obtain results?

### ISSUE THREAD

**Issue by godmar** [prettier/prettier-vscode#713]
I'm using vscode 1.30.2 on Linux with Prettier 1.8.1 I have disabled all other extensions. I do not have a .prettierrc file or a "prettier" key in my package.json, nor any other configuration (I'm aware of).

I create a .js file with this ill-formatted content:
```javascript
function f() {
    a.b(). c(). d();
}
```
I select the file content with Ctrl-A, the press Ctrl-K Ctrl-F to invoke "Format Selection".
The file changes to:

```javascript
function f() {
    a.b().c().d();
}
```

I wait 10s, nothing changes.  Then I press Ctrl-K Ctrl-F again:

```javascript
function f() {
  a.b()
    .c()
    .d();
}
```

Based on (the somewhat inconclusive) [issue #1565](https://github.com/prettier/prettier/issues/1565) I believe that the second result is how prettier formats chained calls.

My question: why do I need to press "Format Selection" twice when using the prettier VSCode plug-in?

**Comment by godmar** [comment]
ps: you can see what I'm seeing in this [1:13 screencast](https://www.cs.cloud.vt.edu/bugs/vscode-prettier-weirdness.webm) which I'll leave up for a couple of weeks.

**Comment by ntotten** [comment]
Are you still seeing this in version 2.0.0?
