### ISSUE TITLE
VSCode not considering tabWidth setting

### ISSUE THREAD

**Issue by aviaryan** [prettier/prettier-vscode#717]
I have a `.prettierrc.yaml` file with tabWidth set to 2. 
I don't have a `.editorconfig` file. 
I am not setting any `prettier.<setting>` settings from VSCode settings. 

The tab width for `js` and `css` files is still 4.

![screen shot 2019-02-10 at 2 41 52 pm](https://user-images.githubusercontent.com/4047597/52531850-08308600-2d42-11e9-9825-bc5e2ef1bb54.png)

UPDATE - After setting `editor.tabSize` to 2 in current workspace settings, it works but I think this plugin should this automatically. Is this a bug?

**Comment by tjx666** [comment]
I also meet this problem that the prettier plugin makes indent setting in the .editorconfig file not work.

**Comment by krokofant** [comment]
Try to change your config to a `.json` file and see if the setting works. `.prettierrc.json` works the best it seems  #371

**Comment by CiGit** [comment]
This extension doesn't read or write `editor.tabSize`
Are you sure you are using this extension ? As of vscode 1.33 it should be easier :-)

**Comment by ntotten** [comment]
I can no longer reproduce this. Try the latest version of the extension preview and let me know if you still have issues. https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
