### ISSUE TITLE
Auto Format deleting bracket incorrectly in Markdown

### ISSUE THREAD

**Issue by Esummins** [prettier/prettier-vscode#720]
I have a line of markdown in the following format:
`[some_ref] [![alt_text][image]][link]`

It looks odd, but `alt_text` is alt text for the image referenced by `image`. The image is also clickable, and links to the`link` reference. `some_ref` is a separate reference.

On save, it gets formatted as:
`[some_ref]![alt_text][image]][link]`

It drops the space, and drops an open bracket, which breaks the `link` link, so it's treated as an independent reference instead of being the on-click link for the image.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
