### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ilirius** [prettier/prettier-vscode#722]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/ilirius/esbenp.prettier-vscode-unresponsive.cpuprofile.txt
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2859547/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)
` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Please attach the stack trace and reopen.
