### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by budalin** [prettier/prettier-vscode#723]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2859678/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

- OS Version: `Darwin x64 15.6.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/gothic/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` 
:warning:
Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kachkaev** [comment]
Hi @budalin! Please check existing issues before creating a new one:
https://github.com/prettier/prettier-vscode/issues?q=is%3Aissue+Extension+causes+high+cpu+load+is%3Aopen

**Comment by ntotten** [comment]
Duplicate of #676
