### ISSUE TITLE
Prettier breaks JSON

### ISSUE THREAD

**Issue by gazedash** [prettier/prettier-vscode#724]
Expected behavior:
Prettieifes or at least doesn't break the json

Actual behavior:
Breaks json on "Format document" (It removes braces from keys and makes strings single quotted)

Prettier extension version 1.8.1
Vs Code version: 1.31.1
Prettier version: 1.16.4

**Comment by kachkaev** [comment]
Hi @gazedash could you please provide an example JSON where you see this happening?

**Comment by kachkaev** [comment]
BTW if you believe the issue is with Prettier, not just VSCode, the issue should probably go to https://github.com/prettier/prettier

**Comment by gazedash** [comment]
@kachkaev so it seems it is a problem with VScode Prettier extension since if I pass to the prettier cli parser option "json", it works as expected.

**Comment by kachkaev** [comment]
From my experience, VSCode is correctly assigning the language to files by extension. If you open a .json and don’t see JSON in the right side of the status bar, something is wrong with file type mapping. Could it be that you installed some extension or tweaked the settings?

**Comment by gazedash** [comment]
@kachkaev no, it shows as "json" and I didn't change any settings, although this bug happened after vs code updated to 1.31.1

**Comment by CiGit** [comment]
do you have a config file with a "parser" key in it?

**Comment by gazedash** [comment]
So it seems the problem was that my prettier config had parser key with value "babylon".
When I changed it to "babel", it started working.
