### ISSUE TITLE
Use local .prettierrc

### ISSUE THREAD

**Issue by uncleramsay** [prettier/prettier-vscode#734]
Hi,

I may be missing something here, but according to the [prettier docs](https://prettier.io/docs/en/configuration.html):

> The configuration file will be resolved starting from the location of the file being formatted, and searching up the file tree until a config file is (or isn't) found.

This doesn't appear to happen with the extension. I have a setup like this:
![image](https://user-images.githubusercontent.com/10271207/53231273-764d4500-3680-11e9-9c32-715778c363f1.png)

But on saving a files in `packages/advantage/src/` the .prettierrc.js file in `packages/advantage` appears to be ignored and instead the default prettier settings are used.

If I copy the config file to the root of my project, the rules are picked up and applied correctly by the extension.

I'm not sure if I'm doing something wrong because it does appear that you're looking for configs in all dirs: https://github.com/prettier/prettier-vscode/blob/78b34af4d1372313ecb3b3aab8e02ac79f62bd08/src/configCacheHandler.ts#L25

Could you let me know if this is a bug or if I'm misunderstanding something?

Thanks

**Comment by gaastonsr** [comment]
Unfortunately currently `.prettierrc` needs to be used (without the `.js` extension) for it to work.

**Comment by CiGit** [comment]
So it works without the "js" extension ?

**Comment by pqkluan** [comment]
Is there any reason for `.prettierrc.js` not being support by `prettier-vscode` plugin?

I'm prefer *.js over JSON file file type because I could put comment on the rules I'm using. Which is consistent with other configuration files for ESlint and Babel.

**Comment by JNaftali** [comment]
`.prettierrc` can be formatted as yaml instead of json. Can use comments that way

**Comment by pqkluan** [comment]
Hi everyone, I forgot to update the issue.

I'm able to user `.prettierrc.js` setting file in the latest version (v2.3.0).
I think we could close the issue.

**Comment by ntotten** [comment]
We now use prettiers default config resolver in version 3.0. This should be completely fixed now with any config type. Please try the preview version here and let me know if you still have issues: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
