### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ColeTownsend** [prettier/prettier-vscode#735]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ColeTownsend** [comment]
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2895101/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by ntotten** [comment]
Duplicate of #676
