### ISSUE TITLE
Format onSave does not work if import with a long relative path in file

### ISSUE THREAD

**Issue by Antibioticvz** [prettier/prettier-vscode#736]
I faced today one strange bug with Prettier and VSCode when files with a long relative path import in it just ignored by prettier extension but with an absolute path or a short one work as expected
![ldrq2ppxrh](https://user-images.githubusercontent.com/6497819/53288566-0edbe600-37a3-11e9-8934-a308cd33e817.gif)

**Comment by ntotten** [comment]
I am unable to reproduce this in version 3.0 (preview). To test the preview version install here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

If you can reproduce this, please provide a github repo that i can use to test this issue and reopen. Thanks!
