### ISSUE TITLE
Format Document breaks function, Format on Save breaks and fixes function

### ISSUE THREAD

**Issue by krmax44** [prettier/prettier-vscode#741]
I ran into this really bizare issue. This is my code:

```js
const getAgentName = agent =>
  typeof agent === 'string'
    ? agent.toLowerCase()
    : agent.slug || agent.name.toLowerCase();
```

Using `Format Document`, I get this broken version of the function above:
```js
const getAgentName = agent =>
  typeof agent === 'string' ?
  agent.toLowerCase() :
  agent.slug || agent.name.toLowerCase();
```

When I save the file with Format on Save enabled, this is what happens:

![Screencast](https://user-images.githubusercontent.com/12673799/53684721-1ce4b600-3d11-11e9-8362-f51aa20a1f12.gif)

It formats (breaks) it, then it magically gets fixed again?!

My `.eslintrc.js`:

```js
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: [
    'plugin:vue/essential',
    'prettier',
    'prettier/vue',
    'eslint:recommended'
  ],
  plugins: ['prettier', 'vue'],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'prettier/prettier': ['error', {
      'singleQuote': true
    }]
  },
  parserOptions: {
    parser: 'babel-eslint'
  }
}
```

Thanks for your help.

**Comment by henrymunro** [comment]
I've had the same problem that was being caused by another vscode extension I installed (Beautify).

**Comment by krmax44** [comment]
It turned out I had ES Lint on Save as well as Format on Save enabled. Maybe at least this issue helps someone else who forgot about that too in the future :smile:
