### ISSUE TITLE
Inconsistency with GQL strings

### ISSUE THREAD

**Issue by xereda** [prettier/prettier-vscode#742]
Inconsistency with GQL strings

The prettier is not being applied when a string, in graphql (gql) format, has an argument operation. Watch:

:+1: 
Is this right. 
Criticism must occur because of unnecessary space. When saved, the prettier corrects:
![captura de tela de 2019-03-07 08-38-37](https://user-images.githubusercontent.com/14337850/53954241-6ab44200-40b4-11e9-8e1f-a692c1fc060b.png)

:-1: 
But when I mingle with a preexisting variable, the prettier ignores validation:
![captura de tela de 2019-03-07 08-47-28](https://user-images.githubusercontent.com/14337850/53955180-0ba3fc80-40b7-11e9-9f36-118fd93adb7a.png)

Observe in the simulations below. When we introduce a variable in the template string, validation and prettier does not occur anymore. The prettier only works again after the variable is removed.

![peek 07-03-2019 09-01](https://user-images.githubusercontent.com/14337850/53955378-a43a7c80-40b7-11e9-91da-dcd7360dc0ee.gif)

![peek 07-03-2019 09-05](https://user-images.githubusercontent.com/14337850/53955620-3e022980-40b8-11e9-882e-d4b63a1b6e47.gif)

**Comment by xereda** [comment]
I tested with the Prettier Playground, but he does not behave well.


![peek 07-03-2019 09-21](https://user-images.githubusercontent.com/14337850/53956604-d0a3c800-40ba-11e9-9e28-f10d6cc44c15.gif)

**Comment by CiGit** [comment]
see https://github.com/prettier/prettier/issues/4404

**Comment by xereda** [comment]
@CiGit `fake-tag` module not working.

**Comment by CiGit** [comment]
I mean: interpolation is not supported by prettier's parser from what I get. Prettier doesn't format gql when there is an interpolation.
There is nothing we can do here. Closing

**Comment by xereda** [comment]
@CiGit What do you suggest as an alternative?
