### ISSUE TITLE
TypeScript specific syntax not recognized

### ISSUE THREAD

**Issue by peralmq** [prettier/prettier-vscode#745]
We use TypeScript and use your `formatOnSave` feature. It woks great for some files but doesn't work for others. It seems like newer TypeScript syntax is not recognized. I.e. `enum` and `as`.

When running prettier from command-line we solve this by adding the `--parser typescript` flag. Can we enable that flag somehow in this plugin too? Or any other workaround that will allow "newer" TypeScript syntax on `formatOnSave`?

Here is an image describing when prettier used via this plugin gets into trouble. Note how prettier fails around the `enum` keyword with an `Unexpected token` error.

<img width="443" alt="Screenshot 2019-03-09 at 10 28 53" src="https://user-images.githubusercontent.com/238536/54069272-db935f80-4256-11e9-9a73-ae2af1eb52cb.png">

**Comment by CiGit** [comment]
I suppose you have a prettier config file where you specify "parser"

**Comment by peralmq** [comment]
@CiGit you're correct! Sorry, we had missed that, had set `parser: 'babylon'` in `.prettierrc.js`. Thanks for the help 🙇
