### ISSUE TITLE
Ignore Prettier in VSCode Settings.json

### ISSUE THREAD

**Issue by jhanstra** [prettier/prettier-vscode#750]
I'm wondering how I would turn Prettier off only for my VSCode settings.json and keybindings.json files. I edit these files frequently and don't want them to be prettier-ified. But they are also not in any 'project' where I could put a .prettierignore file. I tried putting a file at the root of the folder they are in and that didn't work. I don't want to turn off 'formatOnSave' for all json files - just certain ones like settings.json.

Anyone know the best way to do this? Is there any way to do it? I've also tried adding /* eslint-disable prettier */ at the top of the file with no luck. Thanks.

**Comment by ntotten** [comment]
Can you run "File: Save without formatting"?

Also, in vscode now these files dont by default open in json editors so I dont really think this is something we will address at this time.
