### ISSUE TITLE
With wrapAttributes="force-expand-multiline", tags are only formatted onto separate lines if the total length is over 80 characters

### ISSUE THREAD

**Issue by nickraphael** [prettier/prettier-vscode#751]
I want all attributes on a new line.  Hence the force-expand-multiline.  But prettier only splits the attributes onto separate lines if the total length is over 80 characters.  Clearly this has something to do with PrintWidth.  All I want is all html attributes on single lines below the opening tag.  Regardless of the length of any attribute.

Try to format this...
`<div fxLayoutAlign="qwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopox"></div>`

Results in the fxLayoutAlign attribute on the same line as the div tag.

If I add a single character, it will split it onto multiple lines.  I want it to do this regardless of length.
`<div
  fxLayoutAlign="qwertyuiopqwertyuiopqwertyuiopqwertyuiopqwertyuiopoxX"
></div>`

 

My user settings are...
{
  "prettier.singleQuote": true,
  "editor.wordWrap": "bounded"
}

My workspace settings are...
{
  "window.zoomLevel": -1,
  "editor.formatOnSave": true,
  "editor.wordWrap": "bounded",
  "editor.wordWrapColumn": 140,
  "editor.minimap.maxColumn": 140,
  "javascript.preferences.quoteStyle": "single",
  "javascript.preferences.importModuleSpecifier": "relative",
  "search.location": "sidebar",
  "workbench.activityBar.visible": true,
  "workbench.sideBar.location": "left",
  "html.format.wrapAttributes": "force-expand-multiline"
}

**Comment by CiGit** [comment]
If you want to use the default html formatter, you should disable prettier for html.
prettier.disableLanguages: [..., "html"] and restart vscode
"html.format.wrapAttributes": "force-expand-multiline" is specific to the default formatter.

You can alternatively have something like that if you reduce printWidth with prettier.
And you can do that only for html if you use a prettier config file.
https://prettier.io/docs/en/configuration.html
