### ISSUE TITLE
Vue Cli 3  support eslint

### ISSUE THREAD

**Issue by lovik1468** [prettier/prettier-vscode#752]
I have such a problem that the plugin is not compatible with the eslinta rules that are built into vue cli 3. Tell me how to make friends with them. After formatting, I get these errors

http://pix.toile-libre.org/upload/original/1552497764.jpg

**Comment by ntotten** [comment]
This is likely our parser inference. The extension is likely not detecting the type of the file correctly. As a workaround, you can specify the parser in a prettier config file "overrides" property and set the parser. See: https://prettier.io/docs/en/options.html#parser

```
{
	// ...
	"overrides":[{
		"files": "*.html", // replace this by more specific extension if needed
      	"options": {
        	"parser": "html"
      	}
	}]
}
```

Duplicate of #487

**Comment by lovik1468** [comment]
Ok I will try tomorrow
