### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jdgn94** [prettier/prettier-vscode#753]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/juan/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kachkaev** [comment]
https://github.com/prettier/prettier-vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Extension+causes+high+cpu+load+

**Comment by kachkaev** [comment]
__2 maintainers__: Let's see if this trap people fall in can be fixed in VSCode: https://github.com/Microsoft/vscode/issues/70492

**Comment by CiGit** [comment]
@kachkaev All those issues are useless without the attached file. The stack trace can differ between those issues. So not necessarily duplicate. I suspect things in prettier-**lint tho.

**Comment by kachkaev** [comment]
@CiGit by the ‘trap people fall in’ I mean the creation of multiple issues with the same dummy text. I'm subscribed to prettier-vscode on GitHub and am seeing the same issue created over and over again several times a week. This is not useful for anyone 🙂

**Comment by adFedorovich** [comment]
Add this line to .eslintrc.json file, it works for me) 

```
"env": {
	"browser": true
},

```

**Comment by kachkaev** [comment]
@ntotten, just FYI. https://github.com/microsoft/vscode/issues/70492 is why this issue no longer appears recently. Seems like it might be still worth investigating. Hope that closing lots of duplicates won't take you too long 🙌

**Comment by ntotten** [comment]
Closing this one since no stack trace.
