### ISSUE TITLE
trailingComma setting is not respected in SCSS lists/maps 

### ISSUE THREAD

**Issue by jochienabuurs** [prettier/prettier-vscode#755]
See https://github.com/prettier/prettier/issues/4076

When I have prettier-vscode active, it does not respect the trailingComma setting for SCSS lists/maps.

I'm using this config:
```
{
    "$schema": "http://json.schemastore.org/prettierrc",
    "semi": false,
    "singleQuote": true,
    "trailingComma": "all",
    "tabWidth": 4
}
```

Example code:
```
$spacers: map-merge(
    (
        0: 0,
        1: (
            $spacer * 0.25,
        ),
        2: (
            $spacer * 0.5,
        ),
        3: $spacer,
        4: (
            $spacer * 1.5,
        ),
        5: (
            $spacer * 3,
        ),
    ),
    $spacers
) !default;

$grid-breakpoints: (
    xs: 0,
    sm: 576px,
    md: 768px,
    lg: 992px,
    xl: 1200px,
) !default;
```

With prettier-vscode disabled, and using `npx onchange '**/*.{ts,tsx,js,json,scss,css,mdx,md}' -- npx prettier --write {{changed}}` to format on save ([as explained here](https://prettier.io/docs/en/watching-files.html)), my file gets formatted the correct way, respecting `trailingComma: all`:

```
$spacers: map-merge(
    (
        0: 0,
        1: (
            $spacer * 0.25,
        ),
        2: (
            $spacer * 0.5,
        ),
        3: $spacer,
        4: (
            $spacer * 1.5,
        ),
        5: (
            $spacer * 3,
        ),
    ),
    $spacers
) !default;

$grid-breakpoints: (
    xs: 0,
    sm: 576px,
    md: 768px,
    lg: 992px,
    xl: 1200px,
) !default;
```

Switching the `trailingComma: all` to  `trailingComma: none` also correctly formats the document on save, removing all trailing comma's.

What this tells me is that my rules are correctly set up and that nothing is preventing prettier itself to do it's job.

But when I disable the watch command and enable prettier-vscode, all trailing comma's get stripped out, regarding of the `trailingComma` setting.

**Comment by CiGit** [comment]
A Repo we could checkout ?

Untitled SCSS file:
Input AND output:
```scss
$spacers: map-merge(
  (
    0: 0,
    1: (
      $spacer * 0.25,
    ),
    2: (
      $spacer * 0.5,
    ),
    3: $spacer,
    4: (
      $spacer * 1.5,
    ),
    5: (
      $spacer * 3,
    ),
  ),
  $spacers
) !default;

$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px,
) !default;
```
