### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SajjadSM** [prettier/prettier-vscode#756]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: [esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/2973954/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by adFedorovich** [comment]
Add this line to .eslintrc.json file, it works for me) 

```
"env": {
	"browser": true
},

```

**Comment by ntotten** [comment]
Duplicate of #676
