### ISSUE TITLE
can we change the double quotation marks to single one?

### ISSUE THREAD

**Issue by hussamzain** [prettier/prettier-vscode#758]
Hi,
Can we change the default settings for `Prettier` when pressing `alt + shift + f` to use the single quotation instead of double one?

current:
"String"

Wants:
'String'

**Comment by alexlouden** [comment]
Yep this is a setting in Prettier - https://prettier.io/docs/en/options.html#quotes

In my `.prettierrc`:

```js
{
  singleQuote: true
}
```

**Comment by CiGit** [comment]
Or in vscode's settings `"prettier.singleQuote": true`
