### ISSUE TITLE
formatting document removes commented lines in TS files

### ISSUE THREAD

**Issue by mspoerry** [prettier/prettier-vscode#760]
So lets say i have this TS class file:
```
export class SomeClass {
  constructor(
    private num1: number,
    private num2: number
    // num3: number
    // num4: number
  ) {
    this.someMethod2(num1, num2);
  }

  someMethod2(
    num1: number,
    num2: number
    // num3: number
    // num4: number
  ) {
    const sum = num1 + num2;
    if (sum > 0) {
      // TODO
    }
  }
}
```

When i format the document with prettier it removes the commented lines in the constructor. Is this intended or is it a bug? From my prospective that's pretty scary. Formatting should never remove code or comment.

Notes:
- Tslint Integration enabled

**Comment by CiGit** [comment]
What do you mean by "remove", I see prettier moving them outside parameters list tho.

**Comment by mspoerry** [comment]
This is what I get after Format Document:
```
export class SomeClass {
  constructor(private num1: number, private num2: number) {
    this.someMethod2(num1, num2);
  }

  someMethod2(
    num1: number,
    num2: number
    // num3: number
    // num4: number
  ) {
    const sum = num1 + num2;
    if (sum > 0) {
      // TODO
    }
  }
}
```

**Comment by CiGit** [comment]
Ca you try without tslint just to be sure. Then find out which tslint rule would do that.

Have you prettier installed in your project? version?

**Comment by mspoerry** [comment]
My extensions are all global. Disabling TSLint did not help in my current project.

I did some more testing with a clean project (new created). And I noticed different behaviors. Disabling TSLint works in a clean project.

So I found out, by removing the tslint.json file in my working project Format Document looks like this:
```
export class SomeClass {
  constructor(private num1: number, private num2: number) // num3: number
  // num4: number
  {
    this.someMethod2(num1, num2);
  }

  someMethod2(
    num1: number,
    num2: number
    // num3: number
    // num4: number
  ) {
    const sum = num1 + num2;
    if (sum > 0) {
      // TODO
    }
  }
}
```

I doesn't look pretty but the comment doesn't get removed. That's fine for me.

I still don't understand how this can happen or should happen.

**Comment by mspoerry** [comment]
Ok in my tslint.json is this rule:
```
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
```

When I remove it Format Document works fine.

**Comment by mspoerry** [comment]
I still think it's a bug. Because the rule has nothing to do with the constructor parameters itself. Just the placing of braces.

**Comment by CiGit** [comment]
This seems to be a problem with tslint. Have you tried `tslint --fix`  only ?

**Comment by mspoerry** [comment]
Yes I did, but nothing happens. Also to mention tslint doesn't mark it as a problem to be fixed.

**Comment by CiGit** [comment]
Well, basically tslint integration is `prettier` followed by `tslint --fix` so I don't get where this could come from.

**Comment by ntotten** [comment]
This is a but on TSLint. Closing here, please open on the TSLint repo if you are still having this problem.
