### ISSUE TITLE
Disable/revert Markdown table formatting?

### ISSUE THREAD

**Issue by politician** [prettier/prettier-vscode#762]
#### What is the problem?

After a recent update, when I save a Markdown  file containing a table, this extension auto-formats it to an expanded mode.  The problem is that I don't want it to do this because I've got a lot of Markdown files containing a lot of tables, and this new behavior is introducing a lot of wide tables that wrap lines.

*Desired Old Format on Save*
```
Name | Description
--- | ---
shortname | this name isn't very long
a much much much longer name | this name is rather long
this name is so long that the text wraps to the next line in my editor | it's pretty jarring xxxxxxx xxxxxxxx xxxxxx  xxxxxxx xxxxxxxx xxxxxx  xxxxxxx xxxxxxxx xxxxxx
```

<img width="1219" alt="Screen Shot 2019-03-21 at 9 40 02 AM" src="https://user-images.githubusercontent.com/1149663/54768862-5d6f7b00-4bbd-11e9-9184-242d90b50d8d.png">

*Worse New Format*
```
| Name                                                                   | Description                                                                                   |
| ---------------------------------------------------------------------- | --------------------------------------------------------------------------------------------- |
| shortname                                                              | this name isn't very long                                                                     |
| a much much much longer name                                           | this name is rather long                                                                      |
| this name is so long that the text wraps to the next line in my editor | it's pretty jarring xxxxxxx xxxxxxxx xxxxxx  xxxxxxx xxxxxxxx xxxxxx  xxxxxxx xxxxxxxx xxxxxx |
```

<img width="1222" alt="Screen Shot 2019-03-21 at 9 40 10 AM" src="https://user-images.githubusercontent.com/1149663/54768861-5d6f7b00-4bbd-11e9-9f7d-8bd550a80a28.png">

#### How can I reproduce it?

Add a table to a markdown file and save.  Th prettier autoformatter formats it. There are no settings to disable this behavior, just the entire language.

**Comment by CiGit** [comment]
You can add a `<!-- prettier-ignore -->` comment above your table.
[Example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRE7YB8AOlAHICGAtnDgD44AInADOYAqTxlobbLkHy2ogBb0YUHn0EwVpUTk28c+qAHIYOAG4UAnjgA20am045uAVzAr3Xn5+9HZwpDLQEcXX1Q4yiCTl0QpygXWD0DIz4o0Qgg5IiVePy+eAAPSwB3OLwDGByEwzgyx1IoTKh3ezgAE1JagnDeswNCYhh7ACtOAkk8krn5kpwFhaXlnFW15fmN7Z3trbm9kpAAGhAIaVJoUWRQKYIIcoAFKYQblE4rCFIu05AAIziYAA1sQAMp4ThgFrUZAwAgeOBnFQwbgOADqengokhYDgYLevVIVl6tmQ4FENzOLVEFBgTzi1G4nGQADNOA5aWdxqISgAhIGgmBgrQAGRacDZHK5IB5JTBMIccAAih4IPApZykSBIQRaQRycyCMCuo8oH9CC0YOifrpkAAOAAMZ0IEFp6Kq5JG+psfyIAEcPKQiAzOEyWUh2VqzrTuKQ4QjtaJFSq1RrI9LtTBOP8bV07UgAExneGcUgOGEAYQg3GZ5LorT+HlpABUc+8o7SAL5doA)

https://github.com/prettier/prettier/pull/5701 should do it in next prettier's version.
