### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by PeterRock** [prettier/prettier-vscode#765]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3013099/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by adFedorovich** [comment]
Add this line to .eslintrc.json file, it works for me) 

```
"env": {
	"browser": true
},

```

**Comment by ntotten** [comment]
Duplicate of #676
