### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by CibiAananth** [prettier/prettier-vscode#769]
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3017631/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

**Comment by ntotten** [comment]
Duplicate of #676
