### ISSUE TITLE
HTML formatting error: Unexpected closing tag "script".

### ISSUE THREAD

**Issue by NickRimer03** [prettier/prettier-vscode#770]
Sample code:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <!-- some DOM -->
  </body>
</html>

<script>
  // some js code
</script>

<script src=../dist/debug.js></script>
```

Output:
```
Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see httpsc:\Projects\air-gsap\debug\debug.html:://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (c:\Projects\air-gsap\debug\debug.html:35:30)
  33 | </script>
  34 | 
> 35 | <script src=../dist/debug.js></script>
     |                              ^
  36 | 
```

According to this error Prettier doesn't format my code. But the code is valid and works correct in browser.
If I will cut off `</script>` Prettier will response with OK. But the code will not work at all.
WAIDW?

**Comment by CreativeNotice** [comment]
Does adding the missing quotes around the script src attribute help?

**Comment by NickRimer03** [comment]
@CreativeNotice 
Yeah! Quotes `<script src="../dist/debug.js"></script>` makes Prettier alive.
I know that we _should not_ to miss quotes but we _can_.
Does missing quotes always prevent Prettier from working normal?

**Comment by CiGit** [comment]
If there is a `/` quotes would help ;-)
