### ISSUE TITLE
Prettier is not working any more? 

### ISSUE THREAD

**Issue by AhmedHalim96** [prettier/prettier-vscode#774]
I think Prettier is not working anymore. I use the latest vscode on windows, I removed all my settings and other extensions just in case and I did  a clean installation still doesn't work
is it just me?

**Comment by Titozzz** [comment]
Duplicate of https://github.com/prettier/prettier-vscode/issues/763 probably

**Comment by CiGit** [comment]
If you call format on save without having specified a default formatter, chances are nothing happens since vscode 1.33

**Comment by lomeat** [comment]
+, dont work Prettier anymore.

**Comment by ntotten** [comment]
Duplicate of #870

**Comment by GregRush** [comment]
Yup, it does nothing. I just wasted so much time trying to debug it...

**Comment by anthonysim** [comment]
Yup stopped working for me and I have no idea how to fix it.

**Comment by dancherb** [comment]
Prettier (and also Beautify) are being completely ignored as extensions for me (including any configurations) - VSCode continues to just use the default formatting for "Format" and "Format on save" (`"editor.defaultFormatter": "esbenp.prettier-vscode"` is set)

**Comment by lomeat** [comment]
Use extension for vs code 'JavaScript and TypeScript Nightly'
