### ISSUE TITLE
brackets questions

### ISSUE THREAD

**Issue by Witee** [prettier/prettier-vscode#779]
Here is my code(js)
```
if (a) { a = 'b'; }
```

after prettier
```
if (a) {
  a = 'b';
}
```

How to not beautify when there is only one expression？
Many thanks.

**Comment by anthropomorphic** [comment]
Just don't put braces?

```javascript
if (a) a = 'b';
```

**Comment by CiGit** [comment]
Prettier will always break a block. but you can `// prettier-ignore` it or use @anthropomorphic 's solution
