### ISSUE TITLE
[Question] Global configuration to remove [OR not add} newline at end of file

### ISSUE THREAD

**Issue by DoCode** [prettier/prettier-vscode#780]
How can we globally (Visual Studio Code) configure Prettier to remove an existing newline at end of file OR not add a new one when not existing, on formatting documents (JSON, JS, Markdown, and so on)?

**Comment by CiGit** [comment]
This is how prettier works. Nothing can be done specifically here.

**Comment by DoCode** [comment]
Shame.
So I wrote an extension that can do this, on interest see [here](https://marketplace.visualstudio.com/items?itemName=DoCode.vscode-remove-final-newlines).
