### ISSUE TITLE
prettier failing with the new update of vs code (1.33)

### ISSUE THREAD

**Issue by timcluyts** [prettier/prettier-vscode#781]
With the new version of VS Code my prettier doesn't format any longer.

from my settings:
`	"[javascript]": {
		"editor.formatOnSave": true,
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	}`

The error I get:
![image](https://user-images.githubusercontent.com/20314637/55621180-1678ac80-579d-11e9-9b84-339ee2d27a6e.png)

![image](https://user-images.githubusercontent.com/20314637/55621209-27292280-579d-11e9-9fd7-b7bc9acbd8b7.png)

EDIT:
It seems to work when I install prettier as a devdependency, of course, I don't want to be doing this on every project.

**Comment by pcate-fls** [comment]
Running into the same issue after updating. Installing prettier as a dev dependency didn't work for me though.

**Comment by pcate-fls** [comment]
Actually, might be related to: https://github.com/prettier/prettier-vscode/issues/763

Downgrading eslint to 5.15.1 seems to fix the issue.

**Comment by timcluyts** [comment]
> Actually, might be related to: #763
> 
> Downgrading eslint to 5.15.1 seems to fix the issue.

Doesn't seem to be that for me. I just tried with ESLint 5.16.0 but that works for me on a second pc. Which is totally weird because I just updated this pc to VSCode 1.33.0 and it works on this one.

Just tried removing node_modules and all and it keeps working. So I'm totally confused as to why it works on the one pc and doesn't on the other. I have the same VSCode setup (using settings sync) and the project is the same as well.

**Comment by burtek** [comment]
@timcluyts _TS&JS lang features` is built-in. Based on the screen I can see that prettier is first on the list, which makes it not work as per issue mentioned above.

**Comment by timcluyts** [comment]
@burtek I set it as default but got the same error described in my original post. (Also, my initial post already has it set as default).
On the issue mentioned, it seems like 1.33.1 will include a fix for this however.

![image](https://user-images.githubusercontent.com/20314637/55860408-72b04780-5b74-11e9-835e-dc9ea5b197eb.png)

**Comment by palmjack** [comment]
I have the same issue with v.1.33.1
Here's my settings.json
```
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true,
"editor.wordWrap": "on",
"editor.autoIndent": true,
```
None of these work, not even autoIndent

**Comment by trcolgrove** [comment]
Same issue, 1.33.1

**Comment by michael-hll** [comment]
I have the same issue with v.1.33.1
We have a big file when formatted the diff shows a huge difference, this is messy. So temporary we disabled the prettier at this moment.

**Comment by xinshangshangxin** [comment]
I also had;

but I uninstall `vsc`, and remove `~/.vscode`
then I install  `vsc v.1.33.1`, it works again

**Comment by michael-hll** [comment]
@xinshangshangxin I tried like your way, seems doesn't work.

**Comment by TidyIQ** [comment]
Same issue here, although it's able to find regular modules just not scoped modules

**Comment by ryanjbonnell** [comment]
This issue seems to be improved by the updates in the [VS Code 1.35 release](https://code.visualstudio.com/updates/v1_35#_notable-improvements) (May 2019):

> This update brings TypeScript language improvements, along with tooling enhancements for both JavaScript and TypeScript. It also fixes a number of important bugs, including fixes for performance issues that some users were seeing when working with styled-components.
>
> When running the Format With... command, the default formatter is now pre-selected.

**The key to fixing this error and having everything working was to set Prettier as the default formatter.**

Here's how I have VS Code and Prettier configured:

<img width="960" src="https://user-images.githubusercontent.com/133372/60290067-c6594400-98cc-11e9-90c5-bf006b8104b6.png">

Here's the relevant part of my `settings.json`:

```json
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true,
"[javascript]": {
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode"
},
"[php]": {
  "editor.defaultFormatter": "fterrag.vscode-php-cs-fixer"
}
```

With this configuration, JavaScript files will be automatically formatted on save by Prettier.

I'm using **VSCode 1.35.1** with **Prettier 1.9.0** on **macOS 10.14.5** "Mojave".

**Comment by drewgaze** [comment]
I had this issue on Windows + WSL, the only way I was able to fix it was to edit the settings.json to define a formatter config for Javascript specifically. Setting prettier as the editor's default formatter didn't work. Thanks @ryanjbonnell .

**Comment by ntotten** [comment]
Is this still happening in version 2.0.0?

**Comment by aofakore** [comment]
Had the same issue, @ryanjbonnell 's solution worked for me
