### ISSUE TITLE
`printWidth` option is ignored

### ISSUE THREAD

**Issue by astupidnerd** [prettier/prettier-vscode#786]
I'm trying to change the `printWidth` to 150 instead of the default of 80. No matter what, it seems to always use the default.

Here's what I've tried.

The relevant settings from my `settings.json`:

```json
{
  "prettier.singleQuote": true,
  "prettier.printWidth": 150,
  "editor.wordWrapColumn": 150,
  "editor.minimap.maxColumn": 150,
  "yaml.format.printWidth": 150,
  "html.format.wrapLineLength": 150,
  "editor.rulers": [150],
  "prettier.eslintIntegration": false,
  "prettier.tslintIntegration": false,
  "javascript.format.enable": true
}
```

That didn't work, so I also created a `.prettierrc` file in my project's root directory and my home directory:

```json
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "useTabs": false,
  "singleQuote": true,
  "printWidth": 150,
  "bracketSpacing": true,
}
```

Still nothing, so I also created a `.editorconfig` file in both the project root and my home directory:

```
max_line_length = 150
```

Before format:
![image](https://user-images.githubusercontent.com/48503011/55674308-e8ac6a00-5867-11e9-9a70-66ce5dd2bbdd.png)

After format:
![image](https://user-images.githubusercontent.com/48503011/55674313-f7931c80-5867-11e9-9254-c5143d9926b9.png)

I'm not sure what else I'm supposed to do to get this to work. Any help is greatly appreciated!

**Comment by CiGit** [comment]
Prettier will break multiple call (3+ I think) onto multiple line
