### ISSUE TITLE
Using prettier-tslint together with prettier-eslint produces unexpected results

### ISSUE THREAD

**Issue by karol-majewski** [prettier/prettier-vscode#787]
Hello and thank you for your work. I've noticed some unexpected behavior and I was wondering whether it was intentional or not.

In my project, ESLint is used to lint both JavaScript and TypeScript code.

##### `.eslintrc.js`

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module'
  },
  plugins: ['@typescript-eslint'],
  rules: {
    quotes: [2, 'single', { avoidEscape: true }]
  }
};
```

##### `.prettierrc`

```json
{
  "trailingComma": "all",
  "printWidth": 100,
  "tabWidth": 2
}
```

##### `~/Library/Application Support/Code/User/settings.json`

```json
    ...
    "prettier.stylelintIntegration": true,
    "prettier.requireConfig": true,
    "prettier.tslintIntegration": true,
    "prettier.eslintIntegration": true,
    ...
```

**Important**: as you can see, I have both `tslintIntegration` and `eslintIntegration`enabled in my global Visual Studio Code settings.

### Problem

When I run the extension (either manually or by saving the file), all my single quotes are converted into double quotes, despite the ESLint config stating otherwise.

When I disable `"prettier.tslintIntegration"`, the extension works as expected.

### Question

My understanding is: 

1. `prettier-tslint` is prioritized over `prettier-eslint`.
1. Since there is no `tslint.json` file present in the repository, `prettier-tslint` looks for `.prettierrc`. 
1. It finds `.prettierrc`, but because it doesn't override the default setting for `singleQuote` (which is `false` ≡ use double quotes), the default setting is used.

Is that intended? It was a bit problematic for me to find out about it. I had both integrations enabled in my global settings, and in this specific project, the extension started to behave in a weird way.

If it is intended indeed than perhaps it would be a good idea to make it explicit in the README (which I can do).

Please let me know what you think.

**Comment by CiGit** [comment]
TSLint is prioritized for ts files. PR welcome :-)

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
