### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by smanwarulislam** [prettier/prettier-vscode#789]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Windows_NT x64 6.3.9600`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\emu\esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Please attach the stack trace and reopen.
