### ISSUE TITLE
How can prevent split into multiples lines brackets ? TS

### ISSUE THREAD

**Issue by Cazs03** [prettier/prettier-vscode#791]
For now i have this
```
this.globalApplicationService.sidebarService.sidebarFiltersModel.values[
        'idItem'
      ]
```

And I'm want
`this.globalApplicationService.sidebarService.sidebarFiltersModel.values['idItem']
`

This format is more readable and confortable

**Comment by CiGit** [comment]
You can increase printWidth but you will hit the same problem a little later... This is how prettier works.
