### ISSUE TITLE
Prettier not work

### ISSUE THREAD

**Issue by Nuxsby** [prettier/prettier-vscode#792]
Hi,

I use Prettier all the time but, since 2 days, it doesn't work.
It doesn't format on save, doesn't add semicolon etc...

Do you have any idea ?

**Comment by coliff** [comment]
If reporting bugs it's best if you provide more details to help troubleshoot the issue. What version of VS Code are you using? What platform are you running VS Code on?
The recent update to VS Code allows you to change the default formatter. Maybe you haven't set it as Prettier yet? Seee: https://code.visualstudio.com/updates/v1_33#_default-formatter-selection

**Comment by zekth** [comment]
Having the same issue on VsCode 1.33.1 .
Nothing is happening on save or on format command. Also nothing in the `Prettier` output
```json
{
    "workbench.colorTheme": "Dracula",
    "workbench.iconTheme": "vscode-icons",
    "window.zoomLevel": -1,
    "terminal.external.windowsExec": "C:\\Program Files\\Git\\git-bash.exe",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "breadcrumbs.enabled": true,
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true
}
```

**Comment by CiGit** [comment]
@zekth Can you check developer console?

**Comment by pcjmfranken** [comment]
Same issue here on 1.9.0, nothing in dev console on formatting.

Format Selection does seem to work.
