### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dmcclccam** [prettier/prettier-vscode#793]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Linux x64 4.9.0-8-amd64`
- VSCode version: `1.33.0`

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://pastebin.com/raw/GxHpyk2y)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Duplicate of #676
