### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ajrussellaudio** [prettier/prettier-vscode#799]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3088463/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by hegelstad** [comment]
**For JS + TypeScript users:**
I managed to fix this by following this guide to set up typescript-eslint together with prettier:
https://medium.com/@dors718/linting-your-react-typescript-project-with-eslint-and-prettier-2423170c3d42

**Comment by ajrussellaudio** [comment]
Thanks. Looks like a good article, but I'm not using TypeScript or Create React App in the project that is giving me issues.

**Comment by nikolasFreitas** [comment]
> Thanks. Looks like a good article, but I'm not using TypeScript or Create React App in the project that is giving me issues.

But the caches Typescript is because of the VSCODE. It is build in Typescript. You can clean the .cache to try get some performance.

**Comment by ajrussellaudio** [comment]
This seems to have been caused by performance issues in the version of TypeScript 3.4 used by VS Code. Rolling back to TypeScript 3.3 globally, and telling VS Code to use the global TypeScript, solved this issue.

For anyone dropping in from a search:

```
npm install --global typescript@3.3.4000
npm list -g typescript
```

Copy the path from the output of the last command. Then in VS Code edit `settings.json` with:

```json
"typescript.tsdk": "/path/you/just/copied/node_modules/typescript/lib"
```
