### ISSUE TITLE
Breaking SCSS mixin

### ISSUE THREAD

**Issue by joneslloyd** [prettier/prettier-vscode#801]
Hi guys,

I have a SCSS mixin called `responsive-properties` (to help with media queries) :
https://gist.github.com/joneslloyd/17ddf3c372627e2cfdd81eca8eefe79b

However, when I save an SCSS file containing this mixin, the code containing the mixin call is changed from (for example) this:
```
@include responsive-properties(((padding-left, (v: $spacer-x, v-md-up: 0)), (padding-right, (v: $spacer-x, v-md-up: 0)), (margin-left, (v: ($grid-gutter-width / -1), v-sm-up: ($grid-gutter-width / -2), v-md-up: 0)), (margin-right, (v: ($grid-gutter-width / -1), v-sm-up: ($grid-gutter-width / -2), v-md-up: 0)),));
```

To this:
```
@include responsive-properties(
    (
      (padding-left, (v: $spacer-x, v-md-up: 0)),
      (padding-right, (v: $spacer-x, v-md-up: 0)),
      (
        margin-left,
        (
          v: (
            $grid-gutter-width / -1
          ),
          v-sm-up: (
            $grid-gutter-width / -2
          ),
          v-md-up: 0
        )
      ),
      (
        margin-right,
        (
          v: (
            $grid-gutter-width / -1
          ),
          v-sm-up: (
            $grid-gutter-width / -2
          ),
          v-md-up: 0
        )
      )
    )
  );
```

And it will no longer compile. I get the error:
```
ERROR in ./styles/main.scss
Module build failed: ModuleBuildError: Module build failed:
    @if (map-has-key($attribute, v) and (index($actual-media-queries, v) == null)) {
        ^
      Argument `$map` of `map-has-key($map, $key)` must be a map
```

To be clear: It does compile perfectly without the reformatting that Prettier applies.

Do you know how to prevent this from happening?

**Comment by CiGit** [comment]
A prettier ignore comment can help as a workaround

I've little knowledge of SCSS but isn't that an error with your compiler ?

Let's try to ask @evilebottnawi , Seems to me you take care of that in prettier ;-)

**Comment by evilebottnawi** [comment]
Error point on other problem, need reproducible test repo

**Comment by joneslloyd** [comment]
Thanks for the replies!

Prettier Vscode is configured to use stylelint:

```
"prettier.stylelintIntegration": true,
```

But stylelint shouldn't be breaking the SCSS mixin (with map parameters) over multiple lines, so I thought that maybe Prettier was somehow responsible or misinterpreting the stylelint stuff.

In that case, I'll take this up with stylelint 🙂

Thanks for your  help

**Comment by evilebottnawi** [comment]
Anyway can you provide example, looks like a bug, we need fix it

**Comment by joneslloyd** [comment]
I can't give any full source code as it's part of a commercial project. I can give a particular SCSS file that causes the error though, if that helps?

**Comment by joneslloyd** [comment]
I believe the issue is with Prettier – See this Issue: https://github.com/stylelint/stylelint/issues/4058
