### ISSUE TITLE
Prettier isn't configurable without .prettierrc

### ISSUE THREAD

**Issue by zebralight** [prettier/prettier-vscode#802]
Using VS Code v1.33.1
OS: macOS Mojave
v1.8.1
I'd like to configure prettier without the use of any config file, especially to avoid making changes to repositories that don't have them already.  While I say `.prettierrc`, I mean configuration files in general.  Unfortunately, my prettier configuration does not eventually fall back to the vs code settings as expected.  It's getting the rules somewhere but making changes through the vs code settings shows no changes to them.  My linter seems to pick up the issues just fine however and it works as expected when using a file. And unfortunately, I'm stuck at the default settings which aren't compatible with my needs.
 Any help around this would be much appreciated.

If there's another way to just modify the settings file that is used for prettier, so I'm not stuck with the default settings would be great.

**Comment by CiGit** [comment]
Settings are also taken from editorconfig files, but you can configure the rest in vscode's `prettier.*` settings.

**Comment by zebralight** [comment]
For some reason, for projects that don't use these files, I expect that it follows the behavior you, I, and https://github.com/prettier/prettier-vscode#settings described which would ultimately fallback to the configs, but...it doesn't:
![Alt Text](https://imgur.com/a/bo8c3Ze)

**Comment by CiGit** [comment]
What I see is you are using prettier through eslint. This extension and its settings have nothing to do with it.

**Comment by zebralight** [comment]
To isolate the issue, here's another example of a javascript file that isn't `npm init`ed with no dependencies installed.  This exhibits the same behavior of trying to enforce the single quote rule regardless of whether it's enabled or not in the settings.

[Imgur](https://i.imgur.com/8DrVTbG.gifv)

**Comment by CiGit** [comment]
You may have a prettier config file upwards your fs tree.
Are you using eslintIntegration ? in which case you may also have an eslint config file somewhere which we read from.

**Comment by zebralight** [comment]
there was indeed a rogue `.prettierrc` upwards my fs tree!  Thank you so much!
