### ISSUE TITLE
Missing quotes always prevent Prettier from working normal

### ISSUE THREAD

**Issue by NickRimer03** [prettier/prettier-vscode#804]
Code sample:
```html
<unit use = url(gamex-web-module/loader)></unit>
<unit use = url(gamex-web-module/header)></unit>
```
Error message:
```Unexpected closing tag "unit". It may happen when the tag has already been closed by another tag.)
  3 |     <unit use = url(gamex-web-module/loader)></unit>
> 4 |     <unit use = url(gamex-web-module/header)></unit>
    |                                              ^
```
Prettier always falls with error `Unexpected closing tag` if there are no quotes around property value.
First, quotes are not strongly necessary just recommended.
Second, error message disorients user due to false text.

Do not point your attention on tag `unit`. It happens with other tags too, e.g. `<script>`.

**Comment by CiGit** [comment]
I would say `/` is what makes it fail without quote. Unquoted values, which do not fail, will end quoted anyway.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
