### ISSUE TITLE
Ignore prettierconfig changes after open project

### ISSUE THREAD

**Issue by victorzhuk** [prettier/prettier-vscode#806]
When editor is runnig and you try to change some options in prettierconfig they will be ignored, editor restart helps and all works fine.

Reproduce (with some js):
* run editor with some prettierconfig file? for example set printWidth to 80
* input any code string longer 80
* setup eslint with autofix on save, and configure prettier extend and prettier plugin
* save file. as result you can notice that prettier format string as 80 length, bun eslint print error because expect line without shifts
* reload widow with command pallete
* try the same - all works fine

#633 #786

**Comment by CiGit** [comment]
What kind of prettierconfig file are you using?
I don't get what you did between eslint and prettier. 
Any repository to check this out?

**Comment by victorzhuk** [comment]
https://github.com/victorzhuk/prettier-issue806-playground

what to do:
* load project with vscode
* open index.js
* tap `ctrl+shift+I` or `ctrl+s`, both eslint and prettier should reformat quotes to double. save results
* change `"singleQuote": false` -> `"singleQuote": true` in `.prettierrc`
* try save or format again

Expect: plugin watch config changes and reformat index.js again
