### ISSUE TITLE
html formatting tags not found

### ISSUE THREAD

**Issue by Sukruthap** [prettier/prettier-vscode#807]
Issue Type: <b>Bug</b>

I am not getting suggestion of html for coding need to type the html tags

Extension version: 1.8.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.95GB (0.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by CiGit** [comment]
This extension doesn't provide any suggestion. Wrong repository?
