### ISSUE TITLE
Formatting on save is actually happening after save

### ISSUE THREAD

**Issue by LMulvey** [prettier/prettier-vscode#808]
- VSCode Version: 1.33.1
- OS Version: Mac OS 10.13.6 High Sierra
- Plugin version: 1.8.1

Steps to Reproduce:

1. Open a JavaScript file with `prettier-vscode` running
2. Ensure formatOnSave is enabled
3. Make a change that does not adhere to the Prettier settings (priming it to format on save)
4. Save the file.

The file will save, and then format, causing unsaved changes to occur.

![example gif](https://user-images.githubusercontent.com/16218249/56390060-55205500-61e8-11e9-9a2e-efa75cf004e0.gif)

**Comment by hoomjac** [comment]
I encounter the same problem, driving me nuts. I have to uninstall the prettier to solve it

**Comment by xiyanZ** [comment]
me too

**Comment by CiGit** [comment]
Can you check your developer's console and see if you have a message in it? Seems to be VSCode's fault to me :-)

**Comment by LMulvey** [comment]
You were absolutely right. It seems that another extension was throwing an error and causing a delay to the prettier extension. I disabled said extension and things have been running smoothly since. 

Thanks!
