### ISSUE TITLE
Respect editorconfig specs

### ISSUE THREAD

**Issue by AndreasHassing** [prettier/prettier-vscode#81]
As stated in https://github.com/prettier/prettier/issues/42 and https://github.com/prettier/prettier-atom/issues/90, it would be great to have prettier surrender to the specs defined in a project-wise `.editorconfig` file.

**Comment by esbenp** [comment]
Makes sense, however we will probably hold off and see if this will be implemented at `prettier` or if this should be implemented by the editor plugins (us and `prettier-atom`). We will follow the `prettier` discussion and see.

**Comment by CiGit** [comment]
Is this really feasible? Options are missing in editorConfig but are in prettier (semi). The opposite is also true (a lot).
#70 seems a lot more promising to me.

**Comment by Alber70g** [comment]
How is #70 an alternative? Of course there are options missing in .editorconfig, but if it would at least 'obey' the options that are available, that would be nice.

**Comment by CiGit** [comment]
It's an alternative to share a config. But of course nothing to do with editorconfig.
The missing part means it would require to set configuration in different files or accept default values.
I'm not closed to it ;-) just not that convinced.

**Comment by wiredearp** [comment]
The `.editorconfig` also serves to control the code presentation on GitHub, it is especially important if you use tabs (because tab width otherwise defaults to`8`), so one could argue that you anyways need to add this file and then copy the settings from Prettier (unless Prettier would consume the settings from `editorconfig`, of couse). And then my editor also reads the `.editorconfig` and adjusts tabs and spaces automatically, so with this enhancement, all this presentation would only need a single configuration.

**Comment by thorn0** [comment]
This extension should simply use the current active settings of VS Code regarding indentation. The editorconfig extension just changes those settings, so we'll get the compatibility with it automatically then

Why have prettier indent code using say 2 spaces in an editor that inserts say 4 spaces when tab is pressed?

**Comment by CiGit** [comment]
Was exactly thinking about it. #34 was already about that. is editor config updating those options?

**Comment by thorn0** [comment]
> is editor config updating those options?

I don't know how it works internally, but at least it appears so.

**Comment by thorn0** [comment]
I checked [its code](https://github.com/editorconfig/editorconfig-vscode/tree/master/src), and yes, that's exactly how it works: it controls the 2 options - `insertSpaces` and `tabSize`.

**Comment by CiGit** [comment]
Good news here, reading editorconfig is *certainly* coming in next prettier version (1.9)
