### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mende** [prettier/prettier-vscode#814]
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3118013/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.8.1`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

`esbenp.prettier-vscode-unresponsive.cpuprofile.txt` attached.

**Comment by ntotten** [comment]
Duplicate of #676
