### ISSUE TITLE
My prettier.eslintIntegration not working

### ISSUE THREAD

**Issue by mauriciord** [prettier/prettier-vscode#815]
Today my `prettier.eslintIntegration` is not working anymore, it's applying the default prettier config and not respecting my `.eslintrc.json` file, even with the `"prettier.eslintIntegration": true`

- Extension Name: prettier-vscode
- Extension Version: 1.8.1
- OS Version: macOS Mojave 10.14.4
- VSCode version: 1.33.1

My project has:
```json
"prettier-eslint": "^8.8.2",
"prettier-eslint-cli": "^4.7.1",
```

**Comment by diegoaguilar** [comment]
@mauriciord Did you find a workaround for this?

I got under dev dependencies `"prettier-eslint": "^8.8.2"` too, not really adding the cli package. I don't have any local `.eslintrc` or config file but installed it globally.

When I save it runs prettier formatting but won't run `eslint --fix` keeping prettier defaults and falling into a few eslint conflicts.
