### ISSUE TITLE
Files aren't formatted when in a folder starting with a dot

### ISSUE THREAD

**Issue by Floriferous** [prettier/prettier-vscode#818]
When a folder starts with a dot, prettier is ignoring the eslint config, I tried to edit `.eslintignore` and `.prettierignore` without luck.

`.eslintignore` does need a rule `!/.*` to activate in dot folders, but prettier does not care about it apparently.

Here's a simple reproduction: https://github.com/Floriferous/prettier-vscode-dot-folders

**Comment by ntotten** [comment]
I just tried this out and I am not able to reproduce this. Can you provide more information on which version of the extension, vs code and OS you are using?
