### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Yggdrasil09** [prettier/prettier-vscode#821]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.9.0`
- OS Version: `Linux x64 5.0.0-13-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/hp/esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Please attach the stack trace and reopen.
