### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by anganevagg** [prettier/prettier-vscode#822]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Anganevagg\esbenp.prettier-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Please attach the stack trace and reopen.
