### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cezarneaga** [prettier/prettier-vscode#824]
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3147818/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.9.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

**Comment by ntotten** [comment]
Duplicate of #676
