### ISSUE TITLE
eslintIntegration with jsxSingleQuote doesn't work

### ISSUE THREAD

**Issue by svipas** [prettier/prettier-vscode#839]
If `"prettier.eslintIntegration": true,` is enabled this config doesn't work `"prettier.jsxSingleQuote": true,` even if `true` it treats it like `false` with `eslintIntegration`.

The expected behavior would be to respect `prettier.jsxSingleQuote` even if `prettier.eslintIntegration": true` and there is no eslint in project.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
