### ISSUE TITLE
Can't disable the /> for void elements

### ISSUE THREAD

**Issue by MagmaTech12** [prettier/prettier-vscode#843]
The title and image pretty much explain the issue. I really dislike the way void elements are ended with prettier and honestly surprised there's no way to disable that. Is there any way to fix it, or am I just stuck with this format?
![d672d1c4e2152f664ca8c2e627cfed5c](https://user-images.githubusercontent.com/41936162/58605270-368c8f80-8265-11e9-88c1-6520eb0ccd5c.png)

**Comment by bmalehorn** [comment]
Short answer: yes you're stuck with this.

Long answer: this is the wrong git repo to ask this question. This git repo is for the VSCode extension to use the (separate) prettier utility. You're looking for https://github.com/prettier/prettier/, which actually controls how the formatting works.

Long long answer: The point of prettier is to have a standard style everyone uses. The goal isn't to format your code like you prefer writing it, but to format everyone's code the exact same way. So I don't think you'll be able to convince the prettier authors to change it.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
