### ISSUE TITLE
Is not applying changes from 1.16

### ISSUE THREAD

**Issue by brentluna** [prettier/prettier-vscode#844]
This commit was part of 1.16, yet this plugin(1.19) is still formatting `useEffect` in the old 1.15 prettier way, on  

https://github.com/prettier/prettier/pull/5608

**Comment by zomars** [comment]
I'm having this issue also

**Comment by ntotten** [comment]
The extension now uses the latest version of prettier and this should be fixed. Please reopen if you are still seeing this.

**Comment by brentluna** [comment]
@ntotten I'm still seeing it. Has the updated extension been published? VS Marketplace says the extension is on 1.9, last updated 4/26/19. Thanks
