### ISSUE TITLE
why are "prettier.tslintIntegration" and "prettier.eslintIntegration" off by default?

### ISSUE THREAD

**Issue by jasonwilliams** [prettier/prettier-vscode#849]
Like the title says, im curious to know why these are off by default.
Would most users want tslint/eslint integration out of the box if there's config setup in the project?

Took me a while to realise these were off.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
