### ISSUE TITLE
Missing configuration file for scss 

### ISSUE THREAD

**Issue by pattiereaves** [prettier/prettier-vscode#851]
When I use the prettier-stylelint option, I have an ✖️next to prettier in the status bar and I get the following console message:

```
No configuration provided for [path to file]
```

This is the case regardless of whether its a css or an scss file. 

The stylelint extension is working fine — I can see the errors in my stylesheet. 

I don't see any option in this plugins configuration to point it to the stylelint.config.js file, which is not in the root of my project. 

I don't have any other code formatting plugins enabled other than prettier.

I'm using vscode 1.35 and prettier 1.9.

**Comment by patrickcate** [comment]
I've run into the same issue.

**Comment by renestalder** [comment]
I have the same issue with CSS since one of the latest updates. Even though I have a prettier config in my project, it tells me, that there was no config provided. Also, this worked before, so I guess this was introduced with one of the latest updates.

**Comment by kanlukasz** [comment]
The same:
![obraz](https://user-images.githubusercontent.com/30685349/63017837-9b847880-be97-11e9-967b-1a320f2e720a.png)

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
