### ISSUE TITLE
prettier didn't work when use type assertion 'as' in .tsx files

### ISSUE THREAD

**Issue by xinkule** [prettier/prettier-vscode#852]
os: macOS Mojave 10.14.5
vscode: 1.34.0
prettier: 1.9.0

I just found out when I write code like 
```typescript
const a = b as string;
```
It seems like when I use the 'as' keyword, the vscode-prettier doesn't work anymore.

**Comment by zavarka** [comment]
Prettier-vscode appears to have outdated dependencies.  See the workaround in [https://github.com/prettier/prettier-eslint/issues/213](url)

**Comment by ntotten** [comment]
https://github.com/prettier/prettier-vscode/issues/url
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
