### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by chouhanv** [prettier/prettier-vscode#853]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.9.0`
- OS Version: `Linux x64 4.4.0-141-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/user/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ntotten** [comment]
Please attache the stack trace.
