### ISSUE TITLE
EslintIntegration does not work with vue files

### ISSUE THREAD

**Issue by ymdhrk** [prettier/prettier-vscode#854]
Even though `prettier.eslintIntegration` is enabled, `eslint -fix` is not applied but only prettier is applied.
I think most issues related with vue are in the same situation.

After a lot of digging, I finaly found out what caused this issue.

## How this issue occured

1.  vue project is created with `vue cli`

    - The default parser option for eslint is configured as below

    ```
    "parser":"vue-eslint-parser"
    "parserOptions": {
      "parser": "babel-eslint"
    }
    ```

2.  `prettier-vscode` format the vue file with eslintintegration

    - `prettier-vscode` call bundled `eslint-prettier`
    - bundled `eslint-prettier` call bundled `vue-eslint-parser` regardless of user's settings
    - bundled `vue-eslint-parser` can't resolve `babel-eslint` in `parserOptions.parser` because `babel-eslint` is not bundled with `prettier-vscode` and `eslint-prettier`
    - `eslint -fix` stop with the error, so only `prettir` is applied

## solution

`eslint-prettir` should not overwritte the parser that user provided.
Fortunately the `eslint-prettir` problem is fixed by [the latest release](<https://github.com/prettier/prettier-eslint/releases/tag/v9.0.0>).

So the solution for `prettier-vscode` is to update `eslint-prettir` version to 9.0.0.

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
