### ISSUE TITLE
Remove Prettier in the bottom bar

### ISSUE THREAD

**Issue by musm** [prettier/prettier-vscode#857]
How do I disable the extra highlighted icon in the bottom bar?
![image](https://user-images.githubusercontent.com/4319522/59970077-a5d76580-952b-11e9-8a2a-8efb24774a9d.png)

**Comment by kachkaev** [comment]
@musm why do you want to disable it?

**Comment by musm** [comment]
Takes up unnecessary space in the status bar.

**Comment by kachkaev** [comment]
What are you planning to use this space for? How do you turn off other statuses in this part of the footer?

**Comment by musm** [comment]
without the plugin
![image](https://user-images.githubusercontent.com/4319522/59980691-63636680-95c7-11e9-8ecf-1d93baee206d.png)

with the plugin
![image](https://user-images.githubusercontent.com/4319522/59980695-6b230b00-95c7-11e9-9826-c1ff3bf94ad6.png)


It's unnecessary noise to add it to the status bar

**Comment by Devin-Chaves** [comment]
Can you keep it and actually make it bigger? And with a flashing checkmark?

**Comment by musm** [comment]
A simple configuration option would be welcome.

**Comment by David-Else** [comment]
There is no need, you can hide what you want in the status bar with the latest vs code 1.36
https://code.visualstudio.com/updates/v1_36#_hide-individual-status-bar-items

**Comment by kachkaev** [comment]
@musm does @David-Else's solution work for you? Feel free to close this issue if the answer is yes 🙂

**Comment by musm** [comment]
yep
