### ISSUE TITLE
Prettier not active on Ubuntu 18.04 & VSCode 1.35.1

### ISSUE THREAD

**Issue by Bram-Zijp** [prettier/prettier-vscode#862]
On my Windows and Mac this plugin works fine. However on my Ubuntu machine it is not activated. This can be noticed as no formatting is done. Also, when I open the Output tab, the dropdown (which states Tasks by default) does not include Prettier. It is shown however on Windows and Mac. The VSCode settings are identical in all environments.

**Comment by ntotten** [comment]
Did you get any error message?
