### ISSUE TITLE
Can't install eslint-plugin-node in local

### ISSUE THREAD

**Issue by acmilank22** [prettier/prettier-vscode#863]
node 12.4.0

npm 6.9.0

eslint 6.0.1

eslint-plugin-node 9.1.0

prettier-vscode latest

---

```shell
npm i -D eslint-plugin-node
``` 

---

prettier-vscode output

```shell
Failed to load plugin 'node' declared in 'CLIOptions'/foo/bar.js:: Cannot find module 'eslint-plugin-node'
Require stack:
- /__placeholder__.js
```

---

if I uninstall eslint-plugin-node, prettier-vscode will be OK.

**Comment by jimblue** [comment]
same problem here!

**Comment by chengjia080787** [comment]
same problem!

**Comment by PeterRock** [comment]
[ESLint fails to load plugins when using ESLint 6.x #696
](https://github.com/microsoft/vscode-eslint/issues/696)

**Comment by ntotten** [comment]
Duplicate of #870
