### ISSUE TITLE
Recognize global installed Eslint

### ISSUE THREAD

**Issue by HaoyangFan** [prettier/prettier-vscode#864]
Thanks for this amazing package for beautifying my code ❤️ As, I am reading through the write-up, I notice that it mentions **eslint, tslint, and all peer dependencies required by your specific configuration must be installed locally**

Currently I only have Eslint globally installed on my Mac (`sudo npm install -g eslint`), if I understand correctly, does it mean that prettier plugin cannot work properly with this globally installed Eslint, even if I enable `prettier.eslintIntegration`?

For example, for the current project I am working on, do I have to install Eslint again locally to make it work?

Thanks

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
