### ISSUE TITLE
Support for microsoft/vscode-remote-release

### ISSUE THREAD

**Issue by Morgy93** [prettier/prettier-vscode#866]
Would it be possible to make this extension compatible with https://github.com/microsoft/vscode-remote-release so that it can run as an ui extension?

Long explanation: 
>When an extension is ran as UI extension, then the extension needs to explicitly support it. When run as a UI extension then the extension cannot access workspace files. We have an API proposal that enables an extension to access files through a file system provider.
https://github.com/microsoft/vscode-remote-release/issues/867#issuecomment-507044598

**Comment by ntotten** [comment]
I have tested this out and it works as expected on remote development. If you are seeing an error please open a bug with repro steps.
