### ISSUE TITLE
How to run prettier after eslint?

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier-vscode#868]
I enable the "Eslint Integration" option, but when I save a file, it seems to run prettier first, followed by eslint.

I also tried the ESLint plugin, and enabled format on save, and disabled the eslint integration in the prettier plugin, but the result is the same.

Can we configure it to run eslint first, then prettier?

I do see that `prettier-eslint` has a `prettierLast` option, but I don't see how to configure that in VS Code.

**Comment by IanRohde** [comment]
@trusktr Have you looked into `eslint-config-prettier`?

https://prettier.io/docs/en/integrating-with-linters.html#eslint

**Comment by ntotten** [comment]
Not an issue. Please use stackoverflow or other forums for help.
