### ISSUE TITLE
Failed to load plugin 'standard' declared

### ISSUE THREAD

**Issue by ldwqh0** [prettier/prettier-vscode#869]
when I set   "prettier.eslintIntegration": true

then the error happend in VSCode

```bash
Failed to load plugin 'standard' declared in 'CLIOptions'd:\Users\LiDong\Projects\xyyh-git\edc\web\src\c.js:: Cannot find module 'eslint-plugin-standard'
Require stack:
- D:\Users\LiDong\AppData\Local\Programs\Microsoft VS Code\__placeholder__.js
```

i installed eslint and eslint-plugin-standard in node_modules

**Comment by nashaofu** [comment]
same problem,Seems to be caused by eslint upgrade to 6.

**Comment by jimblue** [comment]
Ya same problem too since I've updgrade to eslint 6

**Comment by alexbassy** [comment]
Disabling `prettier.eslintIntegration": true` seemed to fix this for me

**Comment by BernardoFBBraga** [comment]
I also had this problem and rolled back my eslint version. alexbassy's solution worked but turned off prettier which was not an option for me :P

**Comment by ntotten** [comment]
Duplicate of #870
