### ISSUE TITLE
Prettier plugin disables VS code ability to save as 4 spaces

### ISSUE THREAD

**Issue by unyo** [prettier/prettier-vscode#871]
I was trying to figure out why VSCode was saving a previously-formatted as 4 space indent as 2 space indent no matter which setting was selected in the status bar. Apparently the "Prettier" vscode extension is the cause, and I've removed it from my installation.

https://stackoverflow.com/a/51600471/2077884

**Comment by ntotten** [comment]
This doesn't look like a bug. The extension was working as intended. You can disable it per workspace or in the settings.
