### ISSUE TITLE
Doesn't respect all prettier config file types

### ISSUE THREAD

**Issue by runspired** [prettier/prettier-vscode#872]
For instance, a `.prettierrc` file will have its config read but a `.prettierrc.js` file will not. Both are valid: https://prettier.io/docs/en/configuration.html

**Comment by ntotten** [comment]
I am not able to reproduce this. I added tests for this in b31fbe057e1eec02f20b8a055d12954f4a23b7f7. If you can reproduce this please provide more information such as vscode version, which other plugins installed, and a sample repo.
