### ISSUE TITLE
Unnecessary formatting

### ISSUE THREAD

**Issue by liyuhang1997** [prettier/prettier-vscode#873]
When I type the following in the Markdown file

```bash
- 1
- 2
- 3
- 4
```

Prettier will format to:

```bash
-   1
-   2
-   3
-   4
```

When I change `"prettier.tabWidth": 4` to `"prettier.tabWidth": 2`, everything is OK.

I don't need Prettier to do anything for the list, how to turn off this feature?

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
