### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LeonardoJaques** [prettier/prettier-vscode#874]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `1.9.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/leonardojaques/esbenp.prettier-vscode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by baurine** [comment]
I have a similar issue, and the vscode lost response after I typing the format code shortcut. I reported the issue in vscode project: https://github.com/microsoft/vscode/issues/77611

**Comment by sandy2196** [comment]
Does anyone got any solution???

**Comment by ntotten** [comment]
Please upload the log file for the bug report. Without that, we cannot diagnose.
