### ISSUE TITLE
wrong formatting for event handler in polymer

### ISSUE THREAD

**Issue by sndpbohra** [prettier/prettier-vscode#875]
I am using prettier-code formatter plugin in VSCode to format polymer files.
When I try to format, it enclosed event handler in parentheses which makes them unable to find by polymer parser. this is happening only when property is prefixed with "on-".

Code to Format
<mycomp prop1="{{value1}}" prop2="[[value2]]" porp3="value3" onprop4="value4" on-prop5="value5"></mycomp>

in this value5 is event handler

after format
<mycomp
    prop1="{{value1}}"
    prop2="[[value2]]"
    porp3="value3"
    onprop4="value4"
    on-prop5="(value5)"
>
</mycomp>

desired formatting

<mycomp
    prop1="{{value1}}"
    prop2="[[value2]]"
    porp3="value3"
    onprop4="value4"
    on-prop5="value5">
</mycomp>

see the difference in on-prop5 property value formatting

**Comment by ntotten** [comment]
This looks like an an issue for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
