### ISSUE TITLE
There is no document formatter for 'javascriptreact'-files installed.

### ISSUE THREAD

**Issue by JonathanBarrett92** [prettier/prettier-vscode#876]
I've tried restarting VS Code and reinstalling the plugin to no avail. It worked consistently up until today and I've changed nothing in regards to my setup since then. All settings are pretty much default for the plugin too except for tab spacing.

**Comment by idbartosz** [comment]
Probably related to https://github.com/prettier/prettier-vscode/issues/870 - leave 👍there to show authors that it should be fixed ASAP

**Comment by ntotten** [comment]
I'm assuming this is related to #870, otherwise please add repro steps and a sample repository.
