### ISSUE TITLE
Configuration option for prettier-eslint

### ISSUE THREAD

**Issue by maxdubrinsky** [prettier/prettier-vscode#877]
I'm working in a bit of a non-standard environment and require the ability to set some options for `prettier-eslint`. Would it be possible to add an option for sending a config object to `prettier-eslint` when `prettier.eslintIntegration` is enabled?

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
