### ISSUE TITLE
Pass filepath to prettier

### ISSUE THREAD

**Issue by remcohaszing** [prettier/prettier-vscode#878]
I created matzkoh/prettier-plugin-packagejson#5. This checks for the `filepath` property before running the prettier plugin. However, this caused matzkoh/prettier-plugin-packagejson#6.

I added some logging for the options in `preprocess`. When running this using VSCode it turns the `preprocess` doesn’t receive the `filepath` property.

```jsonc
{
  "parser": "json-stringify",
  "useTabs": false,
  "tabWidth": 2,
  "printWidth": 100,
  "endOfLine": "lf",
  "proseWrap": "always",
  "singleQuote": true,
  "trailingComma": "all",
  "plugins": [
    // truncated
  ],
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "cursorOffset": -1,
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "pluginSearchDirs": [],
  "quoteProps": "as-needed",
  "rangeEnd": 5697,
  "rangeStart": 0,
  "requirePragma": false,
  "semi": true,
  "astFormat": "estree-json",
  "printer": {}
}
```

**Comment by ntotten** [comment]
I believe this issue is because we dont yet support plugins. That will be coming in the next release.
