### ISSUE TITLE
Optional chaining operator

### ISSUE THREAD

**Issue by lucasfeliciano** [prettier/prettier-vscode#885]
Optional chaining operator moved to stage 3 https://github.com/tc39/proposal-optional-chaining

prettier already has support for it but on vscode still complains

![image](https://user-images.githubusercontent.com/968014/62046409-1f880080-b208-11e9-9f0f-6e1ae4201d9e.png)

Is this feature implemented on prettier-vscode? If yes how do I enable it?

I already setup my babel and eslint config.
And if I run eslint or prettier binary the test passes, but on vscode it shows the error

**Comment by ntotten** [comment]
This is an issue with VS Code itself, not this extension. It is tracked here: https://github.com/microsoft/TypeScript/issues/16

**Comment by VimLeSai** [comment]
when it will get resolved any ideas or any other options to fix this ?

**Comment by twoperkg** [comment]
While it is not implemented vscode U can install the extension [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Comment by jtswartz** [comment]
> While it is not implemented vscode U can install the extension [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
> Now I can use typescript 3.7 features in vscode

After trying to set `"typescript.validate.enable": false,` in config, your solution worked for my team. Cheers @twoperkg

**Comment by dhruska** [comment]
> > While it is not implemented vscode U can install the extension [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
> > Now I can use typescript 3.7 features in vscode
> 
> After trying to set `"typescript.validate.enable": false,` in config, your solution worked for my team. Cheers @twoperkg

This seems to remove the errors, but Prettier still doesn't work for me.

**Comment by ntotten** [comment]
As an update, Prettier and this extension does support this now. It will depend on VS Code though.

**Comment by VimLeSai** [comment]
see this,

https://code.visualstudio.com/updates/v1_41#_optional-chaining-support-for-javascript-and-typescript

![bitmoji](https://render.bitstrips.com/v2/cpanel/e3a9cd7f-e57e-4081-9c8c-44244c3fb11e-176c1d37-4013-4318-8546-8e1237a8fbf2-v1.png?transparent=1&palette=1&width=246)
