### ISSUE TITLE
How stop prettier wrapping lines

### ISSUE THREAD

**Issue by matanyacohen** [prettier/prettier-vscode#888]
I want manage line wrapping manually. How do that. for example I have follow declaration (TS):

let cols: Array<{ id: number; name: string; width: number; calc: boolean; }> = Array(
        { id: 0, name: "id", width: 23, calc: false },
        { id: 1, name: "name", width: 23, calc: false },
        { id: 1, name: "sum", width: 23, calc: true }
    );
 
I want formatted leave type declaration on one line and the object initialize with separate line for each, like it is. I expect formatter just fix the space and indentation.

**Comment by lneffa** [comment]
I'll add that for me your code wraps correctly in .tsx at least, but for a situation like below the wrapping is problematic:
I get the ending `>` removed when auto wrapped, causing type errors:
```
  const [serviceKeys, replacementIds] = React.useMemo<[string[], number[]]>(() => {
    let parentKeys: string[] = [];
    let childKeys: string[] = [];
    let sibKeys: string[] = []
```
Formats to this, no closing `>` before the `(() =>`:
```
  const [serviceKeys, replacementIds] = React.useMemo<
    [string[], number[]]
(() => {
    let parentKeys: string[] = [];
    let childKeys: string[] = [];
    let sibKeys: string[] = [];
``` 
VS Code Version 1.36.1 
Prettier Version: 1.9.0

**Comment by matanyacohen** [comment]
So prettier not have a option to ignore line break, and leave it as developer set it. No wrap nor unwrap? Did you have plan about it?

**Comment by kvskranthikumar** [comment]
Even I am looking where prettier to skip the line wrapping logic and perform rest of the formating.

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
