### ISSUE TITLE
Error with plugin JSDoc

### ISSUE THREAD

**Issue by t1ma** [prettier/prettier-vscode#889]
VSCode shows error when press "Code Formatter". I've tried delete node_modules and reinstall but it doesn't help.

My package.json has:
eslint - ^6.1.0
eslint-plugin-jsdoc - ^15.8.0

Error in console:

8/1/2019, 11:58:47 AM:
----------------------
Failed to load plugin 'jsdoc' declared in 'CLIOptions'/Users/user/Development/nodejs/tmp/models/task.js:: Cannot find module 'eslint-plugin-jsdoc'
Require stack:
- /__placeholder__.js

**Comment by ntotten** [comment]
Please provide a sample project for repro.
