### ISSUE TITLE
Different formatting with respect to prettier-eslint-cli for Typescript

### ISSUE THREAD

**Issue by julioolvr** [prettier/prettier-vscode#891]
Here's a repo reproducing this issue https://github.com/julioolvr/vscode-prettier-repro

Given this code, this is the way VScode with this plugin formats it:

```ts
function thisIsAFunction({
  thisIsAVeryLongArgumentName,
  thisIsAnEvenLongerArgumentName
}: {
thisIsAVeryLongArgumentName: number;
thisIsAnEvenLongerArgumentName: number;
}) {
  console.log(thisIsAVeryLongArgumentName);
  console.log(thisIsAnEvenLongerArgumentName);
}
```

Here's the output that `prettier-eslint-cli` generates (run `npm run prettier` in the given repo)

```ts
function thisIsAFunction({
  thisIsAVeryLongArgumentName,
  thisIsAnEvenLongerArgumentName
}: {
  thisIsAVeryLongArgumentName: number;
  thisIsAnEvenLongerArgumentName: number;
}) {
  console.log(thisIsAVeryLongArgumentName);
  console.log(thisIsAnEvenLongerArgumentName);
}
```

Notice the indentation in the type definition of the function argument. The eslint extension on vscode complains about it correctly. Relevant vscode config:

```json
{
  "prettier.eslintIntegration": true,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

Let me know if there's anything else you need from my side (or if you can't reproduce it, I couldn't find anything on my specific vscode config that causes this but maybe I'm missing something).

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
