### ISSUE TITLE
printWidth per language?

### ISSUE THREAD

**Issue by Peluko** [prettier/prettier-vscode#892]
Hello. Can the ```prettier.printWidth``` setting have a diferent value on a per language basis?

Regards.

**Comment by kachkaev** [comment]
https://prettier.io/docs/en/configuration.html#configuration-overrides

**Comment by Peluko** [comment]
I know this. I want a setting for this extension on VSCode. **For every file of the same language opened with VSCode.** If I wanted a setting for prettier itself I'd rather ask on prettier forums.

What I want to do is to format JSON without a ```printWidth``` (or with a ```printWidth``` of 10000) and keep the usual 80 or 100 for Typescript and Javascript. And keep it consistent through all the projects and isolated JSON files I have to maintain, without the need for a ```prettierrc``` and, if possible, that could be synced through VS Code Settings Sync. Maybe I've not made clear that I refer to ```prettier.printWidth``` available on ```settings.json```.

**Comment by ntotten** [comment]
For this, you'll want to use the prettier config. It is too difficult to maintain full configuration options duplicated in VS Code. That is why the plugin reads the prettier config by default. https://github.com/prettier/prettier-vscode#prettiers-settings
