### ISSUE TITLE
Anti-formatting blocks/regions

### ISSUE THREAD

**Issue by davwheat** [prettier/prettier-vscode#900]
**Is your feature request related to a problem? Please describe.**
Quite often, I need to add snippets of minified code from third parties for things like analytics, error reporting, etc. It's quite annoying having this minified, obfuscated rubbish clutter up 384 lines when I'm never going to have to do anything with it

**Describe the solution you'd like**
What I'd like to do is have a special piece of text that could be put in a comment to prevent formatting in that region.

**Describe alternatives you've considered**
I've thought about putting these minified code sections into a separate file, but I think that isn't great. Sometimes, splitting up sections of code from each other is a good idea but often these small pieces of code are designed to be loaded ASAP. In HTML, by being delivered with the rest of the page, it cuts down on requests back to the server which takes extra time and resources in a browser. Repeating these requests for thousands of clients and for tens or hundreds of files (if you're insane) just gets ridiculous.

I'm aware that VS Code may not support this. I am not totally sure about the way code formatting extensions work and whether they can fully access the content of a file (I'm assuming they do).

**Example**

```html
<html>
<head>
    <!--#prettier-no-format-->
    <script>
         function f(){console.log("example code i never have to look at and shouldn't be formatted into a 3000000 line mess");}
    </script>
    <!--#prettier-no-format-end-->
</head>
<body>
    <h1>Hello world!</h1>
</body>
</html>
```

**Comment by CiGit** [comment]
Seems you are looking for https://prettier.io/docs/en/ignore.html#html

**Comment by davwheat** [comment]
Why, yes. Yes, I am.

Couldn't find the right keywords to search for. Thanks!
