### ISSUE TITLE
Option to "force" formatting of a document

### ISSUE THREAD

**Issue by ithinkihaveacat** [prettier/prettier-vscode#907]
I have both the VS Code option "format and save" (`editor.formatOnSave`) and the Prettier option "require config" (`prettier.requireConfig`) turned on. This does what I want most of the time, but occasionally I want to "force" formatting of a file that otherwise wouldn't be reformatted. (Even if I explicitly select the "Format Document" option in the command menu, the document is not reformatted, because `prettier.requireConfig` "deactivates" it.)

I would like either:

- the "Format Document" option in VS Code to always apply formatting, irrespective of the value of `prettier.requireConfig` (this would be a breaking change since this can currently be a no-op)
- an additional option ("Force Document Format"?) that always applies formatting, even if `prettier.requireConfig` is true.

**Comment by ntotten** [comment]
Run the VS Code command `Format Document`.

**Comment by ithinkihaveacat** [comment]
@ntotten That doesn't work. I'm guessing VS Code does actually invoke prettier, but then prettier NOOPs due to `prettier.requireConfig` being true, and there being no config.

**Comment by ntotten** [comment]
Oh, I see what you’re saying. Why not add the config, but disable formatOnSave?

**Comment by ithinkihaveacat** [comment]
My use case is I have a number of projects that are set up "properly" with a prettier config, and with the files formatted by prettier. Projects in this state work great with both `formatOnSave` and `requireConfig` turned on.

However sometimes I open up a project that is not prettier-formatted, and I want to format one file in it that is particularly difficult to read, or I come across some random bit of minified CSS that I want to make readable via prettier. In these cases the only way to get prettier to do something is to temporarily set `requireConfig` to false and `formatOnSave` to true (i.e. invert both settings). In this case I want to be able to "force" formatting.

**Comment by ntotten** [comment]
I looked into this and thought about it a bit more. There really isn't any way to do this correctly without VS Code extending their APIs. The formatting providers are registered by an extension. If VS Code provided a command like "Format Document without Ignores" or something we could implement this, but otherwise it would be a whole lot of work to do so and probably behave differently than expected. So without support in VS Code's APIs I am not going to do this.

**Comment by ithinkihaveacat** [comment]
Thanks for considering this!
