### ISSUE TITLE
1.9 does not work, 1.8.1 does

### ISSUE THREAD

**Issue by arogg** [prettier/prettier-vscode#912]
### Summary

1.9 does not work, 1.8.1 does

### Steps To Reproduce:

run win 10 64 bit
make sure vs code is 1.37.1 (currently up to date latest version)
put this and ONLY this in settings:

>  "[typescript]": {
>     "editor.defaultFormatter": "esbenp.prettier-vscode"
>   },

install ONLY pretter 1.9 extension in vs code (currently latest version)
open a new folder, create ts file in it
restart vs code for good measure

now when i try to format code with prettier (context menu, format document) it always says "extensions pretter cannot format <file>.ts"

now downgrade pretter extension to 1.8.1 and reload vs window -> formatting works

### Expected result

formatting works

### Actual result

formatting does not work

**VS Code Version**:

 1.37.1

**Prettier & Prettier Plugin Version**:

1.9 (only prettier vs code extension installed, no npm stuff)

**OS and version**:

win 10 64bit

**Comment by ntotten** [comment]
Could you provide the output log of the extension?

**Comment by chevinbrown** [comment]
I have the same issue. I don't see any output in the console for `Prettier`...I get a message `There is no formatter for 'ruby'-files installed.`...

**Comment by chevinbrown** [comment]
I got this working, but I had to do some weird `cd ~/.vscode/extensions/... && npm i stuff`. I _did_ try reverting to 1.8.0 and didn't run into the same issues. If I can get some collaboration/advice, I'd be happy to dig deeper, but no-response bot kinda doused my desire to help.
