### ISSUE TITLE
Prettier ignores the traillingComma setting

### ISSUE THREAD

**Issue by Samuel-Martineau** [prettier/prettier-vscode#914]
### Summary

I'm trying to set the "prettier.trailingComma" to "all", but, even if I reload the window, Prettier still removes all the trailing commas.

### Steps To Reproduce:

1.  Set "prettier.trailingComma": "all" in settings.json
2.  Reload the window

### Expected result

I expect Prettier to add a trailing comma to this array [1,2,3].

### Actual result

Prettier doesn't add a trailing comma.

### Additional information
My Prettier config in setting.json
```json
"prettier.printWidth": 80,
"prettier.useTabs": false,
"prettier.semi": true,
"prettier.singleQuote": true,
"prettier.quoteProps": "consistent",
"prettier.bracketSpacing": true,
"prettier.arrowParens": "always",
"prettier.ignorePath": ".prettierignore",
"prettier.trailingComma": "all"
```
**VS Code Version**: 1.37.1

**Prettier & Prettier Plugin Version**:

**OS and version**: Darwin x64 18.7.0 (macOS Mojave v10.14.6)

**Comment by CiGit** [comment]
That's on purpose.
It's only for **multi-line** array / Object / parameters / arguments
[see playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAhgGgEabJgE0wF0BuAHSlXJABtoBzGzAAhvQCcP0BPZtkDAj8aAW3QBrOCJABLGDRaYaAd24AHGsRCYQEdTFnQAzslCcOEFQAVOCUynQA3CLII6Q2bmCkwAyuroYLJQDMgwHACucLoAFjCitADqsfJwxoFgcH728rJO8jzI4MamuiHGcBww1twM4sgAZui0lboAVsYAHgBC3r5+6KJwADIhcE0tbSCdXX4hDLRwAIqREPCTrTEggRyVHMXY6NhwtB7qlpVJGsUX6VVOE7oAjmvwtfoOIOjGALRQcDgBCBHg4cFesjBtXQ9XQm2mlVEsnCUW2xgWS1W6wmSGaW10MGOSTcMFiyAATATuLJaAsAMIQUQNRy0M66SKVAAqxwceOmFxCMGJBFJFIADABfCVAA)

**Comment by Samuel-Martineau** [comment]
Thank you
