### ISSUE TITLE
Prettier runs on cli but not in vs-code

### ISSUE THREAD

**Issue by eddysims** [prettier/prettier-vscode#915]
I am trying to use Prettier with https://www.npmjs.com/package/@wordpress/eslint-plugin and VsCode. However i am getting an error when trying to format on save.

running `npx prettier-eslint './**/*.js' --write` works. However the following gives an error

package.json
```
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@wordpress/eslint-plugin": "^2.4.0",
    "prettier-eslint": "^9.0.0",
    "prettier-eslint-cli": "^5.0.0"
  }
}
```

.eslintrc
```
{
    "extends": [ "plugin:@wordpress/eslint-plugin/recommended" ]
}
```

.vscode/settings.json
```
{
    "editor.formatOnSave": true,
    "prettier.eslintIntegration": true,
}
```

Error I'm receiving
```
Failed to load plugin 'jsx-a11y' declared in 'CLIOptions'/Users/***/***/***/src/index.js:: Cannot find module 'eslint-plugin-jsx-a11y'
Require stack:
- /__placeholder__.js
```

**Comment by bryanjhv** [comment]
Did you run `npm install`?

**Comment by ntotten** [comment]
Which version of the extension?

**Comment by ntotten** [comment]
Due to the huge amount of bugs, linting support has been removed in version 2.0.0. See the documentation on the recommended configuration: https://github.com/prettier/prettier-vscode#vscode-eslint-and-tslint-integration
