### ISSUE TITLE
Some Options Not Work in prettier-vscode With plugin-php

### ISSUE THREAD

**Issue by MarkSky** [prettier/prettier-vscode#916]
### Summary

"braceStyle" and "singleQuote" don't work for PHP files.

### Steps To Reproduce:

1.  Installing prettier-vscode to VSCODE.

2. Install @prettier/plugin-php in ~/.vscode/extensions/esbenp.prettier-vscode-1.9.0/

3. setting .prettierrc
```
{
    "printWidth": 120,
    "tabWidth": 4,
    "overrides": [
        {
            "files": "*.js",
            "options": {
                "arrowParens": "always",
                "endOfLine": "crlf",
                "singleQuote": true,
                "trailingComma": "all"
            }
        },
        {
            "files": "*.html",
            "options": {}
        },
        {
            "files": "*.css",
            "options": {
                "singleQuote": true,
                "trailingComma": "all"
            }
        },
        {
            "files": "*.scss",
            "options": {
                "singleQuote": true,
                "trailingComma": "all"
            }
        },
        {
            "files": "*.json",
            "options": {}
        },
        {
            "files": "*.php",
            "options": {
                "braceStyle": "psr-2",
                "singleQuote": false,
                "trailingCommaPHP": "php7.2"
            }
        }
    ]
}
```

### Expected result

```
<?php
function message($value = "")
{
    if ($value != "")
    {
        $js .= "alert(\"" . $value . "\");\r\n";

        echo $js;
    }

    exit();
}
?>
```

### Actual result

```
<?php
function message($value = '')
{
    if ($value != '') {
        $js .= "alert(\"" . $value . "\");\r\n";

        echo $js;
    }

    exit();
}
?>
```

### Additional information

**VS Code Version**: 1.37.1 (user setup)

**Prettier & Prettier Plugin Version**: 1.9.0

**OS and version**: Windows 10 Rro 1903

**Comment by MarkSky** [comment]
#prettier/plugin-php#1114

**Comment by ntotten** [comment]
1.9.0 doesn't support plugins. 1.10.0 was just released and should solve this. Please reopen if not.

**Comment by MarkSky** [comment]
After update to prettier-vscode 2.2.1, formatting doesn't work in php file.
Show I add other setting in prettier-vscode 2.2.1?

**Comment by MarkSky** [comment]
After installed @prettier/plugin-php and open a php project, I got an error in VSCode Developer Tool

> abstractExtensionService.ts:395 Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'resolve'.
_logMessageInConsole @ abstractExtensionService.ts:395

**Comment by MarkSky** [comment]
prettier/prettier-vscode#932
