### ISSUE TITLE
Avoid bundling test-fixtures in package

### ISSUE THREAD

**Issue by bryanjhv** [prettier/prettier-vscode#917]
**Is your feature request related to a problem? Please describe.**
Latest published version as of now (version 1.10.0) now bundles `test-fixtures` directory, which takes longer to download the extension (it's ~43MB now).

**Describe the solution you'd like**
Avoid bundling that folder into the extension package unless it is really needed for end users to have. I guess that's just used for development.

**Describe alternatives you've considered**
I guess doesn't apply.

**Additional context**
Update to 1.10.0 took a lot of time downloading (on a slow connection), which makes it somewhat frustrating. Also, disk space is now ~253MB for only this extension.

**Comment by ntotten** [comment]
Good catch. I renamed the folder and forgot to update the ignore. Fixed in 1.11.0.
