### ISSUE TITLE
Add troubleshooting & debugging in production instructions

### ISSUE THREAD

**Issue by jcrben** [prettier/prettier-vscode#919]
UPDATE: pretty sure I'm just hitting https://github.com/prettier/prettier-vscode/issues/919

For whatever reason, prettier works for most of my projects, but it isn't working in some JavaScript file that I've got in a specific project. It works in some other files (such as a json file). I can't figure out why. I've checked all the logs.

Before I make a bug report, I'd like to figure out how to run the extension from source in production and narrow it down to an actual error. I'm happy to step thru code or add some logs to figure out what's happening.

Unfortunately, https://github.com/prettier/prettier-vscode/blob/master/CONTRIBUTING.md does not explain how to do this, and https://stackoverflow.com/questions/39003860/how-can-i-debug-installed-vscode-extensions says that you can't debug installed extensions (?). So I would somehow have to move my project into the extension to debug it in an environment which replicates my situation?

I tried copying a non-packaged version of an extension into ~/.vscode/extensions to see if that made a difference and allows me to find it in the DevTools, but it didn't show up.

I'd rather not distract from this feature request with discussion of my bug, but I do see this in the console (altho again, it works for my json file):
![image](https://user-images.githubusercontent.com/5614134/63633262-62b47400-c5fa-11e9-96ed-2d4adda50f2a.png)

**Comment by jcrben** [comment]
I pulled this down and tried debugging it - I ran into this issue and couldn't stay in the Extension Development Host:
![image](https://user-images.githubusercontent.com/5614134/63634332-b1b5d580-c609-11e9-9628-90966e6ac711.png)

I also noticed https://github.com/prettier/prettier-vscode/blob/master/CONTRIBUTING.md is missing the `yarn` and `yarn compile` steps, will try to circle back around to those.

**Comment by ntotten** [comment]
This should be fixed in 1.12.0. Please reopen if you still see this.
