### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ScarletFlash** [prettier/prettier-vscode#929]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `2.2.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.0-insider`

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3540941/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by sarpik** [comment]
Same here.

- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `2.2.2`
- OS Version: `Linux x64 5.2.11-arch1-1-ARCH`
- VSCode version: `1.37.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 3420,
		"activateCallTime": 11,
		"activateResolvedTime": 239,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

---


```sh
$ code --version
1.37.1
f06011ac164ae4dc8e753a3fe7f9549844d15e35
x64

$ uname -a
Linux arch-usb 5.2.11-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 29 08:09:36 UTC 2019 x86_64 GNU/Linux
```

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-
vscode/files/3574189/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by sanbornJennifer** [comment]
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3617228/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by pmverma** [comment]
Same problem here.

**Comment by panyachu** [comment]
> * Issue Type: `Performance`
> * Extension Name: `prettier-vscode`
> * Extension Version: `2.2.1`
> * OS Version: `Windows_NT x64 10.0.18362`
> * VSCode version: `1.38.0-insider`
> 
> [esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3540941/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by panyachu** [comment]
* Issue Type: `Performance`
* Extension Name: `prettier-vscode`
* Extension Version: `2.2.2`
* OS Version: `Windows_NT x64 10.0.18362`
* VSCode version: `1.38.1 (user setup)`

[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3647324/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by ScarletFlash** [comment]
Reproduced again:
```
Version: 1.39.0-insider (system setup)
Commit: 695ee74864ef93d10f5de0861cb66af190e76211
Date: 2019-10-02T08:56:48.092Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by ntotten** [comment]
Many performance issues fixed in v3. I am going to close this for now, but please reopen if you see anything in the new version.
