### ISSUE TITLE
Format On Save not triggered when switching tabs and Auto Save set to onFocusChange

### ISSUE THREAD

**Issue by fabb** [prettier/prettier-vscode#930]
### Summary

Moved from VSCode issues: https://github.com/microsoft/vscode/issues/78605

Prettier formats normally, but when switching away from an unsaved editor with Ctrl + Tab, the file often is saved without being formatted.

### Steps To Reproduce:

1.  In settings, activate "Format On Save", and set "Auto Save" to "onFocusChange"
1. Install the Prettier extension (esbenp.prettier-vscode)
1. Open 2 editors, and in one (js/ts file) make some changes that are not pretty formatted
1. Switch editor tabs with Ctrl+Tab - very quickly, do not hold down Ctrl for too long

### Expected result

The file should be formatted with prettier and saved.

### Actual result

Very often, the file is saved as-is without being formatted. This happens every time in my big project, and less often in small test projects. It also does not happen when releasing Ctrl only a second later.

### Additional information

![](https://user-images.githubusercontent.com/153960/62758347-6e425f80-ba7e-11e9-9ee8-7823a0ac80a8.gif)

I could not reproduce the problem with the default formatter of VSCode.

**VS Code Version**:
1.36.1

**Prettier & Prettier Plugin Version**:
prettier: 1.18.2
prettier-vscode: 2.0.0

**OS and version**:
macOS 10.14.6 (18G87)

**Comment by ntotten** [comment]
I am unable to reproduce this with version 3.0.0 (preview) of prettier and VS Code version 1.39.2.

**Comment by fabb** [comment]
How can I install the preview version to check if the bug is also fixed for my projects?

**Comment by fabb** [comment]
Ok I managed to install the 3.0.2 extension from source.

Unfortunately the bug is still there:
![prettier-vscode-bug](https://user-images.githubusercontent.com/153960/67788000-caab8e80-fa71-11e9-99d2-2c9f0361cdf8.gif)

@ntotten can we reopen this issue?

**Comment by BOCbMOU** [comment]
Version 4.0.0, the bug is still exist.
