### ISSUE TITLE
prettier-stylelint or stylelint-prettier?

### ISSUE THREAD

**Issue by guoyunhe** [prettier/prettier-vscode#939]
I see in README and package.json it uses `prettier-stylelint` but this project isn't under `prettier` organization and it isn't updated for a long time.

Here is a `stylelint-prettier` under organization `prettier` and it is more up-to-date. Some people suggest to use `stylelint-prettier` instead of `prettier-stylelint`. I am confused...

**Comment by SharakPL** [comment]
`stylelint-prettier` is the one to use and to make it work you need `"prettier.stylelintIntegration": true,` in vscode settings. Even though it was depreciated by prettier it's still required to format code on save using stylelint configuration.
