### ISSUE TITLE
.editorconfig settings not respected

### ISSUE THREAD

**Issue by mastoj** [prettier/prettier-vscode#942]
### Summary

I have a repo with a .editorconfig file and not prettierrc file. I would expect "Format Document" to apply the rules I have in the editor config, but it seems like the .editorconfig file is ignored. The content of the editorconfig:

> root = true
> [*]
> charset = utf-8
> indent_size = 2
> indent_style = space
> end_of_line = lf
> insert_final_newline = true
> 
> [*.yml]
> indent_size = 2
> 

### Github Repository to Reproduce Issue
Private repsitory.

### Steps To Reproduce:

1. Install prettier and whatnot
2. Create a yml file
3. Create the editorconfig as above
4. Try formatting

### Expected result

I would expect the yml file to use 2 spaces as indentation.

### Actual result

.yml-file are using 4 spaces in the private repo I have.

### Additional information

![Screen Shot 2019-09-02 at 12 37 25](https://user-images.githubusercontent.com/501424/64108974-a0459980-cd7e-11e9-89e5-cb23bc25add8.png)

The screenshot above shows that the rainbow indentation plugin actually recognizes the 2 space tab

**VS Code Version**:

Version: 1.38.0-insider

**Prettier & Prettier Plugin Version**: 2.2.2

**OS and version**: OSX

**Comment by ntotten** [comment]
This is fixed in version 3.0.7 (in preview). You can install and test the preview version here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

Please note that we are using the prettier resolution for config files. The prettier config (i.e. `.prettierrc`) will override `.editorconfig` settings.
