### ISSUE TITLE
缺少operator-linebreak选项，无法设置“运算符处换行时，运算符必须在新行的行首”，希望添加

### ISSUE THREAD

**Issue by fengzhike** [prettier/prettier-vscode#943]
eslint中的“operator-linebreak”选项可以设置换行风格，prettier-vscode中没有对应的设置实现“把换行符放在操作符前面”的要求，建议添加feature

----
Google translate:

The "operator-linebreak" option in eslint can set the line break style. There is no corresponding setting in the prettier-vscode to implement the requirement of "put the newline character before the operator". It is recommended to add a feature.

**Comment by ntotten** [comment]
We don't explose settings of eslint. Use eslint config: https://eslint.org/docs/user-guide/configuring

**Comment by fengzhike** [comment]
There may be misunderstandings. I hope to provide a format scheme similar to the "operator-linebreak" option in eslint, instead of asking for eslint settings. It would be great if you could add operator landscaping schemes, such as:
form
`
let url =

            serverHost +

            '/v1/xxx/xx?fid=' +

            fid +

            '&width=' +

            w +

            '&height=' +

            h;
`
to
`
let url = serverHost

            + '/v1/disk/preview?fid='

            + fid

            + '&width='

            + w

            + '&height='

            + h;
`
