### ISSUE TITLE
prettier-ignore not being respected

### ISSUE THREAD

**Issue by willstocks** [prettier/prettier-vscode#946]
### Summary

I have a .js file that I have included the following that I want to keep on a single line and don't want the formatting messed with
```js
//prettier-ignore
if(document.getElementById("myelement")){/*goes off to create a new element*/}
```

However, on any paste or file save or typing (I have prettier set to format on all), VSCode Prettier is still formatting this JS and splitting it across lines, despite the fact I have instructed ignore.

For reference, I have my settings set to:
```json
  ...
 "editor.formatOnSave": true,
  "editor.formatOnType": true,
  "editor.formatOnPaste": true,  
  "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
  ...
```

### Github Repository to Reproduce Issue
N/A

### Steps To Reproduce:

1.  As above - I can supply a full line if required?

### Expected result

I'm instructing ignore, so prettier should not re-format?

### Actual result

Prettier reformats

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.37.1

**Prettier & Prettier Plugin Version**: 2.2.2

**OS and version**: Windows 10 Pro

**Comment by willstocks** [comment]
Note: it looks like "On Save" it might be being respected. "On Paste" and "On Type" it's definitely not though (although if I `ctrl`+`z` and carry on, it appears to be respected initially and then is not again)

**Comment by clockwood** [comment]
I just came across this issue but with HTML, using . On save it prettifies it no matter what.

**Comment by ntotten** [comment]
This seems to work as expected in version 3.0. We don't yet support format on type.

To try version 3.0 preview use this: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
