### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by TianbinTobin** [prettier/prettier-vscode#948]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `2.2.2`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 982,
		"activateCallTime": 0,
		"activateResolvedTime": 127,
		"activationEvent": "onLanguage:javascript"
	},
	"runtimeErrors": [
		{
			"name": "SyntaxError",
			"message": "Unexpected token, expected \",\" (74:14)"
		},
		{
			"name": "SyntaxError",
			"message": "Unexpected token, expected \",\" (77:14)"
		},
		{
			"name": "SyntaxError",
			"message": "Unexpected token (73:61)"
		},
		{
			"name": "SyntaxError",
			"message": "Unexpected token (73:62)"
		},
		{
			"name": "SyntaxError",
			"message": "Unexpected token (73:63)"
		},
		{
			"name": "SyntaxError",
			"message": "Unterminated string constant (73:65)"
		},
		{
			"name": "SyntaxError",
			"message": "Unexpected token (73:67)"
		},
		{
			"name": "SyntaxError",
			"message": "Unexpected token (73:68)"
		}
	]
}
```

**Comment by ntotten** [comment]
Unfortunately, this isn't enough info to reproduce. Please provide a sample github repo with full steps to reproduce the issue and reopen. Thanks.
