### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by peremuntaner** [prettier/prettier-vscode#949]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `2.2.2`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 11488,
		"activateCallTime": 174,
		"activateResolvedTime": 34,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

**Comment by ntotten** [comment]
We have done significant performance improvements in version 3.0. Please let me know if you still see issues in the latest preview release: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
