### ISSUE TITLE
Extension issue - code loading time

### ISSUE THREAD

**Issue by allwyndsouza** [prettier/prettier-vscode#951]
- Issue Type: `Bug`
- Extension Name: `prettier-vscode`
- Extension Version: `2.2.2`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 11404,
		"activateCallTime": 22,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

**Comment by ntotten** [comment]
We have done significant performance improvements in version 3.0. Please let me know if you still see issues in the latest preview release: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
