### ISSUE TITLE
Necessary trailing comma in generic type in .tsx file gets removed

### ISSUE THREAD

**Issue by sharno** [prettier/prettier-vscode#955]
### Summary

Trailing comma in this example `.tsx` file gets removed. The comma is necessary for the typescript compiler to recognize that it's a type not a JSX tag
```typescript
const f = <T, >() => 1
```
It seems to be not an issue in prettier itself

**VS Code Version**:
1.38.0

**Prettier & Prettier Plugin Version**:
2.2.2

**OS and version**:
Windows 10

**Comment by shiatsumat** [comment]
Since Prettier correctly handles necessary trailing commas if the file extension is `.tsx`, it seems that the information that VSCode gives to Prettier is insufficient.
See also https://github.com/prettier/prettier/issues/6302.

**Comment by ntotten** [comment]
Resolved in 035b4c48ec9494097ce54a647ea79e774735dfdd
