### ISSUE TITLE
No configuration provided for `filepath`.scss Prettier Doesn't format SCSS files

### ISSUE THREAD

**Issue by GeorgeWL** [prettier/prettier-vscode#957]
### Summary
_Short summary of what is going on or to provide context_.

No configuration provided for `filepath`.scss.

Prettier Doesn't format SCSS files.

### Steps To Reproduce:

1.  Have Prettier as Default Formatter for SCSS
1.  Use Format Document Hotkey
1.  Read Prettier Output in the Logs view of VS Code

### Expected result

SCSS file was Formatted without issue or and using the default config of prettier.

_Describe what should have happened_.

### Actual result

SCSS file was not formatted and stated that there was no config set.

_Describe what actually happened instead_.

### Additional information

Have tried a recommendation in another issue of uninstalling prettier, deleting the folder from the `{$home}/.vscode/extensions` folder, re-installing prettier, then reloading VS Code. This made no difference.

_Feel free to attach a screenshot_.

**VS Code Version**: 1.38.1

**Prettier & Prettier Plugin Version**: 
Prettier: 1.18.2
Prettier Extension: 2.2.2

**OS and version**:
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows 10 Pro x64, Version 1903, Build 18362.356

**Comment by rjb8682** [comment]
Currently experiencing this with vscode: `1.38.1`, prettier extension: `2.3.0`.

I do have a .prettierrc in my home folder and like above, works with JSON/TS files

**Comment by ntotten** [comment]
This should be working now with the change in 035b4c48ec9494097ce54a647ea79e774735dfdd. Will be releasing today.
