### ISSUE TITLE
Formatting HTML with too many slashes

### ISSUE THREAD

**Issue by linjialiang** [prettier/prettier-vscode#959]
> Formatting HTML with too many slashes：

![图片](https://user-images.githubusercontent.com/8848263/64915660-8a809d00-d79e-11e9-8f59-56192b3a9f04.png)

The w3c organization recommends formatting without closing tags

> The formatting should look like this：

![图片](https://user-images.githubusercontent.com/8848263/64915666-e77c5300-d79e-11e9-9668-a5f0629569ce.png)

**Comment by BPScott** [comment]
The extension formats code according to Prettier. Any formatting is down to that library if you wish to change it you should open an issue in https://github.com/prettier/prettier. However I'll warn you now that [they're against adding options](https://prettier.io/docs/en/option-philosophy.html) so I expect your request would be denied.

**Comment by linjialiang** [comment]
ok
