### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by muco-rolle** [prettier/prettier-vscode#960]
- Issue Type: `Performance`
- Extension Name: `prettier-vscode`
- Extension Version: `2.2.2`
- OS Version: `Linux x64 4.14.138-1-MANJARO`
- VSCode version: `1.31.1`

**Comment by kachkaev** [comment]
@muco-rolle please upgrade your VSCode. You are using `1.31.1`, which is a few months back from the today's  `1.38.1`.

**Comment by muco-rolle** [comment]
ok thank you
