### ISSUE TITLE
TabWidth from community plugin is ignored

### ISSUE THREAD

**Issue by Janther** [prettier/prettier-vscode#961]
### Summary

I'm contributing to a Prettier plugin for Solidity files.
In Solidity the `tabWidth` is 4 usually. Therefore it's been exported as the [default configuration](https://github.com/prettier-solidity/prettier-plugin-solidity/blob/master/src/options.js#L38) in our plugin.

`prettier-atom` respects this, however `prettier-vscode` is ignoring it and we are forced to use a `prettier.config.js` file for this.

### Github Repository to Reproduce Issue
Here is the example repo
https://github.com/Janther/tabWidth

### Steps To Reproduce:

1.  Have `prettier-vscode` installed and format on save configured.
1.  Install the [solidity language](https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity)
1.  Install the npm dependencies to use the solidity plugin.
1.  Open the `contracts/Migrations.sol` file.
1.  Save the file.

### Expected result

`tabWidth` should be 4.

### Actual result

`tabWidth` is 2.

### Additional information

This is the `prettier.config.js` file that has the default config for `prettier-plugin-solidity`.

```JavaScript
// https://prettier.io/docs/en/configuration.html
module.exports = {
  // Global configuration
  printWidth: 80,
  tabWidth: 4,
  useTabs: false,
  singleQuote: false,
  // Common configuration
  bracketSpacing: false,
  // Solidity configuration
  explicitTypes: "always"
};
```

**VS Code Version**: 1.38.1

**Prettier VSCode**: 2.2.2

**Prettier**: 1.18.2

**Prettier Plugin Solidity**: 1.0.0-alpha.32

**OS and version**: MacOS 10.14.6

**Comment by ntotten** [comment]
This should be fixed in version 3.0. Still in preview, but you can test it here: https://marketplace.visualstudio.com/items?itemName=prettier.prettier-vscode
