### ISSUE TITLE
`plugin-ruby` broken due to missing `./builders` file

### ISSUE THREAD

**Issue by gopeter** [prettier/prettier-vscode#964]
### Summary

I'm using `prettier` (1.18.2), `@prettier/plugin-ruby` (0.15.0) and `prettier-vscode` (2.2.2) together, but `@prettier/plugin-ruby` can't be loaded due to a missing `./builders` file: `Activating extension 'esbenp.prettier-vscode' failed: Cannot find module './builders'.`

This happens since version 0.12.3 of `@prettier/plugin-ruby`: https://github.com/prettier/plugin-ruby/commit/658b8d716b3da907755dd086b8f7c863aeb30c8c

But I'm not sure if it's the fault of `@prettier/plugin-ruby` or if `prettier-vscode` should be aware of it. It doesn't happen when using verison 0.12.2.

### Steps To Reproduce:

1.  Install `prettier-vscode`
1.  Create a new project and install `prettier` and `@prettier/plugin-ruby` (>= 0.12.3)

### Expected result

That the plugin loads correctly ...

### Actual result

... but the formatter can't be found and the developer tools show an error about a missing module

### Additional information

![image](https://user-images.githubusercontent.com/1242960/65413164-19ba3000-ddf1-11e9-91d5-71b2bddd882e.png)

**Comment by chevinbrown** [comment]
Related? 
https://github.com/prettier/prettier-vscode/issues/950
Adding `@prettier/plugin-ruby` to my devDependencies (`^0.15.0`) & prettier 2.3.0 fixed my issue.

**Comment by ntotten** [comment]
I cannot reproduce this in version 3.0 preview of the prettier plugin. 

Steps I followed:

```
mkdir prettier-ruby-test
cd prettier-ruby-test
npm init -y
npm i @prettier/plugin-ruby prettier -D
code .
```

Inside VS Code I created a `foo.rb` file, edited it and saved. Formatting worked correctly and gave this output:

```

[INFO - 9:34:42 AM] Formatting /Users/ntotten/dev/prettier-ruby-test/foo.rb.
[INFO - 9:34:42 AM] Loaded module 'prettier@1.18.2' from '/Users/ntotten/dev/prettier-ruby-test/node_modules/prettier/index.js'.
[INFO - 9:34:42 AM] Resolved ignore file to /Users/ntotten/dev/prettier-ruby-test/.prettierignore.
[INFO - 9:34:42 AM] File Info:
{
  "ignored": false,
  "inferredParser": "ruby"
}

[INFO - 9:34:42 AM] Prettier Options:
{
  "filepath": "/Users/ntotten/dev/prettier-ruby-test/foo.rb",
  "parser": "ruby"
}
```

Please try this out again with the 3.0 preview version: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode. Feel free to reopen if you still see the issue.

**Comment by gopeter** [comment]
Thank you very much, this works really well :-)
