### ISSUE TITLE
esbenp.prettier-vscode-unresponsive.cpuprofile 

### ISSUE THREAD

**Issue by solrevdev** [prettier/prettier-vscode#970]
### Summary

esbenp.prettier-vscode-unresponsive.cpuprofile.txt was created after vscode was unresponsive for a while.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Prettier & Prettier Plugin Version**:
latest?

**OS and version**:

Windows 10 1903 (18362.356)

**Comment by solrevdev** [comment]
[esbenp.prettier-vscode-unresponsive.cpuprofile.txt](https://github.com/prettier/prettier-vscode/files/3661979/esbenp.prettier-vscode-unresponsive.cpuprofile.txt)

**Comment by ntotten** [comment]
We have done significant performance improvements in version 3.0. Please let me know if you still see issues in the latest preview release: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode
