### ISSUE TITLE
Optional chaining not working in typescript file

### ISSUE THREAD

**Issue by Glinkis** [prettier/prettier-vscode#977]
### Summary

Optional chaining just landed in the typscript beta version, so this is more of a heads up than an actual unexpected problem.

### Steps To Reproduce:

1.  Create a typescript project.
2.  Use optional chaining.

### Expected result

The code should format without issues.

### Actual result

The code throws an error.

### Additional information

Error:
```
Expression expected.
  15 | 
  16 |   useLayoutEffect(() => {
> 17 |     ref.current?.scrollIntoView?.({
     |                 ^
  18 |         behavior: 'smooth',
  19 |         block: 'nearest',
  20 |       })
````

**VS Code Version**: 1.38.1

**Prettier & Prettier Plugin Version**: 1.18.2, 2.3.0

**OS and version**: Windows 10

**Comment by ntotten** [comment]
This is an issue in prettier itself, not the VS Code extension: https://github.com/prettier/prettier/issues/6595

**Comment by sunnylqm** [comment]
Prettier 1.19 published, please update. Thanks

**Comment by DavidBabel** [comment]
Same here !

Update is welcome
