### ISSUE TITLE
Strange syntax added after saving ---> {' '}

### ISSUE THREAD

**Issue by exocode** [prettier/prettier-vscode#984]
### Summary

After saving strange syntax is added: `{' '}`

### Steps To Reproduce:

1.  Install Extension
2.  Create a react app
3. place two components in one line
4. hit save (formatOnSave must be enabled):

`    <Row> <EmailConfirmationCard /> </Row>
`
### Expected result

(Not adding any code)
```
    <Row>
      <EmailConfirmationCard />{' '}
    </Row>
```

### Actual result
```
    <Row>
      {' '}
      <EmailConfirmationCard />{' '}
    </Row>
```
### Additional information

![2019-10-04 12 38 12](https://user-images.githubusercontent.com/1597621/66201541-e2c30480-e6a3-11e9-8bad-b714a34058d6.gif)

**VS Code Version**:
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Prettier & Prettier Plugin Version**:
Name: Prettier - Code formatter
Id: esbenp.prettier-vscode
Description: VS Code plugin for prettier/prettier
Version: 2.3.0
Publisher: Esben Petersen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
**OS and version**:
MacOS 10.14.6 (18G95)

**Comment by kachkaev** [comment]
This is expected behaviour of the current Prettier core. See details in https://github.com/prettier/prettier/issues/4223

VSCode extension is just a wrapper, which does not affect how the code gets formatted.
