### ISSUE TITLE
Why is prettier.eslintIntegration [_DEPRECTAED_]?

### ISSUE THREAD

**Issue by lambert-velir** [prettier/prettier-vscode#999]
I would like to format my code with prettier, then apply all eslint fixes.  Previously, this could be achieved by setting `prettier.eslintIntegration` to `true`. Now, the extension say that this option is [\_DEPRECTAED\_] and `prettier-eslint` should be used instead.  However, it's not clear how to use `prettier-eslint` in vscode.  

Why is `prettier.eslintIntegration` [\_DEPRECTAED\_] ?

What is the recommended way to run `prettier-eslint` on file save?

**Comment by ntotten** [comment]
See discussion in #958. For now, it continues to work as is.
